### ISSUE TITLE
Macsec flexCounters do not work for gbsyncd, and are processed by syncd

### ISSUE THREAD

**Issue by arpp93** [Azure/sonic-buildimage#10014]
#### Description
Currently the key ID for MACsec objects are written to flexcounter table consumed by syncd rather than gb_flexcounter table.
This leads to SAI stats call not being called in the correct container and the PHYs in gbsyncd catering to the MACsec are not able to provide the MACsec statistics.

#### Steps to reproduce the issue:
1. Configure macsec on an interface on a device running gbsyncd for phy requests.

#### Describe the results you received:
```
Jul 13 22:00:19.312125 localhost NOTICE swss#orchagent: :- createMACsecSA: MACsec SA Ethernet4:72101644409419332:2 is created.
Jul 13 22:00:19.312721 localhost ERR syncd#syncd: :- translateVidToRid: unable to get RID for VID oid:0x25c01000000003c
Jul 13 22:00:19.312787 localhost WARNING syncd#syncd: :- processFlexCounterEvent: port VID oid:0x25c01000000003c, was not found (probably port was removed/splitted) and will remove from counters now
Jul 13 22:00:19.312787 localhost WARNING syncd#syncd: :- removeMACsecSA: Trying to remove nonexisting MACsec SA oid:0x25c01000000003c
Jul 13 22:00:19.312957 localhost WARNING swss#orchagent: :- wait: got not expected response: :
Jul 13 22:00:19.313420 localhost ERR gbsyncd#GBSAI[20]: :- processFlexCounterEvent: Failed to parse the key

```
The syncd is trying to process the flexCounter event for a SA which exists in gbsyncd.

#### Describe the results you expected:
gbsyncd should be the one processing this event.

#### Output of `show version`:

Fixes of :
https://github.com/Azure/sonic-sairedis/pull/892
https://github.com/Azure/sonic-swss/pull/1867
are integrated in the test image.

**Comment by zhangyanzhao** [comment]
Ze Gan will take a look.

**Comment by jimmyzhai** [comment]
The issue had been fixed by https://github.com/Azure/sonic-swss/pull/2218.
