### ISSUE TITLE
[sonic-cfg]: Vlan names from the minigraph could be incompatible with SONiC Vlan interfaces naming schema

### ISSUE THREAD

**Issue by pavel-shirshov** [Azure/sonic-buildimage#1003]
SONiC supports Vlan interface names in format "Vlan"+dot1Q tag.
So, usually SONiC vlan names are: Vlan1 (for vlan tag 1), Vlan10 (for vlan tag 10) and so on.
Currently sonic-cfg takes a Vlan interface names from the minigraph VlanInterface["Name"] field. But it can contains a vlan name in incompatible format, like "Computers".
So right way to create a vlan name is to use "Vlan" + VlanInterface['Tag"].

**Comment by taoyl-ms** [comment]
Solved in https://github.com/Azure/sonic-buildimage/pull/695.
