### ISSUE TITLE
Image build should fail if debian packages or python wheels fail to install

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#1012]
Take this issue, for instance: https://github.com/Azure/SONiC/issues/113

In this case, the sonic-utilities package fails to get installed due to dependency issues, however, the image build continues and "succeeds" even though the image doesn't contain the necessary sonic-utilities package.

We need a solution to cause the image build to fail in error in instances such as this.

**Comment by stcheng** [comment]
one side effect caused by this is that the `sonic_installer` is not correctly installed. Ansible will not be able to upgrade this system automatically.

**Comment by lguohan** [comment]
add -e in the build_debian.sh and extension.sh and check.

**Comment by qiluo-msft** [comment]
This issue should be there anymore.
