### ISSUE TITLE
[yang] Need Yang for BGP_INTERNAL_NEIGHBOR table

### ISSUE THREAD

**Issue by ganglyu** [Azure/sonic-buildimage#10157]
#### Description

We don't have yang model about BGP_INTERNAL_NEIGHBOR table.
Please refer to https://github.com/Azure/sonic-utilities/issues/2029

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ganglyu** [comment]
@jmmikkel Can you add Yang for BGP_INTERNAL_NEIGHBOR table?

**Comment by jmmikkel** [comment]
I had nothing to do with this table. If you are going to dig up the people who originally added the tables, this needs someone else.
