### ISSUE TITLE
Can't download VS build per wiki instructions

### ISSUE THREAD

**Issue by iancote** [Azure/sonic-buildimage#10223]
#### Description
Hopefully I'm just missing something.  I'm trying to follow the instructions from https://github.com/Azure/SONiC/wiki/SONiC-on-virtual-machine-for-Windows to download a VS image to use for testing.  When I try to follow the link https://sonic-build.azurewebsites.net/ui/sonic/pipelines/142/builds/49244/artifacts/94210?branchName=master&artifactName=sonic-buildimage.vs it just times out.  I have tried to follow the path through the pipeline but I can't find any artifacts.

#### Steps to reproduce the issue:
1. Follow wiki steps.  Try to follow sonic-buildimage.vs link
2. Eventually gets a 500 error waiting on api.github.com

#### Describe the results you received:
500 Error - The request timed out

#### Describe the results you expected:
Page would open as described in the instructions and I could download the target/sonic-vs.img.gz file

#### Output of `show version`:

```
NA
```
#### Output of `show techsupport`:

```
NA
```

**Comment by prsunny** [comment]
Please try with this - https://sonic-build.azurewebsites.net/ui/sonic/pipelines
