### ISSUE TITLE
 eth0 can't be pinged on the same subnet

### ISSUE THREAD

**Issue by tieguoevan** [Azure/sonic-buildimage#1023]
**Description**

eth0 can't be pinged on the same subnet

The reason is that there is no connected routing in interfaces.j2

**Steps to reproduce the issue:**
1. eth0 configured as 10.65.254.240/24
2. Connected device failed to ping from 10.65.254.222 to 10.65.254.240

**Comment by stcheng** [comment]
could you provide the output of `ip route show`?

**Comment by tieguoevan** [comment]
```
root@str-s8900-54xc-01:/home/admin# ip route
10.0.0.56/31 dev PortChannel01  proto kernel  scope link  src 10.0.0.56
10.0.0.58/31 dev PortChannel02  proto kernel  scope link  src 10.0.0.58
10.0.0.60/31 dev PortChannel03  proto kernel  scope link  src 10.0.0.60
10.0.0.62/31 dev PortChannel04  proto kernel  scope link  src 10.0.0.62
10.65.230.0/24 dev eth0  proto kernel  scope link  src 10.65.230.240
240.127.1.0/24 dev docker0  proto kernel  scope link  src 240.127.1.1
```

I think the problem is this line in interfaces.j2
https://github.com/Azure/sonic-buildimage/blob/e27fd4648958633bef45523e09486a9b790fec31/files/image_config/interfaces/interfaces.j2#L30
configure a default route and its nexthop is the gataway. But in our environment, there is no gateway.
We add line to fix this problem locally.
`up ip {{ '-4' if prefix | ipv4 else '-6' }} route add {{ prefix | network }}/{{ prefix | prefixlen }} dev eth0 table default`

**Comment by stcheng** [comment]
correct me if i'm wrong, if the eth0 is configured with 10.65.254.240/24, will this route to the subnet be added automatically in the kernel?

**Comment by lguohan** [comment]
yes, this is a bug. The reason is that we are using the route table default to route the packet when source IP is the management IP. Check below. We need to add the subnet route to the table default.

```
admin@str-a7050-acs-1:~$ ip rule   
0:      from all lookup local 
32764:  from all to 10.20.6.16 lookup default 
32765:  from 10.3.147.241 lookup default 
32766:  from all lookup main 
32767:  from all lookup default 
admin@str-a7050-acs-1:~$ ip route show table default
default via 10.3.146.1 dev eth0 
```

**Comment by prsunny** [comment]
PR raised - https://github.com/Azure/sonic-buildimage/pull/1142
