### ISSUE TITLE
[vstest]Remove config calls from test_nat.py in swss vs tests

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#10244]
#### Description

As a part of ongoing effort to  decouple vstests from sonic-utilities, the click commands called in vs tests should be modified to redis-CLI based config_db set.
This is to remove vs tests from running in sonic-utilities pipeline checkers 

Example of existing command in test_nat:
https://github.com/Azure/sonic-swss/blob/00266891a9f41e5bd37100b05237e865cde429b2/tests/test_nat.py#L36 

Example of how to migrate:
https://github.com/Azure/sonic-swss/pull/2179

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by dgsudharsan** [comment]
@AkhileshSamineni  @adyeung Can you please look into this?

**Comment by dgsudharsan** [comment]
@Praveen-Brcm @adyeung Can you please look into this?

**Comment by AkhileshSamineni** [comment]
@dgsudharsan Fix this one, PR link is https://github.com/Azure/sonic-swss/pull/2278
