### ISSUE TITLE
[chassis][VoQ] No support for recycle port in minigraph

### ISSUE THREAD

**Issue by sanmalho-git** [Azure/sonic-buildimage#10282]
#### Description
In a T2 VoQ chassis, there are two pseudo ports per asic - Inband and Recycle. In the port_config.ini, these ports are listed as:
```
# name         lanes                               alias            index  asic_port_name role  speed    coreid  coreportid  numvoq
...
Ethernet-IB0   115                                 Ethernet-IB0     37     Rcy1-ASIC0     Inb   10000    0       19          8
Ethernet-Rec0  116                                 Ethernet-Rec0    39     Rcy2-ASIC0     Rec   10000    1       20          8

```

For inband ports, there is a  'VoqInbandInterfaces' metadata defined in the minigraph.

```
      <VoqInbandInterfaces xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.Search.Autopilot.Evolution">
        <a:VoqInbandInterface>
          <Name>Ethernet-IB0</Name>
          <Type>port</Type>
          <a:PrefixStr>3.3.3.4/32</a:PrefixStr>
        </a:VoqInbandInterface>
        <a:VoqInbandInterface>
          <Name>Ethernet-IB0</Name>
          <Type>port</Type>
          <a:PrefixStr>3333::3:4/128</a:PrefixStr>
        </a:VoqInbandInterface>
      </VoqInbandInterfaces>
```

In [minigraph.py ](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/minigraph.py) that parses the minigraph.xml file, we have code to parse the VoqInbandInterfaces metadata, and [admin enable them](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/minigraph.py#L1521).

However, there is no metadata defined for the other recycle port (with role as 'Rec') and no corresponding parsing and enabling of these ports in [minigraph.py ](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/minigraph.py). Thus when we load the minigraph, the inband port is admin enabled and operationally up, but the recycle port is admin disabled and operationally down.

#### Steps to reproduce the issue:
1. generate minigraph.xml for a T2 VoQ linecard that has both inband and recycle port defined
2. config load_minigraph -y

#### Describe the results you received:
The recycle port is admin down and operationally down
```
admin@board3:/usr/local/lib/python3.9/dist-packages$ show interface status
     Interface                            Lanes    Speed    MTU    FEC          Alias            Vlan    Oper    Admin                                             Type    Asym PFC
--------------  -------------------------------  -------  -----  -----  -------------  --------------  ------  -------  -----------------------------------------------  ----------
.
.
.
  Ethernet-IB0                              115      10G   9100    N/A   Ethernet-IB0          routed      up       up                                              N/A         off
 Ethernet-Rec0                              116      10G   9100    N/A  Ethernet-Rec0          routed    down     down                                              N/A         off

```

#### Describe the results you expected:
Expect the recycle port to be admin and operationally up

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@rlhui can you please help to triage during Chassis meeting? Thanks.

**Comment by sanmalho-git** [comment]
Issue is fixed with latest code - Recycle ports are admin enabled and are operationally up in a T2 chassis.
