### ISSUE TITLE
Orchagent export platform is empty

### ISSUE THREAD

**Issue by sihuihan88** [Azure/sonic-buildimage#1031]
**Description**
In dockers/docker-orchagent/orchagent.sh
export platform=`sonic-cfggen -v onie_switch_asic` is not working on broadcom platform

**Steps to reproduce the issue:**
1. Run the command 
sonic:~$ sonic-cfggen -v onie_switch_asic

sonic:~$

**Describe the results you received:**
Empty

**Describe the results you expected:**
broadcom related key words

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stcheng** [comment]
i've created this pull request: https://github.com/Azure/sonic-buildimage/pull/1030

**Comment by lguohan** [comment]
is this issue resolved?

**Comment by stcheng** [comment]
resolved
