### ISSUE TITLE
Yang validation fails when Buffer profiles are configured with "NULL" values

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#10342]
#### Description
Below is the sample buffer configuration. In dynamic buffer model, "NULL" is a legal value but yang model check doesn't tolerance it.

Failed to install p4-examples=1.0.1-8: Failed to install p4-examples: Data Loading Failed
Leafref "/sonic-buffer-profile:sonic-buffer-profile/sonic-buffer-profile:BUFFER_PROFILE/sonic-buffer-profile:BUFFER_PROFILE_LIST/sonic-buffer-profile:name" of value "NULL" points to a non-existing leaf. 

    "BUFFER_PG": {
        "Ethernet0|0": {
            "profile": "ingress_lossy_profile"
        },
        "Ethernet0|3-4": {
            "profile": "NULL"
        }
}

Issue is from the below yang model where the value can be only a leafref and so having NULL fails. We also need to check other yang models where buffer profile can be NULL 

https://github.com/Azure/sonic-buildimage/blob/7eb321c376fd1fcdbc67462185b8d4a7cff5f76f/src/sonic-yang-models/yang-models/sonic-buffer-pg.yang#L58

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@adyeung Adam, can you please help to find someone in BRCM to take a look? Thanks.

**Comment by adyeung** [comment]
@AmitKaushik7 Amit from BRCM will followup

**Comment by AmitKaushik7** [comment]
Raised a PR #10353 [Allow NULL Buffer Profile in buffer pg/queue yang files for Dynamic Buffer Model ] for this issue.
