### ISSUE TITLE
[yang] Invalid asn number

### ISSUE THREAD

**Issue by ganglyu** [Azure/sonic-buildimage#10363]
#### Description

radv-test-sample-graph.xml, sample-graph-resource-type.xml, sample-graph-subintf.xml, simple-sample-graph.xml and t0-sample-graph.xml are using 0 as bgp asn number, can not pass yang validation.

#### Steps to reproduce the issue:
1. Run yang validation, follow https://github.com/Azure/sonic-buildimage/pull/9700
2. Just check xml can find invalid asn number.

#### Describe the results you received:
bgp asn is 0.

#### Describe the results you expected:
bgp asn can not be 0.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@ganglyu will you take care of this issue or you need some help from community?

**Comment by qiluo-msft** [comment]
@ganglyu If we added a dummy ASN in xml files, will it work?
