### ISSUE TITLE
[VNET]Removing Vnet with scope default results in SAI VRF delete failure due to references not removed.

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#10412]
#### Description

When Vnet object with scope default is deleted, the removal of the VRF in SAI fails. With default scope both overlay routes and regular routes get created with the VRF associated with VNET. After Overlay routes are removed, when VNET is deleted during the tests, it fails with the below logs

 Mar 29 18:18:23.508200 r-tigon-11 ERR swss#orchagent: :- meta_generic_validation_remove: object 0x3000000000002 reference count is 13028, can't remove
Mar 29 18:18:23.508200 r-tigon-11 ERR swss#orchagent: :- ~VNetVrfObject: Failed to remove virtual router name: Vnet_v4_in_v6-0, rv:-17

In T1 topology apart from Overlay routes used for tests, there are 6.5 K IPv4 routes and 6.5 IPv6 routes. These routes underlying use the same VRF as used by VNET which results in error logs when this VRF is removed.

#### Steps to reproduce the issue:
1. Create VNET with default scope
2. Add overlay as well as regular routes.
3. Remove overlay routes. Remove VNET.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by liat-grozovik** [comment]
@sumukhatv can you please confirm sonic-buildimage master has the fix already? do you have an intention to backport it to any other sonic branches? if so can you share your view on that

**Comment by prsunny** [comment]
This should be available as part of https://github.com/Azure/sonic-buildimage/pull/10803
