### ISSUE TITLE
bgpcfgd is not handling BGP_PEER_RANGE table change

### ISSUE THREAD

**Issue by taoyl-ms** [Azure/sonic-buildimage#1051]

**Comment by stcheng** [comment]
`bgpcfgd: [bgp cfgd] command execution returned 1. Command: "vtysh -c 'configure terminal' -c 'router bgp 66666' -c 'neighbor 10.11.12.13 remote-as 0'", stdout: "% Unknown command.#012"`

**Comment by taoyl-ms** [comment]
#1060 will suppress the error message. Proper implementation of BGP_PEER_RANGE dynamic configuration support will come later.

**Comment by pavel-shirshov** [comment]
Closing this as we don't; need this enhancement right now.
