### ISSUE TITLE
readis-cli: set app db ,but no change to asic db

### ISSUE THREAD

**Issue by zhuzhuzhu23** [Azure/sonic-buildimage#1067]
app db:
127.0.0.1:6379> hgetall "NEIGH_TABLE:Ethernet0:10.0.0.1"
1) "neigh"
2)  "00:01:04:4C:49:F6"
3) "family"
4) "IPv4"

I deleted field "neigh".
127.0.0.1:6379> hgetall "NEIGH_TABLE:Ethernet0:10.0.0.1"
1) "family"
2) "IPv4"

and I queried asic db.But，not change to this key。
127.0.0.1:6379[1]> hgetall "ASIC_STATE:SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{\"ip\":\"10.0.0.1\",\"rif\":\"oid:0x6000000000135\"}"
1) "SAI_NEIGHBOR_ATTR_DST_MAC_ADDRESS"
2) "00:01:04:4C:49:F6"

So do I have a problem with my operation?  And I want to know how to look up with log of app db and asic db.

Thank you.

**Comment by qiluo-msft** [comment]
Hi @zhuzhuzhu23, you are not supposed to manipulate ApplDB contents directly. Roughly speaking, applications use ApplDB to interprocess communication. The providers are using ProducerStateTable, and the consumer (orchagent) is using ConsuerStateTable. The table you saw is manipulated by ConsuerStateTable after popping the data from the queue, and it is for state saving purpose only.

**Comment by qiluo-msft** [comment]
There is no specific log related to your ask. You need to check related components logs to know what happens. In your case, there is no components involved.
