### ISSUE TITLE
[mirroring] Queue value 0 is missing after validation in config mirror-session command

### ISSUE THREAD

**Issue by arfeigin** [Azure/sonic-buildimage#10795]
#### Description
When adding new mirror session with queue value = 0, it is not entered to the config DB and won't show when printing the current mirror sessions.
The issue is found on master/202111/202012 branches, however it works correctly on 202106 branch.
I explored it a bit and the issue was introduced after PR [#1825](https://github.com/Azure/sonic-utilities/pull/1825).

#### Steps to reproduce the issue:
Run the following commands:
1. sudo config mirror_session erspan add ERSPAN2 100.0.0.1 100.0.0.2 0 11 35145 0 Ethernet0 rx
2. show mirror_session

#### Describe the results you received:
Queue value is empty:
![image](https://user-images.githubusercontent.com/101218333/167591810-88f72bc4-67b5-4870-81f4-9af3fa6374f2.png)

#### Describe the results you expected:
(202106 SONiC build)
![image](https://user-images.githubusercontent.com/101218333/167596436-257e94cf-b6a6-444d-9191-8b84f2249ddd.png)

#### Output of `show version`:
![image](https://user-images.githubusercontent.com/101218333/167591600-6a38ab41-0264-4f75-b3a9-f0a5634650c5.png)

#### Additional information you deem important (e.g. issue happens only occasionally):

![image](https://user-images.githubusercontent.com/101218333/167580199-3d65bef6-e5ee-4286-960b-064416170d63.png)
It looks like the issue can be solved by either omitting ‘type=QUEUE_RANGE’ but this way the queue value won't be validated, or keep the validation in place and change the condition check to: ‘if queue >= 0:’.
Both options solve the issue.

**Comment by bingwang-ms** [comment]
Will take a look. Thanks for the great finding.

**Comment by bingwang-ms** [comment]
PR raised to fix the issue https://github.com/Azure/sonic-utilities/pull/2162. Please help take a look. Thanks

**Comment by arfeigin** [comment]
> Will take a look. Thanks for the great finding.

You welcome!

**Comment by arfeigin** [comment]
> PR raised to fix the issue [Azure/sonic-utilities#2162](https://github.com/Azure/sonic-utilities/pull/2162). Please help take a look. Thanks

Thanks for the quick fix!
