### ISSUE TITLE
Force10-S6000 cannot pass memory exhaustion test case

### ISSUE THREAD

**Issue by lizhijianrd** [Azure/sonic-buildimage#10921]
#### Description

DUT `Force10-S6000` failed on test case `platform_tests.test_memory_exhaustion`. The test result is:

```
Failed: Not all critical processes are healthy
```

After the DUT trigger OOM and reboot, the process `orchagent` in docker container `swss` is gone. Then the critical processes check failed.

#### Steps to reproduce the issue:

Use the following commands to run test case `platform_tests.test_memory_exhaustion`:

```
cd ~/repos/sonic-mgmt/tests
./run_tests.sh -i ../ansible/str,../ansible/veos \
        -n "<testbed-name>" \
        -u -m individual \
        -c "platform_tests/test_memory_exhaustion.py" \
        -e "--skip_sanity"
```

**Comment by zhangyanzhao** [comment]
@Blueve can you please help to take a first look? Check with Ying if you need help. Thanks.

**Comment by lizhijianrd** [comment]
We found it only fails on a specific device, maybe due to some hardware failure. So I'll close this issue.
