### ISSUE TITLE
How to add a job in jenkins for ASIC Nephos?

### ISSUE THREAD

**Issue by kaiyu22** [Azure/sonic-buildimage#1109]
**Description**
There is an ASIC vendor Nephos joined SONiC, and how to add a job in jenkins for Nephos in READMD.md? The result is like the below picture. (if Nephos add successful, it will be showed as well)

PS: The version of READMD.md is **201709 branch**

![image](https://user-images.githubusercontent.com/10461485/32359049-bb7c4ce2-c085-11e7-980f-faf723faefe9.png)

**Comment by lguohan** [comment]
added
