### ISSUE TITLE
Support for mlnx_x86?

### ISSUE THREAD

**Issue by byronyi** [Azure/sonic-buildimage#1115]
It seems the latest [mlnx_x86-r5.0.1410](http://switchdev.mellanox.com/onie/) is not supported as listed in here:

https://github.com/Azure/sonic-buildimage/tree/master/device/mellanox

And various commands fail as the platform is not well supported:

```
$ show platform syseeprom
Command: sudo decode-syseeprom
/usr/bin/decode-syseeprom : ERROR : cannot load module: /usr/share/sonic/device/x86_64-mlnx_x86-r5.0.1410/plugins/eeprom.py
```

**Comment by lguohan** [comment]
please upgrade to new onie
