### ISSUE TITLE
[sfputil] device fails to run command "sfputil show eeprom"

### ISSUE THREAD

**Issue by romanvasylys** [Azure/sonic-buildimage#11300]
**Description**
Whilst trying to run `sudo sfputil show eeprom` command, device fails with KeyError when it's trying to get `supported_max_laser_freq`. Instead of eeprom, it outputs error traceback. Device fails to take facts from [QSFP_DD_DATA_MAP](https://github.com/Azure/sonic-utilities/blame/8dee36cb826eb07948c04083ed4e3b074fc27c57/sfputil/main.py#L104), which was added only [on May 10th, 2022](https://github.com/Azure/sonic-utilities/commit/083ebcc3369eb893e77bcdbbcbc162ddf14762ef). There seems to be no MemMap for `supported_max_laser_freq` or `supported_min_laser_freq` on [XcvrMemMap](https://github.com/Azure/sonic-platform-common/blob/f575a401b83bbd5d6b6d68824ff22eae8647be16/sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py)

**Steps to reproduce the issue:**
Run `sudo sfputil show eeprom` command on DUT.

**Describe the results you received:**
```
~$ sudo sfputil show eeprom
Traceback (most recent call last):
File "/usr/local/bin/sfputil", line 8, in
sys.exit(cli())
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in _call_
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 669, in eeprom
output += convert_sfp_info_to_output_string(xcvr_info)
File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 348, in convert_sfp_info_to_output_string
output += '{}{}: {}GHz\n'.format(indent, QSFP_DD_DATA_MAP[key], sfp_info_dict[key])
KeyError: 'supported_max_laser_freq'
```

**Describe the results you expected:**
`sudo sfputil show eeprom` command should output SFP eeprom facts on ports

**Output of `show version`:**
SONiC Software Version: SONiC.master.0-dirty-20220629.144834
Distribution: Debian 11.3
Kernel: 5.10.0-12-2-amd64
Build commit: 89020f53e
Build date: Wed Jun 29 15:31:38 UTC 2022
Built by: user@sonic-ct4-server

Platform: x86_64-accton_as9516_32d-r0
HwSKU: newport

**Additional information you deem important**
There is try-except case for missing facts on sfp_info_dict, but it is out of reach for laser_freq and tx_power keys. My suggestion is to enlarge try-except case in [sfputil method convert_sfp_info_to_output_string](https://github.com/Azure/sonic-utilities/blob/master/sfputil/main.py#L344), so the missing information will show N/A, instead of causing an error:
```
    if sfp_type.startswith('QSFP-DD') or sfp_type.startswith('OSFP'):
        sorted_qsfp_data_map_keys = sorted(QSFP_DD_DATA_MAP, key=QSFP_DD_DATA_MAP.get)
        for key in sorted_qsfp_data_map_keys:
            try:
                if key == 'cable_type':
                    output += '{}{}: {}\n'.format(indent, sfp_info_dict['cable_type'], sfp_info_dict['cable_length'])
                elif key == 'cable_length':
                    pass
                elif key == 'supported_max_tx_power' or key == 'supported_min_tx_power':
                    if key in sfp_info_dict:  # C-CMIS compliant / coherent modules
                        output += '{}{}: {}dBm\n'.format(indent, QSFP_DD_DATA_MAP[key], sfp_info_dict[key])
                elif key == 'supported_max_laser_freq' or key == 'supported_min_laser_freq':
                    if key in sfp_info_dict:  # C-CMIS compliant / coherent modules
                        output += '{}{}: {}GHz\n'.format(indent, QSFP_DD_DATA_MAP[key], sfp_info_dict[key])
                else:
                    output += '{}{}: {}\n'.format(indent, QSFP_DD_DATA_MAP[key], sfp_info_dict[key])
            except (KeyError, ValueError) as e:
                output += '{}{}: N/A\n'.format(indent, QSFP_DD_DATA_MAP[key])
```

**Comment by qinchuanares** [comment]
@romanvasylys what is the module type you use when encountering this issue? I would like to reproduce the issue.

**Comment by prgeor** [comment]
Please use the lastest master. Submodule is now updated.
