### ISSUE TITLE
Impossible to build platform independent docker container

### ISSUE THREAD

**Issue by pavel-shirshov** [Azure/sonic-buildimage#120]
From the documentation:

> Usage
> 
> To build NOS installer image and docker images, run command line
> 
> make configure PLATFORM=[VENDOR]
> 
> 

What if we build a docker container which doesn't depend on the platform?

**Comment by stcheng** [comment]
this issue needs to be resolved
the current solution is to build all dockers using vendor=mellanox
the generic dockers then could be used on the other platforms

**Comment by oleksandrivantsiv** [comment]
This issue is resolved in singe image RP https://github.com/Azure/sonic-buildimage/pull/215
