### ISSUE TITLE
Not able build P4 sonic image..

### ISSUE THREAD

**Issue by rockamble** [Azure/sonic-buildimage#1252]
Hi Team,

I am trying to build sonic P4 image but after giving make, it is getting stuck. 
This is first build, so it will take long time but I waited for entire night, but still stuck at same place .. 
Can anyone please help with this error ? 

l**abuser@labuser:/home/rohit/sonic-buildimage$ sudo make
SONiC Build System

Build Configuration
"CONFIGURED_PLATFORM"             : "p4"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_CONFIG_BUILD_JOBS"         : "1"
"SONIC_CONFIG_MAKE_JOBS"          : "4"
"DEFAULT_USERNAME"                : "admin"
"DEFAULT_PASSWORD"                : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : ""
"SONIC_CONFIG_DEBUG"              : ""
"ROUTING_STACK"                   : "quagga"
"ENABLE_SYNCD_RPC"                : ""
"ENABLE_ORGANIZATION_EXTENSIONS"  : "y"
"PLATFORM"                        : ""
"PLATFORM_PATH"                   : "platform/p4"

lockfile: Try praying, giving up on ".screen"
[ 01 ] [ target/debs/redis-tools_3.2.4-1~bpo8+1_amd64.deb ]**

**Comment by CurryPeng** [comment]
I made target for p4 docker image by using #sudo make target/docker-sonic-p4.gz for the first time,  and some errors occured as well , but not stuck at your issue point. It took perhaps 15 mins from  the first [01] log show to errors appeared.
...
[01] [target/debs/libthrift-0.9.3_0.9.3-2_amd64.deb]
[01] [target/debs/sai-p4-bm_1.0.0_amd64.deb]
[01] [target/debs/p4-sai-adapter_0.1-0_amd64.deb]
[01] [target/debs/libsairedis_1.0.0_amd64.deb]
[01] [target/debs/libteam5_1.26-1_amd64.deb]

slave.mk:339 recipe for target 'docker-start' failed
make: *** [docker-start] Error 1
makefile:71 recipe for target 'target/docker-sonic-p4.gz' failed
make: *** [target/docker-sonic-p4.gz] Error 2

Can anyone please help this issue also, thanks!

**Comment by CurryPeng** [comment]
The issue was resolved, one debian package update failed when compiling src, network issue caused remote site cannot to connect.
