### ISSUE TITLE
“apt-get update” always fail when build base docker image

### ISSUE THREAD

**Issue by phx420** [Azure/sonic-buildimage#1281]
hi,
this is "make" conmand output: 
`Step 1/25 : FROM debian:jessie
 ---> 2fe79f06fa6d
Step 2/25 : MAINTAINER johnar@microsoft.com
 ---> Running in 0c57d770ffbc
 ---> 2da6dfa456e1
Removing intermediate container 0c57d770ffbc
Step 3/25 : RUN echo "deb http://debian-archive.trafficmanager.net/debian/ jessie main contrib non-free" >> /etc/apt/sources.list &&         echo "deb-src http://debian-archive.trafficmanager.net/debian/ jessie main contrib non-free" >> /etc/apt/sources.list &&         echo "deb http://debian-archive.trafficmanager.net/debian-security/ jessie/updates main contrib non-free" >> /etc/apt/sources.list &&         echo "deb-src http://debian-archive.trafficmanager.net/debian-security/ jessie/updates main contrib non-free" >> /etc/apt/sources.list &&         echo 'deb http://debian-archive.trafficmanager.net/debian jessie-backports main' >> /etc/apt/sources.list
 ---> Running in 03850102c49c
...........
...........
 ---> Running in 0cf1c57d9a3f
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://debian-archive.trafficmanager.net jessie InRelease
Get:2 http://debian-archive.trafficmanager.net jessie/updates InRelease [63.1 kB]
Get:3 http://debian-archive.trafficmanager.net jessie-backports InRelease [166 kB]
Get:4 http://debian-archive.trafficmanager.net jessie Release.gpg [2434 B]
Get:5 http://debian-archive.trafficmanager.net jessie Release [148 kB]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [588 kB]
Get:7 http://debian-archive.trafficmanager.net jessie/updates/main Sources [255 kB]
Get:8 http://debian-archive.trafficmanager.net jessie/updates/contrib Sources [1298 B]
Get:9 http://debian-archive.trafficmanager.net jessie/updates/non-free Sources [20 B]
Get:10 http://debian-archive.trafficmanager.net jessie/updates/main amd64 Packages [598 kB]
Get:11 http://debian-archive.trafficmanager.net jessie/updates/contrib amd64 Packages [2366 B]
Get:12 http://debian-archive.trafficmanager.net jessie/updates/non-free amd64 Packages [20 B]
Get:13 http://debian-archive.trafficmanager.net jessie-backports/main amd64 Packages [1170 kB]
Get:14 http://debian-archive.trafficmanager.net jessie/main Sources [9166 kB]
Get:15 http://debian-archive.trafficmanager.net jessie/contrib Sources [58.9 kB]
Get:16 http://debian-archive.trafficmanager.net jessie/contrib amd64 Packages [59.2 kB]
Get:17 http://debian-archive.trafficmanager.net jessie/non-free Sources [119 kB]
Get:18 http://debian-archive.trafficmanager.net jessie/main amd64 Packages [9063 kB]
Get:19 http://debian-archive.trafficmanager.net jessie/non-free amd64 Packages [101 kB]
Ign http://deb.debian.org jessie InRelease
Get:20 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:21 http://deb.debian.org jessie Release.gpg [2434 B]
Get:22 http://deb.debian.org jessie Release [148 kB]
Get:23 http://deb.debian.org jessie-updates/main amd64 Packages [23.1 kB]
Get:24 http://deb.debian.org jessie/main amd64 Packages [9063 kB]
Fetched 31.0 MB in 52s (596 kB/s)
**W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://debian-archive.trafficmanager.net/debian-security/dists/jessie/updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/jessie/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch**
.............
...........
`

could you help me ?

**Comment by stephengzh** [comment]
Hi, I met same issue, did you fix it?
