### ISSUE TITLE
BCM SDK Version Supported in Present Sonic-buildimage

### ISSUE THREAD

**Issue by muindurk** [Azure/sonic-buildimage#1293]
We are looking for Sonic-Buildimage version that will support TH2 ASIC.
Is present version support it? If not When can we expect TH2 support?

**Comment by lguohan** [comment]
we added TH2 support in commit https://github.com/Azure/sonic-buildimage/commit/005a59fc4ded9a8ca94d1d1453c8bb8d2d091f59
