### ISSUE TITLE
[sonic-slave] Wrong version of linux headers in the docker image

### ISSUE THREAD

**Issue by Mrak-IW** [Azure/sonic-buildimage#1329]
**Description**

In new sonic-slave images we have **3.16.0-5** version of linux headers in */lib/modules/* directory.
But most of vendor build systems depends on the version **3.16.0-4**

**Steps to reproduce the issue:**
1. make sonic-slave-build
2. make sonic-slave-bash
3. ls /lib/modules/

**Results received:**
```bash
user@0f4a98633b98:/sonic$ ls /lib/modules/
3.16.0-5-amd64
```

**Results expected:**
```bash
user@0f4a98633b98:/sonic$ ls /lib/modules/
3.16.0-4-amd64
```

**Additional information:**

It happens because of dependencies of the libpcre3 package. Now it needs **linux-headers-3.16.0-5-amd64** and **linux-headers-3.16.0-5-common** to be installed

**Comment by marian-pritsak** [comment]
Hi Denis,


It actually does not matter which version is in slave at the beginning.

Reason for that is that every package that depends on linux headers has a recipe that describes a dependency on headers of correct version that are built and installed automatically bu build system if any such package is built.


Please see

https://github.com/Azure/sonic-buildimage/blob/master/rules/linux-kernel.mk

https://github.com/Azure/sonic-buildimage/blob/f4e37a66f92099cc5d3bbde33823cd38b30a48a8/platform/broadcom/platform-modules-arista.mk#L9


<https://github.com/Azure/sonic-buildimage/blob/f4e37a66f92099cc5d3bbde33823cd38b30a48a8/platform/broadcom/platform-modules-arista.mk#L9>

When you'll try to build this package ( "make -f slave.mk target/debs/sonic-platform-arista_1.0_amd64.deb" ) inside slave container, you'll see that 3.16.0-4 headers are installed prior to building modules.


Marian

________________________________
