### ISSUE TITLE
ConfigDB can get stuck in broken state if "config load_minigraph" crashes

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#1331]
**Description**

If `config load_minigraph` crashes (e.g., due to an improperly formatted minigraph file), it can leave the ConfigDB in a broken state that requires manual intervention to recover from (i.e., database is completely empty; `CONFIG_DB_INITIALIZED` key is missing). ConfigDB should never be left in a broken state, even if `config load_minigraph` should crash.

For more context, see: https://github.com/Azure/SONiC/issues/145

**Steps to reproduce the issue:**
1. Modify /etc/minigraph.xml in order to create an improperly-formatted minigraph file (one that will cause the minigraph parser to crash)
2. Run `config load_minigraph`, ensure it crashes while parsing (you will see Python backtrace)
3. Check contents of  ConfigDB (`redis-cli -n 4 keys '*'); DB will be empty.

**Comment by lguohan** [comment]
dup as #1629
