### ISSUE TITLE
[sensord] module w83627dhg always alarm

### ISSUE THREAD

**Issue by maggiemsft** [Azure/sonic-buildimage#1347]
**Description**
Dell S6000 sensor always alarming

**Steps to reproduce the issue:**
1. do a sudo cat /var/log/syslog
2.
3.

**Describe the results you received:**
ALERT sensord: Sensor alarm: Chip w83627dhg-isa-0a00: 3VSB: +3.36 V (min = +3.22 V, max = +2.96 V) [ALARM]

This happened on my available DellS600-.

**Describe the results you expected:**
Need to know if this is due to wrong configuration of module parameters or it's a real alarm.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    SONiC.HEAD.461-da10ff5
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
remove w83627 module for dell s6000. https://github.com/Azure/sonic-platform-modules-s6000/commit/0c74ca2ff5ef9aedec423d78e87a2fad54bb96d9
