### ISSUE TITLE
How do I put ipmitool to rootfs

### ISSUE THREAD

**Issue by jostar-yang** [Azure/sonic-buildimage#1364]
**Description**
How do I put ipmitool to fsroot/usr/bin/

We have BMC project. We need to use ipmitool to access BMC information.
I think there should be rule to put this kind of utility tool to rootfs.
Ipmitool need to put to /usr/bin/ or /sbin. 
**Steps to reproduce the issue:**
ipmitool mc info

**Describe the results you received:**

**Describe the results you expected:**

# ipmitool mc info
Device ID                 : 32
Device Revision           : 1
Firmware Revision         : 0.01
IPMI Version              : 2.0
Manufacturer ID           : 0

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ForzaTian** [comment]
Hello:
Now I meet the same problem with you. 
Have you know how to add ipmitools in SONiC? Is that convient for you to share the method?
Many thanks.

**Comment by ForzaTian** [comment]
Hello:
I have seen your modify in pull request , it's very helpful , thanks for your share.

**Comment by lguohan** [comment]
use pmon docker which has ipmitool installed.

**Comment by jleveque** [comment]
Hi @ForzaTian. Please close this issue if it is resolved.

**Comment by ForzaTian** [comment]
@jleveque sorry,the issue was not opened by me.

**Comment by jleveque** [comment]
Hi @jostar-yang. Please close this issue if it is resolved.
