### ISSUE TITLE
Architecture question regarding to mage building

### ISSUE THREAD

**Issue by ryanmusic** [Azure/sonic-buildimage#1373]
Hello,

I understand that SAI layer is used to abstract SDK layer provided by different ASIC vendors, and does that mean we actually need to download SDKs in any git repo that's storing them to compile the image? If not, which library do we refer as the header for SDKs?

Sincerely,
Ryan

**Comment by lguohan** [comment]
The asic vendor will provide both SAI and SDK library and ensure the compatibility of them. Users do not have to download SDK separate and compile against the SAI.
