### ISSUE TITLE
SAI v1.2 does not include the broadcom configure on delta_ag9032v1 

### ISSUE THREAD

**Issue by hans-tseng** [Azure/sonic-buildimage#1416]
**Description**

**Steps to reproduce the issue:**
1. download the SONiC image from "https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms" 
2. Installed image on delta_ag9032v1 platform

**Describe the results you received:**
Broadcom ASCI could not be brought up successfully

**Describe the results you expected:**
Broadcom ACSI should be brought up successfully and the "bcmcmd" command should be used 

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
The file didn't get pulled in from Broadcom SAI 3.0 to 3.1. Will fix it soon.

Sorry for the inconvenience.

Regards,
Ying

**Comment by hans-tseng** [comment]
Hi yxieca:
  
    Thanks for your help to put the ag9032v1's configuration file into SAI. About the ag9064 configuration file,th2-ag9064-64x100G.config.bcm, we had sent a requestion mail to 'shuche@microsoft.com'  and attached the file on 2/27.  I will update the ag9064's broadcom configuration file in this issue to you 
[th2-ag9064-64x100G.config.zip](https://github.com/Azure/sonic-buildimage/files/1779963/th2-ag9064-64x100G.config.zip)

BTW, I would like to update the ag9032v1 configuration file,th-ag9032v1-32x100G.config.bcm, which added
[th-ag9032v1-32x100G.config.zip](https://github.com/Azure/sonic-buildimage/files/1779959/th-ag9032v1-32x100G.config.zip)

 the pre-emphasis value

Best Regards

Hans

**Comment by yxieca** [comment]
Hans,

Thanks for attaching them again. I'll check it in and update SAI accordingly.

Regards,
Ying

**Comment by yxieca** [comment]
Hans,

Unfortunately, both configuration files you proposed has some issue. They didn't pass our config_checker.

[config_checker.zip](https://github.com/Azure/sonic-buildimage/files/1782128/config_checker.zip)

Please download the checker I attached above. Unzip them to a same folder, and execute config_checker from that folder, config_checker is a python script. Run it against the config files you want to check in. Please re-post them once you fixed the issues.

Thanks,
Ying

**Comment by hans-tseng** [comment]
Hi, Yxieca:
    Please use the attached file of ag9064's broadcom configuration 
              
[th2-ag9064-64x100G.config.zip](https://github.com/Azure/sonic-buildimage/files/1783283/th2-ag9064-64x100G.config.zip)
     About the pre-emphasis value in the ag9032v1's configuration does not pass the check, and the key reason is we use the "serdes_preemphasis_laneX_"(X=0,1,2,3) to set the pre-emphasis power but the check list does not support it. 
    Each platform, we will tune every port's power to reach the good performance.  That why we want to set the pre-emphasis value in the configuration while loading the configuration file. May you help us to add the pre-emphasis command in the ckeck list or any suggestion for us how to set the pre-emphasis value? 
  


Best Regards
Hans

**Comment by hans-tseng** [comment]
Hi, Yxieca:
    I used the  congif_checker tool and pass it. I updated the ag9064 configuration inhere. 
                   
[th2-ag9064-64x100G.config.zip](https://github.com/Azure/sonic-buildimage/files/1783738/th2-ag9064-64x100G.config.zip)

Hans

**Comment by yxieca** [comment]
Thanks Hans.

Will make it available soon.

Regards,
Ying

**Comment by yxieca** [comment]
Hans,

in your 9064 configuration files, you added a line at the end of the file:

mmu_init_config="MSFT-TH2-Tier1"

This enables some mmu configuration specifically for Microsoft deployment. Do you really want this to be enabled on your platform?

I can remove this line for you if you want. Please let me know.

Thanks,
Ying

**Comment by hans-tseng** [comment]
Hi, Ying

   Thank for your reminding about this. This configure can be removed and as you said it needs additional configurations to cooperate with. If you could kindly tell us what the other configurations then we can test it on ag9064.


Best Regards
Hans

**Comment by yxieca** [comment]
Hans,

I've removed the configuration for you. Will create a new sai image soon.

You can reference to Arista7260CX3-D108C8 configuration and make it complete. Basically, you need to configure the rest of the MMU through buffers.json.j2.

Cheers,
Ying

**Comment by yxieca** [comment]
Hans,

I checked in the new SAI 3.1.3.4-4. Can you check and close this issue?

Thanks,
Ying
