### ISSUE TITLE
Is sonic_sfp / sonic_psu (inherted by sfputil.py / psuutil.py)  on the Porting Guilde re-designing??

### ISSUE THREAD

**Issue by pollyhsu2git** [Azure/sonic-buildimage#1433]
**Description**

1. We've ported / tested OK / PRed sfputil.py  (#1260 ) based on the Porting Guilde
**##### https://github.com/Azure/SONiC/wiki/Porting-Guide
**sfputil.py**: Format: Python module that must implement the class SfpUtil which must inherit from **sonic_sfp.sfputilbase.SfpUtilBase** which communicates with your SFP device driver
**psuutil.py**: Format: Python module that must implement the class PsuUtil which must inherit from **sonic_psu.psu_base.PsuBase** which communicates with your PSU device driver

2.  We found that `sfputil show` even `sfputil version` was not working under the build image with the commit: e18bffd

3. After examining the **sonic-utilities** PRs, we found that **sonic_sfp** together with **sonic_psu** were removed from its setup.py at its #184 (https://github.com/Azure/sonic-utilities/pull/184)
**#####**
$ dpkg --contents ./debs/python-sonic-utilities_1.2-1_all.deb | grep sonic_sfp
$ **[NO FOUND]**
**#####**

**Steps to reproduce the issue:**
1. list the sfputil.py (ls -al) 
2. Issue `sfputil version`
3. Issue `sfputil show`

**Describe the results you received:**
root@sonic:/# ls -al ./usr/share/sonic/device/x86_64-accton_as7816_64x-r0/plugin/sfputil.py
-rw-r--r-- 1 root root 3611 Feb 27  2018 ./usr/share/sonic/device/x86_64-accton_as7816_64x-r0/plugins/sfputil.py
root@sonic:/# sfputil version
Failed to load platform module 'sfputil': [Errno 2] No such file or directory
root@sonic:/# sfputil show
Failed to load platform module 'sfputil': [Errno 2] No such file or directory

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
root@sonic:/home/admin# show version
SONiC Software Version: SONiC.HEAD.0-dirty-20180227.062038
Distribution: Debian 8.10
Kernel: 3.16.0-5-amd64
Build commit: e18bffd
Build date: Tue Feb 27 06:27:54 UTC 2018

    **Attach debug file `sudo generate_dump`:**
[sonic_dump_sonic_20000101_000542.tar.gz](https://github.com/Azure/sonic-buildimage/files/1769958/sonic_dump_sonic_20000101_000542.tar.gz)

**Comment by pollyhsu2git** [comment]
[sonic_dump_sonic_20000101_000542.tar.gz](https://github.com/Azure/sonic-buildimage/files/1769957/sonic_dump_sonic_20000101_000542.tar.gz)

**Comment by fillmorechen0928** [comment]
The same issue as (https://github.com/Azure/sonic-utilities/issues/215)

**Comment by pollyhsu2git** [comment]
@fillmorechen0928, thanks for the info~

**Comment by jleveque** [comment]
Fixed in https://github.com/Azure/sonic-buildimage/pull/1438
