### ISSUE TITLE
How to configure isis in config-db

### ISSUE THREAD

**Issue by louishot** [Azure/sonic-buildimage#14389]
Hi guys,

How to configure isis in config-db
I see there have some example for BGP but no isis.

I tried use vtysh to configure isis it's works fine but When I execute config save -y, the part configured by vtysh is not saved.
I think all configurations should be in config_db.json and load it into FRR instead of configure it in vtysh.

Thank you

**Comment by vmittal-msft** [comment]
ISIS not supported yet.
