### ISSUE TITLE
question about eeprom.py and sfputil.py

### ISSUE THREAD

**Issue by ForzaTian** [Azure/sonic-buildimage#1461]
**Description**

Can't execute eeprom.py and sfputil.py

**Steps to reproduce the issue:**
1. ls eeprom.py  and sfputil.py in sonic
2. execute sonic command

**Describe the results you received:**

admin@sonic:~$  ls /usr/share/sonic/device/x86_64-delta_dsc100-r0/plugins/
eeprom.py  sfputil.py
admin@sonic:~$  sudo decode-syseeprom                                     
/usr/bin/decode-syseeprom : ERROR : cannot load module: /usr/share/sonic/device/"x86_64-delta_dsc100-r0"/plugins/eeprom.py
admin@sonic:~$  sudo sfputil version 
Failed to load platform module 'sfputil': [Errno 2] No such file or directory

In fact I see the closed issue [#1433](https://github.com/Azure/sonic-buildimage/issues/1433) ,
may be it's the same case with me in sfputil.py, and I pull the commit in sonic-utilities, but didn't solve my problem.
So I want to know whether I missed something, any advice?
Thanks for everyone.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by pollyhsu2git** [comment]
@ForzaTian, we've pulled / tested the build commit: 126d08d OK here.

**#####**
root@sonic:/home/admin# sudo decode-syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 164
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21  15 7816-64X-O-AC-F
Part Number          0x22  13 FP3ZZ7664005A
Serial Number        0x23  10 AH29042316
Base MAC Address     0x24   6 70:72:CF:0C:97:92
Manufacture Date     0x25  19 09/29/2017 13:39:29
Label Revision       0x27   3 R01
Platform Name        0x28  27 x86_64-accton_as7816_64x-r0
ONIE Version         0x29  13 2017.05.00.07
MAC Addresses        0x2A   2 131
Manufacturer         0x2B   6 Accton
Manufacture Country  0x2C   2 TW
Vendor Name          0x2D   8 Edgecore
Diag Version         0x2E   8 0.1.0.15
CRC-32               0xFE   4 0x015E69FC
(checksum valid)
root@sonic:/home/admin# sudo sfputil version
sfputil version 2.0
root@sonic:/home/admin# show ver
SONiC Software Version: SONiC.master.0-126d08d
Distribution: Debian 8.10
Kernel: 3.16.0-5-amd64
Build commit: 126d08d
Build date: Mon Mar  5 07:21:42 UTC 2018

**Comment by ForzaTian** [comment]
@pollyhsu2git thanks for your timely reply.
But when I pull the latest commit in today (Mar 6) ,and compile again, the outputs of the two commands on my board have no change.
So may I ask you whether you do anything before you execute the commands on sonic shell?

Thanks again for your info.

**Comment by pollyhsu2git** [comment]
@ForzaTian, NO~ We did not do any particular before the decode-syseeprom / sfputil commands

**Comment by lguohan** [comment]
@ForzaTian , you can also download the latest image from https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/

Does that work?

**Comment by ForzaTian** [comment]
@lguohan Thanks for your reply.
But I am developing our project now, the code haven't pushed into github, so there is no debs for our project in jenkins and the image could not run on our board.

May I ask one more question?
I check the boot log on my board and find syncd segfault such as :
syncd[1752]: segfault at 15f6978 ip 00007f281b7ca04e sp 00007f281aea0c68 error 4 in libc-2.19.so[7f281b738000+1a1000]
syncd[1795]: segfault at 3f65458 ip 00007f569b0aa04e sp 00007f569a780c68 error 4 in libc-2.19.so[7f569b018000+1a1000]
syncd[1843]: segfault at 1529e68 ip 00007fabdca1a04e sp 00007fabdc0f0c68 error 4 in libc-2.19.so[7fabdc988000+1a1000]
I'm not sure whether it has influence on .py execution, so in your experience , what may lead to that error? Could you give me some advice?
If you have no experience for that , please ignore that question.
Thanks for your help.

**Comment by ForzaTian** [comment]
Hi all:
Finally, I found the reason for my error. 
It because the "onie_platform" value in machine.conf is not correct , which has been amended in onie project [onie commit](https://github.com/opencomputeproject/onie/commit/33768d04d8795e207cb9b3f6e6e538b5c2e734aa) .
It has been a long time since my last update onie code, so I pull & compile it, and install sonic again, all the commands can work now.
Many thanks for all of your help.
