### ISSUE TITLE
helping to merge the ag5648 broadcom's config

### ISSUE THREAD

**Issue by hans-tseng** [Azure/sonic-buildimage#1473]
Hi, sir
We had added the requestion about the ag5648,"Add a new supported device, Delta-ag5648 #1470",
would you help to merge the attached config file in to SAI
  
[th-ag5648-48x25G+6x100G.config.zip](https://github.com/Azure/sonic-buildimage/files/1792428/th-ag5648-48x25G.6x100G.config.zip)

Hans

**Comment by lguohan** [comment]
added in #1509
