### ISSUE TITLE
Which set of the SONic Roadmap is for the Coming release, SONiC.201803??

### ISSUE THREAD

**Issue by pollyhsu2git** [Azure/sonic-buildimage#1486]
**Description**

We've found the SONiC.201803 feature list on two different SONiC Wiki links:
1. https://github.com/Azure/SONiC/wiki/Features-and-Roadmap
2. https://github.com/Azure/SONiC/wiki/Sonic-Roadmap-Planning

Which set of the SONic Roadmap is for the coming release, SONiC.201803??

![image](https://user-images.githubusercontent.com/28097129/37322577-6a5a7cae-26b9-11e8-8a26-5374c2102eee.png)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by pollyhsu2git** [comment]
@lihuay  / @xinliu-seattle,
We need your help to clarify it for us!
Thanks~

**Comment by pollyhsu2git** [comment]
@lihuay / @xinliu-seattle,
Based on the announce of `SONiC Release SONiC.201712 Available` on `sonicproject`, we assume that the answer is (2)
![image](https://user-images.githubusercontent.com/28097129/37509244-8cb50a6a-2931-11e8-8824-e626857e7ff3.png)

**Comment by xinliu-seattle** [comment]
@pollyhsu2git,
 sorry we missed to address  this issue in time. 
The right roadmap wiki is: https://github.com/Azure/SONiC/wiki/Sonic-Roadmap-Planning
I have removed the redundant one. Close this issue.
