### ISSUE TITLE
[Debian9-S6100]: In LLDP for port id , instead of interface name ,mac address  is advertised 

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-buildimage#1488]
**Description**

In LLDP for port id , instead of interface name ,mac address  is advertised 

**Steps to reproduce the issue:**
1. Check for LLDP information in peer device

**Describe the results you received:**
In Peer Arista VM : 

ARISTA01T1#show lldp neighbors
Last table change time   : 1:55:32 ago
Number of table inserts  : 19
Number of table deletes  : 18
Number of table drops    : 0
Number of table age-outs : 9

Port       Neighbor Device ID               Neighbor Port ID           TTL
**_Et1        sonic-s6100-01                   4c76.25f4.7081             120_**
ARISTA01T1#

**Describe the results you expected:**
The sonic DUT should be advertising interface name as the port id.

**Additional information **

 **Output of show version sonic DUT:**

_Build : buildimage-brcm-stretch-all 138_

root@sonic-s6100-01:~# show ver
SONiC Software Version: SONiC.HEAD.138-b0b8d69
Distribution: Debian 9.4
Kernel: 4.9.0-5-amd64
Build commit: b0b8d69
Build date: Mon Mar 12 13:03:50 UTC 2018
Built by: johnar@jenkins-worker-4

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.138-b0b8d69    d92b77a90440        331.6 MB
docker-syncd-brcm          latest              d92b77a90440        331.6 MB
docker-orchagent-brcm      HEAD.138-b0b8d69    ae0ca94d991a        260.5 MB
docker-orchagent-brcm      latest              ae0ca94d991a        260.5 MB
docker-lldp-sv2            HEAD.138-b0b8d69    0451d4fe2056        270.7 MB
docker-lldp-sv2            latest              0451d4fe2056        270.7 MB
docker-dhcp-relay          HEAD.138-b0b8d69    d1c0ab97120f        253.6 MB
docker-dhcp-relay          latest              d1c0ab97120f        253.6 MB
docker-database            HEAD.138-b0b8d69    175362bcb375        252.3 MB
docker-database            latest              175362bcb375        252.3 MB
docker-teamd               HEAD.138-b0b8d69    d6911b887ad9        257.6 MB
docker-teamd               latest              d6911b887ad9        257.6 MB
docker-snmp-sv2            HEAD.138-b0b8d69    03312ccf30c8        292 MB
docker-snmp-sv2            latest              03312ccf30c8        292 MB
docker-router-advertiser   HEAD.138-b0b8d69    5400a265ea98        250 MB
docker-router-advertiser   latest              5400a265ea98        250 MB
docker-platform-monitor    HEAD.138-b0b8d69    56e07878c4d7        271.9 MB
docker-platform-monitor    latest              56e07878c4d7        271.9 MB
docker-fpm-quagga          HEAD.138-b0b8d69    94b4ade9f44d        264.1 MB
docker-fpm-quagga          latest              94b4ade9f44d        264.1 MB

**Comment by jleveque** [comment]
Fixed in PR https://github.com/Azure/sonic-buildimage/pull/1469
