### ISSUE TITLE
Does SONiC Deb-9 source code can build now?

### ISSUE THREAD

**Issue by jostar-yang** [Azure/sonic-buildimage#1492]
**Description**
We git clone SONiC deb9 to build, but fail. Does SONiC deb-9 start to wrok?

**Steps to reproduce the issue:**
1.git clone https://github.com/lguohan/sonic-buildimage 
   cd sonic-buildimage
   git checkout stretch 
2. make init 
make configure PLATFORM=broadcom 
BLDENV=stretch make stretch
make target/sonic-broadcom.bin

**Describe the results you received:**
Compile fail when do "make target/sonic-broadcom.bin"
.......................................
+++ git rev-parse --short HEAD
++ echo stretch.0-b0b8d69
+ sudo LANG=C chroot ./fsroot docker tag docker-snmp-sv2:latest docker-snmp-sv2:stretch.0-b0b8d69
+ sudo LANG=C chroot ./fsroot docker load
Error response from daemon: invalid argument
+ clean_sys
+ sudo umount ./fsroot/sys/fs/cgroup/blkio ./fsroot/sys/fs/cgroup/cpuset ./fsroot/sys/fs/cgroup/devices ./fsroot/sys/fs/cgroup/freezer ./fsroot/sys/fs/cgroup/memory ./fsroot/sys/fs/cgroup/perf_event ./fsroot/sys/fs/cgroup/pids ./fsroot/sys/fs/cgroup ./fsroot/sys
+ true
+ rm -f /tmp/tmp.4ZOnhL3nai
+ sudo umount ./fsroot/proc
+ true
[  FAIL LOG END  ] [ target/sonic-broadcom.bin ]
slave.mk:432: recipe for target 'target/sonic-broadcom.bin' failed
make: *** [target/sonic-broadcom.bin] Error 1
Makefile:87: recipe for target 'target/sonic-broadcom.bin' failed
make: *** [target/sonic-broadcom.bin] Error 2

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
daily build for stretch image 

https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-stretch-all/
