### ISSUE TITLE
Jenkins: Marvell's build-image on branch 201709 is failing

### ISSUE THREAD

**Issue by ZivErlich** [Azure/sonic-buildimage#1497]
I've noticed Marvell's build-image on branch 201709 has been failing for the past couple of weeks.
When I dug into the builds' status, I saw that the build is based upon branch master, instead of branch 201709 as it should, and as it is for all other vendors.
Since we have not yet supplied our updates for SAI v1.2 (which branch master is based upon), the build keeps failing.
Is it possible to change it back to be based upon branch 201709 (refs/remotes/origin/201709)?

**Comment by lguohan** [comment]
changed.
