### ISSUE TITLE
Newest SAI does not include the broadcom configuration on quanta_ix1b_32x

### ISSUE THREAD

**Issue by cpchangtw** [Azure/sonic-buildimage#1505]
**Description**
th-ix1b-32x100G.config.bcm didn't included in newest SAI

**Steps to reproduce the issue:**
unpack libsaibcm to check if configuration file in it.

**Describe the results you received:**
there is NO th-ix1b-32x100G.config.bcm

**Describe the results you expected:**
should be included, please help.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

[th-ix1b-32x100G.config.zip](https://github.com/Azure/sonic-buildimage/files/1818234/th-ix1b-32x100G.config.zip)

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
the config does not pass the config_check in the saibcm package. can you provide config that pass the check?

**Comment by cpchangtw** [comment]
Hi
Where can I find the config_check? Is there any document for check rules?
Regards,

**Comment by cpchangtw** [comment]
@lguohan 
Please ignore my previous question, I found config_check and reviewed the error log.
I'm wondering if the parameter check rule could be modified since we might need to change some extra parameters like mdio_io_voltage.

**Comment by lguohan** [comment]
can you send me a full list of the parameter that you need?

**Comment by cpchangtw** [comment]
Hi @lguohan 
sorry for my mistake, after confirm, so far ix1b wouldn't need extra parameters.
update config.bcm which with config_check passed, please help review, thanks.
[th-ix1b-32x100G.config.bcm.zip](https://github.com/Azure/sonic-buildimage/files/1846428/th-ix1b-32x100G.config.bcm.zip)

**Comment by cpchangtw** [comment]
Since the file had been included into SAI, close this issue, thanks.
