### ISSUE TITLE
/host/machine.conf is incorrent

### ISSUE THREAD

**Issue by fillmorechen0928** [Azure/sonic-buildimage#1519]
Please refer 
https://github.com/Azure/sonic-buildimage/issues/1404

Original /host/machine.conf:

onie_version=master-201802221653.0.1-dirty
onie_vendor_id=31874
onie_build_machine=alphanetworks_snh60b0_640f
onie_machine_rev=0
onie_arch=x86_64
onie_build_platform=x86_64-alphanetworks_snh60b0_640f-r0
onie_config_version=1
onie_build_date="2018-02-22T16:53+0800"
onie_partition_type=gpt
onie_kernel_version=3.14.27
onie_firmware=bios
onie_switch_asic=bcm
onie_skip_ethmgmt_macs=no
onie_grub_image_name=grubx64.efi
onie_machine=alphanetworks_snh60b0_640f
onie_platform=x86_64-alphanetworks_snh60b0_640f-r0

Current /host/machine.conf:
onie_arch='x86_64'
onie_bin=''
onie_boot_reason='rescue'
onie_build_date='2018-01-23T19:05+0800'
onie_build_machine='alphanetworks_snh60b0_640f'
onie_cli_static_parms=''
onie_cli_static_url='sonic-broadcom.bin'
onie_config_version='1'
onie_dev='/dev/sda2'
onie_exec_url='sonic-broadcom.bin'
onie_firmware='bios'
onie_grub_image_name='grubx64.efi'
onie_initrd_tmp='/'
onie_installer='/var/tmp/installer'
onie_kernel_version='3.14.27'
onie_machine='alphanetworks_snh60b0_640f'
onie_machine_rev='0'
onie_partition_type='gpt'
onie_platform='x86_64-alphanetworks_snh60b0_640f-r0'
onie_root_dir='/mnt/onie-boot/onie'
onie_skip_ethmgmt_macs='no'
onie_switch_asic='bcm'
onie_vendor_id='31874'
onie_version='master-201801231905.0.1-dirty'

Please remove quote.

It cause path with more quotes for other APP in SONIC.

**Comment by fillmorechen0928** [comment]
The difference is Original /host/machine.conf and Current /host/machine.conf.

ONIE's machine.conf is the same as onie_machine.zip   (https://github.com/Azure/sonic-buildimage/issues/1404)

**Comment by fillmorechen0928** [comment]
The problem is how you generating "/host/machine.conf".

**Comment by fillmorechen0928** [comment]
ONIE's machine.conf is the same as onie_machine.zip (#1404).

Before (https://github.com/Azure/sonic-buildimage/issues/1404) /host/machine.conf
and after  (https://github.com/Azure/sonic-buildimage/issues/1404) /host/machine.conf
should be the same format.

**Comment by fillmorechen0928** [comment]
The result of "set | grep ^onie_ > $demo_mnt/machine.conf" command is different from "cp /etc/machine.conf $demo_mnt" .

**Comment by lguohan** [comment]
#1404 is based on your request, and you have verified the PR and said it works. If it is not working now, then something has changed. In the example you given, you are using different onie versions. I verified the 'set | grep ^onie_ > $demo_mnt/machine.conf', it does not generate quote on my machine.

**Comment by fillmorechen0928** [comment]
PR #1468 is working for #1404 issue.  sonic_installer problem is fixed.

**Comment by fillmorechen0928** [comment]
But PR https://github.com/Azure/sonic-buildimage/pull/1468 generate https://github.com/Azure/sonic-buildimage/issues/1519 found by other team member.

I will  verifiy the 'set | grep ^onie_ > $demo_mnt/machine.conf' on my device.

**Comment by fillmorechen0928** [comment]
I verified the 'set | grep ^onie_ > $demo_mnt/machine.conf', **it  generates quote on my machine.**

**Comment by fillmorechen0928** [comment]
1. Boot up with ONIE and show machine.conf.

![machine_conf](https://user-images.githubusercontent.com/35523342/37900549-1a280ed2-3121-11e8-8fca-3cd480212f89.png)

2.  show machine-build.conf

![machine_build_conf](https://user-images.githubusercontent.com/35523342/37900569-2a2582a6-3121-11e8-87bc-f7ddd0348fa9.png)

3. Execute machine.conf

![exec_machine_conf](https://user-images.githubusercontent.com/35523342/37900581-388aec64-3121-11e8-94cf-8580ad9a7526.png)

4. Show the result of  'set | grep ^onie_ > /tmp/machine.conf',  **it generates quote on my machine**.

![quote_machine_conf](https://user-images.githubusercontent.com/35523342/37900621-614a80c4-3121-11e8-88cc-4217ec927946.png)

**Comment by lguohan** [comment]
can you check your onie version. master-201802221653.0.1-dirty, according to you log above, that one does not have quote.

**Comment by fillmorechen0928** [comment]
The file machine-build.conf  does not have quote.

But the "set" command has quote.

**Comment by fillmorechen0928** [comment]
https://github.com/Azure/sonic-buildimage/issues/1404 has the attachment files onie_machine.zip

**Comment by lguohan** [comment]
```
Original /host/machine.conf:

onie_version=master-201802221653.0.1-dirty
onie_vendor_id=31874
onie_build_machine=alphanetworks_snh60b0_640f
onie_machine_rev=0
onie_arch=x86_64
onie_build_platform=x86_64-alphanetworks_snh60b0_640f-r0
onie_config_version=1
onie_build_date="2018-02-22T16:53+0800"
onie_partition_type=gpt
onie_kernel_version=3.14.27
onie_firmware=bios
onie_switch_asic=bcm
onie_skip_ethmgmt_macs=no
onie_grub_image_name=grubx64.efi
onie_machine=alphanetworks_snh60b0_640f
onie_platform=x86_64-alphanetworks_snh60b0_640f-r0
```

**Comment by lguohan** [comment]
this one does not have quote.

**Comment by fillmorechen0928** [comment]
Don't care about master-201802221653.0.1-dirty version.

This is workaround version for SONIC issue. It's /host/machine.conf does not have quote due to generating from "cp /etc/machine.conf $demo_mnt" .

**Comment by fillmorechen0928** [comment]
The  command 'set | grep ^onie_ > $demo_mnt/machine.conf', it generates quote.

**Comment by lguohan** [comment]
can you check if this works for you?
```
set | grep ^onie |  sed -e "s/='/=/" -e "s/'$//"
```

**Comment by fillmorechen0928** [comment]
Yes, it is work.

The test result:

1. Execute machine.conf
![exec_machine_conf](https://user-images.githubusercontent.com/35523342/38131871-4835029a-343b-11e8-8cb5-f5120e7c2836.png)

2.  Show the result of '**set | grep ^onie |  sed -e "s/='/=/" -e "s/'$//"**', it does not generate quote on my machine.


![no_quote_machine_conf](https://user-images.githubusercontent.com/35523342/38131935-88c969f4-343b-11e8-8da4-8d670cf9879b.png)
