### ISSUE TITLE
[Debian9-Z9100] - lldp nbr is showing incorrect info

### ISSUE THREAD

**Issue by amitabhja** [Azure/sonic-buildimage#1525]
-->

**Description**

The build used on the device is debian 9 but int o/p for "show lldp neighbor detai" the codename "jessie" is shown.
This should be showing up as "stretch"

**Steps to reproduce the issue:**
1. check lldp nbr detail o/p in peer

**Describe the results you received:**
show lldp nbr:
script log:
<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>
    "msg": {
        "Ethernet1": {
            "neighbor_chassis_id": "0x4c7625e4e4c0",
            "neighbor_port_desc": "ARISTA16T2:Ethernet1",
            "neighbor_port_id": "hundredGigE1/16",
            "neighbor_sys_desc": "Debian GNU/Linux 8 (jessie) Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64",
            "neighbor_sys_name": "sonic-z9100-02"                                                                                                                   
<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>
			
show cmd on vm:
<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>
ARISTA01T2#show lldp nei det
Interface Ethernet1 detected 1 LLDP neighbors:

  Neighbor 4c76.25e4.e4c0/"hundredGigE1/1", age 14 seconds
  Discovered 4:16:47 ago; Last changed 4:15:43 ago
  - Chassis ID type: MAC address (4)
    Chassis ID     : 4c76.25e4.e4c0
  - Port ID type: Locally assigned (7)
    Port ID     : "hundredGigE1/1"
  - Time To Live: 120 seconds
  - Port Description: "ARISTA01T2:Ethernet1"
  - System Name: "sonic-z9100-02"
  - System Description: "Debian GNU/Linux 8 (jessie) Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64"
  - System Capabilities : Bridge, WLAN Access Point, Router, Station Only
    Enabled Capabilities: Bridge, Router
  - Management Address Subtype: IPv4
    Management Address        : 10.1.0.32
    Interface Number Subtype  : ifIndex (2)
    Interface Number          : 1
    OID String                :
  - Management Address Subtype: IPv6
    Management Address        : fc00:1::32
    Interface Number Subtype  : ifIndex (2)
    Interface Number          : 1
    OID String                :
  - IEEE802.1/IEEE802.3 Link Aggregation
    Link Aggregation Status: Capable, Disabled (0x01)
    Port ID                : 0
  - IEEE802.3 MAC/PHY Configuration/Status
    Auto-negotiation       : Not Supported
    Operational MAU Type   : Unknown

Interface Ethernet2 detected 0 LLDP neighbors:

Interface Ethernet3 detected 0 LLDP neighbors:

Interface Ethernet4 detected 0 LLDP neighbors:

Interface Ethernet5 detected 0 LLDP neighbors:

Interface Management1 detected 0 LLDP neighbors:

ARISTA01T2#
<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>

**Describe the results you expected:**

The build used on the device is debian 9 but int o/p for "show lldp neighbor detai" the codename "jessie" is shown.
This should be showing up as "stretch"

**Comment by amitabhja** [comment]
seen after merge:
root@sonic:~# lldpctl
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    Ethernet116, via: LLDP, RID: 1, Time: 0 day, 00:01:35
  Chassis:
    ChassisID:    mac 34:17:eb:45:de:00
    SysName:      sonic
    SysDescr:     Debian GNU/Linux 8 (jessie) Linux 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64
    TTL:          120
    MgmtIP:       10.1.0.32
    MgmtIP:       fe80::3617:ebff:fe45:de00
    Capability:   Bridge, on
    Capability:   Router, on
    Capability:   Wlan, off
    Capability:   Station, off
  Port:
    PortID:       local hundredGigE1/30
    PortDescr:    ARISTA14T0:Ethernet1
-------------------------------------------------------------------------------

**Comment by pavel-shirshov** [comment]
was fixed by
https://github.com/Azure/sonic-buildimage/commit/83f81c9676441d88d7a07dc6bcc6510532a77f97#diff-833cde5fbd99d17f29e8cfbd25b9d3bc

**Comment by pavel-shirshov** [comment]
Currently SONiC is running two OSs. We run Debian 9 as host system, Debian 8 as a container system.
lldp shows you a container system. Why do you think it's better to show host system in lldp?

**Comment by yxieca** [comment]
Issue has been addressed.
