### ISSUE TITLE
can not start SONiC os after install

### ISSUE THREAD

**Issue by lockless** [Azure/sonic-buildimage#1529]
I am sure that the SONiC has been installed， but the BIOS bootmenu always ONIE， so it always into ONIE os， what can i do now？

thanks for advise!

```
ONIE:/boot/efi/EFI # ls
SONiC-OS  onie
ONIE:/boot/efi/EFI # 
```

**Comment by lguohan** [comment]
Please fill out necessary information for debugging. When you create new issue, please fill out the form.
