### ISSUE TITLE
How to edit led linkscan callback?

### ISSUE THREAD

**Issue by appleCh** [Azure/sonic-buildimage#1543]
If we want to edit led linkscan callback,
Are the following steps right?

1. edit opennsl-odp source code ledproc_linkxxxx_cb().
2. Follow https://github.com/Azure/SONiC/wiki/Build-Broadcom-Opennsl-and-SAI to rebuild opennsl and SAI.
3. revise led_proc_init.soc

**Comment by pollyhsu2git** [comment]
@appleCh,
We might need to remind you that as far as we know that your posted OPENNSL code segment should be Broadcom NDA  protected~

**Comment by lguohan** [comment]
what API do you need? We need to introduce equivalent SAI callback API.

SAMPLE notification can be found at

https://github.com/opencomputeproject/SAI/blob/4c6e20bee2a3e2d1cc09157d64dd7ac552ff0c13/inc/saifdb.h

**Comment by appleCh** [comment]
Sorry i am not describe my purpose.
We want to modify because sometimes led linkscan callback can not meets our requirement.

For example, 
Our hw design port up at 100G with white coler, 50G Amber, and 40G Blue,
and we hope a led prog can process all speed. 
So, if cb only trun on 0x01 indicate LINKUP, we can not know the port up with what speed.

**Comment by serhepopovych** [comment]
You definitely need to implement your own led_control.py class.

**Comment by jleveque** [comment]
HI @appleCh. Please close this issue if it is resolved.
