### ISSUE TITLE
[Debian9-Z9100] - sfp eeprom data not read due to eeprom not being detected

### ISSUE THREAD

**Issue by amitabhja** [Azure/sonic-buildimage#1545]
**Description**

sfp eeprom data not read due to eeprom not being detected on z9100

sfputil cmd doesnt show any o/p as eeprom does not seem to be detected.

**Steps to reproduce the issue:**
1.check for the cm "sfputil show eeprom"

**Describe the results you received:**
build 151:
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>
root@sonic-z9100-02:~# sfputil show eeprom
Ethernet0: SFP EEPROM not detected
 
Ethernet4: SFP EEPROM not detected
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>

build 154:
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>
root@sonic-z9100-02:/home/admin# sfputil show eeprom
Error reading port info ([Errno 2] No such file or directory: '/usr/share/sonic/device/x86_64-dell_z9100_c2538-r0/Traceback (most recent call last):\n  File "/usr/local/bin/sonic-cfggen", line 232, in <module>\n    main()\n  File "/usr/local/bin/sonic-cfggen", line 167, in main\n    deep_update(data, parse_xml(minigraph, platform))\n  File "/usr/local/lib/python2.7/dist-packages/minigraph.py", line 331, in parse_xml\n    root = ET.parse(filename).getroot()\n  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)\n  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:117841)\n  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118188)\n  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117100)\n  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:111646)\n  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)\n  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)\n  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105621)\nIOError: Error reading file \'/etc/sonic/minigraph.xml\': failed to load external entity "/etc/sonic/minigraph.xml"/portmap.ini')
root@sonic-z9100-02:/home/admin#
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>

**Describe the results you expected:**
o/p from debian 8 on 6100:
root@sonic-s6100-01:~# sfputil show eeprom

Ethernet0: SFP EEPROM detected
        Connector: No separable connector
        Encoding: Unspecified
        Extended Identifier: Unknown
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP+
        Length Cable Assembly(m): 1
        Nominal Bit Rate(100Mbs): 103
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
        Vendor Date Code(YYYY-MM-DD Lot): 2012-07-28
        Vendor Name: Amphenol
        Vendor OUI: 41-50-48
        Vendor PN: 599690001
        Vendor Rev: E
        Vendor SN: APF12300017G79

Ethernet1: SFP EEPROM detected
        Connector: No separable connector
        Encoding: Unspecified
        Extended Identifier: Unknown
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP+
        Length Cable Assembly(m): 1
        Nominal Bit Rate(100Mbs): 103
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
        Vendor Date Code(YYYY-MM-DD Lot): 2011-12-23
        Vendor Name: Amphenol
        Vendor OUI: 41-50-48
        Vendor PN: 599690001
        Vendor Rev: D
        Vendor SN: APF11510011VUP 

    **Output of `show version`:**
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>
oot@sonic-z9100-02:/home/admin# show ver
SONiC Software Version: SONiC.HEAD.154-e69ce25
Distribution: Debian 9.4
Kernel: 4.9.0-5-amd64
Build commit: e69ce25
Build date: Wed Mar 28 00:28:39 UTC 2018
Built by: johnar@jenkins-worker-4

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.154-e69ce25    808e4bcc594f        358.1 MB
docker-syncd-brcm          latest              808e4bcc594f        358.1 MB
docker-orchagent-brcm      HEAD.154-e69ce25    1c46dd25a7e7        287 MB
docker-orchagent-brcm      latest              1c46dd25a7e7        287 MB
docker-lldp-sv2            HEAD.154-e69ce25    645690db4632        297.1 MB
docker-lldp-sv2            latest              645690db4632        297.1 MB
docker-dhcp-relay          HEAD.154-e69ce25    426ad89eeae7        280.1 MB
docker-dhcp-relay          latest              426ad89eeae7        280.1 MB
docker-database            HEAD.154-e69ce25    17edc49cb2d3        278.8 MB
docker-database            latest              17edc49cb2d3        278.8 MB
docker-teamd               HEAD.154-e69ce25    6faa0ba0dde5        284.1 MB
docker-teamd               latest              6faa0ba0dde5        284.1 MB
docker-snmp-sv2            HEAD.154-e69ce25    17ef37ef7e39        319.3 MB
docker-snmp-sv2            latest              17ef37ef7e39        319.3 MB
docker-router-advertiser   HEAD.154-e69ce25    3a813b8ffad0        276.4 MB
docker-router-advertiser   latest              3a813b8ffad0        276.4 MB
docker-platform-monitor    HEAD.154-e69ce25    f9215595cd58        298.4 MB
docker-platform-monitor    latest              f9215595cd58        298.4 MB
docker-fpm-quagga          HEAD.154-e69ce25    24d35e3cdc11        290.6 MB
docker-fpm-quagga          latest              24d35e3cdc11        290.6 MB

root@sonic-z9100-02:/home/admin#
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>

[sonic_dump_sonic-z9100-02_20180329_081459.tar.gz](https://github.com/Azure/sonic-buildimage/files/1859222/sonic_dump_sonic-z9100-02_20180329_081459.tar.gz)

**Comment by amitabhja** [comment]
still seeing after merge:
root@sonic:~# config save
Existing file will be overwritten, continue? [y/N]: y
Running command: sonic-cfggen -d --print-data > /etc/sonic/config_db.json
root@sonic:~# sfputil show syseeprom
Traceback (most recent call last):
  File "/usr/bin/sfputil", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'sfputil')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 370, in cli
    err = load_platform_sfputil()
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 349, in load_platform_sfputil
    platform_sfputil = platform_sfputil_class()
TypeError: Can't instantiate abstract class SfpUtil with abstract methods get_transceiver_change_event
root@sonic:~#

**Comment by xinliu-seattle** [comment]
I am contacting Dell to take a look at this issue.

**Comment by amitabhja** [comment]
sfputil show eeprom:
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>
root@sonic:~# sfputil show eeprom
Ethernet0: SFP EEPROM not detected

Ethernet4: SFP EEPROM not detected

Ethernet8: SFP EEPROM not detected

Ethernet12: SFP EEPROM not detected

Ethernet16: SFP EEPROM not detected

Ethernet20: SFP EEPROM not detected

Ethernet24: SFP EEPROM not detected

Ethernet28: SFP EEPROM not detected

Ethernet32: SFP EEPROM detected
        Connector: No separable connector
        Encoding: 64B66B
        Extended Identifier: Power Class 1(1.5W max)
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP28
        Length Cable Assembly(m): 1
        Nominal Bit Rate(100Mbs): 255
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
        Vendor Date Code(YYYY-MM-DD Lot): 2003-01-24
        Vendor Name: DELL
        Vendor OUI: a8-b0-ae
        Vendor PN: 035KG
        Vendor Rev: A
        Vendor SN: DE0035KG51C0001

Ethernet36: SFP EEPROM detected
        Connector: No separable connector
        Encoding: 64B66B
        Extended Identifier: Power Class 1(1.5W max)
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP28
        Length Cable Assembly(m): 1
        Nominal Bit Rate(100Mbs): 255
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
        Vendor Date Code(YYYY-MM-DD Lot): 2003-01-24
        Vendor Name: DELL
        Vendor OUI: a8-b0-ae
        Vendor PN: 035KG
        Vendor Rev: A
        Vendor SN: DE0035KG51C0001

Ethernet40: SFP EEPROM not detected

Ethernet44: SFP EEPROM not detected

Ethernet48: SFP EEPROM not detected

Ethernet52: SFP EEPROM not detected

Ethernet56: SFP EEPROM detected
        Connector: No separable connector
        Encoding: Unspecified
        Extended Identifier: Power Class 1(1.5W max)
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP+
        Length Cable Assembly(m): 1
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
                Fibre Channel Speed: 1200 Mbytes/Sec
                Fibre Channel link length/Transmitter Technology: Electrical inter-enclosure (EL)
                Fibre Channel transmission media: Twin Axial Pair (TW)
        Vendor Date Code(YYYY-MM-DD Lot): 2013-03-25
        Vendor Name: Molex Inc.
        Vendor OUI: 00-09-3a
        Vendor PN: 1110409129
        Vendor Rev: 00
        Vendor SN: 308430096

Ethernet60: SFP EEPROM detected
        Connector: No separable connector
        Encoding: Unspecified
        Extended Identifier: Power Class 1(1.5W max)
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP+
        Length Cable Assembly(m): 1
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
                Fibre Channel Speed: 1200 Mbytes/Sec
                Fibre Channel link length/Transmitter Technology: Electrical inter-enclosure (EL)
                Fibre Channel transmission media: Twin Axial Pair (TW)
        Vendor Date Code(YYYY-MM-DD Lot): 2013-03-25
        Vendor Name: Molex Inc.
        Vendor OUI: 00-09-3a
        Vendor PN: 1110409129
        Vendor Rev: 00
        Vendor SN: 308430084

Ethernet64: SFP EEPROM not detected

Ethernet68: SFP EEPROM not detected

Ethernet72: SFP EEPROM not detected

Ethernet76: SFP EEPROM not detected

Ethernet80: SFP EEPROM not detected

Ethernet84: SFP EEPROM not detected

Ethernet88: SFP EEPROM not detected

Ethernet92: SFP EEPROM not detected

Ethernet96: SFP EEPROM not detected

Ethernet100: SFP EEPROM not detected

Ethernet104: SFP EEPROM not detected

Ethernet108: SFP EEPROM not detected

Ethernet112: SFP EEPROM not detected

Ethernet116: SFP EEPROM not detected

Ethernet120: SFP EEPROM not detected

Ethernet124: SFP EEPROM not detected


root@sonic:~#
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>
