### ISSUE TITLE
DUT mgmt interface does not get v4 IP address

### ISSUE THREAD

**Issue by wendani** [Azure/sonic-buildimage#1548]
**Description**

on msn2700-22, workaround is to put ipv4 config ahead of ipv6

https://github.com/Azure/sonic-buildimage/pull/1544

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
addressed in https://github.com/Azure/sonic-buildimage/pull/1701
