### ISSUE TITLE
How can I create libsaibcm_X.X.X_amd64.deb to use in sonic-buildimage / platform / broadcom / sai.mk?

### ISSUE THREAD

**Issue by doicom** [Azure/sonic-buildimage#1550]
Hi all,

Someone, please help us. 
Since I want to change SAI version in my own environment, I would like to create SAI binary.

I am trying to create it according to the procedure described on https://github.com/Azure/SONiC/wiki/Build-Broadcom-Opennsl-and-SAI.

In particular, I do not know how OpenNSL and SAI source code is used for binary creation.
Is there source code on Github?
Or would you need to contact Broadcom to obtain the source code?

In Step 7 of Build OpenNSL, `sudo dpkg - i libopennsl *` is implemented.
We do not mention this procedure when building https: // github.com / Broadcom - Switch / OpenNSL.

What is doing with `sudo dpkg - i libopennsl *?`

Please help your idea.

**Comment by pollyhsu2git** [comment]
@doicom,

*****#####QUOTED#####https://github.com/Azure/SONiC/wiki/Build-Broadcom-Opennsl-and-SAI *****
***Intended audience***
Almost all users could build SONiC image by following guide on Building Guide, except those ***who has access to Broadcom Opennsl and SAI source code*** and are working on bringing up a new SAI version.

**Comment by doicom** [comment]
Thanks pollyhsu2git.
thank you for the advice.

I am sorry if my perception was wrong.


I wanted to create binaries of OpenNSL and SAI and to incorporate it into SONiC.

However,
If you check https://github.com/Azure/SONiC/wiki/Build-Broadcom-Opennsl-and-SAI,

· **People trying to acquire a new SAI version** = **a person uploading to github**
Is this recognition correct?

· Because there is the latest SAI in the source code, it is not necessary to create SAI individually.
Is this recognition correct?

· Because Github does not have the necessary source code, you can not create SAI individually.
Is this recognition correct?

doicom

**Comment by lguohan** [comment]
@doicom, if you want to create your own SAI library, you need to contact broadcom to obtain the source code.

**Comment by doicom** [comment]
Hello, @lguohan .
thank you for answering.
I'm sorry, my reaction was delayed.

Broadcom needs contact. And I understood.

Thank you very much.
