### ISSUE TITLE
How could i commit code to SONIC codebase for adding new platform devices?

### ISSUE THREAD

**Issue by fillmorechen0928** [Azure/sonic-buildimage#1553]
How could i commit code to SONIC codebase for adding new platform devices?

We want to add Alphanetworks devices to SONIC codebase.

We have already modified codes on local PC.

But we don't know how to commit code to SONIC codebase?

**Comment by jleveque** [comment]
Please refer to the following pull requests, and let us know if you have further questions:

https://github.com/Azure/sonic-buildimage/pull/1524

https://github.com/Azure/sonic-buildimage/pull/1470
