### ISSUE TITLE
[Debian9-Z9100] config save is hanging indefinitely

### ISSUE THREAD

**Issue by amitabhja** [Azure/sonic-buildimage#1566]
**Description**

config save is hangs indefinitely after deploying t0 topology minigraph from server
cannot take o/p of "show techsupport" as that cmd also hangs indefinitely
using the label 161
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-stretch-all/lastSuccessfulBuild/artifact/target/sonic-broadcom.bin

**Steps to reproduce the issue:**
1. deploy minigraph from server for t0 topology
2. perform cmd "config save" from console
3. the cli hangs indefintely

**Describe the results you received:**
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>
root@sonic-z9100-02:~# config save
Existing file will be overwritten, continue? [y/N]: y
Running command: sonic-cfggen -d --print-data > /etc/sonic/config_db.json
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>

the cmd hangs indefinitely

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>
dmin@sonic-z9100-02:~$ show ver
SONiC Software Version: SONiC.HEAD.161-7c8a635
Distribution: Debian 9.4
Kernel: 4.9.0-5-amd64
Build commit: 7c8a635
Build date: Tue Apr  3 11:25:06 UTC 2018
Built by: johnar@jenkins-worker-4

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.161-7c8a635    263bcbed3b14        358.1 MB
docker-syncd-brcm          latest              263bcbed3b14        358.1 MB
docker-orchagent-brcm      HEAD.161-7c8a635    f5326eae6970        287 MB
docker-orchagent-brcm      latest              f5326eae6970        287 MB
docker-lldp-sv2            HEAD.161-7c8a635    d77ff6995334        297.1 MB
docker-lldp-sv2            latest              d77ff6995334        297.1 MB
docker-dhcp-relay          HEAD.161-7c8a635    92ada5e29818        280.1 MB
docker-dhcp-relay          latest              92ada5e29818        280.1 MB
docker-database            HEAD.161-7c8a635    746e6563e61f        278.7 MB
docker-database            latest              746e6563e61f        278.7 MB
docker-teamd               HEAD.161-7c8a635    b7ac2067fd06        284.1 MB
docker-teamd               latest              b7ac2067fd06        284.1 MB
docker-snmp-sv2            HEAD.161-7c8a635    7096ad720bf0        319.2 MB
docker-snmp-sv2            latest              7096ad720bf0        319.2 MB
docker-router-advertiser   HEAD.161-7c8a635    a78cf51c9c00        276.4 MB
docker-router-advertiser   latest              a78cf51c9c00        276.4 MB
docker-platform-monitor    HEAD.161-7c8a635    072d237209c4        298.3 MB
docker-platform-monitor    latest              072d237209c4        298.3 MB
docker-fpm-quagga          HEAD.161-7c8a635    02f60ab8b7b5        290.6 MB
docker-fpm-quagga          latest              02f60ab8b7b5        290.6 MB

admin@sonic-z9100-02:~$
<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>

    **Attach debug file `sudo generate_dump`:**

"show techsupport" cli also hangs indefinitely

**Comment by lguohan** [comment]
taoyl will introduce timeout and then you can see if you can repro.

**Comment by amitabhja** [comment]
Verification Logs:
root@sonic:~# config save
Existing file will be overwritten, continue? [y/N]: y
Running command: sonic-cfggen -d --print-data > /etc/sonic/config_db.json
root@sonic:~#



root@sonic:~# show ver
SONiC Software Version: SONiC.HEAD.693-3f37b96
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: 3f37b96
Build date: Sun Aug 26 09:13:46 UTC 2018
Built by: johnar@jenkins-worker-4

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.693-3f37b96    e934afcb65a3        336.6 MB
docker-syncd-brcm          latest              e934afcb65a3        336.6 MB
docker-orchagent-brcm      HEAD.693-3f37b96    38a356f0df7a        257.6 MB
docker-orchagent-brcm      latest              38a356f0df7a        257.6 MB
docker-lldp-sv2            HEAD.693-3f37b96    9b54765a5987        270.8 MB
docker-lldp-sv2            latest              9b54765a5987        270.8 MB
docker-dhcp-relay          HEAD.693-3f37b96    0758dc72b19f        253.7 MB
docker-dhcp-relay          latest              0758dc72b19f        253.7 MB
docker-database            HEAD.693-3f37b96    33f38670a603        252.3 MB
docker-database            latest              33f38670a603        252.3 MB
docker-teamd               HEAD.693-3f37b96    d1df4e88a6a0        257.2 MB
docker-teamd               latest              d1df4e88a6a0        257.2 MB
docker-snmp-sv2            HEAD.693-3f37b96    791154a0e7cf        291.2 MB
docker-snmp-sv2            latest              791154a0e7cf        291.2 MB
docker-router-advertiser   HEAD.693-3f37b96    0b3ab8f3fca2        250 MB
docker-router-advertiser   latest              0b3ab8f3fca2        250 MB
docker-platform-monitor    HEAD.693-3f37b96    5bf09433f1f1        283.2 MB
docker-platform-monitor    latest              5bf09433f1f1        283.2 MB
docker-fpm-quagga          HEAD.693-3f37b96    cd3a0dc65949        264.1 MB
docker-fpm-quagga          latest              cd3a0dc65949        264.1 MB
