### ISSUE TITLE
bcmcmd missing on Mellanox SN2100

### ISSUE THREAD

**Issue by maq123** [Azure/sonic-buildimage#1590]
I use `SONiC Software Version: SONiC.HEAD.574-ed915e3`, and it seems bcmcmd is gone?

I try:
```
root@sonic:~# find / -name bcmcmd
root@sonic:~# docker exec -it syncd find / -name bcmcmd
```

Is that purposeful? If yes, how I can access BCM cli now?

**Comment by lguohan** [comment]
bcmcmd is only available for broadcom platform. it is not available on mellanox platform.
