### ISSUE TITLE
add the "usemsi=1" option in  modprob linux-kernel-bde with ag9064

### ISSUE THREAD

**Issue by hans-tseng** [Azure/sonic-buildimage#1598]
Hi Sir 

  We found that the Broadcom's MAC (TH2) initialization in ag9064 was too slow and it will take more than 5 minutes to finish it. So we add the "usemsi=1" while modprob linux-kernel-bde driver and it will speed up initialization process.

**Steps to reproduce the issue:**
1. modify /etc/init.d/opennsl-modules-3.16.0-5-amd64 on ag9064 with
        modprobe linux-kernel-bde dmasize=32M maxpayload=128 usemsi=1
2. re install the linux-kerenl-deb with options we added

**Comment by lguohan** [comment]
I am not familiar with this usemsi option, is this unique to you platform? we do not see such problem on another th2 platform.

**Comment by pollyhsu2git** [comment]
@hans-tseng 
We'll suggest you to do such device dependent revision at your **installer.conf**

**Comment by SAI-shared-user** [comment]
if usemsi is enable, how long is the initialization phase?

**Comment by lguohan** [comment]
if you use usemsi, how long is initialization phase?

**Comment by lguohan** [comment]
suggest you to first discuss with broadcom to understand why this option solves your problem, then we can figure out how to incorporate this into sonic or if not.

**Comment by lguohan** [comment]
addressed in https://github.com/Azure/sonic-buildimage/commit/7730bcf01138f01be0f69c7d636d4b88d0fa7196
