### ISSUE TITLE
please add the broadcom configuration file of delta et-6248brb into SAI

### ISSUE THREAD

**Issue by jackyjsliu** [Azure/sonic-buildimage#1618]
We did a new pull request of delta et-6248brb (https://github.com/Azure/sonic-buildimage/pull/1617),
please help to add the broadcom configuration file,helix4-et-6248brb-48x1G+2x10G.config.bcm, of delta et-6248brb into SAI
[helix4-et-6248brb-48x1G+2x10G.config.bcm.bcm.zip](https://github.com/Azure/sonic-buildimage/files/1923243/helix4-et-6248brb-48x1G.2x10G.config.bcm.bcm.zip)

**Comment by jackyjsliu** [comment]
Sorry, we make a mistake.
We delete our repository accidentally.
So we close the old pull request and open a new pull request.
Here is the correct pull request of delta et-6248brb(https://github.com/Azure/sonic-buildimage/pull/1640)

**Comment by stcheng** [comment]
for the config.bcm file, please follow the new porting guide config.bcm part.
we have updated the workflow so it's easier to add config.bcm files.
https://github.com/Azure/SONiC/wiki/Porting-Guide
thanks!

**Comment by yxieca** [comment]
Done.
