### ISSUE TITLE
rsyslog pushing "old" supervisor logs to syslog

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-buildimage#1652]
**Description**
While stopping and starting `snmp `service, it was observed that the same error message is repeatedly pushed to syslog. 

Initial analysis suggest the logic here may have issues. 

/etc/rsyslog.d/supervisor.conf => InputFileStateFile 

**Steps to reproduce the issue:**
1. systemctl stop snmp, systemctl start snmp multiple times
2. tail -F /var/log/syslog | grep "not expected"
3. The following logging happens everytime snmp service start. Notice the syslog time vs supervisord time

**Describe the results you received:**

```
Apr 26 22:43:48.757317 str-a7060cx-acs-1 INFO supervisord 2018-04-26 21:07:20,342 INFO exited: snmpd (terminated by SIGHUP; not expected)
Apr 26 22:45:58.609038 str-a7060cx-acs-1 INFO supervisord 2018-04-26 21:07:20,342 INFO exited: snmpd (terminated by SIGHUP; not expected)
Apr 26 23:04:25.800888 str-a7060cx-acs-1 INFO supervisord 2018-04-26 21:07:20,342 INFO exited: snmpd (terminated by SIGHUP; not expected)
```

**Describe the results you expected:**
After deleting the above line from `supervisor/supervisord.log`, and repeat the same steps of stopping and starting snmp, the issue was not observed

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    admin@str-a7060cx-acs-1:/$ show version 
    SONiC Software Version: SONiC.20180330.16
    ```

**Comment by lguohan** [comment]
I found the supervisord activity log also goes to stdout/stderr, therefore you can use docker logs to see them. 

https://docs.docker.com/config/containers/logging/configure/#configure-the-delivery-mode-of-log-messages-from-container-to-log-driver
