### ISSUE TITLE
locales on SONiC

### ISSUE THREAD

**Issue by richard28530** [Azure/sonic-buildimage#1681]
currently SONiC has no locales configured.

while you ssh from a terminal with en_US.UTF-8, then the env LANG is injected as en_US.UTF-8.
while you ssh from a terminal with zh_CN.UTF-8, then the env LANG is injected as zh_CN.UTF-8.

when LANG is injected as zh_CN.UTF-8, when try to completion with TAB on command line, it will prompt "-bash: warning: setlocale: LC_CTYPE: cannot change locale (zh_CN.UTF-8)"  serveral times

<pre>
admin@Accton-AS7712-32X:~$
admin@Accton-AS7712-32X:~$ sc
scp           script        scriptreplay
admin@Accton-AS7712-32X:~$ scp -bash: warning: setlocale: LC_CTYPE: cannot change locale (zh_CN.UTF-8)
-bash: warning: setlocale: LC_CTYPE: cannot change locale (zh_CN.UTF-8)
-bash: warning: setlocale: LC_CTYPE: cannot change locale (zh_CN.UTF-8)
-bash: warning: setlocale: LC_CTYPE: cannot change locale (zh_CN.UTF-8)

Accton-AS7712-32X:  localhost:
admin@Accton-AS7712-32X:~$ scp
</pre>

two way to fix this:

1. disable sshd receive locale from remote 
2. configure an default locale

**Comment by lguohan** [comment]
do you have command to install the default locale package? if yes, then can you install it and check the default size. we'd like en_us as the default locale.

**Comment by richard28530** [comment]
I resolve this by below modification in build_debian.sh

#Adds a locale to a debian system in non-interactive mode
sudo sed -i '/^#.* en_US.* /s/^#//' $FILESYSTEM_ROOT/etc/locale.gen && \
    sudo sed -i "\$aLANG=en_US.UTF-8" $FILESYSTEM_ROOT/etc/default/locale && \
    sudo LANG=C DEBIAN_FRONTEND=noninteractive chroot $FILESYSTEM_ROOT locale-gen "en_US.UTF-8"

**Comment by lguohan** [comment]
can you submit an PR, thanks.
