### ISSUE TITLE
upgrade configuration restore

### ISSUE THREAD

**Issue by richard28530** [Azure/sonic-buildimage#1682]
when upgrade all the cofiguration in /etc/sonic will be backup into a folder old_config.
while boot up the minigraph.xml and others(pg_profile_lookup.ini) is not restored from old_config, which will cause some command link 'show interface trans eep' not working.

after each upgrade the directory is deeper.

<pre>
/host/image-master.0-dirty-20180409.140605/rw/etc/sonic$ tree .
.
|-- config_db.json
|-- minigraph.xml
`-- old_config
    |-- config_db.json
    |-- deployment_id_asn_map.yml
    |-- init_cfg.json
    |-- old_config
    |   |-- buffer.json
    |   |-- buffer1.json
    |   |-- config_db.json
    |   |-- deployment_id_asn_map.yml
    |   |-- minigraph.xml
    |   |-- old_config
    |   |   |-- config_db.json
    |   |   |-- deployment_id_asn_map.yml
    |   |   |-- init_cfg.json
    |   |   |-- minigraph.xml
    |   |   |-- snmp.yml
    |   |   |-- sonic_version.yml
    |   |   `-- updategraph.conf
    |   |-- pg_profile_lookup.ini
    |   |-- snmp.yml
    |   |-- sonic_version.yml
    |   `-- updategraph.conf
    |-- snmp.yml
    |-- sonic_version.yml
    `-- updategraph.conf

3 directories, 24 files
</pre>

**Comment by lguohan** [comment]
Thanks for reporting, addressed in #1884
