### ISSUE TITLE
How can I modify broadcom chip register value on boot

### ISSUE THREAD

**Issue by ForzaTian** [Azure/sonic-buildimage#1686]
Now  I'm developing a new project based on BCM56960, according to actual demand, I need to modify some register value, I can use command " bcmcmd -v "m *****" "after sonic bootup.But it's not convient for client use. So is there any way to modify register value on booting time?
Many thanks for your help.

**Comment by zhenggen-xu** [comment]
would it work if you just add those commands into a script and let your start script to call it after syncd is up?

**Comment by ForzaTian** [comment]
@zhenggen-xu ,thanks for your reply. I have tried to add the commands in start script, but according to boot up flow, broadcom's sdk haven't been initialized when start script is executing, so the command can't work as expect.
So how can I execute those command after syncd is up?
Thanks for your advice again.

**Comment by richard28530** [comment]
you can refer to led_proc_init.soc

**Comment by ForzaTian** [comment]
@richard28530 Thanks for your advice. It seems can be used by my scrip.
