### ISSUE TITLE
Orchagent error messages in syslog

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#1697]
Seeing the following orchagent messages in syslog:

```
syslog.10.gz:May 10 10:43:07.496468 str-s6000-acs-7 ERR orchagent: :- doAclTableTask: Unknown table attribute 'SERVICES'
syslog.10.gz:May 10 10:43:07.496994 str-s6000-acs-7 ERR orchagent: :- doAclTableTask: Failed to create ACL table. Table configuration is invalid
```

**Comment by lguohan** [comment]
check in current master image to see if we still have this problem or not.

**Comment by jleveque** [comment]
Haven't tested an image from master, but from examining code, it appears to still exist. I believe I created this issue as a reminder to myself.

https://github.com/Azure/sonic-swss/blob/8bfdea086f14bbe420846d42c607760999cbdcc3/orchagent/aclorch.cpp#L1956

Need to improve logic to ignore control plane ACLs in aclorch.cpp. `doAclTableTask()` should most likely return immediately if ACL is of type "CTRLPLANE." Currently, "CTRLPLANE" ACL will flag failure, as will the "SERVICES" attribute.

**Comment by jleveque** [comment]
Resolved via https://github.com/Azure/sonic-swss/pull/708 / https://github.com/Azure/sonic-buildimage/pull/2320
