### ISSUE TITLE
Failed to build libnl3 

### ISSUE THREAD

**Issue by Alibaba-Sonic** [Azure/sonic-buildimage#1757]
Hi,

We are seeing the following error while building the sonic image

'https://anonscm.debian.org/git/collab-maint/libnl3.git/' not found

Looks like the above git repo have been discontinued. Tried https://alioth-archive.debian.org/git/collab-maint/libnl3.git/, however "git checkout -f b77c0e49cb" failed.

Do you have a backup git repo or replacement link?

Thanks,
Haiyang

===========

(08:59:10) Cloning into 'libnl3'...
(08:59:10) fatal: repository 'https://anonscm.debian.org/git/collab-maint/libnl3.git/' not found
(08:59:10) Makefile:17: recipe for target '/sonic/target/debs/libnl-3-200_3.2.27-1_amd64.deb' failed
(08:59:10) make[1]: *** [/sonic/target/debs/libnl-3-200_3.2.27-1_amd64.deb] Error 128
(08:59:10) make[1]: Leaving directory '/sonic/src/libnl3'
(08:59:10) [  FAIL LOG END  ] [ target/debs/libnl-3-200_3.2.27-1_amd64.deb ]
(08:59:10) make: *** [target/debs/libnl-3-200_3.2.27-1_amd64.deb] Error 1
(08:59:10) slave.mk:183: recipe for target 'target/debs/libnl-3-200_3.2.27-1_amd64.deb' failed
(08:59:10) Makefile:70: recipe for target 'all' failed
(08:59:10) make: *** [all] Error 2

**Comment by jleveque** [comment]
This should be fixed since the following PR was merged: https://github.com/Azure/sonic-buildimage/pull/1755

Please confirm.

**Comment by Alibaba-Sonic** [comment]
Thanks Joe LeVeque
-----------------------------------------------------------------
Sender:Joe LeVeque <notifications@github.com
Sent at:2018 Jun 1 (Fri) 12:3
Recipient:Azure/sonic-buildimage <sonic-buildimage@noreply.github.com
Cc:Sonic项目合作 <sonic-external@list.alibaba-inc.com>; Author <author@noreply.github.com
Subject:Re: [Azure/sonic-buildimage] Failed to build libnl3 (#1757
This should be fixed since the following PR was merged: #175
Please confirm
