### ISSUE TITLE
The kernel header of sonic-slave-base docker changes to linux-headers-3.16.0-6-amd64

### ISSUE THREAD

**Issue by MickeyZhan** [Azure/sonic-buildimage#1758]
When I download the newest SONIC source code and build, the kernel header of sonic-slave-base:latest docker has changed to linux-headers-3.16.0-6-amd64, but my kernel version is 3.16.0-5, whether does it
affect the kernel driver module to load.

**Comment by qiluo-msft** [comment]
Thanks for the report. We are investigating.

**Comment by qiluo-msft** [comment]
Hi @MickeyZhan, according to my best understanding, it will not affect the building of any kernel driver. Actually it will not be used at all. All kernel module will specify their expected kernel version. You may search KVERSION in source tree to get the idea.

The package was introduced by a recent update of https://packages.debian.org/jessie/linux-headers-amd64. The dependency tree looks like:
dkms -> linux-headers-amd64 -> linux-headers-3.16.0-6-amd64

Let me know if any build is broken by this in case.
