### ISSUE TITLE
bcmsh does not support up/down arrow, backspace or history

### ISSUE THREAD

**Issue by zhenggen-xu** [Azure/sonic-buildimage#1763]
**Description**

bcmsh does not support up/down arrow, backspace or history.

This made it not useful for interactive shell.   

To fix this, we need upgrade socat so it supports READLINE feature and we should pass READLINE parameter when calling from socat to UNIX socket.

**Steps to reproduce the issue:**
1.
drivshell>^[[A
-- up arrow case.

drivshell>^[[B
                         
--- down arrow case

drivshell>l3 nat^H    

-- backspace case

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by qiluo-msft** [comment]
Welcome any pull request on this! Thanks Zhenggen!
