### ISSUE TITLE
How SONIC-P4 Connects with ODL？

### ISSUE THREAD

**Issue by wjf1993** [Azure/sonic-buildimage#1784]
Description
I install sonic-p4（543） docker image in my device.But when i try to make sonic-p4 connect with opendaylight and it connect failed.Is it because the current sonic-p4 doesn't have the grpc function yet?

**Briefly describe the problem you are having in a few paragraphs.
**Steps to reproduce the issue:**
**Describe the results you received:**
**Describe the results you expected:**
**Additional information you deem important (e.g. issue happens only occasionally):******

**Comment by lguohan** [comment]
there is no support for connecting sonic-p4 to opendaylight.

**Comment by sinaebrahimi** [comment]
Hi, the issue was created in 2018. Is there any support for ODL or ONOS right now? (Or maybe ONOS and ODL should support SONIC as an on-switch NOS.)
