### ISSUE TITLE
Mass ARP causes snmpd shows "ERR snmpd[34]: Error allocating more space for arpcache. Cache will continue to be limited to 4096 entries"

### ISSUE THREAD

**Issue by sunnogo** [Azure/sonic-buildimage#1874]
**Description**

Mass ARP causes snmpd shows "ERR snmpd[34]: Error allocating more space for arpcache. Cache will continue to be limited to 4096 entries"

**Steps to reproduce the issue:**

Not reproduce everytime due to realloc mechanism.

1. Configure your system to support 4K+ ARP
2. Configure a L3 interface
3. Send 4K+ ARP to that L3 interface.

It's a known bug [net-snmp bug 2678](https://sourceforge.net/p/net-snmp/bugs/2678/). And net-snmp has fix it ([link](https://sourceforge.net/p/net-snmp/code/ci/d6e7f8962b110a2cd65667b2c57a8a60ad3cd222/)). 

**Describe the results you received:**

Get syslog `ERR snmpd[34]: Error allocating more space for arpcache. Cache will continue to be limited to 4096 entries"`

**Describe the results you expected:**

Do not show such error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by lguohan** [comment]
@sunnogo , thanks for reporting. It looks like there is a fix. would you be able to incorporate the patch in snmpd build? https://github.com/Azure/sonic-buildimage/tree/master/src/snmpd

**Comment by lguohan** [comment]
@sunnogo , are you talk about another thread?

**Comment by sunnogo** [comment]
@lguohan Yeah... Sorry, let me copy it to the right thread. And delete it.
