### ISSUE TITLE
[help]Questions about some pull requests

### ISSUE THREAD

**Issue by yangbashuang** [Azure/sonic-buildimage#1899]
**Description**
have opened some pull requests on sonic-buildimage two months ago:
https://github.com/Azure/sonic-buildimage/pull/1702
https://github.com/Azure/sonic-buildimage/pull/1703

these two PRs has been opened over two months and not reviewed yet
is there something wrong in these PRs or what i was missing
what should i do next?

thanks

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
#1703 merged.
#1702 in progress.
