### ISSUE TITLE
Quanta IX1B wrong platform name

### ISSUE THREAD

**Issue by MichelMoriniaux** [Azure/sonic-buildimage#1907]
Quanta T7032-IX1B fails to install correctly because ONIE expects a different platform name

**Steps to reproduce the issue:**
1. compile latest ONIE 
   a. https://github.com/opencomputeproject/onie/blob/master/machine/quanta/quanta_common_rglbmc/INSTALL
2. install ONIE
3. install sonic-broadcom.bin
4. reboot

**Describe the results you received:**
1. console fails to be available ( T7032 expects ttyS1, sonic by default goes to ttyS0 )
2. no ports come up , all addresses are bad, everything FUBAR

**Describe the results you expected:**
1- proper install and running system

**Additional information you deem important (e.g. issue happens only occasionally):**

during the ONIE install process the platform is detected as x86_64-quanta_ix1b_rglbmc-r0
but in sonic-buildimage the switch platform is named x86_64-quanta_ix1b_32x-r0
because of this the sonic install silently fails and the switch fails to function properly

the only way to make a correct install is to:
1. inside ONIE edit /etc/machine.conf
in the last 2 lines of the file replace rglbmc by 32x
2. onie-nos-install URL

once booted a show platform syseeprom now executes and shows
...
Platform Name        0x28  30 x86_64-quanta_common_rglbmc-r0
...
which is the ONIE platform name for this family of switches

**Comment by lguohan** [comment]
addressed in #2065
