### ISSUE TITLE
[virtual-switch] Port config ini type for portsyncd hardcoded

### ISSUE THREAD

**Issue by NehaRajeM** [Azure/sonic-buildimage#1990]
port_config.ini hardcoded for Force10 routers in supervisord.conf for virtual switch.
https://github.com/Azure/sonic-buildimage/blob/master/platform/vs/docker-sonic-vs/supervisord.conf

[program:portsyncd]
command=/usr/bin/portsyncd -p /usr/share/sonic/device/x86_64-dell_s6000_s1220-r0/Force10-S6000/port_config.ini
priority=6
autostart=false
autorestart=false
stdout_logfile=syslog
stderr_logfile=syslog

Expected: based on the hwsku/platform set, the appropriate port_config.ini should be selected.

**Comment by stcheng** [comment]
this leads to another issue that when executing `show platform summary` the output will be empty. It is better to have the platform set as virtual switch and have a specific config_config.ini file for this platform.

**Comment by lguohan** [comment]
@taoyl-ms currently vs can only support Force10-S6000 port_config ini. as long as the vs has 32 ports, we do not need to change that. 

What is the issue you are facing?

**Comment by NehaRajeM** [comment]
So you mean to say that vs cannot support Arista devices as of now?
I am trying to use an Arista Minigraph to bring up the sonic vs.
So I need to use the corresponding port_config.ini [x86_64-arista_7050_qx32/Arista-7050-QX32/port_config.ini] otherwise it does not get configured correctly.

**Comment by taoyl-ms** [comment]
The correct solution should be renaming the platform name to a vs-specific name and let create symbol links for vs-supported skus under it. Reusing the Force10 platform string for virtual switch is confusing.

**Comment by stcheng** [comment]
@taoyl-ms agree.

**Comment by lguohan** [comment]
@NehaRajeM , it can support arista device. @taoyl-ms , we have discussed the separate the alias from port_config.ini for virtual switch. any progress on that?

**Comment by yxieca** [comment]
We have different hwskus on vs now. this issue has been addressed.
