### ISSUE TITLE
Jenkins build failure buildimage-p4-all.

### ISSUE THREAD

**Issue by jcmathews** [Azure/sonic-buildimage#2005]
Hi,

I was trying to build sonicbuildimage for p4. However the build failed while generating sairedis package.
Further investigation, the error seems to be because of not copying  SAI header files to /usr/include/sai.
However this didn't help. Further i tried checking  Jenkins build and looks like build failure with same cause is there too and it is not resolved for a long time.

Can somebody help on this?

Regards,
Jessel.

**Comment by jcmathews** [comment]
logs from jenkins:
make[4]: Entering directory '/sonic/src/sonic-sairedis/SAI/test'
rm -f bin/basic_router  obj/gtest.a obj/gtest_main.a obj/*.o
make -C sai_ut clean
make[5]: Entering directory '/sonic/src/sonic-sairedis/SAI/test/sai_ut'
rm -f ../bin/sai_ut_vr ../bin/sai_ut_rif ../bin/sai_ut_nh ../bin/sai_ut_nhg ../bin/sai_ut_nbr ../bin/sai_ut_route ../bin/sai_ut_fdb ../bin/sai_ut_vlan ../bin/sai_ut_lag ../bin/sai_ut_stp *.o routing/*.o switching/*.o
make[5]: Leaving directory '/sonic/src/sonic-sairedis/SAI/test/sai_ut'
make[4]: Leaving directory '/sonic/src/sonic-sairedis/SAI/test'
make[3]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
rm -rf *.egg-info
make[2]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
   dh_clean
	rm -f debian/libsaithrift-dev.substvars
	rm -f debian/libsaithrift-dev.*.debhelper
	rm -rf debian/libsaithrift-dev/
	rm -f debian/python-saithrift.substvars
	rm -f debian/python-saithrift.*.debhelper
	rm -rf debian/python-saithrift/
	rm -f debian/*.debhelper.log
	rm -f debian/files
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
	rm -f *-stamp
make[1]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
 debian/rules build
make[1]: Entering directory '/sonic/src/sonic-sairedis/SAI'
dh build
   dh_testdir
   dh_auto_configure
   debian/rules override_dh_auto_build
make[2]: Entering directory '/sonic/src/sonic-sairedis/SAI'
/usr/bin/make DESTDIR=/sonic/src/sonic-sairedis/SAI/debian saithrift-build 
make[3]: Entering directory '/sonic/src/sonic-sairedis/SAI'
make -C test/saithrift
make[4]: Entering directory '/sonic/src/sonic-sairedis/SAI/test/saithrift'
mkdir -p ./src/obj
/usr/bin/thrift -o ./src --gen cpp -r ./src/switch_sai.thrift
g++ -I/usr/include/sai -I. -std=c++11 -c src/gen-cpp/switch_sai_rpc.cpp -o src/obj/switch_sai_rpc.o
g++ -I/usr/include/sai -I. -std=c++11 -c src/gen-cpp/switch_sai_types.cpp -o src/obj/switch_sai_types.o
g++ -I/usr/include/sai -I. -std=c++11 -c src/gen-cpp/switch_sai_constants.cpp -o src/obj/switch_sai_constants.o
g++ -I/usr/include/sai -I. -std=c++11 -c src/switch_sai_rpc_server.cpp -o src/obj/switch_sai_rpc_server.o -I/usr/include/sai -I. -std=c++11 -I./src/gen-cpp
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_fdb_entry(const switch_sai::sai_thrift_fdb_entry_t&, sai_fdb_entry_t*)':
src/switch_sai_rpc_server.cpp:219:18: error: 'sai_fdb_entry_t' has no member named 'bv_id'
       fdb_entry->bv_id = (sai_object_id_t) thrift_fdb_entry.bv_id;
                  ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_port_attributes(const std::vector<switch_sai::sai_thrift_attribute_t>&, sai_attribute_t*, sai_object_id_t**)':
src/switch_sai_rpc_server.cpp:245:20: error: 'SAI_PORT_ATTR_PKT_TX_ENABLE' was not declared in this scope
               case SAI_PORT_ATTR_PKT_TX_ENABLE:
                    ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_fdb_flush_attributes(const std::vector<switch_sai::sai_thrift_attribute_t>&, sai_attribute_t*)':
src/switch_sai_rpc_server.cpp:331:20: error: 'SAI_FDB_FLUSH_ATTR_BV_ID' was not declared in this scope
               case SAI_FDB_FLUSH_ATTR_BV_ID:
                    ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_lag_attributes(const std::vector<switch_sai::sai_thrift_attribute_t>&, sai_attribute_t*)':
src/switch_sai_rpc_server.cpp:435:20: error: 'SAI_LAG_ATTR_PORT_VLAN_ID' was not declared in this scope
               case SAI_LAG_ATTR_PORT_VLAN_ID:
                    ^
src/switch_sai_rpc_server.cpp: In member function 'void switch_sai_rpcHandler::sai_thrift_parse_hostif_attributes(sai_attribute_t*, const std::vector<switch_sai::sai_thrift_attribute_t>&) const':
src/switch_sai_rpc_server.cpp:522:94: error: 'SAI_HOSTIF_NAME_SIZE' was not declared in this scope
                   std::memcpy(attr_list[i].value.chardata, attribute.value.chardata.c_str(), SAI_HOSTIF_NAME_SIZE);
                                                                                              ^
Makefile:77: recipe for target 'src/obj/switch_sai_rpc_server.o' failed
make[4]: *** [src/obj/switch_sai_rpc_server.o] Error 1
make[4]: Leaving directory '/sonic/src/sonic-sairedis/SAI/test/saithrift'
Makefile:29: recipe for target 'saithrift-build' failed
make[3]: *** [saithrift-build] Error 2
make[3]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
debian/rules:26: recipe for target 'override_dh_auto_build' failed
make[2]: *** [override_dh_auto_build] Error 2
make[2]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
debian/rules:23: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
dpkg-buildpackage: error: debian/rules build gave error exit status 2
[  FAIL LOG END  ] [ target/debs/libsaithrift-dev_1.0.4_amd64.deb ]
slave.mk:237: recipe for target 'target/debs/libsaithrift-dev_1.0.4_amd64.deb' failed
make: *** [target/debs/libsaithrift-dev_1.0.4_amd64.deb] Error 1
Makefile.work:97: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/data/johnar/workspace/p4/buildimage-p4-all'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE

**Comment by sajishv** [comment]
I too am looking for a resolution of this issue.

**Comment by blakedot** [comment]
Same here; I'd like to try out sonic-p4 but it looks like the Jenkins build has been failing for 6 months...

**Comment by sslvjun** [comment]
Hi, Is this problem solved now? 

I modified `src/sonic-swss/configure.ac`， and it built success. 
```Makefile
diff --git a/configure.ac b/configure.ac
index a33396c..aa2e37a 100644
--- a/configure.ac
+++ b/configure.ac
@@ -38,7 +38,7 @@ AC_ARG_ENABLE(gtest,
 esac],[gtest=false])
 AM_CONDITIONAL(GTEST, test x$gtest = xtrue)
 
-CFLAGS_COMMON="-std=c++11 -Wall -fPIC -Wno-write-strings -I/usr/include/libnl3 -I/usr/include/swss"
+CFLAGS_COMMON="-std=c++11 -Wall -fPIC -Wno-write-strings -I/sonic/src/sonic-sairedis/SAI/inc/ -I/usr/include/libnl3 -I/usr/include/swss"
 
 AM_CONDITIONAL(sonic_asic_platform_barefoot,   test x$CONFIGURED_PLATFORM = xbarefoot)
 AM_COND_IF([sonic_asic_platform_barefoot],
```

Then another problem occured:
```Bash
dpkg: dependency problems prevent configuration of python-sonic-utilities:
 python-sonic-utilities depends on psmisc; however:
  Package psmisc is not installed.

dpkg: error processing package python-sonic-utilities (--install):
 dependency problems - leaving unconfigured
Installing new version of config file /etc/iproute2/rt_dsfield ...
Installing new version of config file /etc/iproute2/rt_protos ...
dpkg: dependency problems prevent configuration of quagga:
 quagga depends on logrotate (>= 3.2-11); however:
  Package logrotate is not installed.

dpkg: error processing package quagga (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (215-17+deb8u7) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 python-sonic-utilities
 quagga
The command '/bin/sh -c dpkg -i debs/libnl-3-200_3.2.27-2_amd64.deb debs/libnl-route-3-200_3.2.27-2_amd64.deb debs/libnl-genl-3-200_3.2.27-2_amd64.deb debs/libnl-nf-3-200_3.2.27-2_amd64.deb debs/libhiredis0.13_0.13.3-2_amd64.deb debs/libnl-cli-3-200_3.2.27-2_amd64.deb debs/libthrift-0.9.3_0.9.3-2_amd64.deb debs/python-thrift_0.9.3-2_amd64.deb debs/thrift-compiler_0.9.3-2_amd64.deb debs/sai-p4-bm_1.0.0_amd64.deb debs/libswsscommon_1.0.0_amd64.deb debs/p4-sai-adapter_0.1-0_amd64.deb debs/libsairedis_1.0.0_amd64.deb debs/libsaimetadata_1.0.0_amd64.deb debs/libteam5_1.26-1_amd64.deb debs/python-swsscommon_1.0.0_amd64.deb debs/swss_1.0.0_amd64.deb debs/syncd_1.0.0_amd64.deb debs/redis-tools_3.2.4-1~bpo8+1_amd64.deb debs/redis-server_3.2.4-1~bpo8+1_amd64.deb debs/libteamdctl0_1.26-1_amd64.deb debs/libteam-utils_1.26-1_amd64.deb debs/sonic-device-data_1.0-1_all.deb debs/python-sonic-utilities_1.2-1_all.deb debs/iproute2_4.9.0-1_amd64.deb debs/quagga_0.99.24.1-2.1_amd64.deb' returned a non-zero code: 1
[  FAIL LOG END  ] [ target/docker-sonic-p4.gz ]
slave.mk:418: recipe for target 'target/docker-sonic-p4.gz' failed
make: *** [target/docker-sonic-p4.gz] Error 1
Makefile.work:132: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr1/sunzhaozhong/test/sonic-buildimage'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
```
I modified `platform/p4/docker-sonic-p4/Dockerfile` and  `platform/p4/docker-sonic-p4/Dockerfile.j2`:

```Makefile
--- Dockerfile.bak      2018-11-14 21:19:20.288000000 -0500
+++ Dockerfile  2018-11-14 20:44:38.244000000 -0500
@@ -41,7 +41,9 @@
                        python-tabulate \
                        bash-completion \
                        libelf1 \
-                       libmnl0
+                       libmnl0 \
+                       psmisc \
+                       logrotate
 
 RUN pip install setuptools
 RUN pip install py2_ipaddress
@@ -74,4 +76,4 @@
 RUN echo "docker-sonic-p4" > /etc/hostname
 RUN touch /etc/quagga/zebra.conf
 
-ENTRYPOINT ["/bin/bash"]
+ENTRYPOINT ["/bin/bash"]
\ No newline at end of file
```
and
```Makefile
--- Dockerfile.j2.bak   2018-11-14 21:19:34.760000000 -0500
+++ Dockerfile.j2       2018-11-14 20:42:30.348000000 -0500
@@ -41,7 +41,9 @@
                        python-tabulate \
                        bash-completion \
                        libelf1 \
-                       libmnl0
+                       libmnl0 \
+                       psmisc \
+                       logrotate
 
 RUN pip install setuptools
 RUN pip install py2_ipaddress
```

I got `docker-sonic-p4.gz`  finally! But when I ran the `p4_test` script, It executed `ping` failed.

**Comment by blakedot** [comment]
thanks @jcmathews! Is this upstream & Jenkins-buildable again?
