### ISSUE TITLE
Can't instantiate abstract class SfpUtil with abstract methods get_transceiver_change_event

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#2017]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

https://groups.google.com/forum/#!topic/sonicproject/7YeMVQRbbLs

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by jleveque** [comment]
All plugins which inherit the base class **must** define a concrete implementation of *every* abstract property and method, otherwise this error will be encountered. When adding a new abstract property or method to a base class, one should also add concrete implementations to all subclasses in the project. The concrete methods can simply be stubs with a "TODO" comment and a `raise NotImplementedError` instruction.

**Comment by keboliu** [comment]
as Joe mentioned, in the implementation of xcvrd, some more method was added, all the platforms need to implement this method or add a stub.

**Comment by lguohan** [comment]
@keboliu, please add a stub for all other platforms which do not have implementation yet. The reason is that we cannot break other platforms when introducing new functions.

**Comment by xinliu-seattle** [comment]
@keboliu, can you input the repro steps, I will ping all platform vendors to add this support.

**Comment by keboliu** [comment]
@xinliu-seattle for the way to reproduce this issue, please check this link https://groups.google.com/forum/#!topic/sonicproject/7YeMVQRbbLs. 
@lguohan I'd like to resolve this issue and have Xcvrd work on all the platforms, but I have concern to modify the code on other platforms directly, it's not about efforts, it's about capability and ownership.

**Comment by keboliu** [comment]
@lguohan @xinliu-seattle  I can create PR to add stubs to other platforms, but without verification as you know I don't have other platforms.  Do we have some list for the platform should be included or just all the platforms?

**Comment by lguohan** [comment]
all platforms with sfputil.py plugin in their folder.

**Comment by lguohan** [comment]
we cannot ask you to do the test, but the syntax of the code should be correct.

**Comment by keboliu** [comment]
please check PR https://github.com/Azure/sonic-buildimage/pull/2038

**Comment by lguohan** [comment]
thanks!
