### ISSUE TITLE
Download portal is down

### ISSUE THREAD

**Issue by sergeimonakhov** [Azure/sonic-buildimage#20357]
#### Description

Hi, [Download portal](https://sonic-build.azurewebsites.net/) return 503

#### Steps to reproduce the issue:
1. Open https://sonic-build.azurewebsites.net/
2. 
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by DanielaMurin** [comment]
I'm also unable to access the portal.
@zhangyanzhao, would you happen to know who might be able to assist?
Thank you.

**Comment by judyjoseph** [comment]
Able to access @DanielaMurin could you try again

**Comment by arf20** [comment]
Still down for me, 503

:/
