### ISSUE TITLE
Config DB is incomplete right after config load_minigraph

### ISSUE THREAD

**Issue by andriymoroz-mlnx** [Azure/sonic-buildimage#2044]
**Description**

Due to counters start delay if “config save” is called right after “config load_minigraph” Config DBs on disk and in memory will be different ("FLEX_COUNTER_TABLE" will be missing)

**Steps to reproduce the issue:**
1. config load_minigraph
2. config save (right after load_minigraph)
3. wait 3 min
4. rename /etc/sonic/config_db.json
5. config save 
6. compare new /etc/sonic/config_db.json and renamed in step 4

**Describe the results you received:**
DB saved later will be different. "FLEX_COUNTER_TABLE"

**Describe the results you expected:**
Saved DBs to be the same

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of show version:**
```
SONiC Software Version: SONiC.HEAD.6-6cf2d10
Distribution: Debian 8.11
Kernel: 3.16.0-5-amd64
Build commit: 6cf2d10
Build date: Thu Sep  6 18:06:54 UTC 2018
Built by: johnar@jenkins-worker-3

``` 

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
I think the diff came 3 minutes later was due to the buffer profiles that are generated by the buffermgrd. Save them or not doesn't hurt next boot. I think it is ok.
