### ISSUE TITLE
 make target/debs/sonic-device-data_1.0-1_all.deb-clean, wait for a long time

### ISSUE THREAD

**Issue by fillmorechen0928** [Azure/sonic-buildimage#2096]
The command "make target/debs/sonic-device-data_1.0-1_all.deb-clean" cause to wait for a long time.(more than 30 minutes)

It did not happend at 20180514 version of SONIC project.

![default](https://user-images.githubusercontent.com/35523342/46194780-f8854780-c334-11e8-9617-a70776bff976.png)

**Comment by yxieca** [comment]
@fillmorechen0928 

Please issue make with NOSTRETCH=1, e.g:

make NOSTRETCH=1 target/debs/sonic-device-data_1.0-1_all.deb
make NOSTRETCH=1 target/debs/sonic-device-data_1.0-1_all.deb-clean

Thanks,
Ying

**Comment by yxieca** [comment]
Please feel free to enter new issue or reopen if the issue still persists.
