### ISSUE TITLE
Kernel: config reload does not clean up old loopback IP address from kernel

### ISSUE THREAD

**Issue by nikos-github** [Azure/sonic-buildimage#2102]
Boot device into sonic. Change config_db.json and assign a new IP address into lo. Perform config reload. The previous IP address is not cleaned up from the kernel which causes BGP peering over the loopback to never come up. Subsequent changes result in stale IP addresses on lo to accumulate.

root@sonic:/home/admin# ip addr show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.1.0.32/32 brd 10.1.0.32 scope global lo
       valid_lft forever preferred_lft forever
    inet 1.2.3.4/32 brd 1.2.3.4 scope global lo
       valid_lft forever preferred_lft forever
    inet 5.6.7.8/32 brd 5.6.7.8 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

**Comment by jipanyang** [comment]
Probably you could update interface-config.sh to do ip addr flush for loopback interface.  Not sure if eth0 has similar problem, since it won't be deleted/created like other frontpanel netdev interface.

**Comment by nikos-github** [comment]
@jipanyang Not that simple.

**Comment by jipanyang** [comment]
@nikos-github please be more specific.  
interfaces-config service will call interface-config.sh for reconfiguring host interface,  current "ifdown lo && ifup lo"will leave previous IP there, but if  ip addr flush dev lo is called before systemctl restart networking, it should work.  Did you see problem with it?

**Comment by nikos-github** [comment]
@jipanyang  You can't do an ip addr flush dev lo because it will also kill the ipv4 and ipv6 localhost addresses. Nothing will work after that.

The right approach is to check the db, find out if there is an address for the loopback in there, and remove that only. Can't  blindly remove all the non-localhost addresses.

**Comment by xinliu-seattle** [comment]
Aptra will propose the fix.

**Comment by nikos-github** [comment]
Not reproducible in latest image (consistently seen in image a month ago) since at the moment, INTF_TABLE is cleared of all entries. The following diffs can also solve the problem if seen again, in config reload function. Placing the diffs here for completeness and closing this issue.

def _loopback_address_delete(config_db):
    loopbacks = config_db.keys(config_db.CONFIG_DB, 'LOOPBACK_INTERFACE|*')
    for key in loopbacks:
        loopback = ConfigDBConnector.deserialize_key(key)
        if loopback == key or len(loopback) < 3:
            continue
        interface = loopback[1]
        if interface == "Loopback0":
            interface = "lo"
        ip_addr = loopback[2]
        command = "ip address delete {} dev {}".format(ip_addr, interface)
        run_command(command, display_cmd=True)
