### ISSUE TITLE
Please help merge PR 2043 ( centec platform update )

### ISSUE THREAD

**Issue by yangbashuang** [Azure/sonic-buildimage#2227]
**Description**
Please help merge PR 2043:
https://github.com/Azure/sonic-buildimage/pull/2043

hung for two months

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stcheng** [comment]
already merged, thanks!
