### ISSUE TITLE
config interface shutdown/startup doesnt work in 201803 branch

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-buildimage#2272]
**Description**

config interface shutdown/startup doesnt work in 201803 branch

**Steps to reproduce the issue:**
1. sudo config interface shutdown/startup Ethernet2
2. Error is thrown and interface status  is not changed 

**Describe the results you received:**

	root@sonic-z9100-02:~# ifconfig  Ethernet2
	Ethernet2 Link encap:Ethernet  HWaddr 4c:76:25:e4:e4:c2
			  inet6 addr: fe80::4e76:25ff:fee4:e4c2/64 Scope:Link
			  UP BROADCAST RUNNING MULTICAST  MTU:9100  Metric:1
			  RX packets:0 errors:0 dropped:0 overruns:0 frame:0
			  TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
			  collisions:0 txqueuelen:1000
			  RX bytes:0 (0.0 B)  TX bytes:1313 (1.2 KiB)

	root@sonic-z9100-02:~#
	root@sonic-z9100-02:~# show interface status Ethernet2
	  Interface    Lanes    Speed    MTU           Alias    Oper    Admin
	-----------  -------  -------  -----  --------------  ------  -------
	  Ethernet2    51,52      50G   9100  fiftyGigE1/1/2      up       up
	root@sonic-z9100-02:~#
	root@sonic-z9100-02:~# config interface shutdown Ethernet2
	ifdown: interface Ethernet2 not configured
	root@sonic-z9100-02:~# config interface startup Ethernet2
	Ignoring unknown interface Ethernet2=Ethernet2.
	root@sonic-z9100-02:~#

**Describe the results you expected:**

The interfaces status should change accordingly upon config interface shutdown/startup

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

	root@sonic-z9100-02:~# show version
	SONiC Software Version: SONiC.HEAD.87-ce54ef7
	Distribution: Debian 8.11
	Kernel: 3.16.0-6-amd64
	Build commit: ce54ef7
	Build date: Tue Oct 30 20:16:25 UTC 2018
	Built by: johnar@jenkins-worker-4

	Docker images:
	REPOSITORY                 TAG                 IMAGE ID            SIZE
	docker-syncd-brcm          HEAD.87-ce54ef7     0b12467446fc        372.6 MB
	docker-orchagent-brcm      HEAD.87-ce54ef7     91edc486eeff        294.3 MB
	docker-orchagent-brcm      latest              91edc486eeff        294.3 MB
	docker-lldp-sv2            HEAD.87-ce54ef7     99a1eac6d870        306.7 MB
	docker-lldp-sv2            latest              99a1eac6d870        306.7 MB
	docker-dhcp-relay          HEAD.87-ce54ef7     0aea3298eaf6        288.7 MB
	docker-dhcp-relay          latest              0aea3298eaf6        288.7 MB
	docker-database            HEAD.87-ce54ef7     d195c5be63cf        288.7 MB
	docker-database            latest              d195c5be63cf        288.7 MB
	docker-teamd               HEAD.87-ce54ef7     f4962e114572        294.1 MB
	docker-teamd               latest              f4962e114572        294.1 MB
	docker-snmp-sv2            HEAD.87-ce54ef7     656cf2f5657b        326.5 MB
	docker-snmp-sv2            latest              656cf2f5657b        326.5 MB
	docker-router-advertiser   HEAD.87-ce54ef7     5b348d48d8ed        286.4 MB
	docker-router-advertiser   latest              5b348d48d8ed        286.4 MB
	docker-platform-monitor    HEAD.87-ce54ef7     3f80a1a03448        308.3 MB
	docker-platform-monitor    latest              3f80a1a03448        308.3 MB
	docker-fpm-quagga          HEAD.87-ce54ef7     e98213aceb12        300.7 MB
	docker-fpm-quagga          latest              e98213aceb12        300.7 MB
	docker-syncd-brcm-rpc      latest              65c5c84841c9        621 MB
	docker-syncd-brcm          latest              65c5c84841c9        621 MB

	root@sonic-z9100-02:~#

**Comment by stcheng** [comment]
On 201803 branch, please still use `ip link set [up|down]` command to toggle the interfaces.

**Comment by chitra-raghavan** [comment]
Thanks
