### ISSUE TITLE
Dell 6000: show platform syseeprom invalid output

### ISSUE THREAD

**Issue by vivekvijaykumar** [Azure/sonic-buildimage#2275]
**Description**
show platform syseeprom errors out on a DellS6000 box running onie version 3.20.1.3 as recommended in the quick start wiki guide in SONiC.

The sonic version is based on Build commit: b1d290c

The machine.conf file as follows - 
root@spine-1:/home/admin# cat /host/machine.conf
onie_version=3.20.1.3
onie_vendor_id=674
onie_platform=x86_64-dell_s6000_s1220-r0
onie_machine=dell_s6000_s1220
onie_machine_rev=0
onie_arch=x86_64
onie_config_version=1
onie_build_date="2015-05-03T16:20-0700"
onie_partition_type=gpt
onie_kernel_version=3.2.35

root@spine-1:/home/admin# show platform summary
Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom

root@spine-1:/home/admin# show platform syseeprom
TLV Name             Len Value
-------------------- --- -----
Invalid TLV field starting at EEPROM offset 0
(checksum valid)

From the onie platform the dump for the eeprom works fine.  

**Steps to reproduce the issue:**
1. make sure onie version 3.20.1.3 is running on Dell S6000
2. install sonic build based on commit b1d290c
3. check output of show platform syseeprom

**Describe the results you received:**
root@spine-1:/home/admin# show platform syseeprom
TLV Name             Len Value
-------------------- --- -----
Invalid TLV field starting at EEPROM offset 0
(checksum valid)

**Describe the results you expected:**
Output should be something like this - 

TlvInfo Header:
Id String:    TlvInfo
Version:      1
Total Length: 92
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21   8 S6000-ON
Part Number          0x22   6 07VJDK
Serial Number        0x23  20 CN07VJDK282985710021
Label Revision       0x27   3 A04
Base MAC Address     0x24   6 EC:F4:BB:FE:90:1A
ONIE Version         0x29   8 3.20.1.3
MAC Addresses        0x2A   2 129
Manufacturer         0x2B   2 FF
Vendor Name          0x2D   4 DELL
Service Tag          0x2F   7 DS0RX42
CRC-32               0xFE   4 0xC64CA48B

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vivekvijaykumar** [comment]
@vharish02 Can we please get someone from Dell to take a look?

**Comment by jleveque** [comment]
@vivekvijaykumar: Did https://github.com/Azure/sonic-buildimage/pull/2315 resolve your issue? If so, please close this.

**Comment by jleveque** [comment]
No response for months. Assuming this issue has been resolved; closing.
