### ISSUE TITLE
Dell S6000: wrong lane mapping in port_config.ini 

### ISSUE THREAD

**Issue by vivekvijaykumar** [Azure/sonic-buildimage#2276]
**Description**

admin@sonic:~$ show platform sum
Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom

I am noticing that the lane maps for the first 6 ports seemed to be swapped based on LLDP neighbors and also by manually checking it by doing single port shut/no shut test. 

current lane map is as follows - 

  Ethernet0      29,30,31,32      40G   
  Ethernet4      25,26,27,28      40G    
  Ethernet8      37,38,39,40      40G    
 Ethernet12      33,34,35,36      40G    
 Ethernet16      41,42,43,44      40G    
 Ethernet20      45,46,47,48      40G    

 
I believe based on LLDP and manual shut/no shut tests the lane maps should be - 

  Ethernet0      25,26,27,28      
  Ethernet4      29,30,31,32      
  Ethernet8      33,34,35,36      
 Ethernet12      37,38,39,40      
 Ethernet16      45,46,47,48   
 Ethernet20      41,42,43,44 

Could we verify that the current lane map for this platform on all ports is valid ? 

**Steps to reproduce the issue:**
1. Install latest sonic on Dell_S6000 <x86_64-dell_s6000_s1220-r0>
2. Wait for all ports to be up with a neighboring 40G platform
3. Do individual shut/no shut and see the peer ports that flap. The wiring will show as though interfaces are cross wired

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

  
    ```
   root@sonic:/home/admin# cat /host/machine.conf
onie_version=3.20.1.3
onie_vendor_id=674
onie_platform=x86_64-dell_s6000_s1220-r0
onie_machine=dell_s6000_s1220
onie_machine_rev=0
onie_arch=x86_64
onie_config_version=1
onie_build_date="2015-05-03T16:20-0700"
onie_partition_type=gpt
onie_kernel_version=3.2.35
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vivekvijaykumar** [comment]
@vharish02 Can we please get someone from Dell to take a look?

**Comment by vivekvijaykumar** [comment]
@lguohan , thanks for the update . I see on the sonic wiki for support [hw](https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms)  that Dell S600-ON is listed as supported.  It also says Dell S6100-ON is supported .  Since the SONIC buildimage is building for S6000, could we update the wiki so it avoids confusion (given that the onie_platform name is also identical between S6000 and S6000-ON)

**Comment by Anandaraj-Maharajan** [comment]
@vivekvijaykumar We are looking in to it. We will make necessary modifications for S6000-ON and raise a PR soon. Update from normal FTOS to SONiC in normal is not a straight forward step.

**Comment by yxieca** [comment]
Information has been provided by Guohan's comments.
