### ISSUE TITLE
Port Based Flow control malfunction

### ISSUE THREAD

**Issue by linalvin** [Azure/sonic-buildimage#2279]
**Description**
when specific port is encountered traffic congestion, there is no any pause frame sent out.
we have tried with 201803 and 201807
this situation has happened in 201807, not in 201803

**Steps to reproduce the issue:**
1. let three ports(Ethernet0, Ethernet1, Ethernet3) are up
2. set up the packets are directed from both Ethernet0 and Ethernet1 to Ethernet3
3. when Ethernet3 is overload, there is no any pause frame packet sent out.

**Describe the results you received:**
capture the packet from Ethernet3. no any pause frame packets

**Describe the results you expected:**
Ethernet3 can send out pause frame packet

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
    201807
    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vemulabalaji** [comment]
Can you update with detailed configuration commands.

**Comment by linalvin** [comment]
box information:
- broadcom chip: Trident 3

commands:
portconfig -p Ethernet0 -s 25000 -f fc -vv
portconfig -p Ethernet1 -s 25000 -f fc -vv
portconfig -p Ethernet2 -s 25000 -f fc -vv
portconfig -p Ethernet3 -s 25000 -f fc -vv

config vlan add 11
config vlan add 12
config vlan member add 11 Ethernet0 -u
config vlan member add 11 Ethernet1 -u
config vlan member add 11 Ethernet2 -u
config vlan member add 11 Ethernet3
config vlan member add 12 Ethernet3 -u

Topology:
                       |------------------------------|		
     TC-1-------|Eth0                                     |
                       |                                            |
     TC-2-------|Eth1      Maple                     |Eth3-----------TC-4
                       |                                            |
     TC-3-------|Eth2                                     |
                       |-----------------------------  |

Traffic is from TC-1, TC-2, TC-3 to TC-4

bcmcmd "ps"
ps
                 ena/        speed/ link auto    STP                  lrn  inter   max   cut   loop
           port  link  Lns   duplex scan neg?   state   pause  discrd ops   face frame  thru?  back
       xe0(  1)  up     1   25G  FD   SW  No   Forward  TX RX   None   FA     KR  9122    No
       xe1(  2)  up     1   25G  FD   SW  No   Forward  TX RX   None   FA     KR  9122    No
       xe2(  3)  up     1   25G  FD   SW  No   Forward  TX RX   None   FA     KR  9122    No
       xe3(  4)  up     1   25G  FD   SW  No   Forward  TX RX   None   FA     KR  9122    No
                                                                                ^^^^^<<== 
                                                                                Pause frame is enabled, but doesn't send out it.
