### ISSUE TITLE
Questions about how to have PR access and add opcode for notification in sonic-py-swsssdk/configdb.py ?

### ISSUE THREAD

**Issue by batmancn** [Azure/sonic-buildimage#2304]
**Description**
I have two questions: 
1) how to give PR? 
2) if it's good to add opcode for notification in configdb.py to verify the difference between these:
```
"AAA": null
"AAA": {}
```

**My solution**
This is my solution: https://github.com/Azure/sonic-py-swsssdk/issues/41
I don't know where to report this issue better, so I report both.

**Comment by stcheng** [comment]
in order to create a pull request, you could first fork the branch and then create a commit in your fork. then you could create a pull request against the current master with your fork's master.

**Comment by yxieca** [comment]
Information provided. Please reopen if further question exists.
