### ISSUE TITLE
[Help]how to add a new build task in sonic-jenkins for a platform

### ISSUE THREAD

**Issue by yangbashuang** [Azure/sonic-buildimage#2313]
**Description**
i want to add build task for centec platform in:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/centec/
no build job for 201803 201807 and master
plaese someone can show me how to do it

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
Done.
