### ISSUE TITLE
Broadcom SAI binary package version mismatch

### ISSUE THREAD

**Issue by pawmas** [Azure/sonic-buildimage#2328]
Hi SONiC team,

I'm just a little confused. I didn't find any information that SONiC team is contributing its own SAI implementation for Broadcom ASIC chips and as far as I know SONiC is using Broadcom SAI binary package. Am I correct?

So in the _sai.mk_ at master branch I can see that to build SONiC image there is used Broadcom SAI binary package in version _3.1.3.5_. On the second side we have available binary package of SAI implementation from official Broadcom's Github repo but we can find there only older version - _3.1.3.4_. 

Why this difference between _3.1.3.4_ and _3.1.3.5_? Does it mean that SONiC/Microsoft team contribute their own SAI implementation for Broadcom chips? Or Broadcom company will release _3.1.3.5_ binary package soon (just SONiC team has access to it earlier)?

Thanks in advance for explain my concerns.

**Comment by yxieca** [comment]
@pawmas

You are correct, SONiC team doesn't come up with another implementation of browdcom SAI.

Please contact Broadcom for individual release of SAI.

Thanks and regards,
Ying

**Comment by stcheng** [comment]
Yes. We mainly update the subversion due to some early bug fixes.

**Comment by pawmas** [comment]
@stcheng ,
But fixed bugs was still development under Broadcom company as @yxieca mentioned?

Thanks
