### ISSUE TITLE
please help merge 2347 on the branch of 201811 to support nephos platform

### ISSUE THREAD

**Issue by simonJi2018** [Azure/sonic-buildimage#2369]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
Change has been included for a while.
