### ISSUE TITLE
Is the branch, 201811  (Broadcom SAI 3.3 GA release) supporting the Broadcom TD3 chip yet?

### ISSUE THREAD

**Issue by pollyhsu2git** [Azure/sonic-buildimage#2370]
**Description**
Based on the Broadcom SAI release note, the Broadcom SAI 3.3.X.X supports the Broadcom TD3 chp.  However, based on our testing here on the branch, 201811, it seems ***`NOT`***

We just want to clarify that:
1. Whether SONiC has any plan to support the Broadcom TD3 chip?
2. If YES, when will it be?

**Steps to reproduce the issue:**
1. git clone the SONiC code base, and checkout the branch, 201811.
2. Do the porting of our TD3 model (AS7726-32X) based on the SONiC porting guide.
3. The syncd initialized failed with the following error messages:

**Describe the results you received:**
Nov  3 17:32:36.851910 sonic ERR syncd#syncd: sai_api_initialize:105 BRCM SAI ver: [3.3.3.1], OCP SAI ver: [1.3.3], SDK ver: [6.5.13]
Nov  3 17:32:39.041327 sonic INFO syncd#supervisord: syncd PCI unit 0: Dev 0xb870, Rev 0x01, Chip BCM56870_A0, Driver BCM56870_A0#015
Nov  3 17:32:39.041327 sonic INFO syncd#supervisord: syncd #015#015
Nov  3 17:32:39.041327 sonic INFO syncd#supervisord: syncd Initializing platform#015#015
Nov  3 17:32:39.148944 sonic INFO syncd#supervisord: syncd SOC unit 0 attached to PCI device BCM56870_A0#015
Nov  3 17:32:39.152045 sonic INFO syncd#supervisord: syncd Boot flags: Cold boot#015
Nov  3 17:32:39.153589 sonic INFO syncd#supervisord: syncd rc: unit 0 device BCM56870_A0#015
Nov  3 17:32:39.971735 sonic INFO syncd#supervisord: syncd 0:_cmd_cancun_file_load: Fail to open/load file bcm56870_a0_cmh.pkg. (Invalid parameter)#015
Nov  3 17:32:39.971735 sonic INFO syncd#supervisord: syncd 0:_cmd_cancun_file_load: Fail to open/load file bcm56870_a0_cch.pkg. (Invalid parameter)#015
Nov  3 17:32:39.971735 sonic INFO syncd#supervisord: syncd 0:_cmd_cancun_file_load: Fail to open/load file bcm56870_a0_ceh.pkg. (Invalid parameter)#015
Nov  3 17:32:40.003190 sonic INFO syncd#supervisord: syncd 0:soc_cancun_cch_reg_set: CCH file is not loaded#015
Nov  3 17:32:40.011619 sonic INFO syncd#supervisord: syncd 0:_cmd_cancun_file_load: Fail to open/load file bcm56870_a0_cih.pkg. (Invalid parameter)#015
....
root@sonic:/# cd /
root@sonic:/# find . -name *.pkg
root@sonic:/#
 <NO FOUND>

**Describe the results you expected:**
1. syncd is initialized successfully.
2. swss is initialized successfully
3. the port / interface is up and running

**Additional information you deem important (e.g. issue happens only occasionally):**

root@sonic:/home/admin# show platform summary
Platform: x86_64-accton_as7726_32x-r0
HwSKU: Accton-AS7726-32X
ASIC: broadcom
root@sonic:/home/admin# show ver
SONiC Software Version: SONiC.201811.0-dirty-20181210.140616
Distribution: Debian 9.6
Kernel: 4.9.0-7-amd64
Build commit: ff9eb73
Build date: Mon Dec 10 06:10:31 UTC 2018
Built by: polly_hsu@Tainan-Linux-216

    **Attach debug file `sudo generate_dump`:**
[sonic_dump_sonic_20161103_174424.tar.gz](https://github.com/Azure/sonic-buildimage/files/2661991/sonic_dump_sonic_20161103_174424.tar.gz)

**Comment by PrabhuSreenivasan** [comment]
Hi,
Below logs suggest cancun files are missing and that could be root cause of your issue. Are they available on SONiC? If not, you may want to get in touch with Broadcom marketing.

Nov 3 17:32:39.971735 sonic INFO syncd#supervisord: syncd 0:_cmd_cancun_file_load: Fail to open/load file bcm56870_a0_cmh.pkg. (Invalid parameter)#15
Nov 3 17:32:39.971735 sonic INFO syncd#supervisord: syncd 0:_cmd_cancun_file_load: Fail to open/load file bcm56870_a0_cch.pkg. (Invalid parameter)#15
Nov 3 17:32:39.971735 sonic INFO syncd#supervisord: syncd 0:_cmd_cancun_file_load: Fail to open/load file bcm56870_a0_ceh.pkg. (Invalid parameter)#15

**Comment by pollyhsu2git** [comment]
@PrabhuSreenivasan 
Um, On SONiC, the Broadcom SAI 3.3 GA release is built / released by MS co-working with Broadcom.  We are trying to clarify whether this chip family will be supported here (MS / Broadcom).

**Comment by Peter5Lin** [comment]
Hi
I'm porting Broadcom TD3 in SAI 3.3.4.3-1 and get some error message after port was inserted

Feb 11 01:31:29.718115 sonic INFO syncd#supervisord: ledinit 0:soc_cmicx_led_link_status: Led msg id 0x0 send failed, Error Code -3#015
Feb 11 01:31:30.980540 sonic INFO syncd#supervisord: ledinit 0:soc_iproc_data_send_wait: No response for msg 0#015
Feb 11 01:31:30.980683 sonic INFO syncd#supervisord: ledinit 0:soc_cmicx_led_link_status: Led msg id 0x0 send failed, Error Code -3#015
Feb 11 01:31:32.239502 sonic INFO syncd#supervisord: ledinit 0:soc_iproc_data_send_wait: No response for msg 4#015
Feb 11 01:31:32.239502 sonic INFO syncd#supervisord: ledinit 0:soc_cmicx_led_speed: Led msg id 0x4 send failed, Error Code -3#015
Feb 11 01:31:32.245943 sonic INFO syncd#supervisord: ledinit #015#015
Feb 11 01:31:32.246061 sonic INFO syncd.sh[2265]: 2019-02-11 01:31:32,245 INFO exited: ledinit (exit status 0; expected)

I checked M0 firmware was loaded

Feb 11 01:30:48.090761 sonic INFO syncd#supervisord: ledinit /sonic/platform/led_proc_init.soc#015#015
Feb 11 01:30:48.104493 sonic INFO syncd#supervisord: ledinit Loading M0 Firmware located at /usr/share/sonic/hwsku/led-auto.bin#015

have I met the same issue? or I'm missing some configuration need to set?

**Comment by yxieca** [comment]
No. SAI 3.3 doesn't have TD3 support. Sorry for taking so long to answer.
