### ISSUE TITLE
incorrect way to detect fast-reboot

### ISSUE THREAD

**Issue by rameshsanth** [Azure/sonic-buildimage#2380]
inconsistent strings used in /proc/cmdline to detect fast reboot. 
[dockers/docker-orchagent/swssconfig.sh](https://github.com/Azure/sonic-buildimage/blob/dedd5624a06aaae81425b9c03714f6801e7b6251/dockers/docker-orchagent/swssconfig.sh#L6)  uses "*fast-reboot*" to detect fast reboot

Looks like SONIC_BOOT_TYPE=fast is the string that is saved by sonic-utilities:scripts/fast-reboot file

Correct usage
[docker_image_ctl.j2](https://github.com/Azure/sonic-buildimage/blob/3f530241d9610a9463d588fdebeb87700aecaecc/files/build_templates/docker_image_ctl.j2#L11) checks for "SONIC_BOOT_TYPE=fast" in cmdline

**Comment by qiluo-msft** [comment]
The doc https://github.com/Azure/SONiC/blob/master/doc/warm-reboot/system-warmboot.md#details-of-kernel-arguments explain the design choice we made. Because of backward-compatibility issue, we made it inconsistent on purpose.

Let me know if you have more questions on the design doc.
