### ISSUE TITLE
Ports stripped the vlan tag in vs-kvm

### ISSUE THREAD

**Issue by dawnbeauty** [Azure/sonic-buildimage#2398]
**Description**
I use vs-kvm image for some l2 switch testing. And i found that the vlan tag of ingress packets will be stripped on sonic ports (not veths).
What i do :
   1.  Send a tagged packet to vnet(created by libvirt/qemu on vs host server)
   2.  Capture(tcpdump -i xxx -n -vvv -Q in) on veth(eth29) and its peer port (Ethernet112)
   Captured packet from veth keep the vlan tag as what i send , but the one from sonic port stripped the vlan tag. 
   3.  Then, I disable the rx_vlan_offload of the two ports (veth/sonic port), and try again, nothing changed.
   4.  Em, maybe the nic driver do not support rx_vlan_offload, so i changed the nic type of vs-kvm from default(rtl8139) to e1000/virtio, but nothing changed.

Did i miss something? Or the driver of these types of nic can not keep the vlan tag in AF_PACKET socket buffer?

**Comment by lguohan** [comment]
we have found this issue and will fix it in the virtual switch in sonic-sairedis.

**Comment by dawnbeauty** [comment]
Thanks, i'll test with the latest vs kvm image.

**Comment by kcudnik** [comment]
i think this is already fixed, closing issue
