### ISSUE TITLE
Sonic building image is unsuccessful

### ISSUE THREAD

**Issue by bsbsrkg** [Azure/sonic-buildimage#2418]
**Description**
Building Sonic image is not successful

ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
man: error while loading shared libraries: libmandb-2.7.0.2.so: cannot open shared object file
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
man: error while loading shared libraries: libmandb-2.7.0.2.so: cannot open shared object file
dh_installman: man --recode UTF-8 ./initramfs\.conf\.5 > initramfs\.conf\.5\.new returned exit code 127
debian/rules:4: recipe for target 'binary' failed
make[2]: *** [binary] Error 127
make[2]: Leaving directory '/sonic/src/initramfs-tools/initramfs-tools'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Makefile:8: recipe for target '/sonic/target/debs/initramfs-tools_0.120_all.deb' failed
make[1]: *** [/sonic/target/debs/initramfs-tools_0.120_all.deb] Error 2
make[1]: Leaving directory '/sonic/src/initramfs-tools'
[  FAIL LOG END  ] [ target/debs/initramfs-tools_0.120_all.deb ]
slave.mk:191: recipe for target 'target/debs/initramfs-tools_0.120_all.deb' failed
make: *** [target/debs/initramfs-tools_0.120_all.deb] Error 1
Makefile:81: recipe for target 'all' failed
make: *** [all] Error 2
**Steps to reproduce the issue:**
1. Git clone Sonic repo
2. Follow steps till make config platform, and then make all
3. We can see the issue

**Describe the results you received:**

Compiling error
**Describe the results you expected:**

Successful compilation
**Additional information you deem important (e.g. issue happens only occasionally):**
https://github.com/Azure/sonic-buildimage/issues/957 is wrt p4 compiling. But I'm seeing error for otger platform also
    **Output of `show version`:**
Na
    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
 
```
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
man: error while loading shared libraries: libmandb-2.7.0.2.so: cannot open shared object file
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
man: error while loading shared libraries: libmandb-2.7.0.2.so: cannot open shared object file
dh_installman: man --recode UTF-8 ./initramfs\.conf\.5 > initramfs\.conf\.5\.new returned exit code 127
debian/rules:4: recipe for target 'binary' failed
make[2]: *** [binary] Error 127
make[2]: Leaving directory '/sonic/src/initramfs-tools/initramfs-tools'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Makefile:8: recipe for target '/sonic/target/debs/initramfs-tools_0.120_all.deb' failed
make[1]: *** [/sonic/target/debs/initramfs-tools_0.120_all.deb] Error 2
make[1]: Leaving directory '/sonic/src/initramfs-tools'
[  FAIL LOG END  ] [ target/debs/initramfs-tools_0.120_all.deb ]
slave.mk:191: recipe for target 'target/debs/initramfs-tools_0.120_all.deb' failed
make: *** [target/debs/initramfs-tools_0.120_all.deb] Error 1
Makefile:81: recipe for target 'all' failed
make: *** [all] Error 2
    ```

**Comment by lguohan** [comment]
if you are using ubuntu 18.04, can you change the storage driver to overlayfs. besides, there is also a fix [be9f3ad](https://github.com/Azure/sonic-buildimage/commit/be9f3ad7c1aabcb1aecfd8212b1acbee5c9581e0)

**Comment by bsbsrkg** [comment]
Thanks for the info

Regards
Ramakrishna

**Comment by kattamamatha** [comment]
When i am running "make init" command i am facing following issues:

+++ Making init +++
BLDENV=stretch make -f Makefile.work init
make[1]: Entering directory '/home/brcmcoe/sonic-buildimage'
fatal: not a git repository (or any of the parent directories): .git
Makefile.work:169: recipe for target 'init' failed
make[1]: *** [init] Error 128
make[1]: Leaving directory '/home/brcmcoe/sonic-buildimage'
Makefile:19: recipe for target 'init' failed
make: *** [init] Error 2

Does anyone faced this issue before while building SONiC image.

**Comment by jleveque** [comment]
@kattamamatha: It appears as though the ".git" directory which Git uses for tracking is missing from your sonic-buildimage directory. Maybe you accidentally deleted it? I recommend you do a fresh clone of your sonic-buildimage repo.

**Comment by kattamamatha** [comment]
Previous issue got resolved when i cloned again,But now i am facing new issue:

brcmcoe@brcmcoe-ProLiant-DL180-Gen9:~/sonic-buildimage$ make init
+++ Making init +++
BLDENV=stretch make -f Makefile.work init
make[1]: Entering directory '/home/brcmcoe/sonic-buildimage'
Cloning into '/home/brcmcoe/sonic-buildimage/platform/barefoot/sonic-platform-modules-arista'...
Cloning into '/home/brcmcoe/sonic-buildimage/platform/broadcom/sonic-platform-modules-arista'...
fatal: unable to access 'https://github.com/aristanetworks/sonic/': Proxy CONNECT aborted
fatal: clone of 'https://github.com/aristanetworks/sonic' into submodule path '/home/brcmcoe/sonic-buildimage/platform/broadcom/sonic-platform-modules-arista' failed
Failed to clone 'platform/broadcom/sonic-platform-modules-arista'. Retry scheduled
Cloning into '/home/brcmcoe/sonic-buildimage/platform/mellanox/mlnx-sai/SAI-Implementation'...
fatal: unable to access 'https://github.com/Mellanox/SAI-Implementation/': Proxy CONNECT aborted
fatal: clone of 'https://github.com/Mellanox/SAI-Implementation' into submodule path '/home/brcmcoe/sonic-buildimage/platform/mellanox/mlnx-sai/SAI-Implementation' failed
Failed to clone 'platform/mellanox/mlnx-sai/SAI-Implementation'. Retry scheduled
Cloning into '/home/brcmcoe/sonic-buildimage/platform/p4/SAI-P4-BM

**Comment by jleveque** [comment]
Looks like git had trouble connecting to GitHub. I say try again now that a couple days have passed.

Are you using a proxy at all?

**Comment by kattamamatha** [comment]
Yeah, I added proxies at all places, now it's working fine.

**Comment by jleveque** [comment]
Good to hear. I will close this issue.

**Comment by kattamamatha** [comment]
Now, I am facing other issues, while executing make configure
PLATFORM=broadcom.
Saying :

"python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-cjlza0mw/mockredispy/

The command 'bin/sh -c pip3 install mockredispy==2.9.3'returned a non-zero
code :1

Makefile.work:138:recipe for target 'configure'failed

**Comment by kattamamatha** [comment]
When  i am executing make configure PLATFORM=broadcom , i am facing few errors saying:

Step 15/37 : RUN pip3 install mockredispy==2.9.3

  ---> Running in 02b4b51e7122
Collecting mockredispy==2.9.3
  Downloading https://files.pythonhosted.org/packages/0a/f1/d7db33898151aa9a1d647654cac55d01a5a1302fa4244af5fb5d3021f848/mockredispy-2.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "/usr/lib/python3.5/http/client.py", line 1107, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
        self.endheaders(body)
      File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
        self.send(msg)
      File "/usr/lib/python3.5/http/client.py", line 877, in send
        self.connect()
      File "/usr/lib/python3/dist-packages/setuptools/ssl_support.py", line 190, in connect
        sock, cert_reqs=ssl.CERT_REQUIRED, ca_certs=self.ca_bundle
      File "/usr/lib/python3.5/ssl.py", line 1077, in wrap_socket
        ciphers=ciphers)
      File "/usr/lib/python3.5/ssl.py", line 760, in __init__
        self.do_handshake()
      File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
        self._sslobj.do_handshake()
      File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [Errno 104] Connection reset by peer
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 747, in open_url
        return open_with_auth(url, self.opener)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 948, in _socket_timeout
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 1067, in open_with_auth
        fp = opener(request)
      File "/usr/lib/python3.5/urllib/request.py", line 466, in open
        response = self._open(req, data)
      File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
        '_open', req)
      File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
        result = func(*args)
      File "/usr/lib/python3/dist-packages/setuptools/ssl_support.py", line 161, in https_open
        lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
      File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jtq1ahsu/mockredispy/setup.py", line 29, in <module>
        'with_redis = mockredis.noseplugin:WithRedis'
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 687, in easy_install
        not self.always_copy, self.local_index
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 636, in fetch_distribution
        dist = find(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 617, in find
        dist.download_location = self.download(dist.location, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 566, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 805, in _download_url
        return self._attempt_download(url, filename)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 811, in _attempt_download
        headers = self._download_to(url, filename)
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 710, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "/usr/lib/python3/dist-packages/setuptools/package_index.py", line 761, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#sha256=f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98: [Errno 104] Connection reset by peer
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jtq1ahsu/mockredispy/
The command '/bin/sh -c pip3 install mockredispy==2.9.3' returned a non-zero code: 1
Makefile.work:138: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
make[1]: Leaving directory '/sonic-buildimage'
Makefile:19: recipe for target 'configure' failed
make: *** [configure] Error 2

**Comment by jleveque** [comment]
Looks like a download error. Maybe a transient issue with the peer or network? I suggest trying again after allowing some time to pass.

**Comment by kattamamatha** [comment]
So, it isn't  some issue with Github ,I mean do we get this error  If we
clone master  of sonic -buildimage from github repo instead of stable
branch,

**Comment by jleveque** [comment]
What do you mean by "stable branch"?

**Comment by kattamamatha** [comment]
Like instead of cloning master we can also clone recent release branch
right like 201905 something like that

**Comment by jleveque** [comment]
I believe all release branches from 201803 onward should not have any build issues.

**Comment by kattamamatha** [comment]
Fine, I will try building it again and get back to you with output. Thank
you

**Comment by kattamamatha** [comment]
I tried build again, but still getting the same error.

**Comment by stcheng** [comment]
@kattamamatha you're still facing the downloading error?

**Comment by kattamamatha** [comment]
Yes same error, I cloned 201904 branch.

**Comment by stcheng** [comment]
https://files.pythonhosted.org/packages/0a/f1/d7db33898151aa9a1d647654cac55d01a5a1302fa4244af5fb5d3021f848/mockredispy-2.9.3.tar.gz
I could download this file. Check your network connectivity?

**Comment by kattamamatha** [comment]
I can download those files from browser, but in 15/37 step these files are
downloading in docker there I am facing issues.

**Comment by stcheng** [comment]
could you manually verify this by entering the docker and try to download the file?
