### ISSUE TITLE
lo address not synced to the asic

### ISSUE THREAD

**Issue by jipanyang** [Azure/sonic-buildimage#2427]
Changes in [intfmgrd]: Merge intfsyncd into intfmgrd:  https://github.com/Azure/sonic-swss/pull/635
has broken the existing behavior that address on lo will be syncd to asic.

lo intf processing in intforch gets voided with this commit.

The original change for syncing lo address to asic:   https://github.com/Azure/sonic-swss/pull/103

**Comment by marian-pritsak** [comment]
https://github.com/Azure/sonic-swss/pull/742
