### ISSUE TITLE
Reboot takes too much time

### ISSUE THREAD

**Issue by stepanblyschak** [Azure/sonic-buildimage#2429]
**Description**

Reboot takes too much time.
It seems related to a docker engine upgrade (https://github.com/Azure/sonic-buildimage/pull/2417)
```
[ **    ] (1 of 2) A stop job is running for …MD container (2min 10s / 2min 50s)
```

**Steps to reproduce the issue:**
1. sudo reboot
2. Observe that reboot takes too much time
3. ...
As a result our deploy task fails

**Describe the results you received:**
Reboot takes more than 5 min to finish

**Describe the results you expected:**
Reboot takes less than 5 min to finish

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by johcheun** [comment]
This is also observed in barefoot platforms, and community test cases that involves reboot are failing due to docker timing out, and reboot taking longer than expected causing ansible test case to fail.

**Comment by lguohan** [comment]
addressed in https://github.com/Azure/sonic-buildimage/commit/bfe46e0f1dd1b1e4769317ec46e31e8ada4d2dba
