### ISSUE TITLE
%syslogtag% not complete

### ISSUE THREAD

**Issue by richard28530** [Azure/sonic-buildimage#2433]
https://github.com/Azure/sonic-buildimage/blob/b57a3766227841b1f7dcb7ee99a3626db510e741/dockers/docker-database/Dockerfile.j2#L4

should be
<pre>
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf
</pre>

**Comment by jleveque** [comment]
Thanks for posting this issue!
