### ISSUE TITLE
solve package build dependency issue

### ISSUE THREAD

**Issue by caizhenghui** [Azure/sonic-buildimage#2467]
**Description**

I'm trying to write my own sai module to support new platform. Is there a way to force the deb packages in the dependency to be built/installed before building my own sai package? 
I have put the following in my sai.mk file 
$(XXX_SAI))_DEPENDS += $(LIBHIREDIS_DEV) $(LIBSWSSCOMMON_DEV)
But at the time of building my sai package, those two packages are not installed. Please help.

**Comment by lguohan** [comment]
Can you take a look at this document. 

https://github.com/Azure/sonic-buildimage/blob/master/README.buildsystem.md

**Comment by xinliu-seattle** [comment]
@caizhenghui, I will close this. Please reopen if you still have questions on this.
