### ISSUE TITLE
Enabling Fast-reboot command in s6100 loaded with T0 topo getting Failed unmounting /host error

### ISSUE THREAD

**Issue by mfriyas** [Azure/sonic-buildimage#2500]
Description:-

Loaded latest master  build 843  in s6100 and enable fast-reboot command in device , its throwing Failed unmounting /host.

Failed logs:-

root@sonic:/home/admin# fast-reboot
[FAILED] Failed unmounting /host.  >>>>>>>>>>>>>>>>>>> error here
[  OK  ] Unmounted /run/docker/netns/default.
[  OK  ] Unmounted /boot.
[  OK  ] Unmounted /var/lib/docker.
[  OK  ] Unmounted /var/log.
[  OK  ] Reached target Unmount All Filesystems.
[  OK  ] Stopped target Local File Systems (Pre).
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Reached target Shutdown.
[  998.495186] kexec_core: Starting new kernel
[    4.478680] rc.local[401]: + sonic-cfggen -y /etc/sonic/sonic_version.yml -v build_version
[    6.170090] rc.local[401]: + SONIC_VERSION=HEAD.843-cacff75
[    6.250141] rc.local[401]: + FIRST_BOOT_FILE=/host/image-HEAD.843-cacff75/platform/firsttime
[    6.364434] rc.local[401]: + process_reboot_cause
[    6.428548] rc.local[401]: + REBOOT_CAUSE_FILE=/var/cache/sonic/reboot-cause.txt
[    6.520422] rc.local[401]: + PREVIOUS_REBOOT_CAUSE_FILE=/var/cache/sonic/previous-reboot-cause.txt
[    6.628387] rc.local[401]: + [ -f /host/image-HEAD.843-cacff75/platform/firsttime ]
[    6.724450] rc.local[401]: + [ -f /var/cache/sonic/reboot-cause.txt ]
[    6.812466] rc.local[401]: + mv -f /var/cache/sonic/reboot-cause.txt /var/cache/sonic/previous-reboot-cause.txt
[    6.936616] rc.local[401]: + echo Unexpected reboot
[    6.996462] rc.local[401]: + [ ! -e /host/machine.conf ]
[    7.068471] rc.local[401]: + . /host/machine.conf
[    7.128440] rc.local[401]: + onie_version=3.25.1.3
[    7.188435] rc.local[401]: + onie_vendor_id=674
[    7.248436] rc.local[401]: + onie_platform=x86_64-dell_s6100_c2538-r0
[    7.336409] rc.local[401]: + onie_machine=dell_s6100_c2538
[    7.408346] rc.local[401]: + onie_machine_rev=0
[    7.468321] rc.local[401]: + onie_arch=x86_64
[    7.528343] rc.local[401]: + onie_config_version=1
[    7.588322] rc.local[401]: + onie_build_date=2016-09-07T19:17-0700
[    7.664310] rc.local[401]: + onie_partition_type=gpt
[    7.724316] rc.local[401]: + onie_kernel_version=4.1.28
[    7.796329] rc.local[401]: + onie_firmware=bios
[    7.860474] rc.local[401]: + onie_switch_asic=bcm
[    7.920440] rc.local[401]: + onie_skip_ethmgmt_macs=no
[    7.992520] rc.local[401]: + program_console_speed
[    8.071354] rc.local[401]: + cut -d , -f2
[    8.135381] rc.local[401]: + grep -Eo console=ttyS[0-9]+,[0-9]+
[    8.223074] rc.local[401]: + cat /proc/cmdline
[    8.287569] rc.local[401]: + speed=9600
[    8.344358] rc.local[401]: + [ -z 9600 ]
[    8.400454] rc.local[401]: + CONSOLE_SPEED=9600
[    8.460431] rc.local[401]: + sed -i s|\-\-keep\-baud .* %I| 9600 %I|g /lib/systemd/system/serial-getty@.service
[    8.584433] rc.local[401]: + systemctl daemon-reload
[    8.648398] rc.local[401]: + [ -f /host/image-HEAD.843-cacff75/platform/firsttime ]
[    8.756533] rc.local[401]: + exit 0

Debian GNU/Linux 9 sonic-s6100-01 ttyS1

sonic-s6100-01 login:
Debian GNU/Linux 9 sonic ttyS1

Show version:-

root@sonic:/var/core# show version
SONiC Software Version: SONiC.HEAD.843-cacff75
Distribution: Debian 9.6
Kernel: 4.9.0-8-amd64
Build commit: cacff75
Build date: Sun Jan 20 11:12:54 UTC 2019
Built by: johnar@jenkins-worker-3

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.843-cacff75    31a552c06bb1        359MB
docker-syncd-brcm          latest              31a552c06bb1        359MB
docker-orchagent-brcm      HEAD.843-cacff75    65cfb87e2212        284MB
docker-orchagent-brcm      latest              65cfb87e2212        284MB
docker-lldp-sv2            HEAD.843-cacff75    8f1c07fc7bf1        272MB
docker-lldp-sv2            latest              8f1c07fc7bf1        272MB
docker-dhcp-relay          HEAD.843-cacff75    15466ff7f5fd        254MB
docker-dhcp-relay          latest              15466ff7f5fd        254MB
docker-database            HEAD.843-cacff75    2b887b855c05        253MB
docker-database            latest              2b887b855c05        253MB
docker-teamd               HEAD.843-cacff75    afb0ace8c33a        272MB
docker-teamd               latest              afb0ace8c33a        272MB
docker-snmp-sv2            HEAD.843-cacff75    40650256060b        292MB
docker-snmp-sv2            latest              40650256060b        292MB
docker-router-advertiser   HEAD.843-cacff75    132a3d62f028        250MB
docker-router-advertiser   latest              132a3d62f028        250MB
docker-platform-monitor    HEAD.843-cacff75    c40042c50b9e        284MB
docker-platform-monitor    latest              c40042c50b9e        284MB
docker-fpm-quagga          HEAD.843-cacff75    42ee52e16ccb        279MB
docker-fpm-quagga          latest              42ee52e16ccb        279MB

**Comment by yxieca** [comment]
Unmount host will always happen because the tool required to umount is installed in this partition. This is not a new behavior.

We are looking into this issue but don't have a concrete solution yet. But I don't think this issue would affect fast reboot.

**Comment by mfriyas** [comment]
Fast reboot time  calculated as 18 secs, for multiple iterations. So fastreboot in sonic is working properly. As in sonic-mgmt there are few changes in script , so once we build the new sonic-mgmt repo we will validate the new fast reboot script

**Comment by TencentSwitchGroup** [comment]
> Unmount host will always happen because the tool required to umount is installed in this partition. This is not a new behavior.
> 
> We are looking into this issue but don't have a concrete solution yet. But I don't think this issue would affect fast reboot.

umount err ：Whether the problem has been solved
