### ISSUE TITLE
building Sonic throws error

### ISSUE THREAD

**Issue by bsbsrkg** [Azure/sonic-buildimage#2507]
Hi,
I'm compiling Sonic 201803 branch for Marvell platform. But getting the below issue.

++++++++++++++++++++++++++++++++++
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
man: error while loading shared libraries: libmandb-2.7.0.2.so: cannot open shared object file
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
man: error while loading shared libraries: libmandb-2.7.0.2.so: cannot open shared object file
dh_installman: man --recode UTF-8 ./initramfs\.conf\.5 > initramfs\.conf\.5\.new returned exit code 127
debian/rules:4: recipe for target 'binary' failed
make[2]: *** [binary] Error 127
make[2]: Leaving directory '/sonic/src/initramfs-tools/initramfs-tools'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Makefile:8: recipe for target '/sonic/target/debs/initramfs-tools_0.120_all.deb' failed
make[1]: *** [/sonic/target/debs/initramfs-tools_0.120_all.deb] Error 2
make[1]: Leaving directory '/sonic/src/initramfs-tools'
[  FAIL LOG END  ] [ target/debs/initramfs-tools_0.120_all.deb ]
slave.mk:191: recipe for target 'target/debs/initramfs-tools_0.120_all.deb' failed
make: *** [target/debs/initramfs-tools_0.120_all.deb] Error 1
Makefile:81: recipe for target 'all' failed
make: *** [all] Error 2
+++++++++++++++++++++++++++

**Comment by lguohan** [comment]
if you are using ubuntu 18.04, can you change the storage driver to overlayfs. besides, there is also a fix https://github.com/Azure/sonic-buildimage/commit/be9f3ad7c1aabcb1aecfd8212b1acbee5c9581e0

**Comment by lguohan** [comment]
the root cause of issue is https://github.com/moby/moby/issues/38420

temp workaround is here:
```
sudo apparmor_parser /etc/apparmor.d/usr.bin.man
```
