### ISSUE TITLE
acl-loader incremental update overwrites previously loaded ACL rules

### ISSUE THREAD

**Issue by wangxin** [Azure/sonic-buildimage#2509]
**Description**

If add ACL rules using "config acl update incremental" command, the previously added ACL rules are overwritten.

Adding ACL rules using command "acl-loader update increment" has the same issue.

**Steps to reproduce the issue:**
1. Create two json files. File1 conatins ACL rules 1,2,3,4,13,14. File2 contains ACL rules 5-12, 15-26.
2. Use "config acl update incremental file1.json" to add first part of the ACL rules. Use "show acl rule" to check the added rules.
3. Use "config acl update incremental file2.json" to add rest of the ACL rules.
4. Use "show acl rule" to list the added ACL rules. The rules added in step 2 are gone. Only ACL rules added in step 3 are listed.

**Describe the results you received:**
The incremental update always overwrites all the existing ACL rules.

**Describe the results you expected:**
I expected the incremental updating to merge the two configurations. In case of conflicts, the later configuration overrides previous configuration.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
$ show version
SONiC Software Version: SONiC.HEAD.868-39b60d2
Distribution: Debian 9.7
Kernel: 4.9.0-8-2-amd64
Build commit: 39b60d2
Build date: Tue Jan 29 19:54:09 UTC 2019
Built by: johnar@jenkins-worker-3
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```
[acl_rules_part1.json.txt](https://github.com/Azure/sonic-buildimage/files/2816866/acl_rules_part1.json.txt)
[acl_rules_part2.json.txt](https://github.com/Azure/sonic-buildimage/files/2816867/acl_rules_part2.json.txt)
[syslog_acl-loader.txt](https://github.com/Azure/sonic-buildimage/files/2816868/syslog_acl-loader.txt)

**Comment by lguohan** [comment]
it is by design. https://github.com/Azure/SONiC/wiki/ACL-Configuration-High-Level-Design
