### ISSUE TITLE
add a default fdb aging time 

### ISSUE THREAD

**Issue by richard28530** [Azure/sonic-buildimage#2547]
https://github.com/Azure/sonic-buildimage/blob/44551d0fb57d9fae3e46f36929fb4a0d66b1d375/dockers/docker-orchagent/switch.json.j2#L13

Currently some SAI implementation do not set a default fdb aging time while initialize switch.
suggest initialize one at swss startup.

<pre>
{# the range of hash_seed is 0-15 #}
{# set default hash seed to 0 #}
{% set hash_seed = 0 %}
{% if DEVICE_METADATA.localhost.type %}
{% if DEVICE_METADATA.localhost.type == "ToRRouter" %}
{% set hash_seed = 0 %}
{% elif DEVICE_METADATA.localhost.type == "LeafRouter" %}
{% set hash_seed = 10 %}
{% endif %}
{% endif %}
[
    {
        "SWITCH_TABLE:switch": {
            "fdb_aging_time": "300",
            "ecmp_hash_seed": "{{ hash_seed }}",
            "lag_hash_seed": "{{ hash_seed }}"
        },
        "OP": "SET"
    }
]
</pre>

**Comment by xinliu-seattle** [comment]
@praveen-li can you please help to review this ? thanks.

**Comment by praveen-li** [comment]
1.) I do not see a diff here. Is some thing wrong.

2.) Also I feel, this part has been addressed already with:
https://github.com/Azure/sonic-buildimage/pull/2365

Thanks.

**Comment by richard28530** [comment]
Close since there is already doing.
