### ISSUE TITLE
lm75 doesn't support written alarm to syslog.

### ISSUE THREAD

**Issue by TencentSwitchGroup** [Azure/sonic-buildimage#2646]
First of all, it's not a sonic-buildimage issue. But I think it's OK to commit this issue here.

[Linux kernel](https://github.com/torvalds/linux/blob/master/drivers/hwmon/lm78.c) supports written temperature sensors  alarm to syslog, only when the temperature sensors support alarm registers. But not all temperature sensors support this feature, for example LM75.

Many vendors use LM75, but SONiC doesn't define how to written a syslog when the temperature is higher then Thigh or lower than Tlow. 

Will SONiC define a way to write such syslog?

**Comment by xinliu-seattle** [comment]
@TencentSwitchGroup please help to clarify the issue. Your link is related to LM78 not LM75?

**Comment by sunnogo** [comment]
LM75 link is https://github.com/torvalds/linux/blob/master/drivers/hwmon/lm75.c.

**Comment by TencentSwitchGroup** [comment]
LM75 is https://github.com/torvalds/linux/blob/master/drivers/hwmon/lm75.c.

It's obviously that kernel support alarm feature in lm77/lm78, but not lm75.
I tested lm75  before, by setting Thigh lower that current temperature, but no syslog found.

**Comment by jleveque** [comment]
Hi @TencentSwitchGroup. Once we transition to the new SONiC platform API, all sensor data will be retrieved using the new platform API and logging to syslog will be handled by a daemon which calls retrieves sensor data using the new API.

**Comment by TencentSwitchGroup** [comment]
Great!
I also work on this now and plan to implement a syslog daemon. The daemon will record peripheral equipment events, such as high temperature alarm, fan / psu plug in or plug out.

**Comment by jleveque** [comment]
Closing, as the new platform API will eventually eliminate the need for lm-sensors in SONiC.
