### ISSUE TITLE
docker connect failure in the build

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#267]
https://sonic-jenkins.westus.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/277/console

+ BUILD_TEMPLATES=files/build_templates
+ IMAGE_CONFIGS=files/image_config
+ trap_push clean_sys
+ local oldcmd=true
+ local 'newcmd=clean_sys; true'
+ trap -- 'clean_sys; true' EXIT INT TERM HUP
+ _trap_push 'clean_sys; true'
+ local 'next=clean_sys; true'
++ sed -e 's/'\''/'\''\\'\'''\''/g'
++ echo 'clean_sys; true'
+ eval 'trap_push() {
        local oldcmd='\''clean_sys; true'\''
        local newcmd="$1; $oldcmd"
        trap -- "$newcmd" EXIT INT TERM HUP
        _trap_push "$newcmd"
    }'
+ sudo LANG=C chroot ./fsroot mount sysfs /sys -t sysfs
+ sudo chroot ./fsroot service docker start
mount: cgroup is already mounted or /sys/fs/cgroup/cpu busy
       cgroup is already mounted on /sys/fs/cgroup
mount: cgroup is already mounted or /sys/fs/cgroup/cpuacct busy
       cgroup is already mounted on /sys/fs/cgroup
mount: cgroup is already mounted or /sys/fs/cgroup/net_cls busy
       cgroup is already mounted on /sys/fs/cgroup
mount: cgroup is already mounted or /sys/fs/cgroup/net_prio busy
       cgroup is already mounted on /sys/fs/cgroup
Starting Docker: docker.
+ sudo chroot ./fsroot docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by oleksandrivantsiv** [comment]
Can you please assign this issue to me?

**Comment by lguohan** [comment]
yes, you are assigned to this issue.

**Comment by NStetskovych** [comment]
On the commit 799f0727a56d5caa5b96db03ad859c6a7d1e0e71
step to reproduce:
make configure PLATFORM=cavium
make

Finished target/sonic-cavium.bin
Executing rules for target/docker-fpm.gz-load
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
slave.mk:293: recipe for target 'target/docker-fpm.gz-load' failed
make: *** [target/docker-fpm.gz-load] Error 1
make: Leaving directory '/sonic'
Makefile:32: recipe for target 'all' failed
make: *** [all] Error 2


Running make second time fix the issue.
