### ISSUE TITLE
Failure trying to run: chroot /sonic-buildimage/fsroot mount -t proc proc /proc

### ISSUE THREAD

**Issue by Maikor** [Azure/sonic-buildimage#27]
Hello, 
I'm trying to build an image for Broadcom.

Step 1-3 is fine, the problem appears when I'm using **make** command in usage section.
Docker version 1.12.1, build 6f9534c

Error output:
>I: Extracting util-linux...
>I: Extracting liblzma5...
>I: Extracting zlib1g...
>W: Failure trying to run: chroot /sonic-buildimage/fsroot mount -t proc proc /proc
>W: See /sonic-buildimage/fsroot/debootstrap/debootstrap.log for details
>Makefile:141: recipe for target 'target/sonic-generic.bin' failed
>make: *** [target/sonic-generic.bin] Error 1
>rm src/initramfs-tools/initramfs-tools_0.120_all.deb src/sonic-linux-kernel/linux-image-3.16.0-4->amd64_3.16.7-ckt11-2+acs8u2_amd64.deb

Thanks.

**Comment by qiluo-msft** [comment]
Could you share the debootstrap.log file? I suspect there is un-clean environment, such as already mounted 'proc' in the system. You may reboot and retry to double check.

**Comment by Maikor** [comment]
Reboot/start from scratch doesn't help. 

Mount and log output below. 

root@aed11b3801d6:/sonic-buildimage# **mount**
...ommitted piece...
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/fs type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,mode=755)


root@aed11b3801d6:/sonic-buildimage# cat ./fsroot/debootstrap/**debootstrap.log**
gpgv: Signature made Sat Sep 17 11:40:00 2016 UTC using RSA key ID 46925553
gpgv: Good signature from "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>"
gpgv: Signature made Sat Sep 17 11:40:00 2016 UTC using RSA key ID 2B90D010
gpgv: Good signature from "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>"
gpgv: Signature made Sat Sep 17 11:47:09 2016 UTC using RSA key ID 518E17E1
gpgv: Good signature from "Jessie Stable Release Key <debian-release@lists.debian.org>"
mount: permission denied

**Comment by qiluo-msft** [comment]
We have never seen this problem. However we are using docker with a different version. Would you mind choosing this version and trying again?

    $ docker version
    Client:
     Version:      1.11.1
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   5604cbe
     Built:        Tue Apr 26 23:11:07 2016
     OS/Arch:      linux/amd64

    Server:
     Version:      1.11.1
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   5604cbe
     Built:        Tue Apr 26 23:11:07 2016
     OS/Arch:      linux/amd64

**Comment by Maikor** [comment]
Sorry for delay. 
same problem: 

> I: Extracting liblzma5...
> I: Extracting zlib1g...
> W: Failure trying to run: chroot /sonic-buildimage/fsroot mount -t proc proc /proc
> W: See /sonic-buildimage/fsroot/debootstrap/debootstrap.log for details
> Makefile:152: recipe for target 'target/sonic-generic.bin' failed
> make: *** [target/sonic-generic.bin] Error 1
> rm src/initramfs-tools/initramfs-tools_0.120_all.deb src/sonic-linux-kernel/linux-image-3.16.0-4-amd64_3.16.7-ckt11-2+acs8u2_amd64.deb

root@7c5607f7c9fc:/sonic-buildimage# docker version

> Client:
>  Version:      1.11.2
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   b9f10c9
>  Built:        Wed Jun  1 21:23:39 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.11.1
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   5604cbe
>  Built:        Tue Apr 26 23:43:49 2016
>  OS/Arch:      linux/amd64


root@7c5607f7c9fc:/sonic-buildimage# lsb_release -a

> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.1 LTS
> Release:        16.04
> Codename:       xenial

Whole workflow: 

git clone https://github.com/Azure/sonic-build-tools
cd sonic-build-tools
./build.sh sonic-slave
docker run -v /var/run/docker.sock:/var/run/docker.sock -it local/sonic-slave bash

_Inside container:_
git clone --recursive https://github.com/Azure/sonic-buildimage.git
cd sonic-buildimage
make brcm-all USERNAME="mike" PASSWORD_ENCRYPTED="$(perl -e 'print crypt("mike123", "salt"),"\n"')"

Any other recommendations? thanks.

**Comment by qiluo-msft** [comment]
Thanks for updating! Please wait some time for our experiment.

**Comment by qiluo-msft** [comment]
Hi Maikor,
We found that there is a bug in README. The sonic-slave docker container should be run with  --privileged.

    docker run -v /var/run/docker.sock:/var/run/docker.sock -it --privileged local/sonic-slave bash

Sorry for the inconvenience.

**Comment by Maikor** [comment]
Hello, still facing some issues. Tried on docker 1.11.1 and 1.12 Output was identical:

> 
> Setting up i2c-tools (3.1.1-1) ...
> Processing triggers for libc-bin (2.19-18+deb8u6) ...
> Processing triggers for systemd (215-17+deb8u5) ...
> Processing triggers for ca-certificates (20141019+deb8u1) ...
> Updating certificates in /etc/ssl/certs... 174 added, 0 removed; done.
> Running hooks in /etc/ca-certificates/update.d....done.
> + sudo rm -f ./fsroot/etc/ssh/ssh_host_dsa_key ./fsroot/etc/ssh/ssh_host_dsa_key.pub ./fsroot/etc/ssh/ssh_host_ecdsa_key ./fsroot/etc/ssh/ssh_host_ecdsa_key.pub ./fsroot/etc/ssh/ssh_host_ed25519_key ./fsroot/etc/ssh/ssh_host_ed25519_key.pub ./fsroot/etc/ssh/ssh_host_rsa_key ./fsroot/etc/ssh/ssh_host_rsa_key.pub
> + sudo cp files/sshd/host-ssh-keygen.sh ./fsroot/usr/local/bin/
> + sudo cp -f files/sshd/sshd.service ./fsroot/lib/systemd/system/ssh.service
> + sudo augtool --autosave 'set /files/etc/ssh/sshd_config/UseDNS no' -r ./fsroot
> sudo: augtool: command not found
> + rm -f /tmp/tmp.jjaLo94Fac
> + clean_sys
> + sudo umount ./fsroot/sys/fs/cgroup/blkio ./fsroot/sys/fs/cgroup/cpuset ./fsroot/sys/fs/cgroup/devices ./fsroot/sys/fs/cgroup/freezer ./fsroot/sys/fs/cgroup/hugetlb ./fsroot/sys/fs/cgroup/memory ./fsroot/sys/fs/cgroup/perf_event ./fsroot/sys/fs/cgroup/pids ./fsroot/sys/fs/cgroup ./fsroot/sys
> umount: /sonic-buildimage/fsroot/sys: target is busy
>         (In some cases useful info about processes that
>          use the device is found by lsof(8) or fuser(1).)
> + true
> + sudo umount ./fsroot/proc
> umount: /sonic-buildimage/fsroot/proc: target is busy
>         (In some cases useful info about processes that
>          use the device is found by lsof(8) or fuser(1).)
> + true
> + true
> Makefile:152: recipe for target 'target/sonic-generic.bin' failed
> make: *** [target/sonic-generic.bin] Error 1
> rm src/initramfs-tools/initramfs-tools_0.120_all.deb src/sonic-linux-kernel/linux-image-3.16.0-4-amd64_3.16.7-ckt11-2+acs8u2_amd64.deb

**Comment by qiluo-msft** [comment]
Thanks for finding a new bug. I am fixing it but not merged. Please check:
https://github.com/Azure/sonic-build-tools/pull/17

**Comment by Maikor** [comment]
hm, another issue, but this one went much further:

> 
> make[2]: Entering directory '/sonic-buildimage/src/sonic-swss-common'
> dh binary  --with autotools-dev
>    dh_testroot
>    dh_prep
>    dh_installdirs
>    debian/rules override_dh_auto_install
> make[3]: Entering directory '/sonic-buildimage/src/sonic-swss-common'
> dh_auto_install
> make[4]: Entering directory '/sonic-buildimage/src/sonic-swss-common'
> Making install in common
> make[5]: Entering directory '/sonic-buildimage/src/sonic-swss-common/common'
> make[6]: Entering directory '/sonic-buildimage/src/sonic-swss-common/common'
>  /bin/mkdir -p '/sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu'
>  /bin/bash ../libtool   --mode=install /usr/bin/install -c   libswsscommon.la '/sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu'
> libtool: install: /usr/bin/install -c .libs/libswsscommon.so.0.0.0 /sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu/libswsscommon.so.0.0.0
> libtool: install: (cd /sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu && { ln -s -f libswsscommon.so.0.0.0 libswsscommon.so.0 || { rm -f libswsscommon.so.0 && ln -s libswsscommon.so.0.0.0 libswsscommon.so.0; }; })
> libtool: install: (cd /sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu && { ln -s -f libswsscommon.so.0.0.0 libswsscommon.so || { rm -f libswsscommon.so && ln -s libswsscommon.so.0.0.0 libswsscommon.so; }; })
> libtool: install: /usr/bin/install -c .libs/libswsscommon.lai /sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu/libswsscommon.la
> libtool: install: /usr/bin/install -c .libs/libswsscommon.a /sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu/libswsscommon.a
> libtool: install: chmod 644 /sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu/libswsscommon.a
> libtool: install: ranlib /sonic-buildimage/src/sonic-swss-common/debian/tmp/usr/lib/x86_64-linux-gnu/libswsscommon.a
> libtool: install: warning: remember to run `libtool --finish /usr/lib/x86_64-linux-gnu'
> make[6]: Nothing to be done for 'install-data-am'.
> make[6]: Leaving directory '/sonic-buildimage/src/sonic-swss-common/common'
> make[5]: Leaving directory '/sonic-buildimage/src/sonic-swss-common/common'
> make[5]: Entering directory '/sonic-buildimage/src/sonic-swss-common'
> make[6]: Entering directory '/sonic-buildimage/src/sonic-swss-common'
> make[6]: Nothing to be done for 'install-exec-am'.
> make[6]: Nothing to be done for 'install-data-am'.
> make[6]: Leaving directory '/sonic-buildimage/src/sonic-swss-common'
> make[5]: Leaving directory '/sonic-buildimage/src/sonic-swss-common'
> make[4]: Leaving directory '/sonic-buildimage/src/sonic-swss-common'
> make[3]: Leaving directory '/sonic-buildimage/src/sonic-swss-common'
>    dh_install
>    dh_installdocs
>    dh_installchangelogs
>    dh_perl
>    dh_link
>    dh_compress
>    dh_fixperms
>    dh_strip
>    dh_makeshlibs
>    dh_shlibdeps
> dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libswsscommon/usr/lib/x86_64-linux-gnu/libswsscommon.so.0.0.0 was not linked against libnl-genl-3.so.200 (it uses none of the library's symbols)
>    dh_installdeb
>    dh_gencontrol
> dpkg-gencontrol: warning: package libswsscommon: unused substitution variable ${misc:Pre-Depends}
>    dh_md5sums
>    dh_builddeb
> dpkg-deb: building package `libswsscommon' in `../libswsscommon_1.0.0_amd64.deb'.
> dpkg-deb: building package `libswsscommon-dev' in `../libswsscommon-dev_1.0.0_amd64.deb'.
> make[2]: Leaving directory '/sonic-buildimage/src/sonic-swss-common'
>  dpkg-genchanges -b >../sonic_1.0.0_amd64.changes
> dpkg-genchanges: binary-only upload (no source code included)
>  dpkg-source --after-build sonic-swss-common
> dpkg-buildpackage: binary-only upload (no source included)
> /sonic-buildimage/src
> make[1]: Leaving directory '/sonic-buildimage/src'
> mkdir -p `dirname dockers/docker-syncd/deps/libswsscommon_1.0.0_amd64.deb` && cp src/libswsscommon_1.0.0_amd64.deb dockers/docker-syncd/deps/
> make -C src brcm/libsairedis_1.0.0_amd64.deb
> make[1]: Entering directory '/sonic-buildimage/src'
> make[1]: *** No rule to make target 'brcm-sdk/libopennsl_*_amd64.deb', needed by 'brcm/libsairedis_1.0.0_amd64.deb'.  Stop.
> make[1]: Leaving directory '/sonic-buildimage/src'
> Makefile:31: recipe for target 'src/brcm/libsairedis_1.0.0_amd64.deb' failed
> make: *** [src/brcm/libsairedis_1.0.0_amd64.deb] Error 2
> rm src/libswsscommon_1.0.0_amd64.deb src/initramfs-tools/initramfs-tools_0.120_all.deb src/sonic-linux-kernel/linux-image-3.16.0-4-amd64_3.16.7-ckt11-2+acs8u2_amd64.deb src/libhiredis0.13_0.13.3-2_amd64.deb
> root@eaaa626f98d8:/sonic-buildimage#

**Comment by qiluo-msft** [comment]
This one is expected if you don't have brcm-sdk/libopennsl DEB file. Currently we don't have the permission to distribute it. Please check https://github.com/Azure/sonic-buildimage/blob/master/README.md#3-get-vendor-sai-sdk

The complete sdk file list for brcm: https://github.com/Azure/sonic-buildimage/blob/master/src/brcm-sdk/filelist.txt
