### ISSUE TITLE
[sfputil] Not able to read out  values of voltage/temp/power on some cables 

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-buildimage#2720]
**Description**

**Steps to reproduce the issue:**
read the eeprom dom info with sfputil:

**Describe the results you received:**
with 201807/201811 image, voltage/temp/power not able to be read out for some cable, but with 201803 image is OK.  any one encountered into similiar issue?

### bad output with 201807/201811 image:

~# sudo sfputil show eeprom --dom -p Ethernet0
Ethernet0: SFP EEPROM detected
CalibrationType: Internally Calibrated
Connector: Optical pigtail
EncodingCodes: NRZ
ExtIdentOfTypeOfTransceiver: GBIC/SFP defined by twowire interface ID
LengthCable(UnitsOfm): 3
NominalSignallingRate(UnitsOf100Mbd): 255
RateIdentifier: Unspecified
ReceivedPowerMeasurementType: Avg power
TransceiverCodes:
FibreChannelLinkLength: short distance (S)
SFP+CableTechnology: Active Cable
TypeOfTransceiver: SFP or SFP Plus
VendorDataCode(YYYY-MM-DD Lot): 2017-06-05
VendorName: Hisense
VendorOUI:
VendorPN: LTF8507-PC03-HW1
VendorRev: 1
VendorSN: S50763H002Y
AlarmFlagStatus:
...
**MonitorData:**
**RXPower: -infdBm**
**TXBias: 0.0000mA**
**TXPower: -infdBm**
**Temperature: 0.0000C**
**Vcc: 0.0000Volts**
StatusControl:
...
TempLowWarning: Off
VccHighWarning: Off
VccLowWarning: Off

### good out with 201803

Ethernet0: SFP EEPROM detected
CalibrationType: Internally Calibrated
Connector: Optical pigtail
EncodingCodes: NRZ
ExtIdentOfTypeOfTransceiver: GBIC/SFP defined by twowire interface ID
LengthCable(UnitsOfm): 3
NominalSignallingRate(UnitsOf100Mbd): 255
RateIdentifier: Unspecified
ReceivedPowerMeasurementType: Avg power
TransceiverCodes:
FibreChannelLinkLength: short distance (S)
SFP+CableTechnology: Active Cable
TypeOfTransceiver: SFP or SFP Plus
VendorDataCode(YYYY-MM-DD Lot): 2017-12-12
VendorName: Hisense
VendorOUI: His
VendorPN: LTF8507-PC03-HW1
VendorRev: 1
VendorSN: S507C3H002G
AlarmFlagStatus:
...
**MonitorData:
RXPower: -3.3451dBm
TXBias: 6.2000mA
TXPower: -1.2703dBm
Temperature: 40.5508C
Vcc: 3.2823Volts**
StatusControl:
...

**Comment by xinliu-seattle** [comment]
@keboliu can you dump the eeprom file to a binary file for debugging/attaching to the ticket?
