### ISSUE TITLE
warm reboot flag not cleared result in "config reload -y" to a "warm reload"

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-buildimage#2729]
**Description**
issue "sudo config warm_restart enable" and then "sudo config reload -y".
expecting a cold reload but from the log can see that it performed a "warm" reload. 

**Steps to reproduce the issue:**
1. issue "sudo config warm_restart enable"
2. issue "sudo config reload -y"
3. check the log

**Describe the results you received:**
it performed a warm reload
```
Apr  2 08:09:06.039650 r-boxer-sw01 NOTICE swss#orchagent: :- checkWarmStart: orchagent doing warm start, restore count 3
Apr  2 08:09:06.039650 r-boxer-sw01 NOTICE swss#orchagent: :- main: --- Starting Orchestration Agent ---
Apr  2 08:09:06.041382 r-boxer-sw01 NOTICE swss#orchagent: :- clear_local_state: clearing local state
```

**Describe the results you expected:**

expect a cold reload.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    root@r-boxer-sw01:/var/log# show version
    SONiC Software Version: SONiC.HEAD.39-1b07437
    Distribution: Debian 9.8
    Kernel: 4.9.0-8-amd64
    Build commit: 1b07437
    Build date: Sun Mar 31 08:54:44 UTC 2019
    Built by: johnar@jenkins-worker-4

    Docker images:
    REPOSITORY                 TAG                 IMAGE ID            SIZE
    docker-orchagent-mlnx      HEAD.39-1b07437     c44454c894ac        286MB
    docker-orchagent-mlnx      latest              c44454c894ac        286MB
    docker-syncd-mlnx          HEAD.39-1b07437     bdaed389f75a        331MB
    docker-syncd-mlnx          latest              bdaed389f75a        331MB
    docker-lldp-sv2            HEAD.39-1b07437     32e72c71a5b0        274MB
    docker-lldp-sv2            latest              32e72c71a5b0        274MB
    docker-dhcp-relay          HEAD.39-1b07437     18fb44318946        256MB
    docker-dhcp-relay          latest              18fb44318946        256MB
    docker-database            HEAD.39-1b07437     ed6c4e488674        255MB
    docker-database            latest              ed6c4e488674        255MB
    docker-snmp-sv2            HEAD.39-1b07437     a8743b91a47e        294MB
    docker-snmp-sv2            latest              a8743b91a47e        294MB
    docker-teamd               HEAD.39-1b07437     9cf398c3ee7d        274MB
    docker-teamd               latest              9cf398c3ee7d        274MB
    docker-router-advertiser   HEAD.39-1b07437     6e2bfd4c867c        254MB
    docker-router-advertiser   latest              6e2bfd4c867c        254MB
    docker-platform-monitor    HEAD.39-1b07437     bdd1f019a2bb        286MB
    docker-platform-monitor    latest              bdd1f019a2bb        286MB
    docker-fpm-quagga          HEAD.39-1b07437     836cbc5f663b        281MB
    docker-fpm-quagga          latest              836cbc5f663b        281MB
    ```

    **Attach debug file `sudo generate_dump`:**
[syslog.zip](https://github.com/Azure/sonic-buildimage/files/3033038/syslog.zip)

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@keboliu The scenario you reported is a true behavior.

But I am not sure if we would encounter this scenario in production since we introduced warmboot finalizer service. Before the service, after a warm reboot, the flag would be persisted until admin explicitly disables it. That leaves a pretty big window for it to happen. With the service, we will disable warmreboot ~2 minutes after warm booting up.

However, if use indeed enabled warm reboot then tries to reload config. We currently don't have a good way of preventing it.

Do you feel warmboot finalizer service is a good mitigation for the issue?

**Comment by keboliu** [comment]
@yxieca warm-reboot finalizer service can address the first case as you mentioned.  
For the second case, can we have "config reload" to clear the "warm reboot" flag before doing any service restart?  I am not sure whether this will violate the design purpose of "config reload"?

**Comment by yxieca** [comment]
@keboliu do you think we can close this issue now?
