### ISSUE TITLE
Could I compile an  ONIE installer just for as5712-54x？

### ISSUE THREAD

**Issue by CnaZhao** [Azure/sonic-buildimage#2877]
I want to compile an ONIE installer just for as5712-54x,not for all of broadcom ASIC.
If can ,how?
Thanks!

**Comment by jleveque** [comment]
Currently, our installer images are built on a per-ASIC manufacturer basis and contain support for all platforms with ASICs from that manufacturer. We do not currently offer a way to build an image which supports a single platform.

**Comment by yxieca** [comment]
Question answered by Joe. Please feel free to enter new questions.
