### ISSUE TITLE
Crash on changing of IP address on a network interface with an active neighbor

### ISSUE THREAD

**Issue by garyachy** [Azure/sonic-buildimage#289]
**Topology**
TG-DUT-DUT-TG

**Steps**
1. Boot two switches with SONIC (OCP branch) and minigraph
2. sudo ifconfig Ethernet0 2.2.2.1 netmask 255.255.255.0 on any switch

**Observed results**
Feb 10 14:23:23 OCPSCH0104001MS NOTICE orchagent: :- removeSubnetRoute: Remove subnet route to 10.10.1.2/30 from Ethernet0
Feb 10 14:23:23 OCPSCH0104001MS NOTICE orchagent: :- removeIp2MeRoute: Remove packet action trap route ip:10.10.1.2
Feb 10 14:23:23 OCPSCH0104001MS NOTICE orchagent: :- removeRouterIntfs: Remove router interface for port Ethernet0
Feb 10 14:23:23 OCPSCH0104001MS ERR orchagent: :- meta_sai_validate_oid: oid is set to null object id
Feb 10 14:23:23 OCPSCH0104001MS ERR orchagent: :- removeRouterIntfs: Failed to remove router interface for port Ethernet0, rv:-5
Feb 10 14:23:23 OCPSCH0104001MS ERR orchagent: :- main: Failed due to exception: Failed to remove router interface.
Feb 10 14:23:23 OCPSCH0104001MS INFO docker[1068]: terminate called without an active exception
Feb 10 14:23:23 OCPSCH0104001MS INFO kernel: [ 1264.781525] Core dump to |/usr/bin/coredump-compress orchagent 91 pipe failed

**Comment by stcheng** [comment]
deprecated. this issue shall go to github.com/Azure/SONiC.
