### ISSUE TITLE
FLEX_COUNTER_TABLE in two DBs ?

### ISSUE THREAD

**Issue by dzhangalibaba** [Azure/sonic-buildimage#2904]
**Description**

why some FLEX_COUNTER_TABLE are using CONFIG_DB, e.g. dockers/docker-orchagent/enable_counters.py

others using FLEX_COUNTER_DB,  e.g.  in orchagent

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wendani** [comment]
The path through CONFIG_DB is handled by FlexCounterOrch, which will set to FLEX_COUNTER_DB. So both ways are essentially the same under the hood.
