### ISSUE TITLE
Typo error STRTCH_DEBS_PATH

### ISSUE THREAD

**Issue by antony-rheneus** [Azure/sonic-buildimage#2970]
https://github.com/Azure/sonic-buildimage/blob/6dbae0e3cd5c7b749fd41f99fe7a57ac1b5a2d37/slave.mk#L599

@@ -596,7 +610,7 @@ $(addprefix $(TARGET_PATH)/, $(SONIC_INSTALLERS)) : $(TARGET_PATH)/% : \
        export files_path="$(FILES_PATH)"
        export python_debs_path="$(PYTHON_DEBS_PATH)"
        export initramfs_tools="$(STRETCH_DEBS_PATH)/$(INITRAMFS_TOOLS)"
-       export linux_kernel="$(STRTCH_DEBS_PATH)/$(LINUX_KERNEL)"
+       export linux_kernel="$(STRETCH_DEBS_PATH)/$(LINUX_KERNEL)"

**Comment by jleveque** [comment]
Thanks for reporting this! Fix is open here: https://github.com/Azure/sonic-buildimage/pull/2971
