### ISSUE TITLE
shutdown interface，arp entry not delete

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#3024]
**Description**
TC(vlan100 100.0.0.1)--(Ethernet2)SONiC(Ethernet3)-TC（vlan100 100.0.0.2），The TC in different network，sonic have two interface in vlan100，and config vlanif（100.0.0.3） 
![图片](https://user-images.githubusercontent.com/51427706/59660942-5b2cb500-91dc-11e9-8758-73327ec8dc9c.png)
![图片](https://user-images.githubusercontent.com/51427706/59660945-5e27a580-91dc-11e9-9663-04175fdaef9d.png)

**Steps to reproduce the issue:**
1. config vlan and vlan interface
2. shutdown interface
3. ARP table entries still exist

**Describe the results you received:**
shotdown interface ARP table entries still exist

**Describe the results you expected:**
ARP table entries not exist

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
        SONiC Software Version: SONiC.201803_rj.0-bbb2a14-20181204.172418
    Distribution: Debian 8.11
    Kernel: 3.16.0-5-amd64
    Build commit: bbb2a14
    Build date: Tue Dec 4 17:28:36 UTC 2018
    Built by: ngcf@ubuntu01
    
    Docker images:
    REPOSITORY TAG IMAGE ID SIZE
    docker-orchagent-brcm latest 4f1f9fc1806a 364.7 MB
    docker-fpm-frr 201803_rj.0-bbb2a14-20181204.172418 6223f4da8ad0 360.9 MB
    docker-fpm-frr latest 6223f4da8ad0 360.9 MB
    docker-teamd 201803_rj.0-bbb2a14-20181204.172418 2a37c8f85d79 356 MB
    docker-teamd latest 2a37c8f85d79 356 MB
    docker-syncd-brcm 201803_rj.0-bbb2a14-20181204.172418 aa8f396c7848 986.1 MB
    docker-syncd-brcm latest aa8f396c7848 986.1 MB
    docker-lldp-sv2 201803_rj.0-bbb2a14-20181204.172418 b9867fa47443 365.3 MB
    docker-lldp-sv2 latest b9867fa47443 365.3 MB
    docker-snmp-sv2 201803_rj.0-bbb2a14-20181204.172418 b5d14f4a8073 387.9 MB
    docker-snmp-sv2 latest b5d14f4a8073 387.9 MB
    docker-dhcp-relay 201803_rj.0-bbb2a14-20181204.172418 87515dbf4f57 350.1 MB
    docker-dhcp-relay latest 87515dbf4f57 350.1 MB
    docker-database 201803_rj.0-bbb2a14-20181204.172418 cde99a623e5b 350.6 MB
    docker-database latest cde99a623e5b 350.6 MB
    docker-platform-monitor 201803_rj.0-bbb2a14-20181204.172418 8f80109ffd86 367.2 MB
    docker-platform-monitor latest 8f80109ffd86 367.2 MB
    docker-router-advertiser 201803_rj.0-bbb2a14-20181204.172418 fee1c0c6d598 348.3 MB
    docker-router-advertiser latest fee1c0c6d598 348.3 MB 
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by prsunny** [comment]
This is a kernel behavior. ARP is bind to the Router Interface (Vlan in this example) and not to member ports. So if you shutdown the member ports, ARP will not be deleted as the Vlan interface is still `admin up`. Kindly check the same by `ifconfig Vlan100 down` and verify the behavior. Please re-open if you have further questions.
