### ISSUE TITLE
How to generate syncd-rpc container for Ansible COPP Test

### ISSUE THREAD

**Issue by brianlin-ec** [Azure/sonic-buildimage#3081]
Description
    We want to build docker-syncd with rpc packages , to replace the regular syncd container with   syncd-rpc container  for Ansible COPP testing purposes.    

 (refer to https://github.com/Azure/sonic-mgmt/issues/401)

    While running "docker-syncd with rpc" from cold /warm start, synd crash is seen in Broadcom  platforms.
  
  
Steps to reproduce the issue:

    . Checkout Sonic source files from branch(2019/04)
    . In the file "sonic-buildimage/ rules / config" , uncomment to enable: ENABLE_SYNCD_RPC = y     
    . Build SONiC image & load image into switch 
    . Check for syncd crash
    
Please let me know is any information about it, thanks!

Regrads,
Brian Lin

**Comment by wendani** [comment]
your command to build rpc looks good.
