### ISSUE TITLE
minigraph.py crashed when no png is in the minigraph

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-buildimage#309]
When there's no png info, minigraph.py will crash, because console_dev and mgmt_dev variables are missing. Better to have some basic checks here.

Besides, if the role tag is missing, the bgpd.conf.j2 will fail to be deployed.

**Comment by stcheng** [comment]
@taoyl-ms

**Comment by taoyl-ms** [comment]
Yes, I met those issues before. I can add a check there to simply not set png data fields when png is missing, and let the failure to be put off to when consumer try to read that data, like the "role" example in bgpd.conf.j2, as you mentioned.

One general question is, how should we handle the case when a template is asking for a certain variable, but that variable is not available in the input data? Writing error into syslog?

**Comment by stcheng** [comment]
writing errors into syslog I think is the base line. otherwise it could be hard to figure out where the issue is. it is better not to crash on any point. because some of the minigraphs are not automatically generated, checking the data integrity could be mandatory. btw, I find that editing the minigraph is not easy. we might later could figure out something like minigraph_editor or so. :)

**Comment by taoyl-ms** [comment]
This detail issue is resolved by PR #335. Let me close this issue and open a new issue about config engine should give more detail error message / some type of minigraph debugging tool.
