### ISSUE TITLE
configurations are re-generated across reboots

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-buildimage#315]
@taoyl-ms Sometimes people would like to update some configurations on the device by themselves. but rebooting will trigger the files inside the dockers to be re-generated again via the minigraph.xml. Is it by design or shall we able to leave the configurations there before manually regenerating this configurations?

**Comment by taoyl-ms** [comment]
It is by design. If want to update configure manually user should modify the template instead of directly edit the auto-generated configuration file.

**Comment by stcheng** [comment]
If there are some configurations made temporarily due to some specific circumstances, or if some configurations are not supported by converting the minigraph.xml, then it might cause some issues I think.

e.g. if we want to shutdown one BGP interface on purpose without modifying the minigraph, then after reboots the BGP session will be up again.

**Comment by stcheng** [comment]
this has been supported by config save -y
