### ISSUE TITLE
PortChannel ip address is missing after do "systemctl restart teamd". 

### ISSUE THREAD

**Issue by habeebmohammed** [Azure/sonic-buildimage#3150]
**Description**
PortChannel ip address is missing after do "systemctl restart teamd". 

**Steps to reproduce the issue:**
root@sonic:/home/admin# show ip interfaces
Interface     IPv4 address/mask    Admin/Oper
------------  -------------------  ------------
Ethernet49    11.11.11.1/24        up/up
Ethernet50    12.12.12.1/24        up/down
PortChannel1  34.34.34.1/24        up/up          <<== Correct
PortChannel2  56.56.56.1/24        up/up          <<== Correct
docker0       240.127.1.1/24       up/down
eth0          10.6.48.133/24       up/up
lo            127.0.0.1/8          up/up
              10.1.0.1/32

root@sonic:/home/admin# systemctl restart teamd <<= Do "systemctl restart teamd"

root@sonic:/home/admin# show ip interfaces
Interface    IPv4 address/mask    Admin/Oper
-----------  -------------------  ------------
Ethernet49   11.11.11.1/24        up/up
Ethernet50   12.12.12.1/24        up/down
                          <<=== Issue : PortChannel 1-2 ip address is missing.
docker0      240.127.1.1/24       up/down
eth0         10.6.48.133/24       up/up
lo           127.0.0.1/8          up/up
             10.1.0.1/32

**Describe the results you received:**

**Describe the results you expected:**
Ip address should be retained after teamd restart. reboot can get the ip addresses back to portchannels

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stepanblyschak** [comment]
Duplicate https://github.com/Azure/sonic-buildimage/issues/3043

**Comment by habeebmohammed** [comment]
@stepanblyschak , I tried changing the swss.sh per #3114 still IP address is lost with "systemctl restart teamd".

**Comment by stepanblyschak** [comment]
@habeebmohammed #3114 appeared to be not enough to fix the issue. There is another fix https://github.com/Azure/sonic-utilities/pull/582

**Comment by habeebmohammed** [comment]
@stepanblyschak , I picked #582 changes as well, still no change in the result.

**Comment by jleveque** [comment]
@habeebmohammed: Azure/sonic-utilities#582 fixes a similar issue when calling `config reload` or `config load_minigraph` -- it would restart teamd twice. That PR prevents this behavior. It sounds like you are manually reproducing this behavior. I believe that currently SONiC does not support restarting teamd without also restarting SwSS first.

@stcheng: Please confirm.

**Comment by yxieca** [comment]
Fixed in master and 201811 branch.
