### ISSUE TITLE
radvd out of range MTU error

### ISSUE THREAD

**Issue by rajendra-dendukuri** [Azure/sonic-buildimage#3161]
**Description**

radvd out of range MTU error

As part of "PR#2795 Build radvd from source; Patch so as not to treat out-of-range MTU as an error", the error message was reduced to warning
and failure was bypassed. 

This issue is created to track a final fix. Following fixes have been commited to 4.18 kernel to support setting of bridge MTU to a value > 9100. When SONiC kernrel is upgraded to a kernel > 4.18, the patch done in radvd needs to be removed and Bridge MTU needs to be set to 9100.

https://github.com/torvalds/linux/commit/3341d9170228d521fb38afae14b449308f3e4018#diff-221ed728b95e6fa6475069eed594287c
https://github.com/torvalds/linux/commit/804b854d374e39f5f8bff9638fd274b9a9ca7d33#diff-221ed728b95e6fa6475069eed594287c
https://github.com/torvalds/linux/commit/f40aa23339e2d06b1a8daaece5a511bb1c4f704c#diff-221ed728b95e6fa6475069eed594287c
https://github.com/torvalds/linux/commit/419d14af9e07fb5ca32b1b1614793c6b1e242152#diff-221ed728b95e6fa6475069eed594287c

**Steps to reproduce the issue:**
1. Make sure that DEVICE_METADATA|localhost|type="ToRRouter"

2. Create a VLAN and add an active link to it
config vlan add 100
config vlan member add 100 Ethernet0
   
3. Assing IPv6 address to the Vlan interface
config interface ip add Vlan100 2002::1/64

4. Restart radv container
systemctl restart radv

5. Check syslog

**Describe the results you received:**

Following error message is seen
Jul 16 00:41:19.823049 sonic WARNING radv#radvd[60]: AdvLinkMTU for Vlan1 (9100) must be zero or between 1280 and 1500

**Describe the results you expected:**
No error/warnings need to be observed

**Comment by jleveque** [comment]
Thanks for creating this issue to track this.

**Comment by jleveque** [comment]
Master branch is now running 4.19 kernel, so the patches in the description should be present.

@prsunny: Do you know if there is a plan to set the bridge MTU to 9100?

**Comment by tahmed-dev** [comment]
@jleveque: @prsunny and I verified that we can set the bridge MTU to 9100. [PR:1393](https://github.com/Azure/sonic-swss/pull/1393) should close this issue.

**Comment by jleveque** [comment]
@tahmed-dev: Thanks for the info! We should then also remove the patch from radvd before closing this issue.
