### ISSUE TITLE
everflow session status showing error

### ISSUE THREAD

**Issue by mfriyas** [Azure/sonic-buildimage#3188]
While executing everflow_testbed.yml, seeing some failures and in sonic device it showing as everflow session status as error. 

Script configures the mirror session with the follwoing parameters and mirror session staus showing error.

root@sonic-z9264f-03:/home/admin# show mirror_session
Name            Status    SRC IP     DST IP    GRE     DSCP    TTL    Queue
--------------  --------  ---------  --------  ------  ------  -----  -------
test_session_1  error     1.1.1.1    2.2.2.2   0x6558  8       1      0

ask path: /var/johnar/sonic-mgmt/ansible/roles/test/tasks/everflow_testbed/run_test.yml:85
Thursday 18 July 2019  11:30:26 +0000 (0:00:00.227)       0:03:52.559 *********
ok: [sonic-z9264f-03] => {
    "out.stdout_lines": [
        "",
        "-----------Matches found in file:'/tmp/syslog'-----------",
        "",
        "Matches:0",
        "",
        "-------------------------------------------------",
        "",
        "",
        "Expected and found matches:0",
        "",
        "-------------------------------------------------",
        "",
        "Total matches:0",
        "Total expected and found matches:0",
        "Total expected but not found matches: 0",
        "",
        "",
        "-------------------------------------------------",
        "",
        "",
        "LOG ANALYSIS SUMMARY",
        "FILE:    /tmp/syslog    MATCHES    0",
        "FILE:    /tmp/syslog    EXPECTED MATCHES    0",
        "-----------------------------------",
        "TOTAL MATCHES:                  0",
        "TOTAL EXPECTED MATCHES:         0",
        "TOTAL EXPECTED MISSING MATCHES: 0",

**Comment by stcheng** [comment]
shall be fixed: https://github.com/Azure/sonic-utilities/pull/580
