### ISSUE TITLE
vnet_vxlan] syncd & swss crash while exec docker exec swss sh -c "swssconfig /vnet.switch.json

### ISSUE THREAD

**Issue by shaukathsathar** [Azure/sonic-buildimage#3214]
While running the testcase vnet_vxlan.yml , the synd & swss crashes and does not come up.
During manual repro , observed that the crash haoppens while perfroming the step 👍

docker exec swss sh -c "swssconfig /vnet.switch.json"

root@sonic-s5232-64:# docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
a329c41aab12 docker-sonic-telemetry:latest "/usr/bin/supervisord" 7 days ago Up 7 hours telemetry
3fef93bb39fe docker-syncd-brcm:latest "/usr/bin/supervisord" 7 days ago Up 7 hours syncd
9db92c2748db docker-dhcp-relay:latest "/usr/bin/docker_ini\u2026" 7 days ago Up 7 hours dhcp_relay
ee25f305bb69 docker-snmp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 7 hours snmp
d2f8e1985ef3 docker-router-advertiser:latest "/usr/bin/supervisord" 7 days ago Up 7 hours radv
923586610d29 docker-teamd:latest "/usr/bin/supervisord" 7 days ago Up 7 hours teamd
e0b03dda5474 docker-orchagent:latest "/usr/bin/supervisord" 7 days ago Up 7 hours swss
2a88bcb95135 docker-fpm-frr:latest "/usr/bin/supervisord" 7 days ago Up 7 hours bgp
ffbaec684e17 docker-platform-monitor:latest "/usr/bin/docker_ini\u2026" 7 days ago Up 7 hours pmon
c0fde4e0c38e docker-lldp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 7 hours lldp
167d3b41ad18 docker-database:latest "/usr/bin/supervisord" 7 days ago Up 7 hours database
root@sonic-s5232-64:#

root@sonic-s5232-64:#
root@sonic-s5232-64:# docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
a329c41aab12 docker-sonic-telemetry:latest "/usr/bin/supervisord" 7 days ago Up 7 hours telemetry
3fef93bb39fe docker-syncd-brcm:latest "/usr/bin/supervisord" 7 days ago Exited (0) 17 seconds ago syncd
9db92c2748db docker-dhcp-relay:latest "/usr/bin/docker_ini\u2026" 7 days ago Up 7 hours dhcp_relay
ee25f305bb69 docker-snmp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 7 hours snmp
d2f8e1985ef3 docker-router-advertiser:latest "/usr/bin/supervisord" 7 days ago Up 7 hours radv
923586610d29 docker-teamd:latest "/usr/bin/supervisord" 7 days ago Up 7 hours teamd
e0b03dda5474 docker-orchagent:latest "/usr/bin/supervisord" 7 days ago Exited (0) 26 seconds ago swss
2a88bcb95135 docker-fpm-frr:latest "/usr/bin/supervisord" 7 days ago Up 7 hours bgp
ffbaec684e17 docker-platform-monitor:latest "/usr/bin/docker_ini\u2026" 7 days ago Up 7 hours pmon
c0fde4e0c38e docker-lldp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 7 hours lldp
167d3b41ad18 docker-database:latest "/usr/bin/supervisord" 7 days ago Up 7 hours database
root@sonic-s5232-64:#
root@sonic-s5232-64:#
root@sonic-s5232-64:# docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
a329c41aab12 docker-sonic-telemetry:latest "/usr/bin/supervisord" 7 days ago Up 7 hours telemetry
3fef93bb39fe docker-syncd-brcm:latest "/usr/bin/supervisord" 7 days ago Up 5 seconds syncd
9db92c2748db docker-dhcp-relay:latest "/usr/bin/docker_ini\u2026" 7 days ago Up Less than a second dhcp_relay
ee25f305bb69 docker-snmp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 11 seconds snmp
d2f8e1985ef3 docker-router-advertiser:latest "/usr/bin/supervisord" 7 days ago Up 11 seconds radv
923586610d29 docker-teamd:latest "/usr/bin/supervisord" 7 days ago Up 11 seconds teamd
e0b03dda5474 docker-orchagent:latest "/usr/bin/supervisord" 7 days ago Up 17 seconds swss
2a88bcb95135 docker-fpm-frr:latest "/usr/bin/supervisord" 7 days ago Up 7 hours bgp
ffbaec684e17 docker-platform-monitor:latest "/usr/bin/docker_ini\u2026" 7 days ago Up 7 hours pmon
c0fde4e0c38e docker-lldp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 7 hours lldp
167d3b41ad18 docker-database:latest "/usr/bin/supervisord" 7 days ago Up 7 hours database
root@sonic-s5232-64:# ls -lrt /var/core/
total 15912
-rw-rw-rw- 1 root root 3296956 Jul 23 21:08 orchagent.1563916101.77.core.gz
-rw-rw-rw- 1 root root 539564 Jul 23 21:09 orchagent.1563916195.79.core.gz
-rw-rw-rw- 1 root root 453957 Jul 23 21:11 orchagent.1563916278.76.core.gz
-rw-rw-rw- 1 root root 3268090 Jul 24 09:25 orchagent.1563960343.76.core.gz
-rw-rw-rw- 1 root root 537646 Jul 24 09:27 orchagent.1563960433.78.core.gz
-rw-rw-rw- 1 root root 455846 Jul 24 09:28 orchagent.1563960525.77.core.gz
-rw-rw-rw- 1 root root 443581 Jul 24 09:30 orchagent.1563960606.78.core.gz
-rw-rw-rw- 1 root root 3288609 Jul 24 09:42 orchagent.1563961374.76.core.gz
-rw-rw-rw- 1 root root 545909 Jul 24 09:44 orchagent.1563961461.78.core.gz
-rw-rw-rw- 1 root root 3446580 Jul 24 17:17 orchagent.1563988665.77.core.gz
root@sonic-s5232-64:# date
Wed Jul 24 17:19:36 UTC 2019
root@sonic-s5232-64:#
root@sonic-s5232-64:#
root@sonic-s5232-64:#
root@sonic-s5232-64:# docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
a329c41aab12 docker-sonic-telemetry:latest "/usr/bin/supervisord" 7 days ago Up 7 hours telemetry
3fef93bb39fe docker-syncd-brcm:latest "/usr/bin/supervisord" 7 days ago Up 47 seconds syncd
9db92c2748db docker-dhcp-relay:latest "/usr/bin/docker_ini\u2026" 7 days ago Up 43 seconds dhcp_relay
ee25f305bb69 docker-snmp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 53 seconds snmp
d2f8e1985ef3 docker-router-advertiser:latest "/usr/bin/supervisord" 7 days ago Up 53 seconds radv
923586610d29 docker-teamd:latest "/usr/bin/supervisord" 7 days ago Up 53 seconds teamd
e0b03dda5474 docker-orchagent:latest "/usr/bin/supervisord" 7 days ago Up 59 seconds swss
2a88bcb95135 docker-fpm-frr:latest "/usr/bin/supervisord" 7 days ago Up 7 hours bgp
ffbaec684e17 docker-platform-monitor:latest "/usr/bin/docker_ini\u2026" 7 days ago Up 7 hours pmon
c0fde4e0c38e docker-lldp-sv2:latest "/usr/bin/supervisord" 7 days ago Up 7 hours lldp
167d3b41ad18 docker-database:latest "/usr/bin/supervisord" 7 days ago Up 7 hours database
root@sonic-s5232-64:#
root@sonic-s5232-64:#
root@sonic-s5232-64:# show ver

SONiC Software Version: SONiC.HEAD.34-33a1b26a
Distribution: Debian 9.9
Kernel: 4.9.0-9-2-amd64
Build commit: 33a1b26a
Build date: Tue Jul 16 07:32:23 UTC 2019
Built by: johnar@jenkins-worker-4

Platform: x86_64-dellemc_s5232f_c3538-r0
HwSKU: DellEMC-S5232f-C32
ASIC: broadcom
Serial Number: CN01WJVTCES0094Q0020
Uptime: 17:19:58 up 6:54, 2 users, load average: 2.22, 1.13, 0.61

Docker images:
REPOSITORY TAG IMAGE ID SIZE
docker-syncd-brcm HEAD.34-33a1b26a d37d30c5cbfa 391MB
docker-syncd-brcm latest d37d30c5cbfa 391MB
docker-lldp-sv2 HEAD.34-33a1b26a f9cec3c0d72f 298MB
docker-lldp-sv2 latest f9cec3c0d72f 298MB
docker-dhcp-relay HEAD.34-33a1b26a 345df033b084 288MB
docker-dhcp-relay latest 345df033b084 288MB
docker-database HEAD.34-33a1b26a 900699b02b38 280MB
docker-database latest 900699b02b38 280MB
docker-snmp-sv2 HEAD.34-33a1b26a 743e5f69a916 312MB
docker-snmp-sv2 latest 743e5f69a916 312MB
docker-orchagent HEAD.34-33a1b26a 0d0b452ea83d 320MB
docker-orchagent latest 0d0b452ea83d 320MB
docker-teamd HEAD.34-33a1b26a ded1fac7f102 302MB
docker-teamd latest ded1fac7f102 302MB
docker-sonic-telemetry HEAD.34-33a1b26a 418627128450 303MB
docker-sonic-telemetry latest 418627128450 303MB
docker-router-advertiser HEAD.34-33a1b26a 37cc2c3acb9e 280MB
docker-router-advertiser latest 37cc2c3acb9e 280MB
docker-platform-monitor HEAD.34-33a1b26a 0c0701fb3d03 325MB
docker-platform-monitor latest 0c0701fb3d03 325MB
docker-fpm-frr HEAD.34-33a1b26a 1059a8733bbe 318MB
docker-fpm-frr latest 1059a8733bbe 318MB
[orchagent.1563914447.76.core.gz](https://github.com/Azure/sonic-buildimage/files/3426111/orchagent.1563914447.76.core.gz)
[orchagent.1563914533.76.core.gz](https://github.com/Azure/sonic-buildimage/files/3426112/orchagent.1563914533.76.core.gz)
[orchagent.1563914619.77.core.gz](https://github.com/Azure/sonic-buildimage/files/3426113/orchagent.1563914619.77.core.gz)
[orchagent.1563914700.77.core.gz](https://github.com/Azure/sonic-buildimage/files/3426114/orchagent.1563914700.77.core.gz)
[orchagent.1563915248.77.core.gz](https://github.com/Azure/sonic-buildimage/files/3426115/orchagent.1563915248.77.core.gz)
[orchagent.1563915336.77.core.gz](https://github.com/Azure/sonic-buildimage/files/3426116/orchagent.1563915336.77.core.gz)
[orchagent.1563915419.77.core.gz](https://github.com/Azure/sonic-buildimage/files/3426117/orchagent.1563915419.77.core.gz)
[repro_steps_log.txt](https://github.com/Azure/sonic-buildimage/files/3426119/repro_steps_log.txt)
[syncd.1563914453.56.core.gz](https://github.com/Azure/sonic-buildimage/files/3426120/syncd.1563914453.56.core.gz)

**Comment by prsunny** [comment]
Please ensure the platform (SAI) has Vxlan support. Looks like you are running on Broadcom which does not have the L3 Vxlan support yet

**Comment by prsunny** [comment]
Closing this issue. Please re-open if you confirm the platform supports Vxlan. Provide the SAI/ASIC details
