### ISSUE TITLE
Multiple restart of swss fails during config load command

### ISSUE THREAD

**Issue by antony-rheneus** [Azure/sonic-buildimage#3230]
https://github.com/Azure/sonic-buildimage/blob/a5de31bf4388bcd8f6bb71334c9da238b0741261/files/build_templates/swss.service.j2#L13

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/sonicproject/xBMbljGPPYc

Need to adjust the burst value according to interval, it has been decreased

**Comment by jleveque** [comment]
@antony-rheneus: Is this issue still valid? If so, can you please add more details to the description?

I don't understand why swss would restart multiple times during config load.

**Comment by antony-rheneus** [comment]
Looks duplicate of https://github.com/Azure/sonic-buildimage/issues/3244
Fix and Issue are discussed in #3244
