### ISSUE TITLE
Multiple restart of swss during config load fails to start swss

### ISSUE THREAD

**Issue by antony-rheneus** [Azure/sonic-buildimage#3244]
https://github.com/Azure/sonic-buildimage/blob/67463f18b2ea396c1b3bab87575f803376a8046e/files/build_templates/swss.service.j2#L13

@jleveque, Interval has been increased to from default 10sec to 1200sec, but burst has been decreased from default 5 to 3.
Since burst is too  low in longer interval timespan, swss was not started by systemd.
Can we revert the burst/increase it?

**Comment by jleveque** [comment]
@antony-rheneus: Could you please explain your issue more? The new settings (StartLimitInterval = 1200sec, StartLimitBurst = 3) now mean that if systemd has already restarted swss 3 times in the past 20 minutes, it should stop trying to restart the service and mark it as failed.

**Comment by nikos-github** [comment]
@jleveque We are having the same issue. Configuration that isn't incremental yet can't be pushed within the specified limit, is causing swss to not start again.

**Comment by jleveque** [comment]
@nikos-github: To clarify, you have a need to perform > 3 configuration pushes (and thus >3 SwSS restarts, due to lack of incremental config) within 20 minutes? Is this correct?

**Comment by antony-rheneus** [comment]
@jleveque , If you run test suite, this fails as test suite does change configs multiple times and test 1by1.
Excerpt " __if systemd has already restarted swss 3 times in the past 20 minutes, it should stop trying to restart the service and mark it as failed."__
How can you be sure swss restart more than thrice is not vaild scenario, I personally feel this is a valid scenario?

Continuous restart is InValid Only if there is issue in application which exited or core dumped, and then endless loop in the same state has to be avoided. For this we cannot add a prevention in generic infra which affects intentional restarts.

**Comment by antony-rheneus** [comment]
@jleveque Would you give some pointers why this was changed from default system service values? If you provide me some insights it would be helpful for me to understand the reason for the change, as you would have analysed to come up with these new values

**Comment by nikos-github** [comment]
> @nikos-github: To clarify, you have a need to perform > 3 configuration pushes (and thus >3 SwSS restarts, due to lack of incremental config) within 20 minutes? Is this correct?

That is correct.

**Comment by jleveque** [comment]
@antony-rheneus: This was changed from the default values once we added the 'auto-restart-upon-critical-process-crash' feature (https://github.com/Azure/sonic-buildimage/pull/2845). This is to prevent SONiC from indefinitely restarting the service there is something causing one of the critical processes to crash consistently.

**Comment by antony-rheneus** [comment]
can we add "systemctl reset-failed swss" to reset the restart counter in the sonic-utilities/ where config load/load_minigraph is being called?
This is to ensure the test suite doesn't report failure for valid multiple restarts

**Comment by avi-milner** [comment]
> can we add "systemctl reset-failed swss" to reset the restart counter in the sonic-utilities/ where config load/load_minigraph is being called?
> This is to ensure the test suite doesn't report failure for valid multiple restarts

also for config reload operation will need to clear counter , this is not only for tests suites, but also for allowing pusing/changing  new configurations as much as desired without restrictions to it

**Comment by jleveque** [comment]
>can we add "systemctl reset-failed swss" to reset the restart counter in the sonic-utilities/ where config load/load_minigraph is being called?
This is to ensure the test suite doesn't report failure for valid multiple restarts

We can. This is something I was already considering adding. I'll look into creating a PR.

**Comment by jleveque** [comment]
@antony-rheneus, @avi-milner: PR here: https://github.com/Azure/sonic-utilities/pull/607. Please review.

**Comment by jleveque** [comment]
Should be addressed by https://github.com/Azure/sonic-utilities/pull/607

**Comment by avi-milner** [comment]
hi @jleveque ,
it seems that the fix is not working as we expected,
when we call to config_reload / config_load/ config_load_minigraph 
from this code you only reset failed counter for services that are already in failed state, this still causes  the config load scenarios to fail after running them within the time window of 20 minutes, 3 times 

can you please fix to always reset failed counter for config load commands ?
