### ISSUE TITLE
Make all failed in branch 201811.

### ISSUE THREAD

**Issue by ajuse** [Azure/sonic-buildimage#3255]
**Description**

**Steps to reproduce the issue:**
1.update latest code from github in branch 201811 at 2019.07.31.
2.make configure PLATFORM=barefoot and BLDENV=stretch make stretch.
3.make all

**Describe the results you received:**
g++ -DHAVE_CONFIG_H -I. -I.. -I .. -I ../warmrestart -g -DNDEBUG  -std=c++11 -Wall -fPIC -Wno-write-strings -I/usr/include/libnl3 -I/usr/include/swss -I/opt/bfn/install/include/switchsai -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros -Wno-switch-default -Wno-long-long -Wno-redundant-decls -I /usr/include/sai -D_FORTIFY_SOURCE=2  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c -o orchagent-portsorch.o `test -f 'portsorch.cpp' || echo './'`portsorch.cpp
In file included from /usr/include/sai/sai_meta.h:6:0,
                 from /usr/include/sai/sai_serialize.h:18,
                 from portsorch.cpp:21:
/usr/include/sai/saimetadata.h:7:27: fatal error: saiextensions.h: No such file or directory
 #include <saiextensions.h>
                           ^
compilation terminated.
Makefile:654: recipe for target 'orchagent-portsorch.o' failed

**Describe the results you expected:**
I find the saiextensions.h file in libsaivs-deb_1.0.0_amd64.deb, but this package was not installed.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
please update the submodules

**Comment by ajuse** [comment]
@lguohan I typed "make init" to update all submodules, but the prolem still here. btw, here is output of  "make init":
sonic@ubuntu:~/software/sonic-buildimage$ make init
+++ Making init +++
make -f Makefile.work init
make[1]: Entering directory '/home/sonic/software/sonic-buildimage'
Entering 'platform/barefoot/sonic-platform-modules-arista'
Entering 'platform/broadcom/sonic-platform-modules-arista'
Entering 'platform/mellanox/hw-management/hw-mgmt'
Entering 'platform/p4/SAI-P4-BM'
Entering 'platform/p4/SAI-P4-BM/p4-switch/behavioral-model'
Entering 'platform/p4/p4-hlir/p4-hlir'
Entering 'platform/p4/p4-hlir/p4-hlir-v1.1'
Entering 'platform/p4/p4c-bm/p4c-bm'
Entering 'src/ptf'
Entering 'src/redis-dump-load'
Entering 'src/sonic-dbsyncd'
Entering 'src/sonic-frr/frr'
Entering 'src/sonic-linux-kernel'
Entering 'src/sonic-platform-common'
Entering 'src/sonic-platform-daemons'
Entering 'src/sonic-py-swsssdk'
Entering 'src/sonic-quagga'
Entering 'src/sonic-sairedis'
Entering 'src/sonic-sairedis/SAI'
Entering 'src/sonic-sairedis/SAI/bm/behavioral-model'
Entering 'src/sonic-sairedis/SAI/test/ptf'
Entering 'src/sonic-sairedis/SAI/test/saithrift/ctypesgen'
Entering 'src/sonic-snmpagent'
Entering 'src/sonic-swss'
Entering 'src/sonic-swss-common'
Entering 'src/sonic-utilities'
make[1]: Leaving directory '/home/sonic/software/sonic-buildimage'

**Comment by yxieca** [comment]
Please rebase to latest 201811 branch. Call 'make init' to update submodules. execute "make configure" again, and build.

**Comment by ajuse** [comment]
@yxieca It worked, thank you very much.
