### ISSUE TITLE
Failed to install SONiC base image (sonic-generic.bin) with ONIE in our x86 switch

### ISSUE THREAD

**Issue by sonicyao1985** [Azure/sonic-buildimage#33]
In the following commit:
https://github.com/Azure/sonic-buildimage/commit/cc7f15094cb0f07d9461e40eb69b66f3ddeac7ae#diff-028739c9bdaa77f69d654ce551a93cec

In file installer/x86_64/install.sh, the following line is introduced:
source platforms/$onie_platform

Since we don't need extra cmd for our own platform, I didn't add a file under the "platforms" directory.
Thus the installing failed due to absence of the platform file.

I think it is better to check the existence of file before source it.

**Comment by lguohan** [comment]
addressing this in #37
