### ISSUE TITLE
vxlan json configs not applying to config_db

### ISSUE THREAD

**Issue by mfriyas** [Azure/sonic-buildimage#3300]
Hi,

While executing vxlan_decap failure am seeing vxlan config test is failing.After debugging i observed that the script trying to configure vxlan json configs from /tmp/vxlan.json. But configs are not apllied in config_db.

Manually tried loading vxlan.json file via 

sonic-cfggen -j /tmp/vxlan_db.Vlan1000.json --write-to-db

root@sonic-z9264f-04:/etc/sonic# sonic-cfggen -j /tmp/vxlan_db.Vlan1000.json --write-to-db

root@sonic-z9264f-03:/etc/sonic# cat config_db.json | grep "TUNNEL"

root@sonic-z9264f-03:/etc/sonic# cat /tmp/vxlan_db.Vlan1000.json
{
    "VXLAN_TUNNEL": {
        "tunnelVlan1000": {
            "src_ip": "10.1.0.32",
            "dst_ip": "8.8.3.239"
        }
    },
    "VXLAN_TUNNEL_MAP": {
        "tunnelVlan1000|map1": {
            "vni": "1336",
            "vlan": "Vlan1000"
        }
    }
}

root@sonic-z9264f-03:/etc/sonic# show version

SONiC Software Version: SONiC.HEAD.52-dirty-20190803.082606
Distribution: Debian 9.9
Kernel: 4.9.0-9-2-amd64
Build commit: 7e98e3f4
Build date: Sat Aug  3 08:37:40 UTC 2019
Built by: johnar@jenkins-worker-4

Platform: x86_64-dellemc_z9264f_c3538-r0
HwSKU: DellEMC-Z9264f-C64
ASIC: broadcom
Serial Number: CN030K8MDND0093E0004
Uptime: 22:14:19 up  6:42,  1 user,  load average: 0.83, 0.50, 0.46

Docker images:
REPOSITORY                 TAG                             IMAGE ID            SIZE
docker-syncd-brcm          HEAD.52-dirty-20190803.082606   d3d66071f629        391MB
docker-syncd-brcm          latest                          d3d66071f629        391MB
docker-fpm-frr             HEAD.52-dirty-20190803.082606   d63e86c7d696        319MB
docker-fpm-frr             latest                          d63e86c7d696        319MB
docker-lldp-sv2            HEAD.52-dirty-20190803.082606   c19ba75cc5ee        298MB
docker-lldp-sv2            latest                          c19ba75cc5ee        298MB
docker-dhcp-relay          HEAD.52-dirty-20190803.082606   7163c2af7a89        289MB
docker-dhcp-relay          latest                          7163c2af7a89        289MB
docker-database            HEAD.52-dirty-20190803.082606   fd0aa3c285d5        281MB
docker-database            latest                          fd0aa3c285d5        281MB
docker-snmp-sv2            HEAD.52-dirty-20190803.082606   b7773da9c938        312MB
docker-snmp-sv2            latest                          b7773da9c938        312MB
docker-orchagent           HEAD.52-dirty-20190803.082606   e3d28443c37d        321MB
docker-orchagent           latest

**Comment by pavel-shirshov** [comment]
you can see changes in the /etc/sonic/config_db.json after you run sudo config save -y.
Before that you can find the changes in the redis db.
I'm closing this. Please open it if you have further questions
