### ISSUE TITLE
ERR log is generated when there is no LED utility supported

### ISSUE THREAD

**Issue by scjuang** [Azure/sonic-buildimage#3302]
**Description**
An ERR SYSLOG will be generated from PMON when it cannot find LED utility. According to porting guide, this utility is optional if front panel LED can be controlled by hardware. Therefore, this should be recorded as INFO log, not ERR log.

(quoted from Porting Guide)
led_control.py
Python module providing a unified API for updating front-panel LED state. It is used by the SONiC LED control daemon.
_NOTE: This file is optional. If your device uses an an entirely hardware-based LED control solution you can omit this file for your device._

In sonic-mgmt test, log analyzer will check if any ERR log appears during test period, any ERR log will result in test case failed finally. But actually this is not a real error.

**Steps to reproduce the issue:**
Boot up the device that use hardware to control LED, e.g AS7712-32X, this ERR log will show up. 

**Describe the results you received:**
Nov  4 03:01:46.179228 sonic **ERR** pmon#ledd: Failed to load ledutil: Failed to load platform module 'led_control': [Errno 2] No such file or directory
Nov  4 03:01:46.179228 sonic INFO pmon#supervisord: ledd Failed to load ledutil: Failed to load platform module 'led_control': [Errno 2] No such file or directory

**Describe the results you expected:**
Nov  4 03:01:46.179228 sonic **INFO** pmon#ledd: Failed to load ledutil: Failed to load platform module 'led_control': [Errno 2] No such file or directory
Nov  4 03:01:46.179228 sonic INFO pmon#supervisord: ledd Failed to load ledutil: Failed to load platform module 'led_control': [Errno 2] No such file or directory

**Comment by jleveque** [comment]
@scjuang: There is a new mechanism you can leverage to prevent the ledd daemon from getting started in the PMon container. Using this, the daemon will not start, and this error message will not get logged. Here is an example: https://github.com/Azure/sonic-buildimage/blob/master/device/mellanox/x86_64-mlnx_msn2700-r0/pmon_daemon_control.json
