### ISSUE TITLE
Orchagent crash upon loading build 57

### ISSUE THREAD

**Issue by nazeerhussainf** [Azure/sonic-buildimage#3314]
**Description**
Orchagent crash is seen upon loading the build SONiC.HEAD.57-dirty-20190808.113157 on DELLEMC S6100 and Z9100. 
Also, most of the docker aren't up.
Attached core file.

root@sonic-s6100-07:/var/core# docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
d01a47b92496        docker-sonic-telemetry:latest    "/usr/bin/supervisord"   38 minutes ago      Up 3 minutes                            telemetry
d8b2b996706b        docker-lldp-sv2:latest           "/usr/bin/supervisord"   45 minutes ago      Up 3 minutes                            lldp
8bfd5ab22eec        docker-platform-monitor:latest   "/usr/bin/docker_ini\u2026"   45 minutes ago      Up 3 minutes                            pmon
f2437a3971fc        docker-fpm-frr:latest            "/usr/bin/supervisord"   45 minutes ago      Up 3 minutes                            bgp
d7f3a9fdbd35        docker-database:latest           "/usr/bin/supervisord"   45 minutes ago      Up 4 minutes                            database
root@sonic-s6100-07:/var/core#
[orchagent.1565334495.76.core.gz](https://github.com/Azure/sonic-buildimage/files/3485173/orchagent.1565334495.76.core.gz)

**Steps to reproduce the issue:**
1. Load the build SONiC.HEAD.57-dirty-20190808.113157 on S6100 or Z9100 and boot the device. Orchagent crash can be seen.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
 SONiC Software Version: SONiC.HEAD.57-dirty-20190808.113157
Distribution: Debian 9.9
Kernel: 4.9.0-9-2-amd64
Build commit: cc312793
Build date: Thu Aug  8 11:41:01 UTC 2019
Built by: johnar@jenkins-worker-4

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
Serial Number: 2G5ZZP2
Uptime: 07:11:08 up 4 min,  1 user,  load average: 2.15, 2.23, 1.04

Docker images:
REPOSITORY                 TAG                             IMAGE ID            SIZE
docker-syncd-brcm          HEAD.57-dirty-20190808.113157   df192dbca586        392MB
docker-syncd-brcm          latest                          df192dbca586        392MB
docker-fpm-frr             HEAD.57-dirty-20190808.113157   c856f40b8786        319MB
docker-fpm-frr             latest                          c856f40b8786        319MB
docker-lldp-sv2            HEAD.57-dirty-20190808.113157   ac1962448edc        298MB
docker-lldp-sv2            latest                          ac1962448edc        298MB
docker-dhcp-relay          HEAD.57-dirty-20190808.113157   6504c2fe19a2        289MB
docker-dhcp-relay          latest                          6504c2fe19a2        289MB
docker-database            HEAD.57-dirty-20190808.113157   eb6472caa6fe        281MB
docker-database            latest                          eb6472caa6fe        281MB
docker-snmp-sv2            HEAD.57-dirty-20190808.113157   9e4fc4499eeb        312MB
docker-snmp-sv2            latest                          9e4fc4499eeb        312MB
docker-orchagent           HEAD.57-dirty-20190808.113157   873953418700        321MB
docker-orchagent           latest                          873953418700        321MB
docker-teamd               HEAD.57-dirty-20190808.113157   7298fc774200        302MB
docker-teamd               latest                          7298fc774200        302MB
docker-sonic-telemetry     HEAD.57-dirty-20190808.113157   9a492ed2fc7a        304MB
docker-sonic-telemetry     latest                          9a492ed2fc7a        304MB
docker-router-advertiser   HEAD.57-dirty-20190808.113157   6021290b863f        281MB
docker-router-advertiser   latest                          6021290b863f        281MB
docker-platform-monitor    HEAD.57-dirty-20190808.113157   d23db561a6c1        325MB
docker-platform-monitor    latest                          d23db561a6c1        325MB
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by nazeerhussainf** [comment]
Still observing the issue on the Aug 27th build(Build 68).

**Comment by pavel-shirshov** [comment]
Please use https://github.com/Azure/SONiC/issues/458 to track the issue. The issue has a solution
Closing this as duplicate
