### ISSUE TITLE
[dhcp_relay]'wait_for_init.sh.j2'  translate duplicate if the interface has both ipv4 and ipv6 address  

### ISSUE THREAD

**Issue by wangshengjun** [Azure/sonic-buildimage#3316]
Signed-off-by: wangshengjun wangshengjun@asterfusion.com
Steps to reproduce the issue:
1.config the Portchannel interface with ipv4 and ipv6 address
 "PORTCHANNEL_INTERFACE": {
        "PortChannel0001": {}, 
        "PortChannel0002": {}, 
        "PortChannel0001|10.0.0.56/31": {}, 
        "PortChannel0001|FC00::71/126": {}, 
        "PortChannel0002|10.0.0.58/31": {}, 
        "PortChannel0002|FC00::75/126": {}
    }, 
2.  attach the  dhcp_relay docker, check the translated script 'wait_for_intf.sh'
docker exec -ti dhcp_relay bash
cat /usr/bin/wait_for_intf.sh 
...
Wait for all interfaces to be up and ready
wait_until_iface_ready ${LAG_TABLE_PREFIX} PortChannel0001
wait_until_iface_ready ${LAG_TABLE_PREFIX} PortChannel0001
wait_until_iface_ready ${LAG_TABLE_PREFIX} PortChannel0002
wait_until_iface_ready ${LAG_TABLE_PREFIX} PortChannel0002
...

Expected Result
the function of 'wait_until_iface_ready' called once for each interface.

**Comment by jleveque** [comment]
Resolved via https://github.com/Azure/sonic-buildimage/pull/3317
