### ISSUE TITLE
When we Switch from One Topology to Other , the Old Topology is still present 

### ISSUE THREAD

**Issue by DhinakaranDayalan** [Azure/sonic-buildimage#3370]
**Description**

**Steps to reproduce the issue:**
1. Load T0 Topology to the DUT using MSFT Test bed. 
2. T0 Topology is successfully Loaded and DUT is up with T0 Topology
3. Switch from T0 Topology to T1 Topology byLoading T1 Topology in Test bed
4. Load T1 Topology config using **"config load minigraph"** command from Test bed.
5. The T1 Topology is loaded successfully and T0 Portchannel are removed. 
6. When we issue **"show ip interface"** command still T0 Portchannel informations are present

**Describe the results you received:**
**T0 Topology Details**

admin@et6448m-M0:~$ show interfaces status
      Interface    Lanes    Speed    MTU       Alias             Vlan    Oper    Admin    Type    Asym PFC
---------------  -------  -------  -----  ----------  ---------------  ------  -------  ------  ----------
      Ethernet0        1       1G   9100   Ethernet0           routed    down     down     N/A         off
      Ethernet1        2       1G   9100   Ethernet1            trunk      up       up     N/A         off
      Ethernet2        3       1G   9100   Ethernet2            trunk      up       up     N/A         off
      Ethernet3        4       1G   9100   Ethernet3            trunk      up       up     N/A         off
      Ethernet4        5       1G   9100   Ethernet4            trunk      up       up     N/A         off
      Ethernet5        6       1G   9100   Ethernet5            trunk      up       up     N/A         off
      Ethernet6        7       1G   9100   Ethernet6            trunk      up       up     N/A         off
      Ethernet7        8       1G   9100   Ethernet7            trunk      up       up     N/A         off
      Ethernet8        9       1G   9100   Ethernet8            trunk      up       up     N/A         off
      Ethernet9       10       1G   9100   Ethernet9            trunk      up       up     N/A         off
     Ethernet10       11       1G   9100  Ethernet10            trunk      up       up     N/A         off
     Ethernet11       12       1G   9100  Ethernet11            trunk      up       up     N/A         off
     Ethernet12       13       1G   9100  Ethernet12            trunk      up       up     N/A         off
     Ethernet13       14       1G   9100  Ethernet13            trunk      up       up     N/A         off
     Ethernet14       15       1G   9100  Ethernet14            trunk      up       up     N/A         off
     Ethernet15       16       1G   9100  Ethernet15            trunk      up       up     N/A         off
     Ethernet16       17       1G   9100  Ethernet16            trunk      up       up     N/A         off
     Ethernet17       18       1G   9100  Ethernet17            trunk      up       up     N/A         off
     Ethernet18       19       1G   9100  Ethernet18            trunk      up       up     N/A         off
     Ethernet19       20       1G   9100  Ethernet19            trunk      up       up     N/A         off
     Ethernet20       21       1G   9100  Ethernet20            trunk      up       up     N/A         off
     Ethernet21       22       1G   9100  Ethernet21            trunk      up       up     N/A         off
     Ethernet22       23       1G   9100  Ethernet22            trunk      up       up     N/A         off
     Ethernet23       24       1G   9100  Ethernet23            trunk      up       up     N/A         off
     Ethernet24       25       1G   9100  Ethernet24            trunk      up       up     N/A         off
     Ethernet25       26       1G   9100  Ethernet25           routed    down     down     N/A         off
     Ethernet26       27       1G   9100  Ethernet26           routed    down     down     N/A         off
     Ethernet27       28       1G   9100  Ethernet27           routed    down     down     N/A         off
     Ethernet28       29       1G   9100  Ethernet28  PortChannel0001      up       up     N/A         off
     Ethernet29       30       1G   9100  Ethernet29  PortChannel0002      up       up     N/A         off
     Ethernet30       31       1G   9100  Ethernet30  PortChannel0003      up       up     N/A         off
     Ethernet31       32       1G   9100  Ethernet31  PortChannel0004      up       up     N/A         off
     Ethernet32       33       1G   9100  Ethernet32           routed    down     down     N/A         off
     Ethernet33       34       1G   9100  Ethernet33           routed    down     down     N/A         off
     Ethernet34       35       1G   9100  Ethernet34           routed    down     down     N/A         off
     Ethernet35       36       1G   9100  Ethernet35           routed    down     down     N/A         off
     Ethernet36       37       1G   9100  Ethernet36           routed    down     down     N/A         off
     Ethernet37       38       1G   9100  Ethernet37           routed    down     down     N/A         off
     Ethernet38       39       1G   9100  Ethernet38           routed    down     down     N/A         off
     Ethernet39       40       1G   9100  Ethernet39           routed    down     down     N/A         off
     Ethernet40       41       1G   9100  Ethernet40           routed    down     down     N/A         off
     Ethernet41       42       1G   9100  Ethernet41           routed    down     down     N/A         off
     Ethernet42       43       1G   9100  Ethernet42           routed    down     down     N/A         off
     Ethernet43       44       1G   9100  Ethernet43           routed    down     down     N/A         off
     Ethernet44       45       1G   9100  Ethernet44           routed    down     down     N/A         off
     Ethernet45       46       1G   9100  Ethernet45           routed    down     down     N/A         off
     Ethernet46       47       1G   9100  Ethernet46           routed    down     down     N/A         off
     Ethernet47       48       1G   9100  Ethernet47           routed    down     down     N/A         off
     Ethernet48       49       1G   9100  Ethernet48           routed    down     down     N/A         off
     Ethernet49       50       1G   9100  Ethernet49           routed    down     down     N/A         off
     Ethernet50       51       1G   9100  Ethernet50           routed    down     down     N/A         off
     Ethernet51       52       1G   9100  Ethernet51           routed    down     down     N/A         off
PortChannel0001      N/A       1G   9100         N/A           routed    down       up     N/A         N/A
PortChannel0002      N/A       1G   9100         N/A           routed    down       up     N/A         N/A
PortChannel0003      N/A       1G   9100         N/A           routed    down       up     N/A         N/A
PortChannel0004      N/A       1G   9100         N/A           routed    down       up     N/A         N/A
admin@et6448m-M0:~$
admin@et6448m-M0:~$ show interfaces  po
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  -------------
0001  PortChannel0001  LACP(A)(Dw)  Ethernet28(D)
0002  PortChannel0002  LACP(A)(Dw)  Ethernet29(D)
0003  PortChannel0003  LACP(A)(Dw)  Ethernet30(D)
0004  PortChannel0004  LACP(A)(Dw)  Ethernet31(D)

**T1 Topology Information**

* PortChannel Information is removed from "**show interface status"** but still present in **"show ip interface"**

admin@et6448m-M0:~$ show interfaces status
  Interface    Lanes    Speed    MTU       Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  -------  -------  -----  ----------  ------  ------  -------  ------  ----------
  Ethernet0        1       1G   9100   Ethernet0  routed      up       up     N/A         off
  Ethernet1        2       1G   9100   Ethernet1  routed      up       up     N/A         off
  Ethernet2        3       1G   9100   Ethernet2  routed      up       up     N/A         off
  Ethernet3        4       1G   9100   Ethernet3  routed      up       up     N/A         off
  Ethernet4        5       1G   9100   Ethernet4  routed      up       up     N/A         off
  Ethernet5        6       1G   9100   Ethernet5  routed      up       up     N/A         off
  Ethernet6        7       1G   9100   Ethernet6  routed      up       up     N/A         off
  Ethernet7        8       1G   9100   Ethernet7  routed      up       up     N/A         off
  Ethernet8        9       1G   9100   Ethernet8  routed      up       up     N/A         off
  Ethernet9       10       1G   9100   Ethernet9  routed      up       up     N/A         off
Ethernet10       11       1G   9100  Ethernet10  routed      up       up     N/A         off
Ethernet11       12       1G   9100  Ethernet11  routed      up       up     N/A         off
Ethernet12       13       1G   9100  Ethernet12  routed      up       up     N/A         off
Ethernet13       14       1G   9100  Ethernet13  routed      up       up     N/A         off
Ethernet14       15       1G   9100  Ethernet14  routed      up       up     N/A         off
Ethernet15       16       1G   9100  Ethernet15  routed      up       up     N/A         off
Ethernet16       17       1G   9100  Ethernet16  routed      up       up     N/A         off
Ethernet17       18       1G   9100  Ethernet17  routed      up       up     N/A         off
Ethernet18       19       1G   9100  Ethernet18  routed      up       up     N/A         off
Ethernet19       20       1G   9100  Ethernet19  routed      up       up     N/A         off
Ethernet20       21       1G   9100  Ethernet20  routed      up       up     N/A         off
Ethernet21       22       1G   9100  Ethernet21  routed      up       up     N/A         off
Ethernet22       23       1G   9100  Ethernet22  routed      up       up     N/A         off
Ethernet23       24       1G   9100  Ethernet23  routed      up       up     N/A         off
Ethernet24       25       1G   9100  Ethernet24  routed      up       up     N/A         off
Ethernet25       26       1G   9100  Ethernet25  routed      up       up     N/A         off
Ethernet26       27       1G   9100  Ethernet26  routed      up       up     N/A         off
Ethernet27       28       1G   9100  Ethernet27  routed      up       up     N/A         off
Ethernet28       29       1G   9100  Ethernet28  routed      up       up     N/A         off
Ethernet29       30       1G   9100  Ethernet29  routed      up       up     N/A         off
Ethernet30       31       1G   9100  Ethernet30  routed      up       up     N/A         off
Ethernet31       32       1G   9100  Ethernet31  routed      up       up     N/A         off
Ethernet32       33       1G   9100  Ethernet32  routed    down     down     N/A         off
Ethernet33       34       1G   9100  Ethernet33  routed    down     down     N/A         off
Ethernet34       35       1G   9100  Ethernet34  routed    down     down     N/A         off
Ethernet35       36       1G   9100  Ethernet35  routed    down     down     N/A         off
Ethernet36       37       1G   9100  Ethernet36  routed    down     down     N/A         off
Ethernet37       38       1G   9100  Ethernet37  routed    down     down     N/A         off
Ethernet38       39       1G   9100  Ethernet38  routed    down     down     N/A         off
Ethernet39       40       1G   9100  Ethernet39  routed    down     down     N/A         off
Ethernet40       41       1G   9100  Ethernet40  routed    down     down     N/A         off
Ethernet41       42       1G   9100  Ethernet41  routed    down     down     N/A         off
Ethernet42       43       1G   9100  Ethernet42  routed    down     down     N/A         off
Ethernet43       44       1G   9100  Ethernet43  routed    down     down     N/A         off
Ethernet44       45       1G   9100  Ethernet44  routed    down     down     N/A         off
Ethernet45       46       1G   9100  Ethernet45  routed    down     down     N/A         off
Ethernet46       47       1G   9100  Ethernet46  routed    down     down     N/A         off
Ethernet47       48       1G   9100  Ethernet47  routed    down     down     N/A         off
Ethernet48       49       1G   9100  Ethernet48  routed    down     down     N/A         off
Ethernet49       50       1G   9100  Ethernet49  routed    down     down     N/A         off
Ethernet50       51       1G   9100  Ethernet50  routed    down     down     N/A         off
Ethernet51       52       1G   9100  Ethernet51  routed    down     down     N/A         off
admin@et6448m-M0:~$
admin@et6448m-M0:~$ show ip interfaces
Interface        IPv4 address/mask    Admin/Oper
---------------  -------------------  ------------
Ethernet0        10.0.0.0/31          up/up
Ethernet1        10.0.0.2/31          up/up
Ethernet2        10.0.0.4/31          up/up
Ethernet3        10.0.0.6/31          up/up
Ethernet4        10.0.0.8/31          up/up
Ethernet5        10.0.0.10/31         up/up
Ethernet6        10.0.0.12/31         up/up
Ethernet7        10.0.0.14/31         up/up
Ethernet8        10.0.0.16/31         up/up
Ethernet9        10.0.0.18/31         up/up
Ethernet10       10.0.0.20/31         up/up
Ethernet11       10.0.0.22/31         up/up
Ethernet12       10.0.0.24/31         up/up
Ethernet13       10.0.0.26/31         up/up
Ethernet14       10.0.0.28/31         up/up
Ethernet15       10.0.0.30/31         up/up
Ethernet16       10.0.0.32/31         up/up
Ethernet17       10.0.0.34/31         up/up
Ethernet18       10.0.0.36/31         up/up
Ethernet19       10.0.0.38/31         up/up
Ethernet20       10.0.0.40/31         up/up
Ethernet21       10.0.0.42/31         up/up
Ethernet22       10.0.0.44/31         up/up
Ethernet23       10.0.0.46/31         up/up
Ethernet24       10.0.0.48/31         up/up
Ethernet25       10.0.0.50/31         up/up
Ethernet26       10.0.0.52/31         up/up
Ethernet27       10.0.0.54/31         up/up
Ethernet28       10.0.0.56/31         up/up
Ethernet29       10.0.0.58/31         up/up
Ethernet30       10.0.0.60/31         up/up
Ethernet31       10.0.0.62/31         up/up
PortChannel0001  10.0.0.56/31         up/down
PortChannel0002  10.0.0.58/31         up/down
PortChannel0003  10.0.0.60/31         up/down
PortChannel0004  10.0.0.62/31         up/down
docker0          240.127.1.1/24       up/down
eth0             10.28.42.43/24       up/up
lo               127.0.0.1/8          up/up
                 10.1.0.32/32
admin@et6448m-M0:~$
admin@et6448m-M0:~$ show in portchannel
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
No.    Team Dev    Protocol    Ports
-----  ----------  ----------  -------

**Describe the results you expected:**

When the config load mini-graph command is executed all the Information about the previous topology has to be removed and only current topology information must be loaded

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wendani** [comment]
The correct steps to switch from T0 to T1:
```
sudo ./testbed-cli.sh remove-topo <t0_testbed_name>
sudo ./testbed-cli.sh add-topo <t1_testbed_name>
sudo ansible-playbook -i str config_sonic_basedon_testbed.yml -l <dut_name> -e topo=t1 -e deploy=true -e testbed_name=<testbed_name>
```
on  DUT, do `sudo config save -y `

**Comment by DhinakaranDayalan** [comment]
Hi Wendani,

I am following the same steps you have mentioned

1. Deleted the OLD Topo
2. Add the New Topo
3. Load the Minigraph for the New Topo 
4. Save the Config

I see the Old config are still present in the JSON.
Actually the config load_minigraph command is not completely erasing the Old topo config and re-installing the new Topo Config. 
Rather its just appending the new configuration on the old Configuration. This is causing the new and old topo configuration exist together. if you need any more details please feel free to contact me.
