### ISSUE TITLE
Change made some time ago to delay snmp in favor of faster fast-reboot stopped working

### ISSUE THREAD

**Issue by stepanblyschak** [Azure/sonic-buildimage#3453]
**Description**

**Steps to reproduce the issue:**
1. docker ps # after fast-reboot
2. # uptime of snmp is same as all other containers
3.

**Describe the results you received:**
Delaying snmp really affect startup time in fast and warm reboot, but now it starts slower cause different issues (BGP flap, LAG flap)

**Describe the results you expected:**
SNMP container start is delayed

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by pavel-shirshov** [comment]
@stepanblyschak you're saying that it doesn't matter now, to delay snmp start or to don't delay it?

**Comment by jleveque** [comment]
@stepanblyschak: I am also confused as to what you are requesting here. Could you please add more information?

**Comment by stepanblyschak** [comment]
@jleveque @pavel-shirshov 
This change https://github.com/Azure/sonic-buildimage/commit/07ea9741fba01d862343f16fedb5fe5f1d27a01f#diff-d39caff3b7cc5743b317762b959ae11fR2 introduces delay for 3m30s  of counters thread and SNMP container. Change was introduced AFAIK to speed up system startup on fast-reboot flow (note: this affects warm-reboot as well)

This change https://github.com/Azure/sonic-buildimage/commit/6eca27e5647f5af9adc149ba3858955ca679f803#diff-f1225e24f7a66e6e78aedf4c7d7514f7R14 made SNMP start right after SWSS so previously introduced timer doesn't work anymore.

The question is:
1) Did we optimize sonic startup so that delay is not needed and we should stay with current behavior and just delete snmp.timer as it does not work?
2) Does second change break the optimization that was introduced in first change and should be fixed, so that SNMP will start with delay? Note, that SNMP will spam errors while counters are not available

**Comment by jleveque** [comment]
@qiluo-msft to comment

**Comment by qiluo-msft** [comment]
My understanding is that we should delay starting snmp docker container now, but current code is not.

**Comment by lguohan** [comment]
@pavel-shirshov , how to resolve this issue?

**Comment by pavel-shirshov** [comment]
@lguohan 
we can:
1. Revert the change which break the feature.
2. Or just remove the timer, if Fast-Reboot still works and we didn't find any regressions.

**Comment by stepanblyschak** [comment]
Should be fixed by https://github.com/Azure/sonic-buildimage/pull/3657

There is another interesting side effect of snmp.timer and ```WantedBy=swss.service```, if we do config reload right after start, during swss restart, after snmp has stopped snmp.timer may trigger snmp to start in the middle of config reload causing swss restart to fail. This should be fixed by https://github.com/Azure/sonic-buildimage/pull/3657.
