### ISSUE TITLE
Jenkins check-in builds fail with the error "no space left on device"

### ISSUE THREAD

**Issue by mikelazar** [Azure/sonic-buildimage#3565]
The pull request is:
https://github.com/Azure/sonic-buildimage/pull/3553

Please note that the pull -request does not affect the build process in any way.

For details, please refer to:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1100/console

---> Running in 331c7b687988
open **/var/lib/docker/vfs/dir/c71475e741cfe79d6526a6d97b713133aaaae7aac1b48b742ebae4409279bf84/usr/share/doc/libselinux1/copyright: no space left on device**
[  FAIL LOG END  ] [ target/docker-platform-monitor.gz ]
slave.mk:525: recipe for target 'target/docker-platform-monitor.gz' failed
make: *** [target/docker-platform-monitor.gz] Error 1

https://github.com/Azure/sonic-buildimage/pull/3553

**Comment by jleveque** [comment]
I freed up space on the Jenkins server. The test is rerunning now. If it succeeds, we can close this issue.

**Comment by jleveque** [comment]
Check builds all passed. Closing this issue.

**Comment by mikelazar** [comment]
@jleveque Thank you!
