### ISSUE TITLE
The ntp.conf file is empty in the recent November images

### ISSUE THREAD

**Issue by mini-nair-dell** [Azure/sonic-buildimage#3603]
Issue:
+++++++
The NTP.conf file has no data , and hence the script <> fails

The file is empty

Failed image
+++++++++++++

root@sonic-s6100-07:/etc# ls -l ntp.conf
-rw-r--r-- 1 root root 0 Oct 14 21:44 ntp.conf
root@sonic-s6100-07:/etc# show version

SONiC Software Version: SONiC.HEAD.169-afbb916
Distribution: Debian 9.11

Passed image
++++++++++++
The passed image has the NTP config in the NTP.conf file.
SONiC.HEAD.101-dirty-20191011.065656

Attached the syslog  and show tech for reference

Thanks
Mini

**Comment by lguohan** [comment]
@Anandaraj-Maharajan

**Comment by mini-nair-dell** [comment]
Closing this issue as it doesnt occur in the recent November branches

**Comment by mini-nair-dell** [comment]
Closing this issue as it doesnt occur in the recent November branches
