### ISSUE TITLE
Orchagent crash on Broadcom platforms with latest master 

### ISSUE THREAD

**Issue by neethajohn** [Azure/sonic-buildimage#3641]
**Description**

Oct 21 20:44:39.306454 str-7260cx3-acs-7 NOTICE swss#orchagent: :- init: broadcom switch capability:
Oct 21 20:44:39.306454 str-7260cx3-acs-7 NOTICE swss#orchagent: :- init:     ACL_TABLE_MIRROR: yes
Oct 21 20:44:39.306454 str-7260cx3-acs-7 NOTICE swss#orchagent: :- init:     ACL_TABLE_MIRRORV6: yes
Oct 21 20:44:39.309377 str-7260cx3-acs-7 NOTICE swss#orchagent: :- init: Get ACL entry priority values, min: 0, max: 2147483647
Oct 21 20:44:39.309587 str-7260cx3-acs-7 ERR syncd#syncd: brcm_sai_get_switch_attribute:2434 Unknown switch attribute 0[74] passed.
Oct 21 20:44:39.309824 str-7260cx3-acs-7 ERR swss#orchagent: :- queryAclActionCapability: AclOrch initialization failed: failed to query maximum ACL action count
Oct 21 20:44:39.310126 str-7260cx3-acs-7 INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::runtime_error'
Oct 21 20:44:39.310126 str-7260cx3-acs-7 INFO swss#supervisord: orchagent   what():  :- queryAclActionCapability: AclOrch initialization failed: failed to query maximum ACL action count
Oct 21 20:44:39.429146 str-7260cx3-acs-7 INFO swss#supervisor-proc-exit-listener: Process orchagent exited unxepectedly. Terminating supervisor...

**Steps to reproduce the issue:**
Loaded Broadcom build 108

ONiC Software Version: SONiC.HEAD.108-dirty-20191021.064610
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: 6cb445cb
Build date: Mon Oct 21 07:02:22 UTC 2019
Built by: johnar@jenkins-worker-4

Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-Q64
ASIC: broadcom
Serial Number: SSJ17450492
Uptime: 21:19:08 up 18 min,  1 user,  load average: 0.20, 0.27, 0.33

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-syncd-brcm          HEAD.108-dirty-20191021.064610   1c02005fb70f        391MB
docker-syncd-brcm          latest                           1c02005fb70f        391MB
docker-fpm-frr             HEAD.108-dirty-20191021.064610   6eeb277f200a        319MB
docker-fpm-frr             latest                           6eeb277f200a        319MB
docker-sflow               HEAD.108-dirty-20191021.064610   398d1efd264e        303MB
docker-sflow               latest                           398d1efd264e        303MB
docker-lldp-sv2            HEAD.108-dirty-20191021.064610   daa7236d5ece        298MB
docker-lldp-sv2            latest                           daa7236d5ece        298MB
docker-dhcp-relay          HEAD.108-dirty-20191021.064610   2e6ff2c6ed69        288MB
docker-dhcp-relay          latest                           2e6ff2c6ed69        288MB
docker-database            HEAD.108-dirty-20191021.064610   2cccc8283911        280MB
docker-database            latest                           2cccc8283911        280MB
docker-snmp-sv2            HEAD.108-dirty-20191021.064610   9d9d55a8b1d2        334MB
docker-snmp-sv2            latest                           9d9d55a8b1d2        334MB
docker-orchagent           HEAD.108-dirty-20191021.064610   49feb6944924        321MB
docker-orchagent           latest                           49feb6944924        321MB
docker-teamd               HEAD.108-dirty-20191021.064610   9f3b626ee116        302MB
docker-teamd               latest                           9f3b626ee116        302MB
docker-sonic-telemetry     HEAD.108-dirty-20191021.064610   96d37c032f62        303MB
docker-sonic-telemetry     latest                           96d37c032f62        303MB
docker-router-advertiser   HEAD.108-dirty-20191021.064610   c3f93695ecb0        280MB
docker-router-advertiser   latest                           c3f93695ecb0        280MB
docker-platform-monitor    HEAD.108-dirty-20191021.064610   424522422c14        328MB
docker-platform-monitor    latest                           424522422c14        328MB

**Comment by stepanblyschak** [comment]
@neethajohn @stcheng Does brcm support SAI_SWITCH_ATTR_MAX_ACL_ACTION_COUNT?

**Comment by iMasaruOki** [comment]
In my environment (Broadcom Trident3 switch),  commit 09171575 is works fine.

**Comment by disaster123** [comment]
For me it works fine on latest master from yesterday or today.

**Comment by stepanblyschak** [comment]
Fixed by https://github.com/Azure/sonic-swss/pull/1106
