### ISSUE TITLE
Boot type during config reload after fast reboot is invalid

### ISSUE THREAD

**Issue by nazariig** [Azure/sonic-buildimage#3697]
**Description**
After the fast reboot, on the next config reload, the system behaves in the same way as during the fast reboot flow. 

It seems that the boot type detection logic in sonic-buildimage and sonic-sairedis are not aligned:

sonic-buildimage/files/scripts/syncd.sh
```bash
function getBootType()
{
    # same code snippet in files/build_templates/docker_image_ctl.j2
    case "$(cat /proc/cmdline)" in
    *SONIC_BOOT_TYPE=warm*)
        TYPE='warm'
        ;;
    *SONIC_BOOT_TYPE=fastfast*)
        TYPE='fastfast'
        ;;
    *SONIC_BOOT_TYPE=fast*|*fast-reboot*)
        TYPE=$(awk '{ if ($1 <= 180) print "fast"; else print "cold" }' /proc/uptime)
        ;;
    *)
        TYPE='cold'
    esac
    echo "${TYPE}"
}
```

sonic-sairedis/syncd/scripts/syncd_init_common.sh
```bash
case "$(cat /proc/cmdline)" in
  *SONIC_BOOT_TYPE=fastfast*)
    if [ -e /var/warmboot/warm-starting ]; then
        FASTFAST_REBOOT='yes'
    fi
    ;;
  *SONIC_BOOT_TYPE=fast*|*fast-reboot*)
     FAST_REBOOT='yes'
    ;;
  *)
     FAST_REBOOT='no'
     FASTFAST_REBOOT='no'
    ;;
esac

...

function set_start_type()
{
    if [ x"$WARM_BOOT" == x"true" ]; then
        CMD_ARGS+=" -t warm"
    elif [ x"$FAST_REBOOT" == x"yes" ]; then
        CMD_ARGS+=" -t fast"
    elif [ x"$FASTFAST_REBOOT" == x"yes" ]; then
        CMD_ARGS+=" -t fastfast"
    fi
}
```

**Steps to reproduce the issue:**
1. fast-reboot
2. config reload -y

**Describe the results you received:**
```bash
root@sonic:/home/admin# docker exec -ti syncd bash
root@sonic:/# ps -aux | grep [s]yncd
root        23  5.1  2.5 1265152 207064 pts/0  Sl   13:15   0:04 /usr/bin/syncd -u -p /tmp/sai.profile -t fast -r -m /usr/share/sonic/hwsku/port_config.ini
```

**Describe the results you expected:**
```bash
root@sonic:/home/admin# docker exec -ti syncd bash
root@sonic:/# ps -aux | grep [s]yncd
root        23  5.1  2.5 1265152 207064 pts/0  Sl   13:15   0:04 /usr/bin/syncd -u -p /tmp/sai.profile -t cold -r -m /usr/share/sonic/hwsku/port_config.ini
```

**Additional information you deem important (e.g. issue happens only occasionally):**
* N/A

**Comment by pavel-shirshov** [comment]
I think that it wouldn't be enough.
If someone restart bgp container without reloading config, bgpd will think we're still in fast-reboot mode.
I think we should disable FAST-REBOOT mode in 3 minutes. 

We can as you propose put the key into the DB and remove it in 3 minutes (or by config reload).
In the scripts we will check the key.
Will it work for you?

**Comment by stepanblyschak** [comment]
@pavel-shirshov I wasn't aware about BGP case, a new fastboot-finalizer service (similarly to warmboot-service) can remove the key after 3 min. It will work for me.

**Comment by pavel-shirshov** [comment]
https://github.com/Azure/sonic-buildimage/pull/3741
