### ISSUE TITLE
When I execute "make all", it stays here. It will not continue.

### ISSUE THREAD

**Issue by zouzhao6** [Azure/sonic-buildimage#3802]
![image](https://user-images.githubusercontent.com/57378160/69414723-3a015f00-0d4e-11ea-90ac-1581d23fbaa7.png)
When I execute "make all", it stays here. It will not continue.

**Comment by lguohan** [comment]
kernel build took a long time.

**Comment by zouzhao6** [comment]
It's been here for three days.
