### ISSUE TITLE
One interface is administratively down after config reload/cold start/swss restart

### ISSUE THREAD

**Issue by stephenxs** [Azure/sonic-buildimage#3842]
**Description**

One interface is administratively down after the start flow, including cold start, config reload, swss restart, etc. 

**Steps to reproduce the issue:**

This issue can occur after any start flow of SONiC.

**Describe the results you received:**
***The flow should be like this:***

1. system restarts.
2. portmgrd receives admin status notification and set port's admin status to up

    on 201811

        Dec 26 17:32:32.188828 mtbc-sonic-01-2410 NOTICE swss#portmgrd: :- doTask: Configure Ethernet120 admin status to up

    on bmtor

        Dec 31 05:08:26.405828 r-tigris-13 NOTICE swss#portmgrd: :- doTask: Configure Ethernet40 admin status to up
        Dec 31 05:08:27.106377 r-tigris-13 NOTICE swss#portmgrd: :- doTask: Configure Ethernet52 admin status to up

3. After system started, the interface is still admin down.

    on 201911

        admin@mtbc-sonic-01-2410:~$ sudo ifconfig Ethernet120
        Ethernet120: flags=4098<BROADCAST,MULTICAST>  mtu 9100
                ether 98:03:9b:f3:f5:00  txqueuelen 1000  (Ethernet)
                RX packets 0  bytes 0 (0.0 B)
                RX errors 0  dropped 0  overruns 0  frame 0
                TX packets 0  bytes 0 (0.0 B)
                TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    on bmtor

        admin@r-tigris-13:~$ sudo ifconfig Ethernet40
        Ethernet40: flags=4098<BROADCAST,MULTICAST>  mtu 9100
                ether b8:59:9f:a9:2a:00  txqueuelen 1000  (Ethernet)
                RX packets 0  bytes 0 (0.0 B)
                RX errors 0  dropped 0  overruns 0  frame 0
                TX packets 0  bytes 0 (0.0 B)
                TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        admin@r-tigris-13:~$ sudo ifconfig Ethernet52
        Ethernet52: flags=4098<BROADCAST,MULTICAST>  mtu 9100
                ether b8:59:9f:a9:2a:00  txqueuelen 1000  (Ethernet)
                RX packets 0  bytes 0 (0.0 B)
                RX errors 0  dropped 0  overruns 0  frame 0
                TX packets 0  bytes 0 (0.0 B)
                TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

4. the show interface indicates the interface is administratively up, which doesn't align with the sysfs.

            Interface            Lanes    Speed    MTU    Alias             Vlan    Oper    Admin                    Type    Asym PFC
        ---------------  ---------------  -------  -----  -------  ---------------  ------  -------  ----------------------  ----------
            Ethernet0          0,1,2,3      10G   9100     etp1  PortChannel0002      up       up  Unknown or unspecified         off
            Ethernet4          4,5,6,7      10G   9100     etp2  PortChannel0002      up       up  Unknown or unspecified         off
            Ethernet8        8,9,10,11      10G   9100     etp3  PortChannel0005      up       up  Unknown or unspecified         off
            Ethernet12      12,13,14,15      10G   9100     etp4  PortChannel0005      up       up  Unknown or unspecified         off
            Ethernet16      16,17,18,19      10G   9100     etp5  PortChannel0008      up       up  Unknown or unspecified         off
            Ethernet20      20,21,22,23      10G   9100     etp6  PortChannel0008      up       up  Unknown or unspecified         off
            Ethernet24      24,25,26,27      10G   9100     etp7  PortChannel0011      up       up  Unknown or unspecified         off
            Ethernet28      28,29,30,31      10G   9100     etp8  PortChannel0011      up       up  Unknown or unspecified         off
            Ethernet32      32,33,34,35      50G   9100     etp9  PortChannel0014      up       up         QSFP28 or later         off
            Ethernet36      36,37,38,39      50G   9100    etp10  PortChannel0014      up       up         QSFP28 or later         off
            Ethernet40      40,41,42,43      50G   9100    etp11  PortChannel0017      up       up         QSFP28 or later         off
            Ethernet44      44,45,46,47      50G   9100    etp12  PortChannel0017      up       up         QSFP28 or later         off
            Ethernet48      48,49,50,51      50G   9100    etp13  PortChannel0020      up       up         QSFP28 or later         off
            Ethernet52      52,53,54,55      50G   9100    etp14  PortChannel0020      up       up         QSFP28 or later         off
            Ethernet56      56,57,58,59      50G   9100    etp15  PortChannel0023      up       up         QSFP28 or later         off
            Ethernet60      60,61,62,63      50G   9100    etp16  PortChannel0023      up       up         QSFP28 or later         off

**Describe the results you expected:**

The interface should be up.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue can occur on master, bmtor and 201911. I observed the issue approximately at the end of Nov. for the first time. But it occurs more frequently recently.

    **Output of `show version`:**

    201911

        SONiC Software Version: SONiC.HEAD.2-1de13ca5
        Distribution: Debian 9.11
        Kernel: 4.9.0-9-2-amd64
        Build commit: 1de13ca5
        Build date: Wed Dec 18 10:49:37 UTC 2019
        Built by: johnar@jenkins-worker-8

        Platform: x86_64-mlnx_msn2410-r0
        HwSKU: ACS-MSN2410
        ASIC: mellanox
        Serial Number: MT1848K10623
        Uptime: 08:33:44 up 1 day, 18:45,  1 user,  load average: 3.09, 3.28, 3.53

        Docker images:
        REPOSITORY                 TAG                 IMAGE ID            SIZE
        docker-syncd-mlnx          HEAD.2-1de13ca5     8f4c738d801e        373MB
        docker-syncd-mlnx          latest              8f4c738d801e        373MB
        docker-platform-monitor    HEAD.2-1de13ca5     504213009feb        565MB
        docker-platform-monitor    latest              504213009feb        565MB
        docker-fpm-frr             HEAD.2-1de13ca5     40f185147cdd        321MB
        docker-fpm-frr             latest              40f185147cdd        321MB
        docker-sflow               HEAD.2-1de13ca5     3dcfeefed710        305MB
        docker-sflow               latest              3dcfeefed710        305MB
        docker-lldp-sv2            HEAD.2-1de13ca5     4005620b16cb        299MB
        docker-lldp-sv2            latest              4005620b16cb        299MB
        docker-dhcp-relay          HEAD.2-1de13ca5     d27627fa9e66        289MB
        docker-dhcp-relay          latest              d27627fa9e66        289MB
        docker-database            HEAD.2-1de13ca5     dc7ec067d322        281MB
        docker-database            latest              dc7ec067d322        281MB
        docker-teamd               HEAD.2-1de13ca5     cf7e9d08ea99        304MB
        docker-teamd               latest              cf7e9d08ea99        304MB
        docker-snmp-sv2            HEAD.2-1de13ca5     a8fe61eb3d6f        335MB
        docker-snmp-sv2            latest              a8fe61eb3d6f        335MB
        docker-orchagent           HEAD.2-1de13ca5     32aa0cbb92cc        323MB
        docker-orchagent           latest              32aa0cbb92cc        323MB
        docker-sonic-telemetry     HEAD.2-1de13ca5     89f29821c6c0        304MB
        docker-sonic-telemetry     latest              89f29821c6c0        304MB
        docker-router-advertiser   HEAD.2-1de13ca5     7c9efd704beb        281MB
        docker-router-advertiser   latest              7c9efd704beb        281MB

    bmtor

        SONiC Software Version: SONiC.HEAD.19-73ecd617
        Distribution: Debian 9.11
        Kernel: 4.9.0-9-2-amd64
        Build commit: 73ecd617
        Build date: Thu Dec 19 11:32:55 UTC 2019
        Built by: johnar@jenkins-worker-11

        Platform: x86_64-mlnx_msn3800-r0
        HwSKU: ACS-MSN3800
        ASIC: mellanox
        Serial Number: MT1937X00527
        Uptime: 07:45:23 up  2:38,  1 user,  load average: 4.17, 3.76, 3.56

        Docker images:
        REPOSITORY                 TAG                 IMAGE ID            SIZE
        docker-syncd-mlnx          HEAD.19-73ecd617    5f6a8e0b93c2        372MB
        docker-syncd-mlnx          latest              5f6a8e0b93c2        372MB
        docker-fpm-frr             HEAD.19-73ecd617    2a546151a689        319MB
        docker-fpm-frr             latest              2a546151a689        319MB
        docker-lldp-sv2            HEAD.19-73ecd617    cf4d5678a102        298MB
        docker-lldp-sv2            latest              cf4d5678a102        298MB
        docker-dhcp-relay          HEAD.19-73ecd617    d4260615a23d        288MB
        docker-dhcp-relay          latest              d4260615a23d        288MB
        docker-database            HEAD.19-73ecd617    66a2fc6dde81        280MB
        docker-database            latest              66a2fc6dde81        280MB
        docker-sflow               HEAD.19-73ecd617    8cf8de27a97c        303MB
        docker-sflow               latest              8cf8de27a97c        303MB
        docker-teamd               HEAD.19-73ecd617    7a452cc7c3d0        303MB
        docker-teamd               latest              7a452cc7c3d0        303MB
        docker-snmp-sv2            HEAD.19-73ecd617    4f4564f031d8        334MB
        docker-snmp-sv2            latest              4f4564f031d8        334MB
        docker-orchagent           HEAD.19-73ecd617    4b60147d3007        321MB
        docker-orchagent           latest              4b60147d3007        321MB
        docker-sonic-telemetry     HEAD.19-73ecd617    560dbac8741d        303MB
        docker-sonic-telemetry     latest              560dbac8741d        303MB
        docker-router-advertiser   HEAD.19-73ecd617    58572c9eaad7        280MB
        docker-router-advertiser   latest              58572c9eaad7        280MB
        docker-platform-monitor    HEAD.19-73ecd617    3c306b7fd73f        564MB
        docker-platform-monitor    latest              3c306b7fd73f        564MB

    **Attach debug file `sudo generate_dump`:**
[syslog.132.gz](https://github.com/Azure/sonic-buildimage/files/4009301/syslog.132.gz)
[syslog.133.gz](https://github.com/Azure/sonic-buildimage/files/4009302/syslog.133.gz)
[syslog.1.gz](https://github.com/Azure/sonic-buildimage/files/4012146/syslog.1.gz)
    ```
    (paste your output here)
    ```

**Comment by stephenxs** [comment]
after swss called "enable ports", the netdev is still shutdown.

**Comment by stephenxs** [comment]
Update the issue with the latest findings.

**Comment by prsunny** [comment]
@zhenggen-xu , can you please check this? I'm not sure if its something broken recently.

**Comment by stephenxs** [comment]
We haven't observed this issue for a long time. Close it.

**Comment by stephenxs** [comment]
We haven't observed this issue for a long time. Close it.
