### ISSUE TITLE
Tomahawk3 (TH3) SDK init fail after  Upgrade broadcom SAI to 3.7.3.2

### ISSUE THREAD

**Issue by fillmorechen0928** [Azure/sonic-buildimage#3944]
Description
+++++++++++++++
2019/ 12 /19  [broadom]: Upgrade broadcom SAI to 3.7.3.2

Tomahawk3 (TH3) SDK init fail after Upgrade broadcom SAI to 3.7.3.2

Syncd Log:

sonic INFO syncd#supervisord: syncd Platform configuration file "/usr/share/sonic/hwsku/th3-snj60b0-32x400G.config.bcm" is used#015
sonic INFO syncd#supervisord: syncd Platform Boot flags: 0x0#015
sonic NOTICE syncd#syncd: message repeated 33 times: [ :- loadRedisScript: lua script loaded, sha: 88270a7c5c90583e56425aca8af8a4b8c39fe757]
sonic INFO syncd#syncd: [none] board_id_default:445 Failed to obtain switch ID.
sonic INFO syncd#supervisord: syncd linux-user-bde: no devices#015
sonic INFO syncd#supervisord: syncd DMA pool size: 16777216#015
sonic INFO syncd#syncd: message repeated 11 times: [ [none] board_id_default:445 Failed to obtain switch ID.]
sonic CRIT syncd#syncd: [none] platformInit:1745 No attached units.
sonic CRIT syncd#syncd: [none] sai_driver_init:207 Error initializing driver, rc = -1.
sonic CRIT syncd#syncd: [none] brcm_sai_create_switch:513 initializing SDK failed with error Operation failed (0xfffffff5).

Before Upgrading broadcom SAI to 3.7.3.2, the TH3 sdk init ok.

**Comment by fillmorechen0928** [comment]
Syslog for Reference:
[syslog.txt](https://github.com/Azure/sonic-buildimage/files/4000003/syslog.txt)

**Comment by richard28530** [comment]
Nov 10 21:21:30 sonic kernel: [    8.927921] linux_kernel_bde: loading out-of-tree module taints kernel.
Nov 10 21:21:30 sonic kernel: [    8.931057] linux-kernel-bde (500): _init(2957):use_msi = 0
Nov 10 21:21:30 sonic kernel: [    8.932518] linux-kernel-bde (500): Not find vendor(0x184e) device(0x1004) bus
Nov 10 21:21:30 sonic kernel: [    8.932522] linux-kernel-bde (500): Not find vendor(0x184e) device(0x1004) bus
Nov 10 21:21:30 sonic kernel: [    8.932525] linux-kernel-bde (500): Not find vendor(0x184e) device(0x1004) bus
Nov 10 21:21:30 sonic kernel: [    8.932527] linux-kernel-bde (500): Not find vendor(0x184e) device(0x1004) bus
Nov 10 21:21:30 sonic kernel: [    9.010317] linux-kernel-bde (501): Allocating DMA memory using method dmaalloc=0
Nov 10 21:21:30 sonic kernel: [    9.011972] linux-kernel-bde (501): _use_dma_mapping:0 _dma_vbase:ffff888435400000 _dma_pbase:35400000 _cpu_pbase:35400000 allocated:1000000 dmaalloc:0


Nov 10 21:23:41.507350 sonic INFO syncd#supervisord: syncd linux-user-bde: no devices#015

there is something wrong with the kernel bde

have you upgrade your kernel bdes associated with proper SDK version.
3.7.x use SDK 6.5.16 

what SAI version you use before ?

**Comment by judyjoseph** [comment]
Hi,
    In the log file the TH3 device is detected by linux-kernel-bde driver after the reboot .. ? Check towards the end of the syslog attached ..

Nov 10 21:52:02.174190 sonic INFO opennsl-modules[502]: Load OpenNSL kernel modules... /etc/init.d/opennsl-modules: line 51: /usr/share/sonic/device/x86_64-alphanetworks_snj60b0_320f-r0/platform_env.conf: No such file or directory
Nov 10 21:52:02.177017 sonic INFO systemd[1]: Started LSB: Set sysfs variables from /etc/sysfs.conf.
Nov 10 21:52:02.212031 sonic WARNING kernel: [    9.710683] linux_kernel_bde: loading out-of-tree module taints kernel.
Nov 10 21:52:02.219795 sonic WARNING kernel: [    9.717604] linux-kernel-bde (547): _init(2957):use_msi = 0
Nov 10 21:52:02.219940 sonic WARNING kernel: [    9.718722] linux-kernel-bde (547): probing: vendor_id=0x14e4, device_id=0xb980
Nov 10 21:52:02.219947 sonic WARNING kernel: [    9.718731] linux-kernel-bde (547): Enabling PCI device : vendor_id=0x14e4, device_id=0xb980
Nov 10 21:52:02.219951 sonic INFO kernel: [    9.718881] linux-kernel-bde 0000:06:00.0: enabling device (0100 -> 0102)
Nov 10 21:52:02.223327 sonic WARNING kernel: [    9.720923] linux-kernel-bde (547): found irq 30
Nov 10 21:52:02.223430 sonic WARNING kernel: [    9.720930] linux-kernel-bde (547): _pci_probe:irq = 30

**Comment by fillmorechen0928** [comment]
Issue fixed.
Porting guide updates about platform_env.conf.
But i don't know about this.

**Comment by lguohan** [comment]
is there a PR to fix this issue?

**Comment by fillmorechen0928** [comment]
> is there a PR to fix this issue?

No, this is for porting new platform. 

Thanks a lot.

**Comment by wzlxyx** [comment]
I meet the same issu.  I cannot get any useful information from above commit.  How did you resolve this issus ?

**Comment by wzlxyx** [comment]
i fixed my problem. refer this https://github.com/Azure/sonic-buildimage/pull/1053/files

**Comment by zhengbiqing** [comment]
@fillmorechen0928  hi, "Tomahawk3 (TH3) SDK init fail after Upgrade broadcom SAI to 3.7.3.2", the SAI is a open source package? where can I get it? 
How to integrate broadcom SDK and broadcom SAI into Sonic? Is there any doc about it?
Thanks!

**Comment by fillmorechen0928** [comment]
@zhengbiqing hi, please reference: 
https://github.com/Azure/sonic-buildimage/commits/master/platform/broadcom/saibcm-modules

Broadcom SDK and Broadcom SAI are already in SONiC.

**Comment by zhengbiqing** [comment]
@fillmorechen0928  thanks!  

there are some files in platform/broadcom/saibcm-modules,  but only 278 items and the size is only 2.2M. 

I am not know what you mean.  can you give me more information about this? Thank you very much.
