### ISSUE TITLE
 Accton-AS9716-32D - decode-syseeprom error

### ISSUE THREAD

**Issue by dlringor** [Azure/sonic-buildimage#3983]
**Description**

**Steps to reproduce the issue:**
1. Install last successfulbuild sonic-broadcom.bin build date Jan 6, 2020, (SONiC Software Version: SONiC.HEAD.168-dirty-20200106.050955)
2. run the command "show version" and "show plaform syseeprom" to hit the error
3.

**Describe the results you received:**
admin@sonic:~$ show version

SONiC Software Version: SONiC.HEAD.168-dirty-20200106.050955
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: 12212467
Build date: Mon Jan  6 05:18:36 UTC 2020
Built by: johnar@jenkins-worker-11

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
/usr/bin/decode-syseeprom : ERROR : [Errno 2] No such file or directory: '/sys/bus/i2c/devices/0-005                                                                                                                                         6/eeprom'
Serial Number:
Uptime: 15:41:09 up 13 min,  1 user,  load average: 0.07, 0.11, 0.13

Docker images:
REPOSITORY                    TAG                              IMAGE ID            SIZE
docker-syncd-brcm             HEAD.168-dirty-20200106.050955   8482b225fc7f        428MB
docker-syncd-brcm             latest                           8482b225fc7f        428MB
docker-platform-monitor       HEAD.168-dirty-20200106.050955   ecfe46900d91        333MB
docker-platform-monitor       latest                           ecfe46900d91        333MB
docker-fpm-frr                HEAD.168-dirty-20200106.050955   a37e2114ddcf        325MB
docker-fpm-frr                latest                           a37e2114ddcf        325MB
docker-lldp-sv2               HEAD.168-dirty-20200106.050955   05587034aa57        303MB
docker-lldp-sv2               latest                           05587034aa57        303MB
docker-dhcp-relay             HEAD.168-dirty-20200106.050955   ef3f3f8c35b9        290MB
docker-dhcp-relay             latest                           ef3f3f8c35b9        290MB
docker-database               HEAD.168-dirty-20200106.050955   73820d6b967e        282MB
docker-database               latest                           73820d6b967e        282MB
docker-sflow                  HEAD.168-dirty-20200106.050955   098f9fc7addb        305MB
docker-sflow                  latest                           098f9fc7addb        305MB
docker-teamd                  HEAD.168-dirty-20200106.050955   134d0ebef28f        305MB
docker-teamd                  latest                           134d0ebef28f        305MB
docker-snmp-sv2               HEAD.168-dirty-20200106.050955   64b368cc002c        339MB
docker-snmp-sv2               latest                           64b368cc002c        339MB
docker-orchagent              HEAD.168-dirty-20200106.050955   cdbbe4e2cd35        323MB
docker-orchagent              latest                           cdbbe4e2cd35        323MB
docker-sonic-mgmt-framework   HEAD.168-dirty-20200106.050955   5d15bc99914e        330MB
docker-sonic-mgmt-framework   latest                           5d15bc99914e        330MB
docker-sonic-telemetry        HEAD.168-dirty-20200106.050955   a6bcaf3f2556        343MB
docker-sonic-telemetry        latest                           a6bcaf3f2556        343MB
docker-router-advertiser      HEAD.168-dirty-20200106.050955   469becf3ba16        282MB
docker-router-advertiser      latest                           469becf3ba16        282MB

admin@sonic:~$ show platform syseeprom
/usr/bin/decode-syseeprom : ERROR : [Errno 2] No such file or directory: '/sys/bus/i2c/devices/0-0056/eeprom'
admin@sonic:~$ timed out waiting for input: auto-logout

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wally-wang-accton** [comment]
You can reference
https://github.com/Azure/sonic-buildimage/pull/3985
You need to update two files.
platform/broadcom/sonic-platform-modules-accton/as9716-32d/utils/accton_as9716_32d_util.py
device/accton/x86_64-accton_as9716_32d-r0/plugins/eeprom.py

**Comment by dlringor** [comment]
Hi Wally-wang,

Thank you for the information.  I have updated the two files that you mentioned and edit the following (I just changed the number 56 to 57):

On sonic-buildimage/platform/broadcom/sonic-platform-modules-accton/as9716-32d/utils/accton_as9716_32d_util.py:
line 128: 'echo 24c02 0x57 > /sys/bus/i2c/devices/i2c-0/new_device',

On sonic-buildimage/device/accton/x86_64-accton_as9716_32d-r0/plugins/eeprom.py:
line 20:         self.eeprom_path = "/sys/bus/i2c/devices/0-0057/eeprom"

It looks like the syseeeprom location got fixed.  However, my build shows it is still dirty.  I will greatly appreciate any suggestion. Thank you.

admin@sonic:~$ show platform syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 172
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21  15 9716-32D-O-AC-F
Part Number          0x22  13 FP5ZZ8632006A
Serial Number        0x23  14 971632D1946004
Base MAC Address     0x24   6 68:21:5F:27:23:C0
Manufacture Date     0x25  19 12/09/2019 14:17:04
Label Revision       0x27   4 R01A
Platform Name        0x28  27 x86_64-accton_as9716_32D-r0
ONIE Version         0x29  13 2019.08.00.03
MAC Addresses        0x2A   2 256
Manufacturer         0x2B   6 Accton
Manufacture Country  0x2C   2 TW
Vendor Name          0x2D   8 Edgecore
Diag Version         0x2E  11 01.01.00.17
CRC-32               0xFE   4 0x0C26CC5B

(checksum valid)

admin@sonic:~$ show version

SONiC Software Version: SONiC.master.0-dirty-20200120.152041
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: d0d1a559
Build date: Tue Jan 21 03:36:10 UTC 2020
Built by: don@dell1

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
Serial Number: 971632D1946004
Uptime: 11:36:11 up 1 min,  1 user,  load average: 1.57, 0.51, 0.18

Docker images:
REPOSITORY                    TAG                              IMAGE ID                                                                                                                                                                         SIZE
docker-syncd-brcm             latest                           9d1fb27f9cb4                                                                                                                                                                     429MB
docker-syncd-brcm             master.0-dirty-20200120.152041   9d1fb27f9cb4                                                                                                                                                                     429MB
docker-platform-monitor       latest                           fd97d693bb8b                                                                                                                                                                     333MB
docker-platform-monitor       master.0-dirty-20200120.152041   fd97d693bb8b                                                                                                                                                                     333MB
docker-fpm-frr                latest                           57b31e1efb4f                                                                                                                                                                     325MB
docker-fpm-frr                master.0-dirty-20200120.152041   57b31e1efb4f                                                                                                                                                                     325MB
docker-lldp-sv2               latest                           e147346ad8dd                                                                                                                                                                     303MB
docker-lldp-sv2               master.0-dirty-20200120.152041   e147346ad8dd                                                                                                                                                                     303MB
docker-router-advertiser      latest                           67026bc0caf8                                                                                                                                                                     282MB
docker-router-advertiser      master.0-dirty-20200120.152041   67026bc0caf8                                                                                                                                                                     282MB
docker-dhcp-relay             latest                           5e2c7860f42e                                                                                                                                                                     292MB
docker-dhcp-relay             master.0-dirty-20200120.152041   5e2c7860f42e                                                                                                                                                                     292MB
docker-database               latest                           704e8a8eba40                                                                                                                                                                     282MB
docker-database               master.0-dirty-20200120.152041   704e8a8eba40                                                                                                                                                                     282MB
docker-sflow                  latest                           9180801eb435                                                                                                                                                                     305MB
docker-sflow                  master.0-dirty-20200120.152041   9180801eb435                                                                                                                                                                     305MB
docker-snmp-sv2               latest                           aa5e6bc81ca5                                                                                                                                                                     339MB
docker-snmp-sv2               master.0-dirty-20200120.152041   aa5e6bc81ca5                                                                                                                                                                     339MB
docker-orchagent              latest                           c24704b948f1                                                                                                                                                                     323MB
docker-orchagent              master.0-dirty-20200120.152041   c24704b948f1                                                                                                                                                                     323MB
docker-teamd                  latest                           7a750c4a80e2                                                                                                                                                                     305MB
docker-teamd                  master.0-dirty-20200120.152041   7a750c4a80e2                                                                                                                                                                     305MB
docker-sonic-mgmt-framework   latest                           238b79d55fd3                                                                                                                                                                     419MB
docker-sonic-mgmt-framework   master.0-dirty-20200120.152041   238b79d55fd3                                                                                                                                                                     419MB
docker-sonic-telemetry        latest                           a5087227fb41                                                                                                                                                                     343MB
docker-sonic-telemetry        master.0-dirty-20200120.152041   a5087227fb41                                                                                                                                                                     343MB

**Comment by dlringor** [comment]
Its working!  Thanks

don@sonic:~$ show version

SONiC Software Version: SONiC.master.0-e75da77f
Distribution: Debian 10.3
Kernel: 4.19.0-6-amd64
Build commit: e75da77f
Build date: Mon Apr 27 01:53:42 UTC 2020
Built by: don@dell1

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
Serial Number: 971632D1946004
Uptime: 02:40:47 up 21 min,  1 user,  load average: 0.55, 0.48, 0.40

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-teamd                  latest              e41b7bc11281        308MB
docker-teamd                  master.0-e75da77f   e41b7bc11281        308MB
docker-syncd-brcm             latest              dcf8b62b12fe        436MB
docker-syncd-brcm             master.0-e75da77f   dcf8b62b12fe        436MB
docker-sonic-telemetry        latest              b14bada211a8        348MB
docker-sonic-telemetry        master.0-e75da77f   b14bada211a8        348MB
docker-sonic-mgmt-framework   latest              f0bd598b8a56        426MB
docker-sonic-mgmt-framework   master.0-e75da77f   f0bd598b8a56        426MB
docker-snmp-sv2               latest              978b79330238        345MB
docker-snmp-sv2               master.0-e75da77f   978b79330238        345MB
docker-sflow                  latest              e2ef3a11064e        309MB
docker-sflow                  master.0-e75da77f   e2ef3a11064e        309MB
docker-router-advertiser      latest              df110e72ede1        287MB
docker-router-advertiser      master.0-e75da77f   df110e72ede1        287MB
docker-platform-monitor       latest              bd440ef45103        351MB
docker-platform-monitor       master.0-e75da77f   bd440ef45103        351MB
docker-orchagent              latest              1006f05062f1        326MB
docker-orchagent              master.0-e75da77f   1006f05062f1        326MB
docker-nat                    latest              bff3ee87b1ad        309MB
docker-nat                    master.0-e75da77f   bff3ee87b1ad        309MB
docker-lldp-sv2               latest              af7a5c6e697b        305MB
docker-lldp-sv2               master.0-e75da77f   af7a5c6e697b        305MB
docker-iccpd                  latest              23db44ef199e        309MB
docker-iccpd                  master.0-e75da77f   23db44ef199e        309MB
docker-fpm-frr                latest              15cdb47606ed        328MB
docker-fpm-frr                master.0-e75da77f   15cdb47606ed        328MB
docker-dhcp-relay             latest              0013aa0c4dcf        297MB
docker-dhcp-relay             master.0-e75da77f   0013aa0c4dcf        297MB
docker-database               latest              5256c4a1578e        287MB
docker-database               master.0-e75da77f   5256c4a1578e        287MB
