### ISSUE TITLE
sonic-platform-modules-dell s6000 build failure does not cause job build failure

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#4095]
**Description**

**Steps to reproduce the issue:**
1. check the buid log
2.
3.

**Describe the results you received:**
s6000 build failure should cause the dpkg-buildpackage -uc -ub to fail. However such failure is ignored.

**Describe the results you expected:**
Please improve the build script not to ignore any error.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
[platform-modules-z9100_1.1_amd64.deb.log](https://github.com/Azure/sonic-buildimage/files/4145735/platform-modules-z9100_1.1_amd64.deb.log)

**Comment by xinliu-seattle** [comment]
@padmanarayana to make sure the fix is in.

**Comment by padmanarayana** [comment]
@santhosh-kt raised https://github.com/Azure/sonic-buildimage/pull/4108
