### ISSUE TITLE
SONiC.HEAD.187-dirty-20200130.072127

### ISSUE THREAD

**Issue by dlringor** [Azure/sonic-buildimage#4096]
I am installing sonic on AS9716-32d. Help please..

admin@sonic:~$ show version

SONiC Software Version: SONiC.HEAD.187-dirty-20200130.072127
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: 5383e2c7
Build date: Thu Jan 30 07:30:49 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
/usr/bin/decode-syseeprom : ERROR : [Errno 2] No such file or directory: '/sys/bus/i2c/devices/0-0056/eeprom'
Serial Number:
Uptime: 17:46:07 up 4 min,  1 user,  load average: 0.39, 0.50, 0.24

Docker images:
REPOSITORY                    TAG                              IMAGE ID            SIZE
docker-syncd-brcm             HEAD.187-dirty-20200130.072127   90849d2a9b6c        430MB
docker-syncd-brcm             latest                           90849d2a9b6c        430MB
docker-platform-monitor       HEAD.187-dirty-20200130.072127   4f8c213127c2        334MB
docker-platform-monitor       latest                           4f8c213127c2        334MB
docker-router-advertiser      HEAD.187-dirty-20200130.072127   d3c313a306c3        283MB
docker-router-advertiser      latest                           d3c313a306c3        283MB
docker-fpm-frr                HEAD.187-dirty-20200130.072127   8d917b98079e        327MB
docker-fpm-frr                latest                           8d917b98079e        327MB
docker-sflow                  HEAD.187-dirty-20200130.072127   d508e53a80dc        307MB
docker-sflow                  latest                           d508e53a80dc        307MB
docker-lldp-sv2               HEAD.187-dirty-20200130.072127   5983520b67c0        304MB
docker-lldp-sv2               latest                           5983520b67c0        304MB
docker-orchagent              HEAD.187-dirty-20200130.072127   915db75abef0        325MB
docker-orchagent              latest                           915db75abef0        325MB
docker-dhcp-relay             HEAD.187-dirty-20200130.072127   2fb63f5ba64e        293MB
docker-dhcp-relay             latest                           2fb63f5ba64e        293MB
docker-database               HEAD.187-dirty-20200130.072127   66b5797bdac4        283MB
docker-database               latest                           66b5797bdac4        283MB
docker-snmp-sv2               HEAD.187-dirty-20200130.072127   d1ed644608c2        340MB
docker-snmp-sv2               latest                           d1ed644608c2        340MB
docker-teamd                  HEAD.187-dirty-20200130.072127   57d965456cdf        307MB
docker-teamd                  latest                           57d965456cdf        307MB
docker-sonic-mgmt-framework   HEAD.187-dirty-20200130.072127   7c4298dfdf62        419MB
docker-sonic-mgmt-framework   latest                           7c4298dfdf62        419MB
docker-sonic-telemetry        HEAD.187-dirty-20200130.072127   823583cfe85f        344MB
docker-sonic-telemetry        latest                           823583cfe85f        344MB

**Comment by lguohan** [comment]
platform driver issue. @roylee123

**Comment by jostar-yang** [comment]
Dlringor,
Can you help check belwo cmd,
systemctl status as9716-32d-platform-monitor.service -l
decode-syseeprom

**Comment by jostar-yang** [comment]
Please merge code from #3985 to your local build. My code still not be merged on master.
Update Code is  
platform/broadcom/sonic-platform-modules-accton/as9716-32d/utils/accton_as9716_32d_util.py
device/accton/x86_64-accton_as9716_32d-r0/plugins/eeprom.py

**Comment by dlringor** [comment]
Hi Jostar-yang,

 

I will just be using the one built Jan20. Here is the output from the two commands:

 

admin@sonic:~$ sudo systemctl status as9716-32d-platform-monitor.service -l

● as9716-32d-platform-monitor.service - Accton AS9716-32D Platform Monitoring se

   Loaded: loaded (/lib/systemd/system/as9716-32d-platform-monitor.service; enab

   Active: active (running) since Fri 2016-12-16 12:18:16 UTC; 2min 32s ago

  Process: 792 ExecStartPre=/usr/local/bin/accton_as9716_32d_util.py install (co

Main PID: 1034 (python)

    Tasks: 1 (limit: 4915)

   Memory: 222.4M

      CPU: 2.620s

   CGroup: /system.slice/as9716-32d-platform-monitor.service

           └─1034 python /usr/local/bin/accton_as9716_32d_monitor.py

 

Dec 16 12:17:58 sonic systemd[1]: Starting Accton AS9716-32D Platform Monitoring

Dec 16 12:18:16 sonic accton_as9716_32d_util.py[792]: init i2c device instance

Dec 16 12:18:16 sonic systemd[1]: Started Accton AS9716-32D Platform Monitoring

admin@sonic:~$ decode-syseeprom

/usr/bin/decode-syseeprom : ERROR : must be root to run

admin@sonic:~$ sudo decode-syseeprom

TlvInfo Header:

   Id String:    TlvInfo

   Version:      1

   Total Length: 172

TLV Name             Code Len Value

-------------------- ---- --- -----

Manufacture Date     0x25  19 12/09/2019 14:17:04

Label Revision       0x27   4 R01A

Platform Name        0x28  27 x86_64-accton_as9716_32D-r0

ONIE Version         0x29  13 2019.08.00.03

Manufacturer         0x2B   6 Accton

Manufacture Country  0x2C   2 TW

Diag Version         0x2E  11 01.01.00.17

Base MAC Address     0x24   6 68:21:5F:27:23:C0

Serial Number        0x23  14 971632D1946004

Part Number          0x22  13 FP5ZZ8632006A

Product Name         0x21  15 9716-32D-O-AC-F

MAC Addresses        0x2A   2 256

Vendor Name          0x2D   8 Edgecore

CRC-32               0xFE   4 0x0C26CC5B

(checksum valid)

 

 

##For the bootlog:

 

Loading SONiC-OS OS kernel ...

Loading SONiC-OS OS initial ramdisk ...

[    8.995370] ata2.00: failed to set xfermode (err_mask=0x40)

[   10.073114] systemd[1]: [/etc/systemd/system/procdockerstatsd.service:9] Fail                              ed to parse service restart specifier, ignoring: Always

[   10.633552] rc.local[516]: + sonic-cfggen -y /etc/sonic/sonic_version.yml -v                               build_version

[   10.756169] kdump-tools[483]: Starting kdump-tools: no crashkernel= parameter                               in the kernel cmdline ... failed!

[   11.555134] rc.local[516]: + SONIC_VERSION=master.0-dirty-20200120.152041

[   11.572454] rc.local[516]: + FIRST_BOOT_FILE=/host/image-master.0-dirty-20200                              120.152041/platform/firsttime

[   11.592575] rc.local[516]: + logger SONiC version master.0-dirty-20200120.152                              041 starting up...

[   11.616446] rc.local[516]: + [ ! -e /host/machine.conf ]

[   11.632455] rc.local[516]: + . /host/machine.conf

[   11.652428] rc.local[516]: + onie_arch=x86_64

[   11.672426] rc.local[516]: + onie_bin=

[   11.684562] rc.local[516]: + onie_boot_reason=install

[   11.700422] rc.local[516]: + onie_build_date=2019-10-23T12:13+08:00

[   11.716577] rc.local[516]: + onie_build_machine=accton_as9716_32d

[   11.736424] rc.local[516]: + onie_build_platform=x86_64-accton_as9716_32d-r0

[   11.760461] rc.local[516]: + onie_cli_static_parms=

[   11.780523] rc.local[516]: + onie_cli_static_url=tftp://192.168.112.38/sonic-                              broadcom.bin

[   11.800414] rc.local[516]: + onie_config_version=1

[   11.816403] rc.local[516]: + onie_dev=/dev/sda2

[   11.836428] rc.local[516]: + onie_exec_url=tftp://192.168.112.38/sonic-broadc                              om.bin

[   11.856446] rc.local[516]: + onie_firmware=auto

[   11.872470] rc.local[516]: + onie_grub_image_name=grubx64.efi

[   11.888478] rc.local[516]: + onie_initrd_tmp=/

[   11.904406] rc.local[516]: + onie_installer=/var/tmp/installer

[   11.920521] rc.local[516]: + onie_kernel_version=4.9.95

[   11.936467] rc.local[516]: + onie_machine=accton_as9716_32d

[   11.952463] rc.local[516]: + onie_machine_rev=0

[   11.968479] rc.local[516]: + onie_partition_type=gpt

[   11.984482] rc.local[516]: + onie_platform=x86_64-accton_as9716_32d-r0

[   12.000413] rc.local[516]: + onie_root_dir=/mnt/onie-boot/onie

[   12.016423] rc.local[516]: + onie_skip_ethmgmt_macs=no

[   12.032426] rc.local[516]: + onie_switch_asic=bcm

[   12.048478] rc.local[516]: + onie_uefi_arch=x64

[   12.064974] rc.local[516]: + onie_uefi_boot_loader=grubx64.efi

[   12.080425] rc.local[516]: + onie_vendor_id=259

[   12.096402] rc.local[516]: + onie_version=2019.08.00.03

[   12.112489] rc.local[516]: + program_console_speed

[   12.129582] rc.local[516]: + cat /proc/cmdline

[   12.154071] rc.local[516]: + grep -Eo console=ttyS[0-9]+,[0-9]+

[   12.183613] rc.local[516]: + cut -d , -f2

[   12.206497] rc.local[516]: + speed=115200

[   12.220808] rc.local[516]: + [ -z 115200 ]

[   12.232746] rc.local[516]: + CONSOLE_SPEED=115200

[   12.248571] rc.local[516]: + sed -i s|\-\-keep\-baud .* %I| 115200 %I|g /lib/                              systemd/system/serial-getty@.service

[   12.268482] rc.local[516]: + systemctl daemon-reload

[   12.284485] rc.local[516]: + [ -f /host/image-master.0-dirty-20200120.152041/                              platform/firsttime ]

[   12.304428] rc.local[516]: + echo First boot detected. Performing first boot                               tasks...

[   12.324439] rc.local[516]: First boot detected. Performing first boot tasks..                              .

[   12.344476] rc.local[516]: + [ -n  ]

[   12.356396] rc.local[516]: + [ -n x86_64-accton_as9716_32d-r0 ]

[   12.372483] rc.local[516]: + platform=x86_64-accton_as9716_32d-r0

[   12.388513] rc.local[516]: + [ -d /host/old_config ]

[   12.404590] rc.local[516]: + [ -f /host/minigraph.xml ]

[   12.420676] rc.local[516]: + [ -n  ]

[   12.432657] rc.local[516]: + touch /tmp/pending_config_initialization

[   12.448985] rc.local[516]: + touch /tmp/notify_firstboot_to_platform

[   12.464874] rc.local[516]: + [ -d /host/image-master.0-dirty-20200120.152041/                              platform/x86_64-accton_as9716_32d-r0 ]

[   12.485020] rc.local[516]: + dpkg -i /host/image-master.0-dirty-20200120.1520                              41/platform/x86_64-accton_as9716_32d-r0/sonic-platform-accton-as9716-32d_1.1_amd                              64.deb

[   12.519493] rc.local[516]: Selecting previously unselected package sonic-plat                              form-accton-as9716-32d.

[   12.541105] rc.local[516]: (Reading database ... 26749 files and directories                               currently installed.)

[   12.560928] rc.local[516]: Preparing to unpack .../sonic-platform-accton-as97                              16-32d_1.1_amd64.deb ...

[   12.580900] rc.local[516]: Unpacking sonic-platform-accton-as9716-32d (1.1) .                              ..

[   12.600807] rc.local[516]: Setting up sonic-platform-accton-as9716-32d (1.1)                               ...

[   12.851692] rc.local[516]: Created symlink /etc/systemd/system/multi-user.tar                              get.wants/as9716-32d-platform-monitor-fan.service → /lib/systemd/system/as9716-3                              2d-platform-monitor-fan.service.

[   13.154008] rc.local[516]: Created symlink /etc/systemd/system/multi-user.tar                              get.wants/as9716-32d-platform-monitor-psu.service → /lib/systemd/system/as9716-3                              2d-platform-monitor-psu.service.

[   13.466811] rc.local[516]: Created symlink /etc/systemd/system/multi-user.tar                              get.wants/as9716-32d-platform-monitor.service → /lib/systemd/system/as9716-32d-p                              latform-monitor.service.

[  OK  ] Started Accton AS9716-32D Platform Monitoring service.

[   32.635282] rc.local[516]: + sync

[   32.668896] rc.local[516]: + [ -n x86_64-accton_as9716_32d-r0 ]

[  OK  ] Started /etc/rc.local Compatibility.

[   32.684851] rc.local[516]: + [ -n  ]

[  OK  ] Started Getty on tty1.

[   32.712368] rc.local[516]: + firsttime_exit

         Starting Database container...

[   32.736347] rc.local[516]: + rm -rf /host/image-master.0-dirty-20200120.15204                              1/platform/firsttime

[  OK  ] Started Serial Getty on ttyS0.

[   32.768367] rc.local[516]: + exit 0

[  OK  ] Reached target Login Prompts.

[  OK  ] Started Database container.

         Starting Monitor warm recovery and disable warmboot when done...

         Starting Config initialization and migration service...

 

Debian GNU/Linux 9 sonic ttyS0

 

sonic login: admin

Password:

Linux sonic 4.9.0-9-2-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2015-12-19) x86_64

 

 

Thank you for your help.

 

Don

**Comment by dlringor** [comment]
Hello,

The latest build is okay.  No dirty docker images.  Thank you!

don@sonic:~$ show version

SONiC Software Version: SONiC.master.0-e75da77f
Distribution: Debian 10.3
Kernel: 4.19.0-6-amd64
Build commit: e75da77f
Build date: Mon Apr 27 01:53:42 UTC 2020
Built by: don@dell1

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
Serial Number: 971632D1946004
Uptime: 02:40:47 up 21 min,  1 user,  load average: 0.55, 0.48, 0.40

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-teamd                  latest              e41b7bc11281        308MB
docker-teamd                  master.0-e75da77f   e41b7bc11281        308MB
docker-syncd-brcm             latest              dcf8b62b12fe        436MB
docker-syncd-brcm             master.0-e75da77f   dcf8b62b12fe        436MB
docker-sonic-telemetry        latest              b14bada211a8        348MB
docker-sonic-telemetry        master.0-e75da77f   b14bada211a8        348MB
docker-sonic-mgmt-framework   latest              f0bd598b8a56        426MB
docker-sonic-mgmt-framework   master.0-e75da77f   f0bd598b8a56        426MB
docker-snmp-sv2               latest              978b79330238        345MB
docker-snmp-sv2               master.0-e75da77f   978b79330238        345MB
docker-sflow                  latest              e2ef3a11064e        309MB
docker-sflow                  master.0-e75da77f   e2ef3a11064e        309MB
docker-router-advertiser      latest              df110e72ede1        287MB
docker-router-advertiser      master.0-e75da77f   df110e72ede1        287MB
docker-platform-monitor       latest              bd440ef45103        351MB
docker-platform-monitor       master.0-e75da77f   bd440ef45103        351MB
docker-orchagent              latest              1006f05062f1        326MB
docker-orchagent              master.0-e75da77f   1006f05062f1        326MB
docker-nat                    latest              bff3ee87b1ad        309MB
docker-nat                    master.0-e75da77f   bff3ee87b1ad        309MB
docker-lldp-sv2               latest              af7a5c6e697b        305MB
docker-lldp-sv2               master.0-e75da77f   af7a5c6e697b        305MB
docker-iccpd                  latest              23db44ef199e        309MB
docker-iccpd                  master.0-e75da77f   23db44ef199e        309MB
docker-fpm-frr                latest              15cdb47606ed        328MB
docker-fpm-frr                master.0-e75da77f   15cdb47606ed        328MB
docker-dhcp-relay             latest              0013aa0c4dcf        297MB
docker-dhcp-relay             master.0-e75da77f   0013aa0c4dcf        297MB
docker-database               latest              5256c4a1578e        287MB
docker-database               master.0-e75da77f   5256c4a1578e        287MB

don@AS9716-32D:~$ systemctl status as9716-32d-platform-monitor.service -l
● as9716-32d-platform-monitor.service - Accton AS9716-32D Platform Monitoring se
   Loaded: loaded (/lib/systemd/system/as9716-32d-platform-monitor.service; enab
   Active: active (running) since Sun 2019-07-21 02:19:46 UTC; 7h ago
  Process: 521 ExecStartPre=/usr/local/bin/accton_as9716_32d_util.py install (co
 Main PID: 2971 (python)
    Tasks: 1 (limit: 4915)
   Memory: 292.0M
   CGroup: /system.slice/as9716-32d-platform-monitor.service
           └─2971 python /usr/local/bin/accton_as9716_32d_monitor.py
