### ISSUE TITLE
Service reload failure due to multiple "--net" args in 'docker create'

### ISSUE THREAD

**Issue by mykolaf** [Azure/sonic-buildimage#4118]
**Description**
A few recent changes introduced an issue with restarting services like nat and mgmt-framework.

The reason is [diff](https://github.com/Azure/sonic-buildimage/commit/abe7ef7e2e2e1215c97cee19a83aab0b130cebe5#diff-c8afa64378a9e3327b28e115326db5f2R291) decided to specify `--net` separately, while few services still have [this](https://github.com/Azure/sonic-buildimage/blob/master/rules/docker-nat.mk#L25)

This causes `config reload` failure.

**Steps to reproduce the issue:**
1. Run image with [3856](https://github.com/Azure/sonic-buildimage/pull/3856)
2. Do config reload 
3. Observe `Job for nat.service failed because the control process exited with error code`

**Describe the results you received:**

Service restart failure
Log:
```
Feb  6 14:21:31.314088 mtbc-sonic-01-2410 INFO nat.sh[27859]: Creating new nat container with HWSKU ACS-MSN2410
Feb  6 14:21:31.483881 mtbc-sonic-01-2410 INFO nat.sh[27859]: docker: network "host" is specified multiple times.
```

**Describe the results you expected:**

Everything running *smooth*

**Additional information you deem important (e.g. issue happens only occasionally):**

Originally observed on 201911 release, should also be in master.
    **Output of `show version`:**

    ```
SONiC Software Version: SONiC.HEAD.28-d192e0c9
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: d192e0c9
Build date: Wed Feb  5 04:39:37 UTC 2020
Built by: johnar@jenkins-worker-8

    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by mykolaf** [comment]
@lguohan This one blocks our regression testing. Could you please take a look at fix I provided? #4119 
The fix is needed in 201911 as well.

**Comment by abdosi** [comment]
@mykolaf Changes are fine in PR.

**Comment by flyover-26** [comment]
Has this problem solved?
I got the same problem.
docker:network "host" is specified multiple times
