### ISSUE TITLE
snmp-subagent MIBUpdater exception loc_chassis_data not subscriptable

### ISSUE THREAD

**Issue by wangxin** [Azure/sonic-buildimage#4230]
**Description**

During testing, this kind of error messages were observed in syslog:

```
Mar  5 00:02:55.555765 r-tigris-13 ERR snmp#snmp-subagent message repeated 14 times: [ [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 115, in reinit_data#012    self.loc_chassis_data[b\'lldp_loc_sys_cap_supported\'] = parse_sys_capability(self.loc_chassis_data[b\'lldp_loc_sys_cap_supported\'])#012TypeError: \'NoneType\' object is not subscriptable]\n

Mar  5 00:02:56.427089 r-tigris-13 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 115, in reinit_data#012    self.loc_chassis_data[b\'lldp_loc_sys_cap_supported\'] = parse_sys_capability(self.loc_chassis_data[b\'lldp_loc_sys_cap_supported\'])#012TypeError: \'NoneType\' object is not subscriptable\n
```

**Steps to reproduce the issue:**
1. SONiC switch is running t1-lag topology
2. Check /var/log/syslog
3.

**Describe the results you received:**
Error message `ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception` in syslog.

**Describe the results you expected:**
No such error message in syslog.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
INFO:common.plugins.sanity_check.checks:cmd='show version', output: 

[ 
    "", 
    "SONiC Software Version: SONiC.HEAD.41-69879e4e", 
    "Distribution: Debian 9.12", 
    "Kernel: 4.9.0-9-2-amd64", 
    "Build commit: 69879e4e", 
    "Build date: Tue Feb 25 03:44:22 UTC 2020", 
    "Built by: johnar@jenkins-worker-8", 
    "", 
    "Platform: x86_64-mlnx_msn3800-r0", 
    "HwSKU: ACS-MSN3800", 
    "ASIC: mellanox", 
    "Serial Number: MT1937X00527\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000", 
    "Uptime: 23:50:09 up 15 min,  0 users,  load average: 3.94, 3.73, 2.59", 
    "", 
    "Docker images:", 
    "REPOSITORY                    TAG                 IMAGE ID            SIZE", 
    "docker-syncd-mlnx             HEAD.41-69879e4e    710129be7282        386MB", 
    "docker-syncd-mlnx             latest              710129be7282        386MB", 
    "docker-router-advertiser      HEAD.41-69879e4e    346c753f1a76        287MB", 
    "docker-router-advertiser      latest              346c753f1a76        287MB", 
    "docker-sonic-mgmt-framework   HEAD.41-69879e4e    b5e6121ba1c9        424MB", 
    "docker-sonic-mgmt-framework   latest              b5e6121ba1c9        424MB", 
    "docker-platform-monitor       HEAD.41-69879e4e    81e936164571        629MB", 
    "docker-platform-monitor       latest              81e936164571        629MB", 
    "docker-fpm-frr                HEAD.41-69879e4e    28b3e009ef55        332MB", 
    "docker-fpm-frr                latest              28b3e009ef55        332MB", 
    "docker-sflow                  HEAD.41-69879e4e    4d9fa4eb4860        312MB", 
    "docker-sflow                  latest              4d9fa4eb4860        312MB", 
    "docker-lldp-sv2               HEAD.41-69879e4e    5328e9f7b7e8        309MB", 
    "docker-lldp-sv2               latest              5328e9f7b7e8        309MB", 
    "docker-dhcp-relay             HEAD.41-69879e4e    3e977a20dc55        297MB", 
    "docker-dhcp-relay             latest              3e977a20dc55        297MB", 
    "docker-database               HEAD.41-69879e4e    c0e1d6128f2c        287MB", 
    "docker-database               latest              c0e1d6128f2c        287MB", 
    "docker-teamd                  HEAD.41-69879e4e    f64e1bf4c54e        312MB", 
    "docker-teamd                  latest              f64e1bf4c54e        312MB", 
    "docker-snmp-sv2               HEAD.41-69879e4e    0ac8e5bcb511        344MB", 
    "docker-snmp-sv2               latest              0ac8e5bcb511        344MB", 
    "docker-orchagent              HEAD.41-69879e4e    a0c6d228bfb3        330MB", 
    "docker-orchagent              latest              a0c6d228bfb3        330MB", 
    "docker-nat                    HEAD.41-69879e4e    a9c3c1ecfeb3        313MB", 
    "docker-nat                    latest              a9c3c1ecfeb3        313MB", 
    "docker-sonic-telemetry        HEAD.41-69879e4e    514146abf30c        349MB", 
    "docker-sonic-telemetry        latest              514146abf30c        349MB" 
] 
```

    **Attach debug file `sudo generate_dump`:**

**Comment by chenkelly** [comment]
Hi @wangxin, do you see lldp-syncd process start successfully?
I encountered a similar problem, lldp-syncd process is not running sometimes.

**Comment by xinliu-seattle** [comment]
@wangxin, which branch is this issue reported on?

**Comment by xinliu-seattle** [comment]
The dump file is not there, please re-attach it.

**Comment by wangxin** [comment]
@xinliu-seattle It was on 201911 branch. I'll see if I can reproduce it using the same image and get a dump.
@chenkelly I am not sure what the status of lld-syncd process was. I'll try to reproduce it and report back.

**Comment by chenkelly** [comment]
We once got the following message during testing lldp case on t1-lag topology, but cannot reproduce it now.
After checking syslog message on DUT, find that 'lldp_syncd' process is not running during lldp test. 
The lldp_sync don't be spawned successfully.
> 
         "________________________ ERROR at teardown of test_lldp ________________________", 
        "", 
        "duthost = <common.devices.SonicHost object at 0x7f37061c3190>", 
        "request = <SubRequest 'loganalyzer' for <Function test_lldp>>", 
        "", 
        "    @pytest.fixture(autouse=True)", 
        "    def loganalyzer(duthost, request):", 
        "        loganalyzer = LogAnalyzer(ansible_host=duthost, marker_prefix=request.node.name)", 
        "        # Add start marker into DUT syslog", 
        "        marker = loganalyzer.init()", 
        "        yield loganalyzer", 
        "        if not request.config.getoption(\"--disable_loganalyzer\") and \"disable_loganalyzer\" not in request.keywords:", 
        "            # Read existed common regular expressions located with legacy loganalyzer module", 
        "            loganalyzer.load_common_config()", 
        "            # Parse syslog and process result. Raise \"LogAnalyzerError\" exception if: total match or expected missing", 
        "            # match is not equal to zero", 
        ">           loganalyzer.analyze(marker)", 
        "", 
        "conftest.py:151: ", 
        "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ", 
        "loganalyzer/loganalyzer.py:222: in analyze", 
        "    self._verify_log(analyzer_summary)", 
        "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ", 
        "", 
        "self = <loganalyzer.loganalyzer.LogAnalyzer instance at 0x7f37064757a0>", 
        "result = {'expect_messages': {'/tmp/pytest-run/syslog.2020-03-23-01:19:20': []}, 'match_files': {'/tmp/pytest-run/syslog.2020-0...eType' object is not subscriptable]\\n\"]}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 1}, ...}", 
        "", 
        "    def _verify_log(self, result):", 
        "        \"\"\"", 
        "        Verify that total match and expected missing match equals to zero or raise exception otherwise.", 
        "        Verify that expected_match is not equal to zero when there is configured expected regexp in self.expect_regex list", 
        "        \"\"\"", 
        "        if not result:", 
        "            raise LogAnalyzerError(\"Log analyzer failed - no result.\")", 
        "        if result[\"total\"][\"match\"] != 0 or result[\"total\"][\"expected_missing_match\"] != 0:", 
        ">           raise LogAnalyzerError(result)", 
        "E           LogAnalyzerError: {'match_messages': {'/tmp/pytest-run/syslog.2020-03-23-01:19:20': ['Mar 23 01:19:23.671746 as7816-64x ERR snmp#snmp-subagent message repeated 15 times: [ [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File \"/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py\", line 40, in start#012    self.reinit_data()#012  File \"/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py\", line 115, in reinit_data#012    self.loc_chassis_data[b\\'lldp_loc_sys_cap_supported\\'] = parse_sys_capability(self.loc_chassis_data[b\\'lldp_loc_sys_cap_supported\\'])#012TypeError: \\'NoneType\\' object is not subscriptable]\\n']}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 1}, 'match_files': {'/tmp/pytest-run/syslog.2020-03-23-01:19:20': {'expected_match': 0, 'match': 1}}, 'expect_messages': {'/tmp/pytest-run/syslog.2020-03-23-01:19:20': []}, 'unused_expected_regexp': []}", 
        "", 
        "loganalyzer/loganalyzer.py:72: LogAnalyzerError",

**Comment by chitra-raghavan** [comment]
The same error message is seen  while running snmp tests in 201911 branch in PTF topology.

`Apr 17 14:03:09.344505 sonic-s5232-01 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File \\"/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py\\", line 40, in start#012    self.reinit_data()#012  File \\"/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py\\", line 115, in reinit_data#012    self.loc_chassis_data[b\'lldp_loc_sys_cap_supported\'] = parse_sys_capability(self.loc_chassis_data[b\'lldp_loc_sys_cap_supported\'])#012TypeError: \'NoneType\' object is not subscriptable\\nApr 17 `

**Comment by wangxin** [comment]
Tested using the same image again, observed these error in syslog:
```
Apr 24 10:09:37.321515 sonic-13 ERR snmp#snmp-subagent [sonic_ax_impl] ERROR: Uncaught exception in sonic_ax_impl.main#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/main.py", line 70, in main#012    event_loop.run_until_complete(agent.run_in_event_loop())#012  File "/usr/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete#012    return future.result()#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/agent.py", line 49, in run_in_event_loop#012    await asyncio.wait_for(background_task, BACKGROUND_WAIT_TIMEOUT, loop=self.loop)#012  File "/usr/lib/python3.6/asyncio/tasks.py", line 352, in wait_for#012    return fut.result()#012AttributeError: '_asyncio.Task' object has no attribute 'send'

Apr 24 10:10:59.549403 sonic-13 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 115, in reinit_data#012    self.loc_chassis_data[b'lldp_loc_sys_cap_supported'] = parse_sys_capability(self.loc_chassis_data[b'lldp_loc_sys_cap_supported'])#012TypeError: 'NoneType' object is not subscriptable

Apr 24 10:11:59.566617 sonic-13 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 169, in reinit_data#012    self.oid_name_map = mibs.init_sync_d_interface_tables(self.db_conn)#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/__init__.py", line 197, in init_sync_d_interface_tables#012    if_name_map, if_id_map = port_util.get_interface_oid_map(db_conn)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/port_util.py", line 51, in get_interface_oid_map#012    if_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_PORT_NAME_MAP', blocking=True)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/dbconnector.py", line 176, in get_all#012    return super(SonicV2Connector, self).get_all(db_id, _hash, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped#012    ret_data = f(inst, db_id, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 303, in get_all#012    raise UnavailableDataError(message, _hash)#012swsssdk.exceptions.UnavailableDataError: Key 'COUNTERS_PORT_NAME_MAP' unavailable in database '2'
```

Checked lldp-syncd status, it is running.

```
admin@sonic-13:/var/log$ docker exec -it lldp bash
root@sonic-13:/# supervisorctl status
lldp-syncd                       RUNNING   pid 73, uptime 0:06:23
lldpd                            RUNNING   pid 67, uptime 0:06:25
lldpmgrd                         RUNNING   pid 79, uptime 0:06:22
rsyslogd                         RUNNING   pid 62, uptime 0:06:26
start.sh                         EXITED    Apr 24 10:11 AM
supervisor-proc-exit-listener    RUNNING   pid 48, uptime 0:06:27
```

Attached a dump here.
[sonic_dump_r-tigris-13_20200424_101940.tar.gz](https://github.com/Azure/sonic-buildimage/files/4528258/sonic_dump_r-tigris-13_20200424_101940.tar.gz)

**Comment by wangxin** [comment]
PR https://github.com/Azure/sonic-mgmt/pull/2100 added this error message to ignore list. Closing the issue.
