### ISSUE TITLE
BGP neighbor configurations are not pushed to frr when DEVICE_NEIGHBOR_METADATA is not present

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#4231]
**Description**
When config_db.json does not have DEVICE_NEIGHBOR_METADATA, the BGP neighbor configurations present in config_db.json are not pushed to FRR.

The dependency on device_neighbor_metadata was introduced in this pull request
https://github.com/Azure/sonic-buildimage/pull/3694/files
**Steps to reproduce the issue:**
1. Add BGP neighbor entries in config_db.json
2. Do not add DEVICE_NEIGHBOR_METADATA 
3. Set docker_routing_config_mode as 'unified' or 'separated'

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by xinliu-seattle** [comment]
Pavel, please confirm if this applies to 201911 or not.

**Comment by pavel-shirshov** [comment]
Should be fixed by https://github.com/Azure/sonic-buildimage/pull/4143
