### ISSUE TITLE
Stop jobs take extremely long on shutdown/reboot

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#425]
Upon reboot (shutdown) a few stop jobs take a very long time to complete. The following are known culprits:

- Switch state service
- Docker Application Container Engine

**Comment by pavel-shirshov** [comment]
What about database?
From my experience database takes the longest time to stop

**Comment by jleveque** [comment]
@pavel-shirshov: The bug I'm referring to causes the services I mentioned to take 30~60 seconds to stop. Database is only taking a few seconds, which now seems "short" compared to these two.

**Comment by jleveque** [comment]
This appears to be fixed with PR #434.

Also, @pavel-shirshov: docker-database should shut down quickly now also, once PR #442 is merged.
