### ISSUE TITLE
[nat]: Unable to retrieve features for container 'nat'

### ISSUE THREAD

**Issue by nazariig** [Azure/sonic-buildimage#4276]
**Description**

NAT service pollutes syslog with the following error messages:
```
ERR nat#supervisor-proc-exit-listener: Unable to retrieve features for container 'nat'. Exiting...
```

**Steps to reproduce the issue:**
1. Install SONiC-OS-HEAD.49-055d7cd1 [201911]
2. Deploy t1-lag topo

**Describe the results you received:**
NAT service pollutes syslog with the error messages and makes a lot of tests fail

**Describe the results you expected:**
no error message are expected while operating in idle mode

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stepanblyschak** [comment]
Closing as duplicate - https://github.com/Azure/sonic-buildimage/issues/4247
Fix in - https://github.com/Azure/sonic-buildimage/pull/4250
