### ISSUE TITLE
rpc image - No module named ptf

### ISSUE THREAD

**Issue by mykolaf** [Azure/sonic-buildimage#4277]
**Description**

Faced issue while running CoPP test:

```
root@sonic:/# /usr/bin/python /opt/ptf_nn_agent.py --device-socket 1@tcp://0.0.0.0:10900 -i 1-3@Ethernet12 --set-nn-rcv-buffer=109430400 --set-iface-rcv-buffer=109430400 --set-nn-snd-buffer=109430400 --set-iface-snd-buffer=109430400
Traceback (most recent call last):
  File "/opt/ptf_nn_agent.py", line 38, in <module>
    from ptf import afpacket
ImportError: No module named ptf
```

Looks like ptf_nn_agent.py has new dependency. Due to it being downloaded by [wget](https://github.com/Azure/sonic-buildimage/blob/master/platform/mellanox/docker-syncd-mlnx-rpc/Dockerfile.j2#L53) we uncontrollably received an updated version.

**Steps to reproduce the issue:**
1. run CoPP test
2.
3.

**Describe the results you received:**

Traceback from nn agent.
**Describe the results you expected:**

Functioning ptf_nn_agent
**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
SONiC Software Version: SONiC.HEAD.31-505d4bfb
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 505d4bfb
Build date: Mon Mar 16 04:52:34 UTC 2020
Built by: johnar@jenkins-worker-8
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by nazariig** [comment]
Closed by https://github.com/Azure/sonic-buildimage/pull/4279
