### ISSUE TITLE
Jenkins builds failing due to lack of free space

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#428]
https://sonic-jenkins.westus.cloudapp.azure.com/job/common/job/buildimage-baseimage-pr/413/:
```
make[4]: Entering directory '/sonic/src/sonic-linux-kernel/linux-3.16.36'
dh_installdocs 
dh_installchangelogs
dh_strip
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol -- -Vkernel:Recommends=irqbalance,
dh_md5sums
dh_builddeb -- -Zxz 
dpkg-deb: building package `linux-image-3.16.0-4-amd64' in `../linux-image-3.16.0-4-amd64_3.16.36-1+deb8u2_amd64.deb'.
make[4]: Leaving directory '/sonic/src/sonic-linux-kernel/linux-3.16.36'
dpkg-deb (subprocess): compressing data member: lzma write error: No space left on device
dpkg-deb: error: subprocess <compress> from tar -cf returned error exit status 2
dh_builddeb: dpkg-deb -Zxz --build debian/linux-image-3.16.0-4-amd64-dbg .. returned exit code 2
debian/rules.real:173: recipe for target 'install-base' failed
```

https://sonic-jenkins.westus.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all-pr/83/:
```
running build
running build_ext
error: [Errno 28] No space left on device: 'build/temp.linux-x86_64-3.6-pydebug'
Makefile:627: recipe for target 'sharedmods' failed
make[3]: *** [sharedmods] Error 1
```

https://sonic-jenkins.westus.cloudapp.azure.com/job/cavium/job/buildimage-cavm-all-pr/410/:
```
/tmp/ccJe73Wu.s: Assembler messages:
/tmp/ccJe73Wu.s: Fatal error: can't write tests-converter_ut.o: No space left on device
```

**Comment by stcheng** [comment]
https://sonic-jenkins.westus.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/130/console
```
dpkg-deb: building package `swss' in `../swss_1.0.0_amd64.deb'.
dpkg-deb (subprocess): compressing control member: internal gzip write error: No space left on device
dpkg-deb: error: subprocess gzip -9c returned error exit status 2
dh_builddeb: dpkg-deb --build debian/swss .. returned exit code 2
dpkg-deb: building package `swss-dbg' in `../swss-dbg_1.0.0_amd64.deb'.
dpkg-deb (subprocess): compressing control member: internal gzip write error: No space left on device
dpkg-deb: error: subprocess gzip -9c returned error exit status 2
dh_builddeb: dpkg-deb --build debian/swss-dbg .. returned exit code 2
debian/rules:22: recipe for target 'binary' failed
```

**Comment by lguohan** [comment]
allocated new 1T disk for jenkins build.

**Comment by stcheng** [comment]
`fatal error: error writing to /tmp/ccCK5Whn.s: No space left on device`

**Comment by lguohan** [comment]
sonic-slave consume the disk, manually cleaned them up. Should be good for a while. Will figure out way to automatically clean up the obseleted sonic-slave

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-buildimage/pull/560

**Comment by jleveque** [comment]
Also: https://sonic-jenkins.westus.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/764/

**Comment by stcheng** [comment]
Also: https://sonic-jenkins.westus.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/771/consoleFull

**Comment by jleveque** [comment]
Looks like it's happening once again: https://sonic-jenkins.westus.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all-pr/752/console

**Comment by stcheng** [comment]
🚑

**Comment by lguohan** [comment]
on worker-1 we have 221G flash for the docker 

/dev/sdb1       221G  126G   84G  61% /mnt

it looks like when there are 10 concurrent jobs running at the same time, the /mnt partition will become full.

I clean up the /mnt partition about 40G garbage data. If this disk partition happens again, I will increase the /mnt partition to 512G.

**Comment by jleveque** [comment]
Closing as we haven't experienced this for a while now.
