### ISSUE TITLE
Debian default reboot routine is executed when user typing "reboot" on buster

### ISSUE THREAD

**Issue by stephenxs** [Azure/sonic-buildimage#4305]
**Description**
Debian default reboot routine is executed when user typing "reboot".
This is because the `/usr/sbin` where the debian default reboot routine sits is in front of `/usr/bin` where the SONiC reboot routine sits in the PATH env. variable, causing Debian's one called when user typing `reboot`.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
is this for buster only?

**Comment by stephenxs** [comment]
> is this for buster only?

Yes. It's only observed on buster.
On buster and stretch the PATH is the same:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
However, on buster the Debian default reboot routine is in `/usr/sbin` while on stretch it's in `/sbin/reboot`, which causes the issue reproducible on buster only.
Another phenomenon, which I don't know whether it's related is that on buster the dirs including `/lib`, `/lib32`, `/lib64`, `/bin` and `/sbin` are all symbol links to their counterpart in `/usr`.
```
lrwxrwxrwx   1 root root    7 Mar 19 15:24 bin -> usr/bin
lrwxrwxrwx   1 root root    7 Mar 19 15:24 lib -> usr/lib
lrwxrwxrwx   1 root root    9 Mar 19 15:24 lib32 -> usr/lib32
lrwxrwxrwx   1 root root    9 Mar 19 15:24 lib64 -> usr/lib64
lrwxrwxrwx   1 root root   10 Mar 19 15:24 libx32 -> usr/libx32
lrwxrwxrwx   1 root root    8 Mar 19 15:24 sbin -> usr/sbin
```

**Comment by stephenxs** [comment]
This issue isn't observed anymore.
