### ISSUE TITLE
[dockers]: "docker stop" command fails on dockers with shell entrypoints

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#435]
`docker stop` sends a signal to the process with PID of 1 inside the docker. However, if the docker has an entrypoint of `/bin/bash` running one or more commands, `/bin/bash` becomes PID 1 and the signal will be received by `/bin/bash` but it will not be forwarded along to processes running *in* the shell. This causes docker stop to timeout instead of shutting the docker down properly.

**Comment by jleveque** [comment]
Fix for docker-database here: https://github.com/Azure/sonic-buildimage/pull/442

For many of the remaining dockers, a problem rears its head: multiple processes need to be started. While we can start multiple processes in a docker using supervisord, some dockers require processes to start in a specific order, however, supervisord, while providing a priority mechanism does not provide an dependency system, so there is no native way to start processes serially. Many people are clamoring for this functionality to be added here: https://github.com/Supervisor/supervisor/issues/122.

In the comments of the issue I linked, one person describes their workaround:

> A workaround that I have used is to set autostart=false on the processes, then create a bootstrap script with autostart=true and  autorestart=false (a one-shot). The bootstrap can be a shell script that calls supervisorctl start for each process. supervisorctl start will block until a process has started successfully.

While this will work, I don't believe this is an ideal solution. Also, it appears someone has created an alternative "ordered-startup-supervisord" here: https://pypi.python.org/pypi/ordered-startup-supervisord/. I'm not sure how stable this is, however. All thoughts are welcome!

**Comment by lguohan** [comment]
do you have a list of dockers that is not currently managed by supervisor?

**Comment by jleveque** [comment]
- docker-basic_router
- docker-dhcp-relay
- docker-fpm
- docker-fpm-gobgp (Uses supervisord, but it is not started as PID 1)
- docker-lldp-sv2 (Uses supervisord, but it is not started as PID 1)
- docker-mlnx-sswsyncd
- docker-mlnx-sswsyncd-rpc
- docker-orchagent
- docker-orchagent-cavm
- docker-orchagent-centec
- docker-orchagent-mlnx
- docker-platform-monitor
- docker-saiserver-brcm
- docker-saiserver-cavm
- docker-saiserver-mlnx
- docker-snmp-sv2 (Uses supervisord, but it is not started as PID 1)
- docker-sswsyncd
- docker-teamd
- docker-vas

**Comment by jleveque** [comment]
Resolved with PR https://github.com/Azure/sonic-buildimage/pull/573
