### ISSUE TITLE
Remove docker-basic_router?

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#436]
Is docker-basic_router deprecated? Should/can it be removed from the project?

**Comment by stcheng** [comment]
This docker is definitely out of date. Still, it might be useful later if we want to run the [SAI PTF tests](https://github.com/opencomputeproject/SAI/tree/master/test/basic_router). We might be able to pick it up later.

**Comment by lguohan** [comment]
basic_router is for 0.9.4, i think it is still useful

**Comment by jleveque** [comment]
OK. We'll leave this alone for now. Thanks.
