### ISSUE TITLE
Remove docker-bgp?

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#438]
Is docker-bgp deprecated? Should/can it be removed from the project?

**Comment by marian-pritsak** [comment]
Its installed into one image by default

**Comment by stcheng** [comment]
@marian-pritsak i think we are installing the docker-fpm

**Comment by stcheng** [comment]
I agree that we just remove this. The docker-bgp was once used in SONiCv1.

**Comment by jleveque** [comment]
PR @ https://github.com/Azure/sonic-buildimage/pull/465
