### ISSUE TITLE
Migrate Dell platform specific settings from SAI library to post init script framework

### ISSUE THREAD

**Issue by aravindmani-1** [Azure/sonic-buildimage#4389]
**Objective:**

- To make use of post init script framework and keep the SAI library cleaner (without Dell platform setting).
- It is required to move the Dell platform related settings(e.g. pre-emphasis, de-emphasis settings ) inside platform specific directory.
- Removing Dell platform settings would give control to Dell to make any further changes in future without depending on SAI team to make it so.
- It needs to be done in coordinated fashion for the merge to avoid any double playing of same configuration.

**Comment by xinliu-seattle** [comment]
This is for coordinating the change on SAI from BRCM. Enhancement not an issue.

**Comment by jeff-yin** [comment]
Ben is working on getting someone from Broadcom involved to look at this.

**Comment by dpbouchard** [comment]
Fix is ready for testing in coordination with Dell as of 16 July 2020.
