### ISSUE TITLE
 [201911] Hash test fails for ingress-port in T1 Topology

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-buildimage#4470]
**Description**

Hash tests fails for ingress port for Broadcom platforms (S6100,S5232) in 201911 branch for T1lag topology
script : https://github.com/Azure/sonic-mgmt/blob/master/tests/fib/test_fib.py#L141

Attached ptf log for the test. 
[hash.log.txt](https://github.com/Azure/sonic-buildimage/files/4521987/hash.log.txt)

	root@sonic-s5232-01:~# show ip route 9.0.0.0
	Routing entry for 0.0.0.0/0
	  Known via "bgp", distance 20, metric 0, best
	  Last update 00:29:54 ago
	  * 10.0.0.1, via Ethernet0
	  * 10.0.0.3, via Ethernet4
	  * 10.0.0.5, via Ethernet8
	  * 10.0.0.7, via Ethernet12
	  * 10.0.0.9, via Ethernet16
	  * 10.0.0.11, via Ethernet20
	  * 10.0.0.13, via Ethernet24
	  * 10.0.0.15, via Ethernet28
	  * 10.0.0.17, via Ethernet32
	  * 10.0.0.19, via Ethernet36
	  * 10.0.0.21, via Ethernet40
	  * 10.0.0.23, via Ethernet44
	  * 10.0.0.25, via Ethernet48
	  * 10.0.0.27, via Ethernet52
	  * 10.0.0.29, via Ethernet56
	  * 10.0.0.31, via Ethernet60

Show counters 

TRaffic is  Transmitted out only through one port Ethernet20

	root@sonic-s5232-01:~# show interface counters
	Last cached time was 2020-04-18 18:32:43.197284
		  IFACE    STATE    RX_OK       RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK      TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
	-----------  -------  -------  -----------  ---------  --------  --------  --------  -------  ----------  ---------  --------  --------  --------
	  Ethernet0        U       47    71.72 B/s      0.00%         0        45         0       92  127.13 B/s      0.00%         0         0         0
	  Ethernet4        U       91   125.65 B/s      0.00%         0        88         0       91  128.25 B/s      0.00%         0         0         0
	  Ethernet8        U       90   123.02 B/s      0.00%         0        88         0       47   75.62 B/s      0.00%         0         0         0
	Ethernet12        U       92   125.98 B/s      0.00%         0        90         0       93  130.64 B/s      0.00%         0         0         0
	Ethernet16        U       91   125.65 B/s      0.00%         0        88         0       91  128.25 B/s      0.00%         0         0         0

	Ethernet20        U      101   138.83 B/s      0.00%         0        99         0   32,115  48.75 KB/s      0.00%         0         0         0
	Ethernet24        U       91   125.65 B/s      0.00%         0        88         0       91  128.25 B/s      0.00%         0         0         0
	Ethernet28        U       90   123.02 B/s      0.00%         0        88         0       91  128.25 B/s      0.00%         0         0         0
	Ethernet32        U       93   127.32 B/s      0.00%         0        91         0       94  132.27 B/s      0.00%         0         0         0
	Ethernet36        U       92   125.98 B/s      0.00%         0        90         0       93  130.68 B/s      0.00%         0         0         0
	Ethernet40        U       93   127.02 B/s      0.00%         0        91         0       94  132.02 B/s      0.00%         0         0         0
	Ethernet44        U       47    71.49 B/s      0.00%         0        44         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet48        U       47    71.49 B/s      0.00%         0        44         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet52        U       90   123.02 B/s      0.00%         0        88         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet56        U       46    70.39 B/s      0.00%         0        44         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet60        U       90   123.02 B/s      0.00%         0        88         0       91  128.29 B/s      0.00%         0         0         0

Traffic from Incoming  T0 ports :

	Ethernet64        U    2,090  3232.78 B/s      0.00%         0        88         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet68        U    2,091  3235.41 B/s      0.00%         0        88         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet72        U    2,090  3232.78 B/s      0.00%         0        88         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet76        U    2,090  3232.78 B/s      0.00%         0        88         0       91  128.29 B/s      0.00%         0         0         0
	Ethernet80        U    2,094  3238.13 B/s      0.00%         0        92         0       74  111.67 B/s      0.00%         0         0         0
	Ethernet84        U    2,092  3235.74 B/s      0.00%         0        90         0       93  130.68 B/s      0.00%         0         0         0
	Ethernet88        U    2,090  3232.78 B/s      0.00%         0        88         0       69   98.69 B/s      0.00%         0         0         0
	Ethernet92        U    2,095  3240.76 B/s      0.00%         0        92         0       71  106.06 B/s      0.00%         0         0         0
	Ethernet96        U    2,094  3238.13 B/s      0.00%         0        92         0       94  130.13 B/s      0.00%         0         0         0
	Ethernet100        U    2,094  3238.13 B/s      0.00%         0        92         0       94  130.13 B/s      0.00%         0         0         0
	Ethernet104        U    2,048  3183.11 B/s      0.00%         0        46         0       94  130.13 B/s      0.00%         0         0         0
	Ethernet108        U    2,094  3238.13 B/s      0.00%         0        92         0       87  120.71 B/s      0.00%         0         0         0
	Ethernet112        U    2,094  3238.13 B/s      0.00%         0        92         0       48   75.11 B/s      0.00%         0         0         0
	Ethernet116        U    2,094  3238.13 B/s      0.00%         0        92         0       94  130.13 B/s      0.00%         0         0         0
	Ethernet120        U    2,094  3238.13 B/s      0.00%         0        92         0       94  130.13 B/s      0.00%         0         0         0
	Ethernet124        U    2,094  3238.13 B/s      0.00%         0        92         0       94  130.13 B/s      0.00%         0         0         0
	Ethernet128        X        0     0.00 B/s      0.00%         0         0         0        0    0.00 B/s      0.00%         0         0         0
	Ethernet129        X        0     0.00 B/s      0.00%         0         0         0        0    0.00 B/s      0.00%         0         0        

**Steps to reproduce the issue:**
1. run the hash test 
2. Test fails for hash_key ingress_port. 
3. test passes for  other hash_keys src-ip,dst-ip,src-port,dst-por

**Describe the results you received:**

	root@bd43a656290d:~# ptf --test-dir ptftests hash_test.HashTest --platform-dir ptftests --platform remote -t "testbed_type='t1-lag';router_mac=u'3c:2c:30:6d:7e:80';dst_ip_range='9.0.0.0,9.255.255.255';in_ports=[27, 22, 29, 25, 20, 28, 26, 21, 24, 31, 23, 30, 19, 16, 18, 17, 4, 5, 8, 9, 10, 11, 2, 3, 0, 1, 14, 15, 12, 13, 6, 7];src_ip_range='8.0.0.0,8.255.255.255';fib_info='/root/fib_info.txt';hash_keys=['ingress-port']" --relax --debug info --log-file hash.log
	WARNING: No route found for IPv6 destination :: (no default route?)
	hash_test.HashTest ... FAIL

	======================================================================
	FAIL: hash_test.HashTest
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "ptftests/hash_test.py", line 230, in runTest
		self.check_hash(hash_key)
	  File "ptftests/hash_test.py", line 82, in check_hash
		assert True if len(hit_count_map.keys()) > 1 else False
	AssertionError

	----------------------------------------------------------------------
	Ran 1 test in 3.424s

	FAILED (failures=1)

	******************************************
	ATTENTION: SOME TESTS DID NOT PASS!!!

	The following tests failed:
	HashTest

	******************************************

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

	root@sonic-s6100-10:~# show ver

	SONiC Software Version: SONiC.HEAD.53-898f8789
	Distribution: Debian 9.12
	Kernel: 4.9.0-11-2-amd64
	Build commit: 898f8789
	Build date: Mon Apr 20 06:06:36 UTC 2020
	Built by: johnar@jenkins-worker-7

	Platform: x86_64-dell_s6100_c2538-r0
	HwSKU: Force10-S6100-T1
	ASIC: broadcom
	Serial Number: FXGSG02
	Uptime: 10:25:06 up 11:33,  1 user,  load average: 2.26, 2.27, 2.25

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by chitra-raghavan** [comment]
Hash test  passed without ingress-port parameter.

**Comment by xinliu-seattle** [comment]
BRCM will take a look at this.

**Comment by chitra-raghavan** [comment]
As per the weekly discussion with Dell-MSFT, This ingress-port is optional parameter . Hence closing this Issue

**Comment by ben-gale** [comment]
Thanks Chitra. I did follow-up. As we know: -
- SONiC (nor SAI) does not specify required hash behavior, so I think this test should be considered informative rather than normative.
- SAI also does not have any knobs for Hash configuration - it's implementer choice
- In this case, we (Broadcom) *could* include the src port in the hash, but don't seem to today. Maybe we'll change this one day, but it's not a priority for us at all.
- So, I agree that closing the issue is the right thing to do at this stage.

Thanks.
