### ISSUE TITLE
Service Requires swss will cause fast/warm reboot to fail

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#4473]
**Description**

Following 3 services were added with Requires swss flag:

root@sonic-host:/etc/systemd/system# grep swss *.service | grep Requires
iccpd.service:Requires=updategraph.service swss.service
mgmt-framework.service:Requires=swss.service
nat.service:Requires=updategraph.service swss.service

There are issues associated with this Rerquires flag:

During warm/fast reboot. These service will be shutdown when swss goes down. That adds extra time. And if service restart kicks in, they will drag up swss, causing fast/warm reboot to fail.

These services needs to be changed to be After swss service. And address dependency in swss service script following the existing examples.

**Steps to reproduce the issue:**
1. sudo fast-reboot -v or sudo warm-reboot -v and watch the progress

**Describe the results you received:**
The shutdown procedure could take several minutes. This is not a 100% reproduce.

**Describe the results you expected:**
shutdown happen quickly within 20-30 seconds before kexec kicks in.

**Additional information you deem important (e.g. issue happens only occasionally):**
admin@str-7260cx3-acs-1:~$ sudo ./fast-reboot -v
OK
Thu Apr 23 16:10:45 UTC 2020 Stopping nat ...
Thu Apr 23 16:10:46 UTC 2020 Stopped nat ...
Thu Apr 23 16:10:46 UTC 2020 Stopping radv ...
Thu Apr 23 16:10:46 UTC 2020 Stopping bgp ...
Thu Apr 23 16:10:46 UTC 2020 Stopped bgp ...
Thu Apr 23 16:10:49 UTC 2020 Stopping teamd ...
Thu Apr 23 16:10:50 UTC 2020 Stopped teamd ...

Thu Apr 23 16:12:22 UTC 2020 Stopping syncd ...
Thu Apr 23 16:14:01 UTC 2020 Stopped syncd ...
Thu Apr 23 16:14:01 UTC 2020 Stopping all remaining containers ...
Warning: Stopping telemetry.service, but it can still be activated by:
  telemetry.timer
Thu Apr 23 16:14:03 UTC 2020 Stopped all remaining containers ...
Thu Apr 23 16:14:15 UTC 2020 Rebooting with /sbin/kexec -e to SONiC-OS-master.259-583bfde4 ...

**Comment by xinliu-seattle** [comment]
service owners please help to take a look. BRCM will take a look at mgmt.-framework, and NAT, Nephos will take a look at ICCPD.

**Comment by ben-gale** [comment]
https://github.com/Azure/sonic-buildimage/pull/4548 has been raised for Mgmt FW. 

NAT is coming soon.

**Comment by ben-gale** [comment]
> #4548 has been raised for Mgmt FW.
> 
> NAT is coming soon.

See https://github.com/Azure/sonic-buildimage/pull/4551 for NAT
