### ISSUE TITLE
No rule to make target 'target/debs/buster/python-p4-hlir_0.9.36-1_all.deb

### ISSUE THREAD

**Issue by kumarph** [Azure/sonic-buildimage#4505]
Hi Team,

I am trying to build P4 platform. During "make all" command i am facing the below error
Can you please help us to resolve the build error

BLDENV=buster make -f Makefile.work all
make[1]: Entering directory '/home/saps/sonic/sonic-buildimage'
SONiC Build System

Build Configuration
"CONFIGURED_PLATFORM"             : "p4"
"CONFIGURED_ARCH"                 : "amd64"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_BUILD_JOBS"                : "1"
"SONIC_CONFIG_MAKE_JOBS"          : "4"
"SONIC_USE_DOCKER_BUILDKIT"       : ""
"USERNAME"                        : "admin"
"PASSWORD"                        : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : ""
"INSTALL_KUBERNETES"              : "n"
"ENABLE_PFCWD_ON_START"           : ""
"INSTALL_DEBUG_TOOLS"             : ""
"ROUTING_STACK"                   : "frr"
"FRR_USER_UID"                    : "300"
"FRR_USER_GID"                    : "300"
"ENABLE_SYNCD_RPC"                : ""
"ENABLE_ORGANIZATION_EXTENSIONS"  : "y"
"HTTP_PROXY"                      : ""
"HTTPS_PROXY"                     : ""
"ENABLE_SYSTEM_TELEMETRY"         : "y"
"ENABLE_RESTAPI"                  : "n"
"ENABLE_ZTP"                      : ""
"SONIC_DEBUGGING_ON"              : ""
"SONIC_PROFILING_ON"              : ""
"KERNEL_PROCURE_METHOD"           : "build"
"BUILD_TIMESTAMP"                 : "20200429.234722"
"BUILD_LOG_TIMESTAMP"             : "none"
"BLDENV"                          : "buster"
"VS_PREPARE_MEM"                  : "yes"
"ENABLE_SFLOW"                    : "y"
"ENABLE_NAT"                      : "y"
"SONIC_DPKG_CACHE_METHOD"         : "none"

**make: *** No rule to make target 'target/debs/buster/python-p4-hlir_0.9.36-1_all.deb', needed by 'target/debs/buster/python-p4-hlir_0.9.36-1_all.deb-install'.  Stop.
Makefile.work:219: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/saps/sonic/sonic-buildimage'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2**

**Comment by paNjii** [comment]
I am also running into this issue, is there any known workaround/solution for this?

**Comment by kumarph** [comment]
I stopped builing P4 platform and went to VS platform.
With VS platform build is successfull without any issue. i was able to spawn SONIC KVM in my Ubuntu 18.04

**Comment by lguohan** [comment]
P4 platform is not maintained now.

**Comment by paNjii** [comment]
> 
> 
> I stopped builing P4 platform and went to VS platform.
> With VS platform build is successfull without any issue. i was able to spawn SONIC KVM in my Ubuntu 18.04

Can you perhaps point me to what you used to get started with VS ? I found this: https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.VsSetup.md but I do not have access to vEOS or cEOS images, is there another way ?
