### ISSUE TITLE
config CLI  fails with traceback no attribute 'load_sonic_global_db_config'

### ISSUE THREAD

**Issue by mykolaf** [Azure/sonic-buildimage#4536]
**Description**

201911 have issue with `config` CLI.
` AttributeError: type object 'SonicDBConfig' has no attribute 'load_sonic_global_db_config' `

**Steps to reproduce the issue:**
1. `config load_minigraph `
2.
3.

**Describe the results you received:**
```
root@sonic:/home/admin# config load_minigraph -y
Traceback (most recent call last):
  File "/usr/bin/config", line 12, in <module>
    sys.exit(config())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 582, in config
    SonicDBConfig.load_sonic_global_db_config()
AttributeError: type object 'SonicDBConfig' has no attribute 'load_sonic_global_db_config'
```
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    SONiC.201911.85-c266435d
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by judyjoseph** [comment]
Hi,
   In 201911, it should get resolved, once we merge in https://github.com/Azure/sonic-py-swsssdk/pull/63. We are in the process of doing the same.

   Ideally in master we should not be seeing the sonic-py-swssdk submodule is already updated to latest via this PR https://github.com/Azure/sonic-buildimage/pull/4421

**Comment by mykolaf** [comment]
Fixed by [submodule update](https://github.com/Azure/sonic-buildimage/commit/acd82fcdc1e44afe8cacfbf9028db0591862c236)
