### ISSUE TITLE
BGPv6 Neighbor configuration on config_db not generated to frr.conf

### ISSUE THREAD

**Issue by Ezrickd** [Azure/sonic-buildimage#4572]
bgp neighbor at 2019 image from March is creating frr config for ipv6 afi neighbor atatement.
when moving to newest image BGP ipv6 unicast neighbor statement is not created.

checking at BGP container I see that there are new folders :
At BGP Docker it is pointing to /usr/share/sonic/templates/bgpd/templates/general/instance.conf.j2

when on erlier build it was all on /usr/share/sonic/templates/

my configuration is simple.

       "2001:0:0:0:192:168:0:74": {
            "asn": "3230003333",
            "holdtime": "10",
            "keepalive": "3",
            "local_addr": "2001:0:0:0:192:168:0:75",
            "name": "t1s9003_p20",
            "nhopself": "0",
            "rrclient": "0"
        },
root@sonic-01:~# show ipv6 bgp summary
% No BGP neighbors found

when running older version like March 201911 image it works,..

**Comment by Ezrickd** [comment]
thank you Pavel.
attached show commands.
[show commands.txt](https://github.com/Azure/sonic-buildimage/files/4612142/show.commands.txt)

**Comment by Ezrickd** [comment]
Hi Pavel 
Found the issue it is a Bug.
IPv6 address is trancating the traling zero to double colon as allowed for IPv6 address.
the IPv6 local address is paresed as user inserted it , thus the local address is not found on ipv6 local device and neighbor is not created.

as you can see from the example only if i will configre the local address as trancated zero's to match the ipv6 interface BGP neighbor will be created at FRR.

here is an example:

root@sonic:~# show ipv6 interfaces
PortChannel1             2001:face::10/127                       up/down       AE-2100-11      2001:face::9
PortChannel17            2001::192:168:0:97/127                  up/down       N/A             N/A

config_db bgp neighbor:
        "2001:0:0:0:192:168:0:96": {
            "admin_status": "up",
            "asn": "65501",
            "holdtime": "10",
            "keepalive": "3",
            "local_addr": "2001:0:0:0:192:168:0:97",
            "name": "AE-2100-11",
            "nhopself": "0",
            "rrclient": "0"
        },
        "2001:face::9": {
            "admin_status": "up",
            "asn": "65501",
            "holdtime": "10",
            "keepalive": "3",
            "local_addr": "2001:face::10",
            "name": "AE-2100-11",
            "nhopself": "0",
            "rrclient": "0"
        }
    "PORTCHANNEL_INTERFACE": {
        "PortChannel1": {},
        "PortChannel17": {},
        "PortChannel1|192.168.0.65/31": {},
        "PortChannel1|2001:face::10/127": {},
        "PortChannel17|192.168.0.97/31": {},
        "PortChannel17|2001:0:0:0:192:168:0:97/127": {},

## If I will change the BGP local Address to trancated zeros, it will be installed.
change the BGP local address to match the interface ipv6 address 

        "2001:0:0:0:192:168:0:96": {
            "admin_status": "up",
            "asn": "65501",
            "holdtime": "10",
            "keepalive": "3",
            "local_addr": "2001::192:168:0:97",
            "name": "AE-2100-11",
            "nhopself": "0",
            "rrclient": "0"
        },
        "2001:face::9": {
            "admin_status": "up",
            "asn": "65501",
            "holdtime": "10",
            "keepalive": "3",
            "local_addr": "2001:face::10",
            "name": "AE-2100-11",
            "nhopself": "0",
            "rrclient": "0"
        }
    },

:/etc/sonic# show ipv6 interfaces
Interface      Master    IPv6 address/mask                       Admin/Oper    BGP Neighbor    Neighbor IP
-------------  --------  --------------------------------------  ------------  --------------  -----------------------
Bridge                   fe80::38dc:7bff:fe47:35ee%Bridge/64     up/down       N/A             N/A
Loopback0                2001:face:face::1/128                   up/up         N/A             N/A
                         fe80::18ad:ccff:fea1:c117%Loopback0/64
PortChannel1             2001:face::10/127                       up/down       AE-2100-11      2001:face::9
PortChannel17            2001::192:168:0:97/127                  up/down       AE-2100-11      2001:0:0:0:192:168:0:96

root@l-csi-4700-01:/etc/sonic# show ipv6 bgp summary

IPv6 Unicast Summary:
BGP router identifier 1.1.1.1, local AS number 65001 vrf-id 0
BGP table version 1
RIB entries 1, using 184 bytes of memory
Peers 2, using 41 KiB of memory
Peer groups 2, using 128 bytes of memory

Neighbor           V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
2001::192:168:0:96 4      65501       0       0        0    0    0    never       Active
2001:face::9       4      65501       0       0        0    0    0    never       Active

**Comment by paulnice** [comment]
@Ezrickd Thank you for your investigation.
Let me try to find the issue in the bgpcfgd. I think what we need is to have all ipv6 addresses to be converted to the one canonical format. Otherwise it is hard to compare them.
Or we have to have all ip addresses as objects, not strings.

**Comment by pavel-shirshov** [comment]
Can you please try this fix https://github.com/Azure/sonic-buildimage/pull/4876

**Comment by rlhui** [comment]
@Ezrickd, will you please confirm if this issue is fixed? Thanks.

**Comment by Ezrickd** [comment]
Is the fix present in 201911 ?

I am using only this for now. If so can
You advise on when it was merged.

Ezrickd

Sent from my iPhone
Sorry for his typing errors (-;

On 28 Jul 2020, at 23:24, rlhui <notifications@github.com> wrote:

﻿

@Ezrickd<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEzrickd&data=02%7C01%7Cezrick%40mellanox.com%7C6ebba41241d64335494c08d83334407f%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C637315646799130973&sdata=rWt1HXfg5XzCWLmsH6XWtqbmzAjblZ3KjX9%2BRt1P5Tc%3D&reserved=0>, will you please confirm if this issue is fixed? Thanks.

**Comment by liat-grozovik** [comment]
@rlhui please confirm the fix is already merged to 201911 otherwise Ezrik cannot verify it. Or you can let me know which exactly fix you would like me to include in a build for him to test.

**Comment by rlhui** [comment]
@liat-grozovik , @Ezrickd, actually the PR to fix this is not yet merged.  Pavel has a question if you could try it.  Before it's merged, please see if it's feasible for you to pull in his PR to your repo and test it, if issue is still found?

**Comment by pavel-shirshov** [comment]
You don't need to build any image
Just donwload file https://raw.githubusercontent.com/Azure/sonic-buildimage/b6c395c864bcb12b688fb120661544a1c7da8fa1/src/sonic-bgpcfgd/bgpcfgd and put it into bgp container instead of the old one
```
docker cp bgpcfgd bgp:/usr/local/bin/bgpcfgd
```

**Comment by Ezrickd** [comment]
Hi Pavel.
tested the new bgpcfgd file, 
works Great ! 
tested with all "zero" and mixed "zero & double colon" 
in every test case the Ipv6 is truncated to double colon and FRR config is matching the IPv6 address.
Excellent.
Ezrickd
