### ISSUE TITLE
Image is compile with flag ENABLE_DHCP_GRAPH_SERVICE and loaded it will not able to use existing config_db.json on system

### ISSUE THREAD

**Issue by abdosi** [Azure/sonic-buildimage#4580]
**Description**
Issue where image is compile with flag ENABLE_DHCP_GRAPH_SERVICE and then we load image and reboot even if there was existing
config_db.json on file system we will still look for DHCP Service for minigraph after reboot and system remain in that stuck state.This behavior is different to what we have in 201811 image.

**Steps to reproduce the issue:**
1. compile image with flag ENABLE_DHCP_GRAPH_SERVICE 
2. Load the image on existing system that has config_db.josn and reboot

**Describe the results you received:**
After reboot system gets stuck looking for DHCP service.

**Describe the results you expected:**

System should not get stuck and using config_db.json present on system before reboot and used for configuration

**Comment by abdosi** [comment]
Issue is being fixed via

https://github.com/Azure/sonic-buildimage/pull/4573

**Comment by xinliu-seattle** [comment]
This has been resolved.
