### ISSUE TITLE
S6100: sonic-clear command doesnt work in master image - 281

### ISSUE THREAD

**Issue by mini-nair-dell** [Azure/sonic-buildimage#4594]
Passed image - Jenkins Master Branch 259
==========================================

root@sonic-s6100-07:~# sonic-clear fdb all
FDB entries are cleared.

Failed image - Jenkins Master Branch 281
=========================================

root@sonic-s6100-07:/var/core# sonic-clear fdb all
Traceback (most recent call last):
  File "/usr/bin/sonic-clear", line 8, in <module>
    from clear.main import cli
  File "/usr/lib/python2.7/dist-packages/clear/main.py", line 165, in <module>
    from .bgp_quagga_v4 import bgp
  File "/usr/lib/python2.7/dist-packages/clear/bgp_quagga_v4.py", line 19, in <module>
    @bgp.command(default=True)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1234, in decorator
    cmd = command(*args, **kwargs)(f)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 89, in _make_command
    callback=f, params=params, **attrs)
TypeError: __init__() got an unexpected keyword argument 'default'

The issue is seen in both T0 and T1 devices.

root@sonic-s6100-07:~# show ver

SONiC Software Version: SONiC.master.281-286aa35a
Distribution: Debian 10.4
Kernel: 4.19.0-6-amd64
Build commit: 286aa35a
Build date: Sun May 10 11:13:59 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
Serial Number: 2G5ZZP2
Uptime: 09:03:48 up  2:14,  1 user,  load average: 2.09, 2.14, 2.08

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-sonic-mgmt-framework   latest                d3de12ec2525        458MB
docker-sonic-mgmt-framework   master.281-286aa35a   d3de12ec2525        458MB
docker-teamd                  latest                3decefd65d68        311MB
docker-teamd                  master.281-286aa35a   3decefd65d68        311MB
docker-syncd-brcm             latest                38072155f27d        438MB
docker-syncd-brcm             master.281-286aa35a   38072155f27d        438MB
docker-sonic-telemetry        latest                51f5e1677f38        353MB
docker-sonic-telemetry        master.281-286aa35a   51f5e1677f38        353MB
docker-snmp-sv2               latest                927a958e5a5a        347MB
docker-snmp-sv2               master.281-286aa35a   927a958e5a5a        347MB
docker-sflow                  latest                2b4adce4dccc        312MB
docker-sflow                  master.281-286aa35a   2b4adce4dccc        312MB
docker-router-advertiser      latest                3f804dd072d6        290MB
docker-router-advertiser      master.281-286aa35a   3f804dd072d6        290MB
docker-platform-monitor       latest                ae7d66e3f592        354MB
docker-platform-monitor       master.281-286aa35a   ae7d66e3f592        354MB
docker-orchagent              latest                e81348724a8f        329MB
docker-orchagent              master.281-286aa35a   e81348724a8f        329MB
docker-nat                    latest                5e7c3b454bc1        312MB
docker-nat                    master.281-286aa35a   5e7c3b454bc1        312MB
docker-lldp-sv2               latest                7f64c376c03b        308MB
docker-lldp-sv2               master.281-286aa35a   7f64c376c03b        308MB
docker-fpm-frr                latest                5625861ee712        331MB
docker-fpm-frr                master.281-286aa35a   5625861ee712        331MB
docker-dhcp-relay             latest                48294d05e601        300MB
docker-dhcp-relay             master.281-286aa35a   48294d05e601        300MB
docker-database               latest                cac06e21f1c3        290MB
docker-database               master.281-286aa35a   cac06e21f1c3        290MB

root@sonic-s6100-07:~#

Thanks
Mini

**Comment by xinliu-seattle** [comment]
@mini will re-test and will confirm if it has been fixed.

**Comment by mini-nair-dell** [comment]
This issue is fixed in the image - SONiC.master.295-f532fb95

Hence closing it.
