### ISSUE TITLE
SONiC build fail - azure-storage cannot be installed anymore

### ISSUE THREAD

**Issue by Russell123987** [Azure/sonic-buildimage#4621]
**Description**
Build SONiC bin fail happened 5/12 until now. Before that i can build success.

**Steps to reproduce the issue:**
 branch is up-to-date with 'origin/master'.
1.git checkout =>branch is up-to-date with 'origin/master'.
2.make init 
3.make configure PLATFORM=broadcom (build other vendor the same problem)
4.make all

**Describe the results you received:**
Collecting azure-storage
  Downloading https://files.pythonhosted.org/packages/5d/cd/cac628adf6cb0086a24c20d76609445f1bf841483d56ec9f5645bbaa9ab7/azure-storage-0.37.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yDGjnW/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yDGjnW/azure-storage/
 clean_sys
 sudo umount ./fsroot/sys/fs/cgroup/blkio ./fsroot/sys/fs/cgroup/cpuset ./fsroot/sys/fs/cgroup/devices ./fsroot/sys/fs/cgroup/freezer ./fsroot/sys/fs/cgroup/hugetlb ./fsroot/sys/fs/cgroup/memory ./fsroot/sys/fs/cgroup/perf_event ./fsroot/sys/fs/cgroup/pids ./fsroot/sys/fs/cgroup/rdma ./fsroot/sys/fs/cgroup ./fsroot/sys
 true
 sudo umount ./fsroot/proc
 true
[  FAIL LOG END  ] [ target/sonic-broadcom.bin ]
slave.mk:758: recipe for target 'target/sonic-broadcom.bin' failed
make: *** [target/sonic-broadcom.bin] Error 1
Makefile.work:216: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sw/SONiC/sonic-buildimage'

**Describe the results you expected:**
i don`t know how fix this fail for build successful

**Comment by lguohan** [comment]
fixed in https://github.com/Azure/sonic-buildimage/commit/1066f238ba2a2ad80000bd8a233856dffc3352b2
