### ISSUE TITLE
[device/accton]Syntax error on config.bcm for AS7312-54XS, AS7312-54X and AS7315-27XB causing interface not showing up

### ISSUE THREAD

**Issue by tanpinsiang** [Azure/sonic-buildimage#4667]
**Syntax error on config.bcm for AS7312-54XS, AS7312-54X and AS7315-27XB causing interface not showing up**

Tested on 201904_57, 201911_74, 201911_81 and master branch.
`sudo show interfaces status`
Shows nothing and the port didn't responds to any command.

Error occur on AS7312-54XS:
sonic INFO syncd#supervisord: syncd Platform configuration: format error in /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm on line 110 (ignored)#015

After checking the file, in line 110 there is a comment " /* Port Map */ ". It looks like a syntax error.
You can check it here: [th-as7312-48x25G+6x100G.config.bcm](https://github.com/Azure/sonic-buildimage/blob/master/device/accton/x86_64-accton_as7312_54xs-r0/Accton-AS7312-54XS/th-as7312-48x25G%2B6x100G.config.bcm#L110)

**Steps to reproduce the issue:**
1. install either 201904_57, 201911_74, 201911_81 or master branch on AS7312-54XS
2. `sudo show interfaces status`, shows nothing and the port didn't responds to any command.
3. check `show logging` command: `sonic INFO syncd#supervisord: syncd Platform configuration: format error in /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm on line 110 (ignored)#015`

**Describe the results you received:**
`sudo show interfaces status` shows nothing and the port didn't responds to any command.
check `show logging` 
```
Feb 14 10:12:45.737033 sonic INFO syncd#syncd: [none] board_id_default:445 Failed to obtain switch ID.
Feb 14 10:12:45.749332 sonic INFO syncd#supervisord: syncd DMA pool size: 33554432#015
Feb 14 10:12:45.749332 sonic INFO syncd#supervisord: syncd warning: device 0xb967 revision 0x2 is not supported#015
Feb 14 10:12:45.749332 sonic INFO syncd#supervisord: syncd Platform configuration: format error in /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm on line 110 (ignored)#015
```
**Describe the results you expected:**
`sudo show interfaces status` should show something like this:
```
admin@sonic:~$ show interfaces status
  Interface            Lanes    Speed    MTU          Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -------------  ------  ------  -------  ---------------  ----------
  Ethernet0               73      10G   9100         swp001  routed    down       up              N/A         N/A
  Ethernet1               74      10G   9100         swp002  routed    down       up              N/A         N/A
  Ethernet2               75      10G   9100         swp003  routed    down       up              N/A         N/A
  Ethernet3               76      10G   9100         swp004  routed    down       up              N/A         N/A
```

**Output of `show version`:**
```
SONiC Software Version: SONiC.master.294-ddd6368e
Distribution: Debian 10.4
Kernel: 4.19.0-6-amd64
Build commit: ddd6368e
Build date: Sat May 23 11:21:59 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-accton_as7312_54xs-r0
HwSKU: Accton-AS7312-54XS
ASIC: broadcom
Serial Number: 731254XS2004135
Uptime: 10:14:11 up 2 min, 1 user, load average: 1.10, 0.76, 0.30
```

**Attach debug file `sudo generate_dump`:**
[Link to find the dump](https://akirakan-my.sharepoint.com/:u:/p/pinsiang_tan/ESEU7ZQdwLpIkSyyTa1mAHQBvQ74tpRfZlntc5ysewvFiQ?e=GY8gZe)

**The same comment is present in the following model too:**
1)AS7312-54X
`./x86_64-accton_as7312_54x-r0/Accton-AS7312-54X/th-as7312-48x25G+6x100G.config.bcm:110:/* Port Map */`
2)AS7312-54XS (this model tested)
`./x86_64-accton_as7312_54xs-r0/Accton-AS7312-54XS/th-as7312-48x25G+6x100G.config.bcm:110:/* Port Map */`
3)AS7315-27XB
`./x86_64-accton_as7315_27xb-r0/Accton-AS7315-27XB/qax-as7315-20x10G+4x25G+3x100G.config.bcm:110:/* Port Map */`

**Possible solution:**
Change `/* Port Map */` to `#/* Port Map */`

**Comment by Lewis-Kang** [comment]
_"Feb 14 10:12:45.749332 sonic INFO syncd#supervisord: syncd warning: device 0xb967 revision 0x2 is not supported#015"_
The above message means that the ASIC used by AS7312-54XS is not supported by the SAI debian packages got from the links indicated in [https://github.com/Azure/sonic-buildimage/blob/master/platform/broadcom/sai.mk](url)

**Comment by Lewis-Kang** [comment]
As I know, the current SAI debian packages (got from the links indicated in https://github.com/Azure/sonic-buildimage/blob/master/platform/broadcom/sai.mk) support the ASIC used by AS7312-54X, but do not support the ASIC used by  AS7312-54XS and AS7315-27XB.

**Comment by chihhan123** [comment]
Solve related issue by PR:
    https://github.com/Azure/sonic-buildimage/pull/4702
Thanks!

**Comment by tanpinsiang** [comment]
Dear @Lewis-Kang, where can I check the SAI debian packages (got from the links indicated in https://github.com/Azure/sonic-buildimage/blob/master/platform/broadcom/sai.mk) support the ASIC used by AS7312-54X, but do not support the ASIC used by AS7312-54XS and AS7315-27XB.
Is it fixable by the PR: #4702?

**Comment by Lewis-Kang** [comment]
@tanpinsiang, the SAI debian packages are released by Broadcom, so we can either check with Broadcom or try to run it to know the answer. The following message means the ASIC is not being supported by the used SAI packages. (PR: #4702 doesn't make SAI support AS7312-54XS and AS7315-27XB)

_sonic INFO syncd#supervisord: syncd warning: device 0xb967 revision 0x2 is not supported_

**Comment by tanpinsiang** [comment]
@Lewis-Kang thanks for the explanation. Do you have any best guess for me about which SAI debian packages are most likely to support AS7312-54XS(Tomahawk+)?

**Comment by Lewis-Kang** [comment]
@tanpinsiang I don't have the information about Broadcom's SAI development plan for supporting various ASICs...

**Comment by tanpinsiang** [comment]
@Lewis-Kang thanks for the info. 
This syntax error issue was solve the following error by the PR:
#4702 and tested on AS7312-54XS. It does fix the format error. 
This issue can be closed.

For the SAI debian packages support for Tomahawk+, do you think it deserve a new issue?

**Comment by Lewis-Kang** [comment]
@tanpinsiang I think you can create an issue. But Broadcom may have their own plan on ASIC support of their released SAI debian packages, I am not sure whether creating such issue would help or not.

**Comment by tanpinsiang** [comment]
PR: #4702 merged. Closing this issue.
