### ISSUE TITLE
After warm-restart swss docker, crm counters were abnormal

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#4736]
**Description**
After warm-restart swss docker, crm counters were abnormal. It prompted that CRM counters are not ready. They would be populated after the polling interval. It couldn't be recovered until device restarted.

**Steps to reproduce the issue:**
1、sudo config warm_restart enable swss
2、sudo systemctl restart swss
3、crm show resources all
**Describe the results you received:**
root@switch2:/home/admin# crm  show resources all

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                       7              16369
ipv6_route                       8               4092
ipv4_nexthop                     1              65531
ipv6_nexthop                     1              65531
ipv4_neighbor                    1              24573
ipv6_neighbor                    1              12286
nexthop_group_member             0              32768
nexthop_group                    0                256
fdb_entry                        2              32764

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  3
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

root@switch2:/home/admin# sudo config warm_restart enable swss
root@switch2:/home/admin# sudo systemctl restart swss
root@switch2:/home/admin# crm  show resources all

CRM counters are not ready. They would be populated after the polling interval.

Resource Name    Used Count    Available Count
---------------  ------------  -----------------

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  3
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

root@switch2:/home/admin# 

**Describe the results you expected:**
After warm-restart swss docker, crm counters are the same as before.

root@switch2:/home/admin# crm  show resources all

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                       7              16369
ipv6_route                       8               4092
ipv4_nexthop                     1              65531
ipv6_nexthop                     1              65531
ipv4_neighbor                    1              24573
ipv6_neighbor                    1              12286
nexthop_group_member             0              32768
nexthop_group                    0                256
fdb_entry                        2              32764

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  3
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```
root@switch2:/home/admin#  show version 

SONiC Software Version: SONiC.HEAD.67-8367dfeb
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 8367dfeb
Build date: Wed May  6 13:49:49 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
Serial Number: G1MW80H000123
Uptime: 16:10:21 up 21 min,  2 users,  load average: 0.59, 0.77, 0.67

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-syncd-brcm             HEAD.67-8367dfeb    6902f81e3ca3        430MB
docker-syncd-brcm             latest              6902f81e3ca3        430MB
docker-platform-monitor       HEAD.67-8367dfeb    299fc1d87ebf        334MB
docker-platform-monitor       latest              299fc1d87ebf        334MB
docker-router-advertiser      HEAD.67-8367dfeb    d1f31448c1b9        283MB
docker-router-advertiser      latest              d1f31448c1b9        283MB
docker-fpm-frr                HEAD.67-8367dfeb    c2b1f3dde8c8        328MB
docker-fpm-frr                latest              c2b1f3dde8c8        328MB
docker-sflow                  HEAD.67-8367dfeb    22588d030e81        308MB
docker-sflow                  latest              22588d030e81        308MB
docker-lldp-sv2               HEAD.67-8367dfeb    8a9b1ba67160        305MB
docker-lldp-sv2               latest              8a9b1ba67160        305MB
docker-orchagent              HEAD.67-8367dfeb    eed753ed4e3b        326MB
docker-orchagent              latest              eed753ed4e3b        326MB
docker-dhcp-relay             HEAD.67-8367dfeb    a91bd90f721a        293MB
docker-dhcp-relay             latest              a91bd90f721a        293MB
docker-database               HEAD.67-8367dfeb    7665762c9470        283MB
docker-database               latest              7665762c9470        283MB
docker-snmp-sv2               HEAD.67-8367dfeb    893a54916304        340MB
docker-snmp-sv2               latest              893a54916304        340MB
docker-teamd                  HEAD.67-8367dfeb    2e77c5e410ba        307MB
docker-teamd                  latest              2e77c5e410ba        307MB
docker-nat                    HEAD.67-8367dfeb    d1c78016f845        309MB
docker-nat                    latest              d1c78016f845        309MB
docker-sonic-mgmt-framework   HEAD.67-8367dfeb    f1f88830db0c        422MB
docker-sonic-mgmt-framework   latest              f1f88830db0c        422MB
docker-sonic-telemetry        HEAD.67-8367dfeb    65d82748277a        345MB
docker-sonic-telemetry        latest              65d82748277a        345MB

root@switch2:/home/admin# 

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@tim-rj Please list exact steps of warm restarting swss.

Warm restarting this swss requires following steps:

sudo config warm_restart enable swss
sudo service swss restart
wait until the reconciliation is done.
sudo config warm_restart disable swss

If you didn't follow this exact steps, please retest.

**Comment by tim-rj** [comment]
> service swss restart
@yxieca @xinliu-seattle  follow exactly the same steps , we found orchagent crash immediately ,syslog show as below:
Jun 11 22:17:34.803112 switch2 NOTICE syncd#syncd: :- threadFunction:  new span  = 417
Jun 11 22:17:35.094311 switch2 INFO swss#supervisord: start.sh portsyncd: started
Jun 11 22:17:35.126010 switch2 NOTICE swss#orchagent: :- postBake: Start MirrorOrch post-baking
Jun 11 22:17:35.126010 switch2 NOTICE swss#orchagent: :- warmRestoreValidation: There are pending consumer tasks after restore: 
Jun 11 22:17:35.126010 switch2 NOTICE swss#orchagent: :- warmRestoreValidation: PORT_TABLE:Ethernet20|SET|index:20|lanes:33|fec:none|mtu:9100|alias:twentyfiveGigE0/21|admin_status:up|speed:250000|oper_status:down|description:
Jun 11 22:17:35.126010 switch2 NOTICE swss#orchagent: :- warmRestoreValidation: PORT_TABLE:Ethernet21|SET|index:21|lanes:34|fec:none|mtu:9100|alias:twentyfiveGigE0/22|admin_status:up|speed:250000|oper_status:down|description:
Jun 11 22:17:35.126010 switch2 NOTICE swss#orchagent: :- warmRestoreValidation: PORT_TABLE:Ethernet23|SET|index:23|lanes:36|mtu:9100|alias:twentyfiveGigE0/24|admin_status:up|speed:250000|oper_status:down|description:
Jun 11 22:17:35.126010 switch2 NOTICE swss#orchagent: :- warmRestoreValidation: PORT_TABLE:Ethernet24|SET|index:24|lanes:41|mtu:9100|alias:twentyfiveGigE0/25|admin_status:up|speed:250000|oper_status:down|description:
Jun 11 22:17:35.126127 switch2 NOTICE swss#orchagent: :- setWarmStartState: orchagent warm start state changed to restored
Jun 11 22:17:35.126127 switch2 ERR swss#orchagent: :- warmRestoreAndSyncUp: Orchagent state restore failed
Jun 11 22:17:35.126127 switch2 ERR swss#orchagent: :- main: Failed to initialize orchstration daemon
Jun 11 22:17:35.126534 switch2 INFO swss#supervisord: orchagent terminate called without an active exception

**Comment by tim-rj** [comment]
Update verification: This issue has gone on newest 201911 branch.  which means this is a bug on this build 'SONiC Software Version: SONiC.HEAD.67-8367dfeb' , not SAI or PLATFORM issue.

**Comment by tim-rj** [comment]
After updating to newest 201911 version and master version, this issue has gone. We will try to reproduce it later and update progress in time.

**Comment by yxieca** [comment]
@tim-rj can you close issue after verifying it is addressed?

**Comment by tim-rj** [comment]
After fix config_db.json's style, the issue has gone. close this!
