### ISSUE TITLE
The port can not become up on  x86_64-accton_wedge100bf_32x-r0.

### ISSUE THREAD

**Issue by PJHsieh** [Azure/sonic-buildimage#4782]
**Description**

**Steps to reproduce the issue:**
1. Install image  SONiC-OS-201911.57-dirty-20200614.033737 on device x86_64-accton_wedge100bf_32x-r0.
2. Loopback connect Ethernet0 and Ethernet4.
3. Set Ethernet0 and Ethernet4 Admin to up.
4. Ethernet0 and Ethernet4 can not become up.

**Describe the results you received:**

root@sonic:/var/log# show int sta
  Interface            Lanes    Speed    MTU        Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----------  ------  ------  -------  ------  ----------
  Ethernet0          0,1,2,3     100G   9100    Ethernet0  routed    down       up     N/A         N/A
  Ethernet4          4,5,6,7     100G   9100    Ethernet4  routed    down       up     N/A         N/A
  Ethernet8        8,9,10,11     100G   9100    Ethernet8  routed    down       up     N/A         N/A

**Describe the results you expected:**
The Oper status for Ethernet0 and Ethernet4 shall become "up".

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
root@sonic:/var/log# show version

SONiC Software Version: SONiC.201911.57-dirty-20200614.033737
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 093d7731
Build date: Sun Jun 14 09:53:03 UTC 2020
Built by: johnar@jenkins-worker-12

Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot
Serial Number: 1632X1706012
Uptime: 19:42:31 up 29 min,  1 user,  load average: 0.56, 0.42, 0.38

Docker images:
REPOSITORY                    TAG                               IMAGE ID            SIZE
docker-syncd-bfn              201911.57-dirty-20200614.033737   c7bf7f5a0616        2.41GB
docker-syncd-bfn              latest                            c7bf7f5a0616        2.41GB
docker-sonic-telemetry        201911.57-dirty-20200614.033737   13027c25bb1c        349MB
docker-sonic-telemetry        latest                            13027c25bb1c        349MB
docker-router-advertiser      201911.57-dirty-20200614.033737   1df34a4fd6f7        285MB
docker-router-advertiser      latest                            1df34a4fd6f7        285MB
docker-platform-monitor       201911.57-dirty-20200614.033737   a1d6ecc05885        353MB
docker-platform-monitor       latest                            a1d6ecc05885        353MB
docker-fpm-frr                201911.57-dirty-20200614.033737   6d97988d9ad0        330MB
docker-fpm-frr                latest                            6d97988d9ad0        330MB
docker-lldp-sv2               201911.57-dirty-20200614.033737   1b54901ae381        307MB
docker-lldp-sv2               latest                            1b54901ae381        307MB
docker-dhcp-relay             201911.57-dirty-20200614.033737   d65f4233ad44        295MB
docker-dhcp-relay             latest                            d65f4233ad44        295MB
docker-database               201911.57-dirty-20200614.033737   3d2391af01c2        285MB
docker-database               latest                            3d2391af01c2        285MB
docker-sflow                  201911.57-dirty-20200614.033737   bfa7d9a18de6        310MB
docker-sflow                  latest                            bfa7d9a18de6        310MB
docker-orchagent              201911.57-dirty-20200614.033737   f0fd78d3bb1e        328MB
docker-orchagent              latest                            f0fd78d3bb1e        328MB
docker-teamd                  201911.57-dirty-20200614.033737   a82f8845b8f7        310MB
docker-teamd                  latest                            a82f8845b8f7        310MB
docker-nat                    201911.57-dirty-20200614.033737   19079002ce97        311MB
docker-nat                    latest                            19079002ce97        311MB
docker-sonic-mgmt-framework   201911.57-dirty-20200614.033737   603e3c2a99dd        425MB
docker-sonic-mgmt-framework   latest                            603e3c2a99dd        425MB
docker-snmp-sv2               201911.57-dirty-20200614.033737   5745c5529b43        343MB
docker-snmp-sv2               latest                            5745c5529b43        343MB

    ```
    (paste your output here)
    ```

admin@sonic:~$ show int sta Ethernet0
  Interface    Lanes    Speed    MTU      Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  -------  -------  -----  ---------  ------  ------  -------  ------  ----------
  Ethernet0  0,1,2,3     100G   9100  Ethernet0  routed    down       up     N/A         N/A
admin@sonic:~$ show int sta Ethernet4
  Interface    Lanes    Speed    MTU      Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  -------  -------  -----  ---------  ------  ------  -------  ------  ----------
  Ethernet4  4,5,6,7     100G   9100  Ethernet4  routed    down       up     N/A         N/A

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

The syncd repeat print the following messages.
Feb 12 19:48:12.358860 sonic ERR syncd[25]: 2018-02-12 19:48:12.358607 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_cpu_qsfp#012
Feb 12 19:48:12.358860 sonic ERR syncd[25]: 2018-02-12 19:48:12.358709 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error Communication Failed with Hardware: in scanning qsfps at qsfp_scan_timer_cb:473#012
Feb 12 19:48:12.358926 sonic INFO supervisord: syncd 2018-02-12 19:48:12.358607 BF_PLTFM ERROR - Error in unselect_cpu_qsfp
Feb 12 19:48:12.359340 sonic INFO supervisord: syncd 2018-02-12 19:48:12.358709 BF_PLTFM ERROR - Error Communication Failed with Hardware: in scanning qsfps at qsfp_scan_timer_cb:473
Feb 12 19:48:12.564044 sonic ERR syncd[25]: 2018-02-12 19:48:12.563763 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 11#012
Feb 12 19:48:12.564179 sonic INFO supervisord: syncd 2018-02-12 19:48:12.563763 BF_PLTFM ERROR - Error in select_qsfp port 11
Feb 12 19:48:12.767717 sonic ERR syncd[25]: 2018-02-12 19:48:12.767538 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 11#012
Feb 12 19:48:12.767832 sonic INFO supervisord: syncd 2018-02-12 19:48:12.767538 BF_PLTFM ERROR - Error in unselect_qsfp port 11
Feb 12 19:48:12.971774 sonic ERR syncd[25]: 2018-02-12 19:48:12.971601 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 4#012
Feb 12 19:48:12.971866 sonic INFO supervisord: syncd 2018-02-12 19:48:12.971601 BF_PLTFM ERROR - Error in select_qsfp port 4
Feb 12 19:48:13.175831 sonic ERR syncd[25]: 2018-02-12 19:48:13.175593 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 4#012
Feb 12 19:48:13.176117 sonic INFO supervisord: syncd 2018-02-12 19:48:13.175593 BF_PLTFM ERROR - Error in unselect_qsfp port 4
Feb 12 19:48:13.380970 sonic ERR syncd[25]: 2018-02-12 19:48:13.380687 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 7#012
Feb 12 19:48:13.381065 sonic INFO supervisord: syncd 2018-02-12 19:48:13.380687 BF_PLTFM ERROR - Error in select_qsfp port 7
Feb 12 19:48:13.584947 sonic ERR syncd[25]: 2018-02-12 19:48:13.584659 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 7#012
Feb 12 19:48:13.585010 sonic INFO supervisord: syncd 2018-02-12 19:48:13.584659 BF_PLTFM ERROR - Error in unselect_qsfp port 7
Feb 12 19:48:13.788760 sonic ERR syncd[25]: 2018-02-12 19:48:13.788563 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in opening the common PCA9548 for pca9535 2#012
Feb 12 19:48:13.788823 sonic INFO supervisord: syncd 2018-02-12 19:48:13.788563 BF_PLTFM ERROR - Error in opening the common PCA9548 for pca9535 2
Feb 12 19:48:13.992709 sonic ERR syncd[25]: 2018-02-12 19:48:13.992535 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in opening the common PCA9548 for pca9535 3#012
Feb 12 19:48:13.992804 sonic INFO supervisord: syncd 2018-02-12 19:48:13.992535 BF_PLTFM ERROR - Error in opening the common PCA9548 for pca9535 3
Feb 12 19:48:14.196970 sonic ERR syncd[25]: 2018-02-12 19:48:14.196733 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 12#012
Feb 12 19:48:14.197135 sonic INFO supervisord: syncd 2018-02-12 19:48:14.196733 BF_PLTFM ERROR - Error in select_qsfp port 12
Feb 12 19:48:14.400802 sonic ERR syncd[25]: 2018-02-12 19:48:14.400621 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 12#012
Feb 12 19:48:14.400972 sonic INFO supervisord: syncd 2018-02-12 19:48:14.400621 BF_PLTFM ERROR - Error in unselect_qsfp port 12
Feb 12 19:48:14.604934 sonic ERR syncd[25]: 2018-02-12 19:48:14.604667 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 5#012
Feb 12 19:48:14.604986 sonic INFO supervisord: syncd 2018-02-12 19:48:14.604667 BF_PLTFM ERROR - Error in select_qsfp port 5
Feb 12 19:48:14.808717 sonic ERR syncd[25]: 2018-02-12 19:48:14.808529 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 5#012
Feb 12 19:48:14.808838 sonic INFO supervisord: syncd 2018-02-12 19:48:14.808529 BF_PLTFM ERROR - Error in unselect_qsfp port 5
Feb 12 19:48:15.012803 sonic ERR syncd[25]: 2018-02-12 19:48:15.012608 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 8#012
Feb 12 19:48:15.012920 sonic INFO supervisord: syncd 2018-02-12 19:48:15.012608 BF_PLTFM ERROR - Error in select_qsfp port 8
Feb 12 19:48:15.216973 sonic ERR syncd[25]: 2018-02-12 19:48:15.216679 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 8#012
Feb 12 19:48:15.217081 sonic INFO supervisord: syncd 2018-02-12 19:48:15.216679 BF_PLTFM ERROR - Error in unselect_qsfp port 8
Feb 12 19:48:15.420937 sonic ERR syncd[25]: 2018-02-12 19:48:15.420618 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_cpu_pca9535_chn#012
Feb 12 19:48:15.421026 sonic INFO supervisord: syncd 2018-02-12 19:48:15.420618 BF_PLTFM ERROR - Error in select_cpu_pca9535_chn
Feb 12 19:48:15.624905 sonic ERR syncd[25]: 2018-02-12 19:48:15.624648 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_cpu_qsfp#012
Feb 12 19:48:15.624905 sonic ERR syncd[25]: 2018-02-12 19:48:15.624740 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error Communication Failed with Hardware: in scanning qsfps at qsfp_scan_timer_cb:473#012
Feb 12 19:48:15.624975 sonic INFO supervisord: syncd 2018-02-12 19:48:15.624648 BF_PLTFM ERROR - Error in unselect_cpu_qsfp
Feb 12 19:48:15.625398 sonic INFO supervisord: syncd 2018-02-12 19:48:15.624740 BF_PLTFM ERROR - Error Communication Failed with Hardware: in scanning qsfps at qsfp_scan_timer_cb:473
Feb 12 19:48:15.828829 sonic ERR syncd[25]: 2018-02-12 19:48:15.828642 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 12#012
Feb 12 19:48:15.828902 sonic INFO supervisord: syncd 2018-02-12 19:48:15.828642 BF_PLTFM ERROR - Error in select_qsfp port 12
Feb 12 19:48:16.032759 sonic ERR syncd[25]: 2018-02-12 19:48:16.032568 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 12#012
Feb 12 19:48:16.032824 sonic INFO supervisord: syncd 2018-02-12 19:48:16.032568 BF_PLTFM ERROR - Error in unselect_qsfp port 12
Feb 12 19:48:16.236974 sonic ERR syncd[25]: 2018-02-12 19:48:16.236702 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 6#012
Feb 12 19:48:16.236974 sonic INFO supervisord: syncd 2018-02-12 19:48:16.236702 BF_PLTFM ERROR - Error in select_qsfp port 6
Feb 12 19:48:16.440882 sonic ERR syncd[25]: 2018-02-12 19:48:16.440623 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 6#012
Feb 12 19:48:16.441022 sonic INFO supervisord: syncd 2018-02-12 19:48:16.440623 BF_PLTFM ERROR - Error in unselect_qsfp port 6
Feb 12 19:48:16.644852 sonic ERR syncd[25]: 2018-02-12 19:48:16.644595 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in select_qsfp port 9#012
Feb 12 19:48:16.644951 sonic INFO supervisord: syncd 2018-02-12 19:48:16.644595 BF_PLTFM ERROR - Error in select_qsfp port 9
Feb 12 19:48:16.848707 sonic ERR syncd[25]: 2018-02-12 19:48:16.848527 ERROR  (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_qsfp port 9#012
Feb 12 19:48:16.848812 sonic INFO supervisord: syncd 2018-02-12 19:48:16.848527 BF_PLTFM ERROR - Error in unselect_qsfp port 9

**Comment by PJHsieh** [comment]
@akokhan

Can you help check this issue ?

**Comment by akokhan** [comment]
What's the cable/qsfp type that you are using? Thanks.

**Comment by PJHsieh** [comment]
> What's the cable/qsfp type that you are using? Thanks.

Hi, akokhan,
The cable I used is a DAC cable.
The Brand: Edge-core.
The Model Name: ET7402-100DAC-1M

It is a 100G QSFP28 DAC Cable.

**Comment by PJHsieh** [comment]
Hi, akokhan,

The syncd repeat print the following messages.
Please note that the messages are printed even if no SFP inserted.

Feb 12 19:48:12.358860 sonic ERR syncd[25]: 2018-02-12 19:48:12.358607 ERROR (BF_PLTFM:(file=null):(func=null):0) - Error in unselect_cpu_qsfp#012
Feb 12 19:48:12.358860 sonic ERR syncd[25]: 2018-02-12 19:48:12.358709 ERROR (BF_PLTFM:(file=null):(func=null):0) - Error Communication Failed with Hardware: in scanning qsfps at qsfp_scan_timer_cb:473#012
......

**Comment by xinliu-seattle** [comment]
@PJHsieh : 1)please join the triage meeting to have your issue discussed. 2) from Syncd msg, it seems an ASIC issue.

**Comment by PJHsieh** [comment]
@xinliu-seattle :
About 1): When will the triage meeting and how shall I join ?
About 2: ASIC issue, do you mean HW issue ?

**Comment by PJHsieh** [comment]
From internal information:
This shall be HW (chip)issue. Therefore, set this issue to done.

**Comment by PJHsieh** [comment]
From internal information:
This issue shall be HW (chip)issue. Therefore, close this issue..

**Comment by ZQ-XPY** [comment]
how to solve this issue?
