### ISSUE TITLE
Docker container installed but not started/running.

### ISSUE THREAD

**Issue by Eric-Zaluzec-Vertiv** [Azure/sonic-buildimage#4805]
**Description**
Building the SONiC broadcom image for an EdgeCore switch. After adding the docker metadata recipe to the platform's makefiles, I see that my docker container is built and installed with the sonic image. After updating my hardware with new sonic image; I run a docker images to verify my docker container is present. However, running docker ps shows my container was not started like the other sonic containers. I can manually start it but the container needs to run on system startup.

I'm unable to enable a sytemd service or run a docker container on system boot. 

I've posted questions on the [sonic google group forum](https://groups.google.com/forum/#!forum/sonicproject) with no luck. 

I'm unable to join the slack chat workspace discussion because I do not have a domain address (@microsoft.com, @mellanox.com, @canonical.com, @ubuntu.com, etc...).

**Steps to reproduce the issue:**
1. Add docker recipe for simple docker image target group
2. Build sonic image
3. Run image on target hardware

**Describe the results you received:**
Running docker ps shows that my container was not started.

**Describe the results you expected:**
Running docker ps shows my container is running.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of  show version:**

 ```
admin@sonic:~$ show version

SONiC Software Version: SONiC.ez-vertiv.0-dirty-20200616.145807
Distribution: Debian 10.4
Kernel: 4.19.0-6-amd64
Build commit: 8f521451
Build date: Tue Jun 16 19:26:34 UTC 2020
Built by: ezaluzec@hsv-redcard

Platform: x86_64-accton_as4630_54pe-r0
HwSKU: Accton-AS4630-54PE
ASIC: broadcom
Serial Number: 463054PE1950038
Uptime: 08:12:10 up 1 day, 22:00,  1 user,  load average: 0.02, 0.14, 0.18

```

**Comment by fillmorechen0928** [comment]
I don't know if SONIC is allowed to add proprietary docker container? Have you checked this on other platform?

**Comment by Eric-Zaluzec-Vertiv** [comment]
Thanks for the response @fillmorechen0928. The docker container is not proprietary, but open source. It is just an Alpine Linux container.

The sonic-buildimage has a buildsystem [README](https://github.com/Azure/sonic-buildimage/blob/master/README.buildsystem.md) where it covers how users can add their custom source code and containers to the sonic image. This functionality seems to be a valid use case.

I've verified that this issue is not platform specific.

**Comment by xinliu-seattle** [comment]
1) please join the triage meeting to describe your issue; 2) please check how other dockers are started, particular the makefile.
