### ISSUE TITLE
ERR syslog about snmp-subagent [ax_interface] When the device is running

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#4877]
**Description**

ERR syslog about snmp-subagent [ax_interface] When the device is running

**Steps to reproduce the issue:**
1.Upgrade the device to master,Check syslog, whether there is abnormal log

**Describe the results you received:**

snmp print ERROR log as follows:

root@switch2:/home/admin# 
root@switch2:/home/admin# zgrep "ERR"  /var/log/syslog*   | grep  "snmp"
/var/log/syslog:Jul  1 15:10:48.234798 switch2 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 40, in reinit_data#012    self.update_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 49, in update_data#012    for sai_id in self.if_id_map}#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py", line 49, in <dictcomp>#012    for sai_id in self.if_id_map}#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/dbconnector.py", line 308, in get_all#012    return super(SonicV2Connector, self).get_all(db_id, _hash, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped#012    ret_data = f(inst, db_id, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 303, in get_all#012    raise UnavailableDataError(message, _hash)#012swsssdk.exceptions.UnavailableDataError: Key 'b'COUNTERS:oid:0x1000000000002'' unavailable in database '2'
/var/log/syslog:Jul  1 15:11:48.361486 switch2 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 46, in start#012    self.update_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 192, in update_data#012    for sai_id in self.if_id_map}#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 192, in <dictcomp>#012    for sai_id in self.if_id_map}#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/dbconnector.py", line 308, in get_all#012    return super(SonicV2Connector, self).get_all(db_id, _hash, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 38, in wrapped#012    ret_data = f(inst, db_id, *args, **kwargs)#012  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 303, in get_all#012    raise UnavailableDataError(message, _hash)#012swsssdk.exceptions.UnavailableDataError: Key 'b'COUNTERS:oid:0x1000000000002'' unavailable in database '2'
/

**Describe the results you expected:**
snmp no print ERROR log

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
admin@switch2:~$ show version 

SONiC Software Version: SONiC.master.277-767bc5c8
Distribution: Debian 10.3
Kernel: 4.19.0-6-amd64
Build commit: 767bc5c8
Build date: Wed May  6 20:38:05 UTC 2020
Built by: johnar@jenkins-worker-4

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
/usr/bin/decode-syseeprom : ERROR : [Errno 2] No such file or directory: '/sys/bus/i2c/devices/2-0057/eeprom'
Serial Number: 
Uptime: 15:53:59 up 48 min,  1 user,  load average: 0.63, 0.61, 0.63

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-sonic-mgmt-framework   latest                a01275dc9a1b        456MB
docker-sonic-mgmt-framework   master.277-767bc5c8   a01275dc9a1b        456MB
docker-teamd                  latest                d5a58806d489        309MB
docker-teamd                  master.277-767bc5c8   d5a58806d489        309MB
docker-syncd-brcm             latest                2c256a6adc95        436MB
docker-syncd-brcm             master.277-767bc5c8   2c256a6adc95        436MB
docker-sonic-telemetry        latest                db9b46db5bc3        351MB
docker-sonic-telemetry        master.277-767bc5c8   db9b46db5bc3        351MB
docker-snmp-sv2               latest                a9f389c7a060        345MB
docker-snmp-sv2               master.277-767bc5c8   a9f389c7a060        345MB
docker-sflow                  latest                c1641844eb47        309MB
docker-sflow                  master.277-767bc5c8   c1641844eb47        309MB
docker-router-advertiser      latest                1fe2f8f31257        288MB
docker-router-advertiser      master.277-767bc5c8   1fe2f8f31257        288MB
docker-platform-monitor       latest                7cda00b77323        352MB
docker-platform-monitor       master.277-767bc5c8   7cda00b77323        352MB
docker-orchagent              latest                d4290290cbe9        327MB
docker-orchagent              master.277-767bc5c8   d4290290cbe9        327MB
docker-nat                    latest                d8027a4e1b26        310MB
docker-nat                    master.277-767bc5c8   d8027a4e1b26        310MB
docker-lldp-sv2               latest                95fc8457ec1e        306MB
docker-lldp-sv2               master.277-767bc5c8   95fc8457ec1e        306MB
docker-fpm-frr                latest                036e21048074        329MB
docker-fpm-frr                master.277-767bc5c8   036e21048074        329MB
docker-dhcp-relay             latest                9ce7e9f68bcd        298MB
docker-dhcp-relay             master.277-767bc5c8   9ce7e9f68bcd        298MB
docker-database               latest                19193db6f7d4        288MB
docker-database               master.277-767bc5c8   19193db6f7d4        288MB

    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
x86_64-ruijie_b6510-48vs8cq-r0 is not a supported platform.

**Comment by tim-rj** [comment]
we will integrate our platform & device as soon as possible.

**Comment by lguohan** [comment]
please provide tech support file.

**Comment by tim-rj** [comment]
This issue should has been fixed by others laster Monday.

**Comment by rlhui** [comment]
@tim-rj, please close this issue if you confirmed. Thanks.

**Comment by tim-rj** [comment]
It's already fixed, below codes is a evidence，db.keys has changed to db_conn.keys, close this one：

    def dbs_get_vlan_id_from_bvid(dbs, bvid):
        for db_conn in Namespace.get_non_host_dbs(dbs):
            db_conn.connect('ASIC_DB')
            vlan_obj = db_conn.keys('ASIC_DB', "ASIC_STATE:SAI_OBJECT_TYPE_VLAN:" + bvid)
