### ISSUE TITLE
Neighbors learned from portchannel, when neighbors are offline for more than 5 minutes, ARP aging is abnormal

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#4879]
**Description**

Neighbors learned from portchannel, when neighbors are offline for more than 5 minutes, ARP aging is abnormal

**Steps to reproduce the issue:**
1.config vlan
2.config portchannel,add into vlan member
3.add a port into portchannel
4.learn a Neighbor from portchannel
5.neighbors are offline,then View arp entries afer 5 minutes

**Describe the results you received:**

snmp print ERROR log as follows:

when neighbors are offline for more than 5 minutes, ARP aging is abnormal

```
root@switch2:/home/admin# show arp
Address      MacAddress         Iface         Vlan
-----------  -----------------  ------------  ------
50.5.1.0     80:05:88:c9:17:01  Ethernet52    -
150.1.1.2    58:69:6c:83:56:86  PortChannel1  3
172.28.57.1  58:69:6c:dc:e8:56  eth0          -
Total number of entries 3 
root@switch2:/home/admin# ping 150.1.1.2
PING 150.1.1.2 (150.1.1.2) 56(84) bytes of data.
^C
--- 150.1.1.2 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 39ms

root@switch2:/home/admin# show arp      
Address        MacAddress         Iface       Vlan
-------------  -----------------  ----------  ------
50.5.1.0       80:05:88:c9:17:01  Ethernet52  -
150.1.1.2      58:69:6c:83:56:86  -           3           -----is wrong
172.28.57.1  58:69:6c:dc:e8:56  eth0          -
Total number of entries 3
root@switch2:/home/admin# ping 150.1.1.2
PING 150.1.1.2 (150.1.1.2) 56(84) bytes of data.
^C
```
**Describe the results you expected:**

Arp entries are normally aging ,as follows:
```
root@switch2:/home/admin# show arp
Address      MacAddress         Iface         Vlan
-----------  -----------------  ------------  ------
50.5.1.0     80:05:88:c9:17:01  Ethernet52    -
172.28.57.1  58:69:6c:dc:e8:56  eth0          -
Total number of entries2 
```
**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
admin@switch2:~$ show version 

SONiC Software Version: SONiC.master.277-767bc5c8
Distribution: Debian 10.3
Kernel: 4.19.0-6-amd64
Build commit: 767bc5c8
Build date: Wed May  6 20:38:05 UTC 2020
Built by: johnar@jenkins-worker-4

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
/usr/bin/decode-syseeprom : ERROR : [Errno 2] No such file or directory: '/sys/bus/i2c/devices/2-0057/eeprom'
Serial Number: 
Uptime: 15:53:59 up 48 min,  1 user,  load average: 0.63, 0.61, 0.63

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-sonic-mgmt-framework   latest                a01275dc9a1b        456MB
docker-sonic-mgmt-framework   master.277-767bc5c8   a01275dc9a1b        456MB
docker-teamd                  latest                d5a58806d489        309MB
docker-teamd                  master.277-767bc5c8   d5a58806d489        309MB
docker-syncd-brcm             latest                2c256a6adc95        436MB
docker-syncd-brcm             master.277-767bc5c8   2c256a6adc95        436MB
docker-sonic-telemetry        latest                db9b46db5bc3        351MB
docker-sonic-telemetry        master.277-767bc5c8   db9b46db5bc3        351MB
docker-snmp-sv2               latest                a9f389c7a060        345MB
docker-snmp-sv2               master.277-767bc5c8   a9f389c7a060        345MB
docker-sflow                  latest                c1641844eb47        309MB
docker-sflow                  master.277-767bc5c8   c1641844eb47        309MB
docker-router-advertiser      latest                1fe2f8f31257        288MB
docker-router-advertiser      master.277-767bc5c8   1fe2f8f31257        288MB
docker-platform-monitor       latest                7cda00b77323        352MB
docker-platform-monitor       master.277-767bc5c8   7cda00b77323        352MB
docker-orchagent              latest                d4290290cbe9        327MB
docker-orchagent              master.277-767bc5c8   d4290290cbe9        327MB
docker-nat                    latest                d8027a4e1b26        310MB
docker-nat                    master.277-767bc5c8   d8027a4e1b26        310MB
docker-lldp-sv2               latest                95fc8457ec1e        306MB
docker-lldp-sv2               master.277-767bc5c8   95fc8457ec1e        306MB
docker-fpm-frr                latest                036e21048074        329MB
docker-fpm-frr                master.277-767bc5c8   036e21048074        329MB
docker-dhcp-relay             latest                9ce7e9f68bcd        298MB
docker-dhcp-relay             master.277-767bc5c8   9ce7e9f68bcd        298MB
docker-database               latest                19193db6f7d4        288MB
docker-database               master.277-767bc5c8   19193db6f7d4        288MB

    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by tim-rj** [comment]
Additional information：
root@switch2:/home/admin# show arp      
Address        MacAddress         Iface       Vlan
-------------  -----------------  ----------  ------
50.5.1.0       80:05:88:c9:17:01  Ethernet52  -
150.1.1.2      58:69:6c:83:56:86  -           3
Total number of entries 2
root@switch2:/home/admin# ping 150.1.1.2
PING 150.1.1.2 (150.1.1.2) 56(84) bytes of data.
^C
--- 150.1.1.2 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 64ms

root@switch2:/home/admin#  bcmcmd "l3 l3table show" | wc -l
6
root@switch2:/home/admin#  bcmcmd "l3 l3table show" 
l3 l3table show
Unit 0, free L3 table entries: 49148
Entry VRF IP address       Mac Address           INTF MOD PORT    CLASS HIT    H/W Index
1     0    50.5.1.0         00:00:00:00:00:00  100006    0    0         0 y      17484
2     0    150.1.1.2        00:00:00:00:00:00  100002    0    0         0 y      47844
drivshell>

**Comment by lguohan** [comment]
again, it is difficult to debug this platform since it is not supported. the platform driver is not checked-in, it is not in the device list. there is no show tech provided. we do not know if you have configured the box correctly.

**Comment by tim-rj** [comment]
ok, we will integrate our platform & device as soon as possible.

**Comment by lguohan** [comment]
also can you provide tech support

**Comment by tim-rj** [comment]
[sonic_dump_switch2_20200714_153357.tar.gz](https://github.com/Azure/sonic-buildimage/files/4917270/sonic_dump_switch2_20200714_153357.tar.gz)

**Comment by tim-rj** [comment]
append one info: arp -n show the same perfomance, so i think it is a kernel issue?

**Comment by yxieca** [comment]
@tim-rj  Can you clarify your expectation? Is your expectation that the kernel arp entry being aged out at the same time when FDB entry aged out?

Kernel ARP entry aging and FDB entry aging are currently 2 independent mechanisms.

**Comment by tim-rj** [comment]
> 
> 
> @tim-rj Can you clarify your expectation? Is your expectation that the kernel arp entry being aged out at the same time when FDB entry aged out?
> 
> Kernel ARP entry aging and FDB entry aging are currently 2 independent mechanisms.

No, I mean arp entry should be removed(age) after a few minutes(maybe 5 or longer) when neighbor's ip address is reoved.

**Comment by prsunny** [comment]
@tim-rj, ARP aging is dependent on multiple factors. In case of Sonic, kernel manages the ARP and the gc threshold values are set to > 1k which means, if the number of total number of entries doesn't exceed those limits, there may not be any garbage collection. Again, it may not be a case only for portchannel, you may observe it with regular physical interface as well.
