### ISSUE TITLE
docker-sonic-mgmt.gz build failed on 201911 branch (head 2020/Jun/28)

### ISSUE THREAD

**Issue by alanC-Cameo** [Azure/sonic-buildimage#4888]
**Description**
"make target/docker-sonic-mgmt.gz" failed on 201911 branch (commit d32beffed06f13125d7af1d6fd339253e0ea0c7a, 2020/Jun/28; HEAD -> 201911, origin/201911) 

**Steps to reproduce the issue:**
1. git clone https://github.com/Azure/sonic-buildimage.git
2. git checkout -b 201911 origin/201911
3. make init
4. make configure PLATFORM=generic
5. make all
6. make target/docker-sonic-mgmt.gz <- failed here

**Describe the results you received:**
Step 12/38 : RUN pip install pytest-ansible==2.2.2
 ---> Running in 8d26d8beba70
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pytest-ansible==2.2.2
  Downloading pytest-ansible-2.2.2.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-OLv9ZG/pytest-ansible/setup.py'"'"'; __file__='"'"'/tmp/pip-install-OLv9ZG/pytest-ansible/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-P8mvOD
         cwd: /tmp/pip-install-OLv9ZG/pytest-ansible/
    Complete output (49 lines):
    Unable to import pypandoc - No module named pypandoc

    Installed /tmp/pip-install-OLv9ZG/pytest-ansible/.eggs/setuptools_markdown-0.4.1-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.5
    Downloading https://files.pythonhosted.org/packages/d6/b7/5050dc1769c8a93d3ec7c4bd55be161991c94b8b235f88bf7c764449e708/pypandoc-1.5.tar.gz#sha256=14a49977ab1fbc9b14ef3087dcb101f336851837fca55ca79cf33846cc4976ff
    Processing pypandoc-1.5.tar.gz
    Writing /tmp/easy_install-R6fcvg/pypandoc-1.5/setup.cfg
    Running pypandoc-1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-R6fcvg/pypandoc-1.5/egg-dist-tmp-8q8hI9
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    creating /tmp/pip-install-OLv9ZG/pytest-ansible/.eggs/pypandoc-1.5-py2.7.egg
    Extracting pypandoc-1.5-py2.7.egg to /tmp/pip-install-OLv9ZG/pytest-ansible/.eggs

    Installed /tmp/pip-install-OLv9ZG/pytest-ansible/.eggs/pypandoc-1.5-py2.7.egg
    Searching for wheel>=0.25.0
    Reading https://pypi.python.org/simple/wheel/
    Best match: wheel 0.34.2
    Downloading https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz#sha256=8788e9155fe14f54164c1b9eb0a319d98ef02c160725587ad60f14ddc57b6f96
    Processing wheel-0.34.2.tar.gz
    Writing /tmp/easy_install-1JaTVW/wheel-0.34.2/setup.cfg
    Running wheel-0.34.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1JaTVW/wheel-0.34.2/egg-dist-tmp-uTQR2J
    warning: no files found matching '*.dynlib' under directory 'tests'
    no previously-included directories found matching 'tests/testdata/*/build'
    no previously-included directories found matching 'tests/testdata/*/dist'
    no previously-included directories found matching 'tests/testdata/*/*.egg-info'
    'tests/testdata/unicode.dist/unicodedist/åäö_日本語.py' not ANSI_X3.4-1968 encodable -- skipping
    warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

    zip_safe flag not set; analyzing archive contents...
    Moving UNKNOWN-0.0.0-py2.7.egg to /tmp/pip-install-OLv9ZG/pytest-ansible/.eggs

    Installed /tmp/pip-install-OLv9ZG/pytest-ansible/.eggs/UNKNOWN-0.0.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-OLv9ZG/pytest-ansible/setup.py", line 141, in <module>
        'Programming Language :: Python :: 3.6',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'wheel>=0.25.0' distribution was not found and is required by pypandoc
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install pytest-ansible==2.2.2' returned a non-zero code: 1
[  FAIL LOG END  ] [ target/docker-sonic-mgmt.gz ]
slave.mk:538: recipe for target 'target/docker-sonic-mgmt.gz' failed
make: *** [target/docker-sonic-mgmt.gz] Error 1
Makefile.work:201: recipe for target 'target/docker-sonic-mgmt.gz' failed
make[1]: *** [target/docker-sonic-mgmt.gz] Error 2
make[1]: Leaving directory '/home/alan_chen/code/sonic-buildimage'
Makefile:6: recipe for target 'target/docker-sonic-mgmt.gz' failed
make: *** [target/docker-sonic-mgmt.gz] Error 2

**Additional information you deem important (e.g. issue happens only occasionally):**
alan_chen@cameo-ws:~/code/sonic-buildimage$ uname -a
Linux cameo-ws 5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yxieca** [comment]
There are some changes in master branch that are missing from 201911 branch. Rita will cherry-pick them into 201911 branch and address the build issue. Meanwhile, please use sonic-mgmt docker built from the master branch.

**Comment by alanC-Cameo** [comment]
well noted and tks for your great support.

**Comment by xinliu-seattle** [comment]
Close this as it is fixed.

**Comment by yxieca** [comment]
This commit: https://github.com/daall/sonic-buildimage/commit/fb535bb2ba871bf6eef8a46081fb63b953578107 fixed the issue.

**Comment by alanC-Cameo** [comment]
after merging the fix (add this line "RUN pip install wheel==0.33.6"), the another error (UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)) reported when installing pytest-ansible==2.2.2 as below.

==========================================
Step 12/39 : RUN pip install --timeout=999 wheel==0.33.6
 ---> Running in dbd433083062
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting wheel==0.33.6
  Downloading wheel-0.33.6-py2.py3-none-any.whl (21 kB)
Installing collected packages: wheel
Successfully installed wheel-0.33.6
Removing intermediate container dbd433083062
 ---> 072af3918efa
Step 13/39 : RUN pip install --timeout=999 pytest-ansible==2.2.2
 ---> Running in 068ae81981f0
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pytest-ansible==2.2.2
  Downloading pytest-ansible-2.2.2.tar.gz (16 kB)
Collecting ansible
  Downloading ansible-2.9.10.tar.gz (14.2 MB)
Collecting pytest
  Downloading pytest-4.6.11-py2.py3-none-any.whl (231 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python2.7/dist-packages (from ansible->pytest-ansible==2.2.2) (2.7.2)
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages (from ansible->pytest-ansible==2.2.2) (2.9.2)
Collecting atomicwrites>=1.0
  Downloading atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting attrs>=17.4.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from pytest->pytest-ansible==2.2.2) (1.15.0)
Collecting funcsigs>=1.0; python_version < "3.0"
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python2.7/dist-packages (from pytest->pytest-ansible==2.2.2) (0.2.5)
Collecting more-itertools<6.0.0,>=4.0.0; python_version <= "2.7"
  Downloading more_itertools-5.0.0-py2-none-any.whl (52 kB)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in /usr/local/lib/python2.7/dist-packages (from pytest->pytest-ansible==2.2.2) (2.3.5)
Collecting py>=1.5.0
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Requirement already satisfied: markupsafe in /usr/local/lib/python2.7/dist-packages (from jinja2->ansible->pytest-ansible==2.2.2) (1.1.1)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible->pytest-ansible==2.2.2) (1.10.0)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible->pytest-ansible==2.2.2) (1.0.23)
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible->pytest-ansible==2.2.2) (1.1.10)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: contextlib2; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest->pytest-ansible==2.2.2) (0.6.0.post1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest->pytest-ansible==2.2.2) (1.2.0)
Collecting configparser>=3.5; python_version < "3"
  Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: backports.functools-lru-cache>=1.2.1; python_version < "3.2" in /usr/local/lib/python2.7/dist-packages (from wcwidth->pytest->pytest-ansible==2.2.2) (1.6.1)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest->pytest-ansible==2.2.2) (1.10.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography->ansible->pytest-ansible==2.2.2) (2.20)
Building wheels for collected packages: pytest-ansible, ansible, PyYAML
  Building wheel for pytest-ansible (setup.py): started
  Building wheel for pytest-ansible (setup.py): finished with status 'done'
  Created wheel for pytest-ansible: filename=pytest_ansible-2.2.2-py2-none-any.whl size=20558 sha256=9f5ea0ab1aa9ae4d89c81344459e8b05f5eeebbc904bb449a9644340f9044e2d
  Stored in directory: /root/.cache/pip/wheels/f1/1c/09/1fd9c073a9a514b007540a7953277333df144f6c55cc2c65ff
  Building wheel for ansible (setup.py): started
  Building wheel for ansible (setup.py): finished with status 'done'
  Created wheel for ansible: filename=ansible-2.9.10-py2-none-any.whl size=16174794 sha256=fcc97b9c77815786613c304dbe297a3f690c4f506fb20750532b3d1102487ff3
  Stored in directory: /root/.cache/pip/wheels/7e/c6/e0/9e4a97449fba30f35604f3cf28d221d82333ad773e2b4fa8c1
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp27-cp27mu-linux_x86_64.whl size=45604 sha256=0535b96d81a2efc422e628851f368ad1535ea1009aeef99e0adb3f1749c98b8c
  Stored in directory: /root/.cache/pip/wheels/d1/d5/a0/3c27cdc8b0209c5fc1385afeee936cf8a71e13d885388b4be2
Successfully built pytest-ansible ansible PyYAML
Installing collected packages: PyYAML, ansible, atomicwrites, configparser, importlib-metadata, pluggy, pyparsing, packaging, attrs, funcsigs, more-itertools, py, pytest, pytest-ansible
Successfully installed PyYAML-5.3.1 ansible-2.9.10 atomicwrites-1.4.0 attrs-19.3.0 configparser-4.0.2 funcsigs-1.0.2 importlib-metadata-1.7.0 more-itertools-5.0.0 packaging-20.4 pluggy-0.13.1 py-1.9.0 pyparsing-2.4.7 pytest-4.6.11 pytest-ansible-2.2.2
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==20.2b1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_internal/cli/main.py", line 75, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_internal/cli/base_command.py", line 114, in main
    return self._main(args)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_internal/cli/command_context.py", line 28, in main_context
    yield
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 479, in __exit__
    _reraise_with_existing_context(exc_details)
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 353, in _reraise_with_existing_context
    exec("raise exc_type, exc_value, exc_tb")
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 468, in __exit__
    if cb(*exc_details):
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 396, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_internal/utils/temp_dir.py", line 46, in global_tempdir_manager
    _tempdir_manager = old_tempdir_manager
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 479, in __exit__
    _reraise_with_existing_context(exc_details)
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 353, in _reraise_with_existing_context
    exec("raise exc_type, exc_value, exc_tb")
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 468, in __exit__
    if cb(*exc_details):
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/contextlib2.py", line 396, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_internal/utils/temp_dir.py", line 175, in __exit__
    self.cleanup()
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_internal/utils/temp_dir.py", line 199, in cleanup
    rmtree(ensure_text(self._path))
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_internal/utils/misc.py", line 136, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 241, in rmtree
    fullname = os.path.join(path, name)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
The command '/bin/sh -c pip install --timeout=999 pytest-ansible==2.2.2' returned a non-zero code: 1
[  FAIL LOG END  ] [ target/docker-sonic-mgmt.gz ]
slave.mk:538: recipe for target 'target/docker-sonic-mgmt.gz' failed
make: *** [target/docker-sonic-mgmt.gz] Error 1
Makefile.work:201: recipe for target 'target/docker-sonic-mgmt.gz' failed
make[1]: *** [target/docker-sonic-mgmt.gz] Error 2
make[1]: Leaving directory '/home/alan_chen/code/sonic-buildimage'
Makefile:6: recipe for target 'target/docker-sonic-mgmt.gz' failed
make: *** [target/docker-sonic-mgmt.gz] Error 2
