### ISSUE TITLE
'make clean' always failed

### ISSUE THREAD

**Issue by iMasaruOki** [Azure/sonic-buildimage#4898]
**Description**

'make clean' are always failed on master branch.
201911 branch has no problem.

**Steps to reproduce the issue:**
1. `make init`
2. `make configure PLATFORM=broadcom` (`PLATFORM=vs` is also affected)
3. `make clean`

**Describe the results you received:**
```
make: *** No rule to make target 'target/debs/buster/redis-tools_5.0.3-3~bpo9+2_amd64.deb-clean', needed by 'target/debs/buster/redis-tools-dbgsym_5.0.3-3~bpo9+2_amd64.deb-clean'.  Stop.
make[1]: *** [Makefile.work:224: clean] Error 2
```

**Describe the results you expected:**

no error.

**Additional information you deem important (e.g. issue happens only occasionally):**

found at commit 20698aa57b

**Comment by lguohan** [comment]
@qiluo-msft, is this due to your redis server upgrade?

**Comment by qiluo-msft** [comment]
@iMasaruOki Thanks for the bug report!
Could you test this PR work for you?
