### ISSUE TITLE
orchagent crash observed intermittently on latest SONIC images

### ISSUE THREAD

**Issue by BaluAlluru** [Azure/sonic-buildimage#4907]
**Description**
orchagent crash observed few times on SONIC latest image.
No Optics are connected to front panel ports.

**Steps to reproduce the issue:**
1. Load the SONIC latest image (tested on jenkins 333 and 338 image)
2. orchagent crash observed
3. show interfaces status output is NULL

**Describe the results you received:**
Orchagent crashed and "show interfaces status" output is NULL.
Observed this issue 3-4 times by rebooting the box.

**Describe the results you expected:**
All processes should come up and "show interfaces status" should show valid data.

**Additional information you deem important (e.g. issue happens only occasionally):**

root@sonic:/home/admin# show version

SONiC Software Version: SONiC.master.333-2e0aa4f1
Distribution: Debian 10.4
Kernel: 4.19.0-6-2-amd64
Build commit: 2e0aa4f1
Build date: Thu Jul  2 17:52:12 UTC 2020
Built by: johnar@jenkins-worker-4

**Comment by BaluAlluru** [comment]
wanted to take "generate dump" on fresh slate. uninstalled the image and reinstalled the image. didn't observe crash after installing the image again.
couldn't collect the generate dump when the crash was observed.
will attach "generate dump" to this issue, when crash is observed.

**Comment by ciju-juniper** [comment]
Issue is seen on the latest master.338 image. Also observing a crash in the bcm_knet driver.

Here is the dmesg output: 
[dmesg_338.txt](https://github.com/Azure/sonic-buildimage/files/4884049/dmesg_338.txt)

Here is the dump generated: 
[sonic_dump_sonic_20190214_102645.tar.gz](https://github.com/Azure/sonic-buildimage/files/4884060/sonic_dump_sonic_20190214_102645.tar.gz)

Here is the core file generated for Orchagent: 
[orchagent.1550139156.50.core.gz](https://github.com/Azure/sonic-buildimage/files/4884068/orchagent.1550139156.50.core.gz)

**Comment by ciju-juniper** [comment]
@smaheshm @lguohan @rlhui Please have a look. Seems like an issue with broadcom components.

**Comment by xinliu-seattle** [comment]
will need brcm to take a look.

**Comment by smaheshm** [comment]
@ciju-juniper How is orchagent crash related to the crash in bcm_knet driver. Do you know if orchagent crash is a result of bcm_knet crash?

Also saw this message in log. Did you get a chance to look at it:
```
Feb 14 10:12:36.739977 sonic NOTICE syncd#syncd: :- processOidCreate: creating switch number 1
Feb 14 10:12:36.747355 sonic INFO syncd#supervisord: syncd Platform configuration file "/usr/share/sonic/hwsku/th2-qfx5210-64x100G.config.bcm" is used#015
Feb 14 10:12:36.747355 sonic INFO syncd#supervisord: syncd Platform Boot flags: 0x0#015
Feb 14 10:12:36.756279 sonic INFO bgp#bgpcfgd: Routing policy for peer 'ARISTA16T2' was updated
Feb 14 10:12:36.816509 sonic INFO syncd#syncd: [none] board_id_default:572 Failed to obtain switch ID.
Feb 14 10:12:36.821019 sonic INFO syncd#syncd: message repeated 11 times: [ [none] board_id_default:572 Failed to obtain switch ID.]
Feb 14 10:12:36.821019 sonic CRIT syncd#syncd: [none] platformInit:1946 No attached units.
Feb 14 10:12:36.821019 sonic CRIT syncd#syncd: [none] sai_driver_init:207 Error initializing driver, rc = -1.
Feb 14 10:12:36.821636 sonic CRIT syncd#syncd: [none] brcm_sai_create_switch:515 initializing SDK failed with error Operation failed (0xfffffff5).
Feb 14 10:12:36.821636 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_INIT_SWITCH: true
Feb 14 10:12:36.821636 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_FDB_EVENT_NOTIFY: 0x556778469350
Feb 14 10:12:36.821636 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_PORT_STATE_CHANGE_NOTIFY: 0x556778469360
Feb 14 10:12:36.821636 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_SWITCH_SHUTDOWN_REQUEST_NOTIFY: 0x556778469370
Feb 14 10:12:36.821667 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_SRC_MAC_ADDRESS: 78:4F:9B:65:6D:88
Feb 14 10:12:36.821667 sonic ERR syncd#syncd: :- processQuadEvent: failed to execute api: create, key: SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000, status: SAI_STATUS_FAILURE
Feb 14 10:12:36.821836 sonic ERR syncd#syncd: :- run: Runtime error: :- processQuadEvent: failed to execute api: create, key: SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000, status: SAI_STATUS_FAILURE
Feb 14 10:12:36.821836 sonic NOTICE syncd#syncd: :- sendShutdownRequest: sending switch_shutdown_request notification to OA for switch: oid:0x0
Feb 14 10:12:36.821836 sonic NOTICE syncd#syncd: :- sendShutdownRequestAfterException: notification send successfull
Feb 14 10:12:36.823462 sonic INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::invalid_argument'
Feb 14 10:12:36.823462 sonic INFO swss#supervisord: orchagent   what():  parse error - unexpected 'o'
```

**Comment by ciju-juniper** [comment]
@smaheshm I don't know if the bcm_knet driver and orchagent crash are related or not. During the startup orchgent crashed and also the bcm_knet driver crashed.

We started observing this as a regression recently. Not sure why syncd is reporting errors. We haven't changed anything on the BCM configuration.

**Comment by smaheshm** [comment]
@ciju-juniper FYI there was a kernel update on July 6th. I know @gechiang also found some issues related to kernel upgrade. @gechiang Have you seen any orchagent related crash in recent (past week) images. 

I think the kernel crash and orchagent crash are unrelated. You mentioned it's seen intermittently, are you referring to orchagent crash?

Orchagent is throwing an exception:

Feb 14 10:12:36.823462 sonic INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::invalid_argument'
Feb 14 10:12:36.823462 sonic INFO swss#supervisord: orchagent   what():  parse error - unexpected 'o'

Can you add the stack trace next time you see a crash. Will save us some time.

**Comment by gechiang** [comment]
The Kernel issue that I reported was seen on debug enabled image.  I did not observe any Orchagent crash in that scenario.
BTW, any time the Syncd reports error back to Orchagent it will cause Orchagent to crash.  This is known behavior and there are plans to address Orchagent to not crash.  So the fact that Syncd is having problem the Orchagent crash is expected.  I think the focus should be to look into why Syncd is having problem.

**Comment by smaheshm** [comment]
@ciju-juniper Based on the reply from Gen Hwa, lets focus on syncd errors. To understand syncd error better, can you confirm if both syncd error and kernel crash are always seen together. 

use ' dmesg -T', with timestamps it becomes easier to compare the two events.

**Comment by smaheshm** [comment]
@ciju-juniper @BaluAlluru Let me know if this issue still exists.

**Comment by ciju-juniper** [comment]
@smaheshm Haven't seen this issue yet in the later images.

**Comment by smaheshm** [comment]
Thank you for the update. Will close this.

**Comment by smaheshm** [comment]
Closing as issue is not seeing in later builds.
