### ISSUE TITLE
[ACL BUG] A regular python trace error print when config acl table

### ISSUE THREAD

**Issue by zhanggongc** [Azure/sonic-buildimage#4934]
I describe this problem by following screenshot:
![image](https://user-images.githubusercontent.com/58503468/87034468-7371d680-c21a-11ea-97bd-2e94d3d76a3e.png)

"config acl add table -p Ethernet22 ACL_MIRROR mirror"
I input this command repeatly, also show acl table 
it will report error regularly..

**Comment by zhanggongc** [comment]
root@7393ec979b0a:/# sudo config acl add table  ACL_MIRROR mirror             
root@7393ec979b0a:/# show acl table
Name        Type    Binding      Description    Stage
----------  ------  -----------  -------------  -------
ACL_MIRROR  mirror  Ethernet0    ACL_MIRROR     ingress
                    Ethernet4
                    Ethernet8
                    Ethernet12
                    Ethernet16
                    Ethernet20
                    Ethernet24
                    Ethernet28
                    Ethernet32
                    Ethernet36
                    Ethernet40
                    Ethernet44
                    Ethernet48
                    Ethernet52
                    Ethernet56
                    Ethernet60
                    Ethernet64
                    Ethernet68
                    Ethernet72
                    Ethernet76
                    Ethernet80
                    Ethernet84
                    Ethernet88
                    Ethernet92
                    Ethernet96
                    Ethernet100
                    Ethernet104
                    Ethernet108
                    Ethernet112
                    Ethernet116
                    Ethernet120
                    Ethernet124
root@7393ec979b0a:/# 
root@7393ec979b0a:/# 
root@7393ec979b0a:/# sudo config acl add table  ACL_MIRROR mirror
root@7393ec979b0a:/# 
root@7393ec979b0a:/# show acl table
Traceback (most recent call last):
  File "/usr/bin/acl-loader", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 770, in table
    acl_loader.show_table(table_name)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 617, in show_table
    if not val["ports"]:
KeyError: 'ports'
root@7393ec979b0a:/# 
root@7393ec979b0a:/# 
root@7393ec979b0a:/# 
root@7393ec979b0a:/# sudo config acl add table  ACL_MIRROR mirror
root@7393ec979b0a:/# 
root@7393ec979b0a:/# 
root@7393ec979b0a:/# show acl table
Name        Type    Binding      Description    Stage
----------  ------  -----------  -------------  -------
ACL_MIRROR  mirror  Ethernet0    ACL_MIRROR     ingress
                    Ethernet4
                    Ethernet8
                    Ethernet12
                    Ethernet16
                    Ethernet20
                    Ethernet24
                    Ethernet28
                    Ethernet32
                    Ethernet36
                    Ethernet40
                    Ethernet44
                    Ethernet48
                    Ethernet52
                    Ethernet56
                    Ethernet60
                    Ethernet64
                    Ethernet68
                    Ethernet72
                    Ethernet76
                    Ethernet80
                    Ethernet84
                    Ethernet88
                    Ethernet92
                    Ethernet96
                    Ethernet100
                    Ethernet104
                    Ethernet108
                    Ethernet112
                    Ethernet116
                    Ethernet120
                    Ethernet124
root@7393ec979b0a:/# 
root@7393ec979b0a:/# 
root@7393ec979b0a:/# 
root@7393ec979b0a:/# sudo config acl add table  ACL_MIRROR mirror
root@7393ec979b0a:/# 
root@7393ec979b0a:/# 
root@7393ec979b0a:/# show acl table
Traceback (most recent call last):
  File "/usr/bin/acl-loader", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 770, in table
    acl_loader.show_table(table_name)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 617, in show_table
    if not val["ports"]:
KeyError: 'ports'
root@7393ec979b0a:/#

**Comment by zhanggongc** [comment]
![image](https://user-images.githubusercontent.com/58503468/87035927-a2894780-c21c-11ea-8ab7-c2b80a4b311f.png)

**Comment by zhanggongc** [comment]
I don't bind any port to acl table, just only create one acl table repeatly, that python trace error still come out regularly

**Comment by yxieca** [comment]
this issue is also reported in issue #4970

**Comment by zhanggongc** [comment]
admin@gdcni:~$ show version 

SONiC Software Version: SONiC.V1.00.10R2-03
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: c062c07
Build date: Wed Jun 24 05:21:36 UTC 2020
Built by: gitlab-runner@harbor

Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot
Serial Number: AJ29068870
Uptime: 08:24:57 up 14:39,  1 user,  load average: 0.28, 0.24, 0.25

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-syncd-bfn              V1.00.10R2-03       b40e457ab208        813MB
docker-syncd-bfn              latest              b40e457ab208        813MB
docker-router-advertiser      V1.00.10R2-03       23d5f48f5391        284MB
docker-router-advertiser      latest              23d5f48f5391        284MB
docker-platform-monitor       V1.00.10R2-03       033bd94f283b        336MB
docker-platform-monitor       latest              033bd94f283b        336MB
docker-fpm-frr                V1.00.10R2-03       ae9c05a54ca1        329MB
docker-fpm-frr                latest              ae9c05a54ca1        329MB
docker-sonic-mgmt-framework   V1.00.10R2-03       0dff34f88792        428MB
docker-sonic-mgmt-framework   latest              0dff34f88792        428MB
docker-lldp-sv2               V1.00.10R2-03       40017eee7cf2        306MB
docker-lldp-sv2               latest              40017eee7cf2        306MB
docker-dhcp-relay             V1.00.10R2-03       ec8611e8f570        294MB
docker-dhcp-relay             latest              ec8611e8f570        294MB
docker-database               V1.00.10R2-03       dab9210ff97e        284MB
docker-database               latest              dab9210ff97e        284MB
docker-sflow                  V1.00.10R2-03       9b4b90186275        309MB
docker-sflow                  latest              9b4b90186275        309MB
docker-orchagent              V1.00.10R2-03       4313414868a6        327MB
docker-orchagent              latest              4313414868a6        327MB
docker-teamd                  V1.00.10R2-03       723f77898c79        309MB
docker-teamd                  latest              723f77898c79        309MB
docker-nat                    V1.00.10R2-03       7e0b38173cd6        310MB
docker-nat                    latest              7e0b38173cd6        310MB
docker-snmp-sv2               V1.00.10R2-03       541336e2d1ac        342MB
docker-snmp-sv2               latest              541336e2d1ac        342MB

**Comment by jleveque** [comment]
This is a different issue than https://github.com/Azure/sonic-buildimage/issues/4970.

Reassigning this issue to @daall.
