### ISSUE TITLE
Configurations of WARM_RESTART_ENABLE_TABLE pushed to STATE_DB instead of config-DB

### ISSUE THREAD

**Issue by venkatmahalingam** [Azure/sonic-buildimage#5017]
**Description**

WARM_RESTART_ENABLE_TABLE configurations are pushed into STATE_DB instead of config DB in the below pull request, because of this, after every cold reboot, we had to manually re-configure the  below table entries, this can be avoided if we retain the configurations in config DB (as it puts the config to config_db.json upon config save) and push these configs to STATE_DB upon handling the warm_reboot command in "sonic-utilities/scripts/warm-reboot", this helps the Enterprise customers to just enable the container that needs warm_restart support one time and then save the config in config DB to persist the config across reboots like we do for timer configuration and then simply executing the warm_restart command will help to restart the particular containers instead of configuring the containers to be warm-restarted after every boot-up.

https://github.com/Azure/sonic-utilities/pull/458

WARM_RESTART_ENABLE_TABLE|system
WARM_RESTART_ENABLE_TABLE|bgp
WARM_RESTART_ENABLE_TABLE|swss

**Steps to reproduce the issue**
1. Just enable warm restart for certain module and reboot node and check whether configs persist across reboots.

**Describe the results you received**
Configs are missed across reboots.

**Describe the results you expected**
Configs should persist across reboots and push to state DB whenever is required.

Here's how warm restart is implemented.
```

1) Using CONFIG_DB, WARM_RESTART table

root@sonic:~# config warm_restart bgp_timer 1800    
root@sonic:~# redis-cli -n 4 hgetall "WARM_RESTART|bgp"
1) "bgp_timer"
2) "1800"


root@sonic:~# config warm_restart bgp_eoiu true


root@sonic:~# redis-cli -n 4 hgetall "WARM_RESTART|bgp"
1) "bgp_timer"
2) "1800"
3) "bgp_eoiu"
4) "true"
root@sonic:~# 


root@sonic:~# config warm_restart neighsyncd_timer 2500
root@sonic:~# redis-cli -n 4 hgetall "WARM_RESTART|swss"
1) "neighsyncd_timer"
2) "2500"
root@sonic:~# 

root@sonic:~# config warm_restart teamsyncd_timer 3000
root@sonic:~# redis-cli -n 4 hgetall "WARM_RESTART|teamd"
1) "teamsyncd_timer"
2) "3000"
root@sonic:~# 

2) Using STATE_DB, WARM_RESTART table


root@sonic:~# config warm_restart enable system
root@sonic:~# redis-cli -n 6 hgetall "WARM_RESTART_ENABLE_TABLE|system"
1) "enable"
2) "true"
root@sonic:~# 


root@sonic:~# config warm_restart enable swss
root@sonic:~# redis-cli -n 6 hgetall "WARM_RESTART_ENABLE_TABLE|swss"
1) "enable"
2) "true"
root@sonic:~# 

root@sonic:~# config warm_restart enable bgp
root@sonic:~# redis-cli -n 6 hgetall "WARM_RESTART_ENABLE_TABLE|bgp"
1) "enable"
2) "true"
root@sonic:~# 

root@sonic:~# config warm_restart enable teamd
root@sonic:~# redis-cli -n 6 hgetall "WARM_RESTART_ENABLE_TABLE|teamd"
1) "enable"
2) "true"
root@sonic:~# 


WARM_RESTART table in CONFIG_DB has 3 instances with keys bgp, swss and teamd


WARM_RESTART_ENABLE_TABLE table in STATE_DB has 4 instances bgp, swss, teamd and system.


```

**Comment by xinliu-seattle** [comment]
This is by design.
