### ISSUE TITLE
Interfaces are displayed as Portchannel members even after deletion of the Portchannel

### ISSUE THREAD

**Issue by madhanmellanox** [Azure/sonic-buildimage#5051]
**Description**

"show interface status" displays Interfaces as port channel members even after deletion of the  Port channel.

**Steps to reproduce the issue:**
1. Create a Port channel
2. Add 2 ports as Port channel members
3. Port channel comes up. 
4. Delete the Port channel without deleting the Port channel members first.
5. Invoke command "show interface status", still the interfaces will be displayed as port channel members.

**Describe the results you received:**
"Show interface status" still shows the interfaces as port channel members.

root@r-qa-sw-eth-2132:/home/admin# config portchannel add portchannel1000
root@r-qa-sw-eth-2132:/home/admin# config portchannel member add portchannel1000 Ethernet108
root@r-qa-sw-eth-2132:/home/admin# config portchannel member add portchannel1000 Ethernet116
root@r-qa-sw-eth-2132:/home/admin#
root@r-qa-sw-eth-2132:/home/admin# show interfaces portchannel
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  -----------------------------
 1000  PortChannel1000  LACP(A)(Up)  Ethernet116(D) Ethernet108(S)
root@r-qa-sw-eth-2132:/home/admin# config portchannel del portchannel1000
root@r-qa-sw-eth-2132:/home/admin#
root@r-qa-sw-eth-2132:/home/admin# config portchannel del portchannel1000
root@r-qa-sw-eth-2132:/home/admin# show interfaces status
      Interface            Lanes    Speed    MTU    Alias             Vlan    Oper    Admin             Type    Asym PFC
---------------  ---------------  -------  -----  -------  ---------------  ------  -------  ---------------  ----------
      Ethernet0              0,1      10G  10000   etp1-1           routed      up       up  QSFP28 or later         N/A
      Ethernet2              2,3      10G  10000   etp1-2           routed      up       up              N/A         N/A
      Ethernet4          4,5,6,7      10G  10000     etp2           routed      up       up   SFP/SFP+/SFP28         N/A
      Ethernet8        8,9,10,11      10G  10000     etp3           routed      up       up  QSFP28 or later         N/A
     Ethernet12      12,13,14,15      N/A  10000     etp4           routed    down       up              N/A         N/A
     Ethernet16      16,17,18,19      N/A  10000     etp5           routed      up       up  QSFP28 or later         N/A
     Ethernet20      20,21,22,23      N/A  10000     etp6           routed    down       up              N/A         N/A
     Ethernet24      24,25,26,27      N/A  10000     etp7           routed      up       up  QSFP28 or later         N/A
     Ethernet28      28,29,30,31      N/A  10000     etp8           routed    down       up              N/A         N/A
     Ethernet32      32,33,34,35      N/A  10000     etp9           routed      up       up  QSFP28 or later         N/A
     Ethernet36      36,37,38,39      N/A  10000    etp10           routed    down       up              N/A         N/A
     Ethernet40      40,41,42,43      N/A  10000    etp11           routed    down       up  QSFP28 or later         N/A
     Ethernet44      44,45,46,47      N/A  10000    etp12           routed    down       up              N/A         N/A
     Ethernet48      48,49,50,51      N/A  10000    etp13           routed    down       up              N/A         N/A
     Ethernet52      52,53,54,55      N/A  10000    etp14           routed    down       up              N/A         N/A
     Ethernet56      56,57,58,59      N/A  10000    etp15           routed    down       up              N/A         N/A
     Ethernet60      60,61,62,63      N/A  10000    etp16           routed    down       up              N/A         N/A
     Ethernet64      64,65,66,67      N/A  10000    etp17           routed    down       up              N/A         N/A
     Ethernet68      68,69,70,71      N/A  10000    etp18           routed    down       up              N/A         N/A
     Ethernet72      72,73,74,75      N/A  10000    etp19           routed    down       up              N/A         N/A
     Ethernet76      76,77,78,79      N/A  10000    etp20           routed    down       up              N/A         N/A
     Ethernet80      80,81,82,83      N/A  10000    etp21           routed    down       up              N/A         N/A
     Ethernet84      84,85,86,87      N/A  10000    etp22           routed    down       up              N/A         N/A
     Ethernet88      88,89,90,91      N/A  10000    etp23           routed    down       up              N/A         N/A
     Ethernet92      92,93,94,95      N/A  10000    etp24           routed    down       up              N/A         N/A
     Ethernet96      96,97,98,99      N/A  10000    etp25           routed    down       up   SFP/SFP+/SFP28         N/A
    Ethernet100  100,101,102,103      N/A  10000    etp26           routed    down       up              N/A         N/A
    Ethernet104  104,105,106,107      N/A  10000    etp27           routed    down       up   SFP/SFP+/SFP28         N/A
    Ethernet108  108,109,110,111      N/A   9100    etp28  portchannel1000      up       up  QSFP28 or later         N/A
    Ethernet112  112,113,114,115      N/A  10000    etp29           routed    down       up              N/A         N/A
    Ethernet116  116,117,118,119      N/A   9100    etp30  portchannel1000      up       up  QSFP28 or later         N/A
    Ethernet120  120,121,122,123      10G  10000    etp31           routed      up       up   SFP/SFP+/SFP28         N/A
    Ethernet124  124,125,126,127      10G  10000    etp32           routed      up       up   SFP/SFP+/SFP28         N/A
portchannel1000              N/A        G             N/A           routed     N/A      N/A              N/A         N/A
root@r-qa-sw-eth-2132:/home/admin#

This config still remains in config_db.json:
    "PORTCHANNEL_MEMBER": {
        "portchannel1000|Ethernet108": {},
        "portchannel1000|Ethernet116": {}
    },

Only the following configuration got removed from config_db.json due to portchannel delete:
    "PORTCHANNEL": {
        "portchannel1000": {
            "admin_status": "up",
            "mtu": "9100"
        }
    },

**Describe the results you expected:**
"Show interface status" should not show the interfaces as port channel members.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
admin@r-qa-sw-eth-2132:~$ show version

SONiC Software Version: SONiC.master.282-0542afb6
Distribution: Debian 10.4
Kernel: 4.19.0-6-amd64
Build commit: 0542afb6
Build date: Thu May 14 14:01:16 UTC 2020
Built by: johnar@jenkins-worker-12

Platform: x86_64-mlnx_msn3700-r0
HwSKU: ACS-MSN3700
ASIC: mellanox
Serial Number: MT1932X22254
Uptime: 21:57:30 up 38 min,  1 user,  load average: 0.33, 0.30, 0.32

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-sonic-mgmt-framework   latest                10da1a903727        459MB
docker-sonic-mgmt-framework   master.282-0542afb6   10da1a903727        459MB
docker-teamd                  latest                36f0015b2b9a        311MB
docker-teamd                  master.282-0542afb6   36f0015b2b9a        311MB
docker-syncd-mlnx             latest                34a151db69a4        391MB
docker-syncd-mlnx             master.282-0542afb6   34a151db69a4        391MB
docker-sonic-telemetry        latest                51622e81f9e8        353MB
docker-sonic-telemetry        master.282-0542afb6   51622e81f9e8        353MB
docker-snmp-sv2               latest                895f4a01a665        347MB
docker-snmp-sv2               master.282-0542afb6   895f4a01a665        347MB
docker-sflow                  latest                5788f6789583        312MB
docker-sflow                  master.282-0542afb6   5788f6789583        312MB
docker-router-advertiser      latest                461a0651af0f        290MB
docker-router-advertiser      master.282-0542afb6   461a0651af0f        290MB
docker-platform-monitor       latest                a505c8510ca4        428MB
docker-platform-monitor       master.282-0542afb6   a505c8510ca4        428MB
docker-orchagent              latest                8afebf77864e        329MB
docker-orchagent              master.282-0542afb6   8afebf77864e        329MB
docker-nat                    latest                053c0ae15371        312MB
docker-nat                    master.282-0542afb6   053c0ae15371        312MB
docker-lldp-sv2               latest                f7ea2ddd90ff        308MB
docker-lldp-sv2               master.282-0542afb6   f7ea2ddd90ff        308MB
docker-fpm-frr                latest                783761225d7a        331MB
docker-fpm-frr                master.282-0542afb6   783761225d7a        331MB
docker-dhcp-relay             latest                58988c62ae8c        300MB
docker-dhcp-relay             master.282-0542afb6   58988c62ae8c        300MB
docker-database               latest                bb09f4819c0a        290MB
docker-database               master.282-0542afb6   bb09f4819c0a        290MB

admin@r-qa-sw-eth-2132:~$

Analyzing the logs of scenario of Portchannel deletion before members deletion
------------------------------------------------------------------------------
Once we delete the portchannel, after the port channel is up, but before deleting Port channel members. Deletion of config of the port channel, triggers the kernel to remove LAG members, which in turn sends NetLink messages to PortSyncd.

Jul 27 21:07:15.429862 sonic NOTICE swss#portsyncd: message repeated 5 times: [ :- onMsg: nlmsg type:16 key:Ethernet116 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:69 master:72 type:sx_netdev]
Jul 27 21:07:15.429862 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:07:15.430030 r-qa-sw-eth-2132 INFO kernel: [ 5739.329275] sx_netdev: sx_netdev_stop: called
Jul 27 21:07:15.430056 r-qa-sw-eth-2132 INFO kernel: [ 5739.329282] sx_netdev: sx_netdev_stop: exit
Jul 27 21:07:15.430165 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:07:15.430266 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:07:15.430436 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:07:15.430457 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:07:15.430540 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:07:15.430634 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:07:15.430752 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:07:15.430823 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:07:15.430939 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:07:15.431047 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:67 master:72 type:sx_netdev
Jul 27 21:07:15.431117 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:07:15.431422 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:07:15.431467 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:07:15.431729 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:07:15.431806 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:07:15.433137 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:07:15.433222 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev

Portsyncd invokes removal of both the Lag Members through Orchagent. And once the STATE DB is updated, Kernel removes both the ports from Portchannel.

Jul 27 21:07:15.433287 sonic NOTICE swss#orchagent: message repeated 189 times: [ :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS]
Jul 27 21:07:15.433287 sonic NOTICE swss#orchagent: :- removeLagMember: Remove member Ethernet116 from LAG portchannel1000 lid:20000000005f2 lmid:1b0000000005f4
Jul 27 21:07:15.433494 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:07:15.433494 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:07:15.433566 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:07:15.433785 sonic NOTICE swss#orchagent: :- removeLagMember: Remove member Ethernet108 from LAG portchannel1000 lid:20000000005f2 lmid:1b0000000005f3
Jul 27 21:07:15.433889 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:07:15.433889 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:07:15.434069 r-qa-sw-eth-2132 INFO kernel: [ 5739.329748] portchannel1000: Port device Ethernet116 removed
Jul 27 21:07:15.434087 r-qa-sw-eth-2132 INFO kernel: [ 5739.330224] sx_netdev: sx_netdev_stop: called
Jul 27 21:07:15.434089 r-qa-sw-eth-2132 INFO kernel: [ 5739.330229] sx_netdev: sx_netdev_stop: exit
Jul 27 21:07:15.434091 r-qa-sw-eth-2132 INFO kernel: [ 5739.330610] portchannel1000: Port device Ethernet108 removed
 
Once Kernel removes Portchannel members, syncd invokes SAI APIs to remove LAG member.

Jul 27 21:07:15.438567 r-qa-sw-eth-2132 INFO syncd#supervisord: syncd Jul 27 21:07:15 NOTICE  SAI_UTILS: mlnx_sai_utils.c[2398]- set_dispatch_attrib_handler: Set EGRESS_DISABLE, key:LAG member (14d00,0,0), val:false
Jul 27 21:07:15.442977 r-qa-sw-eth-2132 INFO syncd#supervisord: syncd Jul 27 21:07:15 NOTICE  SAI_LAG: mlnx_sai_lag.c[1563]- mlnx_remove_lag_member: Removing LAG member (14d00,0,0)
Jul 27 21:07:15.485937 sonic NOTICE swss#orchagent: message repeated 5 times: [ :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS]

Then Orchagent invokes removal of LAG (Portchannel1000) which invokes teammgrd to removeLag. But, teammgrd does not remove LAG members, which is not the case in Port channel member deletion case before Port channel deletion.

Jul 27 21:07:15.485937 sonic NOTICE swss#orchagent: :- removeLag: Remove LAG portchannel1000 lid:20000000005f2
Jul 27 21:07:15.486387 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:07:15.530620 sonic NOTICE teamd#teammgrd: :- removeLag: Stop port channel portchannel1000
Jul 27 21:07:15.574637 sonic INFO teamd#supervisord: teammgrd Device "portchannel1000" does not exist

After teammgrd invokes to remove LAG, not sure why addLagMember is invoked for both the Ports by team mgrd. This last step is not there in the scenario where port channels members are deleted first and then the Portchannel is deleted.

Jul 27 21:07:15.574908 sonic ERR teamd#teammgrd: :- exec: /sbin/ip link set dev "Ethernet108" down; /usr/bin/teamdctl "portchannel1000" port add "Ethernet108": No such file or directory
Jul 27 21:07:15.574942 sonic ERR teamd#teammgrd: :- addLagMember: Failed to add Ethernet108 to port channel portchannel1000
Jul 27 21:07:15.611104 sonic ERR teamd#teammgrd: :- exec: /sbin/ip link set dev "Ethernet116" down; /usr/bin/teamdctl "portchannel1000" port add "Ethernet116": No such file or directory
Jul 27 21:07:15.611104 sonic ERR teamd#teammgrd: :- addLagMember: Failed to add Ethernet116 to port channel portchannel1000

Analyzing the logs of scenario of Portchannel deletion after members deletion
------------------------------------------------------------------------------
Once we delete the portchannel, after the port channel is up, We delete the Portchannel members first before deleting the Port channel. Deletion of config of the port channel members, triggers the kernel to remove LAG members, which in turn sends NetLink messages to PortSyncd.

Jul 27 21:26:41.924819 sonic NOTICE swss#portsyncd: message repeated 5 times: [ :- onMsg: nlmsg type:16 key:Ethernet116 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:69 master:72 type:sx_netdev]
Jul 27 21:26:41.924819 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:67 master:72 type:sx_netdev
Jul 27 21:26:41.924861 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:26:41.925298 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:26:41.925431 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:26:41.925774 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:26:41.925817 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:26:41.926730 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:26:41.927073 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev

Portsyncd invokes removal of both the Lag Members through Orchagent. And once the STATE DB is updated, Kernel removes both the ports from Portchannel. Teammgrd also removes Portchannel members in this case. Syncd also invokes SAI APIs to remove the LAG members from the ASIC.

Jul 27 21:26:41.927294 sonic NOTICE swss#orchagent: message repeated 249 times: [ :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS]
Jul 27 21:26:41.927309 sonic NOTICE swss#orchagent: :- removeLagMember: Remove member Ethernet108 from LAG portchannel1000 lid:20000000005f2 lmid:1b0000000005f3
Jul 27 21:26:41.928359 r-qa-sw-eth-2132 INFO syncd#supervisord: syncd Jul 27 21:26:41 NOTICE  SAI_LAG: mlnx_sai_lag.c[1563]- mlnx_remove_lag_member: Removing LAG member (15500,0,0)
Jul 27 21:26:41.928618 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:26:41.928632 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:26:41.928991 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:26:41.929015 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet108 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:67 master:0 type:sx_netdev
Jul 27 21:26:41.929583 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet108(ok) to state db
Jul 27 21:26:41.930007 sonic NOTICE teamd#teammgrd: :- removeLagMember: Remove Ethernet108 from port channel portchannel1000
Jul 27 21:26:41.930655 sonic NOTICE swss#orchagent: message repeated 2 times: [ :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS]
Jul 27 21:26:41.930655 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet108 MTU to 10000
Jul 27 21:26:41.930887 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:26:41.931546 r-qa-sw-eth-2132 INFO lldp#lldpmgrd: Unable to retrieve description for port 'Ethernet108'. Not adding port description
Jul 27 21:26:41.931709 r-qa-sw-eth-2132 DEBUG kernel: [  469.104300] sx_core: sx_core_dispatch_event: dispatching the event
Jul 27 21:26:41.931728 r-qa-sw-eth-2132 INFO kernel: [  469.104308] sx_netdev: sx_netdev_event: Got LAG_OPER_STATE_UPDATE event. dev = 00000000b238cd1c, dev_id = 1, lag_id = 0, oper_state = 0
Jul 27 21:26:41.931732 r-qa-sw-eth-2132 WARNING kernel: [  469.104312] sx_netdev_set_lag_oper_state: Called for lag_id 0  status DOWN
Jul 27 21:26:49.477055 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:26:49.477461 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:26:49.477461 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:26:49.477712 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:26:49.477778 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:26:49.477905 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:26:49.477985 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:26:49.478101 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:26:49.478166 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:0 oper:0 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:26:49.478284 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:26:49.479687 r-qa-sw-eth-2132 INFO kernel: [  476.651401] sx_netdev: sx_netdev_stop: called
Jul 27 21:26:49.479704 r-qa-sw-eth-2132 INFO kernel: [  476.651405] sx_netdev: sx_netdev_stop: exit
Jul 27 21:26:49.479708 r-qa-sw-eth-2132 INFO kernel: [  476.651698] portchannel1000: Port device Ethernet116 removed
Jul 27 21:26:49.562166 sonic NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet116 admin:1 oper:1 addr:b8:59:9f:a8:e4:00 ifindex:69 master:0 type:sx_netdev
Jul 27 21:26:49.562695 sonic NOTICE swss#orchagent: message repeated 20 times: [ :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS]
Jul 27 21:26:49.562695 sonic NOTICE swss#orchagent: :- removeLagMember: Remove member Ethernet116 from LAG portchannel1000 lid:20000000005f2 lmid:1b0000000005f4
Jul 27 21:26:49.562695 sonic NOTICE swss#portsyncd: :- onMsg: Publish Ethernet116(ok) to state db
Jul 27 21:26:49.562876 r-qa-sw-eth-2132 INFO syncd#supervisord: syncd Jul 27 21:26:49 NOTICE  SAI_UTILS: mlnx_sai_utils.c[2398]- set_dispatch_attrib_handler: Set INGRESS_DISABLE, key:LAG member (14d00,0,0), val:false
Jul 27 21:26:49.562982 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:26:49.563702 r-qa-sw-eth-2132 INFO kernel: [  476.736303] sx_netdev: sx_netdev_open: called
Jul 27 21:26:49.563742 r-qa-sw-eth-2132 INFO kernel: [  476.736317] sx_netdev: sx_netdev_open: exit
Jul 27 21:26:49.563749 r-qa-sw-eth-2132 INFO kernel: [  476.736420] IPv6: ADDRCONF(NETDEV_UP): Ethernet116: link is not ready
Jul 27 21:26:49.565067 sonic NOTICE teamd#teammgrd: :- removeLagMember: Remove Ethernet116 from port channel portchannel1000
Jul 27 21:26:49.566104 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:26:49.566104 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet116 MTU to 10000
Jul 27 21:26:49.566312 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:26:49.566806 r-qa-sw-eth-2132 INFO syncd#supervisord: syncd Jul 27 21:26:49 NOTICE  SAI_LAG: mlnx_sai_lag.c[1563]- mlnx_remove_lag_member: Removing LAG member (14d00,0,0)

Upon invoking removal of Portchannel, Orchagent removes the LAG. Synd also removes the LAG from ASIC.

Jul 27 21:27:10.097448 sonic NOTICE swss#orchagent: message repeated 44 times: [ :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS]
Jul 27 21:27:10.097448 sonic NOTICE swss#orchagent: :- removeLag: Remove LAG portchannel1000 lid:20000000005f2
Jul 27 21:27:10.097724 sonic NOTICE swss#orchagent: :- set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
Jul 27 21:27:10.098312 r-qa-sw-eth-2132 INFO syncd#supervisord: syncd Jul 27 21:27:10 NOTICE  SAI_LAG: mlnx_sai_lag.c[1200]- mlnx_remove_lag: Removing LAG 80

So, in the case of deletion of Portchannel before deletion of members, kernel removes LAG members, teammgrd does not remove LAG members. But, syncd does. In the case of deletion of Port channel members and then deleting port channel, kernel removes LAG members, teammgrd also removes LAG members and syncd also removes LAG members.

**Comment by yxieca** [comment]
@madhanmellanox do you think you can help with a fix for this issue too?

We could add a protection to deny portchannel deletion before members are removed. Or we can recursively remove all port channel members.

**Comment by madhanmellanox** [comment]
@yxieca 
I wanted to go with the approach removing all port channel members before portchannel deletion.
But, as I could see from the logs, removeLAGMember for both the ports are getting called, but that is not invoking config removal from config_db, so I was not sure how to come up with the fix.

**Comment by lguohan** [comment]
it is easier to do the first approach. block port channel removal if there is member.

**Comment by madhanmellanox** [comment]
Sure, I will fix using the first approach - block port channel removal if there is member. I will take it up. Thanks.

**Comment by madhanmellanox** [comment]
The PR containing the fix for review.
https://github.com/Azure/sonic-utilities/pull/1062

**Comment by madhanmellanox** [comment]
The issue is fixed with merging of following PR: https://github.com/Azure/sonic-utilities/pull/1062.
So, closing this PR.
