### ISSUE TITLE
fast-reboot fails to run on Arista-7260cx3

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#5055]
**Description**
The fast-reboot command failed to reboot DUT on Arista-7260cx3 with the following error:
```
admin@str-7260cx3-acs-1:~$ sudo fast-reboot
% Specify remote-as or peer-group commands first.
```
But fast-reboot is able to run on msn2700 with the same version SONiC.

**Steps to reproduce the issue:**
1. Just run command sudo ** fast-reboot **

**Describe the results you received:**
``
% Specify remote-as or peer-group commands first.
``
Then the fast-reboot exit and DUT is not reboot.
More specific, this error message is produced by 
```
admin@str-7260cx3-acs-1:~$ vtysh 

Hello, this is FRRouting (version 7.2.1-sonic).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

str-7260cx3-acs-1# configure terminal
str-7260cx3-acs-1(config)# router bgp 4200065100
str-7260cx3-acs-1(config-router)# neighbor BGPSLBPassive shutdown
% Specify remote-as or peer-group commands first
str-7260cx3-acs-1(config-router)#
```
**Describe the results you expected:**
The DUT is reboot successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
The SONiC version is:
SONiC Software Version: SONiC.20191130.40
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 289a32803
Build date: Mon Jun 29 11:39:04 UTC 2020
Built by: sonicbld@jenkins-slave-phx-2

Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-D108C8
 ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
why is this closed？

**Comment by bingwang-ms** [comment]
> why is this closed？

Talked with Pavel offline and he said this is an issue only in internal repo. So I close it here.

**Comment by lguohan** [comment]
is the fix to be internal only?

**Comment by bingwang-ms** [comment]
> is the fix to be internal only?

Not sure about it for now. I will discuss with Pavel for more details.
