### ISSUE TITLE
frr.conf doens't reflect running FRR config

### ISSUE THREAD

**Issue by Ezrickd** [Azure/sonic-buildimage#5067]
running 201911 with FRRouting (version 7.2.1-sonic)

when checking vtysh "show run" or sonic "show runningconfig bgp", full FRR configuration is displayed.
when checking /etc/sonic/frr/frr.conf only partial configration is dispalyed, this is also relevant to BGP docker /etc/sonic/frr/frr.conf

the issue is imprtant as Tech-Support has no ability to bring the running config, and when ETC folder is backed up the FRR configuration doesnt reflect the running at time of issue.
[frr_config.txt](https://github.com/Azure/sonic-buildimage/files/4995076/frr_config.txt)

**Comment by pavel-shirshov** [comment]
It is not a bug. It is working as designed. frr.conf contains only base frr configuration. The rest configuration is controlled by bgpcfgd.
I'd suggest to download frr configuration from frr itself. Anyway putting startup configuration as running configuration doesn't make sense for tech-support. The frr configuration could be changed by human, for example.

**Comment by Ezrickd** [comment]
Hi Pavel
Allow me to disagree, if user want change FRR config manually he will probably will not use config_db and j2 to create FRR.conf. but rather configure FRR by vtysh and allow it to save.

As for tech-support, better have startup config from nothing at all.

The behavior has changed as in older Sonic images the FRR.conf did reflect the startup config.

I still see that as a flaw in the system.

Not sure I understand why it was changed there is no benefit by removing the config it is only degradation.

Ezrickd

Sent from my iPhone
Sorry for his typing errors (-;

On 29 Jul 2020, at 22:45, pavel-shirshov <notifications@github.com> wrote:

﻿

It is not a bug. It is working as designed. frr.conf contains only base frr configuration. The rest configuration is controlled by bgpcfgd.
I'd suggest to download frr configuration from frr itself. Anyway putting startup configuration as running configuration doesn't make sense for tech-support. The frr configuration could be changed by human, for example.

**Comment by lguohan** [comment]
If this is about having "show tech" to include running configuration of frr config, there are multiple ways to implement. We can dump a frr-running.conf in the show tech if that solves the problem.

**Comment by Ezrickd** [comment]
Agreed.
Accept any solution that will disclose the FRR running configuration when system snapshot is taken.

Tnx

/Ezrick

Ezrick Dayan
Mellanox, Nvidia Networking Division
Office: +972 74 7128603 | Cellphone: +972 54 4974192 | Email: ezrick@mellanox.com<mailto:ezrick@mellanox.com>
ezrick@nvidia.com

[cid:image001.png@01D66668.8E96D590]   [cid:image002.png@01D66668.8E96D590]

**Comment by Ezrickd** [comment]
Hi, 
how it is going to be implemented? 
also under which folder in tech-support.

/Ezrick

**Comment by noaOrMlnx** [comment]
Solved in https://github.com/Azure/sonic-utilities/commit/22d79f387728f40e9994d8dcd3397f42dda8a578#diff-cd1f4d6a5b025b3feb648269fec7b7db4285329bea576baba3734d16b1a1b263R447

**Comment by Ezrickd** [comment]
I can verify that frr.conf is present in 201911 at dump/frr.running_config.
closing the Issue.
