### ISSUE TITLE
[fast-reboot] counter polling is not delayed on fast-boot

### ISSUE THREAD

**Issue by stepanblyschak** [Azure/sonic-buildimage#5107]
**Description**

Inside the swss docker orchagent start.sh executes enable_counters.py script which waits until the uptime of switch is at least 3m,
then writes hardcoded config directly into config db. This was meant to delay counters polling threads on cold/fast-boot. However, if user did "config save -y" after that, counters polling is enabled in CONFIG DB at boot and polling starts imidiatelly.

**Steps to reproduce the issue:**
1. sudo config save -y # if the uptime is more than 3m
2. sudo fast-reboot
3. show int counters # counters polling is started even though the uptime is less than 3m.

**Describe the results you received:**
Increases fast-reboot downtime. Counter polling is not delayed till the end of fast-reboot.

**Describe the results you expected:**
Counter polling should be delayed till the end of fast-reboot.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
#4691

**Comment by liat-grozovik** [comment]
the proposed solution is to remove this config param when the fast reboot script is being called.
