### ISSUE TITLE
test_po_update flaky on KVM

### ISSUE THREAD

**Issue by daall** [Azure/sonic-buildimage#5273]
**Description**
Following https://github.com/Azure/sonic-buildimage/pull/5231 the test_po_update became extremely flaky on the PR runners. It is still passing intermittently so we're not sure if this is a test issue or an image issue introduced by the submodule update.

**Steps to reproduce the issue:**
1. Run test_po_update on a virtual switch w/ the latest master image.

**Describe the results you received:**
Test fails most of the time.

**Describe the results you expected:**
Test should pass consistently.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
@yxieca to follow-up on this issue.

**Comment by daall** [comment]
This issue is also seen on physical switches running the master image.
