### ISSUE TITLE
[201911] Warm boot fail from 201811 to 201911 on Broadcom platform

### ISSUE THREAD

**Issue by abdosi** [Azure/sonic-buildimage#5274]
When doing Warm-boot from 201811 image (SAI 3.5) to 201911 image (SAI 3.7) we are seeing below errors and warm-boot fails.

Root cause:
In 201911 image when syncd gets internal oid we are getting OID for attribute SAI_SWITCH_ATTR_DEFAULT_STP_INST_ID as part of 3.7 . In 3.5 this attribute was not supported.  This particular case is not handled correctly by syncd and when it compares temp and current view the co,mparison logic results in remove operation for this internal OID which cause error (as seen in below logs).

Fix:
Internal OID should always match in comparison logic and should not trigger remove operation

Logs:
Aug 29 18:39:56.343316 str-a7050-acs-1 ERR syncd#syncd: [none] brcm_sai_remove_stp:156 STP Instance 0x0000001000000001 cannot be removed due to 3 vlans present
Aug 29 18:39:56.343361 str-a7050-acs-1 ERR syncd#syncd: :- asic_handle_generic: remove SAI_OBJECT_TYPE_STP RID: oid:0x1000000001 VID oid:0x100000000006b6 failed: SAI_STATUS_OBJECT_IN_USE
Aug 29 18:39:56.343429 str-a7050-acs-1 ERR syncd#syncd: :- asic_process_event: failed to execute api: remove, key: SAI_OBJECT_TYPE_STP:oid:0x100000000006b6, status: SAI_STATUS_OBJECT_IN_USE
Aug 29 18:39:56.343576 str-a7050-acs-1 NOTICE syncd#syncd: :- executeOperationsOnAsic: asic apply took 0.001832 sec
Aug 29 18:39:56.343663 str-a7050-acs-1 ERR syncd#syncd: :- executeOperationsOnAsic: Error while executing asic operations, ASIC is in inconsistent state: :- asic_process_event: failed to execute api: remove, key: SAI_OBJECT_TYPE_STP:oid:0x100000000006b6, status: SAI_STATUS_OBJECT_IN_USE
Aug 29 18:39:56.608242 str-a7050-acs-1 NOTICE syncd#syncd: :- syncdApplyView: apply took 3.141233 sec
Aug 29 18:39:56.608562 str-a7050-acs-1 ERR syncd#syncd: :- syncd_main: Runtime error: :- asic_process_event: failed to execute api: remove, key: SAI_OBJECT_TYPE_STP:oid:0x100000000006b6, status: SAI_STATUS_OBJECT_IN_USE
Aug 29 18:39:56.608562 str-a7050-acs-1 NOTICE syncd#syncd: :- notify_OA_about_syncd_exception: sending switch_shutdown_request notification to OA
Aug 29 18:39:56.608787 str-a7050-acs-1 NOTICE swss#orchagent: :- handle_switch_shutdown_request: switch shutdown request

**Comment by abdosi** [comment]
working on fix.

**Comment by kcudnik** [comment]
@abdosi  when switch is created, there is discovery logic that discovers all the oids, it does not matter whether its cold or warm boot
so at new instance 3.7 SAI_SWITCH_ATTR_DEFAULT_STP_INST_ID  will be discovered, as it was not present on 3.5
and this should be done in different way, SAI_SWITCH_ATTR_DEFAULT_STP_INST_ID should be added to m_default_rid_map in SaiSwitch.cpp, and then when function isSwitchObjectDefaultRid() inside isNonRemovableRid(), and isNonRemovableRid is called in ComparisonLogic, then that object will not be removed, since that is default object
