### ISSUE TITLE
systemd-journald[224]: [/etc/systemd/journald.conf:21] Failed to parse size value, ignoring: 

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#528]
fsck from util-linux 2.25.2
/dev/sda1: clean, 21053/122400 files, 193789/489148 blocks
[   16.049420] systemd-journald[224]: [/etc/systemd/journald.conf:18] Failed to parse size value, ignoring: 50MB
[   16.167920] systemd-journald[224]: [/etc/systemd/journald.conf:21] Failed to parse size value, ignoring: 50MB
[  OK  ] Started LSB: Raise network interfaces..

**Comment by jleveque** [comment]
Should be resolved with https://github.com/Azure/sonic-buildimage/pull/535
