### ISSUE TITLE
 Arista Platform HW watchdog timeout is not setup correcly

### ISSUE THREAD

**Issue by abdosi** [Azure/sonic-buildimage#5287]
In 201911 Watchdog timer is not setup correctly on Arista platform. 
Default being 180 sec is not converted to milli-seconds setup correctly in the SCD Register.

Looks like following line is missing in 201911: 
https://github.com/aristanetworks/sonic/blob/c4108a2e1e1fde809daa46af6fbadcb03c0b5c44/utils/arista#L174

On 201811 Reg Value :
admin@str-a7050-acs-1:~$ sudo watchdog -e
INFO: arming the hardware watchdog for 180s
INFO: arm reg = 11000000000000000100011001010000

On 201911 Reg Value:
admin@str-a7050-acs-1:~$ sudo watchdogutil arm
INFO: arm reg = 11000000000000000000000010110100
Watchdog armed for 180 seconds

**Comment by abdosi** [comment]
@sujinmkang To follow up with Arista.

**Comment by anshuv-mfst** [comment]
@abdosi to look into this issue.
