### ISSUE TITLE
Switch level drop counters not working

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-buildimage#5303]
**Description**

Enabling drop counter for `switch_ingress_drops` not working as expected

**Steps to reproduce the issue:**
1. show dropcounters capabilities 
```
Counter Type            Total
--------------------  -------
SWITCH_EGRESS_DROPS        31
SWITCH_INGRESS_DROPS       31

SWITCH_INGRESS_DROPS
	ACL_ANY
	DECAP_ERROR
```

2. config dropcounters install test_decap  SWITCH_INGRESS_DROPS DECAP_ERROR
```
Sep  3 NOTICE swss#orchagent: :- addDropReason: Succesfully created drop counter TEST_DECAP
Sep  3 NOTICE swss#orchagent: :- installDebugCounter: Succesfully created drop counter test_decap
```

3. redis-cli

```
127.0.0.1:6379[5]> SELECT 4
127.0.0.1:6379[4]> KEYS *DEBUG*
1) "DEBUG_COUNTER|test_decap"
2) "DEBUG_COUNTER_DROP_REASON|TEST_DECAP|DECAP_ERROR"
```

**Describe the results you received:**
show dropcounters counts -t SWITCH_INGRESS_DROPS

<No output>

**Describe the results you expected:**
Valid drop counter values

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    show version 

    SONiC Software Version: SONiC.20191130.47
    Distribution: Debian 9.13
    Kernel: 4.9.0-11-2-amd64
    Build commit: 272885b17
    Build date: Fri Aug 28 01:36:16 UTC 2020
    Built by: sonicbld@jenkins-slave-phx-2

    Platform: x86_64-mlnx_msn3800-r0
    HwSKU: ACS-MSN3800
    ASIC: mellanox

    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by daall** [comment]
After experimenting for a bit I figured out that the issue here is not w/ the switch counter handling, but actually because the name of the counter is lowercase. I will update utilities/swss to not be case-sensitive for the naming. :P
