### ISSUE TITLE
201911 - SNMPwalk on Physical Table MIB yields no results

### ISSUE THREAD

**Issue by madhanmellanox** [Azure/sonic-buildimage#5307]
**Description**

snmpwalk of Physical table MIB yields no results.
madhan@arc-build-server:~$snmpwalk -c public -v2c 10.209.21.32 iso.3.6.1.2.1.47.1.1.1.1
iso.3.6.1.2.1.47.1.1.1.1 = No Such Object available on this agent at this OID

**Steps to reproduce the issue:**
1. Do a snmpwalk on physical table mib on the switch from any server, it will not fetch the results.
2.
3.

**Describe the results you received:**
madhan@arc-build-server:~$snmpwalk -c public -v2c 10.209.21.32 iso.3.6.1.2.1.47.1.1.1.1
iso.3.6.1.2.1.47.1.1.1.1 = No Such Object available on this agent at this OID

**Describe the results you expected:**
iso.3.6.1.2.1.47.1.1.1.1.2.1 = ""
iso.3.6.1.2.1.47.1.1.1.1.2.1000 = STRING: "QSFP28 for etp1"
iso.3.6.1.2.1.47.1.1.1.1.2.1001 = STRING: "DOM Temperature Sensor for etp1"
iso.3.6.1.2.1.47.1.1.1.1.2.1002 = STRING: "DOM Voltage Sensor for etp1"
iso.3.6.1.2.1.47.1.1.1.1.2.1011 = STRING: "DOM RX Power Sensor for etp1/1"
iso.3.6.1.2.1.47.1.1.1.1.2.1012 = STRING: "DOM TX Bias Sensor for etp1/1"
iso.3.6.1.2.1.47.1.1.1.1.2.1013 = STRING: "DOM TX Power Sensor for etp1/1"
iso.3.6.1.2.1.47.1.1.1.1.2.1021 = STRING: "DOM RX Power Sensor for etp1/2"
iso.3.6.1.2.1.47.1.1.1.1.2.1022 = STRING: "DOM TX Bias Sensor for etp1/2"
iso.3.6.1.2.1.47.1.1.1.1.2.1023 = STRING: "DOM TX Power Sensor for etp1/2"
iso.3.6.1.2.1.47.1.1.1.1.2.1031 = STRING: "DOM RX Power Sensor for etp1/3"
iso.3.6.1.2.1.47.1.1.1.1.2.1032 = STRING: "DOM TX Bias Sensor for etp1/3"
iso.3.6.1.2.1.47.1.1.1.1.2.1033 = STRING: "DOM TX Power Sensor for etp1/3"
iso.3.6.1.2.1.47.1.1.1.1.2.1041 = STRING: "DOM RX Power Sensor for etp1/4"
iso.3.6.1.2.1.47.1.1.1.1.2.1042 = STRING: "DOM TX Bias Sensor for etp1/4"
iso.3.6.1.2.1.47.1.1.1.1.2.1043 = STRING: "DOM TX Power Sensor for etp1/4"
iso.3.6.1.2.1.47.1.1.1.1.2.5000 = STRING: "QSFP28 for etp2"
iso.3.6.1.2.1.47.1.1.1.1.2.5001 = STRING: "DOM Temperature Sensor for etp2"
iso.3.6.1.2.1.47.1.1.1.1.2.5002 = STRING: "DOM Voltage Sensor for etp2"
iso.3.6.1.2.1.47.1.1.1.1.2.5011 = STRING: "DOM RX Power Sensor for etp2/1"
iso.3.6.1.2.1.47.1.1.1.1.2.5012 = STRING: "DOM TX Bias Sensor for etp2/1"
iso.3.6.1.2.1.47.1.1.1.1.2.5013 = STRING: "DOM TX Power Sensor for etp2/1"
iso.3.6.1.2.1.47.1.1.1.1.2.5021 = STRING: "DOM RX Power Sensor for etp2/2"
iso.3.6.1.2.1.47.1.1.1.1.2.5022 = STRING: "DOM TX Bias Sensor for etp2/2"
iso.3.6.1.2.1.47.1.1.1.1.2.5023 = STRING: "DOM TX Power Sensor for etp2/2"
iso.3.6.1.2.1.47.1.1.1.1.2.5031 = STRING: "DOM RX Power Sensor for etp2/3"
....
....
....
iso.3.6.1.2.1.47.1.1.1.1.13.45000 = STRING: "LUXN2604BO"
iso.3.6.1.2.1.47.1.1.1.1.13.49000 = STRING: "LUXN2604BO"
iso.3.6.1.2.1.47.1.1.1.1.13.53000 = STRING: "LUXN2604BO"
iso.3.6.1.2.1.47.1.1.1.1.13.57000 = STRING: "LUXN2604BO"
iso.3.6.1.2.1.47.1.1.1.1.13.61000 = STRING: "LUXN2604BO"

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
admin@r-qa-sw-eth-2132:~$ show version

SONiC Software Version: SONiC.201911.138-544aa236
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 544aa236
Build date: Fri Aug  7 13:18:07 UTC 2020
Built by: johnar@jenkins-worker-12

Platform: x86_64-mlnx_msn3700-r0
HwSKU: ACS-MSN3700
ASIC: mellanox
Serial Number: MT1932X22254
Uptime: 15:42:16 up 12:53,  1 user,  load average: 0.79, 0.57, 0.41

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-syncd-mlnx-rpc         201911.138-544aa236   e6f6997bcc16        654MB
docker-syncd-mlnx-rpc         latest                e6f6997bcc16        654MB
docker-sonic-telemetry        201911.138-544aa236   9a394688a4ca        352MB

    
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by madhanmellanox** [comment]
The 201911 image used was:
20191130.44
544aa236c 2020-08-05 | [submodule]: update sonic-utilities [Guohan Lu]

Upon investigation, this image does not have these two commits:
https://github.com/Azure/sonic-snmpagent/commit/bdfcc132aab181287d8e5be20c84f517adc1bdd2
https://github.com/Azure/sonic-snmpagent/commit/a81b402a8ad944db0a20795a135392f4bfaa37ef,

**Comment by anshuv-mfst** [comment]
Please verify is issue is seen.

**Comment by madhanmellanox** [comment]
@anshuv-mfst Does the build 193 of 20181911 contain the fix?

**Comment by madhanmellanox** [comment]
@anshuv-mfst  Yes, the snmpwalk is working on build 193 (Hash 75068f3) of 201911.
