### ISSUE TITLE
Not able to disable port in innovium switch

### ISSUE THREAD

**Issue by dev-aviz** [Azure/sonic-buildimage#5328]
**Description**
Not able to disable port in Innovium Switch

**show version**

SONiC Software Version: SONiC.master.0-dirty-20200816.173139
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64

Platform: x86_64-cameo_esc601_32q-r0
HwSKU: esc601-32q
ASIC: innovium
Serial Number: DC64Y19W50T18004
Uptime: 12:17:44 up 4 min,  1 user,  load average: 0.27, 0.29, 0.14

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-syncd-invm          latest                           398213c9c9d2        372MB
docker-syncd-invm          master.0-dirty-20200816.173139   398213c9c9d2        372MB
docker-router-advertiser   latest                           4749f67a35fb        286MB
docker-router-advertiser   master.0-dirty-20200816.173139   4749f67a35fb        286MB
docker-platform-monitor    latest                           5eb94da0d87a        337MB
docker-platform-monitor    master.0-dirty-20200816.173139   5eb94da0d87a        337MB
docker-fpm-frr             latest                           a11677dec65e        330MB
docker-fpm-frr             master.0-dirty-20200816.173139   a11677dec65e        330MB
docker-sflow               latest                           24236bd57884        310MB
docker-sflow               master.0-dirty-20200816.173139   24236bd57884        310MB
docker-lldp-sv2            latest                           f38b69343221        307MB
docker-lldp-sv2            master.0-dirty-20200816.173139   f38b69343221        307MB
docker-dhcp-relay          latest                           61e1b29cbe5b        296MB
docker-dhcp-relay          master.0-dirty-20200816.173139   61e1b29cbe5b        296MB
docker-database            latest                           fc83e17b5f2a        286MB
docker-database            master.0-dirty-20200816.173139   fc83e17b5f2a        286MB
docker-orchagent           latest                           c4130ef6417f        329MB
docker-orchagent           master.0-dirty-20200816.173139   c4130ef6417f        329MB
docker-teamd               latest                           6605aa99436a        310MB
docker-teamd               master.0-dirty-20200816.173139   6605aa99436a        310MB
docker-nat                 latest                           9cd7a7dd2169        312MB
docker-nat                 master.0-dirty-20200816.173139   9cd7a7dd2169        312MB
docker-sonic-telemetry     latest                           8b1b8a01c9cf        347MB
docker-sonic-telemetry     master.0-dirty-20200816.173139   8b1b8a01c9cf        347MB
docker-snmp-sv2            latest                           689a7e75915a        344MB
docker-snmp-sv2            master.0-dirty-20200816.173139   689a7e75915a        344MB

**Reproduction steps:**
shutdown interface Ethernet48
sonic#config interface shutdown Ethernet48

Admin is still up,  below is the show interface.
show interface status
============================================================================================
Port            Name                            Oper    Admin   Vlan    Speed   MTU
============================================================================================
Ethernet0       Eth1                            down    up      100     100000  9100
Ethernet4       Eth2                            down    up      trunk   100000  9100
Ethernet8       Eth3                            down    up              100000  9100
Ethernet12      Eth4                            down    up              100000  9100
Ethernet16      Eth5                            down    up              100000  9100
Ethernet20      Eth6                            down    up      100     100000  9100
Ethernet24      Eth7                            down    up              100000  9100
Ethernet28      Eth8                            down    up              100000  9100
Ethernet32      Eth9                            down    up              100000  9100
Ethernet36      Eth10                           down    up              100000  9100
Ethernet40      Eth11                           down    up      100     100000  9100
Ethernet44      Eth12                           down    up              100000  9100
**Ethernet48      Eth13                           down    up              100000  9100**
Ethernet52      Eth14                           down    up              100000  9100
Ethernet56      Eth15                           down    up              100000  9100
Ethernet60      Eth16                           down    up              100000  9100
Ethernet64      Eth17                           down    up              100000  9100
Ethernet68      Eth18                           down    up              100000  9100
Ethernet72      Eth19                           down    up              100000  9100
Ethernet76      Eth20                           down    up              100000  9100
Ethernet80      Eth21                           down    up              100000  9100
Ethernet84      Eth22                           down    up              100000  9100
Ethernet88      Eth23                           down    up              100000  9100
Ethernet92      Eth24                           down    up              100000  9100
Ethernet96      Eth25                           down    up              100000  9100
Ethernet100     Eth26                           down    up              100000  9100
Ethernet104     Eth27                           down    up              100000  9100
Ethernet108     Eth28                           down    up              100000  9100
Ethernet112     Eth29                           down    up              100000  9100
Ethernet116     Eth30                           down    up              100000  9100
Ethernet120     Eth31                           down    up              100000  9100
Ethernet124     Eth32                           down    up              100000  9100

**Comment by prsunny** [comment]
@tonytitus , can you take a look?

**Comment by tonytitus** [comment]
@prsunny , sure Prince

**Comment by dev-aviz** [comment]
Here is the update : Issue is not reproducible with official SONiC Releases. Closing the issue.
More details: 
We went ahead and reproduce the issue with official releases(201911 release) with sonic command reference and found that issue not reproducible. so closing the issue.
Platform: x86_64-cameo_esc601_32q-r0
ASIC: innovium
