### ISSUE TITLE
[platform-daemons] pcied daemon doesn't  update STATE_DB

### ISSUE THREAD

**Issue by bratashX** [Azure/sonic-buildimage#5349]
**Steps to reproduce the issue:**

1. Run pcied daemon
2. Execute command
`redis-cli -n 6 SET "PCIE_STATUS|PCIE_DEVICES" "TEST"`
3. Wait one minute
4. Execute command 
 `redis-cli -n 6 GET "PCIE_STATUS|PCIE_DEVICES`

**Describe the results you received:**

pcied daemon must update the database every minute, but `PCIE_STATUS|PCIE_DEVICES` doesn`t change.

**Additional information you deem important (e.g. issue happens only occasionally):**

_**pcie-check.service**_ and **_pcied daemon_** set different variables in STATE_DB.

https://github.com/Azure/sonic-platform-daemons/blob/7f812c93b19fc456ac1ecd66510d403b8ff775c3/sonic-pcied/scripts/pcied#L83

https://github.com/Azure/sonic-buildimage/blob/5b3b4804adcffaa43012596acf6effe5a31f0256/files/image_config/pcie-check/pcie-check.sh#L40

**Comment by liat-grozovik** [comment]
issue was handled and clarified as fixed
