### ISSUE TITLE
[ZTP] "show ztp status" command requires root privileges to be executed

### ISSUE THREAD

**Issue by MaxYaremchuk** [Azure/sonic-buildimage#5377]
**Description**

**show ztp status** command requires root privileges to be executed

**Steps to reproduce the issue**
1. On the SONiC image with enabled ZTP feature issue the command **show ztp status**

**Describe the results you received**
```
$ show ztp status --verbose     
Root privileges are required for this operation
```

**Describe the results you expected**
**show ztp status** command should be successfully executed under admin credentials.

**Output of `show version`**

```
SONiC Software Version: SONiC.HEAD.0-fffee7e3
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: fffee7e3
Build date: Sun Jun 21 09:33:14 UTC 2020
Built by: ezrada@r-build-sonic02

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700 
```
[sonic_dump_DUT-1_20200902_193652.tar.gz](https://github.com/Azure/sonic-utilities/files/5208226/sonic_dump_DUT-1_20200902_193652.tar.gz)

**Comment by rajendra-dendukuri** [comment]
Fixed in:
https://github.com/Azure/sonic-ztp/pull/13
https://github.com/Azure/sonic-utilities/pull/872

**Comment by liat-grozovik** [comment]
@rajendra-dendukuri will you be able to check if the fix can also be cherry picked to 201911?

**Comment by rajendra-dendukuri** [comment]
> @rajendra-dendukuri will you be able to check if the fix can also be cherry picked to 201911?

@liat-grozovik Yes. There are two PR's pending review and approval to be merged to 201911. Once they are approved I can merge them to 201911.

**Comment by liat-grozovik** [comment]
Appreciate

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MaxYaremchuk** [comment]
The bug has been fixed.  Verified on:
```
$ show ver

SONiC Software Version: SONiC.SONIC.202012.28-08bf372_Internal
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 08bf372b
Build date: Sun Feb 28 14:57:46 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02
```
```
admin@sonic-step-03:~$ show ztp status
ZTP Admin Mode : True
ZTP Service    : Inactive
ZTP Status     : SUCCESS
ZTP Source     : dhcp-opt67 (eth0)
Runtime        : 16m 32s
Timestamp      : 2021-03-04 12:18:01 UTC

ZTP Service is not running

01-snmp: SUCCESS
02-script-01: SUCCESS
03-configdb-json: SUCCESS
05-script-02: FAILED
06-script-04: SUCCESS
07-script-05: FAILED
08-script-06: SUCCESS
09-post-provisioning-script: SUCCESS
```
