### ISSUE TITLE
[DPB] Dynamic Port Breakout feature is not working on the latest master image

### ISSUE THREAD

**Issue by vadymhlushko-mlnx** [Azure/sonic-buildimage#5417]
**Description**

The Dynamic Port Breakout feature is not working on the latest master image

**Steps to reproduce the issue:**
1. Put capability files to correct location according to PR [DPB_Seastone](https://github.com/Azure/sonic-buildimage/pull/4235/files)
2. Run the command:
`sonic-cfggen -p <platform.json file location> -k <hwsku> -w`
3. Check `CONFIG_DB`
4. Run the command:
`config interface breakout Ethernet4 4x25G -y`

**Describe the results you received:**

 `root@r-boxer-sw01:~# config interface breakout Ethernet76 1x10G -y`

`Running Breakout Mode : 1x100G[50G,40G,25G,10G]` 
`Target Breakout Mode : 1x10G`

`Ports to be deleted : `
` {`
`    "Ethernet76": "100000"`
`}`
`Ports to be added : `
` {`
`    "Ethernet76": "10000"`
`}

`After running Logic to limit the impact`

`Final list of ports to be deleted : `
` {`
`    "Ethernet76": "100000"`
`} `
`Final list of ports to be added :  `
` {`
 `   "Ethernet76": "10000"`
`}`
`Loaded below Yang Models`
`['sonic-acl', 'sonic-extension', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-``vlan']`
`Note: Below table(s) have no YANG models:`
`TACPLUS_SERVER, DEVICE_METADATA, MAP_PFC_PRIORITY_TO_QUEUE, QUEUE, FLEX_COUNTER_TABLE, CRM, BUFFER_PG, ``BGP_NEIGHBOR, VERSIONS, BUFFER_PORT_INGRESS_PROFILE_LIST, MGMT_INTERFACE, PORT_QOS_MAP, NTP_SERVER, ``BUFFER_QUEUE, WRED_PROFILE, TC_TO_PRIORITY_GROUP_MAP, TELEMETRY, DEVICE_NEIGHBOR, FEATURE, DSCP_TO_TC_MAP, ``PFC_PRIORITY_TO_PRIORITY_GROUP_MAP, BREAKOUT_CFG, DHCP_SERVER, TC_TO_QUEUE_MAP, MGMT_PORT, RESTAPI, ``CABLE_LENGTH, SCHEDULER, BUFFER_PORT_EGRESS_PROFILE_LIST, BUFFER_POOL, BUFFER_PROFILE, `
`Data Loading Failed`
`Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed`

**Describe the results you expected:**

`config interface breakout <intf> <mode>` should work without errors

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```SONiC Software Version: SONiC.master.396-8d285b46
```Distribution: Debian 10.5
```Kernel: 4.19.0-9-2-amd64
```Build commit: 8d285b46
```Build date: Mon Sep  7 12:53:46 UTC 2020
```Built by: johnar@jenkins-worker-4
```
```Platform: x86_64-mlnx_msn2010-r0
```HwSKU: ACS-MSN2010
```ASIC: mellanox
```Serial Number: MT1749X10061
```Uptime: 15:45:35 up 9 min,  1 user,  load average: 0.20, 0.31, 0.27
```
```Docker images:
```REPOSITORY                    TAG                   IMAGE ID            SIZE
```docker-syncd-mlnx             latest                71cea8dd5e40        464MB
```docker-syncd-mlnx             master.396-8d285b46   71cea8dd5e40        464MB
```docker-orchagent              latest                ffb85aa5d8ab        400MB
```docker-orchagent              master.396-8d285b46   ffb85aa5d8ab        400MB
```docker-teamd                  latest                21cf532293cd        386MB
```docker-teamd                  master.396-8d285b46   21cf532293cd        386MB
```docker-nat                    latest                2cd9688fbdcc        389MB
```docker-nat                    master.396-8d285b46   2cd9688fbdcc        389MB
```docker-router-advertiser      latest                2ed6e3a6a9c5        355MB
```docker-router-advertiser      master.396-8d285b46   2ed6e3a6a9c5        355MB
```docker-platform-monitor       latest                66a109975994        508MB
```docker-platform-monitor       master.396-8d285b46   66a109975994        508MB
```docker-lldp                   latest                28260c7c0d32        383MB
```docker-lldp                   master.396-8d285b46   28260c7c0d32        383MB
```docker-dhcp-relay             latest                6f4242867165        362MB
```docker-dhcp-relay             master.396-8d285b46   6f4242867165        362MB
```docker-database               latest                8275540f2214        355MB
```docker-database               master.396-8d285b46   8275540f2214        355MB
```docker-sonic-telemetry        latest                c26b96204307        425MB
```docker-sonic-telemetry        master.396-8d285b46   c26b96204307        425MB
```docker-sonic-mgmt-framework   latest                9e9ebdc4e093        481MB
```docker-sonic-mgmt-framework   master.396-8d285b46   9e9ebdc4e093        481MB
```docker-fpm-frr                latest                10e840427577        402MB
```docker-fpm-frr                master.396-8d285b46   10e840427577        402MB
```docker-sflow                  latest                2bae91587c85        390MB
```docker-sflow                  master.396-8d285b46   2bae91587c85        390MB
```docker-snmp                   latest                20c0c2d41c4f        395MB
```docker-snmp                   master.396-8d285b46   20c0c2d41c4f        395MB

**Comment by vadymhlushko-mlnx** [comment]
@praveen-li

**Comment by vadymhlushko-mlnx** [comment]
@samaity

**Comment by praveen-li** [comment]
As per email:

Hi Vadym

You did not share Syslog yet. Also, copy the config, you can change the parameters in the config for security purpose.[Or share in email].

>>>
Please run the command with -v option. Then paste the Syslog while error.

Or in Slack, you can show me your config if that is okie.

**Comment by vadymhlushko-mlnx** [comment]
**config interface breakout Ethernet76 1x10G -v**
``` 
Do you want to Breakout the port, continue? [y/N]: y

Running Breakout Mode : 1x100G[50G,40G,25G,10G] 
Target Breakout Mode : 1x10G

Ports to be deleted : 
 {
    "Ethernet76": "100000"
}
Ports to be added : 
 {
    "Ethernet76": "10000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet76": "100000"
} 
Final list of ports to be added :  
 {
    "Ethernet76": "10000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-extension', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-vlan']
Note: Below table(s) have no YANG models:
TACPLUS_SERVER, DEVICE_METADATA, MAP_PFC_PRIORITY_TO_QUEUE, QUEUE, FLEX_COUNTER_TABLE, CRM, BUFFER_PG, BGP_NEIGHBOR, VERSIONS, BUFFER_PORT_INGRESS_PROFILE_LIST, MGMT_INTERFACE, PORT_QOS_MAP, NTP_SERVER, BUFFER_QUEUE, WRED_PROFILE, TC_TO_PRIORITY_GROUP_MAP, TELEMETRY, DEVICE_NEIGHBOR, FEATURE, DSCP_TO_TC_MAP, PFC_PRIORITY_TO_PRIORITY_GROUP_MAP, BREAKOUT_CFG, DHCP_SERVER, TC_TO_QUEUE_MAP, MGMT_PORT, RESTAPI, CABLE_LENGTH, SCHEDULER, BUFFER_PORT_EGRESS_PROFILE_LIST, BUFFER_POOL, BUFFER_PROFILE, 
Data Loading Failed
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed

**Comment by vadymhlushko-mlnx** [comment]
`show techsupport --since "1 day"`


[sonic_dump_r-boxer-sw01_20200922_132027.tar.gz](https://github.com/Azure/sonic-buildimage/files/5261675/sonic_dump_r-boxer-sw01_20200922_132027.tar.gz)

**Comment by vadymhlushko-mlnx** [comment]
@praveen-li @samaity

**Comment by praveen-li** [comment]
@vadymhlushko-mlnx : the config has many fields which are not supported by yang models, for example: pfc_asym in PORT table. 
We need to find who added this field and ask to add such fields in YANG models as well. 
For this, I will discuss with Microsoft, how to make sure new fields are added in YANG models. As of now, I will raise a new PR will the new fields in your config.

@samaity : Kindly check once if breakmode looks correct here. i.e. moving from 100G -> 10G.

"PORT": {"Ethernet8": {"lanes": "8", "description": "ARISTA02T0:Ethernet1", "pfc_asym": "off", "mtu": "9100", "alias": "Ethernet8", "admin_status": "up", "speed": "25000"}

**Comment by vadymhlushko-mlnx** [comment]
> @vadymhlushko-mlnx : the config has many fields which are not supported by yang models, for example: pfc_asym in PORT table.
> We need to find who added this field and ask to add such fields in YANG models as well.
> For this, I will discuss with Microsoft, how to make sure new fields are added in YANG models. As of now, I will raise a new PR will the new fields in your config.
> 
> @samaity : Kindly check once if breakmode looks correct here. i.e. moving from 100G -> 10G.
> 
> "PORT": {"Ethernet8": {"lanes": "8", "description": "ARISTA02T0:Ethernet1", "pfc_asym": "off", "mtu": "9100", "alias": "Ethernet8", "admin_status": "up", "speed": "25000"}

@praveen-li, any updates?

**Comment by praveen-li** [comment]
@vadymhlushko-mlnx: My PR is underway, but that will not solve this issue. As mentioned to use DPB features:
You need to have YANG models for the config tables you used, especially the one which has a dependency on PORT. Also, you need to have backend code developed for those tables. 
Without that, even though port will break after my PR, but backend will not work as expected.

**Comment by praveen-li** [comment]
Raise https://github.com/Azure/sonic-buildimage/pull/5577.

But remember you need to remove tables from config DB which does not have Yang models, to make it work.

**Comment by vadymhlushko-mlnx** [comment]
> @vadymhlushko-mlnx: My PR is underway, but that will not solve this issue. As mentioned to use DPB features:
> You need to have YANG models for the config tables you used, especially the one which has a dependency on PORT. Also, you need to have backend code developed for those tables.
> Without that, even though port will break after my PR, but backend will not work as expected.

Okay, thanks.
@praveen-li, who will be responsible to write code for - `"YANG models for the config tables you used, especially the one which has a dependency on PORT"` and for `"backend code developed for those tables"`?

**Comment by praveen-li** [comment]
@vadymhlushko-mlnx, anybody in the community, who wants the DPB feature to work for those tables. So if it is a must for you, then you and your team should start with YANG models and the backend code. Without these yang models, you can break-out the port but may potentially crash the backend. 

Please refer to get more insight: https://github.com/Azure/SONiC/blob/master/doc/dynamic-port-breakout/sonic-dynamic-port-breakout-HLD.md. Thx.

**Comment by vadymhlushko-mlnx** [comment]
@praveen-li, could you please explain to me why such tables `DEVICE_METADATA, CRM, FEATURE` etc. are affecting on YANG lib which is deciding to split port or not?

I'm asking it because `DEVICE_METADATA, CRM, FEATURE` is not related to PORT instance at all, so why do we need to check if there are YANG models of those before splitting the port?

Maybe this is a design issue?

**Comment by vadymhlushko-mlnx** [comment]
I have tried to integrate this [sonic-buildimage/pull/5577](https://github.com/Azure/sonic-buildimage/pull/5577) PR.
And copy YANG models from [sonic-buildimage/pull/4442](https://github.com/Azure/sonic-buildimage/pull/4442) to `/usr/local/yang-models` folder on the switch.
Also on the switch was the very simple CONFIG_DB (please check attachments)
[config_db.zip](https://github.com/Azure/sonic-buildimage/files/5386527/config_db.zip)
[sonic_dump_r-tigris-13_20201015_164049.tar.gz](https://github.com/Azure/sonic-buildimage/files/5386524/sonic_dump_r-tigris-13_20201015_164049.tar.gz)

And I have the same results as before (output bellow):

``` 
root@r-tigris-13:/home/admin# config interface breakout -v Ethernet248 2x50G
Do you want to Breakout the port, continue? [y/N]: y

Running Breakout Mode : 1x100G[40G]
Target Breakout Mode : 2x50G

Ports to be deleted :
 {
    "Ethernet248": "100000"
}
Ports to be added :
 {
    "Ethernet250": "50000",
    "Ethernet248": "50000"
}

After running Logic to limit the impact

Final list of ports to be deleted :
 {
    "Ethernet248": "100000"
}
Final list of ports to be added :
 {
    "Ethernet250": "50000",
    "Ethernet248": "50000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-extension', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-vlan', 'sonic-versions', 'sonic-breakout_cfg', 'sonic-device_metadata', 'sonic-crm', 'sonic-flex_counter']
Note: Below table(s) have no YANG models:
TELEMETRY, FEATURE,
Data Loading Failed
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed

**Comment by vadymhlushko-mlnx** [comment]
I have tried to get all YANG models (except [sonic-flex_counter.yang](https://github.com/Azure/sonic-buildimage/pull/4442/files#diff-b9f8e98f7abb53dc7b42c3d5e58e17e1b498012bfe577bb13410775adbda0285))  from [LINK](https://github.com/praveen-li/sonic-buildimage/tree/new_yang_models_msft/src/sonic-yang-models/yang-models).
With very simple [CONFIG_DB](https://github.com/Azure/sonic-buildimage/files/5410041/config_db.zip)
[sonic_dump_r-tigris-13_20201020_161152.tar.gz](https://github.com/Azure/sonic-buildimage/files/5410046/sonic_dump_r-tigris-13_20201020_161152.tar.gz)

And have the next output:
``` 
root@r-tigris-13:/home/admin# config interface breakout Ethernet248 4x25G[10G] -v -y

Running Breakout Mode : 1x100G[40G]
Target Breakout Mode : 4x25G[10G]

Ports to be deleted :
 {
    "Ethernet248": "100000"
}
Ports to be added :
 {
    "Ethernet251": "25000",
    "Ethernet250": "25000",
    "Ethernet248": "25000",
    "Ethernet249": "25000"
}

After running Logic to limit the impact

Final list of ports to be deleted :
 {
    "Ethernet248": "100000"
}
Final list of ports to be added :
 {
    "Ethernet251": "25000",
    "Ethernet250": "25000",
    "Ethernet248": "25000",
    "Ethernet249": "25000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-extension', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-vlan', 'sonic-versions', 'sonic-breakout_cfg', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-crm']
Note: Below table(s) have no YANG models:
FLEX_COUNTER_TABLE, TELEMETRY, FEATURE,
Below Config can not be verified, It may cause harm to the system
 {}
Do you wish to Continue? [y/N]: y
[ERROR] Port breakout Failed!!! Opting Out
Failed to break out Port. Error:
``` 

But in logs I have the next error:

`Oct 20 12:13:24.070692 r-tigris-13 ERR ConfigMgmt: global name 'natsorted' is not defined`

Seems like there is something wrong with [config_mgmt.py](https://github.com/Azure/sonic-utilities/blob/b6af9f48e29852985137a57ff5396591af7f107c/config/config_mgmt.py).

@praveen-li Could you please suggest something?

**Comment by praveen-li** [comment]
@vadymhlushko-mlnx 

Kindly share var/log/syslog as well. 

natsorted is not used by config_mgmt, but it seems an internal library is using this package which is not installed on your switch. 

Natsort related change is merged 11 days ago via below PR : 
https://github.com/Azure/sonic-utilities/pull/1151. 
@jleveque for PR 1151.

for the time being maybe, if you install the PKGs yourself, it should work.

**Comment by vadymhlushko-mlnx** [comment]
> 
> 
> I have tried to get all YANG models (except [sonic-flex_counter.yang](https://github.com/Azure/sonic-buildimage/pull/4442/files#diff-b9f8e98f7abb53dc7b42c3d5e58e17e1b498012bfe577bb13410775adbda0285)) from [LINK](https://github.com/praveen-li/sonic-buildimage/tree/new_yang_models_msft/src/sonic-yang-models/yang-models).
> With very simple [CONFIG_DB](https://github.com/Azure/sonic-buildimage/files/5410041/config_db.zip)
> [sonic_dump_r-tigris-13_20201020_161152.tar.gz](https://github.com/Azure/sonic-buildimage/files/5410046/sonic_dump_r-tigris-13_20201020_161152.tar.gz)
> 
> And have the next output:
> 
> ```
> root@r-tigris-13:/home/admin# config interface breakout Ethernet248 4x25G[10G] -v -y
> 
> Running Breakout Mode : 1x100G[40G]
> Target Breakout Mode : 4x25G[10G]
> 
> Ports to be deleted :
>  {
>     "Ethernet248": "100000"
> }
> Ports to be added :
>  {
>     "Ethernet251": "25000",
>     "Ethernet250": "25000",
>     "Ethernet248": "25000",
>     "Ethernet249": "25000"
> }
> 
> After running Logic to limit the impact
> 
> Final list of ports to be deleted :
>  {
>     "Ethernet248": "100000"
> }
> Final list of ports to be added :
>  {
>     "Ethernet251": "25000",
>     "Ethernet250": "25000",
>     "Ethernet248": "25000",
>     "Ethernet249": "25000"
> }
> Loaded below Yang Models
> ['sonic-acl', 'sonic-extension', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-vlan', 'sonic-versions', 'sonic-breakout_cfg', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-crm']
> Note: Below table(s) have no YANG models:
> FLEX_COUNTER_TABLE, TELEMETRY, FEATURE,
> Below Config can not be verified, It may cause harm to the system
>  {}
> Do you wish to Continue? [y/N]: y
> [ERROR] Port breakout Failed!!! Opting Out
> Failed to break out Port. Error:
> ```
> 
> But in logs I have the next error:
> 
> `Oct 20 12:13:24.070692 r-tigris-13 ERR ConfigMgmt: global name 'natsorted' is not defined`
> 
> Seems like there is something wrong with [config_mgmt.py](https://github.com/Azure/sonic-utilities/blob/b6af9f48e29852985137a57ff5396591af7f107c/config/config_mgmt.py).
> 
> @praveen-li Could you please suggest something?

@praveen-li  
Latest logs [syslog.zip](https://github.com/Azure/sonic-buildimage/files/5416497/syslog.zip)

Also you can check `sonic_dump_r-tigris-13_20201020_161152.tar.gz` archive for the logs.

``` 
root@arc-switch1004:/home/admin# pip list | grep nat
natsort                      6.2.
```

As you can see, `natsort` is already installed, but I have tried again

```
root@arc-switch1004:/home/admin# pip install natsort
Requirement already satisfied: natsort in /usr/local/lib/python2.7/dist-packages (6.2.1)
root@arc-switch1004:/home/admin# pip3 install natsort
Requirement already satisfied: natsort in /usr/local/lib/python3.7/dist-packages (6.2.1)
```

And the output of breakout command the same as in previous comment.
Could you please suggest something?

**Comment by praveen5582** [comment]
@vadymhlushko-mlnx 

the logs shared are not from the same timestamp. ideally you should do timestamp before running command. Also natsort is not a problem here, ConfigMgmt is still going ahead. 

I think, we should schedule a debugging session to help you guys, Ask Anshu, I think 10.00 P.M. to 11.00 P.M. Friday should be good. Thx.

**Comment by vadymhlushko-mlnx** [comment]
> @vadymhlushko-mlnx
> 
> the logs shared are not from the same timestamp. ideally you should do timestamp before running command. Also natsort is not a problem here, ConfigMgmt is still going ahead.
> 
> I think, we should schedule a debugging session to help you guys, Ask Anshu, I think 10.00 P.M. to 11.00 P.M. Friday should be good. Thx.

@praveen5582, @praveen-li - could we set up a debug session on Monday (26 October) at any time that is suitable for you (we have a time zone GMT+3).

Also could you please provide me email or something else, so I can contact with Anshu?

**Comment by vadymhlushko-mlnx** [comment]
This issue divided into:

[[DPB] dynamic port breakout is not working because of the missing import library](https://github.com/Azure/sonic-buildimage/issues/6008)
[[sonic-config-engine/sonic-cfggen]: Fix natsort import.](https://github.com/Azure/sonic-buildimage/pull/5860)
[[DPB] dynamic port breakout configuration not present in CONFIG_DB after the image installation](https://github.com/Azure/sonic-buildimage/issues/6023)
[[DPB] wrong aliases for interfaces](https://github.com/Azure/sonic-buildimage/issues/6024)
[[DPB] Dynamic Port Breakout feature is not stable](https://github.com/Azure/sonic-buildimage/issues/6027)
