### ISSUE TITLE
[sonic-mgmt] ip command is not available in sonc-mgmt docker

### ISSUE THREAD

**Issue by Junchao-Mellanox** [Azure/sonic-buildimage#5425]
**Description**

After the commit https://github.com/Azure/sonic-buildimage/commit/2868a2793558353a912cd2d738c3a70bb4ef7dbf, ip command is no longer available in sonic-mgmt docker

**Steps to reproduce the issue:**
1.  Run sonic-mgmt dokcer and exec ip command

**Describe the results you received:**

```
johnar@e9444e101a63:~$ cat /etc/issue
Ubuntu 18.04.5 LTS \n \l

johnar@e9444e101a63:~$ ip
bash: ip: command not found
```

**Describe the results you expected:**

ip command should be available

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@daall , can you take a look at this one?

**Comment by daall** [comment]
Looks like a common issue w/ the 18.04 docker image. Looks like we just need to install iproute2.
