### ISSUE TITLE
test_po_cleanup is unstable on KVM

### ISSUE THREAD

**Issue by daall** [Azure/sonic-buildimage#5432]
**Description**

**Steps to reproduce the issue:**
1. Open a PR
2. Run the test_po_cleanup test

**Describe the results you received:**
Test fails frequently. See:

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/test_results_analyzer/

https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/sonic-mgmt-testing/job/sonic-mgmt-pr/test_results_analyzer/

https://github.com/Azure/sonic-buildimage/pull/5133#issuecomment-696891522

**Describe the results you expected:**
Test should pass consistently.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by daall** [comment]
@yxieca FYI

**Comment by abdosi** [comment]
Looking into this.

**Comment by lguohan** [comment]
https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/sonic-mgmt-testing/job/sonic-mgmt-pr/1429/testReport/junit/pc/test_po_cleanup/test_po_cleanup/

looks like we still consistently see this issue.

**Comment by abdosi** [comment]
@lguohan Sonic-swss submodule update PR is still not merged. 

https://github.com/Azure/sonic-buildimage/pull/5489
