### ISSUE TITLE
No such file or directory  #include <switch_sai_rpc_server.h>

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-buildimage#548]
```
syncd.h:20:35: fatal error: switch_sai_rpc_server.h: No such file or directory
 #include <switch_sai_rpc_server.h>
```
Build failure on p4 platform:
https://sonic-jenkins.westus.cloudapp.azure.com/job/p4/job/buildimage-p4-all-pr/649/console

**Comment by pavel-shirshov** [comment]
As soon as p4 will have libsaithrift the build will work.

**Comment by junghongkao** [comment]
This issue is related to #522 commit

**Comment by junghongkao** [comment]
Shuotian

Is this issue fixed yet ? I just saw that you close this.

Jim

**Comment by Rancho333** [comment]
```
In file included from syncd_saiswitch.cpp:1:0:
syncd.h:20:35: fatal error: switch_sai_rpc_server.h: No such file or directory
 #include <switch_sai_rpc_server.h>
```
I found this error in branch 201904, How to fix it?

**Comment by pavel-shirshov** [comment]
@Rancho333 How we can reproduce this?

**Comment by Rancho333** [comment]
@pavel-shirshov I run commands as follow:
```
1.sudo modprobe overlay
2.git checkout 201904
3.make init
4.make configure PLATFORM=centec
5make target/sonic-centec.bin
```
The attach file make-targetsonic-centec.bin.log with the error info is part of the whole logs.
[make-targetsonic-centec.bin.log](https://github.com/Azure/sonic-buildimage/files/3495032/make-targetsonic-centec.bin.log)

**Comment by pavel-shirshov** [comment]
Try to build the image broadcom?
If that works for you, you have an issue of dependency of LIBSAITHRIFT_DEV inside of sonic-buildimage
If it doesn't we need to check that further.

**Comment by pavel-shirshov** [comment]
Also check that you have libsaithrift-dev*.deb inside of the target dir

**Comment by Rancho333** [comment]
I did not found the libsaithrift-dev*.deb inside of the target dir. Am I
missing something?
[image: image.png]
And the broadcom is still in compile.I will let you konw when i  get the
result.

pavel-shirshov <notifications@github.com> 于2019年8月14日周三 上午6:05写道：

**Comment by Rancho333** [comment]
@pavel-shirshov Sorry, I'm doing something else in the meantime. I can make image of broadcom and do nothing special. Ha, I don't known what i have done,but now i have libsaithrift-dev*.deb inside of the target dir. So ，it's the issue of dependency of  LIBSAITHIRFT_DEV? How can i fix it?

**Comment by pavel-shirshov** [comment]
I can only suggest to check the difference between broadcom Makefiles and your platform Makefiles.
