### ISSUE TITLE
[pdk pde] Make initpde failed

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#5486]
**Description**

**Steps to reproduce the issue:**
```
1. make initpde
```
**Describe the results you received:**
```
make: *** No rule to make target 'initpde'.  Stop.
make[1]: *** [Makefile.work:233: initpde] Error 2
make[1]: Leaving directory '/home/sdk/ssp/sonic-buildimage'
make: *** [Makefile:8: initpde] Error 2
```

**Describe the results you expected:**
can integrate pde module into sonic.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
Please add link to the PR.

**Comment by tim-rj** [comment]
https://github.com/Azure/SONiC/pull/407

**Comment by ben-gale** [comment]
The code for this feature is not yet merged - see https://github.com/Azure/sonic-buildimage/pull/3778 - this is why you are seeing what you are seeing.
