### ISSUE TITLE
AS5712-54X operational status

### ISSUE THREAD

**Issue by mipxman** [Azure/sonic-buildimage#5494]
Hi Guys! 

according SONiC Supported Devices and Platforms list, on below link: 
[https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms]()

I install the latest Jenkins sonic installer bin on my as5712-54x, in the test environment my device detect 10G SFP+ module
`sonic#sudo sfputil show eeprom --dom -p Ethernet0`
, but It’s operational status always down!  I try to test my connections. All connections and links are tested in another device and it’s true. 
Also I try to use bcmsh (broadcom shell) to check PortStatus and etc but  my own test was failed
**_May I use a specific version of SONiC?_**

*/  HW: as5712-54x 
 Broadcom Tridenet2(BCM56850_A0) BCM56854_A2

**Comment by anshuv-mfst** [comment]
Which SONiC release version is this?
TD2 is verified, please check with 201911 image if issue persists. 
Please add output for show techsupport.

**Comment by mipxman** [comment]
Hi, Thanks. I try to install some OS from [Jenkins](https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/) the version 202006 , 201811, 201803 is same and I have a problem with physical layer! 
About 201911 version I install my own SONiC build and its not work correctly. I tested last version of Jenkins build of this version and share my experience in next two days.

For SONiC Version: 202006: 
![1](https://user-images.githubusercontent.com/66869651/94723707-0a57b600-0366-11eb-8961-76343486db8e.png)
![2](https://user-images.githubusercontent.com/66869651/94723709-0af04c80-0366-11eb-959a-56b0d23e7fa0.jpg)

**Comment by mipxman** [comment]
@anshuv-mfst I installed SONiC-201911  SONiC.HEAD.200-e9c2fdbf  but it is not different with other versions. the SFP+ 10Gbps modules not work correctly ! 
![B1](https://user-images.githubusercontent.com/66869651/94987449-54fa4d80-0573-11eb-861b-ddf7fc1b8243.png)
[sonic_dump_sonic_20161103_173105.tar.gz](https://github.com/Azure/sonic-buildimage/files/5321331/sonic_dump_sonic_20161103_173105.tar.gz)

**Comment by mipxman** [comment]
I found the problem sfp module_rx_los_ and module_tx_disable_ are true in my device. I edited manually 
`sudo echo "1" > /sys/bus/i2c/devices/1-0061/module_tx_disable_<port_number> `  #please check some module ports are in 1-0062 folder. 
or use the python script code to change it 
`accton_as5712_util.py set sfp <port_number> <0|1>`  #0:false 1:true 
`accton_as5712_util.py set sfp 1 0 `


I think we must change drivers code before building. @anshuv-mfst

**Comment by lamaral** [comment]
I just ran into this same problem with the version below:
```
SONiC Software Version: SONiC.master.246629-8fc8578c4
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: 8fc8578c4
Build date: Tue Apr  4 14:14:28 UTC 2023
Built by: AzDevOps@vmss-soni000SSB
```

Am I holding it wrong or is this issue still present?
