### ISSUE TITLE
orchagent crash after warm reboot

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#5521]
**Description**

**Steps to reproduce the issue:**
1. run nightly test on t0 topology
2.
3.

**Describe the results you received:**
orchagent crashed after warm reboot and test failed. The DUT was left on failure state.

**Describe the results you expected:**
1. test pass

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
root@str-dx010-acs-4:/var/log# show version

SONiC Software Version: SONiC.master.425-4006ce71
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 4006ce71
Build date: Sun Sep 27 07:52:44 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100007
Uptime: 16:04:16 up  7:53,  1 user,  load average: 1.76, 1.70, 1.45

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                20617ff1849b        391MB
docker-teamd                  master.425-4006ce71   20617ff1849b        391MB
docker-sonic-mgmt-framework   latest                04e712b877e4        486MB
docker-sonic-mgmt-framework   master.425-4006ce71   04e712b877e4        486MB
docker-router-advertiser      latest                793cb0e5c2fa        359MB
docker-router-advertiser      master.425-4006ce71   793cb0e5c2fa        359MB
docker-platform-monitor       latest                f867f6e00a19        434MB
docker-platform-monitor       master.425-4006ce71   f867f6e00a19        434MB
docker-lldp                   latest                2ec74daaf081        388MB
docker-lldp                   master.425-4006ce71   2ec74daaf081        388MB
docker-dhcp-relay             latest                56b4112e9427        366MB
docker-dhcp-relay             master.425-4006ce71   56b4112e9427        366MB
docker-database               latest                32598ba6c32e        359MB
docker-database               master.425-4006ce71   32598ba6c32e        359MB
docker-orchagent              latest                bd1d90cb1a3f        405MB
docker-orchagent              master.425-4006ce71   bd1d90cb1a3f        405MB
docker-nat                    latest                de766da20285        394MB
docker-nat                    master.425-4006ce71   de766da20285        394MB
docker-sonic-telemetry        latest                3d34711e992d        429MB
docker-sonic-telemetry        master.425-4006ce71   3d34711e992d        429MB
docker-fpm-frr                latest                b79fad0eb74e        407MB
docker-fpm-frr                master.425-4006ce71   b79fad0eb74e        407MB
docker-sflow                  latest                418e8407b585        395MB
docker-sflow                  master.425-4006ce71   418e8407b585        395MB
docker-snmp                   latest                075ee0d414ab        399MB
docker-snmp                   master.425-4006ce71   075ee0d414ab        399MB
docker-syncd-brcm             latest                b93785e0dca0        447MB
docker-syncd-brcm             master.425-4006ce71   b93785e0dca0        447MB    ```

    **Attach debug file `sudo generate_dump`:**

    ```
file is too big to upload.
Oct  1 11:20:58.849988 str-dx010-acs-4 INFO snmp#supervisord 2020-10-01 11:20:53,345 INFO exited: dependent-startup (exit status 0; expected)
Oct  1 11:21:01.930612 str-dx010-acs-4 INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::system_error'
Oct  1 11:21:01.931081 str-dx010-acs-4 INFO swss#supervisord: orchagent   what():  Resource deadlock avoided
Oct  1 11:21:02.007895 str-dx010-acs-4 DEBUG core_uploader.py: core_uploader.py: Received create event - /var/core/orchagent.1601551261.105.core.gz
    ```

**Comment by yxieca** [comment]
system is unable to self healing because config reload is failing:

root@str-dx010-acs-4:/var/log# sudo config reload -y
Executing stop of service telemetry...
Failed to stop telemetry.service: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
See system logs and 'systemctl status telemetry.service' for details.

**Comment by shi-su** [comment]
These two PRs meant to fix orchagent crash after warm-reboot: https://github.com/Azure/sonic-sairedis/pull/668 and https://github.com/Azure/sonic-sairedis/pull/664.

**Comment by vaibhavhd** [comment]
This error is not seen on vsimage and on physical DUT. There is another OA crash seen after warm-reboot which is tracked under https://github.com/Azure/sonic-buildimage/issues/6069
