### ISSUE TITLE
Command "show interfaces neighbor expected" doesn't show all interfaces

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#5526]
**Description**

**Steps to reproduce the issue:**
1. run test iface_namingmode/test_iface_namingmode.py::test_show_interfaces_neighbor_expected
2.
3.

**Describe the results you received:**
Both alias and default mode are failing

**Describe the results you expected:**
Both alias and default mode are passing

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
SONiC Software Version: SONiC.20191130.50
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: fb8dbcdd3
Build date: Wed Sep 30 23:47:35 UTC 2020
Built by: sonicbld@jenkins-slave-phx-2

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B018B03BY100009
Uptime: 00:07:05 up  8:54,  1 user,  load average: 0.93, 1.25, 1.07

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-snmp-sv2            20191130.50         8028250707ba        348MB
docker-snmp-sv2            latest              8028250707ba        348MB
docker-fpm-frr             20191130.50         f4baba63a326        335MB
docker-fpm-frr             latest              f4baba63a326        335MB
docker-acms                20191130.50         7dd0a1672d04        182MB
docker-acms                latest              7dd0a1672d04        182MB
docker-lldp-sv2            20191130.50         f0ba69be6205        312MB
docker-lldp-sv2            latest              f0ba69be6205        312MB
docker-orchagent           20191130.50         627673b32849        333MB
docker-orchagent           latest              627673b32849        333MB
docker-teamd               20191130.50         c0cd4579c21d        314MB
docker-teamd               latest              c0cd4579c21d        314MB
docker-syncd-brcm          20191130.50         38d2e8f41d91        436MB
docker-syncd-brcm          latest              38d2e8f41d91        436MB
docker-platform-monitor    20191130.50         77d4b95e5eaa        357MB
docker-platform-monitor    latest              77d4b95e5eaa        357MB
docker-sonic-telemetry     20191130.50         3130b2643362        353MB
docker-sonic-telemetry     latest              3130b2643362        353MB
docker-database            20191130.50         ef988f7f6dc3        289MB
docker-database            latest              ef988f7f6dc3        289MB
docker-dhcp-relay          20191130.50         2659b59c9097        299MB
docker-dhcp-relay          latest              2659b59c9097        299MB
docker-router-advertiser   20191130.50         9985f9526e08        289MB
docker-router-advertiser   latest              9985f9526e08        289MB
k8s.gcr.io/pause           3.2                 80d28bedfe5d        683kB    ```

    **Attach debug file `sudo generate_dump`:**

Not log file. I think the issue here is that "show interfaces neighbor expected" is not showing all interfaces. From looking at the diff. I think for all dual member lags, only one lag member showed up in the output. E.g. Ethernet0 and Ethernet4. Only Ethernet4 showed up.

```
admin@str-dx010-acs-1:~$ lldpshow 
Capability codes: (R) Router, (B) Bridge, (O) Other
LocalPort    RemoteDevice    RemotePortID    Capability    RemotePortDescr
-----------  --------------  --------------  ------------  -----------------
Ethernet0    ARISTA01T2      Ethernet1       BR
Ethernet4    ARISTA01T2      Ethernet2       BR
Ethernet8    ARISTA03T2      Ethernet1       BR
Ethernet12   ARISTA03T2      Ethernet2       BR
Ethernet16   ARISTA05T2      Ethernet1       BR
Ethernet20   ARISTA05T2      Ethernet2       BR
Ethernet24   ARISTA07T2      Ethernet1       BR
Ethernet28   ARISTA07T2      Ethernet2       BR
Ethernet32   ARISTA09T2      Ethernet1       BR
Ethernet36   ARISTA09T2      Ethernet2       BR
Ethernet40   ARISTA11T2      Ethernet1       BR
Ethernet44   ARISTA11T2      Ethernet2       BR
Ethernet48   ARISTA13T2      Ethernet1       BR
Ethernet52   ARISTA13T2      Ethernet2       BR
Ethernet56   ARISTA15T2      Ethernet1       BR
Ethernet60   ARISTA15T2      Ethernet2       BR
Ethernet64   ARISTA01T0      Ethernet1       BR
Ethernet68   ARISTA02T0      Ethernet1       BR
Ethernet72   ARISTA03T0      Ethernet1       BR
Ethernet76   ARISTA04T0      Ethernet1       BR
Ethernet80   ARISTA05T0      Ethernet1       BR
Ethernet84   ARISTA06T0      Ethernet1       BR
Ethernet88   ARISTA07T0      Ethernet1       BR
Ethernet92   ARISTA08T0      Ethernet1       BR
Ethernet96   ARISTA09T0      Ethernet1       BR
Ethernet100  ARISTA10T0      Ethernet1       BR
Ethernet104  ARISTA11T0      Ethernet1       BR
Ethernet108  ARISTA12T0      Ethernet1       BR
Ethernet112  ARISTA13T0      Ethernet1       BR
Ethernet116  ARISTA14T0      Ethernet1       BR
Ethernet120  ARISTA15T0      Ethernet1       BR
Ethernet124  ARISTA16T0      Ethernet1       BR
eth0         2200-ACS-1      ge-0/0/35       BR            ge-0/0/35.0
--------------------------------------------------
Total entries displayed:  33
admin@str-dx010-acs-1:~$ show interfaces neighbor expected 
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet64   ARISTA01T0  Ethernet1       None                10.64.246.168   ToRRouter
Ethernet4    ARISTA01T2  Ethernet2       None                10.64.246.160   SpineRouter
Ethernet68   ARISTA02T0  Ethernet1       None                10.64.246.169   ToRRouter
Ethernet72   ARISTA03T0  Ethernet1       None                10.64.246.170   ToRRouter
Ethernet12   ARISTA03T2  Ethernet2       None                10.64.246.161   SpineRouter
Ethernet76   ARISTA04T0  Ethernet1       None                10.64.246.171   ToRRouter
Ethernet80   ARISTA05T0  Ethernet1       None                10.64.246.172   ToRRouter
Ethernet20   ARISTA05T2  Ethernet2       None                10.64.246.162   SpineRouter
Ethernet84   ARISTA06T0  Ethernet1       None                10.64.246.173   ToRRouter
Ethernet88   ARISTA07T0  Ethernet1       None                10.64.246.174   ToRRouter
Ethernet28   ARISTA07T2  Ethernet2       None                10.64.246.163   SpineRouter
Ethernet92   ARISTA08T0  Ethernet1       None                10.64.246.175   ToRRouter
Ethernet96   ARISTA09T0  Ethernet1       None                10.64.246.176   ToRRouter
Ethernet36   ARISTA09T2  Ethernet2       None                10.64.246.164   SpineRouter
Ethernet100  ARISTA10T0  Ethernet1       None                10.64.246.177   ToRRouter
Ethernet104  ARISTA11T0  Ethernet1       None                10.64.246.178   ToRRouter
Ethernet44   ARISTA11T2  Ethernet2       None                10.64.246.165   SpineRouter
Ethernet108  ARISTA12T0  Ethernet1       None                10.64.246.179   ToRRouter
Ethernet112  ARISTA13T0  Ethernet1       None                10.64.246.180   ToRRouter
Ethernet52   ARISTA13T2  Ethernet2       None                10.64.246.166   SpineRouter
Ethernet116  ARISTA14T0  Ethernet1       None                10.64.246.181   ToRRouter
Ethernet120  ARISTA15T0  Ethernet1       None                10.64.246.182   ToRRouter
Ethernet60   ARISTA15T2  Ethernet2       None                10.64.246.167   SpineRouter
Ethernet124  ARISTA16T0  Ethernet1       None                10.64.246.183   ToRRouter
admin@str-dx010-acs-1:~$ show interfaces neighbor expected | grep Ether | wc -l
24
admin@str-dx010-acs-1:~$ lldpshow | grep Ether | wc -l
32
admin@str-dx010-acs-1:~$ sudo teamshow 
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  ---------------------------
 0002  PortChannel0002  LACP(A)(Up)  Ethernet0(S) Ethernet4(S)
 0005  PortChannel0005  LACP(A)(Up)  Ethernet8(S) Ethernet12(S)
 0008  PortChannel0008  LACP(A)(Up)  Ethernet20(S) Ethernet16(S)
 0011  PortChannel0011  LACP(A)(Up)  Ethernet28(S) Ethernet24(S)
 0014  PortChannel0014  LACP(A)(Up)  Ethernet32(S) Ethernet36(S)
 0017  PortChannel0017  LACP(A)(Up)  Ethernet44(S) Ethernet40(S)
 0020  PortChannel0020  LACP(A)(Up)  Ethernet52(S) Ethernet48(S)
 0023  PortChannel0023  LACP(A)(Up)  Ethernet60(S) Ethernet56(S)
 ```

**Comment by yxieca** [comment]
This is also a master branch issue. Confirmed with image:
Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100005
Uptime: 00:13:30 up  9:16,  1 user,  load average: 1.39, 2.25, 2.34

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                20617ff1849b        391MB
docker-teamd                  master.425-4006ce71   20617ff1849b        391MB
docker-sonic-mgmt-framework   latest                04e712b877e4        486MB
docker-sonic-mgmt-framework   master.425-4006ce71   04e712b877e4        486MB
docker-router-advertiser      latest                793cb0e5c2fa        359MB
docker-router-advertiser      master.425-4006ce71   793cb0e5c2fa        359MB
docker-platform-monitor       latest                f867f6e00a19        434MB
docker-platform-monitor       master.425-4006ce71   f867f6e00a19        434MB
docker-lldp                   latest                2ec74daaf081        388MB
docker-lldp                   master.425-4006ce71   2ec74daaf081        388MB
docker-dhcp-relay             latest                56b4112e9427        366MB
docker-dhcp-relay             master.425-4006ce71   56b4112e9427        366MB
docker-database               latest                32598ba6c32e        359MB
docker-database               master.425-4006ce71   32598ba6c32e        359MB
docker-orchagent              latest                bd1d90cb1a3f        405MB
docker-orchagent              master.425-4006ce71   bd1d90cb1a3f        405MB
docker-nat                    latest                de766da20285        394MB
docker-nat                    master.425-4006ce71   de766da20285        394MB
docker-sonic-telemetry        latest                3d34711e992d        429MB
docker-sonic-telemetry        master.425-4006ce71   3d34711e992d        429MB
docker-fpm-frr                latest                b79fad0eb74e        407MB
docker-fpm-frr                master.425-4006ce71   b79fad0eb74e        407MB
docker-sflow                  latest                418e8407b585        395MB
docker-sflow                  master.425-4006ce71   418e8407b585        395MB
docker-snmp                   latest                075ee0d414ab        399MB
docker-snmp                   master.425-4006ce71   075ee0d414ab        399MB
docker-syncd-brcm             latest                b93785e0dca0        447MB
docker-syncd-brcm             master.425-4006ce71   b93785e0dca0        447MB

**Comment by lguohan** [comment]
@yxieca , i checked, it looks like this is an issue for 201911 image as well.

```
admin@str-dx010-acs-1:~$ show interfaces neighbor expected 
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet64   ARISTA01T0  Ethernet1       None                10.64.246.168   ToRRouter
Ethernet4    ARISTA01T2  Ethernet2       None                10.64.246.160   SpineRouter
Ethernet68   ARISTA02T0  Ethernet1       None                10.64.246.169   ToRRouter
Ethernet72   ARISTA03T0  Ethernet1       None                10.64.246.170   ToRRouter
Ethernet12   ARISTA03T2  Ethernet2       None                10.64.246.161   SpineRouter
Ethernet76   ARISTA04T0  Ethernet1       None                10.64.246.171   ToRRouter
Ethernet80   ARISTA05T0  Ethernet1       None                10.64.246.172   ToRRouter
Ethernet20   ARISTA05T2  Ethernet2       None                10.64.246.162   SpineRouter
Ethernet84   ARISTA06T0  Ethernet1       None                10.64.246.173   ToRRouter
Ethernet88   ARISTA07T0  Ethernet1       None                10.64.246.174   ToRRouter
Ethernet28   ARISTA07T2  Ethernet2       None                10.64.246.163   SpineRouter
Ethernet92   ARISTA08T0  Ethernet1       None                10.64.246.175   ToRRouter
Ethernet96   ARISTA09T0  Ethernet1       None                10.64.246.176   ToRRouter
Ethernet36   ARISTA09T2  Ethernet2       None                10.64.246.164   SpineRouter
Ethernet100  ARISTA10T0  Ethernet1       None                10.64.246.177   ToRRouter
Ethernet104  ARISTA11T0  Ethernet1       None                10.64.246.178   ToRRouter
Ethernet44   ARISTA11T2  Ethernet2       None                10.64.246.165   SpineRouter
Ethernet108  ARISTA12T0  Ethernet1       None                10.64.246.179   ToRRouter
Ethernet112  ARISTA13T0  Ethernet1       None                10.64.246.180   ToRRouter
Ethernet52   ARISTA13T2  Ethernet2       None                10.64.246.166   SpineRouter
Ethernet116  ARISTA14T0  Ethernet1       None                10.64.246.181   ToRRouter
Ethernet120  ARISTA15T0  Ethernet1       None                10.64.246.182   ToRRouter
Ethernet60   ARISTA15T2  Ethernet2       None                10.64.246.167   SpineRouter
Ethernet124  ARISTA16T0  Ethernet1       None                10.64.246.183   ToRRouter
admin@str-dx010-acs-1:~$ sudo teamshow
```
