### ISSUE TITLE
orchagent continuously prints out "set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS"

### ISSUE THREAD

**Issue by daall** [Azure/sonic-buildimage#5570]
**Description**
Orchagent continually sprays this message to the syslog:
```
set: setting attribute 0x10000004 status: SAI_STATUS_SUCCESS
```

Which causes this to occur:
```
Oct  9 00:33:00.374116 sonic INFO swss#rsyslogd: imuxsock[pid: 42, name: /usr/bin/orchagent] from <sonic:orchagent>: begin to drop messages due to rate-limiting
Oct  9 00:36:57.412514 sonic INFO swss#rsyslogd: imuxsock[pid: 42, name: /usr/bin/orchagent]: 32511 messages lost due to rate-limiting
```

Which masks legitimate syslog messages from orchagent (e.g. "create ACL table foo").

**Steps to reproduce the issue:**
1. Start the DUT.
2. Check the syslog.

**Describe the results you received:**
```
Oct  9 00:33:00.374116 sonic INFO swss#rsyslogd: imuxsock[pid: 42, name: /usr/bin/orchagent] from <sonic:orchagent>: begin to drop messages due to rate-limiting
Oct  9 00:36:57.412514 sonic INFO swss#rsyslogd: imuxsock[pid: 42, name: /usr/bin/orchagent]: 32511 messages lost due to rate-limiting
```

**Describe the results you expected:**
There shouldn't be any throttling/need to throttle while orchagent is idle and no updates are being received from neighbors/bgp/etc.

**Comment by theasianpianist** [comment]
From what I can tell, the SAI_STATUS_SUCCESS message does not seem to be causing the rate limiting. Will continue investigating.

@daall next time you notice this, can you `grep` for "begin to drop messages" in your syslogs?
