### ISSUE TITLE
[SNMP] ifMIB ifAlias show wrong output

### ISSUE THREAD

**Issue by henzelis** [Azure/sonic-buildimage#5591]
**Description**

ifAlias OID of the ifMIB shows the wrong output. According to the RFC2863:

This object is an 'alias' name for the interface as
specified by a network manager, and provides a non-volatile
'handle' for the interface.

**Steps to reproduce the issue:**
1. Run on DUT show interface status
2. Run snmp query to DUT:
 snmpwalk -v 2c -c public <IP.ADDRESS> 1.3.6.1.2.1.31.1.1.1.18
3. Observe empty strings instead of Aliases.

**Describe the results you received:**
```
 # snmpwalk -v 2c -c public 127.0.0.1 1.3.6.1.2.1.31.1.1.1.18
iso.3.6.1.2.1.31.1.1.1.18.1 = ""
iso.3.6.1.2.1.31.1.1.1.18.5 = ""
iso.3.6.1.2.1.31.1.1.1.18.9 = "" <-------EMPTY OUTPUT
iso.3.6.1.2.1.31.1.1.1.18.13 = ""
iso.3.6.1.2.1.31.1.1.1.18.17 = ""
iso.3.6.1.2.1.31.1.1.1.18.21 = ""
iso.3.6.1.2.1.31.1.1.1.18.25 = ""
iso.3.6.1.2.1.31.1.1.1.18.29 = ""
iso.3.6.1.2.1.31.1.1.1.18.33 = ""
iso.3.6.1.2.1.31.1.1.1.18.37 = ""
iso.3.6.1.2.1.31.1.1.1.18.41 = ""
iso.3.6.1.2.1.31.1.1.1.18.45 = ""
iso.3.6.1.2.1.31.1.1.1.18.49 = ""
iso.3.6.1.2.1.31.1.1.1.18.53 = ""
iso.3.6.1.2.1.31.1.1.1.18.57 = ""
iso.3.6.1.2.1.31.1.1.1.18.61 = ""
iso.3.6.1.2.1.31.1.1.1.18.65 = ""
iso.3.6.1.2.1.31.1.1.1.18.69 = ""
iso.3.6.1.2.1.31.1.1.1.18.73 = ""
iso.3.6.1.2.1.31.1.1.1.18.77 = ""
iso.3.6.1.2.1.31.1.1.1.18.81 = ""
iso.3.6.1.2.1.31.1.1.1.18.85 = ""
iso.3.6.1.2.1.31.1.1.1.18.89 = ""
iso.3.6.1.2.1.31.1.1.1.18.93 = ""
iso.3.6.1.2.1.31.1.1.1.18.97 = ""
iso.3.6.1.2.1.31.1.1.1.18.101 = ""
iso.3.6.1.2.1.31.1.1.1.18.105 = ""
iso.3.6.1.2.1.31.1.1.1.18.109 = ""
iso.3.6.1.2.1.31.1.1.1.18.113 = ""
iso.3.6.1.2.1.31.1.1.1.18.117 = ""
iso.3.6.1.2.1.31.1.1.1.18.121 = ""
iso.3.6.1.2.1.31.1.1.1.18.125 = ""
```

**Describe the results you expected:**
```
# snmpwalk -v 2c -c public 127.0.0.1 1.3.6.1.2.1.31.1.1.1.18
iso.3.6.1.2.1.31.1.1.1.18.1 = STRING: "etp1"
iso.3.6.1.2.1.31.1.1.1.18.5 = STRING: "etp2"
iso.3.6.1.2.1.31.1.1.1.18.9 = STRING: "etp3" <-----ALIASES SUPPOSED TO BE THERE
iso.3.6.1.2.1.31.1.1.1.18.13 = STRING: "etp4"
iso.3.6.1.2.1.31.1.1.1.18.17 = STRING: "etp5"
iso.3.6.1.2.1.31.1.1.1.18.21 = STRING: "etp6"
iso.3.6.1.2.1.31.1.1.1.18.25 = STRING: "etp7"
iso.3.6.1.2.1.31.1.1.1.18.29 = STRING: "etp8"
iso.3.6.1.2.1.31.1.1.1.18.33 = STRING: "etp9"
iso.3.6.1.2.1.31.1.1.1.18.37 = STRING: "etp10"
iso.3.6.1.2.1.31.1.1.1.18.41 = STRING: "etp11"
iso.3.6.1.2.1.31.1.1.1.18.45 = STRING: "etp12"
iso.3.6.1.2.1.31.1.1.1.18.49 = STRING: "etp13"
iso.3.6.1.2.1.31.1.1.1.18.53 = STRING: "etp14"
iso.3.6.1.2.1.31.1.1.1.18.57 = STRING: "etp15"
iso.3.6.1.2.1.31.1.1.1.18.61 = STRING: "etp16"
iso.3.6.1.2.1.31.1.1.1.18.65 = STRING: "etp17"
iso.3.6.1.2.1.31.1.1.1.18.69 = STRING: "etp18"
iso.3.6.1.2.1.31.1.1.1.18.73 = STRING: "etp19"
iso.3.6.1.2.1.31.1.1.1.18.77 = STRING: "etp20"
iso.3.6.1.2.1.31.1.1.1.18.81 = STRING: "etp21"
iso.3.6.1.2.1.31.1.1.1.18.85 = STRING: "etp22"
iso.3.6.1.2.1.31.1.1.1.18.89 = STRING: "etp23"
iso.3.6.1.2.1.31.1.1.1.18.93 = STRING: "etp24"
iso.3.6.1.2.1.31.1.1.1.18.97 = STRING: "etp25"
iso.3.6.1.2.1.31.1.1.1.18.101 = STRING: "etp26"
iso.3.6.1.2.1.31.1.1.1.18.105 = STRING: "etp27"
iso.3.6.1.2.1.31.1.1.1.18.109 = STRING: "etp28"
iso.3.6.1.2.1.31.1.1.1.18.113 = STRING: "etp29"
iso.3.6.1.2.1.31.1.1.1.18.117 = STRING: "etp30"
iso.3.6.1.2.1.31.1.1.1.18.121 = STRING: "etp31"
iso.3.6.1.2.1.31.1.1.1.18.125 = STRING: "etp32
````

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
   SONiC.201911.0-8e0d4c04
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 8e0d4c04
Build date: Fri Sep 25 04:56:55 UTC 2020
Built by: stephens@arc-build-server-2

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
[sonic_dump_r-qa-sw-eth-2134_20201002_121528.tar.gz](https://github.com/Azure/sonic-buildimage/files/5363480/sonic_dump_r-qa-sw-eth-2134_20201002_121528.tar.gz)

    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by SuvarnaMeenakshi** [comment]
@henzelis This output should be "interface description" and not "alias". This is not a recent change and has been the case in SONiC.
https://github.com/Azure/sonic-snmpagent/blob/6e4a796b245a99da29f8390fe01d09a37d32ec4f/src/sonic_ax_impl/mibs/ietf/rfc2863.py#L146
Again, "show interfaces description"  output will help verify, the snmp output in the MIB should match "Description" column.

**Comment by henzelis** [comment]
I configure the descriptions and output exactly show "Descriptions":

`root@r-ethernet-sw230:/home/admin# show int description 
  Interface    Oper    Admin    Alias    Description
-----------  ------  -------  -------  -------------
  Ethernet0      up       up     etp1         To SW1
  Ethernet4    down       up     etp2        To Core
  Ethernet8      up       up     etp3         To SW2
 Ethernet12    down       up     etp4            N/A
 Ethernet16    down       up     etp5            N/A
 Ethernet20    down       up     etp6            N/A
 Ethernet24    down       up     etp7            N/A
 Ethernet28    down       up     etp8            N/A
 Ethernet32    down       up     etp9            N/A
 Ethernet36    down       up    etp10            N/A
 Ethernet40    down       up    etp11            N/A
 Ethernet44    down       up    etp12            N/A
 Ethernet48    down       up    etp13            N/A
 Ethernet52    down       up    etp14            N/A
 Ethernet56    down       up    etp15            N/A
 Ethernet60    down       up    etp16            N/A`

snmpwalk -v 2c -c public 127.0.0.1 1.3.6.1.2.1.31.1.1.1.18
iso.3.6.1.2.1.31.1.1.1.18.1 = STRING: "To SW1"
iso.3.6.1.2.1.31.1.1.1.18.5 = STRING: "To Core"
iso.3.6.1.2.1.31.1.1.1.18.9 = STRING: "To SW2"
iso.3.6.1.2.1.31.1.1.1.18.13 = ""
iso.3.6.1.2.1.31.1.1.1.18.17 = ""
iso.3.6.1.2.1.31.1.1.1.18.21 = ""
iso.3.6.1.2.1.31.1.1.1.18.25 = ""
iso.3.6.1.2.1.31.1.1.1.18.29 = ""
iso.3.6.1.2.1.31.1.1.1.18.33 = ""
iso.3.6.1.2.1.31.1.1.1.18.37 = ""
iso.3.6.1.2.1.31.1.1.1.18.41 = ""
iso.3.6.1.2.1.31.1.1.1.18.45 = ""
iso.3.6.1.2.1.31.1.1.1.18.49 = ""
iso.3.6.1.2.1.31.1.1.1.18.53 = ""
iso.3.6.1.2.1.31.1.1.1.18.57 = ""
iso.3.6.1.2.1.31.1.1.1.18.61 = ""

But for a clear of SNMP implementation in SONiC can you provide information about OIDs for aliases of interfaces?

**Comment by henzelis** [comment]
Thank you for your answers and explanation. I will know that ifAlias shows descriptions and not aliases and this behaviour is expected.
