### ISSUE TITLE
[SNMP] ifMIB ifName show wrong output

### ISSUE THREAD

**Issue by henzelis** [Azure/sonic-buildimage#5592]
**Description**

SNMP ifMIB ifName output shows the wrong output - Alias of interface names instead of Names as required by RFC2863.
RFC2863:
"The textual name of the interface. The value of this
object should be the name of the interface as assigned by
the local device and should be suitable for use in commands
entered at the device's console'."

**Steps to reproduce the issue:**
1. Run on DUT show interface status
2. Run snmp query to DUT:
snmpwalk -v 2c -c public <IP.ADDRESS> 1.3.6.1.2.1.31.1.1.1.1
3. Observe that the output of OID contains Aliases instead of Names

**Describe the results you received:**
```
#  snmpwalk -v 2c -c public <IP.ADDRESS> 1.3.6.1.2.1.31.1.1.1.1
iso.3.6.1.2.1.31.1.1.1.1.1 = STRING: "etp1"   <-----IT SHOWS ALIASES NOT NAMES AS REQUIRED
iso.3.6.1.2.1.31.1.1.1.1.5 = STRING: "etp2"
iso.3.6.1.2.1.31.1.1.1.1.9 = STRING: "etp3"
iso.3.6.1.2.1.31.1.1.1.1.13 = STRING: "etp4"
iso.3.6.1.2.1.31.1.1.1.1.17 = STRING: "etp5"
iso.3.6.1.2.1.31.1.1.1.1.21 = STRING: "etp6"
iso.3.6.1.2.1.31.1.1.1.1.25 = STRING: "etp7"
iso.3.6.1.2.1.31.1.1.1.1.29 = STRING: "etp8"
iso.3.6.1.2.1.31.1.1.1.1.33 = STRING: "etp9"
iso.3.6.1.2.1.31.1.1.1.1.37 = STRING: "etp10"
iso.3.6.1.2.1.31.1.1.1.1.41 = STRING: "etp11"
iso.3.6.1.2.1.31.1.1.1.1.45 = STRING: "etp12"
iso.3.6.1.2.1.31.1.1.1.1.49 = STRING: "etp13"
iso.3.6.1.2.1.31.1.1.1.1.53 = STRING: "etp14"
iso.3.6.1.2.1.31.1.1.1.1.57 = STRING: "etp15"
iso.3.6.1.2.1.31.1.1.1.1.61 = STRING: "etp16"
iso.3.6.1.2.1.31.1.1.1.1.65 = STRING: "etp17"
iso.3.6.1.2.1.31.1.1.1.1.69 = STRING: "etp18"
iso.3.6.1.2.1.31.1.1.1.1.73 = STRING: "etp19"
iso.3.6.1.2.1.31.1.1.1.1.77 = STRING: "etp20"
iso.3.6.1.2.1.31.1.1.1.1.81 = STRING: "etp21"
iso.3.6.1.2.1.31.1.1.1.1.85 = STRING: "etp22"
iso.3.6.1.2.1.31.1.1.1.1.89 = STRING: "etp23"
iso.3.6.1.2.1.31.1.1.1.1.93 = STRING: "etp24"
iso.3.6.1.2.1.31.1.1.1.1.97 = STRING: "etp25"
iso.3.6.1.2.1.31.1.1.1.1.101 = STRING: "etp26"
iso.3.6.1.2.1.31.1.1.1.1.105 = STRING: "etp27"
iso.3.6.1.2.1.31.1.1.1.1.109 = STRING: "etp28"
iso.3.6.1.2.1.31.1.1.1.1.113 = STRING: "etp29"
iso.3.6.1.2.1.31.1.1.1.1.117 = STRING: "etp30"
iso.3.6.1.2.1.31.1.1.1.1.121 = STRING: "etp31"
iso.3.6.1.2.1.31.1.1.1.1.125 = STRING: "etp32"
```

**Describe the results you expected:**
```
#  snmpwalk -v 2c -c public <IP.ADDRESS> 1.3.6.1.2.1.31.1.1.1.1
iso.3.6.1.2.1.31.1.1.1.1.1 = STRING:  "Ethernet0" 
iso.3.6.1.2.1.31.1.1.1.1.5 = STRING:  "Ethernet4" 
iso.3.6.1.2.1.31.1.1.1.1.9 = STRING:  "Ethernet8" 
iso.3.6.1.2.1.31.1.1.1.1.13 = STRING:  "Ethernet12"
iso.3.6.1.2.1.31.1.1.1.1.17 = STRING:  "Ethernet16"
iso.3.6.1.2.1.31.1.1.1.1.21 = STRING:  "Ethernet20"
iso.3.6.1.2.1.31.1.1.1.1.25 = STRING:  "Ethernet24"
iso.3.6.1.2.1.31.1.1.1.1.29 = STRING:  "Ethernet28"
iso.3.6.1.2.1.31.1.1.1.1.33 = STRING:  "Ethernet32"
iso.3.6.1.2.1.31.1.1.1.1.37 = STRING:  "Ethernet36"
iso.3.6.1.2.1.31.1.1.1.1.41 = STRING:  "Ethernet40"
iso.3.6.1.2.1.31.1.1.1.1.45 = STRING:  "Ethernet44"
iso.3.6.1.2.1.31.1.1.1.1.49 = STRING:  "Ethernet48"
iso.3.6.1.2.1.31.1.1.1.1.53 = STRING:  "Ethernet52"
iso.3.6.1.2.1.31.1.1.1.1.57 = STRING:  "Ethernet56"
iso.3.6.1.2.1.31.1.1.1.1.61 = STRING:  "Ethernet60"
iso.3.6.1.2.1.31.1.1.1.1.65 = STRING:  "Ethernet64"
iso.3.6.1.2.1.31.1.1.1.1.69 = STRING:  "Ethernet68"
iso.3.6.1.2.1.31.1.1.1.1.73 = STRING:  "Ethernet72"
iso.3.6.1.2.1.31.1.1.1.1.77 = STRING:  "Ethernet76"
iso.3.6.1.2.1.31.1.1.1.1.81 = STRING:  "Ethernet80"
iso.3.6.1.2.1.31.1.1.1.1.85 = STRING:  "Ethernet84"
iso.3.6.1.2.1.31.1.1.1.1.89 = STRING:  "Ethernet88"
iso.3.6.1.2.1.31.1.1.1.1.93 = STRING:  "Ethernet92"
iso.3.6.1.2.1.31.1.1.1.1.97 = STRING:  "Ethernet96"
iso.3.6.1.2.1.31.1.1.1.1.101 = STRING:  "Ethernet100"
iso.3.6.1.2.1.31.1.1.1.1.105 = STRING:  "Ethernet104"
iso.3.6.1.2.1.31.1.1.1.1.109 = STRING:  "Ethernet108"
iso.3.6.1.2.1.31.1.1.1.1.113 = STRING:  "Ethernet112"
iso.3.6.1.2.1.31.1.1.1.1.117 = STRING:  "Ethernet116"
iso.3.6.1.2.1.31.1.1.1.1.121 = STRING:  "Ethernet120"
iso.3.6.1.2.1.31.1.1.1.1.125 = STRING:  "Ethernet124"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
SONiC.201911.0-8e0d4c04
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 8e0d4c04
Build date: Fri Sep 25 04:56:55 UTC 2020
Built by: stephens@arc-build-server-2

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
```

    **Attach debug file `sudo generate_dump`:**
[sonic_dump_r-qa-sw-eth-2134_20201002_121528.tar.gz](https://github.com/Azure/sonic-buildimage/files/5363543/sonic_dump_r-qa-sw-eth-2134_20201002_121528.tar.gz)

**Comment by SuvarnaMeenakshi** [comment]
@henzelis Can you check the output of CLI "show interfaces description".  Ideally, snmp output for the MIB should retrieve the alias from PORT table in APP_DB. So if the alias is not correctly configured, snmp output might not be as expected. "show interfaces description" will help understand the expected output.

**Comment by henzelis** [comment]
Output is here:
'''root@r-qa-sw-eth-2134:/home/admin# show int desc
  Interface    Oper    Admin    Alias    Description
-----------  ------  -------  -------  -------------
  Ethernet0    down       up     etp1            N/A
  Ethernet4    down       up     etp2            N/A
  Ethernet8    down       up     etp3            N/A
 Ethernet12    down       up     etp4            N/A
 Ethernet16    down       up     etp5            N/A
 Ethernet20    down       up     etp6            N/A
 Ethernet24    down       up     etp7            N/A
 Ethernet28    down       up     etp8            N/A
 Ethernet32    down       up     etp9            N/A
 Ethernet36    down       up    etp10            N/A
 Ethernet40    down       up    etp11            N/A
 Ethernet44    down       up    etp12            N/A
 Ethernet48    down       up    etp13            N/A
 Ethernet52    down       up    etp14            N/A
 Ethernet56    down       up    etp15            N/A
 Ethernet60    down       up    etp16            N/A
 Ethernet64    down       up    etp17            N/A
 Ethernet68    down       up    etp18            N/A
 Ethernet72    down       up    etp19            N/A
 Ethernet76    down       up    etp20            N/A
 Ethernet80    down       up    etp21            N/A
 Ethernet84    down       up    etp22            N/A
 Ethernet88    down       up    etp23            N/A
 Ethernet92    down       up    etp24            N/A
 Ethernet96    down       up    etp25            N/A
Ethernet100    down       up    etp26            N/A
Ethernet104    down       up    etp27            N/A
Ethernet108    down       up    etp28            N/A
Ethernet112      up       up    etp29            N/A
Ethernet116      up       up    etp30            N/A
Ethernet120    down       up    etp31            N/A
Ethernet124    down       up    etp32            N/A
```
Also, I suppose this information should be included in the dump file, provided previously...
As you can see - it looks like something wrong with MIB, name, and interface alias in the table show the correct output, but snmp provide information in an inverted manner.

**Comment by SuvarnaMeenakshi** [comment]
@henzelis looking at the above output, SNMP output looks correct. There is no issue here.
As I mentioned above, SNMP output should show "alias", which from the above output is "etp1/etp2..".
If you change the interface alias in config_db to , that should get reflected in SNMP output as well.
Looking at the above CLI output, I see that https://github.com/Azure/sonic-buildimage/issues/5591 - this is also not an issue. The Interface description is empty , hence SNMP is showing the right output.
I will close both the issues as they are not SNMP issues, but the expected behavior.

**Comment by Junchao-Mellanox** [comment]
See code here:
https://github.com/Azure/sonic-snmpagent/blob/6e4a796b245a99da29f8390fe01d09a37d32ec4f/src/sonic_ax_impl/mibs/ietf/rfc2863.py#L141
and here:
https://github.com/Azure/sonic-snmpagent/blob/6e4a796b245a99da29f8390fe01d09a37d32ec4f/src/sonic_ax_impl/mibs/ietf/rfc2863.py#L154

For ifName, it returns alias, for ifAlias, it returns description. From the comment of those method, it seems this is on purpose. See the code snippet:

```
def interface_alias(self, sub_id):
        """
        ifAlias specific - this is not the "Alias map".
        To be homogenous with what is available in the wild this should return the interface 'description'.
        :param sub_id: The 1-based sub-identifier query.
        :return: The  SONiC interface description, empty string if not defined.
        """
```

But we would like to understand the reason to do this.

**Comment by qiluo-msft** [comment]
@Junchao-Mellanox You may check the discussion https://github.com/Azure/sonic-snmpagent/pull/74#discussion_r208055665.
Basically the industry practice is not exactly matching the ifName/ifAlias/IfDesc "names" well. We implement as-is just to make the monitor system happy.

**Comment by Junchao-Mellanox** [comment]
@qiluo-msft Thanks for the information.
@henzelis I think Qi's comment answered our question, what do you think?

**Comment by henzelis** [comment]
Thank you for your answers and explanation. I will know that ifName shows aliases and this behavior is expected.
