### ISSUE TITLE
xcvrd print out error logs from initializeGlobalConfig call

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-buildimage#5680]
**Description**

**Steps to reproduce the issue:**
 Install a  recent 201911 image like SONiC.201911.209-bea968bb will see this issue from time to time.

**Describe the results you received:**
error log captured from the syslog:

> Oct 20 00:02:45.922548 arc-switch1025 ERR pmon#xcvrd[34]: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json
> Oct 20 00:03:42.371442 arc-switch1025 ERR pmon#xcvrd[34]: :- initializeGlobalConfig: SonicDBConfig Global config is already initialized
> Oct 20 00:11:46.062052 arc-switch1025 ERR pmon#xcvrd[35]: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json
> Oct 20 00:12:41.998294 arc-switch1025 ERR pmon#xcvrd[35]: :- initializeGlobalConfig: SonicDBConfig Global config is already initialized
> 
[syslog.9.gz](https://github.com/Azure/sonic-buildimage/files/5412780/syslog.9.gz)

**Describe the results you expected:**

there should be error logs

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
    SONiC Software Version: SONiC.201911.209-bea968bb  
    Distribution: Debian 9.13
    Kernel: 4.9.0-11-2-amd64
    Build commit: bea968bb
    Build date: Mon Oct  5 03:59:15 UTC 2020
    Built by: johnar@jenkins-worker-8
    
    Platform: x86_64-mlnx_msn2700-r0
    HwSKU: ACS-MSN2700
    ASIC: mellanox
    Serial Number: MT1822K07815
    Uptime: 01:30:44 up 15 min,  1 user,  load average: 3.77, 3.54, 2.41
    
    Docker images:
    REPOSITORY                    TAG                                     IMAGE ID            SIZE
    docker-syncd-mlnx             201911.209-bea968bb                     6547ab0ff53d        397MB
    docker-syncd-mlnx             latest                                  6547ab0ff53d        397MB
    docker-router-advertiser      201911.209-bea968bb                     c9b94e0a305c        289MB
    docker-router-advertiser      latest                                  c9b94e0a305c        289MB
    docker-sonic-mgmt-framework   201911.209-bea968bb                     375110592f83        431MB
    docker-sonic-mgmt-framework   latest                                  375110592f83        431MB
    docker-platform-monitor       201911.209-bea968bb                     64b5589857ec        664MB
    docker-platform-monitor       latest                                  64b5589857ec        664MB
    docker-fpm-frr                201911.209-bea968bb                     49dd163c9120        335MB
    docker-fpm-frr                latest                                  49dd163c9120        335MB
    docker-sflow                  201911.209-bea968bb                     439a39ec05e7        315MB
    docker-sflow                  latest                                  439a39ec05e7        315MB
    docker-lldp-sv2               201911.209-bea968bb                     29b7b19345c9        312MB
    docker-lldp-sv2               latest                                  29b7b19345c9        312MB
    docker-dhcp-relay             201911.209-bea968bb                     81d62dd22c60        299MB
    docker-dhcp-relay             latest                                  81d62dd22c60        299MB
    docker-database               201911.209-bea968bb                     52f86ffc0ca1        289MB
    docker-database               latest                                  52f86ffc0ca1        289MB
    docker-teamd                  201911.209-bea968bb                     bf98b3369925        315MB
    docker-teamd                  latest                                  bf98b3369925        315MB
    docker-snmp-sv2               201911.209-bea968bb                     b595057b162a        348MB
    docker-snmp-sv2               latest                                  b595057b162a        348MB
    docker-orchagent              201911.209-bea968bb                     a45bfd97ecf2        333MB
    docker-orchagent              latest                                  a45bfd97ecf2        333MB
    docker-nat                    201911.209-bea968bb                     fff136adffb1        316MB
    docker-nat                    latest                                  fff136adffb1        316MB
    docker-sonic-telemetry        201911.209-bea968bb                     aeb8ee6731d1        353MB
    docker-sonic-telemetry        latest                                  aeb8ee6731d1        353MB
    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by judyjoseph** [comment]
Initial update: 

Oct 20 00:02:45.922548 arc-switch1025 ERR pmon#xcvrd[34]: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json

>>>> This file database_global.json is not created in single ASIC platforms, hence this error message should not affect.
          Multi-asic platforms don’t have this error message. Will check how to suppress this error message in swsscommon.

Oct 20 00:03:42.371442 arc-switch1025 ERR pmon#xcvrd[34]: :- initializeGlobalConfig: SonicDBConfig Global config is already initialized

>>>  It is because the API initializeGlobalConfig() is called from the parent xcvrd process and its child threads. It is an INFO message and not an ERR, as it just tells the global config is initialized already. Will take care of it in xcvrd itself.

**Comment by judyjoseph** [comment]
Working on this !
