### ISSUE TITLE
Build fails on master branch

### ISSUE THREAD

**Issue by iMasaruOki** [Azure/sonic-buildimage#5692]
**Description**

Build fails on master branch.

**Steps to reproduce the issue:**
1. make all

**Describe the results you received:**

```
make: execvp: /bin/bash: Argument list too long
make: *** [http://slave.mk:389: target/debs/buster/sonic-device-data_1.0-1_all.deb] Error 127
```

**Describe the results you expected:**

build successful.

**Additional information you deem important (e.g. issue happens only occasionally):**

tested on ommit 97b33e4da

**Comment by iMasaruOki** [comment]
Only parallel build are affected.

**Comment by lguohan** [comment]
can you print out more information. what are those arguments?

**Comment by iMasaruOki** [comment]
I had misunderstanding the problem.

I'm tested some cases.
- In my (source is modified) tree, build fails with JOBS=1.  (note: dpkg cache are enabled)
- Build twice without clean are successful.

- In unmodified master, build successful.
- In master with JOBS=8 (without dpkg cache), build successful.
- In master with dpkg cache, build fails.

It seems to be dpkg cache problem.
I'll try remove all cache files and rebuild.

**Comment by lguohan** [comment]
check build failure here. https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-all-pr/5822/console

**Comment by lguohan** [comment]
@iMasaruOki , what cache mode are you using RWCACHE or RCACHE?
