### ISSUE TITLE
broadcom master image build broken for >10 days

### ISSUE THREAD

**Issue by daall** [Azure/sonic-buildimage#5729]
**Description**
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/ has broken for several days.

**Steps to reproduce the issue:**
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/448/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/450/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/452/
(and others)

**Describe the results you received:**
(trimmed for brevity, see one of the above links for full failure output)
```
14:11:21.851  g++ -I/usr/include/sai -I. -std=c++11 -DFORCE_BOOST_SMART_PTR -c src/gen-cpp/switch_sai_rpc.cpp -o src/obj/switch_sai_rpc.o
14:11:21.851  g++ -I/usr/include/sai -I. -std=c++11 -DFORCE_BOOST_SMART_PTR -c src/gen-cpp/switch_sai_types.cpp -o src/obj/switch_sai_types.o
14:11:21.851  g++ -I/usr/include/sai -I. -std=c++11 -DFORCE_BOOST_SMART_PTR -c src/gen-cpp/switch_sai_constants.cpp -o src/obj/switch_sai_constants.o
14:11:21.851  g++ -I/usr/include/sai -I. -std=c++11 -DFORCE_BOOST_SMART_PTR -c src/switch_sai_rpc_server.cpp -o src/obj/switch_sai_rpc_server.o -I/usr/include/sai -I. -std=c++11 -DFORCE_BOOST_SMART_PTR -I./src/gen-cpp
14:11:21.851  src/switch_sai_rpc_server.cpp:48:17: fatal error: sai.h: No such file or directory
14:11:21.851   #include <sai.h>
14:11:21.851                   ^
14:11:21.851  compilation terminated.
14:11:21.851  Makefile:81: recipe for target 'src/obj/switch_sai_rpc_server.o' failed
14:11:21.851  make[4]: *** [src/obj/switch_sai_rpc_server.o] Error 1
14:11:21.851  make[4]: Leaving directory '/sonic/src/sonic-sairedis/SAI/test/saithrift'
14:11:21.851  Makefile:29: recipe for target 'saithrift-build' failed
14:11:21.851  make[3]: *** [saithrift-build] Error 2
14:11:21.851  make[3]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
14:11:21.851  debian/rules:26: recipe for target 'override_dh_auto_build' failed
14:11:21.851  make[2]: *** [override_dh_auto_build] Error 2
14:11:21.851  make[2]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
14:11:21.851  debian/rules:23: recipe for target 'build' failed
14:11:21.851  make[1]: *** [build] Error 2
14:11:21.851  make[1]: Leaving directory '/sonic/src/sonic-sairedis/SAI'
14:11:21.851  dpkg-buildpackage: error: debian/rules build gave error exit status 2
14:11:21.851  [  FAIL LOG END  ] [ target/debs/stretch/libsaithrift-dev_0.9.4_amd64.deb ]
```

**Describe the results you expected:**
The build should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Based on the Jenkins change history for build 448 (when the failures started), this seems to have started after https://github.com/Azure/sonic-buildimage/pull/5651 was merged.

**Comment by lguohan** [comment]
after building syncd, the current build system will uninstall
libsaibcm-dev package. when building ptf docker, libsaithrift-dev
requires libsaibcm-dev to be installed.

i have a temporary workaround to address this problem in sonic-build-tools.

https://github.com/Azure/sonic-build-tools/commit/8220ed1506d3b4447ce69462bd81e09e97dd3783
