### ISSUE TITLE
[docker-fpm-frr]: Use supervisord as Docker entrypoint

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#576]
@rodnymolina: Please refactor docker-fpm-frr to use supervisord as the entrypoint in order to align the Docker with our new convention. I did not modify this Docker as I have no way to test it.

You can reference my changes to docker-fpm-quagga and docker-fpm-gobgp in PR https://github.com/Azure/sonic-buildimage/pull/573 as examples.

Thanks!

**Comment by rodnymolina** [comment]
Sure Joe, will take care of this.

**Comment by stcheng** [comment]
already fixed in https://github.com/Azure/sonic-buildimage/pull/2870
