### ISSUE TITLE
No interface MAC addresses in output of ifPhysAddress RFC1213

### ISSUE THREAD

**Issue by henzelis** [Azure/sonic-buildimage#5792]
**Description**

OID ifPhysAddress(1.3.6.1.2.1.2.2.1.6) show empty values. But should show MAC addresses according to RFC1213

**Steps to reproduce the issue:**
1. Run command:
_snmpwalk -v 2c -c public 127.0.0.1 1.3.6.1.2.1.2.2.1.6_

2.Observe empty values

**Observed behavior**
Empty values in output:
<pre>
 snmpwalk -v 2c -c public 127.0.0.1 1.3.6.1.2.1.2.2.1.6
iso.3.6.1.2.1.2.2.1.6.1 = "" 
iso.3.6.1.2.1.2.2.1.6.5 = "" 
iso.3.6.1.2.1.2.2.1.6.9 = "" 
iso.3.6.1.2.1.2.2.1.6.13 = "" 
iso.3.6.1.2.1.2.2.1.6.17 = "" 
iso.3.6.1.2.1.2.2.1.6.21 = ""_
</pre>
**Expected behavior**
The output should contain MAC addresses of interfaces

**Output of `show version`:**
<pre>
SONiC Software Version: SONiC.201911.210-cc135807
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: cc135807
Build date: Wed Oct  7 04:18:37 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-mlnx_msn3800-r0
HwSKU: ACS-MSN3800
ASIC: mellanox
</pre>
[sonic_dump_r-qa-sw-eth-114_20201030_151538.tar.gz](https://github.com/Azure/sonic-buildimage/files/5479826/sonic_dump_r-qa-sw-eth-114_20201030_151538.tar.gz)

**Comment by anshuv-mfst** [comment]
@qiluo-msft - could you please confirm if this is by design or bug.

**Comment by qiluo-msft** [comment]
The ifPhysAddress OID is not supported right now. However we welcome any code contribution on this.
