### ISSUE TITLE
OID ifSpeed show wrong interface speed values

### ISSUE THREAD

**Issue by henzelis** [Azure/sonic-buildimage#5793]
**Description**

OID ifSpeed show wrong interface speed values,

**Steps to reproduce the issue:**
1. configure interface speed on DUT:
<pre>
config interface speed Ethernet64 10000
</pre>
2. Run snmpwalk command to verify values:
<pre>
 snmpwalk -v 2c -c public 127.0.0.1 1.3.6.1.2.1.2.2.1.5.65
iso.3.6.1.2.1.2.2.1.5.65 = Gauge32: 4294967295
</pre>

**Describe the results you received:**
snmpwalk command show wrong inerface speed:
<pre>
 snmpwalk -v 2c -c public <DUT.IP> 1.3.6.1.2.1.2.2.1.5.65
iso.3.6.1.2.1.2.2.1.5.65 = Gauge32: 4294967295 <------THIS IS A WRONG VALUE
</pre>

**Describe the results you expected:**
snmpwalk command show wrong inerface speed:
<pre>
 snmpwalk -v 2c -c public <DUT.IP> 1.3.6.1.2.1.2.2.1.5.65
iso.3.6.1.2.1.2.2.1.5.65 = Gauge32: 10000000 <---- IT SHOULD SHOW INTERFACE SPEED
</pre>
**Output of `show version`:**
<pre>
SONiC Software Version: SONiC.201911.210-cc135807
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: cc135807
Build date: Wed Oct  7 04:18:37 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-mlnx_msn3800-r0
HwSKU: ACS-MSN3800
ASIC: mellanox
</pre>
[sonic_dump_r-qa-sw-eth-114_20201030_151538.tar.gz](https://github.com/Azure/sonic-buildimage/files/5479873/sonic_dump_r-qa-sw-eth-114_20201030_151538.tar.gz)

**Comment by astrekozov** [comment]
Firstly 1.3.6.1.2.1.2.2.1.5 OID referenced in RFC 1213 with the name ifSpeed, contains "An estimate of the interface's current bandwidth in bits per second" and have type GAUGE (gauge32, uint32). Hence it is limited to value 4,294,967,295 (~2.2Gb). Obviously this does not cover modern systems, so in RFC 2863 suggested to store these values in ifHighSpeed (1.3.6.1.2.1.31.1.1.1.15) which has the current number of 1,000,000 (1 million) bits/second units.
RFC recommends against using 64-bit values and suggests that in case port speed exceeds 32-bit unsigned value "If the bandwidth of the interface is greater than the maximum value reportable by this object then this object should report its maximum value (4,294,967,295)".

Thus the values displayed are correct.

**Comment by henzelis** [comment]
Thank you for the detailed explanation and research of this issue. Agree with you.
