### ISSUE TITLE
RFC4293 OIDs not mplemented in snmp agent

### ISSUE THREAD

**Issue by henzelis** [Azure/sonic-buildimage#5796]
**Description**

Output of next OIDs return incorrect values.:

-  ipAddressPrefixOrigin
-  ipAddressType
-  ipDefaultRouterLifetime
-  ipv6ScopeZoneIndexTable

**Steps to reproduce the issue:**
1. Run on DUT snmp query for next OIDs:
<pre>
ipAddressPrefixOrigin
 ipAddressType
 ipDefaultRouterLifetime
 ipv6ScopeZoneIndexTable
</pre>
 2. Verify that output is incorrect.

**Describe the results you received:**
<pre>
ipAddressPrefixOrigin(1.3.6.1.2.1.4.32.1.5 ) OID not shows value "4" for interfaces that get IP address by dhcp, example eth0 show 2.

Verify ipAddressType(1.3.6.1.2.1.4.34.1.4) OID:
Exaptable values are:
unicast(1),
anycast(2),
broadcast(3)
But it not shows correct values for anycast addresses that were set up. For example with the command "config interface ip add Ethernet64 2001:db8:6301::/128 anycast".

ipAddressOrigin(1.3.6.1.2.1.4.34.1.6) OID not showing correct value for DHCP assigned interfaces as (4) but should be.

ipDefaultRouterLifetime(1.3.6.1.2.1.4.37.1.4) - time for IPv4 and IPv6 are different and unexpected
example:
# snmpwalk -v 2c -c public 127.0.0.1 1.3.6.1.2.1.4.37.1.4
iso.3.6.1.2.1.4.37.1.4.1.4.10.209.20.1.2 = Gauge32: 4294967295
iso.3.6.1.2.1.4.37.1.4.2.16.254.128.0.0.0.0.0.0.138.81.251.255.254.52.173.0.2 = Gauge32: 1644

ipv6ScopeZoneIndexEntry(1.3.6.1.2.1.4.36.1):
- only ipv6ScopeZoneIndexLinkLocal(1.3.6.1.2.1.4.36.1.2) show values,
- other (1.3.6.1.2.1.4.36.1.(3-13) show 0 values

</pre>

**Describe the results you expected:**

The output of OIDs should show expected data:
 ipAddressPrefixOrigin
 ipAddressType
 ipDefaultRouterLifetime
 ipv6ScopeZoneIndexTable

   **Output of `show version`:**
<pre>
SONiC.201911.210-cc135807
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: cc135807
Build date: Wed Oct  7 04:18:37 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-mlnx_msn3800-r0
HwSKU: ACS-MSN3800
ASIC: mellanox
</pre>   
[sonic_dump_r-qa-sw-eth-2037_20201015_080241.tar.gz](https://github.com/Azure/sonic-buildimage/files/5482327/sonic_dump_r-qa-sw-eth-2037_20201015_080241.tar.gz)

**Comment by anshuv-mfst** [comment]
@qiluo-msft - could you please verify if this is by design or is a bu. Thanks

**Comment by qiluo-msft** [comment]
RFC4293 OIDs are not supported right now.
