### ISSUE TITLE
Multi asic support for config vlan, show vlan and show ip int

### ISSUE THREAD

**Issue by anamehra** [Azure/sonic-buildimage#5839]
**Description**
config vlan, show vlan and show ip interface CLIs does not have multi asic support.

**Steps to reproduce the issue:**
1. config vlan -n asic0
2. show ip int -d all
3. show vlan brief -d all

**Describe the results you received:**
root@sonic:# config vlan -n asic0 add 101
Error: no such option: -n

root@sonic# show ip int -d all
Error: no such option: -d

root@sonic# show vlan brief -n asic0
Error: no such option: -n

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
vlan is not supported in multi-asic. 
Please provide more input: which platform is this tested on? (pizza box or chassis?)

**Comment by anamehra** [comment]
This is for chassis.

Is there any work in progress for show ip int support for multi asic?

**Comment by anamehra** [comment]
Please suggest.

**Comment by anshuv-mfst** [comment]
Enhancement is not planned for 202012 release. Please file new issue for show ip int CLI enhancement for Chassis.

**Comment by anamehra** [comment]
Filed #6171 for show ip int CLI enhancement

**Comment by anshuv-mfst** [comment]
Closing as this will be tracked via #6171

**Comment by anamehra** [comment]
> Closing as this will be tracked via #6171

#6171 is for "show ip interface"
Is there a different bug for config vlan/show vlan CLI? My understanding was this bug will be used for that.
