### ISSUE TITLE
[Celestica] PMon error

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#5853]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
```
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd Process Process-1:
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     self.run()
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     self._target(*self._args, **self._kwargs)
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 963, in task_worker
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     status, port_dict = _wrapper_get_transceiver_change_event(timeout)
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 184, in _wrapper_get_transceiver_change_event
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     return platform_sfputil.get_transceiver_change_event(timeout)
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd AttributeError: 'SfpUtilHelper' object has no attribute 'get_transceiver_change_event'
syslog.80.gz:Nov  7 11:47:09.283457 str2-dx010-acs-6 WARNING pmon#thermalctld: Fan fault warning: PSU-1 FAN-1 is broken.
syslog.80.gz:Nov  7 11:47:09.340973 str2-dx010-acs-6 WARNING pmon#thermalctld: Insufficient number of working fans warning: 1 fans are not working.
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by jleveque** [comment]
Root cause is that there is no `get_change_event()` method defined for the dx010 platform in the platform's [Chassis class](https://github.com/Azure/sonic-buildimage/blob/master/device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py), so xcvrd falls back to try the old sfputil plugin, and `get_transceiver_change_event()` is [not implemented there](https://github.com/Azure/sonic-buildimage/blob/master/device/celestica/x86_64-cel_seastone-r0/plugins/sfputil.py#L204), either.

**Comment by bingwang-ms** [comment]
pmon service will not start on SONiC.master.478-23b0e07d, dx010-4. Is it the same issue?

**Comment by jleveque** [comment]
@bingwang-ms: I just checked that device, and yes, this issue is present. However, it also appears that there is also a driver or hardware issue with that device, as I see errors like the following:

```
thermalctld IOError: Failed to read eeprom : [Errno 2] No such file or directory: '/sys/class/i2c-adapter/i2c-12/12-0050/eeprom'
```

You might want to try rebooting and/or power-cycling the device.

**Comment by bingwang-ms** [comment]
Thanks @jleveque . Already rebooted the DUT, but the issue is still present. The file ```'/sys/class/i2c-adapter/i2c-12/12-0050/eeprom'``` is missing on DUT. Is this file included in image?

**Comment by jleveque** [comment]
@bingwang-ms: No. This is a device file. It should be created by the platform drivers.

**Comment by lguohan** [comment]
celestica upload the change by Friday.
