### ISSUE TITLE
orchagent crash due to unresolved next hop at warm_restart

### ISSUE THREAD

**Issue by caizhenghui** [Azure/sonic-buildimage#5872]
**Description**

**Steps to reproduce the issue:**
1. set static route to a non-resolved NH: e.g. ip route add 100.0.0.0/24 via 10.0.0.107 where: 10.0.0.107 is not resolved.
2. config warm_restart enable swss
3. systemctl restart swss

**Describe the results you received:**
orchagent crashes and swss container exits. 
In syslog:
Nov  9 21:36:24.325599 sonic NOTICE swss#orchagent: :- postBake: Start MirrorOrch post-baking
Nov  9 21:36:24.325644 sonic NOTICE swss#orchagent: :- warmRestoreValidation: There are pending consumer tasks after restore:
Nov  9 21:36:24.325644 sonic NOTICE swss#orchagent: :- warmRestoreValidation: ROUTE_TABLE:100.0.0.0/24|SET|nexthop:10.0.0.107|ifname:Ethernet212
Nov  9 21:36:24.325654 sonic NOTICE swss#orchagent: :- setWarmStartState: orchagent warm start state changed to restored
Nov  9 21:36:24.325661 sonic ERR swss#orchagent: :- warmRestoreAndSyncUp: Orchagent state restore failed
Nov  9 21:36:24.325661 sonic ERR swss#orchagent: :- main: Failed to initialize orchstration daemon
Nov  9 21:36:24.325980 sonic INFO swss#supervisord: orchagent terminate called without an active exception

**Describe the results you expected:**
swss should still work and no core should be generated.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
root@sonic:/var/log# show ver 

SONiC Software Version: SONiC.201911.0-ce724860
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: ce724860
Build date: Tue Oct 20 13:57:02 UTC 2020
Built by: zcai@qnc-ubm16-zcai

Platform: x86_64-juniper_qfx5210-r0
HwSKU: Juniper-QFX5210-64C
ASIC: broadcom
Serial Number: YJ0219370003
Uptime: 21:39:55 up 33 min,  1 user,  load average: 0.36, 0.63, 0.57

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-sflow                  201911.0-ce724860   dc5c5dc3053d        315MB
docker-sflow                  latest              dc5c5dc3053d        315MB
docker-fpm-frr                201911.0-ce724860   b702d9ed2433        335MB
docker-fpm-frr                latest              b702d9ed2433        335MB
docker-snmp-sv2               201911.0-ce724860   910c699933ec        348MB
docker-snmp-sv2               latest              910c699933ec        348MB
docker-sonic-mgmt-framework   201911.0-ce724860   c9efba4282f2        431MB
docker-sonic-mgmt-framework   latest              c9efba4282f2        431MB
docker-lldp-sv2               201911.0-ce724860   c48045bf2fb0        312MB
docker-lldp-sv2               latest              c48045bf2fb0        312MB
docker-orchagent              201911.0-ce724860   8e5496a1fe76        333MB
docker-orchagent              latest              8e5496a1fe76        333MB
docker-nat                    201911.0-ce724860   e4a0c0b2edb3        316MB
docker-nat                    latest              e4a0c0b2edb3        316MB
docker-teamd                  201911.0-ce724860   0f1b067e20d8        314MB
docker-teamd                  latest              0f1b067e20d8        314MB
docker-syncd-brcm             201911.0-ce724860   15ed1755c13a        436MB
docker-syncd-brcm             latest              15ed1755c13a        436MB
docker-sonic-telemetry        201911.0-ce724860   17e02bba8b02        353MB
docker-sonic-telemetry        latest              17e02bba8b02        353MB
docker-platform-monitor       201911.0-ce724860   d07e8709cb6e        357MB
docker-platform-monitor       latest              d07e8709cb6e        357MB
docker-dhcp-relay             201911.0-ce724860   a07933dd536f        299MB
docker-dhcp-relay             latest              a07933dd536f        299MB
docker-database               201911.0-ce724860   17ceb158b209        289MB
docker-database               latest              17ceb158b209        289MB
docker-router-advertiser      201911.0-ce724860   7f22c7557efc        289MB
docker-router-advertiser      latest              7f22c7557efc        289MB
    ```
[sonic_dump_sonic_20201109_213622.tar.gz](https://github.com/Azure/sonic-buildimage/files/5513421/sonic_dump_sonic_20201109_213622.tar.gz)

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
do you see this issue on master as well?

**Comment by caizhenghui** [comment]
@lguohan No, I didn't run test with master. Is there an known issue report/PR from master that just need to backport?

**Comment by anshuv-mfst** [comment]
This is not supported for static route/warm-restart. 
Need to add protection in warm-restart - @yxieca to discuss in Warmboot subgroup.
