### ISSUE TITLE
Mellanox build master failure

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#5897]
**Description**

**Steps to reproduce the issue:**
https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all/456/

```
23:11:17  ============================= test session starts ==============================
23:11:17  platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
23:11:17  rootdir: /sonic/src/sonic-bgpcfgd, inifile: pytest.ini
23:11:17  plugins: cov-2.6.0
23:11:17  collected 76 items
23:11:17  
23:11:17  tests/test_allow_list.py ...............                                 [ 19%]
23:11:17  tests/test_bbr.py .......................                                [ 50%]
23:11:17  tests/test_ipv6_nexthop_global.py .                                      [ 51%]
23:11:17  tests/test_pfx_filter.py ...........                                     [ 65%]
23:11:17  tests/test_sonic-cfggen.py FFFFFFFFFFFFFFFFF                             [ 88%]
23:11:17  tests/test_templates.py .........                                        [100%]
23:11:17  
23:11:17  =================================== FAILURES ===================================
```

**Describe the results you received:**
mellanox build should pass.

it is unclear why only mellanox build is failing.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
build 455 is ok, but starting from build 456 the build is failing.

it seems caused by bgpcfgd upgrade to python3.

**Comment by pavel-shirshov** [comment]
That should be fixed by moving sonic-config-engine to python3. After that sonic-bgpcfgd will not run python2 interpreter from python3 interpreter.
And this PR will woek https://github.com/Azure/sonic-buildimage/pull/5847

**Comment by pavel-shirshov** [comment]
```
File "/sonic/src/sonic-config-engine/sonic-cfggen", line 33, in <module>\n    import netaddr\nImportError: No module named netaddr\n''
```
That means that sonic-config-engine was run by python3 interpreter, not python2 despite this https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-bgpcfgd/tests/test_sonic-cfggen.py#L17 and that everything works not in debug image.
