### ISSUE TITLE
xcvrd keep on crashing with latest master image 484 on 7050cx3 platform

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#5907]
**Description**

**Steps to reproduce the issue:**
1. Install master image 484 on 7050cx3 platform
2.
3.

**Describe the results you received:**
pmon keep on crashing:

Nov 11 23:08:02.670333 str2-7050cx3-acs-07 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Nov 11 23:08:02.670477 str2-7050cx3-acs-07 INFO pmon#supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 5, in <module>
Nov 11 23:08:02.670477 str2-7050cx3-acs-07 INFO pmon#supervisord: xcvrd     from src.xcvrd import main
Nov 11 23:08:02.670552 str2-7050cx3-acs-07 INFO pmon#supervisord: xcvrd ImportError: No module named src.xcvrd

**Describe the results you expected:**
System boots up and healthy

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
SONiC Software Version: SONiC.master.484-b5cfc025
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: b5cfc025
Build date: Wed Nov 11 18:18:57 UTC 2020
Built by: johnar@jenkins-worker-6

Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-C32
ASIC: broadcom
Serial Number: JPW20281078
Uptime: 23:59:02 up 29 min,  1 user,  load average: 3.10, 2.85, 2.08
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@vdahiya12 , can you identify which pr cause the regression?
