### ISSUE TITLE
Add LICENSE to sonic-restapi repo

### ISSUE THREAD

**Issue by caizhenghui-juniper** [Azure/sonic-buildimage#5930]
**Description**

Need LICENSE file for complete open source process in sonic-restapi repo

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Missing LICENSE file in sonic-restapi repo.

**Describe the results you expected:**
We need LICENSE file in sonic-restapi repo just as other sonic repos.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
Guohan - Can you please provide input.

**Comment by prsunny** [comment]
PR merged. Closing the issue
