### ISSUE TITLE
DellEMC: Need pg_lookup_profile.ini for TD3,TH3 platforms.

### ISSUE THREAD

**Issue by aravindmani-1** [Azure/sonic-buildimage#5932]
**Description**
Currently in DellEMC platforms, pg_profile_lookup.ini are all 208 cell size based.
We need values that are in alignment with TD3 platform(256 cell size),TH3(254 cell size).

TD3: 
https://github.com/Azure/sonic-buildimage/blob/master/device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/pg_profile_lookup.ini
TH3:
https://github.com/Azure/sonic-buildimage/blob/master/device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/pg_profile_lookup.ini

**Steps to reproduce the issue:**
Check https://github.com/Azure/sonic-buildimage/blob/master/device/dell/x86_64-dellemc_s5232f_c3538-r0/DellEMC-S5232f-C32/pg_profile_lookup.ini file.
https://github.com/Azure/sonic-buildimage/blob/master/device/dell/x86_64-dellemc_z9332f_d1508-r0/DellEMC-Z9332f-O32/pg_profile_lookup.ini

show techsupport is not attached here as the issue is straight forward

**Describe the results you received:**

**Describe the results you expected:**

**Comment by anshuv-mfst** [comment]
@ben-gale - Please look into this issue.

**Comment by ben-gale** [comment]
> @ben-gale - Please look into this issue.

Asking @jeff-yin to take this one - thx.

**Comment by gechiang** [comment]
@vmittal-msft Is this already addressed by your recent MMUT profile PRs?

**Comment by vmittal-msft** [comment]
Yes this should be taken care already. I took care for Z9332 (TH3) & Aravind recent PR for S5232F (TD3) should have taken care for this. @aravindmani-1 can confirm.
