### ISSUE TITLE
Unable to install sonic_utilities-1.2-py3-none-any.whl with Build 492

### ISSUE THREAD

**Issue by Blueve** [Azure/sonic-buildimage#5942]
**Description**

I installed the latest success build [492](https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/492/) to my SONiC switch.
And I am trying to install the newest sonic-utilities package `sonic_utilities-1.2-py3-none-any.whl` but failed with following error:
```
admin@sonic:~$ sudo pip install --force-reinstall --no-deps sonic_utilities-1.2-py3-none-any.whl
sonic_utilities-1.2-py3-none-any.whl is not a supported wheel on this plaform.
```

I was wondering that it might related to this change: https://github.com/Azure/sonic-utilities/pull/1128
I am not sure if this is the platform issue or base image issue or is there an ongoing task for that?

**Steps to reproduce the issue:**
1. Install image 492
2. Build sonic-utilities-1.2-py3-none-any.whl
3. Install sonic-utilities-1.2-py3-none-any.whl with command `sudo pip install --force-reinstall --no-deps sonic_utilities-1.2-py3-none-any.whl`

**Describe the results you received:**

The installation failed with below error:
```
sonic_utilities-1.2-py3-none-any.whl is not a supported wheel on this platform.
```

**Describe the results you expected:**
The package installed without any issue.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
admin@sonic:~$ show version

SONiC Software Version: SONiC.master.492-e526d889
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: e526d889
Build date: Mon Nov 16 09:08:19 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_e1031-r0
HwSKU: Celestica-E1031-T48S4
ASIC: broadcom
Serial Number: R0882B2F160615GD000006
Uptime: 08:38:14 up 14 min,  2 users,  load average: 2.06, 3.63, 3.13

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-snmp                   latest                b3fbbdf0a732        458MB
docker-snmp                   master.492-e526d889   b3fbbdf0a732        458MB
docker-teamd                  latest                8e784367cc04        454MB
docker-teamd                  master.492-e526d889   8e784367cc04        454MB
docker-sonic-mgmt-framework   latest                efda89429ce3        578MB
docker-sonic-mgmt-framework   master.492-e526d889   efda89429ce3        578MB
docker-router-advertiser      latest                1c08552c349b        421MB
docker-router-advertiser      master.492-e526d889   1c08552c349b        421MB
docker-platform-monitor       latest                6ad8c0548036        534MB
docker-platform-monitor       master.492-e526d889   6ad8c0548036        534MB
docker-lldp                   latest                8f6d86eaaa25        485MB
docker-lldp                   master.492-e526d889   8f6d86eaaa25        485MB
docker-dhcp-relay             latest                876d49713757        428MB
docker-dhcp-relay             master.492-e526d889   876d49713757        428MB
docker-database               latest                3d944ee29d03        421MB
docker-database               master.492-e526d889   3d944ee29d03        421MB
docker-orchagent              latest                4a1f908f059e        468MB
docker-orchagent              master.492-e526d889   4a1f908f059e        468MB
docker-nat                    latest                5d7c8386030e        457MB
docker-nat                    master.492-e526d889   5d7c8386030e        457MB
docker-sonic-telemetry        latest                be95535a4a93        491MB
docker-sonic-telemetry        master.492-e526d889   be95535a4a93        491MB
docker-fpm-frr                latest                f017be17f608        471MB
docker-fpm-frr                master.492-e526d889   f017be17f608        471MB
docker-sflow                  latest                e32a4db2937e        455MB
docker-sflow                  master.492-e526d889   e32a4db2937e        455MB
docker-syncd-brcm             latest                7aacd07f4385        536MB
docker-syncd-brcm             master.492-e526d889   7aacd07f4385        536MB

```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by Blueve** [comment]
Hi @jleveque, I guess you might know that... Should I need some additional configuration for that?

**Comment by jleveque** [comment]
Try calling `pip3` explicitly: `sudo pip3 install --force-reinstall --no-deps sonic_utilities-1.2-py3-none-any.whl`

However, you might run into issues with missing dependencies. Once https://github.com/Azure/sonic-buildimage/pull/5926 merges, this should not be an issue.

**Comment by Blueve** [comment]
> Try calling `pip3` explicitly: `sudo pip3 install --force-reinstall --no-deps sonic_utilities-1.2-py3-none-any.whl`
> 
> However, you might run into issues with missing dependencies. Once #5926 merges, this should not be an issue, as the Python 3 package will be installed in the image by default.

Thanks a lot!
pip3 works for me. Unfortunately, I got dependencies missing issue as you side and pip3 couldn't resolve them due to my lab's network. I will close this issue after the PR merged. : D

**Comment by lguohan** [comment]
@Blueve , please use the linked pull request feature when a pr can close this issue.

**Comment by jleveque** [comment]
Technically, this isn't an issue with sonic-buildimage; until https://github.com/Azure/sonic-buildimage/pull/5926 merges, the image is technically still using the Python 2 wheel. This is only a problem because @Blueve is trying to install the Python 3 wheel in the image without the dependencies installed.
