### ISSUE TITLE
[orchagent] sairedis fails to create route

### ISSUE THREAD

**Issue by noaOrMlnx** [Azure/sonic-buildimage#5948]
**Description**
orchagent has the following error message in syslog:

`ERR swss#orchagent: :- meta_sai_validate_route_entry: object key SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"30.1.10.0/24","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000680"} already exists`

`ERR swss#orchagent: :- add_route: SAI failed to create route`

This issue occurs while running vnet_vxlan test which adds duplicated routes. This message is received in the second attempt to add the route. 

**Steps to reproduce the issue:**
1. run vxlan/test_vnet_vxlan.py 
2. the test will fail and the above error will be shown in syslog

**Describe the results you received:**
`ERR swss#orchagent: :- meta_sai_validate_route_entry: object key SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"30.1.10.0/24","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000680"} already exists`

`ERR swss#orchagent: :- add_route: SAI failed to create route`

**Describe the results you expected:**
The error log should not be shown.

**Comment by anshuv-mfst** [comment]
this is non-issue, MLNX team discussed with Prince.
