### ISSUE TITLE
NTP test failing on Mellanox 2700

### ISSUE THREAD

**Issue by sumukhatv** [Azure/sonic-buildimage#5975]
**Description**

The NTP Pytest is failing with the error `/usr/sbin/ntpd: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory\n`

This is happening on Mellanox 2700 running 20191130 image.

**Steps to reproduce the issue:**
1. Run the NTP `pytest` from the `sonic-mgmt` repository

**Describe the results you received:**
```
>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           RunAnsibleModuleFail: run module service failed, Ansible Results =>
E           {
E               "changed": false, 
E               "failed": true, 
E               "invocation": {
E                   "module_args": {
E                       "arguments": "", 
E                       "enabled": null, 
E                       "name": "ntp", 
E                       "pattern": null, 
E                       "runlevel": "default", 
E                       "sleep": null, 
E                       "state": "restarted"
E                   }
E               }, 
E               "msg": "/usr/sbin/ntpd: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory\n"
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
    ```
    SONiC Software Version: SONiC.20191130.53
    Distribution: Debian 9.13
    Kernel: 4.9.0-11-2-amd64
    Build commit: d7fee5665
    Build date: Mon Nov 16 13:43:46 UTC 2020
    Built by: sonicbld@jenkins-slave-phx-2

    Platform: x86_64-mlnx_msn2700-r0
    HwSKU: Mellanox-SN2700
    ASIC: mellanox
    ```

**Comment by anshuv-mfst** [comment]
(CC: @stepanblyschak , @volodymyrsamotiy )

@sumukhatv - Issue might be with testbed server,  aparmor profile. Please disable aparmor and retry steps.

**Comment by sumukhatv** [comment]
> (CC: @stepanblyschak , @volodymyrsamotiy )
> 
> @sumukhatv - Issue might be with testbed server, aparmor profile. Please disable aparmor and retry steps.

Can you provide me the steps to do it?

**Comment by stepanblyschak** [comment]
This issue is related to apparmor profile on testbed server.
Please check:
```
root@arc-host26:~# ls -al /etc/apparmor.d/disable/usr.sbin.ntpd
lrwxrwxrwx 1 root root 29 Dec  1 09:13 /etc/apparmor.d/disable/usr.sbin.ntpd -> /etc/apparmor.d/usr.sbin.ntpd
```

If profile for ntpd is not disabled, try to disable and rerun the test.

Since this is not an issue with DUT I suggest to move this issue to sonic-mgmt and add the step for disabling ntpd profile in testbed deployment playbooks
