### ISSUE TITLE
Regression - Interface transceivers are incorrectly reported as "Not present"

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#5978]
**Description**

Regression in latest master image -
Interface transceivers are shown as `Not present`. However, in reality transceivers are present as the interfaces are oper up and admin up.

```
admin@str-7260cx3-acs-7:~$ show int transceiver presence 
Port         Presence
-----------  -----------
Ethernet0    Not present
Ethernet4    Not present
Ethernet8    Not present
Ethernet12   Not present
Ethernet16   Not present
Ethernet20   Not present
Ethernet24   Not present
Ethernet28   Not present
...
```

```
admin@str-7260cx3-acs-7:~$ show int transceiver eeprom
Ethernet0: SFP EEPROM Not detected
Ethernet4: SFP EEPROM Not detected
Ethernet8: SFP EEPROM Not detected
Ethernet12: SFP EEPROM Not detected
Ethernet16: SFP EEPROM Not detected
Ethernet20: SFP EEPROM Not detected
Ethernet24: SFP EEPROM Not detected
....
```
**Steps to reproduce the issue:**
1. Install latest master image. I tested with `SONiC.master.494-b595a6ea`
2. Do `show interfaces transceiver presence `.
3. All the ports are shown as `Not present`.
4. Check output of `show interface status` - the interfaces are connected and UP.

**Describe the results you received:**
 Transceivers are shown as `Not present`.
EEPROM Not detected for all ports.

**Describe the results you expected:**
Transceivers should be "Present" when physically present.
EEPROM should be detected

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
admin@str-7260cx3-acs-7:~$ show ver

SONiC Software Version: SONiC.master.494-b595a6ea
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: b595a6ea
Build date: Wed Nov 18 09:49:17 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-Q64
ASIC: broadcom
```

**Comment by lguohan** [comment]
is this related to #5974

**Comment by vaibhavhd** [comment]
I see errors in syslog in `arista/utils/sonic_platform/chassis.py` that are fixed by https://github.com/Azure/sonic-platform-common/pull/143
This seems to have caused the below error in detecting EEPROM, and consequently transceiver information is not updated.
```
pmon#syseepromd[37]: Failed to load platform-specific eeprom from sonic_platform package due to NameError("name 'STATUS_LED_COLOR_OFF' is not defined",)
```
I will wait for the latest image to re-confirm the issue.

**Comment by vaibhavhd** [comment]
This issue is not seen anymore on the latest of master (tested 498). Transceivers and EEPROM are detected.

```
admin@str-7260cx3-acs-7:~$ show interface transceiver presence 
Port         Presence
-----------  -----------
Ethernet0    Present
Ethernet4    Present
...
```

```
admin@str-7260cx3-acs-7:~$ show version 

SONiC Software Version: SONiC.master.498-5fbb6ee6
```
