### ISSUE TITLE
LAG state becomes no-carrier even if there are members in LOWER_UP

### ISSUE THREAD

**Issue by marian-pritsak** [Azure/sonic-buildimage#600]
```
$ ip link show PortChannel0 ; ip link show Ethernet0 ; ip link show Ethernet4
38: PortChannel0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 24:8a:07:05:31:c0 brd ff:ff:ff:ff:ff:ff
17: Ethernet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master PortChannel0 state UP mode DEFAULT group default qlen 1000
    link/ether 24:8a:07:05:31:c0 brd ff:ff:ff:ff:ff:ff
23: Ethernet4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast master PortChannel0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 24:8a:07:05:31:c0 brd ff:ff:ff:ff:ff:ff
```

teamd [min_ports configuration](https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-teamd/teamd.j2#L7) does not allow less than 75% of active members causing whole LAG to go down.

**Comment by marian-pritsak** [comment]
@lguohan is it a desired behavior?

**Comment by stcheng** [comment]
yes. if less than 75% of members are DOWN. the whole LAG will be set to DOWN with NO-CARRIER flag.

**Comment by liatgrozovik** [comment]
The LAG test is running for more than a  month on daily now and it was passing until recently (all was good a week ago. IMO build 2.3.3 was working while 2.3.4 is not).
The behaviour seems to be modified recently. @stcheng please elaborate why the change introduced and why the desired behaviour has been modified without taking into consideration tests available and behaviour should not be modified unless all are sync.

**Comment by lguohan** [comment]
what are build 2.3.3 and  2.3.4? minlink was added at jan 30. which lag test fails?

**Comment by marian-pritsak** [comment]
Build 233 and 234.

We tried to put link on the other side of LAG member down to check if traffic will be redistributed via another member, but whole LAG goes down as soon as one LAG member goes down and packets are not transmitted at all.

**Comment by lguohan** [comment]
Here are the changed in build 234. https://sonic-jenkins.westus.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all/234/

I do not find any changes related to lag. given the min_link is merged into master and Jan 30. I do not have explaination why build 233 works but not build 234.

**Comment by lguohan** [comment]
can we close this issue? it is by design.

**Comment by marian-pritsak** [comment]
Closing
