### ISSUE TITLE
[DPB] dynamic port breakout is not working because of the missing import library

### ISSUE THREAD

**Issue by vadymhlushko-mlnx** [Azure/sonic-buildimage#6008]
**Description**
The error in logs while doing breakout command on the switch:

`“ERR ConfigMgmt: global name 'natsorted' is not defined”`

**Steps to reproduce the issue:**
1. Burn the image to the switch that supports Dynamic Port Breakout
2. Do the next command: `config interface breakout EthernetXX 4x25G[10G]`

**Describe the results you received:**
```
root@r-tigris-13:/home/admin# config interface breakout Ethernet248 4x25G[10G] -v -y

Running Breakout Mode : 1x100G[40G]
Target Breakout Mode : 4x25G[10G]

Ports to be deleted :
 {
    "Ethernet248": "100000"
}
Ports to be added :
 {
    "Ethernet251": "25000",
    "Ethernet250": "25000",
    "Ethernet248": "25000",
    "Ethernet249": "25000"
}

After running Logic to limit the impact

Final list of ports to be deleted :
 {
    "Ethernet248": "100000"
}
Final list of ports to be added :
 {
    "Ethernet251": "25000",
    "Ethernet250": "25000",
    "Ethernet248": "25000",
    "Ethernet249": "25000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-extension', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-vlan', 'sonic-versions', 'sonic-breakout_cfg', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-crm']
Note: Below table(s) have no YANG models:
FLEX_COUNTER_TABLE, TELEMETRY, FEATURE,
Below Config can not be verified, It may cause harm to the system
 {}
Do you wish to Continue? [y/N]: y
[ERROR] Port breakout Failed!!! Opting Out
Failed to break out Port. Error:
```

**Describe the results you expected:**

DPB CLI and functionality should work without errors

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Attach debug file `sudo generate_dump`:**

[sonic_dump_r-tigris-13_20201020_161152.tar.gz](https://github.com/Azure/sonic-buildimage/files/5585240/sonic_dump_r-tigris-13_20201020_161152.tar.gz)

**Comment by vadymhlushko-mlnx** [comment]
To fix this error - need to put the next line `from natsort import natsorted` into [sonic-cfggen file](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/sonic-cfggen)

Originally, this import line had existed in the sonic-cfggen file, but it was removed. Could someone explain why?

**Comment by tahmed-dev** [comment]
@praveen-li will fix this in configMgmt module. Please see discussion here [PR:5860](https://github.com/Azure/sonic-buildimage/pull/5860)

**Comment by vadymhlushko-mlnx** [comment]
This issue already has [PR](https://github.com/Azure/sonic-buildimage/pull/5860) opened
