### ISSUE TITLE
Complie error in libsaimetadata

### ISSUE THREAD

**Issue by chienbernie** [Azure/sonic-buildimage#602]
I want to update SAI of SONiC to v1.0.0 which is used in ASIC's SDK.
But I got the compile error as below in libsaimetadata when building /sonic/src/sonic-sairedis.
Is sonic-sairedis supporting SAI v1.0.0? 
Or how can I do for updating SAI?
Thanks.

sai_meta.h:108:9: error: 'sai_hostif_trap_id_t' does not name a type
         sai_hostif_trap_id_t      trap_id;
         ^
sai_meta.h:111:9: error: 'sai_unicast_route_entry_t' does not name a type
         sai_unicast_route_entry_t route_entry;
         ^
.....

cc1plus: all warnings being treated as errors
Makefile:837: recipe for target 'libsaimetadata_la-sai_extra_acl.lo' failed
make[4]: *** [libsaimetadata_la-sai_extra_acl.lo] Error 1
make[4]: Leaving directory '/sonic/src/sonic-sairedis/meta'
Makefile:393: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/sonic/src/sonic-sairedis'
Makefile:324: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/sonic/src/sonic-sairedis'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'binary-syncd' failed
make[1]: *** [binary-syncd] Error 2
make[1]: Leaving directory '/sonic/src/sonic-sairedis'

**Comment by stcheng** [comment]
@kcudnik could you take a look

**Comment by kcudnik** [comment]
since you have errors with unicast route, that means you are using v0.9.x branch
v1.0.1 is currently in development, there are no packages yet available but yo can compile it from sairedis/origin/v1.0.1 branch

**Comment by chienbernie** [comment]
Hi kcudnik,


Updated the information. The SAI of ASIC's SDK should be v0.9.6.
I have done 
1. Replaced the sai.deb from ASIC's SDK into  SONiC to update /usr/include/sai to v0.9.6
2. Replaced the libsai.deb from ASIC's SDK into SONiC to update libsai.so 

Then I got this error. Because sairedis / SAI of SONiC master branch are v0.9.4 SAI, right?

How should I do?
1. Do I need to update SAI's branch from v0.9.4 to v0.9.6 in .gitmodules
[submodule "src/SAI"]
	path = src/SAI
	url = https://github.com/opencomputeproject/SAI
	branch = v0.9.6
2. How can I align sairedis with v0.9.6 SAI? I don't see a branch for v0.9.6.

**Comment by kcudnik** [comment]
I'm afraid that v0.9.6 vs v0.9.4 contains too many changes,  branch 0.9.6 is very close to v1.0.1
changing sairedis to 0.9.6 would take a lot of effort which probably you dont want to make. I will discuss this tommorow at work what can we do with this.

**Comment by chienbernie** [comment]
Hi Kcudnik,

I checked the ASIC's SDK roodmap. It might support SAI v1.0.0 next version.
Do you think to upgrade SONiC's SAI to v1.0.0 easier?

Otherwise, how can I check those versions of SAI, sairedis and ASIC's SAI are aligned?
SAI has branch v1.0, v1.1
sairedis has branch v1.0, v1.0.1,v2.0
...

**Comment by chienbernie** [comment]
Hi Kcudnik,

I tried to sync SAI / sairedis / sai of ASIC to v1.0.1
I got new error. I think I need to update libsaithrift- dev and python-saithrift.
But I can't find the entry point. Can you tell me how to replace those two packages?
Thanks.



Finished target/debs/libhiredis0.13_0.13.3-2_amd64.deb-install
Executing rules for target/debs/libsaithrift-dev_0.9.4_amd64.deb
/sonic/src/SAI /sonic
tail: cannot open 'debian/changelog' for reading: No such file or directory
dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1
make: *** [target/debs/libsaithrift-dev_1.0.1_amd64.deb] Error 1
make: *** Waiting for unfinished jobs....
slave.mk:171: recipe for target 'target/debs/libsaithrift-dev_0.9.4_amd64.deb' failed
Finished target/debs/linux-headers-3.16.0-4-common_3.16.36-1+deb8u2_amd64.deb
make: Leaving directory '/sonic'
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kcudnik** [comment]
Sorry for the delay, do you still have issue with compiling ?

**Comment by chienbernie** [comment]
I am using branch v1.0.1.  It should work for SAI v1.0.1, right?

**Comment by lguohan** [comment]
1.0.1 was already in master a few months ago, we do not see any issue on that.
