### ISSUE TITLE
Dell show-version output not properly formatted.

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#6081]
**Description**

After the recent change to account for Python2 to 3 support, the PR https://github.com/Azure/sonic-buildimage/pull/5960/files made changes to support `bytearray` type returned by read_eeprom and read_eeprom_bytes.

However, now Serial Number is not printed correctly. It seems that `bytearray` to `str` conversion is not done before populating the `show version` platform output.

**Steps to reproduce the issue:**
1. Install latest SONiC master image on a Dell platform.
2. Check `show version`
3. The `Serial Number` will be printed with `type` `bytearray`.

**Describe the results you received:**
```
admin@str-s6100-acs-4:~$ show ver

SONiC Software Version: SONiC.master.508-6803e1d1
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 6803e1d1
Build date: Tue Dec  1 07:53:00 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
Serial Number: bytearray(b'9ZPQG02')
Uptime: 23:09:06 up 6 min,  1 user,  load average: 1.71, 1.57, 0.82
```

**Describe the results you expected:**

Type `bytearray` should not be printed.

**Comment by vaibhavhd** [comment]
@ArunSaravananBalachandran I am tagging you as I think the cosmetic issue here is due to this PR - https://github.com/Azure/sonic-buildimage/pull/5960

**Comment by ArunSaravananBalachandran** [comment]
> @ArunSaravananBalachandran I am tagging you as I think the cosmetic issue here is due to this PR - #5960

@vaibhavhd This issue is due to 'serial_number' method in Dell S6100 eeprom plugin not converting bytearray to string.
Will raise a PR with the fix.

**Comment by vaibhavhd** [comment]
> > @ArunSaravananBalachandran I am tagging you as I think the cosmetic issue here is due to this PR - #5960
> 
> @vaibhavhd This issue is due to 'serial_number' method in Dell S6100 eeprom plugin not converting bytearray to string.
> Will raise a PR with the fix.

Thanks Arun!
