### ISSUE TITLE
pmon xcvrd crash on multi asic chassis when all asics are BackEnd

### ISSUE THREAD

**Issue by anamehra** [Azure/sonic-buildimage#6097]
**Description**
xcvrd crash if none of the asic on the board are FrontEnd on a multi asic Chassis system. This cause pmon service to go down.

Nov  4 12:38:27.645057 sonic INFO pmon#supervisord: lm-sensors Starting sensor daemon: sensord
Nov  4 12:38:27.666989 sonic INFO pmon#sensord: sensord started
Nov  4 12:38:27.667853 sonic INFO pmon#supervisord: lm-sensors .
Nov  4 12:38:28.374348 sonic INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Nov  4 12:38:28.374348 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1302, in <module>
Nov  4 12:38:28.375320 sonic INFO pmon#supervisord: xcvrd     main()
Nov  4 12:38:28.375320 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1299, in main
Nov  4 12:38:28.375320 sonic INFO pmon#supervisord: xcvrd     xcvrd.run()
Nov  4 12:38:28.375320 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1260, in run
Nov  4 12:38:28.375354 sonic INFO pmon#supervisord: xcvrd     self.init()
Nov  4 12:38:28.375354 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1233, in init
Nov  4 12:38:28.375354 sonic INFO pmon#supervisord: xcvrd     post_port_sfp_dom_info_to_db(is_warm_start, self.stop_event)
Nov  4 12:38:28.375397 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 451, in post_port_sfp_dom_info_to_db
Nov  4 12:38:28.375397 sonic INFO pmon#supervisord: xcvrd     post_port_sfp_info_to_db(logical_port_name, int_tbl[asic_index], transceiver_dict, stop_event)
Nov  4 12:38:28.375412 sonic INFO pmon#supervisord: xcvrd KeyError: 0
Nov  4 12:38:28.395801 sonic INFO pmon#supervisor-proc-exit-listener: Process xcvrd exited unxepectedly. Terminating supervisor...

Empty lists are not handled in the script.

**Steps to reproduce the issue:**
1. Configure a Chassis system with multi-asic
2. Boot the system
3.

**Describe the results you received:**
root@sonic:/# systemctl status pmon.service 
● pmon.service - Platform monitor container
   Loaded: loaded (/usr/lib/systemd/system/pmon.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Fri 2016-11-04 12:39:47 UTC; 9min ago
  Process: 9093 ExecStop=/usr/bin/pmon.sh stop (code=exited, status=0/SUCCESS)
  Process: 8998 ExecStart=/usr/bin/pmon.sh wait (code=exited, status=0/SUCCESS)
  Process: 8881 ExecStartPre=/usr/bin/pmon.sh start (code=exited, status=0/SUCCESS)
 Main PID: 8998 (code=exited, status=0/SUCCESS)
      CPU: 967ms

Nov 04 12:39:47 sonic systemd[1]: pmon.service: Service hold-off time over, scheduling restart.
Nov 04 12:39:47 sonic systemd[1]: Stopped Platform monitor container.
Nov 04 12:39:47 sonic systemd[1]: pmon.service: Start request repeated too quickly.
Nov 04 12:39:47 sonic systemd[1]: Failed to start Platform monitor container.
Nov 04 12:39:47 sonic systemd[1]: pmon.service: Unit entered failed state.
Nov 04 12:39:47 sonic systemd[1]: pmon.service: Failed with result 'start-limit-hit'.

**Describe the results you expected:**
xcvrd should handle empty list and should not crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

sonic-buildimage/src/sonic-platform-daemons% git status
HEAD detached at 419f05b

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
Issue is seen on Cisco 8800 chassis. 
Please provide output for "show tech support" command.

**Comment by anamehra** [comment]
Is there a limited set of logs which may help instead of complete show tech dump?

**Comment by judyjoseph** [comment]
@anamehra, I will take a look and check how to check this. But have a general question of why we need to start XCVRD when there are no front-end ASIC's which usually have transceiver interfaces ? Can we skip starting xcvrd in pmon ?

**Comment by anamehra** [comment]
@judyjoseph, SONiC multi-asic supports routers with different asic role on same board. So there could be some asics with FrontEnd and some with BackEnd or all with same role. But as pmon is single service handling all asics, one might want to run xcrvd to check all asics to handle FrontEnd asics if present. But yes, if there is no other requirement to run XCRVD then it may not need to be started if all asics are BackEnd. In any case, it is a good idea to handle empty lists gracefully in python scripts.

**Comment by judyjoseph** [comment]
Sure @anamehra, will add the check to make sure it covers all cases  -- but I wanted to point out we have a control file eg:(https://github.com/Azure/sonic-buildimage/blob/master/device/mellanox/x86_64-mlnx_msn3700_simx-r0/pmon_daemon_control.json) using whicih we can skip starting pmon daemon which are not needed.

**Comment by anamehra** [comment]
Thanks @judyjoseph for that info! I will try that on my router!

**Comment by anamehra** [comment]
blocking the pmon process spawn via pmon_daemon_control.json worked fine.

**Comment by judyjoseph** [comment]
Closing this issue as using the "skip_xcvrd" in pmon_daemon_control.json worked fine.
