### ISSUE TITLE
show system-health CLI is not working in latest master image

### ISSUE THREAD

**Issue by aravindmani-1** [Azure/sonic-buildimage#6224]
**Description**
When executing "show system-health summary/detail/monitor-list, following errors were seen in latest master image.

root@sonic:~# show system-health summary
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 21, in summary
    if os.environ["UTILITIES_UNIT_TESTING"] == "1":
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'UTILITIES_UNIT_TESTING'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/show", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 33, in summary
    from health_checker.manager import HealthCheckerManager
ModuleNotFoundError: No module named 'health_checker'
root@sonic:~#

**Steps to reproduce the issue:**
1. Execute show system-health summary/detail/monitor-list
2. Notice the error thrown.

**Describe the results you received:**
Above mentioned errors were seen when executing system-health CLI 

**Describe the results you expected:**
Expecting the healthd to be compatible with python3.
Health checker directory is not seen in python3.7 dist-package.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
root@sonic:~# show ver

SONiC Software Version: SONiC.master.522-dirty-20201215.060116
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 4257c792
Build date: Tue Dec 15 06:08:23 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
ASIC Count: 1
Serial Number: CFXYZP2
Uptime: 11:14:00 up  5:07,  1 user,  load average: 3.13, 3.38, 3.54

Docker images:
REPOSITORY                    TAG                                IMAGE ID            SIZE
docker-snmp                   latest                             b483850a99c9        485MB
docker-snmp                   master.522-dirty-20201215.060116   b483850a99c9        485MB
docker-teamd                  latest                             278ec7d8b43a        492MB
docker-teamd                  master.522-dirty-20201215.060116   278ec7d8b43a        492MB
docker-sonic-mgmt-framework   latest                             8a8002b5b7ed        609MB
docker-sonic-mgmt-framework   master.522-dirty-20201215.060116   8a8002b5b7ed        609MB
docker-router-advertiser      latest                             c386bafb71a1        448MB
docker-router-advertiser      master.522-dirty-20201215.060116   c386bafb71a1        448MB
docker-platform-monitor       latest                             2ddebb766809        573MB
docker-platform-monitor       master.522-dirty-20201215.060116   2ddebb766809        573MB
docker-lldp                   latest                             82862b16aea0        488MB
docker-lldp                   master.522-dirty-20201215.060116   82862b16aea0        488MB
docker-dhcp-relay             latest                             b457f75353f5        455MB
docker-dhcp-relay             master.522-dirty-20201215.060116   b457f75353f5        455MB
docker-database               latest                             d71f985a3277        448MB
docker-database               master.522-dirty-20201215.060116   d71f985a3277        448MB
docker-orchagent              latest                             901fedf415f3        506MB
docker-orchagent              master.522-dirty-20201215.060116   901fedf415f3        506MB
docker-nat                    latest                             bd470d765c1d        495MB
docker-nat                    master.522-dirty-20201215.060116   bd470d765c1d        495MB
docker-sonic-telemetry        latest                             2be7723ff3c6        523MB
docker-sonic-telemetry        master.522-dirty-20201215.060116   2be7723ff3c6        523MB
docker-fpm-frr                latest                             019f642edec4        508MB
docker-fpm-frr                master.522-dirty-20201215.060116   019f642edec4        508MB
docker-sflow                  latest                             075965ad793b        493MB
docker-sflow                  master.522-dirty-20201215.060116   075965ad793b        493MB
docker-syncd-brcm             latest                             d8c8182d9372        542MB
docker-syncd-brcm             master.522-dirty-20201215.060116   d8c8182d9372        542MB

root@sonic:~#

[sonic_dump_sonic_20201216_111737.tar.gz](https://github.com/Azure/sonic-buildimage/files/5702556/sonic_dump_sonic_20201216_111737.tar.gz)

**Comment by vaibhavhd** [comment]
This issue was earlier raised as part of https://github.com/Azure/sonic-buildimage/issues/6104

**Comment by yxieca** [comment]
@aravindmani-1 can you validate the fix associated with issue #6104 ? Thanks!

**Comment by aravindmani-1** [comment]
@yxieca , It is working fine now.
