### ISSUE TITLE
"WARNING python3: :- operator(): DB '{APPL_DB}' is empty with pattern '_GEARBOX_TABLE:phy:*'!" is generated for "show interface status/counters"

### ISSUE THREAD

**Issue by gechiang** [Azure/sonic-buildimage#6311]
**Description**

Whenever user issue "show interface counters" or "show interface status", a warning message similar to the following is logged in syslog:
```
Dec 28 20:12:13.556771 str-s6100-acs-2 WARNING python3: :- operator(): DB '{APPL_DB}' is empty with pattern '_GEARBOX_TABLE:phy:*'!
```
perhaps the handler should add handling of cases where such DB entry is not expected for the given platform/SKU and not blindly issue requests thinking that it will always be there which result to these syslog warning messages...

"sonic-utilities/scripts/gearboxutil"  seems to be the handler that is causing the above issue.

**Steps to reproduce the issue:**
1. on an ssh session logged on to the DUT run the following cmd "sudo tail -f /var/log/syslog" 
2. On a different ssh session of the same DUT Issue CLI cmd "show interface counters" or "show interface status"
3. Observe the warning message gets logged into syslog each time the CLI is executed.

**Describe the results you expected:**
There should not be such warning logged into syslog.  Better handling should be made to avoid trigger unnecessary warning/error logging onto the syslog.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
```
admin@str-s6100-acs-2:~$ show vers

SONiC Software Version: SONiC.HEAD.191-9c06df8e
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 9c06df8e
Build date: Mon Dec 28 01:33:12 UTC 2020
Built by: johnar@jenkins-worker-22
```

**Comment by maksymbelei95** [comment]
Dear @gechiang, @lguohan

I have investigated the issue.
The root cause of the issue is https://github.com/Azure/sonic-utilities/blob/master/show/main.py#L166.
The checking of gearbox is being performed each time you calls show command, so, it explains why the warning occurs so often.
I have made PR with fix of the issue and some additional changes. Could you check it? 
https://github.com/Azure/sonic-utilities/pull/1343
