### ISSUE TITLE
[BRCM Th3  Z9332 ]: Unable to add one more ingress acl table 

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-buildimage#6323]
**Description**
Platform : Z9332 
ASIC : Th3 

```
root@sonic-z9332-10429:~# show platform summary
Platform: x86_64-dellemc_z9332f_d1508-r0
HwSKU: DellEMC-Z9332f-O32
ASIC: broadcom
ASIC Count: 1
root@sonic-z9332-10429:~#

```

**Script** : https://github.com/Azure/sonic-mgmt/blob/master/tests/acl/test_acl.py 

Creating new acl table fails with the following syslog messages. 

**syslogs :** 

	Dec 30 10:44:48.913716 sonic-z9332-10429 ERR syncd#syncd: [0] SAI_API_ACL:_brcm_sai_create_acl_table:7911 field group config create failed with error No resources for operation (0xfffffff2).
	Dec 30 10:44:48.913716 sonic-z9332-10429 ERR syncd#syncd: [0] SAI_API_ACL:brcm_sai_create_acl_table:174 create table entry failed with error -4.
	Dec 30 10:44:48.913716 sonic-z9332-10429 ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_INSUFFICIENT_RESOURCES
	Dec 30 10:44:48.914302 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_ACL_BIND_POINT_TYPE_LIST: 2:SAI_ACL_BIND_POINT_TYPE_PORT,SAI_ACL_BIND_POINT_TYPE_LAG
	Dec 30 10:44:48.914302 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_ETHER_TYPE: true
	Dec 30 10:44:48.914678 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_ACL_IP_TYPE: true
	Dec 30 10:44:48.914878 sonic-z9332-10429 ERR swss#orchagent: :- create: create status: SAI_STATUS_INSUFFICIENT_RESOURCES
	Dec 30 10:44:48.914878 sonic-z9332-10429 ERR swss#orchagent: :- addAclTable: Failed to create ACL table DATA_INGRESS_TEST
	Dec 30 10:44:48.914939 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_SRC_IP: true
	Dec 30 10:44:48.914939 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_DST_IP: true
	Dec 30 10:44:48.914939 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_ICMP_TYPE: true
	Dec 30 10:44:48.914974 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_ICMP_CODE: true
	Dec 30 10:44:48.914974 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_IP_PROTOCOL: true
	Dec 30 10:44:48.915000 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_L4_SRC_PORT: true
	Dec 30 10:44:48.915092 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_L4_DST_PORT: true
	Dec 30 10:44:48.915092 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_TCP_FLAGS: true
	Dec 30 10:44:48.915092 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_ACL_RANGE_TYPE: 2:SAI_ACL_RANGE_TYPE_L4_DST_PORT_RANGE,SAI_ACL_RANGE_TYPE_L4_SRC_PORT_RANGE
	Dec 30 10:44:48.915126 sonic-z9332-10429 ERR syncd#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_ACL_STAGE: SAI_ACL_STAGE_INGRESS

**Steps to reproduce the issue:**
1. create ingress L3 acl table 

```
	root@sonic-z9332-10429:/home/admin# cat acl_test_dir/test_acl.json
	{
		"ACL_TABLE": {
			"DATA_INGRESS_TEST": {
				"policy_desc": "DATA_INGRESS_TEST, ingress",
				"type": "L3",
				"stage": "ingress",
				"ports": [
					"Ethernet0"
				]
			}
		}
	}
	root@sonic-z9332-10429:/home/admin#
```

2. Apply the json file. 

     `     root@sonic-z9332-10429:/home/admin# sonic-cfggen -j acl_test_dir/test_acl.json --write-to-db `

3. Check whether the acl is applied. 
Issue is seen in master as well as [brcm-cache](https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-cache/)  image. 

**Describe the results you received:**
Acl table is not applied  and the script fails. 

**Describe the results you expected:**
Acl should have applied and test should pass 

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

	root@sonic-z9332-10429:/var/log# show ver

	SONiC Software Version: SONiC.HEAD.171-2f1445e6
	Distribution: Debian 10.7
	Kernel: 4.19.0-9-2-amd64
	Build commit: 2f1445e6
	Build date: Wed Dec 23 05:47:43 UTC 2020
	Built by: johnar@jenkins-worker-22

	Platform: x86_64-dellemc_z9332f_d1508-r0
	HwSKU: DellEMC-Z9332f-O32
	ASIC: broadcom
	ASIC Count: 1
	Serial Number: TH04CN21CET009BR0023
	Uptime: 10:57:56 up  5:47,  2 users,  load average: 1.21, 1.75, 1.98

	Docker images:
	REPOSITORY                    TAG                 IMAGE ID            SIZE
	docker-syncd-brcm-rpc         latest              7553262df30b        1.03GB
	docker-syncd-brcm             HEAD.171-2f1445e6   cb35bf102979        726MB
	docker-syncd-brcm             latest              cb35bf102979        726MB
	docker-syncd-brcm             original            cb35bf102979        726MB
	docker-snmp                   HEAD.171-2f1445e6   069011059f33        525MB
	docker-snmp                   latest              069011059f33        525MB
	docker-teamd                  HEAD.171-2f1445e6   30198adbcb2d        523MB
	docker-teamd                  latest              30198adbcb2d        523MB
	docker-router-advertiser      HEAD.171-2f1445e6   c62ac5b91162        480MB
	docker-router-advertiser      latest              c62ac5b91162        480MB
	docker-platform-monitor       HEAD.171-2f1445e6   efee72060807        605MB
	docker-platform-monitor       latest              efee72060807        605MB
	docker-nat                    HEAD.171-2f1445e6   41b036156187        526MB
	docker-nat                    latest              41b036156187        526MB
	docker-dhcp-relay             HEAD.171-2f1445e6   7894aba96cf7        487MB
	docker-dhcp-relay             latest              7894aba96cf7        487MB
	docker-database               HEAD.171-2f1445e6   11fb7fe17769        480MB
	docker-database               latest              11fb7fe17769        480MB
	docker-lldp                   HEAD.171-2f1445e6   42cc914e614b        520MB
	docker-lldp                   latest              42cc914e614b        520MB
	docker-orchagent              HEAD.171-2f1445e6   18a2cf43b1fa        554MB
	docker-orchagent              latest              18a2cf43b1fa        554MB
	docker-sonic-telemetry        HEAD.171-2f1445e6   61784f3e2daf        554MB
	docker-sonic-telemetry        latest              61784f3e2daf        554MB
	docker-sonic-mgmt-framework   HEAD.171-2f1445e6   4e9235bff8a3        681MB
	docker-sonic-mgmt-framework   latest              4e9235bff8a3        681MB
	docker-fpm-frr                HEAD.171-2f1445e6   e30a3907c4ba        540MB
	docker-fpm-frr                latest              e30a3907c4ba        540MB
	docker-sflow                  HEAD.171-2f1445e6   f2369b2ba634        523MB
	docker-sflow                  latest              f2369b2ba634        523MB

	root@sonic-z9332-10429:/var/log#

 **Attach debug file `sudo generate_dump`:**
[sonic_dump_sonic-z9332-10429_20201230_104503.tar.gz](https://github.com/Azure/sonic-buildimage/files/5754091/sonic_dump_sonic-z9332-10429_20201230_104503.tar.gz)

Script log : 
[Acl_Script_log.txt](https://github.com/Azure/sonic-buildimage/files/5754094/Acl_Script_log.txt)

fp show output: 
[fp_show.txt](https://github.com/Azure/sonic-buildimage/files/5754096/fp_show.txt)

**Comment by chitra-raghavan** [comment]
"crm show resources acl group and "show acl table " output below. 

**BEFORE APPLYING ACL :**

	root@sonic-z9332-10429:~# crm show resources acl group

	Stage    Bind Point    Resource Name      Used Count    Available Count
	-------  ------------  ---------------  ------------  -----------------
	INGRESS  PORT          acl_group                  32                224
	INGRESS  PORT          acl_table                   2                  0
	INGRESS  LAG           acl_group                   0                224
	INGRESS  LAG           acl_table                   2                  0
	INGRESS  VLAN          acl_group                   0                224
	INGRESS  VLAN          acl_table                   0                  2
	INGRESS  RIF           acl_group                   0                224
	INGRESS  RIF           acl_table                   0                  0
	INGRESS  SWITCH        acl_group                   0                224
	INGRESS  SWITCH        acl_table                   0                  2
	EGRESS   PORT          acl_group                   0                224
	EGRESS   PORT          acl_table                   0                  4
	EGRESS   LAG           acl_group                   0                224
	EGRESS   LAG           acl_table                   0                  4
	EGRESS   VLAN          acl_group                   0                224
	EGRESS   VLAN          acl_table                   0                  4
	EGRESS   RIF           acl_group                   0                224
	EGRESS   RIF           acl_table                   0                  4
	EGRESS   SWITCH        acl_group                   0                224
	EGRESS   SWITCH        acl_table                   0                  4


	root@sonic-z9332-10429:~# show acl table
	Name        Type       Binding      Description    Stage
	----------  ---------  -----------  -------------  -------
	SNMP_ACL    CTRLPLANE  SNMP         SNMP_ACL       ingress
	DATAACL     L3         Ethernet0    DATAACL        ingress
						   Ethernet8
						   Ethernet16
						   Ethernet24
						   Ethernet32
						   Ethernet40
						   Ethernet48
						   Ethernet56
						   Ethernet64
						   Ethernet72
						   Ethernet80
						   Ethernet88
						   Ethernet96
						   Ethernet104
						   Ethernet112
						   Ethernet120
						   Ethernet128
						   Ethernet136
						   Ethernet144
						   Ethernet152
						   Ethernet160
						   Ethernet168
						   Ethernet176
						   Ethernet184
						   Ethernet192
						   Ethernet200
						   Ethernet208
						   Ethernet216
						   Ethernet224
						   Ethernet232
						   Ethernet240
						   Ethernet248
	EVERFLOWV6  MIRRORV6   Ethernet0    EVERFLOWV6     ingress
						   Ethernet8
						   Ethernet16
						   Ethernet24
						   Ethernet32
						   Ethernet40
						   Ethernet48
						   Ethernet56
						   Ethernet64
						   Ethernet72
						   Ethernet80
						   Ethernet88
						   Ethernet96
						   Ethernet104
						   Ethernet112
						   Ethernet120
						   Ethernet128
						   Ethernet136
						   Ethernet144
						   Ethernet152
						   Ethernet160
						   Ethernet168
						   Ethernet176
						   Ethernet184
						   Ethernet192
						   Ethernet200
						   Ethernet208
						   Ethernet216
						   Ethernet224
						   Ethernet232
						   Ethernet240
						   Ethernet248
	SSH_ONLY    CTRLPLANE  SSH          SSH_ONLY       ingress
	EVERFLOW    MIRROR     Ethernet0    EVERFLOW       ingress
						   Ethernet8
						   Ethernet16
						   Ethernet24
						   Ethernet32
						   Ethernet40
						   Ethernet48
						   Ethernet56
						   Ethernet64
						   Ethernet72
						   Ethernet80
						   Ethernet88
						   Ethernet96
						   Ethernet104
						   Ethernet112
						   Ethernet120
						   Ethernet128
						   Ethernet136
						   Ethernet144
						   Ethernet152
						   Ethernet160
						   Ethernet168
						   Ethernet176
						   Ethernet184
						   Ethernet192
						   Ethernet200
						   Ethernet208
						   Ethernet216
						   Ethernet224
						   Ethernet232
						   Ethernet240
						   Ethernet248
	root@sonic-z9332-10429:~#

**AFTER APPLYING ACL**



	root@sonic-z9332-10429:~# sonic-cfggen -j  test_acl.json --write-to-db
	root@sonic-z9332-10429:~#
	root@sonic-z9332-10429:~# 
	root@sonic-z9332-10429:~# crm show resources acl group

	Stage    Bind Point    Resource Name      Used Count    Available Count
	-------  ------------  ---------------  ------------  -----------------
	INGRESS  PORT          acl_group                  32                224
	INGRESS  PORT          acl_table                   2                  0
	INGRESS  LAG           acl_group                   0                224
	INGRESS  LAG           acl_table                   2                  0
	INGRESS  VLAN          acl_group                   0                224
	INGRESS  VLAN          acl_table                   0                  2
	INGRESS  RIF           acl_group                   0                224
	INGRESS  RIF           acl_table                   0                  0
	INGRESS  SWITCH        acl_group                   0                224
	INGRESS  SWITCH        acl_table                   0                  2
	EGRESS   PORT          acl_group                   0                224
	EGRESS   PORT          acl_table                   0                  4
	EGRESS   LAG           acl_group                   0                224
	EGRESS   LAG           acl_table                   0                  4
	EGRESS   VLAN          acl_group                   0                224
	EGRESS   VLAN          acl_table                   0                  4
	EGRESS   RIF           acl_group                   0                224
	EGRESS   RIF           acl_table                   0                  4
	EGRESS   SWITCH        acl_group                   0                224
	EGRESS   SWITCH        acl_table                   0                  4


	root@sonic-z9332-10429:~# show acl table
	Name               Type       Binding      Description                 Stage
	-----------------  ---------  -----------  --------------------------  -------
	SNMP_ACL           CTRLPLANE  SNMP         SNMP_ACL                    ingress
	DATAACL            L3         Ethernet0    DATAACL                     ingress
								  Ethernet8
								  Ethernet16
								  Ethernet24
								  Ethernet32
								  Ethernet40
								  Ethernet48
								  Ethernet56
								  Ethernet64
								  Ethernet72
								  Ethernet80
								  Ethernet88
								  Ethernet96
								  Ethernet104
								  Ethernet112
								  Ethernet120
								  Ethernet128
								  Ethernet136
								  Ethernet144
								  Ethernet152
								  Ethernet160
								  Ethernet168
								  Ethernet176
								  Ethernet184
								  Ethernet192
								  Ethernet200
								  Ethernet208
								  Ethernet216
								  Ethernet224
								  Ethernet232
								  Ethernet240
								  Ethernet248
	EVERFLOWV6         MIRRORV6   Ethernet0    EVERFLOWV6                  ingress
								  Ethernet8
								  Ethernet16
								  Ethernet24
								  Ethernet32
								  Ethernet40
								  Ethernet48
								  Ethernet56
								  Ethernet64
								  Ethernet72
								  Ethernet80
								  Ethernet88
								  Ethernet96
								  Ethernet104
								  Ethernet112
								  Ethernet120
								  Ethernet128
								  Ethernet136
								  Ethernet144
								  Ethernet152
								  Ethernet160
								  Ethernet168
								  Ethernet176
								  Ethernet184
								  Ethernet192
								  Ethernet200
								  Ethernet208
								  Ethernet216
								  Ethernet224
								  Ethernet232
								  Ethernet240
								  Ethernet248
	DATA_INGRESS_TEST  L3         Ethernet0    DATA_INGRESS_TEST, ingress  ingress
	SSH_ONLY           CTRLPLANE  SSH          SSH_ONLY                    ingress
	EVERFLOW           MIRROR     Ethernet0    EVERFLOW                    ingress
								  Ethernet8
								  Ethernet16
								  Ethernet24
								  Ethernet32
								  Ethernet40
								  Ethernet48
								  Ethernet56
								  Ethernet64
								  Ethernet72
								  Ethernet80
								  Ethernet88
								  Ethernet96
								  Ethernet104
								  Ethernet112
								  Ethernet120
								  Ethernet128
								  Ethernet136
								  Ethernet144
								  Ethernet152
								  Ethernet160
								  Ethernet168
								  Ethernet176
								  Ethernet184
								  Ethernet192
								  Ethernet200
								  Ethernet208
								  Ethernet216
								  Ethernet224
								  Ethernet232
								  Ethernet240
								  Ethernet248
	root@sonic-z9332-10429:~#

**Comment by gechiang** [comment]
@chitra-raghavan This issue is due to TH3 has lower ACL resource and if DATA_ACL is already present, then it will not have space available to accommodate another ACL TABLE (in this case Test_acl).
Please remove DATA_ACL (or do not program it to begin with) and try again with the TEST_ACL table addition to see if it still fails.  The expectation is that it should not fail any more.
After your validation, please go ahead close this issue.
Thanks!

**Comment by gechiang** [comment]
@chitra-raghavan I assume no news is good news...  I am closing this issue now. if you feel this is unresolved, please reopen it...
Thanks!
