### ISSUE TITLE
Not sorted interfaces in config_db.json file

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6328]
**Description**

Not sorted interface in config_db.json file. In the previous builds, the configuration file was readable and sorted but for now it like some randomly generated and not sorted content, it is very hard to read, search and troubleshoot something manually there.

**Steps to reproduce the issue:**
1. Run more /etc/sonic/config_db.json
2. Observer unsorted interfaces in the configuration file

**Describe the results you received:**
`
 "PORT": {
        "Ethernet180": {  <----------------first port should be Ethernet0 (etp1)
            "alias": "etp46",
            "admin_status": "up",
            "mtu": "9100",
            "lanes": "180,181,182,183",
            "index": "46"
        },

        "Ethernet8": {
            "alias": "etp3",
            "admin_status": "up",
            "mtu": "9100",
            "lanes": "8,9,10,11",
            "index": "3"
        },

        "Ethernet44": {
            "alias": "etp12",
            "admin_status": "up",
            "mtu": "9100",
            "lanes": "44,45,46,47",
            "index": "12"
        },

        "Ethernet184": {
            "alias": "etp47",
            "admin_status": "up",
            "mtu": "9100",
            "lanes": "184,185,186,187",
            "index": "47"
        },
        "Ethernet188": {
            "alias": "etp48",
            "admin_status": "up",
            "mtu": "9100",
            "lanes": "188,189,190,191",
            "index": "48"
        },
        "Ethernet0": {
            "alias": "etp1",
            "admin_status": "up",
            "mtu": "9100",
            "lanes": "0,1,2,3",
            "index": "1"
        },
`

**Describe the results you expected:**
Expected that interfaces will be sorted like before.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
  SONiC Software Version: SONiC.201911.47-6d386540
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 6d386540
Build date: Mon Dec 28 10:18:16 UTC 2020
Built by: sw-r2d2-bot@r-build-sonic-ci02

Platform: x86_64-mlnx_msn3700c-r0
HwSKU: ACS-MSN3700C
ASIC: mellanox
Serial Number: MT1935X01905
Uptime: 09:56:07 up 16 min,  2 users,  load average: 3.68, 1.66, 0.92

Docker images:
REPOSITORY                    TAG                  IMAGE ID            SIZE
docker-syncd-mlnx             201911.47-6d386540   927fc7a1435c        399MB
docker-syncd-mlnx             latest               927fc7a1435c        399MB
docker-sonic-telemetry        201911.47-6d386540   f29b5dc19901        353MB
docker-sonic-telemetry        latest               f29b5dc19901        353MB
docker-router-advertiser      201911.47-6d386540   29d0d50f7ede        290MB
docker-router-advertiser      latest               29d0d50f7ede        290MB
docker-platform-monitor       201911.47-6d386540   235edc0168dd        666MB
docker-platform-monitor       latest               235edc0168dd        666MB
docker-fpm-frr                201911.47-6d386540   0f6aea036977        335MB
docker-fpm-frr                latest               0f6aea036977        335MB
docker-teamd                  201911.47-6d386540   c748a9b70235        315MB
docker-teamd                  latest               c748a9b70235        315MB
docker-lldp-sv2               201911.47-6d386540   f22e5c4d1e37        312MB
docker-lldp-sv2               latest               f22e5c4d1e37        312MB
docker-dhcp-relay             201911.47-6d386540   c863de8bd9e2        300MB
docker-dhcp-relay             latest               c863de8bd9e2        300MB
docker-database               201911.47-6d386540   761c2ff57234        290MB
docker-database               latest               761c2ff57234        290MB
docker-snmp-sv2               201911.47-6d386540   2014b20828aa        348MB
docker-snmp-sv2               latest               2014b20828aa        348MB
docker-orchagent              201911.47-6d386540   5da88fc05dde        333MB
docker-orchagent              latest               5da88fc05dde        333MB
docker-sflow                  201911.47-6d386540   333ed88b554b        315MB
docker-sflow                  latest               333ed88b554b        315MB
docker-nat                    201911.47-6d386540   9a1f6037cf02        316MB
docker-nat                    latest               9a1f6037cf02        316MB
docker-sonic-mgmt-framework   201911.47-6d386540   3fe1e32ba0f2        429MB
docker-sonic-mgmt-framework   latest               3fe1e32ba0f2        429MB
    ```

**Comment by liat-grozovik** [comment]
@lguohan I am not sure if this is a bug or not but clearly a change in behaviour.
Is there a req to keep the configuration sorted? if not, and there is no real reason to sort it, this issue can be closed.
But if there was an intention to sort it (i think it is also user friendly) we should understand why this was changed recently.

**Comment by tahmed-dev** [comment]
Thanks @Hedgehog-Guru , @liat-grozovik . The sorting of config_db file was remove via commit [9122d16d](https://github.com/Azure/sonic-buildimage/commit/9122d16dd28c36d10a05ce0b30d81ff6273f1c63). The sorting logic was mainly used in unit test to compare outputs as strings and so the need for the string to be sorted. Since `natsort` cause almost 1s during run-time and there is no requirement to have config_db sorted (might be useful for manual diffs,) `natsort` was removed and the verification logic is moved to the unit tests. Please let me know if you further concerns. If not, I'd recommend closing this issue.

**Comment by liat-grozovik** [comment]
I think that if such change is done the right way is to inform it to the community and somehow document it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Hedgehog-Guru** [comment]
Dear @tahmed-dev, in this particular case, I think the problem is extremely critical. The operating system for a network engineer is CLI and configuration files.
SONiC, as an operating system is designed not only for automated deployment, but also for network engineers to work with it, as evidenced by the presence of the command line, and configuration files are the result of commands. Of the hardware and operating systems presented in the top segment for it, I have never encountered that configuration files were not sorted. Unsorted configuration files and command results result in huge configuration costs.
I strongly recommend, from the point of view of the network engineer, to return the sorting of the configuration file. Let's not ruin the attitude of network engineers to work with the SONiC operating system.

**Comment by liat-grozovik** [comment]
I totally agree.
Although SONiC upstream code removed as explained there are users who expect to have it sorted for easily use and tracking.
I strongly vote for having that back.
Also there is non public automation and validations that end users have internally so I do think this will break it for them as well.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lguohan** [comment]
config save is not on the critical path? I understand the logic to remove it in sonic cfggen, but maybe we can add it back for config save? @tahmed-dev

**Comment by liat-grozovik** [comment]
@tahmed-dev will you return the logic to config_db which is the end user DB used?

**Comment by tahmed-dev** [comment]
> config save is not on the critical path? I understand the logic to remove it in sonic cfggen, but maybe we can add it back for config save? @tahmed-dev

@lguohan I agree that `config save` is not on the critical path and so the logic could be added there.

**Comment by tahmed-dev** [comment]
> @tahmed-dev will you return the logic to config_db which is the end user DB used?

@liat-grozovik, @Hedgehog-Guru It would take some time as I am tracking a high priority item at the moment.

**Comment by dprital** [comment]
@tahmed-dev  - what is the status of this issue ? was the sort logic put back ?
