### ISSUE TITLE
Control fans and sensors by BMC

### ISSUE THREAD

**Issue by YaoTien** [Azure/sonic-buildimage#633]
Hi,

I would like to porting fans and sensors for our device, and had been study the porting guide.
As the guide, it looks like fans and sensors be manage by CPU.
However, our device adopt BMC to manage fans and sensors, and commucate to system through IPMI.
As BMC case, SONiC how to control fans and sensors?
Can the porting guide be used on BMC case?
Thanks for your response.

**Comment by lguohan** [comment]
you mention "BMC to manage fans and sensors", since BMC already does that, what do you need SONiC to do with the fans and sensors? As you mention IPMI, SONiC can also use IPMI to retrieve information from BMC.

**Comment by YaoTien** [comment]
Hi @Iguohan,
So I don't need to add fancontrol, sensors.conf and led_control.py files, right?
Thanks.

**Comment by stcheng** [comment]
I think fancontrol is not needed in SONiC as it is already handled outside in BMC.
As for the sensors.conf, I think it is not bad to put one inside SONiC as we're doing passive monitoring on the sensors that the system could detect. As for the led_control.py, it is related to the front panel port LEDs not related to the box peripheral LEDs.

**Comment by YaoTien** [comment]
As I say, BMC manage fans, sensors, eeproms of sfp in our board.
So when I do "show environment", only display CPU's temperatures.
Should I get sensors information by IPMI and integrate to "show environment"?
Thanks.

**Comment by jleveque** [comment]
Hi @YaoTien. The new SONiC platform API is now available [here](). https://github.com/Azure/sonic-platform-common/tree/master/sonic_platform_base. We will soon be transitioning all daemons and CLI to interact with platform hardware using this API. You should implement the API for your platform to communicate with your BMC. The "show environment" command will eventually display sensor data by calling functions in the new platform API.

**Comment by jleveque** [comment]
@YaoTien: Since you haven't responded to my previous comment, I am assuming the new platform API will suffice. Please feel free to reopen this or open a new issue if need be.
