### ISSUE TITLE
[Platform system health] ASIC key is not handled properly in system health daemon

### ISSUE THREAD

**Issue by aravindmani-1** [Azure/sonic-buildimage#6343]
**Description**
The ASIC table key used in system health is “TEMPERATURE_INFO|ASIC”. 
https://github.com/Azure/sonic-buildimage/blob/a64994ec298bc8cae8f8b03216d6c4e1ed27586e/src/system-health/health_checker/hardware_checker.py#L11

In Dell platforms, we don’t have this key.
    root@sonic:/# redis-cli -n  6  hgetall  "TEMPERATURE_INFO|ASIC"
    (empty array)
    root@sonic:~#

The available list of keys for Dell S6100 are 
root@sonic:~# redis-cli -n 6 keys "*TEMPERATURE_INFO*"
1) "TEMPERATURE_INFO|ASIC On-board Rear"
2) "TEMPERATURE_INFO|CPU Core 1"
3) "TEMPERATURE_INFO|CPU Core 2"
4) "TEMPERATURE_INFO|Front GE board"
5) "TEMPERATURE_INFO|CPU On-board"
6) "TEMPERATURE_INFO|ASIC On-board Front"
7) "TEMPERATURE_INFO|System Front"
8) "TEMPERATURE_INFO|CPU Core 3"
9) "TEMPERATURE_INFO|Front SFP+ board"
10) "TEMPERATURE_INFO|CPU Core 0"
root@sonic:~#

If we change the system health code to retrieve one of the keys mentioned(ASIC on-board Rear /ASIC on-board Front”), the error was not seen.
root@sonic:~# show system-health summary              
  Services:
    Status: OK
  Hardware:
    Status: OK

**Steps to reproduce the issue:**
1. Load master image and create a system health json file for Dell S6100 platform.
2. Check show system-health summary in Dell S6100

**Describe the results you received:**
In some Dell platforms, we’ve only one ASIC sensor(ASIC On-board) alone.
Currently, ASIC Temperature error will be logged when executing system health CLI if this issue is not fixed.
root@sonic:~# show system-health summary
  Services:
    Status: OK
  Hardware:
    Status: Not OK
    Reasons: Failed to get ASIC temperature

**Describe the results you expected:**
Status was set to OK when ASIC key(ASIC on-board Front/Rear is used).

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
root@sonic:~# show ver
SONiC Software Version: SONiC.master.522-dirty-20201215.060116
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 4257c792
Build date: Tue Dec 15 06:08:23 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
ASIC Count: 1
Serial Number: CFXYZP2
Uptime: 03:37:19 up 4 days, 19:26,  1 user,  load average: 4.13, 3.67, 3.61

Docker images:
REPOSITORY                    TAG                                IMAGE ID            SIZE
docker-snmp                   latest                             b483850a99c9        485MB
docker-snmp                   master.522-dirty-20201215.060116   b483850a99c9        485MB
docker-teamd                  latest                             278ec7d8b43a        492MB
docker-teamd                  master.522-dirty-20201215.060116   278ec7d8b43a        492MB
docker-sonic-mgmt-framework   latest                             8a8002b5b7ed        609MB
docker-sonic-mgmt-framework   master.522-dirty-20201215.060116   8a8002b5b7ed        609MB
docker-router-advertiser      latest                             c386bafb71a1        448MB
docker-router-advertiser      master.522-dirty-20201215.060116   c386bafb71a1        448MB
docker-platform-monitor       latest                             2ddebb766809        573MB
docker-platform-monitor       master.522-dirty-20201215.060116   2ddebb766809        573MB
docker-lldp                   latest                             82862b16aea0        488MB
docker-lldp                   master.522-dirty-20201215.060116   82862b16aea0        488MB
docker-dhcp-relay             latest                             b457f75353f5        455MB
docker-dhcp-relay             master.522-dirty-20201215.060116   b457f75353f5        455MB
docker-database               latest                             d71f985a3277        448MB
docker-database               master.522-dirty-20201215.060116   d71f985a3277        448MB
docker-orchagent              latest                             901fedf415f3        506MB
docker-orchagent              master.522-dirty-20201215.060116   901fedf415f3        506MB
docker-nat                    latest                             bd470d765c1d        495MB
docker-nat                    master.522-dirty-20201215.060116   bd470d765c1d        495MB
docker-sonic-telemetry        latest                             2be7723ff3c6        523MB
docker-sonic-telemetry        master.522-dirty-20201215.060116   2be7723ff3c6        523MB
docker-fpm-frr                latest                             019f642edec4        508MB
docker-fpm-frr                master.522-dirty-20201215.060116   019f642edec4        508MB
docker-sflow                  latest                             075965ad793b        493MB
docker-sflow                  master.522-dirty-20201215.060116   075965ad793b        493MB
docker-syncd-brcm             latest                             d8c8182d9372        542MB
docker-syncd-brcm             master.522-dirty-20201215.060116   d8c8182d9372        542MB

    **Attach debug file `sudo generate_dump`:**

**Comment by sujinmkang** [comment]
@keboliu, @Junchao-Mellanox: Can you please comment on this?
And also I have one question in addition to this issue, why does the system health daemon check only the ASIC temperature not other components' temperature?

**Comment by Junchao-Mellanox** [comment]
Hi @sujinmkang , 

1. Why we hard code "TEMPERATURE_INFO|ASIC" as the key of ASIC thermal object?  I remember I had some discussion with the community when review the HLD. It is not possible to get ASIC temperature among all thermal objects without knowing the ASIC key. So we got an agreement that, the thermal name for ASIC should be "ASIC" for all vendors and it is vendor's responsibility to align it. 
2. Why does the system health daemon check only the ASIC temperature not other components's temperature? I suppose the reason is that not all thermal object defines the "get_high_threshold" function. For example, not all SFP cables has the ability to get its temperature and temperature threshold. As SFP cables can be replaced and different cables have different thermal capability, it is hard to check such thermal object in system health.

**Comment by aravindmani-1** [comment]
Hi @Junchao-Mellanox,

Regarding the first item, If there are multiple ASIC keys(ASIC on-board Front/Rear), we can not have the same ASIC key name.
How do you want to handle this?.

**Comment by sujinmkang** [comment]
@Junchao-Mellanox  and @aravindmani-1 
To support multi-ASIC and multiple internal sensor in each ASIC, I want to re-define the DB schema as below.
The ASIC thermal monitoring hld (https://github.com/Azure/SONiC/blob/master/doc/asic_thermal_monitoring_hld.md) has defined multiple temperature sensor reading for each ASIC.
thermalctld uses the temperature values from the state db updated by the ASIC thermal monitoring polling module.
```
; Defines information for an ASIC thermal object
key                               =  "TEMPERATURE_INFO|ASIC {}"
; field                            = value
timestamp                    = STRING                         ; timestamp for the temperature fetched
high_threshold             = FLOAT                          ; temperature high threshold
critical_high_threshold = FLOAT                          ; temperature critical high threshold
low_threshold               = FLOAT                          ; temperature low threshold
critical_low_threshold   = FLOAT                          ; temperature critical low threshold
warning_status             = BOOLEAN                     ; temperature warning status
average_temperature    = FLOAT                          ; current average temperature value
maximum_temperature  = FLOAT                         ; maximum temperature value
temperature_0              = FLOAT                          ; ASIC internal sensor 0 temperature value
...
temperature_N              = FLOAT                          ; ASIC internal sensor N temperature value
```
Please share your comments if you have any other idea.

**Comment by aravindmani-1** [comment]
@sujinmkang I don't think ASIC on-board Front/Rear sensors will have internal temperature 0 to N sensors.
