### ISSUE TITLE
SONIC build fails with "Makefile:95: recipe for target 'github.com/go-redis/redis' failed" error

### ISSUE THREAD

**Issue by Mithunkh** [Azure/sonic-buildimage#6378]
Hi Team,

While compiling the Mellanox-SONiC image as mentioned In the https://github.com/Azure/sonic-buildimage/tree/201911, we are getting below error. Kindly provide your input to solve this compilation issue.

Error:
[ target/debs/stretch/libyang-dev_1.0.73_amd64.deb-install ]
02:41:03 [ building ] [ target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb ]
02:41:09 [ finished ] [ target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb ]
02:41:09 [ FAIL LOG START ] [ target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb ]
02:41:09 /sonic/src/sonic-mgmt-framework /sonic
02:41:09 dpkg-buildpackage: info: source package sonic-mgmt-framework
02:41:09 dpkg-buildpackage: info: source version 1.0-01
02:41:09 dpkg-buildpackage: info: source distribution UNRELEASED
02:41:09 dpkg-buildpackage: info: source changed by Prabhu Sreenivasan <prabhu.sreenivassan@broadcom.com>
02:41:09 dpkg-source --before-build sonic-mgmt-framework
02:41:09 dpkg-buildpackage: info: host architecture amd64
02:41:09 fakeroot debian/rules clean
02:41:09 make[1]: Entering directory '/sonic/src/sonic-mgmt-framework'
02:41:09 dh clean --with systemd
02:41:09 dh_auto_clean
02:41:09 make -j1 clean
02:41:09 make[2]: Entering directory '/sonic/src/sonic-mgmt-framework'
02:41:09 make -C src/rest clean
02:41:09 make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/rest'
02:41:09 make -C /sonic/src/sonic-mgmt-framework/models clean
02:41:09 make[4]: Entering directory '/sonic/src/sonic-mgmt-framework/models'
02:41:09 find: '../build/yaml': No such file or directory
02:41:09 rm -rf ../build/rest_server/dist
02:41:09 rm -rf ../build/rest_server/codegen
02:41:09 rm -rf ../build/swagger_client_py
02:41:09 make -C yang clean
02:41:09 make[5]: Entering directory '/sonic/src/sonic-mgmt-framework/models/yang'
02:41:09 find: '../../models/yang/annotations/openapi_annotations': No such file or directory
02:41:09 rm -rf ../../build/yaml
02:41:09 rm -rf allyangs.tree allyangs_tree.html
02:41:09 make[5]: Leaving directory '/sonic/src/sonic-mgmt-framework/models/yang'
02:41:09 make[4]: Leaving directory '/sonic/src/sonic-mgmt-framework/models'
02:41:09 make -C /sonic/src/sonic-mgmt-framework/models/yang clean
02:41:09 make[4]: Entering directory '/sonic/src/sonic-mgmt-framework/models/yang'
02:41:09 find: '../../models/yang/annotations/openapi_annotations': No such file or directory
02:41:09 rm -rf ../../build/yaml
02:41:09 rm -rf allyangs.tree allyangs_tree.html
02:41:09 make[4]: Leaving directory '/sonic/src/sonic-mgmt-framework/models/yang'
02:41:09 rm -f /sonic/src/sonic-mgmt-framework/build/rest_server/main /sonic/src/sonic-mgmt-framework/build/rest_server/generate_cert
02:41:09 rm -f /sonic/src/sonic-mgmt-framework/build/tests/rest/server.test
02:41:09 make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/rest'
02:41:09 make -C src/cvl clean
02:41:09 make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/cvl'
02:41:09 make -C tests clean
02:41:09 make[4]: Entering directory '/sonic/src/sonic-mgmt-framework/src/cvl/tests'
02:41:09 make[4]: go: Command not found
02:41:09 Removing files ...
02:41:09 rm -rf cfg_validator cv_acl cv_edit_op cv_vlan
02:41:09 make[4]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/cvl/tests'
02:41:09 rm -rf /sonic/src/sonic-mgmt-framework/pkg/linux_amd64/cvl.a
02:41:09 rm -rf /sonic/src/sonic-mgmt-framework/build/tests/cvl
02:41:09 make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/cvl'
02:41:09 make -C src/translib clean
02:41:09 make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/translib'
02:41:09 rm -f ocbinds/ocbinds.go
02:41:09 rm -f /sonic/src/sonic-mgmt-framework/pkg/linux_amd64/translib.a
02:41:09 rm -rf /sonic/src/sonic-mgmt-framework/build/tests/translib
02:41:09 make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/translib'
02:41:09 make -C src/cvl/schema clean
02:41:09 make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/cvl/schema'
02:41:09 Removing files ...
02:41:09 rm -rf *.yin *.tree
02:41:09 make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/cvl/schema'
02:41:09 make -C src/cvl cleanall
02:41:09 make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/cvl'
02:41:09 rm -rf build
02:41:09 rm -rf /sonic/src/sonic-mgmt-framework/pkg/linux_amd64/cvl.a
02:41:09 rm -rf /sonic/src/sonic-mgmt-framework/build/tests/cvl
02:41:09 make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/cvl'
02:41:09 rm -rf build/*
02:41:09 rm -rf debian/.debhelper
02:41:09 rm -rf /sonic/src/sonic-mgmt-framework/gopkgs/src/github.com/openconfig/goyang/annotate.go
02:41:09 make[2]: Leaving directory '/sonic/src/sonic-mgmt-framework'
02:41:09 dh_clean
02:41:09 make[1]: Leaving directory '/sonic/src/sonic-mgmt-framework'
02:41:09 debian/rules build
02:41:09 make[1]: Entering directory '/sonic/src/sonic-mgmt-framework'
02:41:09 make[1]: 'build' is up to date.
02:41:09 make[1]: Leaving directory '/sonic/src/sonic-mgmt-framework'
02:41:09 fakeroot debian/rules binary
02:41:09 make[1]: Entering directory '/sonic/src/sonic-mgmt-framework'
02:41:09 dh binary --with systemd
02:41:09 dh_update_autotools_config
02:41:09 dh_auto_configure
02:41:09 dh_auto_build
02:41:09 make -j1
02:41:09 make[2]: Entering directory '/sonic/src/sonic-mgmt-framework'
02:41:09 mkdir -p /sonic/src/sonic-mgmt-framework/build
02:41:09 /usr/local/go/bin/go get -v -d go.opentelemetry.io/otel
02:41:09 cd /sonic/src/sonic-mgmt-framework/gopkgs/src/go.opentelemetry.io/otel && git clean -fd && git checkout -fq 1f2eba2cdb0fb7e92ce199c6c06167d4080a55ff
02:41:09 /usr/local/go/bin/go get -v github.com/gorilla/mux
02:41:09 /usr/local/go/bin/go get -v github.com/Workiva/go-datastructures/queue
02:41:09 /usr/local/go/bin/go get -v github.com/go-redis/redis
02:41:09 get "go.opentelemetry.io/otel/metric": found meta tag get.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/metric?go-get=1
02:41:09 get "go.opentelemetry.io/otel/metric": verifying non-authoritative meta tag
02:41:09 go.opentelemetry.io/otel (download)
02:41:09 # cd /sonic/src/sonic-mgmt-framework/gopkgs/src/go.opentelemetry.io/otel; git pull --ff-only
02:41:09 You are not currently on a branch.
02:41:09 Please specify which branch you want to merge with.
02:41:09 See git-pull(1) for details.
02:41:09
02:41:09 git pull <remote> <branch>
02:41:09
02:41:09 package go.opentelemetry.io/otel/metric: exit status 1
02:41:09 get "go.opentelemetry.io/otel/trace": found meta tag get.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/trace?go-get=1
02:41:09 get "go.opentelemetry.io/otel/trace": verifying non-authoritative meta tag
02:41:09 package go.opentelemetry.io/otel/trace: cannot find package "go.opentelemetry.io/otel/trace" in any of:
02:41:09 /usr/local/go/src/go.opentelemetry.io/otel/trace (from $GOROOT)
02:41:09 /sonic/src/sonic-mgmt-framework/gopkgs/src/go.opentelemetry.io/otel/trace (from $GOPATH)
02:41:09 /sonic/src/sonic-mgmt-framework/src/go.opentelemetry.io/otel/trace
02:41:09 Makefile:95: recipe for target 'github.com/go-redis/redis' failed
02:41:09 make[2]: *** [github.com/go-redis/redis] Error 1
02:41:09 make[2]: Leaving directory '/sonic/src/sonic-mgmt-framework'
02:41:09 dh_auto_build: make -j1 returned exit code 2
02:41:09 debian/rules:3: recipe for target 'binary' failed
02:41:09 make[1]: *** [binary] Error 2
02:41:09 make[1]: Leaving directory '/sonic/src/sonic-mgmt-framework'
02:41:09 dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
02:41:09 [ FAIL LOG END ] [ target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb ]
02:41:09 slave.mk:349: recipe for target 'target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb' failed
02:41:09 make: *** [target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb] Error 1
02:41:10 make[1]: *** [Makefile.work:201: all] Error 2
02:41:10 make[1]: Leaving directory '/home/jenkins/workspace/SONiC/open-sonic-mellanox-201911'
02:41:10 make: *** [Makefile:8: all] Error 2

**Comment by Mithunkh** [comment]
We are able to solve this issue.

**Comment by kpetremann** [comment]
how did you solve the issue?

**Comment by kpetremann** [comment]
If anyone is having the same issue, the fix is to include this commit if not included in the hash you are building: https://github.com/Azure/sonic-buildimage/commit/ac5117f20b1a2652e3f4338a724644f8827d6660
