### ISSUE TITLE
warm reboot finalizer service could wait for not enabled component for 5 minutes

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#6383]
**Description**
With latest master / 202012 branch image. The warm reboot finalizer could wait for not enabled component to reconcile for 5 minutes.

**Steps to reproduce the issue:**
1. warm reboot
2.
3.

**Describe the results you received:**
warm reboot finalizer wait for 

Jan  7 19:40:33.519985 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Tearing down control plane assistant ...
Jan  7 19:40:36.712066 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Save in-memory database after warm reboot ...
Jan  7 19:40:37.301030 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Some components didn't finish reconcile: natsyncd ...
Jan  7 19:40:37.302572 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Finalizing warmboot...

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    latest master.
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
Jan  7 19:40:33.519985 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Tearing down control plane assistant ...
Jan  7 19:40:36.712066 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Save in-memory database after warm reboot ...
Jan  7 19:40:37.301030 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Some components didn't finish reconcile: natsyncd ...
Jan  7 19:40:37.302572 str-7260cx3-acs-1 NOTICE root: WARMBOOT_FINALIZER : Finalizing warmboot...
    ```

**Comment by shi-su** [comment]
Also noticed this issue in kvm warm reboot with latest images.

**Comment by lguohan** [comment]
this one is important. any clue? is this related to frr 7.5?
