### ISSUE TITLE
[Non-Functional ] [REST] | framework#supervisord: rest-server 2020/12/27 03:53:03 http: TLS handshake error from 10.80.54.9:56475: EOF

### ISSUE THREAD

**Issue by TzvikNVDA** [Azure/sonic-buildimage#6412]
[sonic_dump_ptr-sonic-n2-t2_20201130_083504.tar.gz](https://github.com/Azure/sonic-buildimage/files/5796380/sonic_dump_ptr-sonic-n2-t2_20201130_083504.tar.gz)
**Description**

Errors found in syslog 

**Steps to reproduce the issue:**
    1. run RDMA and TCP traffic for 12 hours 
    2.check logs

**Describe the results you received:**
    didn't see any impact on the traffic

**Describe the results you expected:**
    don't except to see errors like such in the log

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    SONiC Software Version: SONiC.201911.38-3b97d437
    Distribution: Debian 9.13
    Kernel: 4.9.0-11-2-amd64
    Build commit: 3b97d437
    Build date: Thu Dec 10 13:32:40 UTC 2020
    Built by: sw-r2d2-bot@r-build-sonic-ci02

    Platform: x86_64-mlnx_msn2700-r0
    HwSKU: Mellanox-SN2700-D48C8
    ASIC: mellanox
    Serial Number: MT1811X06314

**Errors found the sonic logs:**
- 
[sonic_dump_ptr-sonic-n2-t2_20201130_083504.tar.gz](https://github.com/Azure/sonic-buildimage/files/5796368/sonic_dump_ptr-sonic-n2-t2_20201130_083504.tar.gz)
framework#supervisord: rest-server 2020/12/27 03:53:03 http: TLS handshake error from 10.80.54.9:56475: EOF,
- framework#supervisord: rest-server 2020/12/27 03:52:53 http: TLS handshake error from 10.80.54.9:56881: EOF,
- framework#supervisord: rest-server 2020/12/27 03:54:22 http: TLS handshake error from 10.80.54.9:57350: EOF

**Comment by anshuv-mfst** [comment]
@ben-gale - could you please help on this, thanks.

**Comment by sachinholla** [comment]
Hi @TzvikNVDA, these errors indicate that a non-HTTPS request has been made to the REST server. We also observed the  Swagger UI (launched via `https://SWITCH_IP/ui`) can send such requests some time. Is your testcase involves sending any requests to the REST server or do you open Swagger UI?

I do not see these syslogs in the dump file; so I am not sure what was going on around that time.

**Comment by liat-grozovik** [comment]
@sachinholla this errors raised without any REST request in the test. it was a long weekend run of traffic tesst which the log had the error.
@dprital can you please help to upload dump when this error was raised?

**Comment by dprital** [comment]
Issue is not reproduced anymore.
