### ISSUE TITLE
FDB Entries are not cleared even after shutting down the respective interface on which the entry learned.

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6425]
Description:
FDB Entries are not cleared even after shutting down the respective interface on this the entry learned.

Procedure:

Created a VLAN using below commands
```
config vlan add 200
config vlan member add 200 Ethernet12
config vlan member add 200 Ethernet28

root@sonic-testing:/home/admin# show vlan config
Name VID Member Mode

Vlan200 200 Ethernet12 tagged
Vlan200 200 Ethernet28 tagged_
```
Now, sent matching traffic in bi-direction using external TG (IXIA). Observed that traffic is forwarding to the ports and respective FDB entries are created.
```
root@sonic-testing:/home/admin# show mac
    No. Vlan MacAddress Port Type

    1 200 00:01:02:05:07:08 Ethernet28 Dynamic
    2 200 00:01:02:05:06:08 Ethernet12 Dynamic_
```
Stop the traffic and shutdown the interface Ethernet12 and Ethernet28 respectively. Observed that interfaces are down but mac entries are not cleared.

```
root@sonic-testing:/home/admin# show mac
    No. Vlan MacAddress Port Type

    1 200 00:01:02:05:07:08 Ethernet28 Dynamic
    2 200 00:01:02:05:06:08 Ethernet12 Dynamic
```

**Comment by Hedgehog-Guru** [comment]
Bug moved from https://github.com/Azure/SONiC/issues/253

**Comment by anshuv-mfst** [comment]
This is not supported. MAC entries age out after 600sec/10mins.

**Comment by Hedgehog-Guru** [comment]
The bug has been fixed by the community. Not reproduced on SONIC.master with hash 6957e37

**Comment by Ezrickd** [comment]
can you please provide what is the PR to fix the issue in 201911 ?
