### ISSUE TITLE
tag/commit hash is not respected in new image builds

### ISSUE THREAD

**Issue by daall** [Azure/sonic-buildimage#6445]
**Description**
Recent 202012 builds from Jenkins are coming out like this:
```
admin@sonic~$ show ver
SONiC Software Version: SONiC.202012.8-dirty-20210113.013138
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 063a4859
Build date: Wed Jan 13 08:20:46 UTC 2021
Built by: johnar@jenkins-worker-7
```

**Steps to reproduce the issue:**
1. Build an image based on a specific tag or commit hash, w/o any outstanding/uncommitted changes.
2. Check the IMAGE_VERSION in the build output
3. Check `show ver` on a DUT

**Describe the results you received:**
Image says "dirty" and has a time stamp like so:
```
admin@sonic~$ show ver
SONiC Software Version: SONiC.202012.8-dirty-20210113.013138
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 063a4859
Build date: Wed Jan 13 08:20:46 UTC 2021
Built by: johnar@jenkins-worker-7
```

**Describe the results you expected:**
Image version should just have the tag/commit hash that it was built off of, since there are no outstanding changes when we build on Jenkins.

```
admin@sonic~$ show ver
SONiC Software Version: 202012.7-264ecb18
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 063a4859
Build date: Wed Jan 13 08:20:46 UTC 2021
Built by: johnar@jenkins-worker-7
```

**Additional information you deem important (e.g. issue happens only occasionally):**
If you look at the output in the build logs, it looks like the initial container/buster container has the correct image version, but subsequent ones do not.

**Comment by lguohan** [comment]
I do not think this issue is related to #6469

**Comment by dflynn-Nokia** [comment]
Oops, my bad. PR #6469 is linked to Issue #6455 and not #6445.

**Comment by daall** [comment]
It looks like the issue is coming from ./platform/broadcom/sonic-platform-modules-dell/z9332f/build/lib.linux-x86_64-2.7/sonic_platform/ipmihelper.py. This file is overridden by ./platform/broadcom/sonic-platform-modules-dell/common/ipmihelper.py in platform/broadcom/sonic-platform-modules-dell/debian/rules, which causes the workspace to become dirty. Following up with Dell.
