### ISSUE TITLE
warm-upgrade  (201811 to 202012) fails with orchagent core

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#6453]
**Description**

Orchagent crashes after warm upgrade from 201811 to 202012:

```
Jan 13 22:52:23.873260 str-s6100-acs-2 ERR swss#orchagent: :- wait: SELECT operation result: TIMEOUT on notify
Jan 13 22:52:23.873490 str-s6100-acs-2 ERR swss#orchagent: :- wait: failed to get response for notify
Jan 13 22:52:23.873986 str-s6100-acs-2 ERR swss#orchagent: :- initSaiRedis: Failed to notify syncd INIT_VIEW, rv:-1 gSwitchId 0
Jan 13 22:52:23.874146 str-s6100-acs-2 NOTICE swss#orchagent: :- uninitialize: begin
Jan 13 22:52:23.874268 str-s6100-acs-2 NOTICE swss#orchagent: :- uninitialize: begin
Jan 13 22:52:23.874318 str-s6100-acs-2 NOTICE swss#orchagent: :- ~RedisChannel: join ntf thread begin
Jan 13 22:52:23.874473 str-s6100-acs-2 WARNING swss#orchagent: :- meta_sai_on_switch_shutdown_request: switch_id oid:0x0 is of type SAI_OBJECT_TYPE_NULL, but expected SAI_OBJECT_TYPE_SWITCH
Jan 13 22:52:23.874590 str-s6100-acs-2 ERR swss#orchagent: :- operator(): not handled: SAI_OBJECT_TYPE_NULL
Jan 13 22:52:23.875813 str-s6100-acs-2 INFO swss#/supervisord: orchagent terminate called after throwing an instance of 'std::runtime_error'
Jan 13 22:52:23.876002 str-s6100-acs-2 INFO swss#/supervisord: orchagent   what():  :- operator(): not handled: SAI_OBJECT_TYPE_NULL
Jan 13 22:52:24.108779 str-s6100-acs-2 INFO swss#supervisord 2021-01-13 22:52:24,108 INFO exited: orchagent (terminated by SIGABRT (core dumped); not expected)
Jan 13 22:52:25.119274 str-s6100-acs-2 INFO swss#/supervisor-proc-exit-listener: Process orchagent exited unxepectedly. Terminating supervisor...
```

**Steps to reproduce the issue:**
1. Run `test_upgrade_path` testcase with base image as latest 201811 branch, and target image as latest 202012 branch image.
2. Check syslog - SWSS terminate and OA core is found.

**Describe the results you received:**

**Describe the results you expected:**
Successful warm upgrade.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vaibhavhd** [comment]
This is expected due to missing SAI support for the warm upgrade. ETA for the support - ~April.

**Comment by VenkatCisco** [comment]
how do we disable warm reboot in sonic so orchagent doesnt crash ? I see the same issue with 202012 branch.

**Comment by vaibhavhd** [comment]
@VenkatCisco, I don't know if you can disable warm-reboot altogether. If you want, you can still do cold reboot.
What is the issue that you had noticed? Were you trying to warm upgrade from 201811 to 202012?

This error should not be seen if you are trying to warm-reboot from 202012 to 202012 image.
