### ISSUE TITLE
Incorrect breakout port results in traceback prints instead of an error print

### ISSUE THREAD

**Issue by slutati1536** [Azure/sonic-buildimage#6484]
**Description**

Incorrect breakout results in traceback prints instead of an error print.

**Steps to reproduce the issue:**

1.sudo config interface breakout Ethernet4 2x50G
2.sudo config interface breakout Ethernet8 2x50G
3.sudo config interface breakout Ethernet8 1x100G
4.sudo config interface breakout Ethernet6 1x100G - Failure is expected but should have error print, not traceback

port Ethernet4 - breakout into Ethernet4 and Ethernet6, 
so in order to return port to old setting we should unbreak port Ethernet4 (as we did to Ethernet8)
not Ethernet6.

**Describe the results you received:**

Instead of an informative error print for the user, there is this trace back print:

root@r-panther-13:/home/admin# sudo config interface breakout Ethernet6 1x100G -v
Do you want to Breakout the port, continue? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/config", line 8, in <module>
    sys.exit(config())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/config/main.py", line 2283, in breakout
    cur_brkout_mode = cur_brkout_dict[interface_name]["brkout_mode"]
KeyError: 'Ethernet6'

**Describe the results you expected:**

An error message indicating Ethernet6 is a breakout result of breakout of Ethernet4, try command on Ethernet4.
or something along those lines.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
	
root@r-panther-13:/home/admin# show version

SONiC Software Version: SONiC.dpb_qa_image.0-23134a64
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 23134a64
Build date: Fri Jan 15 08:52:11 UTC 2021
Built by: vadymh@r-build-sonic03

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2020T04244
Uptime: 12:06:06 up  5:32,  1 user,  load average: 4.01, 4.38, 4.88

Docker images:
REPOSITORY                    TAG                       IMAGE ID            SIZE
docker-syncd-mlnx             dpb_qa_image.0-23134a64   72cd4f0bad6c        540MB
docker-syncd-mlnx             latest                    72cd4f0bad6c        540MB
docker-sflow                  dpb_qa_image.0-23134a64   070e94ad45b1        465MB
docker-sflow                  latest                    070e94ad45b1        465MB
docker-snmp                   dpb_qa_image.0-23134a64   4513d9bbede9        436MB
docker-snmp                   latest                    4513d9bbede9        436MB
docker-dhcp-relay             dpb_qa_image.0-23134a64   e9f74defdbed        402MB
docker-dhcp-relay             latest                    e9f74defdbed        402MB
docker-teamd                  dpb_qa_image.0-23134a64   4432208a6469        463MB
docker-teamd                  latest                    4432208a6469        463MB
docker-nat                    dpb_qa_image.0-23134a64   b0f25765961f        466MB
docker-nat                    latest                    b0f25765961f        466MB
docker-router-advertiser      dpb_qa_image.0-23134a64   875949f0ef94        395MB
docker-router-advertiser      latest                    875949f0ef94        395MB
docker-platform-monitor       dpb_qa_image.0-23134a64   77567d9ce67c        683MB
docker-platform-monitor       latest                    77567d9ce67c        683MB
docker-lldp                   dpb_qa_image.0-23134a64   9bba135a3864        435MB
docker-lldp                   latest                    9bba135a3864        435MB
docker-database               dpb_qa_image.0-23134a64   ae8be589a33c        394MB
docker-database               latest                    ae8be589a33c        394MB
docker-sonic-mgmt-framework   dpb_qa_image.0-23134a64   9f7fe89d1421        608MB
docker-sonic-mgmt-framework   latest                    9f7fe89d1421        608MB
docker-orchagent              dpb_qa_image.0-23134a64   5928b24d51e3        481MB
docker-orchagent              latest                    5928b24d51e3        481MB
docker-macsec                 dpb_qa_image.0-23134a64   b255f6b0ccf1        466MB
docker-macsec                 latest                    b255f6b0ccf1        466MB
docker-sonic-telemetry        dpb_qa_image.0-23134a64   4e502f1867fd        469MB
docker-sonic-telemetry        latest                    4e502f1867fd        469MB
docker-fpm-frr                dpb_qa_image.0-23134a64   684115a1f6cc        480MB
docker-fpm-frr         latest                    684115a1f6cc        480MB

   

    **Attach debug file `sudo generate_dump`:**

 could not generate because of issue #6462

I attached the output of reproducing the issue. [
[breakout_log.txt](https://github.com/Azure/sonic-buildimage/files/5830084/breakout_log.txt)
](url)

**Comment by zhenggen-xu** [comment]
This is a bug that CLI should check the key existence first.  @samaity

**Comment by zhenggen-xu** [comment]
should be addressed by https://github.com/Azure/sonic-utilities/pull/1270

**Comment by samaity** [comment]
already merged [Azure/sonic-utilities#1270](url)
