### ISSUE TITLE
syncd crash on master RPC image

### ISSUE THREAD

**Issue by Junchao-Mellanox** [Azure/sonic-buildimage#6622]
**Description**

syncd crash on master RPC image, error log:

```
Jan 28 03:50:38.688445 r-anaconda-10 INFO syncd#/supervisord: syncd /usr/bin/syncd: symbol lookup error: /usr/bin/syncd: undefined symbol: _ZN6apache6thrift6server13TSimpleServerC1ERKN5boost10shared_ptrINS0_10TProcessorEEERKNS4_INS0_9transport16TServerTransportEEERKNS4_INS9_17TTransportFactoryEEERKNS4_INS0_8protocol16TProtocolFactoryEEE

```

The issue is found beween hash 25e4d77 and hash 46b3bd5. I went over all changes between two hash, here is a suspicious commit: https://github.com/Azure/sonic-buildimage/commit/8ce1e3ed92ed0e141bd74d99f76af61e34b96ffd

In this commit, it removes libboost-all-dev and upgrade it to libboost1.71-dev.

**Steps to reproduce the issue:**
Load master RPC image

**Describe the results you received:**

syncd crash and not all dockers up

**Describe the results you expected:**

syncd should be able to up correctly

**Additional information you deem important (e.g. issue happens only occasionally):**

Found at hash 46b3bd5

**Comment by lguohan** [comment]
can you provide the suspicious commit id?

**Comment by Junchao-Mellanox** [comment]
https://github.com/Azure/sonic-buildimage/commit/8ce1e3ed92ed0e141bd74d99f76af61e34b96ffd

**Comment by lguohan** [comment]
@tahmed-dev , can you take a look?

**Comment by tahmed-dev** [comment]
> @tahmed-dev , can you take a look?

Looking.

**Comment by tahmed-dev** [comment]
The unmangled symbols is:
```apache::thrift::server::TSimpleServer::TSimpleServer(boost::shared_ptr<apache::thrift::TProcessor> const&, boost::shared_ptr<apache::thrift::transport::TServerTransport> const&, boost::shared_ptr<apache::thrift::transport::TTransportFactory> const&, boost::shared_ptr<apache::thrift::protocol::TProtocolFactory> const&)```

Looks like recent [TSimpleServer](https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/server/TSimpleServer.h#L42) is using `std::shared_ptr` instead of `boost::shared_ptr`

**Comment by tahmed-dev** [comment]
@lguohan to solve this issue we can
1. install thrift server v0.13.0 that moved away from boost smat ptr, or
2. change our build to use std smart ptr [here](https://github.com/Azure/sonic-buildimage/blob/master/src/thrift/Makefile#L29)

I also made change ([PR:784](https://github.com/Azure/sonic-sairedis/pull/784)) to azure pipeline to pull matching boost lib to what we have in buildimage.

**Comment by lguohan** [comment]
it is using CXXFLAGS="-DFORCE_BOOST_SMART_PTR" , I do not quite understand the proposal here.

**Comment by tahmed-dev** [comment]
The second proposal to remove the macro definition such that it will use `std::shared_ptr`. It's been adopted in c++11.

On another note and for first proposal above, there is no 0.13.0 in Debian packaging and it was not back-ported to buster.

**Comment by lguohan** [comment]
do you know why it is added, and who?

**Comment by tahmed-dev** [comment]
@stepanblyschak the boost flag was introduced via [PR:2640](https://github.com/Azure/sonic-buildimage/pull/2640/files#diff-58b852f06fd683d54ef700d479d367e58d099be7809ef6b3dcc9e0f20cc4bd7fR24) Wonder why it was forced to use boost variant?

**Comment by lguohan** [comment]
@liat-grozovik , can you take a look at the question?

**Comment by stepanblyschak** [comment]
@tahmed-dev @lguohan
Initially thrift 0.9.3 used boost pointers by default. With upgrade to 0.11.0 ```-DDFORCE_BOOST_SMART_PTR``` forces thrift to be backward compatible. Please see the boost usage in saithrift code: https://github.com/opencomputeproject/SAI/blob/master/test/saithrift/src/switch_sai_rpc_server.cpp#L77 which does not compile with 0.11.0 without  ```-DDFORCE_BOOST_SMART_PTR```

**Comment by tahmed-dev** [comment]
thanks @stepanblyschak! Indeed [thrift 0.11.0](https://github.com/apache/thrift/blob/0.11.0/lib/cpp/src/thrift/server/TSimpleServer.h#L43) is using `stdcxx` name that could be either `boost` or `std` and is not hard coded. In v0.13.0, `boost` use for smart pointers was removed since it was adopted in C++ standard.

Let me dig further why the mangled name differed when upgraded to boost v1.71. I am under the impression that this compile time dependency would not affect mangled names. I might be wrong. I'll wait to see the recent build of syncd rpc.

**Comment by tahmed-dev** [comment]
@Junchao-Mellanox, @daall was the issue seen with RPC syncd built after [PR:6649](https://github.com/Azure/sonic-buildimage/pull/6649) got merged and syncd compiled with that PR?

**Comment by Junchao-Mellanox** [comment]
I verified with hash aae9664, the issue is still there.

```
Feb  5 01:09:02.854833 r-tigris-13 INFO syncd#/supervisord: syncd /usr/bin/syncd: symbol lookup error: /usr/bin/syncd: undefined symbol: _ZN6apache6thrift6server13TSimpleServerC1ERKN5boost10shared_ptrINS0_10TProcessorEEERKNS4_INS0_9transport16TServerTransportEEERKNS4_INS9_17TTransportFactoryEEERKNS4_INS0_8protocol16TProtocolFactoryEEE
Feb  5 01:09:02.857073 r-tigris-13 INFO syncd#supervisord 2021-02-05 01:09:02,856 INFO exited: syncd (exit status 127; not expected)

```
