### ISSUE TITLE
Command not working "show system-health"

### ISSUE THREAD

**Issue by gcupryn** [Azure/sonic-buildimage#6641]
**Description**
On SONiC

show version

SONiC Software Version: SONiC.master.98-dirty-20210119.070609
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 755c7379
Build date: Tue Jan 19 07:17:32 UTC 2021
Built by: johnar@jenkins-worker-4

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
ASIC Count: 1

**Steps to reproduce the issue:**
1.run sudo show system-healt detail
2. or run sudo show system-health summary
3. or run sudo show system-health monitor-list

**Describe the results you received:**
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 103, in detail
    chassis = Chassis()
TypeError: __init__() missing 1 required positional argument: 'platform'

Looks like generate_dump is also buggy:
 sudo generate_dump
/usr/local/bin/generate_dump: line 89: syntax error near unexpected token fi'
/usr/local/bin/generate_dump: line 89:     fi'

**Comment by jleveque** [comment]
@gcupryn: The `generate_dump` syntax error was fixed [here](https://github.com/Azure/sonic-utilities/commit/bc2d27edc2923f5096b37a727200a8427f93463e#diff-cd1f4d6a5b025b3feb648269fec7b7db4285329bea576baba3734d16b1a1b263). Can you please try building from the latest HEAD?

**Comment by jleveque** [comment]
@Staphylo, @zzhiyuan: Can you please try to reproduce this `show system-health` issue on the Arista 7170-64C?

**Comment by gcupryn** [comment]
> @gcupryn: The `generate_dump` syntax error was fixed [here](https://github.com/Azure/sonic-utilities/commit/bc2d27edc2923f5096b37a727200a8427f93463e#diff-cd1f4d6a5b025b3feb648269fec7b7db4285329bea576baba3734d16b1a1b263). Can you please try building from the latest HEAD?

Thanks !
I have checked on other HW running :
**SONiC Software Version: SONiC.master.107-dirty-20210128.022453**
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: aab37b7f
Build date: Thu Jan 28 09:26:28 UTC 2021
Built by: johnar@jenkins-worker-4

**Platform: x86_64-accton_wedge100bf_32x-r0**
HwSKU: montara
ASIC: barefoot
ASIC Count: 1


This time seeing this :
```
admin@sonic:~$ sudo generate_dump
Command: sensors timedout after 5 minutes.
HW Mgmt dump script /usr/bin/hw-management-generate-dump.sh does not exist
/var/dump/sonic_dump_sonic_20210202_195025.tar.gz
admin@sonic:~$

```

**Comment by jleveque** [comment]
@gcupryn: It appears as though a dump file was generated, have you examined the dump file to see if it looks OK? I'm not sure about the `Command: sensors timedout after 5 minutes.` message, but the `HW Mgmt dump script /usr/bin/hw-management-generate-dump.sh does not exist` is expected if a `hw-management-generate-dump.sh` script does not exist for the platform, and this is a newly-added feature. If the dump file looks to have problems or the `Command: sensors timedout after 5 minutes.` message is consistent, please feel free to open a separate PR to track this.

Let's keep this issue focused on the `show system-health` issue on the Arista 7170 platform.

**Comment by gcupryn** [comment]
Thanks @jleveque,  indeed dump file looks correct.
I will take close look(including checks on other platforms) into   ```Command: sensors timedout after 5 minutes``` if needed I will created a separate ticket.

**Comment by zzhiyuan** [comment]
> @Staphylo, @zzhiyuan: Can you please try to reproduce this `show system-health` issue on the Arista 7170-64C?

I was able to replicate it. However, I want to ask why is system_health using:

sonic_platform.chassis.Chassis()

and not:

sonic_platform.platform.Platform().get_chassis()

as seen here:
https://github.com/Azure/sonic-platform-daemons/blob/master/sonic-xcvrd/xcvrd/xcvrd.py#L1227

**Comment by jleveque** [comment]
> > @Staphylo, @zzhiyuan: Can you please try to reproduce this `show system-health` issue on the Arista 7170-64C?
> 
> I was able to replicate it. However, I want to ask why is system_health using:
> 
> sonic_platform.chassis.Chassis()
> 
> and not:
> 
> sonic_platform.platform.Platform().get_chassis()
> 
> as seen here:
> https://github.com/Azure/sonic-platform-daemons/blob/master/sonic-xcvrd/xcvrd/xcvrd.py#L1227

Good question. @shlomibitton, @Junchao-Mellanox: Can you please answer explain why show/system_health.py does not instantiate the Platform class and obtain the Chassis object from there?

**Comment by Staphylo** [comment]
Just updating this issue to say that this problem still exists.

There is also another issue where the `system-health` cli makes a call to `chassis.initizalize_system_led()` on top of the typo, this method is not defined in `ChassisBase` and therefore probably not implemented by most vendors.
This method seem like a nice addition to the ChassisBase class but I have my doubts about a cli triggering a re-initialization of the status leds at each invocation. Feels this logic should be exercised by a daemon, `healthd` would be a good candidate.
See https://github.com/Azure/sonic-utilities/blob/c166f66827157f8e442e2176ce3efe166a5f6b5e/show/system_health.py#L46

After removing fixing `Chassis()` invocations by `Platform().get_chassis()` and removing the `chassis.initizalize_system_led()` the CLI does seem to work on Arista products.

**Comment by jleveque** [comment]
@shlomibitton, @Junchao-Mellanox: Can you please answer explain why show/system_health.py does not instantiate the Platform class and obtain the Chassis object from there?

**Comment by vemulabalaji** [comment]
Observed same issue on BCM boards. sonic_platform module not found. (Image: SONiC.202012.0-b4832d40a)

root@sonic:~# show system-health summary
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 21, in summary
    if os.environ["UTILITIES_UNIT_TESTING"] == "1":
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'UTILITIES_UNIT_TESTING'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 34, in summary
    from sonic_platform.chassis import Chassis
ModuleNotFoundError: No module named 'sonic_platform'
root@sonic:~#


admin@sonic:~$ show version

SONiC Software Version: SONiC.202012.0-b4832d40a
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: b4832d40a
Build date: Tue Jun 22 14:10:12 UTC 2021
Built by: balaji@sfstypc01

Platform: x86_64-accton_as7716_32x-r0
HwSKU: Accton-AS7716-32X
ASIC: broadcom
ASIC Count: 1
Serial Number: 771632X1716006
Uptime: 18:05:12 up 1 day,  4:35,  1 user,  load average: 0.70, 0.56, 0.42

**Comment by Staphylo** [comment]
FWIW I merged a fix in master for this issue as part of #8281
We do not have an immediate desire to backport this to 202012 but we could if it is being asked for.

Bear in mind that that there are still a few shortcomings in our platform API that will make `system-health` report faulty PSUs though they are just fine.
We're working on exposing the missing PSU power consumption API as well as an other fix required to make system-health and psud happy. We expect 202111 to have the feature fully supported and will consider backport to 202012 when we get there.

You should expect an output looking like this currently
```
root@sonic:~# show system-health detail
System status summary

  System status LED  amber
  Services:
    Status: OK
  Hardware:
    Status: Not OK
    Reasons: Invalid voltage data for PSU 2, voltage=N/A, range=[N/A,N/A]
	     Invalid voltage data for PSU 1, voltage=N/A, range=[N/A,N/A]

System services and devices monitor list

Name                Status    Type
------------------  --------  ----------
sonic               OK        System
rsyslog             OK        Process
root-overlay        OK        Filesystem
var-log             OK        Filesystem
routeCheck          OK        Program
container_checker   OK        Program
teamd|teamsyncd     OK        Program
teamd|teammgrd      OK        Program
syncd|syncd         OK        Program
syncd|dsserve       OK        Program
snmp|snmpd          OK        Program
snmp|snmp_subagent  OK        Program
sflow|sflowmgrd     OK        Program
lldp|lldpd_monitor  OK        Program
lldp|lldp_syncd     OK        Program
lldp|lldpmgrd       OK        Program
bgp|zebra           OK        Program
bgp|fpmsyncd        OK        Program
bgp|bgpd            OK        Program
bgp|staticd         OK        Program
bgp|bgpcfgd         OK        Program
bgp|bgpmon          OK        Program
PSU 1               Not OK    PSU
PSU 2               Not OK    PSU
fan1                OK        Fan
fan2                OK        Fan
fan3                OK        Fan
fan4                OK        Fan

System services and devices ignore list

Name             Status    Type
---------------  --------  ------
asic             Ignored   Device
psu.temperature  Ignored   Device
PSU1 Fan         Ignored   Device
PSU2 Fan         Ignored   Device
```

Once the fixes are in, the above example will no longer ignore psu fan and temperature and will no longer have missing voltage information. The asic temperature will remained ignored for the time being.
We should be able to add `psu.voltage` into the ignore list to get `OK` status everywhere, which I might consider in my next PR.

**Comment by gcupryn** [comment]
Thanks for the fix !
I have verified it on:


```
admin@sonic:~$ show version

SONiC Software Version: SONiC.master.27175-dirty-20210804.085023
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: e13f5246b
Build date: Wed Aug  4 15:10:52 UTC 2021
Built by: AzDevOps@sonic-build-workers-000KD9

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
ASIC Count: 1
```


Output on my side looks :
```
admin@sonic:~$ sudo show system-health detail
System status summary

  System status LED  amber
  Services:
    Status: OK
  Hardware:
    Status: Not OK
    Reasons: PSU 2 is out of power
             Invalid voltage data for PSU 1, voltage=N/A, range=[N/A,N/A]

System services and devices monitor list


Name                        Status    Type
--------------------------  --------  ----------
sonic                       OK        System
rsyslog                     OK        Process
root-overlay                OK        Filesystem
var-log                     OK        Filesystem
routeCheck                  OK        Program
diskCheck                   OK        Program
container_checker           OK        Program
container_memory_telemetry  OK        Program
PSU 1                       Not OK    PSU
PSU 2                       Not OK    PSU
fan1                        OK        Fan
fan2                        OK        Fan
fan3                        OK        Fan
fan4                        OK        Fan

System services and devices ignore list

Name             Status    Type
---------------  --------  ------
PSU1 Fan         Ignored   Device
psu.temperature  Ignored   Device
PSU2 Fan         Ignored   Device
asic             Ignored   Device
```

What about supporting other platforms - I have quickly checked on WEDGE 100-32X from Edge Core: 

```
admin@sonic:~$ show version

SONiC Software Version: SONiC.master.27175-dirty-20210804.165553
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: e13f5246b
Build date: Wed Aug  4 17:05:24 UTC 2021
Built by: AzDevOps@sonic-build-workers-000KD9

Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot
ASIC Count: 1
```

and got :

```
admin@sonic:~$ sudo show system-health detail
System health configuration file not found, exit...
admin@sonic:~$
```

**Comment by Staphylo** [comment]
The system-health daemon is platform independent but it relies on some vendor specific platform API to work and as well as a configuration file.
To get support on the `x86_64-accton_wedge100bf_32x-r0` you should try to get in contact with the platform owner to see if they can add the missing support.
You can look at the git history of the files under https://github.com/Azure/sonic-buildimage/tree/master/device/barefoot/x86_64-accton_wedge100bf_32x-r0 to see who that might be.

**Comment by gcupryn** [comment]
Thanks @Staphylo for the explanation, I have found needed contact.
