### ISSUE TITLE
ERR sniffer: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#6708]
**Description**

**Steps to reproduce the issue:**
https://dev.azure.com/mssonic/build/_build/results?buildId=3077&view=ms.vss-test-web.build-test-results-tab&runId=35866&resultId=100000&paneView=debug

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@qiluo-msft , can you talk a look, are we missing something?

**Comment by lguohan** [comment]
i found all issue appear in this pr. https://github.com/Azure/sonic-buildimage/pull/6679

so, i think it is still pyswsssdk conversion problem. can you take a look? the pr #6679 is still blocked.

**Comment by qiluo-msft** [comment]
ACK

**Comment by lguohan** [comment]
i grep the repro, i can only find sniffer in sonic-utilties, which is related to mellanox, i am not sure why it appears on kvm platform.
