### ISSUE TITLE
PortsOrch init error: SAI attr SAI_SWITCH_ATTR_NUMBER_OF_SYSTEM_PORTS not supported

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#6727]
**Description**

PR https://github.com/Azure/sonic-swss/pull/1431 made changes in PortsOrch for system ports init/addition. `getSystemPorts` call fails https://github.com/Azure/sonic-swss/blob/master/orchagent/portsorch.cpp#L401.

Errors seen in PortsOrch initialization: `ERR swss#orchagent: :- getSystemPorts: Failed to get number of system ports, rv:-2`
Sairedis recording reports `SAI_STATUS_NOT_SUPPORTED` for attr ID: `SAI_SWITCH_ATTR_NUMBER_OF_SYSTEM_PORTS`.

Scope or the impact of this error is not clear, and it does not seem to impact the rest of the operations in PortsOrch initialization.

**Steps to reproduce the issue:**
1. Reboot the device (warm/cold).
2. Check syslog.
3.

**Describe the results you received:**

Syslog:
```
Feb  8 21:19:57.092751 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:1000000000038 lanes:109 110
Feb  8 21:19:57.093836 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:1000000000039 lanes:111 112
Feb  8 21:19:57.094852 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:100000000003a lanes:113 114
Feb  8 21:19:57.095865 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:100000000003b lanes:115 116
Feb  8 21:19:57.096895 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:100000000003c lanes:117 118
Feb  8 21:19:57.098087 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:100000000003d lanes:119 120
Feb  8 21:19:57.099279 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:100000000003e lanes:121 122
Feb  8 21:19:57.100358 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:100000000003f lanes:123 124
Feb  8 21:19:57.101459 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:1000000000040 lanes:125 126
Feb  8 21:19:57.102460 str-s6100-acs-2 NOTICE swss#orchagent: :- PortsOrch: Get port with lanes pid:1000000000041 lanes:127 128
Feb  8 21:19:57.104515 str-s6100-acs-2 ERR swss#orchagent: :- getSystemPorts: Failed to get number of system ports, rv:-2
```
From sairedis recording:
```
2021-02-08.21:19:57.103599|g|SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000|SAI_SWITCH_ATTR_NUMBER_OF_SYSTEM_PORTS=2
2021-02-08.21:19:57.104310|G|SAI_STATUS_NOT_SUPPORTED|
```

**Describe the results you expected:**
Is this error expected?

**Additional information you deem important (e.g. issue happens only occasionally):**

This error was seen in TD3 (7050CX3) and TH (S6100) T0 devices.
    **Output of `show version`:**

```
SONiC Software Version: SONiC.HEAD.364-092f5378
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 092f5378
Build date: Mon Feb  8 02:02:06 UTC 2021
Built by: johnar@jenkins-worker-22

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
```
    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
make it as info level. i do not think it deserve error log. 202012 does not have this code.
