### ISSUE TITLE
"sfputil" command can't show the  information of 25G AOC properly

### ISSUE THREAD

**Issue by roooockwell** [Azure/sonic-buildimage#678]
Hi ,
    **I'm testing sonic on x86_64-ingrasys_s8900_54xc-r0.
    There is something wrong about the display of 25G AOC   using "sfputil" command. the display of 100G is ok.**
root@sonic:/home/admin# sfputil 
Ethernet0: SFP detected
	Connector : Unknown
	Encoding : Unknown
	Extended Identifier : Unknown
	Extended RateSelect Compliance : Unknown
	Identifier : Unknown
	Length Cable Assembly(m) : 255
	Length OM1(m) : 255
	Length OM2(m) : 255
	Length OM3(2m) : 255
	Length(km) : 255
	Nominal Bit Rate(100Mbs) : 255
	Specification compliance :
		10/40G Ethernet Compliance Code : 10GBase-LR
		Fibre Channel Speed : 100 Mbytes/Sec
		Fibre Channel link length/Transmitter Technology : Electrical inter-enclosure (EL)
		Fibre Channel transmission media : Miniature Coax (MI)
		Gigabit Ethernet Compliant codes : 1000BASE-CX
		SAS/SATA compliance codes : SAS 3.0G
		SONET Compliance codes : 40G OTN (OTU3B/OTU3C)
	**Vendor Date Code(YYYY-MM-DD Lot) : 20ÿÿ-ÿÿ-ÿÿ ÿÿ
	Vendor Name : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor OUI : ff-ff-ff
	Vendor PN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor Rev : ÿÿ
	Vendor SN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ**

Ethernet1: SFP detected
	Connector : Unknown
	Encoding : Unknown
	Extended Identifier : Unknown
	Extended RateSelect Compliance : Unknown
	Identifier : Unknown
	Length Cable Assembly(m) : 255
	Length OM1(m) : 255
	Length OM2(m) : 255
	Length OM3(2m) : 255
	Length(km) : 255
	Nominal Bit Rate(100Mbs) : 255
	Specification compliance :
		10/40G Ethernet Compliance Code : 10GBase-LR
		Fibre Channel Speed : 100 Mbytes/Sec
		Fibre Channel link length/Transmitter Technology : Electrical inter-enclosure (EL)
		Fibre Channel transmission media : Miniature Coax (MI)
		Gigabit Ethernet Compliant codes : 1000BASE-CX
		SAS/SATA compliance codes : SAS 3.0G
		SONET Compliance codes : 40G OTN (OTU3B/OTU3C)
	Vendor Date Code(YYYY-MM-DD Lot) : 20ÿÿ-ÿÿ-ÿÿ ÿÿ
	Vendor Name : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor OUI : ff-ff-ff
	Vendor PN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor Rev : ÿÿ
	Vendor SN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ

Ethernet2: SFP detected
	Connector : Unknown
	Encoding : Unknown
	Extended Identifier : Unknown
	Extended RateSelect Compliance : Unknown
	Identifier : Unknown
	Length Cable Assembly(m) : 255
	Length OM1(m) : 255
	Length OM2(m) : 255
	Length OM3(2m) : 255
	Length(km) : 255
	Nominal Bit Rate(100Mbs) : 255
	Specification compliance :
		10/40G Ethernet Compliance Code : 10GBase-LR
		Fibre Channel Speed : 100 Mbytes/Sec
		Fibre Channel link length/Transmitter Technology : Electrical inter-enclosure (EL)
		Fibre Channel transmission media : Miniature Coax (MI)
		Gigabit Ethernet Compliant codes : 1000BASE-CX
		SAS/SATA compliance codes : SAS 3.0G
		SONET Compliance codes : 40G OTN (OTU3B/OTU3C)
	**Vendor Date Code(YYYY-MM-DD Lot) : 20ÿÿ-ÿÿ-ÿÿ ÿÿ
	Vendor Name : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor OUI : ff-ff-ff
	Vendor PN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor Rev : ÿÿ
	Vendor SN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ**

Ethernet3: SFP detected
	Connector : Unknown
	Encoding : Unknown
	Extended Identifier : Unknown
	Extended RateSelect Compliance : Unknown
	Identifier : Unknown
	Length Cable Assembly(m) : 255
	Length OM1(m) : 255
	Length OM2(m) : 255
	Length OM3(2m) : 255
	Length(km) : 255
	Nominal Bit Rate(100Mbs) : 255
	Specification compliance :
		10/40G Ethernet Compliance Code : 10GBase-LR
		Fibre Channel Speed : 100 Mbytes/Sec
		Fibre Channel link length/Transmitter Technology : Electrical inter-enclosure (EL)
		Fibre Channel transmission media : Miniature Coax (MI)
		Gigabit Ethernet Compliant codes : 1000BASE-CX
		SAS/SATA compliance codes : SAS 3.0G
		SONET Compliance codes : 40G OTN (OTU3B/OTU3C)
	Vendor Date Code(YYYY-MM-DD Lot) : 20ÿÿ-ÿÿ-ÿÿ ÿÿ
	Vendor Name : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor OUI : ff-ff-ff
	Vendor PN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
	Vendor Rev : ÿÿ
	Vendor SN : ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ

Ethernet4: SFP detected
	Connector : Unknown or unspecified
	Encoding : Unspecified
	Extended Identifier : Unknown
	Extended RateSelect Compliance : QSFP+ Rate Select Version 1
	Identifier : Unknown or unspecified
	Specification compliance :
	Vendor Date Code(YYYY-MM-DD Lot) : 20-- 
	Vendor Name : 
	Vendor OUI : 00-00-00
	Vendor PN : 
	Vendor Rev : 
	Vendor SN : 

Ethernet5: SFP detected
	Connector : Unknown or unspecified
	Encoding : Unspecified
	Extended Identifier : Unknown
	Extended RateSelect Compliance : QSFP+ Rate Select Version 1
	Identifier : Unknown or unspecified
	Specification compliance :
	**Vendor Date Code(YYYY-MM-DD Lot) : 20-- 
	Vendor Name : 
	Vendor OUI : 00-00-00
	Vendor PN : 
	Vendor Rev : 
	Vendor SN :** 

Ethernet6: SFP detected
	Connector : Unknown or unspecified
	Encoding : Unspecified
	Extended Identifier : Unknown
	Extended RateSelect Compliance : QSFP+ Rate Select Version 1
	Identifier : Unknown or unspecified
	Specification compliance :
	Vendor Date Code(YYYY-MM-DD Lot) : 20-- 
	Vendor Name : 
	Vendor OUI : 00-00-00
	Vendor PN : 
	Vendor Rev : 
	Vendor SN : 

Ethernet7: SFP detected
	Connector : Unknown or unspecified
	Encoding : Unspecified
	Extended Identifier : Unknown
	Extended RateSelect Compliance : QSFP+ Rate Select Version 1
	Identifier : Unknown or unspecified
	Specification compliance :
	Vendor Date Code(YYYY-MM-DD Lot) : 20-- 
	Vendor Name : 
	Vendor OUI : 00-00-00
	Vendor PN : 
	Vendor Rev : 
	Vendor SN :

**Comment by stcheng** [comment]
could you hexdump the raw data of the eeprom file here?

**Comment by wadelnn** [comment]
This is cause by this issue [here](https://github.com/Azure/sonic-utilities/issues/10).
We hard-code to modify the /usr/lib/python2.7/dist-packages/sonic_sfp/sfputilbase.py on line 356 to remove by 4. And result seem fine to display 25G AOC as follows:
Ethernet0: SFP detected
        Connector : Unknown
        Encoding : Unknown
        Extended Identifier : Unknown
        Extended RateSelect Compliance : Unknown
        Identifier : Unknown
        Length Cable Assembly(m) : 255
        Length OM1(m) : 255
        Length OM2(m) : 255
        Length OM3(2m) : 255
        Length(km) : 255
        Nominal Bit Rate(100Mbs) : 255
        Specification compliance :
                10/40G Ethernet Compliance Code : 10GBase-LR
                Fibre Channel Speed : 100 Mbytes/Sec
                Fibre Channel link length/Transmitter Technology : Electrical inter-enclos
                Fibre Channel transmission media : Miniature Coax (MI)
                Gigabit Ethernet Compliant codes : 1000BASE-CX
                SAS/SATA compliance codes : SAS 3.0G
                SONET Compliance codes : 40G OTN (OTU3B/OTU3C)
        Vendor Date Code(YYYY-MM-DD Lot) : 20▒▒-▒▒-▒▒ ▒▒
        Vendor Name : ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
        Vendor OUI : ff-ff-ff
        Vendor PN : ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
        Vendor Rev : ▒▒
        Vendor SN : ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒

Ethernet1: SFP detected
        Connector : Unknown
        Encoding : Unknown
        Extended Identifier : Unknown
        Extended RateSelect Compliance : Unknown
        Identifier : Unknown
        Length Cable Assembly(m) : 255
        Length OM1(m) : 255
        Length OM2(m) : 255
        Length OM3(2m) : 255
        Length(km) : 255
        Nominal Bit Rate(100Mbs) : 255
        Specification compliance :
                10/40G Ethernet Compliance Code : 10GBase-LR
                Fibre Channel Speed : 100 Mbytes/Sec
                Fibre Channel link length/Transmitter Technology : Electrical inter-enclos
                Fibre Channel transmission media : Miniature Coax (MI)
                Gigabit Ethernet Compliant codes : 1000BASE-CX
                SAS/SATA compliance codes : SAS 3.0G
                SONET Compliance codes : 40G OTN (OTU3B/OTU3C)
        Vendor Date Code(YYYY-MM-DD Lot) : 20▒▒-▒▒-▒▒ ▒▒
        Vendor Name : ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
        Vendor OUI : ff-ff-ff
        Vendor PN : ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
        Vendor Rev : ▒▒
        Vendor SN : ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒

Ethernet2: SFP detected
        Connector : Unknown or unspecified
        Encoding : Unspecified
        Extended Identifier : Unknown
        Extended RateSelect Compliance : QSFP+ Rate Select Version 1
        Identifier : Unknown or unspecified
        Specification compliance :
        Vendor Date Code(YYYY-MM-DD Lot) : 20--
        Vendor Name :
        Vendor OUI : 00-00-00
        Vendor PN :
        Vendor Rev :
        Vendor SN :

Ethernet3: SFP detected
        Connector : Unknown or unspecified
        Encoding : Unspecified
        Extended Identifier : Unknown
        Extended RateSelect Compliance : QSFP+ Rate Select Version 1
        Identifier : Unknown or unspecified
        Specification compliance :
        Vendor Date Code(YYYY-MM-DD Lot) : 20--
        Vendor Name :
        Vendor OUI : 00-00-00
        Vendor PN :
        Vendor Rev :
        Vendor SN :

Ethernet4: SFP not detected

Ethernet5: SFP not detected

Ethernet6: SFP not detected

Ethernet7: SFP not detected

Ethernet8: SFP not detected

Ethernet9: SFP not detected

**Comment by stcheng** [comment]
thanks. then i think it is a easier issue to address. we will track the issue.

**Comment by lguohan** [comment]
it is probably more than that. it looks like the sff_8436_eeprom driver needs to be updated to support sfp.

**Comment by roooockwell** [comment]
what about now？do you fix this bug now?

**Comment by stcheng** [comment]
@lguohan https://github.com/Azure/sonic-linux-kernel/pull/20 related to this?

**Comment by gongjianLhr** [comment]
I tested it in 1.0.3, this problem still exists. Haven't you fixed it yet?

**Comment by liuqu** [comment]
@lguohan @stcheng  [Azure/sonic-linux-kernel#20 ](https://github.com/Azure/sonic-linux-kernel/pull/20) can fix this bug? Or need platform developer to fix it?

**Comment by liuqu** [comment]
@wadelnn  The SFP EEPROM information is still empty in platform ingrasys_s8900_64xc. Could you help to check the cause?

root@sonic:/home/admin# show platform summary 
Platform: x86_64-ingrasys_s8900_64xc-r0
HwSKU: INGRASYS-S8900-64XC
ASIC: broadcom

root@sonic:/home/admin# sfputil show eeprom -p Ethernet1
Ethernet1: SFP EEPROM detected
	Connector: Unknown or unspecified
	Encoding: Unspecified
	Extended Identifier: Unknown
	Extended RateSelect Compliance: QSFP+ Rate Select Version 1
	Identifier: Unknown or unspecified
	Specification compliance:
	Vendor Date Code(YYYY-MM-DD Lot): 20-- 
	Vendor Name: 
	Vendor OUI: 00-00-00
	Vendor PN: 
	Vendor Rev: 
	Vendor SN:

**Comment by Balaselvi** [comment]
Hello,

I faced the same issue, the reason was i have not specified the qsfp ports start and end correctly in
@property
    def qsfp_ports(self):
        return range(0, self.PORTS_IN_BLOCK + 1)
If we leave the above default range, then even the sfp ports are treated as qsfp ports and that is the reason for the above problem. If all ports are sfp then return 0 fromthe above qsfp_ports.

Reference the below bugfix:
https://github.com/Azure/sonic-buildimage/pull/1080

**Comment by Balaselvi** [comment]
Code snippet involved:
sfputil.py
@property
def qsfp_ports(self):
    return range(48, self.PORTS_IN_BLOCK + 1)
 
sfputilbase.py uses the same as below:
def get_eeprom_dict(self, port_num):
        """Returns dictionary of interface and dom data.
        format: {<port_num> : {'interface': {'version' : '1.0', 'data' : {...}},
                               'dom' : {'version' : '1.0', 'data' : {...}}}}
        """
 
        sfp_data = {}
 
        eeprom_ifraw = self.get_eeprom_raw(port_num)
        eeprom_domraw = self.get_eeprom_dom_raw(port_num)
 
        if eeprom_ifraw is None:
            return None
 
        if port_num in self.qsfp_ports:
            print "Port in QSFP %s" % str(port_num)
            sfpi_obj = sff8436InterfaceId(eeprom_ifraw)
            if sfpi_obj is not None:
                sfp_data['interface'] = sfpi_obj.get_data_pretty()
            # For Qsfp's the dom data is part of eeprom_if_raw
            # The first 128 bytes
 
            sfpd_obj = sff8436Dom(eeprom_ifraw)
            if sfpd_obj is not None:
                sfp_data['dom'] = sfpd_obj.get_data_pretty()
            return sfp_data
        print "Port not in QSFP %s" % str(port_num)
        sfpi_obj = sff8472InterfaceId(eeprom_ifraw)
        if sfpi_obj is not None:
            sfp_data['interface'] = sfpi_obj.get_data_pretty()
            cal_type = sfpi_obj.get_calibration_type()
 
        if eeprom_domraw is not None:
            sfpd_obj = sff8472Dom(eeprom_domraw, cal_type)
            if sfpd_obj is not None:
                sfp_data['dom'] = sfpd_obj.get_data_pretty()
 
        return sfp_data

**Comment by wadelnn** [comment]
@liuqu Sorry for response so late. We fixed this issue on PR #1145 . Please assist to verify this issue.

**Comment by liuqu** [comment]
@wadelnn All the SFP EEPROM information has been filled now. Thanks! :)

**Comment by jleveque** [comment]
@liuqu: Good to hear!

Can this issue be closed now?

**Comment by jleveque** [comment]
@roooockwell: Is this issue resolved for you? Can it be closed?
