### ISSUE TITLE
[sflow] corrupted interfaces counters are exported to sflow collector

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6795]
#### Description

Interface counters which are exported by sflow to the collector have corrupted structure

#### Steps to reproduce the issue:
1. Enable sflow feature
```
config feature state sflow enabled
```
2. Configure any sflow collector. For example reachable via management interface
```
config sflow collector add C1 10.209.21.159
```
3. Enable sflow
```
config sflow enable
```
4. Capture and analyse packets on the collector 

#### Describe the results you received:

sflow counters structure has invalid sample format id. Check pcap file attached

#### Describe the results you expected:

Generic interface counters (0x01) or/and ethernet interface counters (0x02)
Check valid pcap file attached as an example

#### Output of `show version`:
```
SONiC Software Version: SONiC.SONIC.202012.10-d26a4af_Internal
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: d26a4aff
Build date: Thu Feb  4 15:28:36 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02

Platform: x86_64-mlnx_msn3700-r0
HwSKU: ACS-MSN3700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1852X03965
Uptime: 19:22:39 up  1:13,  1 user,  load average: 2.51, 1.62, 1.26
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[sonic_dump_qa-anconda-test10_20210216_183037.tar.gz](https://github.com/Azure/sonic-buildimage/files/5990354/sonic_dump_qa-anconda-test10_20210216_183037.tar.gz)
[sflow-counters-01.zip](https://github.com/Azure/sonic-buildimage/files/5990362/sflow-counters-01.zip)
[wireshark screenshot](https://user-images.githubusercontent.com/74326396/108098513-24cbcb00-708c-11eb-932f-b1fe1d959950.png)
[sflow-valid-example.zip](https://github.com/Azure/sonic-buildimage/files/5990364/sflow-valid-example.zip)

**Comment by prsunny** [comment]
Is this generic (for all interfaces/platforms that you tested)? @padmanarayana , @dgsudharsan , could you please take a look and suggest next steps?

**Comment by padmanarayana** [comment]
The counters are retrieved from the CountersDB and the samples get constructed entirely from within hsflowd (https://github.com/sflow/host-sflow/blob/master/src/Linux/mod_sonic.c#L1120).

@sflow : can you please help in determining if the "Unknown sample format" is just a Wireshark dissector issue or a real corruption ?

**Comment by sflow** [comment]
It looks like the Wireshark dissector does not decode some of the standard sFlow structures.  It's hard to tell if it's skipping over them cleanly or not (I suspect not, in which case there is a Wireshark bug).  I ran the .pcap through sflowtool to see which structures are there.  It is the standard set of host structures that report MAC addresses, CPU, memory, disk, TCP/IP counters etc.   So there is no SONiC problem.

Here is the sflowtool output for the first datagram in the capture.  If you compare with the Wireshark screen capture you'll see that Wireshark did not know what do with the first counter structure "0:2001" -- or any of the ones that came after it.

startDatagram =================================
datagramSourceIP -
datagramSize 772
unixSecondsUTC 1613529082
localtime 2021-02-17T02:31:22+0000
pcapTimestamp 2021-02-16T16:25:35+0000
datagramVersion 5
agentSubId 100000
agent 10.209.21.164
packetSequenceNo 1
sysUpTime 9649
samplesInPacket 1
startSample ----------------------
sampleType_tag 0:2
sampleType COUNTERSSAMPLE
sampleSequenceNo 1
sourceId 2:1
counterBlock_tag 0:2001
adaptor_0_ifIndex 2
adaptor_0_MACs 1
adaptor_0_MAC_0 b8599f0b42ac
adaptor_1_ifIndex 4
adaptor_1_MACs 1
adaptor_1_MAC_0 b8599fa63800
adaptor_2_ifIndex 3
adaptor_2_MACs 1
adaptor_2_MAC_0 02422185cd29
adaptor_3_ifIndex 38
adaptor_3_MACs 1
adaptor_3_MAC_0 b8599fa63800
counterBlock_tag 0:2010
udpInDatagrams 3873
udpNoPorts 21
udpInErrors 0
udpOutDatagrams 3827
udpRcvbufErrors 0
udpSndbufErrors 0
udpInCsumErrors 0
counterBlock_tag 0:2009
tcpRtoAlgorithm 1
tcpRtoMin 200
tcpRtoMax 120000
tcpMaxConn 4294967295
tcpActiveOpens 751
tcpPassiveOpens 687
tcpAttemptFails 71
tcpEstabResets 6
tcpCurrEstab 90
tcpInSegs 97499
tcpOutSegs 97218
tcpRetransSegs 0
tcpInErrs 0
tcpOutRsts 88
tcpInCsumErrors 0
counterBlock_tag 0:2008
icmpInMsgs 19
icmpInErrors 18
icmpInDestUnreachs 0
icmpInTimeExcds 0
icmpInParamProbs 0
icmpInSrcQuenchs 0
icmpInRedirects 0
icmpInEchos 0
icmpInEchoReps 19
icmpInTimestamps 0
icmpInAddrMasks 0
icmpInAddrMaskReps 0
icmpOutMsgs 0
icmpOutErrors 0
icmpOutDestUnreachs 22
icmpOutTimeExcds 0
icmpOutParamProbs 21
icmpOutSrcQuenchs 0
icmpOutRedirects 0
icmpOutEchos 0
icmpOutEchoReps 0
icmpOutTimestamps 0
icmpOutTimestampReps 1
icmpOutAddrMasks 0
icmpOutAddrMaskReps 0
counterBlock_tag 0:2007
ipForwarding 1
ipDefaultTTL 64
ipInReceives 101569
ipInHdrErrors 0
ipInAddrErrors 16
ipForwDatagrams 0
ipInUnknownProtos 0
ipInDiscards 0
ipInDelivers 101553
ipOutRequests 101057
ipOutDiscards 0
ipOutNoRoutes 1
ipReasmTimeout 0
ipReasmReqds 0
ipReasmOKs 0
ipReasmFails 0
ipFragOKs 0
ipFragFails 0
ipFragCreates 0
counterBlock_tag 0:2005
disk_total 29275430912
disk_free 25614200832
disk_partition_max_used 12.50
disk_reads 195861
disk_bytes_read 1070196736
disk_read_time 30917
disk_writes 6212
disk_bytes_written 66457600
disk_write_time 3145
counterBlock_tag 0:2004
mem_total 8256372736
mem_free 3688407040
mem_shared 0
mem_buffers 216920064
mem_cached 1138479104
swap_total 0
swap_free 0
page_in 604458
page_out 34224
swap_in 0
swap_out 0
counterBlock_tag 0:2003
cpu_load_one 1.990
cpu_load_five 1.050
cpu_load_fifteen 0.590
cpu_proc_run 0
cpu_proc_total 595
cpu_num 8
cpu_speed 1002
cpu_uptime 1001
cpu_user 281210
cpu_nice 0
cpu_system 190060
cpu_idle 7483110
cpu_wio 940
cpuintr 0
cpu_sintr 4130
cpuinterrupts 2685666
cpu_contexts 18028366
cpu_steal 0
cpu_guest 0
cpu_guest_nice 0
counterBlock_tag 0:2006
nio_bytes_in 0
nio_pkts_in 0
nio_errs_in 0
nio_drops_in 0
nio_bytes_out 0
nio_pkts_out 0
nio_errs_out 0
nio_drops_out 0
counterBlock_tag 0:2000
hostname qa-anconda-test10
UUID 46da7d82-76aa-11e9-8000-b8599fa63800
machine_type 3
os_name 2
os_release 4.19.0-9-2-amd64
endSample   ----------------------
endDatagram   =================================

**Comment by anshuv-mfst** [comment]
Dell team to provide input on the issue, thanks.

**Comment by padmanarayana** [comment]
Thanks @sflow.
@Hedgehog-Guru : can you run the tests with sflowtool and confirm this is just a wireshark issue ?

**Comment by Hedgehog-Guru** [comment]
@padmanarayana , with the **sflowtool** it looks OK. You are right, it is a Wireshark issue.
