### ISSUE TITLE
Fresh install on Dell S5248F-ON, no working SFP ports, pmon/pcied/xcvrd/psud dead 

### ISSUE THREAD

**Issue by aledwmorris** [Azure/sonic-buildimage#6820]
#### Description

Install of SONiC on Dell S5248F-ON switch.  From first boot, no SFP ports are working - all lights are solid on.  Seems that pmon processes pcied, xcvrd, psud have died.

#### Steps to reproduce the issue:
1. install
2. observe lights (all on)
3. "show interface transceiver presence" (shows none present)

#### Describe the results you received:

no working SFP slots

#### Describe the results you expected:

working SFP slots

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.580-c54a03fa
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: c54a03fa
Build date: Wed Feb 10 08:45:33 UTC 2021
Built by: johnar@jenkins-worker-8

Platform: x86_64-dellemc_s5248f_c3538-r0
HwSKU: DellEMC-S5248f-P-25G
ASIC: broadcom
ASIC Count: 1
Serial Number: CN0NW42MCES0094O0011
Uptime: 02:25:32 up 3 min,  1 user,  load average: 0.51, 0.40, 0.19

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-syncd-brcm             latest                81e43ececd13        679MB
docker-syncd-brcm             master.580-c54a03fa   81e43ececd13        679MB
docker-snmp                   latest                c0c83d48418e        438MB
docker-snmp                   master.580-c54a03fa   c0c83d48418e        438MB
docker-teamd                  latest                df3bdf2127b8        407MB
docker-teamd                  master.580-c54a03fa   df3bdf2127b8        407MB
docker-router-advertiser      latest                d68c61811aac        397MB
docker-router-advertiser      master.580-c54a03fa   d68c61811aac        397MB
docker-platform-monitor       latest                a2f2d0a84c9e        604MB
docker-platform-monitor       master.580-c54a03fa   a2f2d0a84c9e        604MB
docker-macsec                 latest                3aca767566a1        411MB
docker-macsec                 master.580-c54a03fa   3aca767566a1        411MB
docker-lldp                   latest                231a146d7695        437MB
docker-lldp                   master.580-c54a03fa   231a146d7695        437MB
docker-dhcp-relay             latest                81558c825c9b        404MB
docker-dhcp-relay             master.580-c54a03fa   81558c825c9b        404MB
docker-database               latest                2efc3c92e605        397MB
docker-database               master.580-c54a03fa   2efc3c92e605        397MB
docker-sonic-mgmt-framework   latest                fcd6ef90793a        615MB
docker-sonic-mgmt-framework   master.580-c54a03fa   fcd6ef90793a        615MB
docker-orchagent              latest                deef2e8beddf        426MB
docker-orchagent              master.580-c54a03fa   deef2e8beddf        426MB
docker-nat                    latest                469870862671        410MB
docker-nat                    master.580-c54a03fa   469870862671        410MB
docker-sonic-telemetry        latest                aa3f1e9b4c5b        471MB
docker-sonic-telemetry        master.580-c54a03fa   aa3f1e9b4c5b        471MB
docker-fpm-frr                latest                b63f1a6b83ac        426MB
docker-fpm-frr                master.580-c54a03fa   b63f1a6b83ac        426MB
docker-sflow                  latest                fe6cabd53086        408MB
docker-sflow                  master.580-c54a03fa   fe6cabd53086        408MB
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[sonic_dump_sonic_20210219_022609.tar.gz](https://github.com/Azure/sonic-buildimage/files/6005109/sonic_dump_sonic_20210219_022609.tar.gz)

**Comment by jeff-yin** [comment]
Please assign to @vpsubramaniam

**Comment by anshuv-mfst** [comment]
@vpsubramaniam - could you please look into the issue, thanks.

**Comment by jeff-yin** [comment]
Short term fix is to address the crashes, but after that we need to migrate the platform to API 2.0.

**Comment by vpsubramaniam** [comment]
Raised below merge requests to address this issue,
https://github.com/Azure/sonic-buildimage/pull/7022
https://github.com/Azure/sonic-platform-common/pull/177

**Comment by aledwmorris** [comment]
I still don't have a working system.  Downloaded latest build:

> admin@sonic:~$ show version
> 
> SONiC Software Version: SONiC.master.646-990b1127
> Distribution: Debian 10.9
> Kernel: 4.19.0-12-2-amd64
> Build commit: 990b1127
> Build date: Sat Apr 24 09:20:49 UTC 2021
> Built by: johnar@jenkins-worker-2
> 
> Platform: x86_64-dellemc_s5248f_c3538-r0
> HwSKU: DellEMC-S5248f-P-25G
> ASIC: broadcom
> ASIC Count: 1
> Traceback (most recent call last):
>   File "/usr/local/bin/decode-syseeprom", line 18, in <module>
>     import sonic_platform
> ModuleNotFoundError: No module named 'sonic_platform'
> Serial Number: 
> Uptime: 12:03:12 up  1:11,  1 user,  load average: 2.15, 1.62, 1.58


Problem seems to be still in the pmon container:

> admin@sonic:~$ docker container logs pmon
> ...
> 2021-04-28 10:54:38,446 INFO stopped: dependent-startup (terminated by SIGTERM)
> sonic-platform package not installed, attempting to install...
> Error: Unable to locate /usr/share/sonic/platform/sonic_platform-1.0-py2-none-any.whl
> sonic-platform package not installed, attempting to install...
> Error: Unable to locate /usr/share/sonic/platform/sonic_platform-1.0-py3-none-any.whl
> /usr/local/lib/python3.7/dist-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
>   'Supervisord is running as root and it is searching '
> 2021-04-28 10:55:11,677 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
> 2021-04-28 10:55:11,677 INFO Set uid to user 0 succeeded
> 2021-04-28 10:55:11,690 INFO RPC interface 'supervisor' initialized
> 2021-04-28 10:55:11,690 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2021-04-28 10:55:11,691 INFO supervisord started with pid 1
> 2021-04-28 10:55:12,695 INFO spawned: 'dependent-startup' with pid 24
> 2021-04-28 10:55:12,697 INFO spawned: 'supervisor-proc-exit-listener' with pid 25
> 2021-04-28 10:55:14,026 INFO success: dependent-startup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2021-04-28 10:55:14,027 INFO success: supervisor-proc-exit-listener entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2021-04-28 10:55:14,035 INFO spawned: 'rsyslogd' with pid 28
> 2021-04-28 10:55:15,097 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2021-04-28 10:55:16,115 INFO spawned: 'xcvrd' with pid 32
> 2021-04-28 10:55:16,115 INFO success: xcvrd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2021-04-28 10:55:16,122 INFO spawned: 'psud' with pid 33
> 2021-04-28 10:55:16,123 INFO success: psud entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2021-04-28 10:55:16,130 INFO spawned: 'syseepromd' with pid 34
> 2021-04-28 10:55:16,137 INFO spawned: 'pcied' with pid 35
> 2021-04-28 10:55:16,158 INFO exited: psud (exit status 1; not expected)
> 2021-04-28 10:55:16,170 WARN received SIGTERM indicating exit request
> 2021-04-28 10:55:16,171 INFO waiting for dependent-startup, supervisor-proc-exit-listener, rsyslogd, xcvrd, syseepromd, pcied to die
> 2021-04-28 10:55:16,173 INFO stopped: pcied (terminated by SIGTERM)
> 2021-04-28 10:55:16,174 INFO stopped: syseepromd (terminated by SIGTERM)
> 2021-04-28 10:55:16,177 INFO stopped: xcvrd (terminated by SIGTERM)
> 2021-04-28 10:55:16,197 INFO stopped: rsyslogd (exit status 0)
> 2021-04-28 10:55:16,199 INFO stopped: supervisor-proc-exit-listener (terminated by SIGTERM)
> 2021-04-28 10:55:16,202 INFO stopped: dependent-startup (terminated by SIGTERM)
> sonic-platform package not installed, attempting to install...
> Error: Unable to locate /usr/share/sonic/platform/sonic_platform-1.0-py2-none-any.whl
> sonic-platform package not installed, attempting to install...
> Error: Unable to locate /usr/share/sonic/platform/sonic_platform-1.0-py3-none-any.whl
> /usr/local/lib/python3.7/dist-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
>   'Supervisord is running as root and it is searching '
> 2021-04-28 11:19:15,684 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
> ...

(this is looped over and over and the container is dead)

I'm grateful for any help you can extend.

**Comment by aledwmorris** [comment]
Hi @vpsubramaniam @jeff-yin can you tell me where to look for psud log messages so I can try to figure out why it is dying?  Thanks.

**Comment by vpsubramaniam** [comment]
@aledwmorris, the current issue (psud exited) is completely different from the one reported earlier. You can check the 'psud' logs in syslog files, please try the below command,
sudo zgrep -ai "psud" /var/log/syslog*
If possible share this output as well.

**Comment by aledwmorris** [comment]
Thanks @vpsubramaniam here's the log:

(repeated over and over)

/var/log/syslog.2.gz:Apr 28 10:55:16.123766 sonic INFO pmon#supervisord 2021-04-28 10:55:16,122 INFO spawned: 'psud' with pid 33
/var/log/syslog.2.gz:Apr 28 10:55:16.124047 sonic INFO pmon#supervisord 2021-04-28 10:55:16,123 INFO success: psud entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
/var/log/syslog.2.gz:Apr 28 10:55:16.155619 sonic INFO pmon#/supervisord: psud Traceback (most recent call last):
/var/log/syslog.2.gz:Apr 28 10:55:16.155690 sonic INFO pmon#/supervisord: psud   File "/usr/local/bin/psud", line 17, in <module>
/var/log/syslog.2.gz:Apr 28 10:55:16.155724 sonic INFO pmon#/supervisord: psud     from sonic_platform.psu import Psu
/var/log/syslog.2.gz:Apr 28 10:55:16.155757 sonic INFO pmon#/supervisord: psud ImportError: No module named sonic_platform.psu
/var/log/syslog.2.gz:Apr 28 10:55:16.159231 sonic INFO pmon#supervisord 2021-04-28 10:55:16,158 INFO exited: psud (exit status 1; not expected)
/var/log/syslog.2.gz:Apr 28 10:55:16.170507 sonic INFO pmon#/supervisor-proc-exit-listener: Process 'psud' exited unexpectedly. Terminating supervisor 'pmon'

**Comment by aledwmorris** [comment]
I've opened a new issue https://github.com/Azure/sonic-buildimage/issues/7644
