### ISSUE TITLE
Load balancing fails when running test_fib on latest brcm-cache image

### ISSUE THREAD

**Issue by nazeerhussainf** [Azure/sonic-buildimage#6875]
#### Description
Script test_fib fails due to load balancing not happening properly on the latest brcm-cache image(SONiC.HEAD.405-2e42ecb5).
Attached the test logs, fib logs from PTF docker and show tech files.

There was an old case where the same issue was  #reported(https://github.com/Azure/sonic-buildimage/issues/5681) and it was fixed in the latest BRCM SAI version. But, the issue still occurs even in the latest BRCM SAI.
The following BRCM SAI is running on the brcm-cache image(SONiC.HEAD.405-2e42ecb5).
bcmsai version
BRCM SAI ver: [4.3.0.13], OCP SAI ver: [1.7.1], SDK ver: [sdk-6.5.21]

#### Steps to reproduce the issue:
1. Run the test_fib image on the latest brcm-cache image.
2.
3.

#### Describe the results you received:

E                   "fib_test.FibTest ... FAIL", 
E                   "", 
E                   "======================================================================", 
E                   "FAIL: fib_test.FibTest", 
E                   "----------------------------------------------------------------------", 
E                   "Traceback (most recent call last):", 
E                   "  File \"ptftests/fib_test.py\", line 360, in runTest", 
E                   "    self.check_ip_ranges(ipv4=False)", 
E                   "  File \"ptftests/fib_test.py\", line 160, in check_ip_ranges", 
E                   "    self.check_ip_range(ip_range, next_hop, ipv4)", 
E                   "  File \"ptftests/fib_test.py\", line 175, in check_ip_range", 
E                   "    self.check_ip_route(src_port, ip_range.get_first_ip(), exp_port_list, ipv4)", 
E                   "  File \"ptftests/fib_test.py\", line 199, in check_ip_route", 
E                   "    res = self.check_ipv6_route(src_port, dst_ip_addr, dst_port_list)", 
E                   "  File \"ptftests/fib_test.py\", line 303, in check_ipv6_route", 
E                   "    return verify_packet_any_port(self, masked_exp_pkt, dst_port_list)", 
E                   "  File \"/usr/lib/python2.7/dist-packages/ptf/testutils.py\", line 2533, in verify_packet_any_port", 
E                   "    % (result.port, device_number, ports, result.format()))", 
E                   "AssertionError: Received expected packet on port 41 for device 0, but it should have arrived on one of these ports: [38, 39].", 

#### Output of `show version`:

```
root@sonic-z9332-10429:~# show version 

SONiC Software Version: SONiC.HEAD.405-2e42ecb5
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 2e42ecb5
Build date: Thu Feb 18 08:16:54 UTC 2021
Built by: johnar@jenkins-worker-22

Platform: x86_64-dellemc_z9332f_d1508-r0
HwSKU: DellEMC-Z9332f-M-O16C64
ASIC: broadcom
ASIC Count: 1
Serial Number: TH04CN21CET009BR0023
Uptime: 07:25:06 up 10 min,  2 users,  load average: 2.88, 1.67, 0.88

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-syncd-brcm             HEAD.405-2e42ecb5   7eac82154ced        679MB
docker-syncd-brcm             latest              7eac82154ced        679MB
docker-sonic-telemetry        HEAD.405-2e42ecb5   0d019ec8ff40        472MB
docker-sonic-telemetry        latest              0d019ec8ff40        472MB
docker-snmp                   HEAD.405-2e42ecb5   6c8af6de4fb7        438MB
docker-snmp                   latest              6c8af6de4fb7        438MB
docker-teamd                  HEAD.405-2e42ecb5   6ff5a4e32510        408MB
docker-teamd                  latest              6ff5a4e32510        408MB
docker-router-advertiser      HEAD.405-2e42ecb5   381a5b537ac9        397MB
docker-router-advertiser      latest              381a5b537ac9        397MB
docker-platform-monitor       HEAD.405-2e42ecb5   802d843d1bc5        605MB
docker-platform-monitor       latest              802d843d1bc5        605MB
docker-macsec                 HEAD.405-2e42ecb5   c10c9718ed5d        411MB
docker-macsec                 latest              c10c9718ed5d        411MB
docker-lldp                   HEAD.405-2e42ecb5   afb12be13f3a        437MB
docker-lldp                   latest              afb12be13f3a        437MB
docker-dhcp-relay             HEAD.405-2e42ecb5   ce31fa38e730        404MB
docker-dhcp-relay             latest              ce31fa38e730        404MB
docker-database               HEAD.405-2e42ecb5   cbcb4a849326        397MB
docker-database               latest              cbcb4a849326        397MB
docker-sonic-mgmt-framework   HEAD.405-2e42ecb5   2bbfead535d5        615MB
docker-sonic-mgmt-framework   latest              2bbfead535d5        615MB
docker-orchagent              HEAD.405-2e42ecb5   bbf100e02ef0        426MB
docker-orchagent              latest              bbf100e02ef0        426MB
docker-nat                    HEAD.405-2e42ecb5   ef6a526028e5        411MB
docker-nat                    latest              ef6a526028e5        411MB
docker-sflow                  HEAD.405-2e42ecb5   dc972d9c13ec        409MB
docker-sflow                  latest              dc972d9c13ec        409MB
docker-fpm-frr                HEAD.405-2e42ecb5   a753af2f7787        426MB
docker-fpm-frr                latest              a753af2f7787        426MB

root@sonic-z9332-10429:~#
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[fib_test.FibTest.ipv4.True.ipv6.True.2021-02-19-06_27_21.log](https://github.com/Azure/sonic-buildimage/files/6034132/fib_test.FibTest.ipv4.True.ipv6.True.2021-02-19-06_27_21.log)
[sonic_dump_sonic-z9332-10429_20210224_055051.tar.gz](https://github.com/Azure/sonic-buildimage/files/6034133/sonic_dump_sonic-z9332-10429_20210224_055051.tar.gz)
[test_fib_logs.txt](https://github.com/Azure/sonic-buildimage/files/6034134/test_fib_logs.txt)

**Comment by anshuv-mfst** [comment]
Issue seen in TH3.

**Comment by chitra-raghavan** [comment]
@gechiang , CSP#CS00012047260

**Comment by gechiang** [comment]
@chitra-raghavan 
Do you still see this issue with this test case using the latest SONIC image on your TH3 device?  There were multiple issues with the fib tests in early days but the SAI issue was fixed and then there were test case issues which also were fixed.
It would be very helpful if you can give the latest a try and update if we need to pursuit this issue ay more...
Thanks!

**Comment by chitra-raghavan** [comment]
Did not hit this issue in latest sai 4.3.3.5  in 202012 branch and testcase passed. 
root@sonic-10429:/#
root@sonic-10429:/#
root@sonic-10429:/# dpkg -l | grep sai
ii  libsaibcm                  4.3.3.5                     amd64        Switch Abstraction Interface sdk based on Broadcom SAI
ii  libsaimetadata             1.0.0                       amd64        This package contains SAI-Metadata implementation for SONiC project.
ii  libsairedis                1.0.0                       amd64        This package contains SAI-Redis implementation for SONiC project.
 
root@sonic-10429:~#
root@sonic-10429:~# show ver
SONiC Software Version: SONiC.202012.85-e6bbb3c3
Distribution: Debian 10.9
Kernel: 4.19.0-12-2-amd64
Build commit: e6bbb3c3
Build date: Fri Apr 23 06:07:36 UTC 2021
Built by: johnar@jenkins-worker-1
Platform: x86_64-dellemc_z9332f_d1508-r0
HwSKU: DellEMC-Z9332f-M-O16C64
ASIC: broadcom
ASIC Count: 1
Serial Number: TH04CN21CET009BR0023
Uptime: 11:12:47 up 1 day, 43 min,  1 user,  load average: 1.14, 2.28, 2.58

**Comment by gechiang** [comment]
@chitra-raghavan Thanks for the update!  looks like the initial problems are all addressed now.
If you agree, please go ahead and close this case.
Thanks!
