### ISSUE TITLE
Trunk LAG interface is listed as routed port in "show interfaces status" output.

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6928]
#### Description
A trunk LAG port is listed as router port in show interfaces status output

#### Steps to reproduce the issue:
1. add random vlans
2. create a portchannel
3. add ports to portchannel
4. assign vlans to portchannel
5. issue show interface status

#### Describe the results you received:
`
#show int status | grep -iE "(Ethernet0|Ethernet8|portcha)"

      Ethernet0          0,1,2,3       1G   9100    N/A     etp1  PortChannel0001      up       up   QSFP+ or later         N/A
      Ethernet8        8,9,10,11      1G   9100    N/A     etp3  PortChannel0001      up       up  QSFP28 or later         N/A
      PortChannel0001   N/A           2G   9100    N/A      N/A           routed    down       up              N/A         N/A
`

#### Describe the results you expected:
A trunk LAG port should be listed as **trunk** port in show interfaces status' output

#### Output of `show version`:
```
SONiC Software Version: SONiC.SONIC.202012.25-7c00106_Internal
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 7c001068
Build date: Tue Feb 23 17:47:44 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02

Platform: x86_64-mlnx_msn3800-r0
HwSKU: ACS-MSN3800
```

#### Additional information you deem important (e.g. issue happens only occasionally):
[sonic_dump_r-qa-sw-eth-2322_20210301_124956.tar.gz](https://github.com/Azure/sonic-buildimage/files/6061704/sonic_dump_r-qa-sw-eth-2322_20210301_124956.tar.gz)

**Comment by anshuv-mfst** [comment]
Known limitation, needs output enhancement. 
CC: @qiluo-msft

**Comment by qiluo-msft** [comment]
@prsunny Could you check on this platform?

**Comment by prsunny** [comment]
@qiluo-msft, this is a known issue in the CLI output and requested help in the community for a fix.

**Comment by maksymbelei95** [comment]
@Hedgehog-Guru, @prsunny, here is the fix for the issue: https://github.com/Azure/sonic-utilities/pull/1478. Could you check it?
