### ISSUE TITLE
Error message displayed on deleting vlan member "Failed to get port by bridge port ID"

### ISSUE THREAD

**Issue by allas-nvidia** [Azure/sonic-buildimage#6936]
#### Description:
When we remove vlan member from vlan we can see error in log:
> ERR swss#orchagent: :- update: Failed to get port by bridge port ID ...

It seems there is a race which can cause the scenario, when we receive notifications about FDB FLUSH on port which was already removed.

removeBridgePort (portsorch.cpp) called as a result of "remove vlan member" command, will call flushFDBEntries and at the end of this function ( removeBridgePort ) will set port.m_bridge_port_id = SAI_NULL_OBJECT_ID;
As a result of flushFDBEntries sai will notify FdbOrch  with attr oid which will be passed to the function  FdbOrch::update( fdborch.cpp) as bridge_port_id.
However, the function  getPortByBridgePortId will return false - as m_bridge_port_id was set to SAI_NULL_OBJECT_ID at the end of the function removeBridgePort and the error "Failed to get port by bridge port ID" will appear in log.

#### Steps to reproduce the issue:
1. sudo config vlan add 3
2. sudo config vlan member add 3 Ethernet8
3. sudo config vlan member del 3 Ethernet8

#### Describe the results you received:
 Error in log:  "Failed to get port by bridge port ID"

#### Describe the results you expected:
No error in log
#### Output of `show version`:

```
(paste your output here)
```

**Comment by prsunny** [comment]
@madhanmellanox , can you please take a look?

**Comment by madhanmellanox** [comment]
@allas-nvidia in bool PortsOrch::removeBridgePort(Port &port), we call 
    //Flush the FDB entires corresponding to the port
    gFdbOrch->flushFDBEntries(port.m_bridge_port_id, SAI_NULL_OBJECT_ID);

we don't m_bridge_port_id to SAI_NULL_OBJECT_ID, we set vlan_id to SAI_NULL_OBJECT_ID.

**Comment by prsunny** [comment]
In this flow, flushFDBEntries is called from two places:
1. removeVlanMember
2. removeBridgePort

So I'm assuming flush event is generated in both cases and for the first one, `FdbOrch::update` correctly process the event but for the second flush event, it throws the` Failed to get port by bridge port` error. Is this correct understanding?

When you repro the issue, can you please confirm if the STATEDB entry is cleaned?

`redis-cli -n 6 keys *FDB*`

**Comment by allas-nvidia** [comment]
Yes, STATEDB entry is cleaned

**Comment by liat-grozovik** [comment]
fix was integrated to both master and 202012. issue considered to be closed
