### ISSUE TITLE
Fast-reboot fails in latest Master

### ISSUE THREAD

**Issue by rkdevi27** [Azure/sonic-buildimage#6965]
#### Description
The "fast-reboot" command in latest master image fails in Dell S6100 device.
root@sonic:/home/admin# fast-reboot
Failed to run fast-reboot-dump.py. Exit code: 2

#### Steps to reproduce the issue:
1. Load the latest Master image
2. Wait till the dockers are up and running
3. Execute "fast-reboot" command

#### Describe the results you received:
The "fast-reboot" command fails with message "Failed to run fast-reboot-dump.py. Exit code: 2"

#### Describe the results you expected:
The "fast-reboot command should succeed and the device should come up fine after fast-reboot.

#### Output of `show version`:
root@sonic:/home/admin# show version

SONiC Software Version: SONiC.master.600-880a743c
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 880a743c
Build date: Wed Mar  3 10:44:19 UTC 2021
Built by: johnar@worker-s7bcec0

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
ASIC Count: 1
Serial Number: CN0GXF8P779316870078
Uptime: 20:54:47 up 7 min,  1 user,  load average: 4.86, 3.01, 1.38

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-syncd-brcm             latest                62fb700d116b        680MB
docker-syncd-brcm             master.600-880a743c   62fb700d116b        680MB
docker-snmp                   latest                1feb3a04ee10        438MB
docker-snmp                   master.600-880a743c   1feb3a04ee10        438MB
docker-teamd                  latest                e54fee32563e        408MB
docker-teamd                  master.600-880a743c   e54fee32563e        408MB
docker-nat                    latest                4ee9b0239c86        411MB
docker-nat                    master.600-880a743c   4ee9b0239c86        411MB
docker-router-advertiser      latest                280afe9426ec        398MB
docker-router-advertiser      master.600-880a743c   280afe9426ec        398MB
docker-platform-monitor       latest                153c764d48b5        606MB
docker-platform-monitor       master.600-880a743c   153c764d48b5        606MB
docker-dhcp-relay             latest                92aec391f448        405MB
docker-dhcp-relay             master.600-880a743c   92aec391f448        405MB
docker-database               latest                be77f9f69f9a        398MB
docker-database               master.600-880a743c   be77f9f69f9a        398MB
docker-lldp                   latest                c1006353728a        438MB
docker-lldp                   master.600-880a743c   c1006353728a        438MB
docker-orchagent              latest                63e94c802e34        427MB
docker-orchagent              master.600-880a743c   63e94c802e34        427MB
docker-sonic-telemetry        latest                a8753229391b        487MB
docker-sonic-telemetry        master.600-880a743c   a8753229391b        487MB
docker-macsec                 latest                62f21294a8a0        411MB
docker-macsec                 master.600-880a743c   62f21294a8a0        411MB
docker-sonic-mgmt-framework   latest                9a2841ebdb16        616MB
docker-sonic-mgmt-framework   master.600-880a743c   9a2841ebdb16        616MB
docker-fpm-frr                latest                f2a60abf3139        426MB
docker-fpm-frr                master.600-880a743c   f2a60abf3139        426MB
docker-sflow                  latest                0891b6c3ee53        409MB
docker-sflow                  master.600-880a743c   0891b6c3ee53        409MB

#### Additional information you deem important (e.g. issue happens only occasionally):
The journalctl and syslog messages related to the failure:

root@sonic:/home/admin# fast-reboot -vvv
Thu 04 Mar 2021 08:50:31 PM UTC Saving counters folder before warmboot...
Failed to run fast-reboot-dump.py. Exit code: 2
Thu 04 Mar 2021 08:50:33 PM UTC fast-reboot failure (12) cleanup ...
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# journalctl -a | grep fast-reboot-dump.py
                                                File "/usr/local/bin/fast-reboot-dump.py", line 301, in <module>
                                                File "/usr/local/bin/fast-reboot-dump.py", line 293, in main
                                                File "/usr/local/bin/fast-reboot-dump.py", line 280, in generate_default_route_entries
                                                File "/usr/local/bin/fast-reboot-dump.py", line 301, in <module>
                                                File "/usr/local/bin/fast-reboot-dump.py", line 293, in main
                                                File "/usr/local/bin/fast-reboot-dump.py", line 280, in generate_default_route_entries
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# cat /var/log/syslog | grep fast-reboot-dump.py
Mar  4 20:50:23.829554 sonic ERR fast-reboot-dump: Got an exception Object of type FieldValueMap is not JSON serializable: Traceback: Traceback (most recent call last):#012  File "/usr/local/bin/fast-reboot-dump.py", line 301, in <module>#012    res = main()#012  File "/usr/local/bin/fast-reboot-dump.py", line 293, in main#012    generate_default_route_entries(root_dir + '/default_routes.json')#012  File "/usr/local/bin/fast-reboot-dump.py", line 280, in generate_default_route_entries#012    json.dump(default_routes_output, fp, indent=2, separators=(',', ': '))#012  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump#012    for chunk in iterable:#012  File "/usr/lib/python3.7/json/encoder.py", line 429, in _iterencode#012    yield from _iterencode_list(o, _current_indent_level)#012  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list#012    yield from chunks#012  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict#012    yield from chunks#012  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode#012    o = _default(o)#012  File "/usr/lib/python3.7/json/encoder.py", line 179, in default#012    raise TypeError(f'Object of type {o.__class__.__name__} '#012TypeError: Object of type FieldValueMap is not JSON serializable
Mar  4 20:50:33.037228 sonic ERR fast-reboot-dump: Got an exception Object of type FieldValueMap is not JSON serializable: Traceback: Traceback (most recent call last):#012  File "/usr/local/bin/fast-reboot-dump.py", line 301, in <module>#012    res = main()#012  File "/usr/local/bin/fast-reboot-dump.py", line 293, in main#012    generate_default_route_entries(root_dir + '/default_routes.json')#012  File "/usr/local/bin/fast-reboot-dump.py", line 280, in generate_default_route_entries#012    json.dump(default_routes_output, fp, indent=2, separators=(',', ': '))#012  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump#012    for chunk in iterable:#012  File "/usr/lib/python3.7/json/encoder.py", line 429, in _iterencode#012    yield from _iterencode_list(o, _current_indent_level)#012  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list#012    yield from chunks#012  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict#012    yield from chunks#012  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode#012    o = _default(o)#012  File "/usr/lib/python3.7/json/encoder.py", line 179, in default#012    raise TypeError(f'Object of type {o.__class__.__name__} '#012TypeError: Object of type FieldValueMap is not JSON serializable
root@sonic:/home/admin#
root@sonic:/home/admin#

[sonic_dump_sonic_20210304_205615.tar.gz](https://github.com/Azure/sonic-buildimage/files/6084804/sonic_dump_sonic_20210304_205615.tar.gz)

**Comment by rkdevi27** [comment]
Hi, Is there any update on this issue.

**Comment by rkdevi27** [comment]
Hi,
This issue is not seen in SONiC.master.613-8504c72f (latest master)
Whereas it is consistently seen in SONiC.master.600-880a743c
I will update if the issue is seen again.

**Comment by anshuv-mfst** [comment]
Issue no longer seen in latest master, thanks.

**Comment by anshuv-mfst** [comment]
@vaibhavhd - could you please investigate what might have caused/fixed the issue. Issue is no longer seen in SONiC.master.613-8504c72f (latest master) while seen in SONiC.master.600-880a743c.
