### ISSUE TITLE
"show run all", "show run ports", "show run interfaces" are not showing running configs in 201911 image

### ISSUE THREAD

**Issue by rlhui** [Azure/sonic-buildimage#6982]
#### Description

CLI "show run all", "show run ports", "show run interfaces" are outputting errors

#### Steps to reproduce the issue:
1.  Issue CLI "show run", "show run ports" or "show run interfaces" and it did not work as expected.

#### Describe the results you received:
ritahui@TestDUT:~$ show run all | more
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 416, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 339, in main
    configdb.connect()
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 74, in connect
    self.db_connect('CONFIG_DB', wait_for_init, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 69, in db_connect
    SonicV2Connector.connect(self, self.db_name, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/dbconnector.py", line 250, in connect
    self.dbintf.connect(db_id, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 171, in connect
    self._onetime_connect(db_id)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 183, in _onetime_connect
    client.config_set('notify-keyspace-events', self.KEYSPACE_EVENTS)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 719, in config_set
    return self.execute_command('CONFIG SET', name, value)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 13 connecting to unix socket: /var/run/redis/redis.sock. Permission denied.

#### Describe the results you expected:

Running config should be displayed.  In earlier version

ritahui@TestDUT2:~$ show run all
{
    "AAA": {
        "authentication": {
            "login": "tacacs+"
        }
    }, 
  
<trim output>

#### Output of `show version`:

SONiC Software Version: SONiC.20191130.59
Distribution: Debian 9.13
Kernel: 4.9.0-14-2-amd64
Build commit: 7d7bdb0aa
Build date: Sat Jan 30 01:57:15 UTC 2021
Built by: sonicbld@new-worker-20

Platform: x86_64-arista_7060_cx32s
HwSKU: Arista-7060CX-32S-Q32
ASIC: broadcom
Serial Number: SSJ17490433
Uptime: 19:22:32 up  9:48,  1 user,  load average: 1.35, 1.58, 1.86

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-fpm-frr             20191130.59         68ab97ac7cf1        326MB
docker-fpm-frr             latest              68ab97ac7cf1        326MB
docker-orchagent           20191130.59         eae6c7670cb5        333MB
docker-orchagent           latest              eae6c7670cb5        333MB
docker-teamd               20191130.59         4c483a004ef5        315MB
docker-teamd               latest              4c483a004ef5        315MB
docker-syncd-brcm          20191130.59         6b3f7b0cc54e        437MB
docker-syncd-brcm          latest              6b3f7b0cc54e        437MB
docker-acms                20191130.59         ee39c1f0179d        184MB
docker-acms                latest              ee39c1f0179d        184MB
docker-platform-monitor    20191130.59         630127d00052        358MB
docker-platform-monitor    latest              630127d00052        358MB
docker-lldp-sv2            20191130.59         6590b6fcf372        312MB
docker-lldp-sv2            latest              6590b6fcf372        312MB
docker-snmp-sv2            20191130.59         eb71d7d877db        351MB
docker-snmp-sv2            latest              eb71d7d877db        351MB
docker-sonic-telemetry     20191130.59         a4a4f59c5e50        353MB
docker-sonic-telemetry     latest              a4a4f59c5e50        353MB
docker-router-advertiser   20191130.59         95bdb0004b53        290MB
docker-router-advertiser   latest              95bdb0004b53        290MB
docker-dhcp-relay          20191130.59         41011ffad614        300MB
docker-dhcp-relay          latest              41011ffad614        300MB
docker-database            20191130.59         ebf7962d195a        290MB
docker-database            latest              ebf7962d195a        290MB
k8s.gcr.io/pause           3.2                 80d28bedfe5d        683kB

```

**Comment by tahmed-dev** [comment]
This should have been fixed by [PR:5289](https://github.com/Azure/sonic-buildimage/pull/5289)

**Comment by rlhui** [comment]
> This should have been fixed by [PR:5289](https://github.com/Azure/sonic-buildimage/pull/5289)

@tahmed-dev  - PR:5289 was already there.
