### ISSUE TITLE
sonic_installer will change and set the system default console baud-rate to platform after installing image

### ISSUE THREAD

**Issue by fengkm** [Azure/sonic-buildimage#701]
sonic_installer will change and set the system default console baud-rate to platform after installing image.

ex:
Platform Console Setting
root@sonic:/usr/share/sonic/device/x86_64-ingrasys_s9100-r0# cat installer.conf 
CONSOLE_PORT=0x2f8
CONSOLE_DEV=1
CONSOLE_SPEED=115200

After sonic_installer install sonic-broadcom.bin
The console value will be changed as below

root@sonic:/home/admin# cat /host/grub/grub.cfg 
serial --port=0x3f8 --speed=9600 --word=8 --parity=no --stop=1

The CONSOLE_PORT=0x3f8, CONSOLE_SPEED=9600, and CONSOLE_DEV=ttyS0 are set with SONiC default value, not platform console setting as installer.conf.

**Comment by lguohan** [comment]
fixed in #710
