### ISSUE TITLE
ERR monit[480]: 'routeCheck' program timed out after 5.067 m. Killing program with pid 8480\

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#7023]
#### Steps to reproduce the issue:
1. https://dev.azure.com/mssonic/build/_build/results?buildId=6586&view=logs&j=551384a3-3c3d-5d98-9a93-ab579ce10658&t=dcc0ef7a-c27d-5084-36c2-e0f4d142c187
2.
3.

#### Output of `show version`:

```
(paste your output here)
```

**Comment by renukamanavalan** [comment]
I installed the sonic-broadcom.bin from the artifacts pointed by your link. I could not repro.

```
admin@my-dut:~$ time route_check.py

real    0m0.617s
user    0m0.373s
sys     0m0.072s
```

Can you please check your logs for route_check.py crashing stack generated when it got killed?
This can help us see, where it was stuck.

**Comment by lguohan** [comment]
all logs are published here. can you check? https://dev.azure.com/mssonic/build/_build/results?buildId=6586&view=artifacts&pathAsName=false&type=publishedArtifacts

this does not always happens, but in some cases it happens.

**Comment by renukamanavalan** [comment]
**Summary:**
This error happens upon ansible job invoking "config reload". Not on every conflig reload, but every failure happens during config-reload only.  It happens only once, while in the middle of daemons starting up. Even the monit is "awakened". Looked into 7 syslog archives

**Key missing**: Though route_check.py is *stated* to be killed by monit, there is no crash-stack in any of the logs. So there is no clue on where route_check.py was stuck at. 
 
**Attempted Repro:** Ran "reload" and "route_check" in two shells in a loop concurrently. The max I could get is to take the duration from fraction of a second to 9 seconds.
 
**Theory:**
Possibly some swsscommon call got stuck. Just a guess only
 
**Conclusion:**
This is not the common runtime failure. Hence this is not a critical issue.
Said that, I will put some more effort to see, if I could repro.

**Comment by lguohan** [comment]
it is not uncommon. here is another same case. 

https://dev.azure.com/mssonic/build/_build/results?buildId=6941&view=logs&j=551384a3-3c3d-5d98-9a93-ab579ce10658&t=dcc0ef7a-c27d-5084-36c2-e0f4d142c187

**Comment by renukamanavalan** [comment]
This error is "commonly" associated with "config reload" indirectly.
This error is *not* commonly seen otherwise.
Sample sequence below:

a) Ansible invoking "config reload"
b) Later during startup: Monit refreshed with a SIGHUP
c) In 5 mins: routcheck.py timedout error as after 5.067m

```
Mar 14 03:11:17.399108 vlab-01 INFO ansible-command: Invoked with creates=None executable=/bin/bash _uses_shell=True strip_empty_ends=True _raw_params=config reload -y &>/dev/null removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
....
syslog.6.gz:Mar 14 03:16:42.926197 vlab-01 INFO monit[449]: Awakened by the SIGHUP signal#012Reinitializing Monit - Control file '/etc/monit/monitrc'
...
Mar 14 03:21:47.149443 vlab-01 ERR monit[449]: 'routeCheck' program timed out after 5.067 m. Killing program with pid 30570
```

**Comment by renukamanavalan** [comment]
Unable to figure out, why we don't get crashing call stack ... Wondering on next steps ...

**Comment by renukamanavalan** [comment]
Raised [PR #1502](https://github.com/Azure/sonic-utilities/pull/1502), to help get call stack, upon hang. Not to wait till monit kills, where we lose any crashing call stack.

W/o call stack and with no repro, we are in dark.

**Comment by prsunny** [comment]
can this be closed?
