### ISSUE TITLE
201811 build failure: Unable to checkout <commit SHA> in submodule path 'src/sonic-utilities'

### ISSUE THREAD

**Issue by uraghura** [Azure/sonic-buildimage#7069]
#### Description
when I tried to do “make init” in 201811 sonic-buildimage, it failed with below error message. In the Azure/sonic-utilities repo, below commit HASH did not belong to any branch of sonic-utilities repo.  Is this issue known or someone facing it?

fatal: reference is not a tree: 2e44a2b31483e863b1eabbcb06bc8eb597be2a13
Unable to checkout '2e44a2b31483e863b1eabbcb06bc8eb597be2a13' in submodule path 'src/sonic-utilities'
Makefile.work:168: recipe for target 'init' failed
make[1]: *** [init] Error 1

#### Steps to reproduce the issue:
1. Checkout 201811 sonic-buildimage repo.
2. make init

#### Describe the results you received:
Build failure

#### Describe the results you expected:
Build should go through

#### Output of `show version`:
N/A

**Comment by lguohan** [comment]
looks like also failing here. https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-201811/79/

**Comment by anshuv-mfst** [comment]
@yxieca - could you please take a look, thanks.
