### ISSUE TITLE
dual tor: Show Mux Cable Status Produces Empty Table After Swss Restart

### ISSUE THREAD

**Issue by tahmed-dev** [Azure/sonic-buildimage#7086]
#### Description
`show muxcable status` cli produces empty table after swss is restarted.

#### Steps to reproduce the issue:
1. restart swss container
2.
3.

#### Describe the results you received:
```
admin@STR43-0101-0101-01LT0:~$ show muxcable status 
PORT    STATUS    HEALTH
------  --------  --------
```

#### Describe the results you expected:
```
admin@STR43-0101-0101-01LT0:~$ show muxcable status 
PORT         STATUS    HEALTH
-----------  --------  ---------
Ethernet0    standby   unhealthy
Ethernet4    standby   unhealthy
Ethernet8    active    unhealthy
Ethernet12   standby   unhealthy
```

#### Output of `show version`:
`beta.14`

#### Additional information you deem important (e.g. issue happens only occasionally):
restart pmon container fixes the issue

**Comment by prsunny** [comment]
Closing as the fix is merged
