### ISSUE TITLE
201911 "show mac" & "show arp" fail when Trunk interface is Trunk.

### ISSUE THREAD

**Issue by Ezrickd** [Azure/sonic-buildimage#7096]
Issue can be found fixed in 202012. https://github.com/Azure/sonic-buildimage/issues/5927

I need that fixed also for 201911.

Issue description: 

when one of a Vlan members is configured as Tagged, show mac & show arp is failing  with following error.

/home/admin# show vlan brief
+-----------+-----------------------+-----------------+----------------+-----------------------+
|   VLAN ID | IP Address            | Ports           | Port Tagging   | DHCP Helper Address   |
+===========+=======================+=================+================+=======================+
|        80 | 80.80.80.1/24         | PortChannel0005 | tagged         | 11.11.11.11           |
+-----------+-----------------------+-----------------+----------------+-----------------------+
|       106 | 192.168.106.254/24    | Ethernet68      | tagged         |                       |
+-----------+-----------------------+-----------------+----------------+-----------------------+
|       110 | 2001:ace:face::110/64 | Ethernet80      | untagged       | 2001:80:80:80::1      |
+-----------+-----------------------+-----------------+----------------+-----------------------+

:/home/admin# show mac
Failed to get Vlan id for bvid oid:0x26000000000013

invalid literal for int() with base 10: 'oid:0x26000000000013'
/home/admin# show arp
Failed to get Vlan id for bvid oid:0x26000000000013

invalid literal for int() with base 10: 'oid:0x26000000000013'

when I change the Port Tagging to Untagged it works.

 show vlan brief
+-----------+-----------------------+-----------------+----------------+-----------------------+
|   VLAN ID | IP Address            | Ports           | Port Tagging   | DHCP Helper Address   |
+===========+=======================+=================+================+=======================+
|        80 | 80.80.80.1/24         | PortChannel0005 | untagged       | 11.11.11.11           |
+-----------+-----------------------+-----------------+----------------+-----------------------+
|       106 | 192.168.106.254/24    | Ethernet68      | untagged       |                       |
+-----------+-----------------------+-----------------+----------------+-----------------------+
|       110 | 2001:ace:face::110/64 | Ethernet80      | untagged       | 2001:80:80:80::1      |
+-----------+-----------------------+-----------------+----------------+-----------------------+
root@AE-2700-5-Sonic:/etc/sonic# show mac
  No.    Vlan  MacAddress         Port             Type
-----  ------  -----------------  ---------------  -------
    1      80  00:AA:80:00:00:00  PortChannel0005  Dynamic
    2      80  7C:FE:90:F6:95:ED  PortChannel0005  Dynamic
Total number of entries 2
root@AE-2700-5-Sonic:/etc/sonic# show arp
Address       MacAddress         Iface            Vlan
------------  -----------------  ---------------  ------
10.0.0.1      24:8a:07:3f:18:62  Ethernet4        -
10.209.20.1   00:00:5e:00:01:01  eth0             -
10.209.22.32  00:25:90:2a:ce:de  eth0             -
80.0.0.6      24:8a:07:82:8d:c8  Ethernet4        -
172.16.20.9   24:8a:07:d0:ed:c8  PortChannel0116  -
Total number of entries 5
root@AE-2700-5-Sonic:/etc/sonic#
/etc/sonic# show ver

SONiC Software Version: SONiC.201911.95-de5c664b
Distribution: Debian 9.13
Kernel: 4.9.0-14-2-amd64
Build commit: de5c664b
Build date: Mon Mar 15 16:50:09 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci03

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
Serial Number: MT1833K19718
Uptime: 12:23:04 up 17 min,  1 user,  load average: 3.52, 4.49, 3.16

Docker images:
REPOSITORY                    TAG                  IMAGE ID            SIZE
docker-syncd-mlnx             201911.95-de5c664b   52b20512efd9        399MB
docker-syncd-mlnx             latest               52b20512efd9        399MB
docker-sonic-telemetry        201911.95-de5c664b   c2982bdbc919        354MB
docker-sonic-telemetry        latest               c2982bdbc919        354MB
docker-router-advertiser      201911.95-de5c664b   25b9b832e8e4        290MB
docker-router-advertiser      latest               25b9b832e8e4        290MB
docker-platform-monitor       201911.95-de5c664b   b2d9f9aacca0        666MB
docker-platform-monitor       latest               b2d9f9aacca0        666MB
docker-fpm-frr                201911.95-de5c664b   adbbf24dd825        335MB
docker-fpm-frr                latest               adbbf24dd825        335MB
docker-lldp-sv2               201911.95-de5c664b   32fa47a003e0        312MB
docker-lldp-sv2               latest               32fa47a003e0        312MB
docker-dhcp-relay             201911.95-de5c664b   68fd0849f71c        300MB
docker-dhcp-relay             latest               68fd0849f71c        300MB
docker-database               201911.95-de5c664b   712163d932ea        290MB
docker-database               latest               712163d932ea        290MB
docker-sflow                  201911.95-de5c664b   c663b30ffe18        315MB
docker-sflow                  latest               c663b30ffe18        315MB
docker-teamd                  201911.95-de5c664b   60c017e87445        315MB
docker-teamd                  latest               60c017e87445        315MB
docker-orchagent              201911.95-de5c664b   8ad05177975c        333MB
docker-orchagent              latest               8ad05177975c        333MB
docker-snmp-sv2               201911.95-de5c664b   e50867ad785d        351MB
docker-snmp-sv2               latest               e50867ad785d        351MB
docker-nat                    201911.95-de5c664b   55256f31e254        317MB
docker-nat                    latest               55256f31e254        317MB
docker-sonic-mgmt-framework   201911.95-de5c664b   c7c74302d0f1        428MB
docker-sonic-mgmt-framework   latest               c7c74302d0f1        428MB

**Comment by qiluo-msft** [comment]
The latest 201911 image should fix it already https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-201911/330/artifact/target/

Could you please test it again? I verified FDB on tagged interface (a PortChannel inside vlan) is working fine.

PS: could you reformat above messages with markdown syntax for better readability?

**Comment by qiluo-msft** [comment]
Close. Feel free to reopen if you found not fixed.
