### ISSUE TITLE
201911 Mac address is not removed when learned interface is down.

### ISSUE THREAD

**Issue by Ezrickd** [Azure/sonic-buildimage#7097]
same issue in 202012 is closed and fixed need that in 201911.

https://github.com/Azure/sonic-buildimage/issues/6425

the issue :

FDB entry will be kept in FDB until the timeout or leaned from new interface, regardless of the leaned interface status.
this keeps the FDB table full of none usable MAC address when interface is Shut.

in the below example I use Portchannel but the behavior is same for physical interface 

we can see that PortChannel005 has learned two MAC address, shutting down both LAG interfaces bring the PortChannel to DW.
we can see that the FDB still keep the addresses learned from PortChannel005.

root@AE-2700-5-Sonic:/etc/sonic# show mac
  No.    Vlan  MacAddress         Port             Type
-----  ------  -----------------  ---------------  -------
    1      80  00:AA:80:00:00:00  PortChannel0005  Dynamic
    2      80  7C:FE:90:F6:95:ED  PortChannel0005  Dynamic
Total number of entries 2
root@AE-2700-5-Sonic:/etc/sonic#
root@AE-2700-5-Sonic:/etc/sonic#
root@AE-2700-5-Sonic:/etc/sonic# show interfaces portchannel
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  ----------------------------
 0005  PortChannel0005  LACP(A)(Up)  Ethernet2(S) Ethernet6(S)
 0023  PortChannel0023  LACP(A)(Dw)  Ethernet100(D) Ethernet96(D)
 0116  PortChannel0116  LACP(A)(Up)  Ethernet116(S)
root@AE-2700-5-Sonic:/etc/sonic# config interface shutdown Ethernet2
root@AE-2700-5-Sonic:/etc/sonic# config interface shutdown Ethernet6
root@AE-2700-5-Sonic:/etc/sonic# show inter portchannel
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  ----------------------------
 0005  PortChannel0005  **LACP(A)(Dw)  Ethernet2(D) Ethernet6(D)**
 0023  PortChannel0023  LACP(A)(Dw)  Ethernet100(D) Ethernet96(D)
 0116  PortChannel0116  LACP(A)(Up)  Ethernet116(S)
root@AE-2700-5-Sonic:/etc/sonic# show mac
  No.    Vlan  MacAddress         Port             Type
-----  ------  -----------------  ---------------  -------
    1      80  00:AA:80:00:00:00  PortChannel0005  Dynamic
    2      80  7C:FE:90:F6:95:ED  PortChannel0005  Dynamic
Total number of entries 2
root@AE-2700-5-Sonic:/etc/sonic#

**Comment by anshuv-mfst** [comment]
Issue is fixed in master and known limitation in 201911 and 202012 release ( do not plan to backport to the releases)

**Comment by Ezrickd** [comment]
can you please advise on the PR in 202012 for the Fix..
