### ISSUE TITLE
201811 build failure for broadcom build: 'https://salsa.debian.org/kernel-team/initramfs-tools.git/': The requested URL returned error: 503

### ISSUE THREAD

**Issue by uraghura** [Azure/sonic-buildimage#7099]
#### Description
When trying to build SONiC image for Broadcom platforms, seeing build failure in 201811 branch. Is this issue known?

Facing the below issues during "make SONIC_BUILD_JOBS=40 PASSWORD=xxxx target/sonic-broadcom.bin":

fatal: unable to access 'https://salsa.debian.org/sk-guest/monit.git/': The requested URL returned error: 503
Makefile:9: recipe for target '/sonic/target/debs/monit_5.20.0-6_amd64.deb' failed

fatal: unable to access 'https://salsa.debian.org/kernel-team/initramfs-tools.git/': The requested URL returned error: 503
Makefile:11: recipe for target '/sonic/target/debs/initramfs-tools_0.130_all.deb' failed

#### Steps to reproduce the issue:
1. Clone and checkout latest 201811
2. make init ; make configure PLATFORM=broadcom
3. make SONIC_BUILD_JOBS=40 PASSWORD=xxxx target/sonic-broadcom.bin

#### Describe the results you received:
Build failure

#### Describe the results you expected:
Build should go through

#### Output of `show version`:
N/A

#### Additional information you deem important (e.g. issue happens only occasionally):
Always reproducible

**Comment by lguohan** [comment]
https://lists.debian.org/debian-infrastructure-announce/2021/03/msg00000.html

it is recovered
