### ISSUE TITLE
201811 parallel build failure seen with Innovium platform

### ISSUE THREAD

**Issue by uraghura** [Azure/sonic-buildimage#7139]
#### Description
Seeing parallel build failure due to conflicts between packages innovium-sai-headers 0.10.8.1.0.3 & libsaivs-dev_1.0.0_amd64.deb. In a single threaded i.e., serial build SONIC_BUILD_JOBS=1, build goes fine.

[ FAIL LOG START ] [ target/debs/libsaivs-dev_1.0.0_amd64.deb-install ]
Selecting previously unselected package libsaivs-dev.
(Reading database ... 135113 files and directories currently installed.)
Preparing to unpack .../libsaivs-dev_1.0.0_amd64.deb ...
Unpacking libsaivs-dev (1.0.0) ...
dpkg: error processing archive target/debs/libsaivs-dev_1.0.0_amd64.deb (--install):
 trying to overwrite '/usr/include/sai/saiswitchextensions.h', which is also in package innovium-sai-headers 0.10.8.1.0.3
Errors were encountered while processing:
 target/debs/libsaivs-dev_1.0.0_amd64.deb
[  FAIL LOG END  ] [ target/debs/libsaivs-dev_1.0.0_amd64.deb-install ]
slave.mk:396: recipe for target 'target/debs/libsaivs-dev_1.0.0_amd64.deb-install' failed

#### Steps to reproduce the issue:
1. make init
2. make configure PLATFORM=innovium
3. make SONIC_BUILD_JOBS=40 PASSWORD=xxxx target/sonic-innovium.bin

#### Describe the results you received:
Parallel build failure

#### Describe the results you expected:
Build should go through

#### Output of `show version`:
N/A

#### Additional information you deem important (e.g. issue happens only occasionally):
Always reproducible

**Comment by uraghura** [comment]
Is this known issue? Any PR for this?

**Comment by abdosi** [comment]
@tonytitus

**Comment by anshuv-mfst** [comment]
@tonytitus - could innovium team please take a look into this issue, thanks.

**Comment by tonytitus** [comment]
Will take a look

**Comment by uraghura** [comment]
SONiC specific issue and fix needs to be backported from other branches. We could see a fix https://github.com/Azure/sonic-buildimage/pull/6335/files done for few parallel build issues. But these fixes are not  available for 201811. For now, Workaround is *NOT* to do parallel build for innovium platform.

**Comment by bluecmd** [comment]
This still happens, even in 202411 - FWIW.

```
[ building ] [ target/debs/bookworm/libsaivs-dev_1.0.0_amd64.deb-install ] 
dpkg-query: package 'saihdr' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
[ finished ] [ target/debs/bookworm/libsaivs-dev_1.0.0_amd64.deb-install ] 
[ FAIL LOG START ] [ target/debs/bookworm/libsaivs-dev_1.0.0_amd64.deb-install ]
[20:16:57] Build start time: Thu Dec 26 20:16:57 UTC 2024
[20:16:57] Selecting previously unselected package libsaivs-dev.
[20:16:57] (Reading database ... 227297 files and directories currently installed.)
[20:16:57] Preparing to unpack .../libsaivs-dev_1.0.0_amd64.deb ...
[20:16:57] Unpacking libsaivs-dev (1.0.0) ...
[20:16:57] dpkg: error processing archive target/debs/bookworm/libsaivs-dev_1.0.0_amd64.deb (--install):
[20:16:57]  trying to overwrite '/usr/include/sai/sai.h', which is also in package innovium-sai-headers 4.0.1
[20:16:57] Errors were encountered while processing:
[20:16:57]  target/debs/bookworm/libsaivs-dev_1.0.0_amd64.deb
[  FAIL LOG END  ] [ target/debs/bookworm/libsaivs-dev_1.0.0_amd64.deb-install ]
```
