### ISSUE TITLE
multi-asic: sonic-cfggen fails to get right port_config file when -n option is provided

### ISSUE THREAD

**Issue by anamehra** [Azure/sonic-buildimage#7161]
#### Description
On 202012, multi-asic system, when I run sonic-cfggen to genretae config_dbX.json for am asic_id X, the right port config file is not picked. sonic-cfggen calls device_info.get_path_to_port_config_file method with hwsku but no asic_id. The method returns none. Sonic-cfggen fails to get the right port_config.ini path.

        if args.port_config is None:
            args.port_config = device_info.get_path_to_port_config_file(hwsku)

def get_path_to_port_config_file(hwsku=None, asic=None):
    """
    Retrieves the path to the device's port configuration file
.
.
        **asic**: a string , asic argument should be passed on multi-ASIC devices only,
              it should be omitted on single-ASIC platforms. 

Moreover device_info.py use swsssdk for ConfigDBConnector, SonicDBConfig, SonicV2Connector while sonic-cfggen is moved to libswsscommon, which may cause other db issue as seen in #7155 

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```

**Comment by anshuv-mfst** [comment]
Issue seen only on 202012 and not seen in 201911. 
@anamehra - please provide more info 
1. provide complete command
2. Is the issue seen in master? please re-create with master branch

**Comment by anamehra** [comment]
For a 3 asic system, here is the HWSKU directory structure:
ls /usr/share/sonic/device/platform-x/hwsku/*/
0/port_config.ini
1/port_config.ini
2/port_config.ini

command run:
**export HWSKU=/usr/share/sonic/device/platform-x/hwsku/
sonic-cfggen -n asic0 -H -k $HWSKU --preset t1**

The command doe snot pick the right port_config.ini file which should be /usr/share/sonic/device/platform-x/hwsku/0/port_config.ini

when sonic-cfggen makes a call to device_info.get_path_to_port_config_file(hwsku), the return value is 'None'
changing this call to device_info.get_path_to_port_config_file(hwsku, asic_id) helped return the correct path
and sonic-cfggen generated right data.

As a workaround, I passed -p <port_config.ini> option and that worked fine as it bypass the get_path_to_port_config_file () call.

**Comment by anshuv-mfst** [comment]
Hi @SuvarnaMeenakshi could you please provide input, thanks.

**Comment by SuvarnaMeenakshi** [comment]
I will raise a PR to fix sonic-cfggen to take namespace parameter.
A PR for swsscommon which was required is merged in: https://github.com/Azure/sonic-swss-common/pull/470
Will update with sonic-cfggen fix PR here.

**Comment by anamehra** [comment]
@SuvarnaMeenakshi looks like Azure/sonic-swss-common#470 handles the swsscommon issue reported in #7155
Is there a different commit PR for sonic-cfggen port_config.ini path as reported in this issue?

**Comment by SuvarnaMeenakshi** [comment]
> @SuvarnaMeenakshi looks like [Azure/sonic-swss-common#470](https://github.com/Azure/sonic-swss-common/pull/470) handles the swsscommon issue reported in #7155
> Is there a different commit PR for sonic-cfggen port_config.ini path as reported in this issue?

yes; it is here: https://github.com/Azure/sonic-buildimage/pull/7632

**Comment by SuvarnaMeenakshi** [comment]
Fixed in https://github.com/Azure/sonic-buildimage/pull/7632
