### ISSUE TITLE
DHCLIENT fails to renew lease on expiry

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#7192]
#### Description
Sometimes Dhclient doesn't renew after the first boot. It happens very rare and not easily recreatable. This is a known issue reported in isc-dhclient 4.4.2 as listed in the bugs below

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867276

https://bugs.debian.org/cgi-bin/pkgreport.cgi?archive=0;dist=unstable;ordering=normal;repeatmerged=0;src=isc-dhcp

The issue can be recovered by 'dhclient eth0'

lease {
  interface "eth0";
  fixed-address 10.210.24.228;
  filename "pxelinux.0";
  option subnet-mask 255.255.252.0;
  option dhcp-lease-time 3600;
  option routers 10.210.24.1;
  option dhcp-message-type 5;
  option dhcp-server-identifier 10.211.0.124;
  option domain-name-servers 10.211.0.124,10.211.0.121,10.7.77.135;
  option domain-search "mtr.labs.mlnx.", "labs.mlnx.", "mlnx.", "lab.mtl.com.", "mtl.com.";
  option broadcast-address 10.210.27.255;
  option ntp-servers 10.211.0.134,10.211.0.124,10.7.77.135;
  option host-name "r-anaconda-70";
  option domain-name "mtr.labs.mlnx";
  renew 1 2021/03/29 10:25:27;
  rebind 1 2021/03/29 10:25:27;
  expire 1 2021/03/29 10:25:27;
}
lease {
  interface "eth0";
  fixed-address 10.210.24.228;
  filename "pxelinux.0";
  option subnet-mask 255.255.252.0;
  option routers 10.210.24.1;
  option dhcp-lease-time 3600;
  option dhcp-message-type 5;
  option domain-name-servers 10.211.0.124,10.211.0.121,10.7.77.135;
  option dhcp-server-identifier 10.211.0.124;
  option domain-search "mtr.labs.mlnx.", "labs.mlnx.", "mlnx.", "lab.mtl.com.", "mtl.com.";
  option ntp-servers 10.211.0.134,10.211.0.124,10.7.77.135;
  option broadcast-address 10.210.27.255;
  option host-name "r-anaconda-70";
  option domain-name "mtr.labs.mlnx";
  renew 1 2021/03/29 10:53:13;
  rebind 1 2021/03/29 11:18:24;
  expire 1 2021/03/29 11:25:54;
}
lease {
  interface "eth0";
  fixed-address 10.210.24.228;
  filename "pxelinux.0";
  option subnet-mask 255.255.252.0;
  option routers 10.210.24.1;
  option dhcp-lease-time 3600;
  option dhcp-message-type 5;
  option domain-name-servers 10.211.0.124,10.211.0.121,10.7.77.135;
  option dhcp-server-identifier 10.211.0.124;
  option domain-search "mtr.labs.mlnx.", "labs.mlnx.", "mlnx.", "lab.mtl.com.", "mtl.com.";
  option ntp-servers 10.211.0.134,10.211.0.124,10.7.77.135;
  option broadcast-address 10.210.27.255;
  option host-name "r-anaconda-70";
  option domain-name "mtr.labs.mlnx";
  renew 1 2021/03/29 18:24:11;
  rebind 1 2021/03/29 18:46:58;
  expire 1 2021/03/29 18:54:28;
}
 

syslog.66.gz:Mar 29 10:20:46.328836 sonic INFO dhclient[3350]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:21:32.303275 sonic INFO dhclient[8235]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:21:44.260818 sonic INFO dhclient[8727]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:22:42.190632 sonic INFO dhclient[12407]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:24:20.798080 r-anaconda-70 INFO dhclient[17179]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:25:16.554980 r-anaconda-70 INFO dhclient[778]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:25:19.874660 r-anaconda-70 INFO dhclient[778]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:25:25.318863 r-anaconda-70 INFO dhclient[778]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.66.gz:Mar 29 10:25:54.447477 r-anaconda-70 INFO dhclient[3544]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.7.gz:Mar 29 17:29:52.683837 r-anaconda-70 INFO dhclient[21965]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67
syslog.7.gz:Mar 29 17:29:54.109652 r-anaconda-70 INFO dhclient[3544]: DHCPREQUEST for 10.210.24.228 on eth0 to 255.255.255.255 port 67

#### Steps to reproduce the issue:
1. Reboot the device after installing new image.
2. Wait for dhcp lease to expire

#### Describe the results you received:
IP address on eth0 is removed and ssh connectivity to the device is lost.

#### Describe the results you expected:
IP address should not be removed and the lease should be renewed before expiry
[sonic_dump_r-anaconda-70_20210329_183626.tar.gz](https://github.com/Azure/sonic-buildimage/files/6230908/sonic_dump_r-anaconda-70_20210329_183626.tar.gz)

#### Output of `show version`:

```
show version

SONiC Software Version: SONiC.SONIC.202012.55-0269fc1_Internal
Distribution: Debian 10.9
Kernel: 4.19.0-12-2-amd64
Build commit: 0269fc19
Build date: Tue Mar 30 15:47:31 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02

Platform: x86_64-mlnx_msn3700-r0
HwSKU: ACS-MSN3700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2037X14189
Uptime: 17:12:40 up 43 min,  1 user,  load average: 0.74, 0.76, 1.03

Docker images:
REPOSITORY                    TAG                                IMAGE ID            SIZE
docker-syncd-mlnx             SONIC.202012.55-0269fc1_Internal   04c5b8cb6ed0        730MB
docker-syncd-mlnx             latest                             04c5b8cb6ed0        730MB
docker-platform-monitor       SONIC.202012.55-0269fc1_Internal   c87b9a532dda        785MB
docker-platform-monitor       latest                             c87b9a532dda        785MB
docker-snmp                   SONIC.202012.55-0269fc1_Internal   94bbb448b081        528MB
docker-snmp                   latest                             94bbb448b081        528MB
docker-teamd                  SONIC.202012.55-0269fc1_Internal   8498554ccd94        476MB
docker-teamd                  latest                             8498554ccd94        476MB
docker-nat                    SONIC.202012.55-0269fc1_Internal   6b2a3387c91b        478MB
docker-nat                    latest                             6b2a3387c91b        478MB
docker-dhcp-relay             SONIC.202012.55-0269fc1_Internal   434806927975        472MB
docker-dhcp-relay             latest                             434806927975        472MB
docker-orchagent              SONIC.202012.55-0269fc1_Internal   bd0ce88beeb9        522MB
docker-orchagent              latest                             bd0ce88beeb9        522MB
docker-fpm-frr                SONIC.202012.55-0269fc1_Internal   f6198a2e6ecd        494MB
docker-fpm-frr                latest                             f6198a2e6ecd        494MB
docker-sflow                  SONIC.202012.55-0269fc1_Internal   155e1304c0ee        476MB
docker-sflow                  latest                             155e1304c0ee        476MB
docker-lldp                   SONIC.202012.55-0269fc1_Internal   04811f4c9314        438MB
docker-lldp                   latest                             04811f4c9314        438MB
docker-sonic-telemetry        SONIC.202012.55-0269fc1_Internal   af7e2fed9586        487MB
docker-sonic-telemetry        latest                             af7e2fed9586        487MB
docker-sonic-mgmt-framework   SONIC.202012.55-0269fc1_Internal   a7102689a7cc        616MB
docker-sonic-mgmt-framework   latest                             a7102689a7cc        616MB
docker-router-advertiser      SONIC.202012.55-0269fc1_Internal   8eccf750c8a5        398MB
docker-router-advertiser      latest                             8eccf750c8a5        398MB
docker-database               SONIC.202012.55-0269fc1_Internal   ca17646eb20d        398MB
docker-database               latest                             ca17646eb20d        398MB


```

**Comment by dgsudharsan** [comment]
@tahmed-dev @jleveque Please let me know if you need any more information

**Comment by tahmed-dev** [comment]
@dgsudharsan which DHCP client was used? AFAIK, SONiC doesn't build the DHCP client, only the relay is being built.

**Comment by roysr-nv** [comment]
dhclient version: `isc-dhclient-4.4.1`

**Comment by dprital** [comment]
@tahmed-dev  - Can you please estimate when this issue can be fixed ? from our POV it is showstopper bug.

**Comment by anshuv-mfst** [comment]
@tahmed-dev - could you please take a look, thanks.

**Comment by tahmed-dev** [comment]
> dhclient version: `isc-dhclient-4.4.1`

SONiC does not build nor support this requirement at the moment and so why this is a SONiC issue?

**Comment by tahmed-dev** [comment]
> @tahmed-dev - Can you please estimate when this issue can be fixed ? from our POV it is showstopper bug.

@dprital What is POV? The dhclient is not being built by SONiC and so this is new requirement and is not an issue against existing SONiC feature. The solution online states that starting the dhclient with the interface name after reboot solves the issue. Does this work in your setup?

**Comment by tahmed-dev** [comment]
The issue has been inactive for long. Will close this issue in a week if there are no more activity.

**Comment by tahmed-dev** [comment]
closing this issue.
