### ISSUE TITLE
[KVM] Warmboot reboot_pre_check failed as "Docker exec on syncd timedout"

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#7214]
#### Description

After adding a new check in warmboot script for checking docker exec, KVM warmboot test has started reporting exec timedout error for syncd container.
The `docker exec` to `syncd` container timedout after 1s. However docker exec test worked for all other containers 
`containers="radv bgp lldp swss database teamd syncd"`

https://dev.azure.com/mssonic/build/_build/results?buildId=9127&view=logs&j=917c1508-19c3-53d5-10ca-59367f40e278&t=ee91ab2a-89fc-53fe-e8a3-d4d569b7f2e0&l=88

This check failed and prevented warmboot from proceeding:
https://github.com/Azure/sonic-utilities/blob/master/scripts/fast-reboot#L322

#### Steps to reproduce the issue:
1. Run warmboot test on KVM
2. Warmboot is not allowed, as prechecks fail (docker exec syncd takes more 1s).
3.

#### Describe the results you received:
Advanced reboot test failed with

```
advanced-reboot.ReloadTest ... Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "ptftests/advanced-reboot.py", line 1190, in reboot_dut
    raise Exception("{} failed with error {}".format(self.reboot_type, stderr))
Exception: warm-reboot failed with error [u'Docker exec on syncd timedout\n']

FAIL

======================================================================
FAIL: advanced-reboot.ReloadTest
----------------------------------------------------------------------
```

#### Describe the results you expected:
Docker exec to syncd container should not timeout. Warmboot should proceed.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vaibhavhd** [comment]
This failure is more frequent and the error is seen on other containers too - radv, syncd are known to timeout on exec call.

At this point the cause seems to be slow KVM device, which leads to timeouts in different containers.

**Comment by shi-su** [comment]
It is a little surprising that that line takes more than a second to be done. I suspect if it runs at such a speed, it will get some other timeout even if it does not fail here.

**Comment by vaibhavhd** [comment]
I agree with you! The 1s was the more strictest timeout of all in the script. Actually these timeouts happened after these new changes https://github.com/Azure/sonic-utilities/pull/1495/files

So, below are the potential KVM failures due to the image change:
1. Docker exec test for all containers - 1s (this failure in this PR)
2. `syncd_request_shutdown` timeout - 5s
2. `remove Redis dump file from database container` timeout - 5s

I think 5s should be good enough time in KVM to try to remove redis dump file from database container.

I am not too sure if 5s timeout is good enough for syncd_request_shutdown. I will want to check this from the test runs.

**Comment by daall** [comment]
KVM-specific issue, fixed in the test cases: https://github.com/Azure/sonic-mgmt/pull/3266
