### ISSUE TITLE
Build Error on Ubuntu 20.04: Server does not implement system.SystemServer (missing system.mustEmbedUnimplementedSystemServer method)

### ISSUE THREAD

**Issue by ncalad** [Azure/sonic-buildimage#7268]
Server does not implement system.SystemServer (missing system.mustEmbedUnimplementedSystemServer method)

#### Steps to reproduce the issue:
1. git clone https://github.com/Azure/sonic-buildimage.git 
2. make init
3. make configure PLATFORM=broadcom
4. make all 

#### Describe the results you received:
... 
patch -d vendor -p0 < patches/gnmi_get.patch
patching file ./github.com/jipanyang/gnxi/gnmi_get/gnmi_get.go
touch vendor/.done
/usr/local/go/bin/go install -mod=vendor  github.com/Azure/sonic-telemetry/telemetry
# github.com/Azure/sonic-telemetry/gnmi_server
gnmi_server/server.go:144:42: cannot use srv (type *Server) as type system.SystemServer in argument to system.RegisterSystemServer:
	*Server does not implement system.SystemServer (missing system.mustEmbedUnimplementedSystemServer method)
make[2]: *** [Makefile:54: sonic-telemetry] Error 2
make[2]: Leaving directory '/sonic/src/sonic-telemetry'
dh_auto_build: make -j1 returned exit code 2
make[1]: *** [debian/rules:7: build] Error 2
make[1]: Leaving directory '/sonic/src/sonic-telemetry'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
[  FAIL LOG END  ] [ target/debs/buster/sonic-telemetry_0.1_amd64.deb ]
make: *** [slave.mk:454: target/debs/buster/sonic-telemetry_0.1_amd64.deb] Error 1

#### Describe the results you expected:
I expected build to proceed to completion 

#### Additional information you deem important (e.g. issue happens only occasionally):
This happens again if I re-run 'make all'

**Comment by gord1306** [comment]
please refer https://github.com/Azure/sonic-telemetry/pull/76
