### ISSUE TITLE
[HLX] Regression: syncd crash

### ISSUE THREAD

**Issue by Blueve** [Azure/sonic-buildimage#7276]
#### Description

Syncd crashed due to SAI issue.
Relating SAI issue was ignored previously, a recent change(https://github.com/Azure/sonic-swss/pull/1665) regarding SAI error handling caused this regression.

#### Steps to reproduce the issue:
1. Include all changes for fixing recent HLX platform issue
2. Build image and install
3. Check syncd status and log

#### Describe the results you received:

```
Apr  9 00:52:08.077649 str-e1031-acs-4 ERR syncd#syncd: [none] SAI_API_NEIGHBOR:_brcm_sai_nbr_bcast_ip_create:3537 egress create failed with error Invalid configuration (0xfffffff1).
Apr  9 00:52:08.077649 str-e1031-acs-4 ERR syncd#syncd: [none] SAI_API_NEIGHBOR:brcm_sai_create_neighbor_entry:444 nbr bcast ip create failed with error -1.
Apr  9 00:52:08.077649 str-e1031-acs-4 ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_FAILURE
Apr  9 00:52:08.078376 str-e1031-acs-4 ERR syncd#syncd: :- processQuadEvent: attr: SAI_NEIGHBOR_ENTRY_ATTR_DST_MAC_ADDRESS: FF:FF:FF:FF:FF:FF
Apr  9 00:52:08.085094 str-e1031-acs-4 ERR swss#orchagent: :- create: create status: SAI_STATUS_FAILURE
Apr  9 00:52:08.085536 str-e1031-acs-4 ERR swss#orchagent: :- addDirectedBroadcast: Failed to create broadcast entry 192.168.7.255 rv:-1
Apr  9 00:52:08.085928 str-e1031-acs-4 ERR swss#orchagent: :- handleSaiCreateStatus: Encountered failure in create operation, exiting orchagent, SAI API: SAI_API_NEIGHBOR, status: SAI_STATUS_FAILURE
```

#### Describe the results you expected:

syncd running without issues

#### Output of `show version`:

```
(paste your output here)
```

**Comment by gechiang** [comment]
The following case was filed to track this issue with BRCM:
BRCM Case CS00012183303 [4.3] SAI_API_NEIGHBOR:_brcm_sai_nbr_bcast_ip_create:3537 egress create failed with error Invalid configuration (0xfffffff1)

**Comment by gechiang** [comment]
@blueve Can you please try out any latest 202012 image that has SAI 4.3.5.1 or later versions.
I did validate this to be fixed already.  if you still find issues, feel free to reopen this issue.
Closing it now...

**Comment by Blueve** [comment]
> @Blueve Can you please try out any latest 202012 image that has SAI 4.3.5.1 or later versions.
> I did validate this to be fixed already. if you still find issues, feel free to reopen this issue.
> Closing it now...

Yes, this issue has been addressed.  Thanks for closing this issue : D
