### ISSUE TITLE
Build fails with "chroot ./fsroot docker info"

### ISSUE THREAD

**Issue by bluecmd** [Azure/sonic-buildimage#7354]
#### Description

I am trying to build SONiC master (commit 75c29cbbb995cc9f0b146c72a1fb2426cf3c9814).

#### Steps to reproduce the issue:
1. git checkout master
2. make init
3. make configure PLATFORM=broadcom
4. make all

NOTE: I have also set `SONIC_CONFIG_USE_NATIVE_DOCKERD_FOR_BUILD` but I seem to be getting the same result even without.

#### Describe the results you received:

Output of target/sonic-broadcom.bin.log:
```
[...]
+ sudo cp files/image_config/platform/rc.local ./fsroot/etc/
+ sudo cp files/image_config/platform/linux_kernel_bde.conf ./fsroot/etc/modprobe.d/
+ [[ amd64 == armhf ]]
+ [[ amd64 == arm64 ]]
+ trap_push clean_proc
+ local 'oldcmd=clean_sys; true'
+ local 'newcmd=clean_proc; clean_sys; true'
+ trap -- 'clean_proc; clean_sys; true' EXIT INT TERM HUP
+ _trap_push 'clean_proc; clean_sys; true'
+ local 'next=clean_proc; clean_sys; true'
++ echo 'clean_proc; clean_sys; true'
++ sed -e 's/'\''/'\''\\'\'''\''/g'
+ eval 'trap_push() {
        local oldcmd='\''clean_proc; clean_sys; true'\''
        local newcmd="$1; $oldcmd"
        trap -- "$newcmd" EXIT INT TERM HUP
        _trap_push "$newcmd"
    }'
+ sudo mount proc /proc -t proc
+ sudo mkdir ./fsroot/target
+ sudo mount --bind target ./fsroot/target
+ sudo chroot ./fsroot docker info
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
+ clean_proc
+ sudo umount /proc
+ clean_sys
+ sudo chroot ./fsroot umount /sys/fs/cgroup/cgroup.controllers /sys/fs/cgroup/cgroup.events /sys/fs/cgroup/cgroup.freeze /sys/fs/cgroup/cgroup.max.depth /sys/fs/cgroup/cgroup.max.descendants /sys/fs/cgroup/cgroup.procs /sys/fs/cgroup/cgroup.stat /sys/fs/cgroup/cgroup.subtree_control /sys/fs/cgroup/cgroup.threads /sys/fs/cgroup/cgroup.type /sys/fs/cgroup/cpu.max /sys/fs/cgroup/cpu.pressure /sys/fs/cgroup/cpu.stat /sys/fs/cgroup/cpu.weight /sys/fs/cgroup/cpu.weight.nice /sys/fs/cgroup/cpuset.cpus /sys/fs/cgroup/cpuset.cpus.effective /sys/fs/cgroup/cpuset.cpus.partition /sys/fs/cgroup/cpuset.mems /sys/fs/cgroup/cpuset.mems.effective /sys/fs/cgroup/io.max /sys/fs/cgroup/io.pressure /sys/fs/cgroup/io.stat /sys/fs/cgroup/memory.current /sys/fs/cgroup/memory.events /sys/fs/cgroup/memory.events.local /sys/fs/cgroup/memory.high /sys/fs/cgroup/memory.low /sys/fs/cgroup/memory.max /sys/fs/cgroup/memory.min /sys/fs/cgroup/memory.oom.group /sys/fs/cgroup/memory.pressure /sys/fs/cgroup/memory.stat /sys/fs/cgroup/memory.swap.current /sys/fs/cgroup/memory.swap.events /sys/fs/cgroup/memory.swap.high /sys/fs/cgroup/memory.swap.max /sys/fs/cgroup/pids.current /sys/fs/cgroup/pids.events /sys/fs/cgroup/pids.max /sys/fs/cgroup/rdma.current /sys/fs/cgroup/rdma.max /sys/fs/cgroup /sys
umount: /sys/fs/cgroup/cgroup.controllers: no mount point specified.
umount: /sys/fs/cgroup/cgroup.events: no mount point specified.
umount: /sys/fs/cgroup/cgroup.freeze: no mount point specified.
umount: /sys/fs/cgroup/cgroup.max.depth: no mount point specified.
umount: /sys/fs/cgroup/cgroup.max.descendants: no mount point specified.
umount: /sys/fs/cgroup/cgroup.procs: no mount point specified.
umount: /sys/fs/cgroup/cgroup.stat: no mount point specified.
umount: /sys/fs/cgroup/cgroup.subtree_control: no mount point specified.
umount: /sys/fs/cgroup/cgroup.threads: no mount point specified.
umount: /sys/fs/cgroup/cgroup.type: no mount point specified.
umount: /sys/fs/cgroup/cpu.max: no mount point specified.
umount: /sys/fs/cgroup/cpu.pressure: no mount point specified.
umount: /sys/fs/cgroup/cpu.stat: no mount point specified.
umount: /sys/fs/cgroup/cpu.weight: no mount point specified.
umount: /sys/fs/cgroup/cpu.weight.nice: no mount point specified.
umount: /sys/fs/cgroup/cpuset.cpus: no mount point specified.
umount: /sys/fs/cgroup/cpuset.cpus.effective: no mount point specified.
umount: /sys/fs/cgroup/cpuset.cpus.partition: no mount point specified.
umount: /sys/fs/cgroup/cpuset.mems: no mount point specified.
umount: /sys/fs/cgroup/cpuset.mems.effective: no mount point specified.
umount: /sys/fs/cgroup/io.max: no mount point specified.
umount: /sys/fs/cgroup/io.pressure: no mount point specified.
umount: /sys/fs/cgroup/io.stat: no mount point specified.
umount: /sys/fs/cgroup/memory.current: no mount point specified.
umount: /sys/fs/cgroup/memory.events: no mount point specified.
umount: /sys/fs/cgroup/memory.events.local: no mount point specified.
umount: /sys/fs/cgroup/memory.high: no mount point specified.
umount: /sys/fs/cgroup/memory.low: no mount point specified.
umount: /sys/fs/cgroup/memory.max: no mount point specified.
umount: /sys/fs/cgroup/memory.min: no mount point specified.
umount: /sys/fs/cgroup/memory.oom.group: no mount point specified.
umount: /sys/fs/cgroup/memory.pressure: no mount point specified.
umount: /sys/fs/cgroup/memory.stat: no mount point specified.
umount: /sys/fs/cgroup/memory.swap.current: no mount point specified.
umount: /sys/fs/cgroup/memory.swap.events: no mount point specified.
umount: /sys/fs/cgroup/memory.swap.high: no mount point specified.
umount: /sys/fs/cgroup/memory.swap.max: no mount point specified.
umount: /sys/fs/cgroup/pids.current: no mount point specified.
umount: /sys/fs/cgroup/pids.events: no mount point specified.
umount: /sys/fs/cgroup/pids.max: no mount point specified.
umount: /sys/fs/cgroup/rdma.current: no mount point specified.
umount: /sys/fs/cgroup/rdma.max: no mount point specified.
+ true
+ true
+ sudo LANG=C chroot ./fsroot umount /proc
+ true
```

#### Describe the results you expected:

The build succeeded

#### Output of `show version`:

N/A 

#### Output of `show techsupport`:

N/A 

#### Additional information you deem important (e.g. issue happens only occasionally):

I am running Debian bullseye.

**Comment by bluecmd** [comment]
I have tested with running the same things on another machine, running Ubuntu 20.10, and it seems to work with default build settings.

**Comment by bluecmd** [comment]
I will run the build using Ubuntu 20.10 for now

**Comment by ZhaoWeir** [comment]
Have you solved the problem?

**Comment by Prakash-Sanchela** [comment]
same issue I am facinf while building broadcom sonic image. 
Even I did make clean after the error but still same error I am facing. 

Steps :
Clone repo
Make init
make configure PLATFORM=broadcom
make SONIC_BUILD_JOBS=4 target/sonic-***-broadcom.*w*

Previously on same environement i was able to build the image and this error is causing pain and doesn't get any input to resolve this yet. 

Here is the error logs. 

`E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Selecting previously unselected package smartmontools.
(Reading database ... 49058 files and directories currently installed.)
Preparing to unpack .../smartmontools_7.2-1_amd64.deb ...
Unpacking smartmontools (7.2-1) ...
Setting up smartmontools (7.2-1) ...
Created symlink /etc/systemd/system/smartd.service -> /lib/systemd/system/smartmontools.service.
Created symlink /etc/systemd/system/multi-user.target.wants/smartmontools.service -> /lib/systemd/system/smartmontools.service.
+ sudo dpkg --root=./fsroot-broadcom -i target/debs/bullseye/openssh-server_8.4p1-5+deb11u1_amd64.deb
dpkg: warning: downgrading openssh-server from 1:8.4p1-5+deb11u2 to 1:8.4p1-5+deb11u1
(Reading database ... 49104 files and directories currently installed.)
Preparing to unpack .../openssh-server_8.4p1-5+deb11u1_amd64.deb ...
Unpacking openssh-server (1:8.4p1-5+deb11u1) over (1:8.4p1-5+deb11u2) ...
dpkg: dependency problems prevent configuration of openssh-server:
 openssh-server depends on openssh-client (= 1:8.4p1-5+deb11u1); however:
  Version of openssh-client on system is 1:8.4p1-5+deb11u2.

dpkg: error processing package openssh-server (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openssh-server
+ clean_sys
+ sudo chroot ./fsroot-broadcom umount /sys/fs/cgroup/blkio /sys/fs/cgroup/cpu /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuacct /sys/fs/cgroup/cpuset /sys/fs/cgroup/devices /sys/fs/cgroup/freezer /sys/fs/cgroup/hugetlb /sys/fs/cgroup/memory /sys/fs/cgroup/net_cls /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/net_prio /sys/fs/cgroup/perf_event /sys/fs/cgroup/pids /sys/fs/cgroup/rdma /sys/fs/cgroup/systemd /sys/fs/cgroup /sys
umount: /sys/fs/cgroup/cpu: no mount point specified.
umount: /sys/fs/cgroup/cpu,cpuacct: no mount point specified.
umount: /sys/fs/cgroup/cpuacct: no mount point specified.
umount: /sys/fs/cgroup/net_cls: no mount point specified.
umount: /sys/fs/cgroup/net_cls,net_prio: no mount point specified.
umount: /sys/fs/cgroup/net_prio: no mount point specified.
umount: /sys/fs/cgroup/systemd: no mount point specified.
+ true
+ true
+ sudo LANG=C chroot ./fsroot-broadcom umount /proc
+ true
[  FAIL LOG END  ] [ target/sonic-aboot-broadcom.swi ]
make: *** [slave.mk:1266: target/sonic-aboot-broadcom.swi] Error 1
make[1]: Leaving directory '/home/sonic/prakash/sonic-buildimage'`

**Comment by Applepi** [comment]
This also doesn't work on Ubuntu 20.04 LTS as recommended by the build docs for branch 202106. 

I guess I shouldn't have trusted this project for core infrastructure if they can't even get their build working outside of the pipeline.
