### ISSUE TITLE
build error with the old repo

### ISSUE THREAD

**Issue by zhenggen-xu** [Azure/sonic-buildimage#742]
I had the sonic-buildimage version: 
commit d083d7e79cd9614a8874a0301ff7466ee244de34 
which was built fine before.  But now when I do "make target/sonic-broadcom.bin" again, I see below error:

Executing rules for target/docker-base.gz
Sending build context to Docker daemon 97.74 MB
Step 1/12 : FROM debian:jessie
jessie: Pulling from library/debian
9f0706ba7422: Pulling fs layer
9f0706ba7422: Verifying Checksum
9f0706ba7422: Download complete
9f0706ba7422: Pull complete
Digest: sha256:4bc62f74d246e8428be8dd3833461ba2cfd135064aed4001f3c12b87a011e30c
Status: Downloaded newer image for debian:jessie
 ---> 62a932a5c143
Step 2/12 : RUN find /usr/share/doc -depth \( -type f -o -type l \) ! -name copyright | xargs rm || true
 ---> Running in ef7872d749b5
 ---> f61e68082843
Removing intermediate container ef7872d749b5
Step 3/12 : RUN while [ -n "$(find /usr/share/doc -depth -type d -empty -print -exec rmdir {} +)" ]; do :; done
 ---> Running in dd201b291719
 ---> 7b5dea5e21a1
Removing intermediate container dd201b291719
Step 4/12 : RUN rm -rf                                      /usr/share/man/*                        /usr/share/groff/*                      /usr/share/info/*                       /usr/share/lintian/*                    /usr/share/linda/*                      /var/cache/man/*                        /usr/share/locale/*
 ---> Running in 0d92e380620c
 ---> 05c458f4e4a4
Removing intermediate container 0d92e380620c
Step 5/12 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 44b6e3694f34
 ---> 246b54e1f547
Removing intermediate container 44b6e3694f34
Step 6/12 : COPY sources.list /etc/apt/sources.list
 ---> c47d9da3ab9a
Removing intermediate container ce85b8101dd7
Step 7/12 : COPY dpkg_01_drop /etc/dpkg/dpkg.cfg.d/01_drop
 ---> 879658dce237
Removing intermediate container ff7528ab34f2
Step 8/12 : RUN apt-get clean && apt-get update
 ---> Running in 1b5d0904378f
E: Could not open lock file /var/cache/apt/archives/lock - open (2: No such file or directory)
E: Unable to lock the download directory
The command '/bin/sh -c apt-get clean && apt-get update' returned a non-zero code: 100
slave.mk:298: recipe for target 'target/docker-base.gz' failed
make: *** [target/docker-base.gz] Error 1
make: Leaving directory '/sonic'
make: *** [target/sonic-broadcom.bin] Error 2

I didn't change the code/repo and it looked like the build scripts pulled something that was not compatible with the old repo?

**Comment by zhenggen-xu** [comment]
tried rebuild the slave docker etc didn't help.

**Comment by ehocchen** [comment]
come up the same problem. Create the missing file can fix my problem. See https://github.com/silvio/docker-matrix/issues/32

**Comment by lguohan** [comment]
refer to this issue. https://github.com/Azure/sonic-buildimage/pull/685

close this issue as it is resolved.
