### ISSUE TITLE
Invalid file name in windows, having ':' charactor.

### ISSUE THREAD

**Issue by liushilongbuaa** [Azure/sonic-buildimage#7420]
#### Steps to reproduce the issue:
1. run 'git pull' in windows on the branch which tracking master branch.
2.
3.

#### Describe the results you received:
error: invalid path 'src/sonic-host-services/tests/hostcfgd/sample_output/RADIUS/10.1
0.10.1:1645.conf'

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anshuv-mfst** [comment]
@adam-yeung - could you please take a look, thanks.

**Comment by adyeung** [comment]
@adyeung

**Comment by a-barboza** [comment]
@liushilongbuaa @renukamanavalan 

I think the windows filesystem cannot handle the ":" in the filename. Can you confirm? If so, I can put in a PR to take out the ":" from the Unit Tests.

`C:\>type 10.10.10.1:1645.conf
The filename, directory name, or volume label syntax is incorrect.

C:\>type 10.10.10.1.conf
The system cannot find the file specified.

C:\>`

**Comment by liushilongbuaa** [comment]
A file name can't contain any of the following characters:  \ / : * ? " < > |
