### ISSUE TITLE
[sflow] | sflow restart required to update interface sampling rate

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#7444]
#### Description

sflow disable/enable required to update sampling rate when interface speed changes

#### Steps to reproduce the issue:

```
sonic# config interface speed Ethernet8 100000
sonic# config sflow enable 
sonic# show sflow interface | grep Ethernet8
| Ethernet8   | up            | 100000          |
sonic# config interface speed Ethernet8 400000
sonic# show sflow interface | grep Ethernet8
| Ethernet8   | up            | 100000          |              <== 400000 is expected
sonic# config sflow disable 
sonic# config sflow enable 
sonic# show sflow interface | grep Ethernet8
| Ethernet8   | up            | 400000          |
sonic# 
````

#### Describe the results you received:

sflow restart required to update sampling rate when interface speed changes

#### Describe the results you expected:

sflow sampling rate updated without service restart

#### Output of `show version`:

```
SONiC Software Version: SONiC.SONIC.202012.65-5bdbfcf_Internal
Distribution: Debian 10.9
Kernel: 4.19.0-12-2-amd64
Build commit: 5bdbfcfb
Build date: Fri Apr 16 07:25:51 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02

Platform: x86_64-mlnx_msn4700-r0
HwSKU: ACS-MSN4700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2007X06834
Uptime: 06:55:07 up 1 min,  2 users,  load average: 0.29, 0.17, 0.07
```

#### Output of `show techsupport`:

[sonic_dump_r-qa-sw-eth-2044_20210420_205552.tar.gz](https://github.com/Azure/sonic-buildimage/files/6382412/sonic_dump_r-qa-sw-eth-2044_20210420_205552.tar.gz)

**Comment by dgsudharsan** [comment]
This issue is fixed by the PR https://github.com/Azure/sonic-swss/pull/1721

**Comment by Hedgehog-Guru** [comment]
Checked in SONiC.202012.79-6060da3a_Internal
Thanks!
