### ISSUE TITLE
BGP fails to restore route table before reconciliation in warm reboot

### ISSUE THREAD

**Issue by shi-su** [Azure/sonic-buildimage#7488]
#### Steps to reproduce the issue:
1. Run continuous warm-reboot test on kvm
2. The warm-reboot fails in 1 out of 20 warm-reboots
3. An example failure https://dev.azure.com/mssonic/build/_build/results?buildId=12439&view=logs&j=917c1508-19c3-53d5-10ca-59367f40e278&t=82841ee8-7d01-5dbd-2843-d8193599bb85

#### Describe the results you received:
BGP fails to restore route table before reconciliation in warm reboot. The reconciliation process removes all routes including the default route. The route table gets restores tens of seconds after reconciliation.

Note: this issue is seen on KVM, whether it happens on other platforms has not yet been confirmed.

#### Describe the results you expected:
Route table restores before reconciliation. The reconciliation process does not remove any routes.

#### Output of `show version`:
The latest master image.
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by shi-su** [comment]
It seems that one of the peers gets updated late (after reconciliation). Here is an example with logs below: 10.0.0.59 gets updated after the reconciliation. It seems that there is some bgp configuration that prevents any routes that do not point to the whole pre-defined peer-group (10.0.0.57, 10.0.0.59, 10.0.0.61, 10.0.0.63). Therefore, without 10.0.0.59 getting updated, all ipv4 routes would not be added and the default route would have packet action as drop.

syslog
```
Apr 24 08:13:19.999392 vlab-01 NOTICE bgp#fpmsyncd: :- main: Warm-Restart timer expired.
Apr 24 08:13:20.001535 vlab-01 NOTICE bgp#fpmsyncd: :- reconcile: Warm-Restart: Initiating reconciliation process for bgp application.
Apr 24 08:13:20.002001 vlab-01 NOTICE bgp#fpmsyncd: :- reconcile: Warm-Restart reconciliation: deleting stale entry 192.184.192.0/25 { nexthop: 10.0.0.57,10.0.0.59,10.0.0.61,10.0.0.63 | ifname: PortChannel0001,PortChannel0002,PortChannel0003,PortChannel0004 } 
Apr 24 08:13:20.003092 vlab-01 NOTICE bgp#fpmsyncd: :- reconcile: Warm-Restart reconciliation: deleting stale entry 192.228.144.128/25 { nexthop: 10.0.0.57,10.0.0.59,10.0.0.61,10.0.0.63 | ifname: PortChannel0001,PortChannel0002,PortChannel0003,PortChannel0004 } 
...
Apr 24 08:13:20.012138 vlab-01 NOTICE bgp#fpmsyncd: :- reconcile: Warm-Restart reconciliation: deleting stale entry 0.0.0.0/0 { nexthop: 10.0.0.57,10.0.0.59,10.0.0.61,10.0.0.63 | ifname: PortChannel0001,PortChannel0002,PortChannel0003,PortChannel0004 } 
...
```
bgpd.log
```
Apr 24 08:12:31.737072 vlab-01 INFO bgp#bgpd[55]: %ADJCHANGE: neighbor 10.0.0.61(Unknown) in vrf default Up
Apr 24 08:12:33.343009 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv6 Unicast from fc00::72 in vrf default
Apr 24 08:12:33.390097 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.0.63 in vrf default
Apr 24 08:12:33.698307 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv6 Unicast from fc00::7a in vrf default
Apr 24 08:12:34.069738 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv6 Unicast from fc00::7e in vrf default
Apr 24 08:12:36.683955 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv6 Unicast from fc00::76 in vrf default
Apr 24 08:12:38.927587 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.0.57 in vrf default
Apr 24 08:12:40.327171 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.0.61 in vrf default
Apr 24 08:14:20.136259 vlab-01 INFO bgp#bgpd[55]: bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.0.59 in vrf default
```
zebra.log
```
Apr 24 08:14:20.000664 vlab-01 WARNING bgp#staticd[54]: route_notify_owner: Route 0.0.0.0/0 over-ridden by better route for table: 254
```

**Comment by yxieca** [comment]
Is this issue caused by bgp didn't get enough CPU cycles to work with peer?

What is the likelihood of this happening on a physical DUT?

**Comment by shi-su** [comment]
Attaching logs from a failed test
[swss.rec.txt](https://github.com/Azure/sonic-buildimage/files/6423382/swss.rec.txt)
[syslog.1.txt](https://github.com/Azure/sonic-buildimage/files/6423383/syslog.1.txt)
[syslog.txt](https://github.com/Azure/sonic-buildimage/files/6423384/syslog.txt)
[zebra.log.txt](https://github.com/Azure/sonic-buildimage/files/6423385/zebra.log.txt)
[bgpd.log.txt](https://github.com/Azure/sonic-buildimage/files/6423386/bgpd.log.txt)
[sairedis.rec.txt](https://github.com/Azure/sonic-buildimage/files/6423387/sairedis.rec.txt)





.

**Comment by zhenggen-xu** [comment]
What is your FRR configuration?

Do we have “bgp graceful-restart select-defer-time” configured? If not, then it is expected we will wait for all peers End-of-RIB to do route selection.
The question is, why we don’t get End-of-RIB for one peer before the reconciliation timeout (120 seconds)?  This is the time cover from when BGP daemon is up and to get EoR.  This seems to be extremely long already in case of typical DC routes scale. 
 
There was a reconnect timer that is important, by default is 120 seconds, you should set to lower like 10 seconds:
neighbor V4 timers connect 10
 
I suspect this is the issue.
