### ISSUE TITLE
Please re-enable buildimage-brcm-all and buildimage-brcm-202012

### ISSUE THREAD

**Issue by ymc-dabe** [Azure/sonic-buildimage#7506]
#### Description
It looks like the jenkins jobs [buildimage-brcm-all](https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/) and [buildimage-brcm-202012](https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-202012/) were disabled end of April. Thus no new builds are run for branches `master` and `202012` for the broadcom platform.

#### Steps to reproduce the issue:
* Open a browser and visit [buildimage-brcm-all](https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/) and/or [buildimage-brcm-202012](https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-202012/) 

#### Describe the results you received:
* You will see a note: `This project is currently disabled`

#### Describe the results you expected:
A recent (hopefully successful) nightly build, instead of the `This project is currently disabled`-note

#### Output of `show version`:
_None_

#### Output of `show techsupport`:
_None_

#### Additional information you deem important (e.g. issue happens only occasionally):
Thanks a lot in advance for re-enabling those builds in jenkins!

**Comment by lguohan** [comment]
you can find them in azure pipeline. public jenkins is going to be deprecated.

https://dev.azure.com/mssonic/build/_build?definitionId=138

**Comment by ymc-dabe** [comment]
Thanks a lot for the link, @lguohan. That explains, why the jobs on Jenkins are disabled...
