### ISSUE TITLE
How to I test port_config.ini?

### ISSUE THREAD

**Issue by YaoTien** [Azure/sonic-buildimage#751]
Hi,
How to I test port_config.ini?
And what is Ethernet interface to do?
Thanks.

**Comment by stcheng** [comment]
what do you mean by 'testing'?
The `Ethernet` is the prefix used in SONiC for front panel ports' host interface names.

**Comment by YaoTien** [comment]
I had been modified the port_config.ini.
But I can't see any EthernetX interface by ifconfig command when system bootup.
As my knowledge,  I think EthernetX are linked to ASIC lane and application traffic should be transmission from EthernetX.
So I think EthernetX will be bring up when system started, and EthernetX's tx/rx increase when traffic is transmitting.
Am I correct?
Thanks.

**Comment by stcheng** [comment]
once orchagent starts, it will query the lane mappings via SAI and this information will be available in the syslog. Check https://github.com/Azure/sonic-swss/blob/master/orchagent/portsorch.cpp#L106. Use the information here to match the `port_config.ini` file and see if the EthernetX are correctly matched with right lane combinations.
