### ISSUE TITLE
bgp neighbors doesnt come up with vlan subinterface and bgp neighbor config

### ISSUE THREAD

**Issue by vikneels** [Azure/sonic-buildimage#7531]
#### Description
When I try to configure BGP neighbor with vlan sub interface, I dont see running config reflecting the same and show ip bgp summary doesnt show neighbor. The following is on vswitch . Added the below on config_db.json. 

#### Steps to reproduce the issue:
1. Bring up image
2. configure vlan subintf and bgp neighbor
3.

#### Describe the results you received:
   "VLAN_SUB_INTERFACE": {
        "Ethernet16.1": {
            "admin_status": "up"
        },
        "Ethernet16.1|192.168.1.2/24": {}
    },
    "BGP_NEIGHBOR": {
        "192.168.1.1": {
            "rrclient": "0",
            "name": "to_tgen",
            "local_addr": "192.168.1.2",
            "nhopself": "0",
            "holdtime": "180",
            "asn": "200",
            "keepalive": "60",
            "admin_status": "up"
        },

After config reload, dint see the entry on the show running o/p and not on bgp summary as well.

However, I could configure the same via frr. 

sonic(config)# neighbor 192.168.1.1 activ^C      
sonic(config)# router bgp ^C
sonic(config)# router bgp 65100
sonic(config-router)# neighbor 192.168.1.1 remote-as 200
sonic(config-router)# address-family ipv4 unicast                 
sonic(config-router-af)# neighbor 192.168.1.1 activate 
sonic(config-router-af)# exit-address-family 
sonic(config-router)# exit 
sonic# show running-config 
Building configuration...

After this, I could see the output on show running config as well as show ip bgp summ
 neighbor 192.168.1.1 remote-as 200

root@sonic:/home/admin# show ip bgp summary

IPv4 Unicast Summary:
BGP router identifier 10.1.0.1, local AS number 65100 vrf-id 0
BGP table version 4
RIB entries 3, using 576 bytes of memory
Peers 32, using 698112 KiB of memory
Peer groups 2, using 128 bytes of memory

Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.3       4  65200          0          0         0      0       0  never      Active          ARISTA02T2
10.0.0.5       4  65200          0          0         0      0       0  never      Active          ARISTA03T2
10.0.0.7       4  65200          0          0         0      0       0  never      Active          ARISTA04T2
10.0.0.9       4  65200          0          0         0      0       0  never      Active          ARISTA05T2
10.0.0.11      4  65200          0          0         0      0       0  never      Active          ARISTA06T2
10.0.0.13      4  65200          0          0         0      0       0  never      Active          ARISTA07T2
10.0.0.15      4  65200          0          0         0      0       0  never      Active          ARISTA08T2
10.0.0.17      4  65200          0          0         0      0       0  never      Active          ARISTA09T2
10.0.0.19      4  65200          0          0         0      0       0  never      Active          ARISTA10T2
10.0.0.21      4  65200          0          0         0      0       0  never      Active          ARISTA11T2
10.0.0.23      4  65200          0          0         0      0       0  never      Active          ARISTA12T2
10.0.0.25      4  65200          0          0         0      0       0  never      Active          ARISTA13T2
10.0.0.27      4  65200          0          0         0      0       0  never      Active          ARISTA14T2
10.0.0.29      4  65200          0          0         0      0       0  never      Active          ARISTA15T2
10.0.0.31      4  65200          0          0         0      0       0  never      Active          ARISTA16T2
10.0.0.33      4  64001          0          0         0      0       0  never      Active          ARISTA01T0
10.0.0.35      4  64002          0          0         0      0       0  never      Active          ARISTA02T0
10.0.0.37      4  64003          0          0         0      0       0  never      Active          ARISTA03T0
10.0.0.39      4  64004          0          0         0      0       0  never      Active          ARISTA04T0
10.0.0.41      4  64005          0          0         0      0       0  never      Active          ARISTA05T0
10.0.0.43      4  64006          0          0         0      0       0  never      Active          ARISTA06T0
10.0.0.45      4  64007          0          0         0      0       0  never      Active          ARISTA07T0
10.0.0.47      4  64008          0          0         0      0       0  never      Active          ARISTA08T0
10.0.0.49      4  64009          0          0         0      0       0  never      Active          ARISTA09T0
10.0.0.51      4  64010          0          0         0      0       0  never      Active          ARISTA10T0
10.0.0.53      4  64011          0          0         0      0       0  never      Active          ARISTA11T0
10.0.0.55      4  64012          0          0         0      0       0  never      Active          ARISTA12T0
10.0.0.57      4  64013          0          0         0      0       0  never      Active          ARISTA13T0
10.0.0.59      4  64014          0          0         0      0       0  never      Active          ARISTA14T0
10.0.0.61      4  64015          0          0         0      0       0  never      Active          ARISTA15T0
10.0.0.63      4  64016          0          0         0      0       0  never      Active          ARISTA16T0
192.168.1.1    4    200          0          0         0      0       0  never      Active          to_tgen

Total number of neighbors 32

sroot@sonic:/home/admin# show version

SONiC Software Version: SONiC.master.655-72ca4d74
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 72ca4d74
Build date: Fri Feb 12 11:24:43 UTC 2021
Built by: johnar@worker-sae8690

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: 000000
Uptime: 20:59:12 up 3 days, 18:59,  1 user,  load average: 0.04, 0.48, 0.73

**Comment by prsunny** [comment]
Could you please add a DEVICE_NEIGHBOR_METADATA entry for `"name": "to_tgen",` and retry the config? . Also share the bpgcfgd logs if its still failing!
@neethajohn for viz

**Comment by vikneels** [comment]
Sure, Thanks for taking a look. I Will try out and update the same.

**Comment by anshuv-mfst** [comment]
@neethajohn - could you please take a look, thanks.
