### ISSUE TITLE
[201911] PortChannel IP addresses are lost after 'config reload'

### ISSUE THREAD

**Issue by shlomibitton** [Azure/sonic-buildimage#7591]
#### Description
After running 'config reload', the assigned IP addresses on LAG interfaces are lost.

#### Steps to reproduce the issue:
1. Install a fresh image based on 201911 branch.
2. Configure PortChannels on the switch.
3. Run 'config reload' command and observe IP address is missing.

#### Describe the results you received:
In the log we can see an ERROR for assigning the IP to the PortChannel from intfmgrd:

**Apr 22 15:31:25.304056 t1s9015-d INFO swss#supervisord: intfmgrd RTNETLINK answers: File exists
Apr 22 15:31:25.304756 t1s9015-d ERR swss#intfmgrd: :- setIntfIp: Command ‘/sbin/ip address “add” “10.210.1.57/31” dev “PortChannel9”’ failed with rc 2**

This means the de-init flow didn't remove the ip address of the PortChannel from the kernel.
Starting the flow again will recreate the LAG interfaces and update STATE DB to return 'true' for 'isIntfStateOk(alias)' and then run 'setIntfIp(alias, "add", ip_prefix)' which failing because the IP is already configured on the kernel.
Eventually this IP will be deleted by another process I am not sure which one, but the IP address is missing and the PortChannel exist.
To prove this claim, I stopped all services manually without starting them again and the IP addresses configured to some PortChannels were still exist.
To stop the services related to LAGS I issued "systemctl stop swss.service" which will stop 'teamd.service' as well as it is a dependent service.

**After stopping the services:**

root@Spine4700-5:/home/admin# docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                       PORTS               NAMES
25e1bdb4a417        docker-snmp-sv2:latest               "/usr/bin/supervisord"   10 minutes ago      Exited (137) 6 minutes ago                       snmp
2d6ec9fff300        docker-sonic-mgmt-framework:latest   "/usr/bin/supervisord"   10 minutes ago      Exited (0) 6 minutes ago                         mgmt-framework
7ee5967b3f8f        docker-sonic-telemetry:latest        "/usr/bin/supervisord"   10 minutes ago      Exited (0) 6 minutes ago                         telemetry
ca7cb7a27cf9        docker-platform-monitor:latest       "/usr/bin/docker_ini…"   13 minutes ago      Exited (0) 5 minutes ago                         pmon
ff427570950e        docker-dhcp-relay:latest             "/usr/bin/docker_ini…"   13 minutes ago      Exited (0) 5 minutes ago                         dhcp_relay
55eeb8cfd1a9        docker-router-advertiser:latest      "/usr/bin/docker-ini…"   13 minutes ago      Exited (0) 5 minutes ago                         radv
d47b0a58a493        docker-lldp-sv2:latest               "/usr/bin/docker-lld…"   13 minutes ago      Up 10 minutes                                    lldp
3a807715a8ed        docker-syncd-mlnx:latest             "/usr/bin/supervisord"   13 minutes ago      Exited (0) 5 minutes ago                         syncd
58416e6f5b4a        docker-teamd:latest                  "/usr/bin/supervisord"   13 minutes ago      Exited (0) 5 minutes ago                         teamd
e7b9495252e0        docker-orchagent:latest              "/usr/bin/docker-ini…"   13 minutes ago      Exited (0) 6 minutes ago                         swss
5d14bea8a0ac        docker-fpm-frr:latest                "/usr/bin/supervisord"   14 minutes ago      Up 10 minutes                                    bgp
0b4ead33d921        docker-database:latest               "/usr/local/bin/dock…"   14 minutes ago      Up 14 minutes                                    database

root@Spine4700-5:/home/admin# ifconfig
Bridge: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::fc6b:25ff:fe3c:5177  prefixlen 64  scopeid 0x20<link>
        ether 7e:b0:bb:84:e6:5d  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 260 (260.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**PortChannel8**: flags=4099<UP,BROADCAST,MULTICAST>  mtu 9178
        inet 10.210.2.203  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 2001:558:1b0:8182::2cb  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**PortChannel9**: flags=4099<UP,BROADCAST,MULTICAST>  mtu 9178
        inet 10.210.3.9  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 2001:558:1b0:8182::309  prefixlen 127  scopeid 0x0<global>
        inet6 2001:558:1b0:8182::309  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**PortChannel73**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.112  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        inet6 2001:558:1b0:8182::1170  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 63  bytes 4086 (3.9 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 31  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 13 overruns 0  carrier 0  collisions 0

**PortChannel74**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.114  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        inet6 2001:558:1b0:8182::1172  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 63  bytes 3978 (3.8 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 31  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 9 overruns 0  carrier 0  collisions 0

**PortChannel75**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.116  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        inet6 2001:558:1b0:8182::1174  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 58  bytes 3748 (3.6 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 24  bytes 1748 (1.7 KiB)
        TX errors 0  dropped 16 overruns 0  carrier 0  collisions 0

**PortChannel76**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.118  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 2001:558:1b0:8182::1176  prefixlen 127  scopeid 0x0<global>
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 60  bytes 3840 (3.7 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 31  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 9 overruns 0  carrier 0  collisions 0

**PortChannel77**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.120  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 2001:558:1b0:8182::1178  prefixlen 127  scopeid 0x0<global>
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 62  bytes 4040 (3.9 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 31  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 11 overruns 0  carrier 0  collisions 0

**PortChannel78**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.122  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        inet6 2001:558:1b0:8182::117a  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 60  bytes 3840 (3.7 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 31  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 9 overruns 0  carrier 0  collisions 0

**PortChannel79**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.124  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        inet6 2001:558:1b0:8182::117c  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 60  bytes 3840 (3.7 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 31  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 9 overruns 0  carrier 0  collisions 0

**PortChannel80**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9178
        inet 10.210.17.126  netmask 255.255.255.254  broadcast 0.0.0.0
        inet6 fe80::1eaa:aaff:feaa:aa00  prefixlen 64  scopeid 0x20<link>
        inet6 2001:558:1b0:8182::117e  prefixlen 127  scopeid 0x0<global>
        ether 1c:aa:aa:aa:aa:00  txqueuelen 1000  (Ethernet)
        RX packets 60  bytes 3840 (3.7 KiB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 31  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 9 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 240.127.1.1  netmask 255.255.255.0  broadcast 240.127.1.255
        inet6 fe80::1  prefixlen 64  scopeid 0x20<link>
        inet6 fd00::1  prefixlen 80  scopeid 0x0<global>
        ether 02:42:fd:5b:f9:9c  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 11.11.11.105  netmask 255.255.255.0  broadcast 11.11.11.255
        inet6 fe80::e42:a1ff:fecf:417a  prefixlen 64  scopeid 0x20<link>
        ether 0c:42:a1:cf:41:7a  txqueuelen 1000  (Ethernet)
        RX packets 3399  bytes 407357 (397.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 275865  bytes 44155824 (42.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xf8100000-f81fffff

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 469163  bytes 70773004 (67.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 469163  bytes 70773004 (67.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

#### Describe the results you expected:
All IP addresses should be assigned successfully and noe ERR messages should be raised.

#### Output of `show techsupport`:
[sonic_dump_Spine4700-5_20210429_145731.zip](https://github.com/Azure/sonic-buildimage/files/6465852/sonic_dump_Spine4700-5_20210429_145731.zip)

#### Additional information you deem important (e.g. issue happens only occasionally):
This issue is not reproduced ~20% of the time which indicate some race condition between processes.

**Comment by anshuv-mfst** [comment]
Issue triage Meeting 5/12: 
- Issue occurs when there are many port channels (~80)
- Might be dup of  https://github.com/Azure/sonic-buildimage/issues/6503

**Comment by anshuv-mfst** [comment]
@judyjoseph - could you please take a look, thanks.

**Comment by judyjoseph** [comment]
Thanks @nazariig - Fixed in 201911 via PR #7662
