### ISSUE TITLE
[multi-asic][swsscommon] Instance specific config load is not happening in correct database server instance

### ISSUE THREAD

**Issue by vganesan-nokia** [Azure/sonic-buildimage#7595]
#### Description

In multi-asic implementation, configuration load from conifg_db\<instance number\>.json is not happening in redis server of correct instance. All configs are loaded in the global redis server only.

#### Steps to reproduce the issue:
1. In multi-asic system with say 3 asics, have config_db0.json, config_db1.json and config_db2.json in /etc/sonic directory. Let these configuration files have distinct configuration so that we can confirm reproduction of this issue
2. Reboot the system
3. After the systems comes up and operational, dump the config db of asic0, asic1 and asic2 instances. (i.e., dump the config_db of redis from database0 and database1 and database2 containers respectively)

#### Describe the results you received:
- The config dbs of name spaces asic0, asic1 and asic2 do not have information provided in their respective config_db\<instance number\>.json files.

#### Describe the results you expected:
The configuration from config_db0.json, config_db1.json and config_db2.json should be available in redis databases from database0, database1 and database2 containers respectively

#### Additional information you deem important (e.g. issue happens only occasionally):
- It appears that all the instance specific configs are loaded in the global database. This is because transition from C++ constructor to python in SWIG code misses passing namespace to sonicv2connector since the namespace is avaiable in kwargs. A possible fix is extracting the namespace from kwargs and setting to namespace (in SWIG python insert of  class SonicV2Connector(SonicV2Connector_Native))

**Comment by anshuv-mfst** [comment]
@abdosi - could you please take a look, thanks.

**Comment by judyjoseph** [comment]
@vganesan-nokia, are you still seeing this issue ? I see that a probable fix (https://github.com/Azure/sonic-swss-common/pull/470/files) would have gone in already and the sonic-swsscommon submodule is updated here in buildimage as well.

**Comment by vganesan-nokia** [comment]
> @vganesan-nokia, are you still seeing this issue ? I see that a probable fix (https://github.com/Azure/sonic-swss-common/pull/470/files) would have gone in already and the sonic-swsscommon submodule is updated here in buildimage as well.

With this fix, I do not see this issue anymore. Thanks

**Comment by judyjoseph** [comment]
Thanks, Closing this as it is fixed with this commit https://github.com/Azure/sonic-swss-common/pull/470
