### ISSUE TITLE
"ip vrf exec" does not work

### ISSUE THREAD

**Issue by irene-pan1202** [Azure/sonic-buildimage#7745]
#### Description

ip vrf exec command is not work in 202012. It seems to always specify the default vrf. Add "cgroup_no_v1=net_prio,net_cls" to /host/grub/grub.cfg will make this problem go away. But I don’t know whether disabling cgroup v1 net_cls, net_prio will cause other effects?

#### Steps to reproduce the issue:
1. config vrf add mgmt
2. ip vrf exec mgmt ping 10.250.0.196
3.

#### Describe the results you received:
admin@as7816-64x-3:~$ sudo ip vrf exec mgmt ping 10.250.0.196
connect: Network is unreachable

admin@as7816-64x-3:~$ ping -I mgmt 10.250.0.196
ping: Warning: source address might be selected on device other than mgmt.
PING 10.250.0.196 (10.250.0.196) from 10.250.0.183 mgmt: 56(84) bytes of data.
64 bytes from 10.250.0.196: icmp_seq=1 ttl=64 time=0.404 ms
^C
--- 10.250.0.196 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.404/0.404/0.404/0.000 ms

#### Output of `show version`:

```
Distribution: Debian 10.9
Kernel: 4.19.0-12-2-amd64
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by venkatmahalingam** [comment]
I don’t know whether disabling cgroup v1 net_cls, net_prio will cause other effects?
Please refer the below issue for more information.
https://github.com/Azure/sonic-linux-kernel/pull/198

**Comment by venkatmahalingam** [comment]
As some utilities in the system, like ip vrf, use cgroup2, there is necessity to disable net_prio, net_cls to ensure that those utilities will work correct.

**Comment by venkatmahalingam** [comment]
Please close this issue.

**Comment by irene-pan1202** [comment]
Refer to Azure/sonic-linux-kernel#198
