### ISSUE TITLE
Orchagent exit after configuring incorrect advertised interface type value

### ISSUE THREAD

**Issue by Junchao-Mellanox** [Azure/sonic-buildimage#7768]
#### Description

Orchagent exit after configuring incorrect advertised interface type value. But it seems that this is by design, see https://github.com/Azure/sonic-swss/pull/1665. In the PR, it introduces a new way to handle SAI return value.

```cpp
task_process_status Orch::handleSaiSetStatus(sai_api_t api, sai_status_t status, void *context)
{
    /*
     * This function aims to provide coarse handling of failures in sairedis set
     * operation (i.e., notify users by throwing excepions when failures happen).
     * Return value: task_success - Handled the status successfully. No need to retry this SAI operation.
     *               task_need_retry - Cannot handle the status. Need to retry the SAI operation.
     *               task_failed - Failed to handle the status but another attempt is unlikely to resolve the failure.
     * TODO: 1. Add general handling logic for specific statuses
     *       2. Develop fine-grain failure handling mechanisms and replace this coarse handling
     *          in each orch.
     *       3. Take the type of sai api into consideration.
     */
    switch (status)
    {
        case SAI_STATUS_SUCCESS:
            SWSS_LOG_WARN("SAI_STATUS_SUCCESS is not expected in handleSaiSetStatus");
            return task_success;
        default:
            SWSS_LOG_ERROR("Encountered failure in set operation, exiting orchagent, SAI API: %s, status: %s",
                        sai_serialize_api(api).c_str(), sai_serialize_status(status).c_str());
            exit(EXIT_FAILURE);
    }
    return task_need_retry;
}
```

It just exit if the SAI return value is not SAI_STATUS_SUCCESS. To me, it looks like too strict. In my case, I configured port  adv_speeds=100G, adv_interface_types=CR (correct value should be CR4), SAI returned  and orchagent just exited. Maybe we should provide a way for user to correct his/her configuration? Or is there a known better way to handle such case?

Related log:
```
Jun  1 03:35:22.172518 r-leopard-41 ERR swss#orchagent: :- set: set status: SAI_STATUS_INVALID_ATTR_VALUE_0
Jun  1 03:35:22.172518 r-leopard-41 ERR swss#orchagent: :- handleSaiSetStatus: Encountered failure in set operation, exiting orchagent, SAI API: SAI_API_PORT, status: SAI_STATUS_INVALID_ATTR_VALUE_0
```

#### Steps to reproduce the issue:
1. config interface autoneg Ethernet0 enabled
2. config interface advertised-speeds Ethernet0 100000
3. config interface advertised-types Ethernet0 CR

#### Describe the results you received:

Orchagent exited.

#### Describe the results you expected:

Orchagent should not exit.

#### Output of `show version`:

Master branch hash 6616c1bac
```
(paste your output here)
```
#### Output of `show techsupport`:

N/A
```
(paste your output here or download and attach the file here )
```

**Comment by Junchao-Mellanox** [comment]
@qiluo-msft @shi-su Much appreciate if you could take a look.

**Comment by qiluo-msft** [comment]
Thanks Junchao for the bug report!
@shi-su Could you check and improve?

**Comment by shi-su** [comment]
> Thanks Junchao for the bug report!
> @shi-su Could you check and improve?

Ack. I will take a look.

**Comment by Junchao-Mellanox** [comment]
A WA for this issue: https://github.com/Azure/sonic-swss/pull/1906

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox and @shi-su is this issue still relevant? if so, @shi-su could you please update?

**Comment by prsunny** [comment]
looks like its fixed as part of https://github.com/Azure/sonic-swss/pull/1906. @Junchao-Mellanox , can you please close this issue?
