### ISSUE TITLE
Building on Ubuntu ARM fails

### ISSUE THREAD

**Issue by ncalad** [Azure/sonic-buildimage#7780]
I stood up an Amazon EC2 ARM Ubuntu 20.04 instance but SONiC won't build.

#### Steps to reproduce the issue:
1. Stand up ARM 64-bit running Ubuntu 20.04
2. Install Docker using debs for ARM
3. git clone from repo
4. make init
5. make configure PLATFORM=broadcom

#### Describe the results you received:

non-zero code: 100
Unable to find image 'sonic-slave-stretch:a99c9f3c1b0' locally
Error response from daemon: pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: No such container:path: sonic-slave-stretch:/etc/os-release
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/pre-versions
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/post-versions
Error: No such container: sonic-slave-stretch
Image sonic-slave-stretch-ubuntu:568203f5d76 not found. Building...
Sending build context to Docker daemon  46.59kB
Step 1/18 : ARG slave_base_tag_ref=latest
Step 2/18 : FROM sonic-slave-stretch:${slave_base_tag_ref}
pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Unable to find image 'sonic-slave-stretch-ubuntu:568203f5d76' locally
docker: Error response from daemon: pull access denied for sonic-slave-stretch-ubuntu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make[1]: *** [Makefile.work:291: configure] Error 125
make[1]: Leaving directory '/home/ubuntu/OpenGear/sonic/sonic-buildimage'
make: *** [Makefile:34: configure] Error 2

**Comment by lguohan** [comment]
are you trying to build a broadcom image on arm64? afaik, this is not supported.

**Comment by ncalad** [comment]
OK ...thank you.
