### ISSUE TITLE
distrubition upgrade error !!

### ISSUE THREAD

**Issue by aymen09** [Azure/sonic-buildimage#780]
:/# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  adduser apt apt-utils base-files base-passwd bash bash-completion
  bsdmainutils bsdutils coreutils dash debconf debconf-i18n
  debian-archive-keyring debianutils diffutils dirmngr dpkg e2fslibs e2fsprogs
  findutils gcc-7-base gnupg gnupg-agent gnupg-l10n gpgv grep gzip hostname
  init-system-helpers libacl1 libapt-inst2.0 libapt-pkg5.0 libassuan0 libattr1
  libaudit-common libaudit1 libblkid1 libbsd0 libbz2-1.0 libc-bin libc6
  libcap-ng0 libcomerr2 libdb5.3 libdebconfclient0 libfdisk1 libffi6 libgcc1
  libgcrypt20 libgmp10 libgnutls30 libgpg-error0 libgpm2 libhogweed4 libidn2-0
  libksba8 libldap-2.4-2 libldap-common liblocale-gettext-perl liblz4-1
  liblzma5 libmount1 libncurses5 libncursesw5 libnettle6 libnpth0 libp11-kit0
  libpam-modules libpam-modules-bin libpam-runtime libpam0g libpcre3
  libreadline7 libsasl2-2 libsasl2-modules libsasl2-modules-db libselinux1
  libsemanage-common libsemanage1 libsepol1 libsmartcols1 libsqlite3-0 libss2
  libssl1.1 libstdc++6 libsystemd0 libtasn1-6 libtext-charwidth-perl
  libtext-iconv-perl libtext-wrapi18n-perl libtinfo5 libudev1 libunistring0
  libustr-1.0-1 libuuid1 login lsb-base manpages mawk mount multiarch-support
  ncurses-base ncurses-bin passwd perl-base pinentry-curses readline-common
  sed sensible-utils sysvinit-utils tar util-linux uuid-runtime zlib1g
0 upgraded, 115 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/39.7 MB of archives.
After this operation, 129 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
E: Cannot get debconf version. Is debconf installed?
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 26%E: Cannot get debconf version. Is debconf installed?
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 52%E: Cannot get debconf version. Is debconf installed?
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 78%E: Cannot get debconf version. Is debconf installed?
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 100%
dpkg: error: cannot scan updates directory '/var/lib/dpkg/updates/': No such file or directory
dpkg-query: error: cannot scan updates directory '/var/lib/dpkg/updates/': No such file or directory
update-kali-menu: error: dpkg-query gave error exit status 2
E: Sub-process /usr/bin/dpkg returned an error code (2)
E: Problem executing scripts DPkg::Post-Invoke '[ ! -x /usr/share/kali-menu/update-kali-menu ] || /usr/share/kali-menu/update-kali-menu wait_dpkg'
E: Sub-process returned an error code

**Comment by lguohan** [comment]
what is the context here? where do we do this dist-upgrade?

**Comment by lguohan** [comment]
dist-upgrade is not supported.
