### ISSUE TITLE
Build break: marvell-armhf builds on master branch appear to be broken

### ISSUE THREAD

**Issue by dflynn-Nokia** [Azure/sonic-buildimage#7835]
#### Description
The master branch builds within the Azure.sonic-buildimage.official.marvell-armhf pipeline are failing.

https://dev.azure.com/mssonic/build/_build?definitionId=141&_a=summary

I suspect this is related to PR #7633 

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
let's revert first @yxieca take a look

**Comment by lguohan** [comment]
reverted.

**Comment by dflynn-Nokia** [comment]
Looking more closely at the marvell-armhf build failure

make[3]: Entering directory '/sonic/src/systemd-sonic-generator'
gcc -std=gnu99 -D_GNU_SOURCE -D_SSG_UNITTEST -o systemd-sonic-generator.o -c systemd-sonic-generator.c
g++ -std=c++11 -D_GNU_SOURCE -o ssg_test ssg-test.cc systemd-sonic-generator.o /usr/lib/x86_64-linux-gnu/libgtest.a -lpthread -lboost_filesystem -lboost_system
g++: error: **/usr/lib/x86_64-linux-gnu/libgtest.a**: No such file or directory

It seems PR# 7633 is x86_64 specific.
Can we revert?

**Comment by yxieca** [comment]
Looks like https://github.com/Azure/sonic-buildimage/pull/7831 addressed the build issue.

**Comment by dflynn-Nokia** [comment]
Yes, master branch builds are now working again.
Thanks for fixing this.
