### ISSUE TITLE
[minigraph] MAC shows as NONE in VLAN Table

### ISSUE THREAD

**Issue by tahmed-dev** [Azure/sonic-buildimage#7847]
#### Description

MAC address shows as `None` in the Vlan table when minigraph has the following property:

`<MacAddress i:nil="true"/>`

Which results in `vlanmgrd` erring and `swss` get terminated.

#### Steps to reproduce the issue:
1. load minigraph with new 202012/master image
2. observer swss crashing
3.

#### Describe the results you received:
swss crashed and switch is not useable

#### Describe the results you expected:
swss should not crash

#### Output of `show version`:
```
202012 and master
```
#### Output of `show techsupport`:

```
Not provided
```

#### Additional information you deem important (e.g. issue happens only occasionally):
The fix could be changing this [line](https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/minigraph.py#L560) to:
```
            if vlanmac is not None and vlanmac.text is not None:
```

**Comment by yxieca** [comment]
Curious how did we missed this issue in nightly tests?

**Comment by theasianpianist** [comment]
@yxieca our minigraphs that we generate in the lab to do not have null VLAN MACs
