### ISSUE TITLE
[voq] SAI support for changing encap index in voq neighbor attribute programming (set function)

### ISSUE THREAD

**Issue by vganesan-nokia** [Azure/sonic-buildimage#7879]
#### Description

For VOQ neighbors we program encap index for remote neighbor records. If the encap index is reallocated to a different encap index than previously allocated by the owner of the neighbor, at the remote side, the neighbor should be reprogrammed with changed voq encap index. Currently SAI (brcm SAI,  for example) does not support change (set) of voq encap index for existing neighbors in neighbor entry set attribute function . As a work-around we handle the encap index attribute change by deleting the existing old neighbor record and re-adding it back with new encap index. To avoid this two steps change handling, we need SAI support for voq encap index attribute setting in neighbor entry attribute programming (set operation) (similar to MAC change programming)

#### Steps to reproduce the issue:

Please refer issue https://github.com/Azure/sonic-buildimage/issues/7451 for reproducing a problem whose fix (https://github.com/Azure/sonic-swss/pull/1729) will have this double action change handling.

Also refer to BRCM SAI neighbor entry set attribute function for sample.

#### Describe the results you received:

Refer the fix for this issue in PR https://github.com/Azure/sonic-swss/pull/1729

#### Describe the results you expected:

The SAI neighbor entry set attribute API should handle voq encap index setting similar to MAC address setting

#### Additional information you deem important (e.g. issue happens only occasionally):

This issue is raised as response to a review comment to PR https://github.com/Azure/sonic-swss/pull/1729

**Comment by zhangyanzhao** [comment]
For tracking purpose. @abdosi will take care

**Comment by vganesan-nokia** [comment]
Fixed in SAI release 5.0.0.6
