### ISSUE TITLE
[voq] System lag id boundary setting in CHASSIS_APP_DB fails

### ISSUE THREAD

**Issue by vganesan-nokia** [Azure/sonic-buildimage#7912]
#### Description

In VOQ chassis systems, system lag id boundary is set in redis-chassis server immediately after starting the database-chassis container in the supervisor card. This system lad id boundary was not set correctly all the time. Intermittently there was failure in setting these values in CHASSIS_APP_DB in redis-chassis server. (Thanks to @ysmanman for pointing out this issue and suggesting a potential fix)

#### Steps to reproduce the issue:

1. Set required values for lagid_start and lagid_end in chassisdb.conf
2. Reboot chassis

#### Describe the results you received:

Sometimes, the SYSTEM_LAG_ID_START and SYSTEM_LAG_ID_END are not set correctly and there was failure in setting these values in CHASSIS_APP_DB

#### Describe the results you expected:

The variables SYSTEM_LAG_ID_START and SYSTEM_LAG_ID_END should be set to values mentioned in the chassisdb.conf consistently all the time after every reboot of the VOQ chassis.

#### Additional information you deem important (e.g. issue happens only occasionally):

The PR https://github.com/Azure/sonic-buildimage/pull/7911 has fix for this.

**Comment by zhangyanzhao** [comment]
@judyjoseph please review the PRs.

**Comment by vganesan-nokia** [comment]
Fixed by PR https://github.com/Azure/sonic-buildimage/pull/7911
