### ISSUE TITLE
[fwutil] update command reference for platform_components.json example

### ISSUE THREAD

**Issue by caizhenghui-juniper** [Azure/sonic-buildimage#7953]
#### Description

Since commit https://github.com/Azure/sonic-utilities/commit/fd7781b52d6b70d90505ca128277ce864cee7ab2#diff-dfdf5772988b97db10b1fe0354cbbe81a91f14939a9ba68091e5038990f50a13
The info field in component section is not valid anymore. But the command reference document is not updated for the change.
Example: 
                "FPGA": {
                    "firmware": "/etc/<platform_name>/fw/<onie_platform>/chassis1/fpga.bin",
                    "version": "5",
                    "info": "Power cycle is required"
                }
And in code: 
                self.__module_component_map[section][key1] = OrderedDict()

            if value1:
                **if len(value1) != 1 and len(value1) != 2:**
                    self.__parser_component_fail("unexpected number of records: key={}".format(key1))

                if self.FIRMWARE_KEY not in value1:
                    missing_key = self.FIRMWARE_KEY
                    break
                elif len(value1) == 2 and self.VERSION_KEY not in value1:
                    missing_key = self.VERSION_KEY
                    break
#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:
If we follow the example in command reference, fwutil will exit with error. 

#### Describe the results you expected:
Modify the examples in command reference doc to reflect new change.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@sujinmkang please take a look. Thanks. @nazariig

**Comment by nazariig** [comment]
@caizhenghui-juniper / @zhangyanzhao FYI: https://github.com/Azure/sonic-utilities/pull/1708
