### ISSUE TITLE
[mirroring] Missing type validations in config mirror-session command

### ISSUE THREAD

**Issue by raphaelt-nvidia** [Azure/sonic-buildimage#7990]
#### Description

Things that are not checked at CLI level in config mirror-session include:
•	Queue is a uint8
•	TTL is a uint8
•	DSCP is a unit8
•	Source and destination IPs have valid IP address format.

What all in the above paragraph have in common is that the HLD of 10/2020 prescribes Yang model validation for them.  There is currently no such validation; there is only this file https://github.com/Azure/sonic-mgmt-common/blob/86c110812583d0132d6504a1e74eb0337f521fde/cvl/testdata/schema/sonic-mirror-session.yang which Broadcom plan to update.  In the meantime, these are not checked at the CLI level, causing orchagent to log errors and the command goes no further.

Do we want to add CLI-level type validation, integrate the Yang model, or both?

#### Steps to reproduce the issue:

1. config mirror_session span add ms3 Ethernet12 Ethernet16 rx ajdh
2. config mirror_session erspan add ms6 40.0.0.1 40.0.0.2 63 256 100 4 Ethernet136 tx
3. config mirror_session erspan add ms6 40.0.0.1 40.0.0.2 64 255 100 4 Ethernet136 tx
4. config mirror_session erspan add ms7 401.0.0.1 40.0.0.2 3 10 "" "" Ethernet132 tx

#### Describe the results you received:

1. ERR swss#orchagent: :- createEntry: Failed to parse session ms3 attribute queue error: stoul.
2. ERR swss#orchagent: :- createEntry: Failed to parse session ms6 attribute ttl error: failed to convert 256 value is not in range 0 - 255.
3. ERR swss#orchagent: :- createEntry: Failed to parse session ms6 attribute dscp error: failed to convert 64 value is not in range 0 - 63.
4. ERR swss#orchagent: :- createEntry: Failed to parse session ms7 attribute src_ip error: Error converting 401.0.0.1 to IP address.

Erroneous values appear in config_DB and show.

#### Describe the results you expected:

Rejection messages at CLI level, no errors in log, and no configuration.

#### Output of `show version`:

SONiC Software Version: SONiC.202106.0-ebc962c22
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: ebc962c
Build date: Thu Jun 24 17:59:46 UTC 2021
Built by: raphaelt@r-build-sonic05

Platform: x86_64-mlnx_msn2410-r0
HwSKU: ACS-MSN2410
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1921X01546
Uptime: 13:55:39 up 2:44, 2 users, load average: 1.58, 1.65, 1.65

Docker images:
REPOSITORY TAG IMAGE ID SIZE
docker-syncd-mlnx 202106.0-ebc962c22 d00568dad081 961MB
docker-syncd-mlnx latest d00568dad081 961MB
docker-snmp 202106.0-ebc962c22 69263d7ff0ca 454MB
docker-snmp latest 69263d7ff0ca 454MB
docker-dhcp-relay 202106.0-ebc962c22 12bd15bd2785 420MB
docker-dhcp-relay latest 12bd15bd2785 420MB
docker-teamd 202106.0-ebc962c22 92f76cb0c626 424MB
docker-teamd latest 92f76cb0c626 424MB
docker-nat 202106.0-ebc962c22 36858e717963 427MB
docker-nat latest 36858e717963 427MB
docker-router-advertiser 202106.0-ebc962c22 34fc1983f5d3 413MB
docker-router-advertiser latest 34fc1983f5d3 413MB
docker-platform-monitor 202106.0-ebc962c22 74dd0063f256 738MB
docker-platform-monitor latest 74dd0063f256 738MB
docker-lldp 202106.0-ebc962c22 ce9a9e42fecd 453MB
docker-lldp latest ce9a9e42fecd 453MB
docker-macsec 202106.0-ebc962c22 89d2ebe2ddaa 427MB
docker-macsec latest 89d2ebe2ddaa 427MB
docker-database 202106.0-ebc962c22 32ce5d38e191 413MB
docker-database latest 32ce5d38e191 413MB
docker-orchagent 202106.0-ebc962c22 c6254d27f85d 442MB
docker-orchagent latest c6254d27f85d 442MB
docker-sonic-telemetry 202106.0-ebc962c22 bd04168564d8 501MB
docker-sonic-telemetry latest bd04168564d8 501MB
docker-sonic-mgmt-framework 202106.0-ebc962c22 a5ec5adee9cd 570MB
docker-sonic-mgmt-framework latest a5ec5adee9cd 570MB
docker-fpm-frr 202106.0-ebc962c22 5436d8f7e983 442MB
docker-fpm-frr latest 5436d8f7e983 442MB
docker-sflow 202106.0-ebc962c22 0d353410dcb2 425MB
docker-sflow latest 0d353410dcb2 425MB

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by raphaelt-nvidia** [comment]
Any news?

**Comment by bingwang-ms** [comment]
Acked. Will work on it shortly.

**Comment by bingwang-ms** [comment]
Issue addressed in PR https://github.com/Azure/sonic-utilities/pull/1825
