### ISSUE TITLE
[pcied] daemon is in FATAL state when system starts

### ISSUE THREAD

**Issue by DavidZagury** [Azure/sonic-buildimage#7993]
#### Description
The pcied damon does not start.
It crashes when trying to start it and enters FATAL state.

#### Steps to reproduce the issue:
1.  Load switch
2.  Enter pmon contianer
3.  Check pcied status

#### Describe the results you received:
Pcied daemon crashes when trying to start it.

#### Describe the results you expected:
Pcied daemon should load.

#### Output of `show version`:
Image based 5c503b81ae186aa378928edf36fa1d347e919d7a

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

On the log we can see:
> Jun 27 12:24:04.281007 r-leopard-41 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 48, in load_platform_pcieutil
> Jun 27 12:24:04.281070 r-leopard-41 INFO pmon#/supervisord: pcied     self.log_error("Failed to load platform Pcie module. Error : {}".format(str(e)), True)
> Jun 27 12:24:04.281070 r-leopard-41 INFO pmon#/supervisord: pcied NameError: name 'self' is not defined
> Jun 27 12:24:04.288837 r-leopard-41 INFO pmon#/supervisord: pcied Exception ignored in: <function DaemonPcied.__del__ at 0x7fb1817b9488>
> Jun 27 12:24:04.288837 r-leopard-41 INFO pmon#/supervisord: pcied Traceback (most recent call last):
> Jun 27 12:24:04.288837 r-leopard-41 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 100, in __del__
> Jun 27 12:24:04.288837 r-leopard-41 INFO pmon#/supervisord: pcied     if self.status_table:
> Jun 27 12:24:04.288837 r-leopard-41 INFO pmon#/supervisord: pcied AttributeError: 'DaemonPcied' object has no attribute 'status_table'

It started after the merge of https://github.com/Azure/sonic-platform-daemons/pull/189
This PR added in the function _load_platform_pcieutil_ on file _src/sonic-platform-daemons/sonic-pcied/scripts/pcied_ a call to _self.log_error_ which is not defined in this scoop.

The lines: 
https://github.com/Azure/sonic-platform-daemons/blob/2d2749ab77ea0cfb9b1a9a0a5c7eeffbde9daed8/sonic-pcied/scripts/pcied#L48
https://github.com/Azure/sonic-platform-daemons/blob/2d2749ab77ea0cfb9b1a9a0a5c7eeffbde9daed8/sonic-pcied/scripts/pcied#L53

**Comment by liat-grozovik** [comment]
@sujinmkang could you please take a look? this is a result of recent changes in master I believe. Lets not take into 202012 until it is clear we have stable changes in master.
