### ISSUE TITLE
Cannot reach the first 256 addresses in specific VLANs

### ISSUE THREAD

**Issue by shi-su** [Azure/sonic-buildimage#8026]
#### Description
Cannot reach the first 256 addresses in VLANs with specific prefixes other than 192.168.0.1/21 (e.g., 192.168.16.1/21)

#### Steps to reproduce the issue:
1. Deploy a t0 testbed with the VLAN prefix here https://github.com/Azure/sonic-mgmt/blob/master/ansible/vars/topo_t0.yml#L60 changed to a prefix other than 192.168.0.1/21 (192.168.16.1/21 in this issue as an example) and redeploy minigraph. 
2. Add IP addresses on the ptf (e.g., `ip addr add 192.168.16.15/21 dev eth4` and `ip addr add 192.168.17.15/21 dev eth5`)
3. Ping the above-mentioned addresses from sonic switch.

#### Describe the results you received:
Ping to `192.168.17.15` could get through while to `192.168.16.15` could not. Tried addresses of `192.168.16.x`, none could get through.

#### Describe the results you expected:
Ping to both `192.168.16.x` and `192.168.17.x` is expected to get through.

#### Output of `show version`:
Observed the issue in 201911, 202012 and master branch on Broadcom, Mellanox, and virtual switch.

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):
The issue does not happen for the VLAN prefix `192.168.0.1/21`: 
1. Deploy a t0 testbed with the default vlan prefix `192.168.0.1/21`
2. Add IP addresses on the ptf (e.g., `ip addr add 192.168.0.15/21 dev eth4` and `ip addr add 192.168.1.15/21 dev eth5`)
3. Ping from sonic switch to both `192.168.0.15` and `192.168.1.15` gets through.

**Comment by prsunny** [comment]
is it a ptf issue or dut isssue?

**Comment by zhangyanzhao** [comment]
@shi-su please provide more info. Thanks.

**Comment by shi-su** [comment]
I think I understood the problem. If the Vlan gets configured in this way, test setup will have some overlap between the Vlan network and some bgp routes, and the Vlan gets override by bgp for the first 256 addresses. However, as such setup is used in many places in sonic-mgmt (e.g., https://github.com/Azure/sonic-mgmt/blob/master/ansible/vars/topo_t0.yml#L67, https://github.com/Azure/sonic-mgmt/blob/master/ansible/vars/topo_t0-56.yml#L129), I think we need to do something there to avoid such overlap between bgp route since it may result in some unexpected test results.

```
admin@vlab-01:~$ show ip route 192.168.16.1
Routing entry for 192.168.16.0/25
  Known via "bgp", distance 20, metric 0, best
  Last update 00:23:18 ago
  * 10.0.0.57, via PortChannel0001, weight 1
  * 10.0.0.59, via PortChannel0002, weight 1
  * 10.0.0.61, via PortChannel0003, weight 1
  * 10.0.0.63, via PortChannel0004, weight 1


admin@vlab-01:~$ show ip route 192.168.17.1
Routing entry for 192.168.16.0/21
  Known via "connected", distance 0, metric 0, best
  Last update 00:23:49 ago
  * directly connected, Vlan1000
```
