### ISSUE TITLE
docker-platform-monitor/start.sh

### ISSUE THREAD

**Issue by SenaoNetworksInc** [Azure/sonic-buildimage#805]
Before "supervisorctl start fancontrol", it must execute "rm -f /var/run/fancontrol.pid"  or any other method for kill fancontrol.pid -- otherwise "supervisorctl start fancontrol" will show an error message in some situation.

**Comment by stcheng** [comment]
Does this mean that the previous run failed to clean up the PID?

**Comment by SenaoNetworksInc** [comment]
Hi, Stcheng : 
Yes, thank you for reply^^
