### ISSUE TITLE
[route] test_static_route_ecmp ipv4 and ipv6 failures because expected packet arrives on wrong port

### ISSUE THREAD

**Issue by theasianpianist** [Azure/sonic-buildimage#8109]

**Comment by kevinskwang** [comment]
Created a PR to fix this issue at [#PR3740](https://github.com/Azure/sonic-mgmt/pull/3740).

**Comment by kevinskwang** [comment]
Link to the [PR3749](https://github.com/Azure/sonic-mgmt/pull/3749) and [PR3791](https://github.com/Azure/sonic-mgmt/pull/3791/)
