### ISSUE TITLE
[vlan] All cases fail on 7050cx3 single ToR

### ISSUE THREAD

**Issue by theasianpianist** [Azure/sonic-buildimage#8136]

**Comment by akokhan** [comment]
I think this duplicates https://github.com/Azure/sonic-buildimage/issues/8111

**Comment by theasianpianist** [comment]
closing as duplicate of https://github.com/Azure/sonic-buildimage/issues/8111, resolved by https://github.com/Azure/sonic-utilities/pull/1709
