### ISSUE TITLE
config interface speed throws an error on a multi-asic  box.

### ISSUE THREAD

**Issue by mlok-nokia** [Azure/sonic-buildimage#8308]
#### Description
config interface speed is broken when trying to configure for a frontpanel port on a multi-asic pizza box.

#### Steps to reproduce the issue:
1. Issue config interface to set the speed of an interface on a multi-asic pizza box

#### Describe the results you received:
```
admin@sonic:~$ sudo config interface -n asic0 speed Ethernet0 40000
name 'front_asic_namespaces' is not defined
```

#### Describe the results you expected:
Expect no error message and speed get set on the specified interface

#### Output of `show version`:
SONiC buildimage from commit 'https://github.com/Azure/sonic-buildimage/commit/3b3012791311ea7724975c8485236a0ee88d7510', 

However, looking at the latest code, the issue still exists.

**Comment by zhangyanzhao** [comment]
PR is waiting for review.

**Comment by zhangyanzhao** [comment]
@abdosi  will help to review the PR
