### ISSUE TITLE
[Nokia] fanout switch syncd crashed with memory issue

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#8351]
#### Description
This issue was found on nightly testbed. syncd crashed on fanout switch and causing link_flap test to fail.

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:
syslog.342.gz:Jun  4 06:56:22.238158 str-2-7215-acs-2 INFO syncd#supervisord: syncd syncd: cpssEnabler/mainOs/src/gtOs/linux/osLinuxMem.c:700: internalOsFree: Assertion `memblock != ((void *)0)' failed.

#### Describe the results you expected:
no crash

#### Output of `show version`:

```
SONiC Software Version: SONiC.HEAD.0-2aee8092
Distribution: Debian 10.7
Kernel: 4.19.0-6-2-armmp
Build commit: 2aee8092
Build date: Tue Dec 15 00:52:36 UTC 2020
Built by: gitlab-runner@sonic-bld2

Platform: armhf-nokia_ixs7215_52x-r0
HwSKU: Nokia-7215
ASIC: marvell
Serial Number: NK203110015
Uptime: 00:06:39 up 63 days, 23:35,  2 users,  load average: 0.58, 0.58, 0.56
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by radha-danda** [comment]
@yxieca, No sufficient details are present in the issue to debug further. We have not seen this in our lab anytime
 
Can you please share the details about:
-	the steps to reproduce the issue
-	syncd core file and  syslogs

**Comment by yxieca** [comment]
Close issue due to no-repro and the log from the crash is no longer available.
