### ISSUE TITLE
caclmgrd.service FAILURE status for single ASIC device

### ISSUE THREAD

**Issue by SavchukRomanLv** [Azure/sonic-buildimage#8388]
#### Description
After  [8222](https://github.com/Azure/sonic-buildimage/pull/8222)  caclmgrd.service: Main process exited, code=exited, status=1/FAILURE error appears due to reference before assignment error:
`Aug  9 14:37:00.653073 igk-5-dut INFO caclmgrd[16197]:   File "/usr/local/bin/caclmgrd", line 821, in <module>
Aug  9 14:37:00.653191 igk-5-dut INFO caclmgrd[16197]:     main()
Aug  9 14:37:00.653262 igk-5-dut INFO caclmgrd[16197]:   File "/usr/local/bin/caclmgrd", line 817, in main
Aug  9 14:37:00.653312 igk-5-dut INFO caclmgrd[16197]:     caclmgr.run()
Aug  9 14:37:00.653678 igk-5-dut INFO caclmgrd[16197]:   File "/usr/local/bin/caclmgrd", line 760, in run
Aug  9 14:37:00.653945 igk-5-dut INFO caclmgrd[16197]:     if db_id == state_db_id:
Aug  9 14:37:00.654001 igk-5-dut INFO caclmgrd[16197]: UnboundLocalError: local variable 'state_db_id' referenced before assignment`

#### Steps to reproduce the issue:
1. Deploy SONiC image [27940](https://dev.azure.com/mssonic/build/_build/results?buildId=27940&view=results)
#### Describe the results you received:
caclmgrd.service: Main process exited, code=exited, status=1/FAILURE error appears

#### Describe the results you expected:
caclmgrd.service started successfully 

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.27940-dirty-20210808.083526
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 8608af711
Build date: Sun Aug  8 13:39:19 UTC 2021
Built by: AzDevOps@sonic-build-workers-000KUX

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
ASIC Count: 1
Serial Number: SGD19412172
Model Number: DCS-7170-64C
Hardware Revision: N/A
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by SavchukRomanLv** [comment]
@trzhang-msft can you please take a look?

**Comment by trzhang-msft** [comment]
@SavchukRomanLv thanks, the fix is here https://github.com/Azure/sonic-buildimage/pull/8393

**Comment by trzhang-msft** [comment]
fixed by https://github.com/Azure/sonic-buildimage/pull/8393
