### ISSUE TITLE
file system full could cause service not running after reboot

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#839]
We noticed that some devices running old sonic releases could fill /var/log/ partition to 100%.

When /var/log partition is full, we noticed that some containers (if not all) would stay down after o.s. reboot.

The issue of filling /var/log partition has been solved in recent release (swss releases log file to allow logrotate to happen).

However, when we upgrade from old releases with full partitions to new releases, the storage space is not automatically freed. Therefore, human intervention is needed to clear these partitions.

As result, we would like to see that the upgrade process format the /var/log partition to mitigate the issue where a full /var/log partition could prevent rebooted device to start service.

**Comment by grozovik** [comment]
we discussed that during the sonic to sonic upgrade and we agreed this is not correct. when we upgrade we would like to keep the /var/log so we will see the reboot flow as well.
Also, when we install a version it does not recent automatically so it means that this will be removed even before the upgrade which is not correct.

I do think that the install procedure on these cases should be manually.
appreciate if you can refer to the above before we start the implementation.

**Comment by marian-pritsak** [comment]
As @grozovik pointed, logs are not cleared by design.
The rationale behind this is to keep as much information as possible.

I'm more concerned about a problem that containers are inoperable when log partition is full. The main purpose of moving logs to separate mount was to limit its size so that in a case of flooding from some component switch won't stop working due to 'no space left' error.

@jleveque , are you aware of this problem? The switch shouldn't become inoperable even if we have /var/log full.

**Comment by lguohan** [comment]
@grozovik, even when clear the /var/log we should still see the reboot flow.

@grozovik, can you explain this? I do not fully understand this.

"
Also, when we install a version it does not recent automatically so it means that this will be removed even before the upgrade which is not correct.

I do think that the install procedure on these cases should be manually."

@marian-pritsak , swss won't start if the log is full as it tries to open swss/sairedis log file.

**Comment by liatgrozovik** [comment]
sonic-installer can be used at any time for future use and will not necessarily followed by immediate rebooted. This was one of the reasons we didnt implement the log clear when we run the install.
We agreed that if the user would like to clear the log he should do it manually.

As this is only relevant to the version which does not support log size limit i dont think we should add a clear log to any sonic-installer call. If you wajt it it should be only as an option param which by default no clear log is done.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lguohan** [comment]
seems we are following liat suggestion, nothing further needs to be done.
