### ISSUE TITLE
[202012 platform_tests] test_platform_info.py::test_thermal_control_psu_absence error

### ISSUE THREAD

**Issue by sujinmkang** [Azure/sonic-buildimage#8453]
#### Description
202012 image has an error from sonic-mgmt/tests/platform_tests/test_platform_info.py::test_thermal_control_psu_absence error
on vms20-t0-7050cx3

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:

ignore_list = ['.*Error getting sensor data: dps460.*Kernel interface error.*']
loganalyzer = <tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzer instance at 0x7f24c9334fa0>
marker     = 'turn_on_off_psu_and_check_psustatus.2021-08-10-20:19:09'
request    = <SubRequest 'ignore_particular_error_log' for <Function test_thermal_control_psu_absence[str2-7050cx3-acs-01-ignore_particular_error_log0]>>

platform_tests/test_platform_info.py:126: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/plugins/loganalyzer/loganalyzer.py:282: in analyze
    self._verify_log(analyzer_summary)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzer instance at 0x7f24c9334fa0>
result = {'expect_messages': {'/tmp/syslog.str2-7050cx3-acs-01.2021-08-10-20:19:37': []}, 'match_files': {'/tmp/syslog.str2-705...ct type psu.any.absence not found')\n"]}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 1}, ...}

    def _verify_log(self, result):
        """
        Verify that total match and expected missing match equals to zero or raise exception otherwise.
        Verify that expected_match is not equal to zero when there is configured expected regexp in self.expect_regex list
        """
        if not result:
            raise LogAnalyzerError("Log analyzer failed - no result.")
        if result["total"]["match"] != 0 or result["total"]["expected_missing_match"] != 0:
>           raise LogAnalyzerError(result)
E           LogAnalyzerError: {'match_messages': {'/tmp/syslog.str2-7050cx3-acs-01.2021-08-10-20:19:37': ["Aug 10 20:27:03.110129 str2-7050cx3-acs-01 ERR pmon#thermalctld: Caught exception while initializing thermal manager - Exception('ThermalJsonObject type psu.any.absence not found')\n"]}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 1}, 'match_files': {'/tmp/syslog.str2-7050cx3-acs-01.2021-08-10-20:19:37': {'expected_match': 0, 'match': 1}}, 'expect_messages': {'/tmp/syslog.str2-7050cx3-acs-01.2021-08-10-20:19:37': []}, 'unused_expected_regexp': []}

result     = {'expect_messages': {'/tmp/syslog.str2-7050cx3-acs-01.2021-08-10-20:19:37': []}, 'match_files': {'/tmp/syslog.str2-705...ct type psu.any.absence not found')\n"]}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 1}, ...}
self       = <tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzer instance at 0x7f24c9334fa0>

common/plugins/loganalyzer/loganalyzer.py:88: LogAnalyzerErro

#### Describe the results you expected:
No error

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Staphylo** [comment]
I found the problem related to this issue.
The test replaces our thermal_policy configuration by its own but it therefore relies on properties we did not implement.
I will be adding the missing ones.
