### ISSUE TITLE
[2020 platform_tests] TestChassisApi::test_status_led failure on vms20-t0-7050cx3-1 

### ISSUE THREAD

**Issue by sujinmkang** [Azure/sonic-buildimage#8464]
#### Description

Latest 202012 image has platform_tests/api/test_chassis.py::TestChassisApi::test_status_led failure on vms20-t0-7050cx3-1 
#### Steps to reproduce the issue:
1. run platform_tests/api/test_chassis.py on arista-7050cx3_32s
2.
3.

#### Describe the results you received:
 
platform_tests/api/test_chassis.py:444: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_chassis.TestChassisApi object at 0x7f05788d1210>

    def assert_expectations(self):
        """
        Checks if there are any error messages waiting in failed_expectations.
        If so, it will fail an assert and pass a concatenation of all pending
        error messages. It will also clear failed_expectations to prepare it
        for the next use.
        """
        if len(self.failed_expectations) > 0:
            err_msg = ", ".join(self.failed_expectations)
            # TODO: When we move to Python 3.3+, we can use self.failed_expectations.clear() instead
            del self.failed_expectations[:]
>           pytest_assert(False, err_msg)
E           Failed: Failed to perform set_status_led, Failed to perform set_status_led, Failed to set status_led to fault, Failed to perform set_status_led, Failed to set status_led to normal, Failed to perform set_status_led, Failed to set status_led to off

err_msg    = 'Failed to perform set_status_led, Failed to perform set_status_led, Failed to set status_led to fault, Failed to perform set_status_led, Failed to set status_led to normal, Failed to perform set_status_led, Failed to set status_led to off'
self       = <test_chassis.TestChassisApi object at 0x7f05788d1210>

#### Describe the results you expected:
 PASSED or SKIPPED

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Staphylo** [comment]
This API is implemented but failing indeed. I'll have a look.
