### ISSUE TITLE
eth0 failed to get an IP address via DHCP when install the image via ONIE

### ISSUE THREAD

**Issue by keboliu** [Azure/sonic-buildimage#8512]
#### Description

When installing an image from ONIE, it failed to get an IP address for eth0, which result in no way to access the DUT except console.  This issue can be reproduced from the master image with the latest commit hash c89567750.  As I tested, if I revert https://github.com/Azure/sonic-buildimage/commit/c8b5daed27fa29a1d993379d68dbbe5b05dcfc0d, this issue disappeared, so I believe this commit cause the issue.

This issue can be reproduced easily on different setups by simply install the image from ONIE,  and when it boots up, access through the console, manually issue command "dhclient eth0 -v" can have the IP address assigned correctly.

**No IP address assigned on eth0 after boot up:**

```
root@sonic:/home/admin# ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fcfc:fcfc:210:24:9a03:9bff:fe98:cf36  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::9a03:9bff:fe98:cf36  prefixlen 64  scopeid 0x20<link>
        ether 98:03:9b:98:cf:36  txqueuelen 1000  (Ethernet)
        RX packets 1041  bytes 145033 (141.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 176  bytes 18674 (18.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xfb100000-fb1fffff  
```

**relevant error observed in syslog:**

```
Aug 18 02:11:14.860696 sonic WARNING info: executing /sbin/dhclient -x -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
Aug 18 02:11:14.860696 sonic WARNING info: executing /sbin/dhclient -x -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
Aug 18 02:11:14.860696 sonic WARNING info: executing /sbin/dhclient -x -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
Aug 18 02:11:14.906840 sonic INFO dhclient[3113]: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7
Aug 18 02:11:14.910233 sonic WARNING info: executing /sbin/dhclient -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0 -nw
Aug 18 02:11:14.910233 sonic WARNING info: executing /sbin/dhclient -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0 -nw
Aug 18 02:11:14.910233 sonic WARNING info: executing /sbin/dhclient -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0 -nw
Aug 18 02:11:14.966584 sonic INFO dhclient[3116]: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 4
Aug 18 02:11:14.970977 sonic INFO networking[3087]: error: eth0: dhclient: timeout failed to detect new ip addresses
Aug 18 02:11:14.971123 sonic WARNING error: eth0: dhclient: timeout failed to detect new ip addresses
Aug 18 02:11:14.971420 sonic WARNING info: executing /sbin/dhclient -r -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
Aug 18 02:11:14.971420 sonic WARNING info: executing /sbin/dhclient -r -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
Aug 18 02:11:14.971420 sonic WARNING info: executing /sbin/dhclient -r -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
Aug 18 02:11:14.979530 sonic INFO dhclient[3136]: Killed old client process
```

#### Steps to reproduce the issue:

1. Install an image via ONIE
2. Try to access the DUT via SSH, it will fail

#### Describe the results you received:

After installing the image from ONIE, no IP address was assigned to eth0

#### Describe the results you expected:

IP address should be assigned to eth0 and DUT should be accessible from SSH after boot up

#### Output of `show version`:

```
root@r-anaconda-15:/home/admin# show version

SONiC Software Version: SONiC.master.29321-c89567750
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: c89567750
Build date: Mon Aug 16 14:19:54 UTC 2021
Built by: AzDevOps@sonic-build-workers-000LLZ

Platform: x86_64-mlnx_msn3700c-r0
HwSKU: ACS-MSN3700C
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1852X03897
Model Number: MSN3700-CS2F
Hardware Revision: A3
Uptime: 03:01:00 up 50 min,  2 users,  load average: 0.50, 0.40, 0.44

Docker images:
REPOSITORY                    TAG                      IMAGE ID            SIZE
docker-syncd-mlnx             latest                   1375f61bab72        963MB
docker-syncd-mlnx             master.29321-c89567750   1375f61bab72        963MB
docker-platform-monitor       latest                   81b6488debcc        741MB
docker-platform-monitor       master.29321-c89567750   81b6488debcc        741MB
docker-snmp                   latest                   327b8d1e7108        455MB
docker-snmp                   master.29321-c89567750   327b8d1e7108        455MB
docker-dhcp-relay             latest                   a7ad1080d627        420MB
docker-sflow                  latest                   fdf2236d42eb        426MB
docker-sflow                  master.29321-c89567750   fdf2236d42eb        426MB
docker-router-advertiser      latest                   33b1f9acf2ae        413MB
docker-router-advertiser      master.29321-c89567750   33b1f9acf2ae        413MB
docker-teamd                  latest                   a98cbd640ad1        425MB
docker-teamd                  master.29321-c89567750   a98cbd640ad1        425MB
docker-orchagent              latest                   22854706f617        443MB
docker-orchagent              master.29321-c89567750   22854706f617        443MB
docker-database               latest                   7923b0601900        413MB
docker-database               master.29321-c89567750   7923b0601900        413MB
docker-lldp                   latest                   2553f923c6ef        453MB
docker-lldp                   master.29321-c89567750   2553f923c6ef        453MB
docker-macsec                 latest                   cfdc4e5198b8        428MB
docker-macsec                 master.29321-c89567750   cfdc4e5198b8        428MB
docker-nat                    latest                   e3da98eb8591        428MB
docker-nat                    master.29321-c89567750   e3da98eb8591        428MB
docker-sonic-mgmt-framework   latest                   e57ba2dec8f8        569MB
docker-sonic-mgmt-framework   master.29321-c89567750   e57ba2dec8f8        569MB
docker-fpm-frr                latest                   3d351ad85c8b        443MB
docker-fpm-frr                master.29321-c89567750   3d351ad85c8b        443MB
docker-sonic-telemetry        latest                   9ec152d1f5e1        501MB
docker-sonic-telemetry        master.29321-c89567750   9ec152d1f5e1        501MB



```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```
[sonic_dump_r-anaconda-15_20210818_022254.tar.gz](https://github.com/Azure/sonic-buildimage/files/7004252/sonic_dump_r-anaconda-15_20210818_022254.tar.gz)

**Comment by tjcw** [comment]
I see the same problem with DHCP using the master branch at commit ca713e2fad73c436a4beef5470be7d24185a5bba , configured to use OVS switch (make configure PLATFORM=vs). I use the sonic-vs.img.gz image, decompressed and booted with qemu.
I have previously had success with the 201206 branch at commit 93e939b8af46e89183e4d845b834d8040e916f38 .

This is the first time that a build of 'master' has completed for me, so I am unable to be more specific as to which commit introduces the bug.

**Comment by keboliu** [comment]
I was able to identify the problematic commit hash, it's  https://github.com/Azure/sonic-buildimage/commit/c8b5daed27fa29a1d993379d68dbbe5b05dcfc0d,  after I reverted it, I see the eth0 can obtain IP address as before.

**Comment by saiarcot895** [comment]
I see the cause of this issue: ifupdown2 3.0.0 added a check after starting dhclient to see if a new IP address was added (if dhclient succeeded in getting a new address); this check wasn't there in 1.2.8. This alone would be fine (and in fact match the behavior of ifupdown), but we're installing a policy file at `/etc/network/ifupdown2/policy.d/ifupdown2_policy.json` with `"dhcp-wait" : "no"` (packaged from `files/dhcp/ifupdown2_policy.json`).

What this does is it tells ifupdown2 to start dhclient with the `-nw` flag, which tells dhclient to become a daemon immediately, before it gets an IP address. This lets ifupdown2 continue ahead without waiting for dhclient to get an IP address and then become a daemon. This behavior is the same in 1.2.8 and 3.0.0. What's new in 3.0.0 is that because it's checking for a new IP address after dhclient becomes a daemon, since dhclient takes a second or two to actually get and install the IP address, ifupdown2 will see that there's no new IP addresses, and so kill the dhclient process and release any leases that got acquired.

I think the only fix here might be to remove `"dhcp-wait" : "no"` from that policy file, but I'm not sure why it was added there in the first place.

**Comment by rajendra-dendukuri** [comment]
This option was added to allow multiple dhclient instances to start in parallel. When dhclient is run on in-band interfaces(typically 32-48ports), having the no wait option ensures that "systemctl restart networking" is not blocked for a lot of time. Yes, if we remove it, there can be issues when using ZTP. Also, if the OOB interface is not receiving DHCP offer as soon as the switch boots, it may result in slower start of services if they are blocked on eth0 getting an ip address. If there is a behavior change in ifupdown2 3.0.0 compared to v1.2.8, I would flag that to the ifupdown2 maintainer. The fix ideally should be to have a new policy setting which allows things to run like it was in v1.2.8.

**Comment by lguohan** [comment]
can this ifupdown2 policy be per interface? the issue is on eth0 now.

**Comment by saiarcot895** [comment]
For this particular policy entry, it looks like ifupdown2 checks only the global policy setting, not the per-interface policy setting. They do have the ability to specify per-interface policy settings, but this one is calling a method that only checks the global policy settings.
