### ISSUE TITLE
[warm-reboot] Warm-reboot with image upgrade fails to trigger due to ASIC config checksum failure

### ISSUE THREAD

**Issue by tjchadaga** [Azure/sonic-buildimage#8531]
#### Description

Warm-reboot from 201811 to 202012 image fails to trigger with ASIC config checksum failure

sudo sonic_installer list
Current: SONiC-OS-20181130.96
Next: SONiC-OS-20201231.18
Available: 
SONiC-OS-20201231.18
SONiC-OS-20181130.96

sudo warm-reboot -v
ASIC config may have changed: errno=1
Thu Aug 19 19:40:11 UTC 2021 warm-reboot failure (1) cleanup ...
Thu Aug 19 19:40:12 UTC 2021 Cancel warm-reboot: code (0)

#### Steps to reproduce the issue:
1. Trigger warm-reboot from 201811 with next image set to 202012

#### Describe the results you received:
Warm-reboot failed to trigger since pre-check script failed due to asic config checksum mismatch

Aug 19 19:40:11.619225 str2-7050cx3-acs-01 INFO admin: Checking that ASIC configuration has not changed
Aug 19 19:40:11.961169 str2-7050cx3-acs-01 ERR admin: ASIC config may have changed, checksum failed
Aug 19 19:40:11.967083 str2-7050cx3-acs-01 NOTICE admin: warm-reboot failure (1) cleanup ...
Aug 19 19:40:12.378115 str2-7050cx3-acs-01 NOTICE admin: Cancel warm-reboot: code (0)

The script is comparing current asic config checksum with destination config checksum which appear to be different, hence the failure:

cat /etc/sonic/asic_config_checksum 
b2cef48d51902955c8d2740f14970f6164c21318
 cat /tmp/dst_asic_config_checksum 
aada672b9cde2fc7076e8e581a9a0d394888fb93

#### Describe the results you expected:
warm-reboot pre-check script should pass and no errors seen 

#### Output of `show version`:

```
SONiC Software Version: SONiC.20181130.96
Distribution: Debian 9.13
Kernel: 4.9.0-14-amd64
Build commit: 325e0f2
Build date: Tue Jul 20 01:31:49 UTC 2021
Built by: AzDevOps@sonic-int-build-workers-00028K
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Issue is easily reproducible

**Comment by prsunny** [comment]
Could you please try with `warm-reboot -f`?

**Comment by tjchadaga** [comment]
> Could you please try with `warm-reboot -f`?

warm-reboot -f helps get past this issue. Running into https://github.com/Azure/sonic-buildimage/issues/8532 after doing this.

**Comment by prsunny** [comment]
@vaibhavhd , are you looking into this issue?

**Comment by vaibhavhd** [comment]
Yes, I am tracking this offline. Checksum failure is expected for 201811 to 202012 warm upgrade. For public images, we have `-i` option in warm-reboot script to skip ONLY ASIC config checksum failure.
