### ISSUE TITLE
Gateway IP address is always x.x.x.1 if setup ManagementIPInterface in minigraph.xml

### ISSUE THREAD

**Issue by okanchou9** [Azure/sonic-buildimage#857]
Hi,

Opening an issue base on https://groups.google.com/forum/#!topic/sonicproject/AC30lG0qiPs and please refer the following for copy of original message:

---------------------------------------------------------------------------------------------------------
Just found out that the IP address of gateway is always x.x.x.1 if setup ManagementIPInterface in minigraph.xml by the following line in minigraph.py:

gwaddr = ipaddress.IPAddress(int(mgmtipn.network) + 1)

I don't think this is a good way to hardcore this address since the IP address of gateway in different network topology may not x.x.x.1.
Suggest adding a new tag for it like the following sample xml format:

<a:ManagementIPInterface>
    <Name>HostIP</Name>
    <AttachTo>eth0</AttachTo>
    <a:Prefix xmlns:b="Microsoft.Search.Autopilot.Evolution">
        <b:IPPrefix>100.0.0.30/24</b:IPPrefix>
    </a:Prefix>
    <a:PrefixStr>100.0.0.30/24</a:PrefixStr>
    <Gateway>100.0.0.254</Gateway>
</a:ManagementIPInterface>

Any suggestions would be helpful and let me know if any problem.

Regards,
Kenie Liu

**Comment by taoyl-ms** [comment]
Specifying gateway is not supported in minigraph schema. Please use `gwaddr` attribute in `MGMT_INTERFACE` table in config db to config this.
