### ISSUE TITLE
IPv6 use-link-local-only disable is not working as expected

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#8571]
#### Description
When there are no IPv6 addresses configured on an interface and IPv6 link local is enabled globally/local and then disabled, IPv6 should be disabled on the interface. However, IPv6 works on the interface and even ping from peer works on the link local IP address.
The behavior is not as per the HLD which has below statement.
"Similarly, the IPv6 mode on an interface is disabled when IPv6 'use-link-local-only' mode is disabled with no manually configured addresses on the interface (or) when all addresses are unconfigured on the interface with IPv6 'use-link-local-only' disabled."

#### Steps to reproduce the issue:
1.config interface ipv6 enable use-link-local-only Ethernet24
2.config interface ipv6 disable use-link-local-only Ethernet24
3.show ipv6 interfaces
4. Ping from peer

#### Describe the results you received:
show ipv6 interfaces
Interface    Master    IPv4 address/mask                       Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  --------------------------------------  ------------  --------------  -------------
Bridge                 fe80::e86e:f2ff:fe08:4721%Bridge/64     up/down       N/A             N/A
Ethernet0              fe80::268a:7ff:fed0:d40%Ethernet0/64    up/up         N/A             N/A
Ethernet4              fe80::268a:7ff:fed0:d40%Ethernet4/64    up/up         N/A             N/A
Ethernet8              fe80::268a:7ff:fed0:d40%Ethernet8/64    up/up         N/A             N/A
Ethernet16             fe80::268a:7ff:fed0:d40%Ethernet16/64   up/up         N/A             N/A
Ethernet20             2001:32::1/64                           up/up         N/A             N/A
                       fe80::268a:7ff:fed0:d40%Ethernet20/64                 N/A             N/A
Ethernet24             fe80::268a:7ff:fed0:d40%Ethernet24/64   up/up         N/A             N/A
Ethernet124            fe80::268a:7ff:fed0:d40%Ethernet124/64  up/up         N/A             N/A
Loopback0              2001:32::1/64                           up/up         N/A             N/A
                       fe80::f49b:2cff:fe7d:3985%Loopback0/64                N/A             N/A
docker0                fd00::1/80                              up/down       N/A             N/A
                       fe80::1%docker0/64                                    N/A             N/A
eth0                   fe80::ee0d:9aff:fe30:761a%eth0/64       up/up         N/A             N/A
lo                     ::1/128                                 up/up         N/A             N/A

ping6 fe80::268a:7ff:fed0:d40%Ethernet24
PING fe80::268a:7ff:fed0:d40%Ethernet24(fe80::268a:7ff:fed0:d40%Ethernet24) 56 data bytes
64 bytes from fe80::268a:7ff:fed0:d40%Ethernet24: icmp_seq=1 ttl=64 time=0.257 ms
64 bytes from fe80::268a:7ff:fed0:d40%Ethernet24: icmp_seq=2 ttl=64 time=0.290 ms
64 bytes from fe80::268a:7ff:fed0:d40%Ethernet24: icmp_seq=3 ttl=64 time=0.243 ms
64 bytes from fe80::268a:7ff:fed0:d40%Ethernet24: icmp_seq=4 ttl=64 time=0.357 ms
64 bytes from fe80::268a:7ff:fed0:d40%Ethernet24: icmp_seq=5 ttl=64 time=0.300 ms

IPv6 and ping to link local works even after disabling IPv6 link local

#### Describe the results you expected:
After disabling IPv6 link local, ping and any functionality related to IPv6 link local shouldn't work

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.177-e3a30deea_Internal
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: e3a30deea
Build date: Fri Aug 20 08:01:05 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02-244

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1623X09522
Model Number: MSN2700-CS2FO
Hardware Revision: Not Specified
Uptime: 22:42:25 up  1:07,  1 user,  load average: 1.31, 1.34, 1.10

Docker images:
REPOSITORY                    TAG                             IMAGE ID            SIZE
docker-dhcp-relay             latest                          7458f8bdcd53        420MB
docker-syncd-mlnx             latest                          a40ca503a1ef        964MB
docker-syncd-mlnx             master.177-e3a30deea_Internal   a40ca503a1ef        964MB
docker-snmp                   latest                          e993728805c9        455MB
docker-snmp                   master.177-e3a30deea_Internal   e993728805c9        455MB
docker-teamd                  latest                          62e47c604ceb        425MB
docker-teamd                  master.177-e3a30deea_Internal   62e47c604ceb        425MB
docker-platform-monitor       latest                          2c662d9af346        742MB
docker-platform-monitor       master.177-e3a30deea_Internal   2c662d9af346        742MB
docker-lldp                   latest                          48b43174141b        453MB
docker-lldp                   master.177-e3a30deea_Internal   48b43174141b        453MB
docker-database               latest                          3e86e48aacbc        413MB
docker-database               master.177-e3a30deea_Internal   3e86e48aacbc        413MB
docker-router-advertiser      latest                          fa4d431edaa6        413MB
docker-router-advertiser      master.177-e3a30deea_Internal   fa4d431edaa6        413MB
docker-orchagent              latest                          fa0e7d68b19e        443MB
docker-orchagent              master.177-e3a30deea_Internal   fa0e7d68b19e        443MB
docker-nat                    latest                          1d02ea9fd6a8        428MB
docker-nat                    master.177-e3a30deea_Internal   1d02ea9fd6a8        428MB
docker-macsec                 latest                          a5f71fb9c8b2        428MB
docker-macsec                 master.177-e3a30deea_Internal   a5f71fb9c8b2        428MB
docker-sonic-telemetry        latest                          681b3bf54910        501MB
docker-sonic-telemetry        master.177-e3a30deea_Internal   681b3bf54910        501MB
docker-sonic-mgmt-framework   latest                          6e3eda9c2774        569MB
docker-sonic-mgmt-framework   master.177-e3a30deea_Internal   6e3eda9c2774        569MB
docker-fpm-frr                latest                          3477cf9a789e        443MB
docker-fpm-frr                master.177-e3a30deea_Internal   3477cf9a789e        443MB
docker-sflow                  latest                          3c3bc089cefd        426MB
docker-sflow                  master.177-e3a30deea_Internal   3c3bc089cefd        426MB

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prsunny** [comment]
@AkhileshSamineni , can you please take a look? @dgsudharsan , please check this [review comment](https://github.com/Azure/sonic-swss/pull/1463/files#r654055476)

**Comment by AkhileshSamineni** [comment]
@dgsudharsan 
Here are more details about ipv6 link-local : 
1. The global/interface enable config command will create the RIF in the hardware, if there is no ipv6 global address configured on a interface.
2. The global/interface disable config command will delete the RIF in the hardware, if there is no ipv6 global address configured on a interface.
3. IPv6 LL is enabled by default in the kernel stack and the config command is not enabling/disabling the IPv6 LL in stack.

So there is no command to disable the ipv6 link-local in kerel stack.
And by default FE80::/10, /128 routes are added to hardware and any packet destined to link-local address are copied to CPU. 
As ipv6 link-local is enabled by default, ping will always work. It is expected behavior only.

There is a task item to disable the ipv6 link-local from kernel perspective - https://github.com/Azure/sonic-buildimage/issues/8364

**Comment by dgsudharsan** [comment]
@AkhileshSamineni Can you please check the steps provided

1.config interface ipv6 enable use-link-local-only Ethernet24
2.config interface ipv6 disable use-link-local-only Ethernet24
3.show ipv6 interfaces
4. Ping from peer

Before the first step RIF doesn't exist - Ping doesn't work
After the first step RIF is created - Ping works.
After the second step - RIF is not removed (There are no global address) - Ping shouldn't work. But ping works!!

When we do enable and disable the behavior shouldn't change.

**Comment by AkhileshSamineni** [comment]
@dgsudharsan I am able to recreate the issue.
After second step 2, the RIF is not getting deleted due to ipv6 link-local neigh entry is not deleted from APPL_DB, resulting in refcount for the interface (Ethernet24) is non-zero.

I have fixed it.
