### ISSUE TITLE
IPv4 routes with IPv6 link local next hops are not installed in the hardware.

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#8606]
#### Description

IPv4 routes with IPv6 link local next hops are not installed in the hardware. The routes are not pushed to the ASIC DB. The issue is next hop is pushed to APP_DB as v4 instead of v6.

As we can see in the output below fe80:: is directly converted to ipv4 and it results in 254.128.0.0 as next hop which is wrong!!

show ip route
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
       F - PBR, f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup

B>* 2.1.0.0/16 [200/0] via fe80::268a:7ff:fed0:d40, Ethernet0, weight 1, 02:22:26
B>* 5.1.0.0/16 [200/0] via fe80::268a:7ff:fed0:d40, Ethernet0, weight 1, 02:22:26
B>* 10.1.0.2/32 [200/0] via fe80::268a:7ff:fed0:d40, Ethernet0, weight 1, 02:22:26

redis-cli -n 0 hgetall "ROUTE_TABLE:2.1.0.0/16"
1) "nexthop"
2) "254.128.0.0"
3) "ifname"
4) "Ethernet0"

redis-cli -n 1 keys *ROUTE_ENTRY*
1) "ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{\"dest\":\"fe80::/10\",\"switch_id\":\"oid:0x21000000000000\",\"vr\":\"oid:0x3000000000002\"}"
2) "ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{\"dest\":\"2001:1234:4576::/64\",\"switch_id\":\"oid:0x21000000000000\",\"vr\":\"oid:0x3000000000002\"}"
3) "ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{\"dest\":\"fe80::7efe:90ff:fef5:3640/128\",\"switch_id\":\"oid:0x21000000000000\",\"vr\":\"oid:0x3000000000002\"}"
4) "ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{\"dest\":\"2001:32::/64\",\"switch_id\":\"oid:0x21000000000000\",\"vr\":\"oid:0x3000000000002\"}"
5) "ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{\"dest\":\"::/0\",\"switch_id\":\"oid:0x21000000000000\",\"vr\":\"oid:0x3000000000002\"}"
6) "ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{\"dest\":\"0.0.0.0/0\",\"switch_id\":\"oid:0x21000000000000\",\"vr\":\"oid:0x3000000000002\"}"

redis-cli -n 0 keys *NEIGH*
1) "NEIGH_TABLE:Ethernet0:fe80::268a:7ff:fed0:d40"
2) "NEIGH_TABLE:Ethernet0:169.254.0.1"
3) "NEIGH_RESOLVE_TABLE:Ethernet0:254.128.0.0"

root@sonic:~# ip route
2.1.0.0/16 via 169.254.0.1 dev Ethernet0 proto bgp metric 20 onlink
5.1.0.0/16 via 169.254.0.1 dev Ethernet0 proto bgp metric 20 onlink
10.1.0.2 via 169.254.0.1 dev Ethernet0 proto bgp metric 20 onlink
240.127.1.0/24 dev docker0 proto kernel scope link src 240.127.1.1 linkdown

#### Steps to reproduce the issue:
1. Configure IPv6 link local
2. Exchange IPv4 routes
3. Check ASIC_DB to see if the routes are programmed

#### Output of `show version`:

```
show version

SONiC Software Version: SONiC.master.177-e3a30deea_Internal
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: e3a30deea
Build date: Fri Aug 20 08:01:05 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02-244

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1623X09522
Model Number: MSN2700-CS2FO
Hardware Revision: Not Specified
Uptime: 19:59:39 up  2:29,  1 user,  load average: 0.45, 0.61, 0.79

Docker images:
REPOSITORY                    TAG                             IMAGE ID            SIZE
docker-dhcp-relay             latest                          7458f8bdcd53        420MB
docker-syncd-mlnx             latest                          a40ca503a1ef        964MB
docker-syncd-mlnx             master.177-e3a30deea_Internal   a40ca503a1ef        964MB
docker-snmp                   latest                          e993728805c9        455MB
docker-snmp                   master.177-e3a30deea_Internal   e993728805c9        455MB
docker-teamd                  latest                          62e47c604ceb        425MB
docker-teamd                  master.177-e3a30deea_Internal   62e47c604ceb        425MB
docker-platform-monitor       latest                          2c662d9af346        742MB
docker-platform-monitor       master.177-e3a30deea_Internal   2c662d9af346        742MB
docker-lldp                   latest                          48b43174141b        453MB
docker-lldp                   master.177-e3a30deea_Internal   48b43174141b        453MB
docker-database               latest                          3e86e48aacbc        413MB
docker-database               master.177-e3a30deea_Internal   3e86e48aacbc        413MB
docker-router-advertiser      latest                          fa4d431edaa6        413MB
docker-router-advertiser      master.177-e3a30deea_Internal   fa4d431edaa6        413MB
docker-orchagent              latest                          fa0e7d68b19e        443MB
docker-orchagent              master.177-e3a30deea_Internal   fa0e7d68b19e        443MB
docker-nat                    latest                          1d02ea9fd6a8        428MB
docker-nat                    master.177-e3a30deea_Internal   1d02ea9fd6a8        428MB
docker-macsec                 latest                          a5f71fb9c8b2        428MB
docker-macsec                 master.177-e3a30deea_Internal   a5f71fb9c8b2        428MB
docker-sonic-telemetry        latest                          681b3bf54910        501MB
docker-sonic-telemetry        master.177-e3a30deea_Internal   681b3bf54910        501MB
docker-sonic-mgmt-framework   latest                          6e3eda9c2774        569MB
docker-sonic-mgmt-framework   master.177-e3a30deea_Internal   6e3eda9c2774        569MB
docker-fpm-frr                latest                          3477cf9a789e        443MB
docker-fpm-frr                master.177-e3a30deea_Internal   3477cf9a789e        443MB
docker-sflow                  latest                          3c3bc089cefd        426MB
docker-sflow                  master.177-e3a30deea_Internal   3c3bc089cefd        426MB

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
Adam will take a look.

**Comment by adyeung** [comment]
The fix will require a few changes from fpmsyncd, neighbororch, routeorch to address the FRR BGP IPv6LL NH, BRCM is targeting the fix to be pushed around 9/15.

**Comment by zhangyanzhao** [comment]
@adyeung would you please help to check the status of this issue?

**Comment by adyeung** [comment]
#8740 already merged. Pending UT on #1903 UT, Utpal will followup and update #1903
