### ISSUE TITLE
Link-local global command exists in the IPv4 CLI tree

### ISSUE THREAD

**Issue by dgsudharsan** [Azure/sonic-buildimage#8609]
#### Description
Link local global commands exist in the IPv4 CLI tree. Currently there is no feature to support IPv4 link local. So this command shouldn't be part of the config CLI. This command however operates on the IPv6 CLI. Its better to remove the command for IPv4.
```
root@sonic:~# config ipv6 enable link-local
root@sonic:~# config ip disable  link-local
sroot@sonic:~# show ipv6 link-local-mode
+------------------+----------+
| Interface Name   | Mode     |
+==================+==========+
| Ethernet124      | Disabled |
+------------------+----------+
| Ethernet16       | Disabled |
+------------------+----------+
root@sonic:~#
```

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.177-e3a30deea_Internal
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: e3a30deea
Build date: Fri Aug 20 08:01:05 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02-244

Platform: x86_64-mlnx_msn2740-r0
HwSKU: ACS-MSN2740
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1726X02088
Model Number: MSN2740-CB2F1OS
Hardware Revision: A2
Uptime: 20:42:33 up  3:47,  1 user,  load average: 1.20, 1.33, 1.04

Docker images:
REPOSITORY                    TAG                             IMAGE ID            SIZE
docker-dhcp-relay             latest                          7458f8bdcd53        420MB
docker-syncd-mlnx             latest                          a40ca503a1ef        964MB
docker-syncd-mlnx             master.177-e3a30deea_Internal   a40ca503a1ef        964MB
docker-snmp                   latest                          e993728805c9        455MB
docker-snmp                   master.177-e3a30deea_Internal   e993728805c9        455MB
docker-teamd                  latest                          62e47c604ceb        425MB
docker-teamd                  master.177-e3a30deea_Internal   62e47c604ceb        425MB
docker-platform-monitor       latest                          2c662d9af346        742MB
docker-platform-monitor       master.177-e3a30deea_Internal   2c662d9af346        742MB
docker-lldp                   latest                          48b43174141b        453MB
docker-lldp                   master.177-e3a30deea_Internal   48b43174141b        453MB
docker-database               latest                          3e86e48aacbc        413MB
docker-database               master.177-e3a30deea_Internal   3e86e48aacbc        413MB
docker-router-advertiser      latest                          fa4d431edaa6        413MB
docker-router-advertiser      master.177-e3a30deea_Internal   fa4d431edaa6        413MB
docker-orchagent              latest                          fa0e7d68b19e        443MB
docker-orchagent              master.177-e3a30deea_Internal   fa0e7d68b19e        443MB
docker-nat                    latest                          1d02ea9fd6a8        428MB
docker-nat                    master.177-e3a30deea_Internal   1d02ea9fd6a8        428MB
docker-macsec                 latest                          a5f71fb9c8b2        428MB
docker-macsec                 master.177-e3a30deea_Internal   a5f71fb9c8b2        428MB
docker-sonic-telemetry        latest                          681b3bf54910        501MB
docker-sonic-telemetry        master.177-e3a30deea_Internal   681b3bf54910        501MB
docker-sonic-mgmt-framework   latest                          6e3eda9c2774        569MB
docker-sonic-mgmt-framework   master.177-e3a30deea_Internal   6e3eda9c2774        569MB
docker-fpm-frr                latest                          3477cf9a789e        443MB
docker-fpm-frr                master.177-e3a30deea_Internal   3477cf9a789e        443MB
docker-sflow                  latest                          3c3bc089cefd        426MB
docker-sflow                  master.177-e3a30deea_Internal   3c3bc089cefd        426MB

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by AkhileshSamineni** [comment]
@dgsudharsan There is no IPv4 CLI tree in config mode. We have only ipv6 tree.
The command "config ip disable  link-local" is same as "config ipv6 disable link-local", as CLICK treating 'ip' as short form for 'ipv6'.

Example : Command "show int status" is similar as "show interface status". CLICK treating 'int' as short form for 'interface'.
Please check once.

**Comment by dgsudharsan** [comment]
@AkhileshSamineni Please check show --help output here. There is an IPv4 tree
show --help
Usage: show [OPTIONS] COMMAND [ARGS]...

  SONiC command line - 'show' command

Options:
  -h, -?, --help  Show this message and exit.

Commands:
  aaa                   Show AAA configuration
  acl                   Show ACL related information
  arp                   Show IP ARP table
  boot                  Show boot configuration
  buffer                Show buffer information
  buffer_pool           Show details of the buffer pools
  chassis-modules       Show chassis-modules information
  clock                 Show date and time
  dropcounters          Show drop counter related information
  ecn                   Show ECN configuration
  environment           Show environmentals (voltages, fans, temps)
  feature               Show feature status
  fgnhg                 Show FGNHG information
  headroom-pool         Show details of headroom pool
  interfaces            Show details of the network interfaces
  **ip                    Show IP (IPv4) commands**
  ipv6                  Show IPv6 commands
  kdump                 Show kdump configuration, status and information
  kubernetes
  line                  Show all console lines and their info include...
  lldp                  LLDP (Link Layer Discovery Protocol) information
  logging               Show system log
  mac                   Show MAC (FDB) entries
  management_interface  Show management interface parameters
  mgmt-vrf              Show management VRF attributes
  mirror_session        Show existing everflow sessions
  mmu                   Show mmu configuration
  muxcable              SONiC command line - 'show muxcable' command
  nat                   Show details of the nat
  ndp                   Show IPv6 Neighbour table
  ntp                   Show NTP information
  pfc                   Show details of the priority-flow-control (pfc)
  pfcwd                 Show details of the pfc watchdog
  platform              Show platform-specific hardware info
  policer               Show existing policers
  priority-group        Show details of the PGs
  processes             Display process information
  queue                 Show details of the queues
  radius                Show RADIUS configuration
  reboot-cause          Show cause of most recent reboot
  route-map             show route-map
  runningconfiguration  Show current running configuration information
  services              Show all daemon services
  sflow                 Show sFlow related information
  snmpagentaddress      Show SNMP agent listening IP address configuration
  snmptrap              Show SNMP agent Trap server configuration
  startupconfiguration  Show startup configuration information
  subinterfaces         Show details of the sub port interfaces
  system-health         SONiC command line - 'show system-health' command
  system-memory         Show memory information
  tacacs                Show TACACS+ configuration
  techsupport           Gather information for troubleshooting
  uptime                Show system uptime
  users                 Show users
  version               Show version information
  vlan                  Show VLAN information
  vnet                  Show vnet related information
  vrf                   Show vrf config
  vxlan                 Show vxlan related information
  warm_restart          Show warm restart configuration and state
  watermark             Show details of watermark
  ztp                   Show Zero Touch Provisioning status

**Comment by AkhileshSamineni** [comment]
Please check the config --help, not show --help.

**Comment by dgsudharsan** [comment]
@A

> Please check the config --help, not show --help.

Sorry for missing it out. Will close the bug. Thanks for clarification.
