### ISSUE TITLE
[hostcfgd] hoscfgd doesn't honor CFG DB updates if they arrive in a specific time interval

### ISSUE THREAD

**Issue by vivekrnv** [Azure/sonic-buildimage#8619]
#### Description

We have an internal test which invokes "config feature state sflow enabled" at around 92 sec after the boot and the update was never honored. The issue was narrowed down to the delayed start of hostcfgd (which starts at 90th sec). I'll explain with an example

Let say system boots up at 0th sec. hostcfg starts at 90th sec. The hostcfgd reads the FEATURE|* tables at 90th sec and acts on it accordingly for the next 10 seconds (i.e mask/unmask/enable/disable).  And it then starts listening to notifications of feature table from 100th sec. 

So, an update which is made before 90th sec and after 100th sec is honored. Updates made between 90th – 100th sec will not. 

#### Steps to reproduce the issue:
1. Make sure SFLOW feature state is disabled, save it. 
2. Write a one shot timer to start at 94 sec after boot up. Make it enable sflow using "config feature state sflow enabled"
3. Reboot the switch with one-shot timer in place.

#### Describe the results you received:

The update will not be honored

```
# Command was run on

2021-08-23 12:33:23 [    INFO]  Running cmd: sudo config feature state sflow enabled 


# Pre-notification listen phase i.e. https://github.com/Azure/sonic-buildimage/blob/202012/src/sonic-host-services/scripts/hostcfgd#L656 was active from 

12:33:22.986854  <->  12:33:34.245694 and thus the update was missed

Aug 23 12:33:22.986854 sonic INFO /hostcfgd: Waiting for systemctl to finish initialization
Aug 23 12:33:23.000117 sonic INFO /hostcfgd: systemctl has finished initialization -- proceeding ....

...............

................

Aug 23 12:33:33.421544 sonic INFO /hostcfgd: Feature 'lldp.service' is enabled and started
Aug 23 12:33:33.437933 sonic INFO /hostcfgd: Feature 'sflow' is stopped and disabled
..........

.........

Aug 23 12:33:34.234307 sonic INFO /hostcfgd: Running cmd: 'sudo systemctl start dhcp_relay.service'
Aug 23 12:33:34.245694 sonic INFO /hostcfgd: Feature 'dhcp_relay.service' is enabled and started
```

#### Describe the results you expected:

The update should be honored

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
Vivek will fix this issue.
