### ISSUE TITLE
[202012] [PR checks] Some KVM VS tests are failing

### ISSUE THREAD

**Issue by volodymyrsamotiy** [Azure/sonic-buildimage#8642]
#### Description

Below PR checks are failing for PRs created for ```202012``` sonic-buildimage branch.
* Azure.sonic-buildimage (Test kvmtest-t0) 
* Azure.sonic-buildimage (Test kvmtest-t1-lag)

Failures are observed in the following tests:
* [test_container_checker[vlab-03|teamd]](https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/32242/logs/62)
* [test_cpu_memory_usage[vlab-01]](https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/32242/logs/71)

#### Steps to reproduce the issue:
1. Create PR for sonic-buildimage ```202012``` branch
2. Wait until KVM PR checks failed
3. Observe mentioned tests failed

#### Describe the results you received:
Some KVM VS tests are failing for ```202012``` sonic-buildimage PRs

#### Describe the results you expected:
All PR checks should pass

#### Output of `show version`:

```
N/A
```
#### Output of `show techsupport`:

```
N/A
```

#### Additional information you deem important (e.g. issue happens only occasionally):

```
N/A
```

**Comment by lguohan** [comment]
@yozhao101 , can you check?

**Comment by yozhao101** [comment]
> @yozhao101 , can you check?

Thanks! I will check and figure out the reason.

**Comment by volodymyrsamotiy** [comment]
@lguohan , @yozhao101 
Could you please clarify if is there any progress?
Currently I see that all PRs in "sonic-buildimage" are failing and not only for "202012", but for "master" as well.
Thanks in advance.

**Comment by yozhao101** [comment]
> @lguohan , @yozhao101
> Could you please clarify if is there any progress?
> Currently I see that all PRs in "sonic-buildimage" are failing and not only for "202012", but for "master" as well.
> Thanks in advance.

We are actively working on fixing this issue.
