### ISSUE TITLE
Change hostname in minigraph.xml is not working

### ISSUE THREAD

**Issue by okanchou9** [Azure/sonic-buildimage#869]
Hi,

Would like to change the hostname of sonic by modifying the value of hostname in minigraph.xml and reboot to apply this modification.
But the hostname is still named "sonic" after reboot, I can only think this feature is broken.

The following link is the page that shows how to define the hostname of sonic device:

https://github.com/Azure/SONiC/wiki/Configuration-and-Minigraph

Sample format of Hostname:

<Hostname>switch1</Hostname>

Any suggestions would be helpful and let me know if any problem.

Regards,
Kenie Liu

**Comment by taoyl-ms** [comment]
Yes, change hostname through minigraph is not supported now.

I'll add support of this feature after migrating to config DB.
