### ISSUE TITLE
[Nokia][7215] SAI: ERROR HOST_INTERFACE

### ISSUE THREAD

**Issue by Blueve** [Azure/sonic-buildimage#8699]
#### Description

SAI: ERROR HOST_INTERFACE detected in syslog.

#### Steps to reproduce the issue:
1. Install image
2. Reboot and wait system up
3. `cat /var/log/syslog | grep ERR`

#### Describe the results you received:
```
Sep  7 07:22:05.554334 str2-7215-acs-1 INFO syncd#/supervisord: syncd ../xps/xpsFdb.c:1500, ERROR: Entry not found in table Error code : (23)
Sep  7 07:22:05.554871 str2-7215-acs-1 INFO syncd#syncd: ../xps/xpsFdb.c:1500, ERROR: Entry not found in table Error code : (23)
Sep  7 07:22:05.555770 str2-7215-acs-1 INFO syncd#/supervisord: syncd 07:22:05 SAI: ERROR NEIGHBOR xpSaiNeighbor.c:1668 : fdb get failed for mac ff:ff:ff:ff:ff:ff vlan 1000
Sep  7 07:22:05.646160 str2-7215-acs-1 INFO syncd#/supervisord: syncd 07:22:05 SAI: ERROR HOST_INTERFACE xpSaiHostInterface.c:1180 : Failed to set 6
Sep  7 07:22:05.647230 str2-7215-acs-1 INFO syncd#/supervisord: syncd 07:22:05 SAI: ERROR HOST_INTERFACE xpSaiHostInterface.c:1291 : Attr type not available
```

#### Describe the results you expected:
No such logs appear

#### Output of `show version`:
Use image: Image: https://dev.azure.com/mssonic/build/_build/results?buildId=33599&view=results

**Comment by Blueve** [comment]
https://github.com/Azure/sonic-swss/blob/master/orchagent/intfsorch.cpp#L1311

**Comment by yxieca** [comment]
The more concerning issue is that there seems to be a dependency that neighbor entry can only created with a known fdb entry.

All FF mac is used for direct broadcast feature.

**Comment by rajkumar38** [comment]
> The more concerning issue is that there seems to be a dependency that neighbor entry can only created with a known fdb entry.
> 
> All FF mac is used for direct broadcast feature.

Just to clarify, neighbor creation will not be failed, when FDB entry not found.
In this specific case, SDK is configured to flood in vlan.
Confusion is because of the log level. We will fix the log level.

**Comment by Blueve** [comment]
@rajkumar38 is this issue related to test_dir_bcast test failure?
```
>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E           {
E               "changed": true, 
E               "cmd": "ptf --test-dir ptftests dir_bcast_test.BcastTest --platform-dir /root/ptftests --platform remote -t 'testbed_type='\"'\"'t0-52'\"'\"';router_mac=u'\"'\"'50:e0:ef:7a:f1:d1'\"'\"';vlan_info='\"'\"'/root/vlan_info.txt'\"'\"'' --relax --debug info --log-file /tmp/dir_bcast.BcastTest.2021-09-12-11:32:56.log", 
E               "delta": "0:00:04.347232", 
E               "end": "2021-09-12 11:25:40.298195", 
E               "failed": true, 
E               "invocation": {
E                   "module_args": {
E                       "_raw_params": "ptf --test-dir ptftests dir_bcast_test.BcastTest --platform-dir /root/ptftests --platform remote -t 'testbed_type='\"'\"'t0-52'\"'\"';router_mac=u'\"'\"'50:e0:ef:7a:f1:d1'\"'\"';vlan_info='\"'\"'/root/vlan_info.txt'\"'\"'' --relax --debug info --log-file /tmp/dir_bcast.BcastTest.2021-09-12-11:32:56.log", 
E                       "_uses_shell": true, 
E                       "argv": null, 
E                       "chdir": "/root", 
E                       "creates": null, 
E                       "executable": null, 
E                       "removes": null, 
E                       "stdin": null, 
E                       "stdin_add_newline": true, 
E                       "strip_empty_ends": true, 
E                       "warn": true
E                   }
E               }, 
E               "msg": "non-zero return code", 
E               "rc": 1, 

```

**Comment by rajkumar38** [comment]
> @rajkumar38 is this issue related to test_dir_bcast test failure?
> 
> ```
> >           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
> E           RunAnsibleModuleFail: run module shell failed, Ansible Results =>
> E           {
> E               "changed": true, 
> E               "cmd": "ptf --test-dir ptftests dir_bcast_test.BcastTest --platform-dir /root/ptftests --platform remote -t 'testbed_type='\"'\"'t0-52'\"'\"';router_mac=u'\"'\"'50:e0:ef:7a:f1:d1'\"'\"';vlan_info='\"'\"'/root/vlan_info.txt'\"'\"'' --relax --debug info --log-file /tmp/dir_bcast.BcastTest.2021-09-12-11:32:56.log", 
> E               "delta": "0:00:04.347232", 
> E               "end": "2021-09-12 11:25:40.298195", 
> E               "failed": true, 
> E               "invocation": {
> E                   "module_args": {
> E                       "_raw_params": "ptf --test-dir ptftests dir_bcast_test.BcastTest --platform-dir /root/ptftests --platform remote -t 'testbed_type='\"'\"'t0-52'\"'\"';router_mac=u'\"'\"'50:e0:ef:7a:f1:d1'\"'\"';vlan_info='\"'\"'/root/vlan_info.txt'\"'\"'' --relax --debug info --log-file /tmp/dir_bcast.BcastTest.2021-09-12-11:32:56.log", 
> E                       "_uses_shell": true, 
> E                       "argv": null, 
> E                       "chdir": "/root", 
> E                       "creates": null, 
> E                       "executable": null, 
> E                       "removes": null, 
> E                       "stdin": null, 
> E                       "stdin_add_newline": true, 
> E                       "strip_empty_ends": true, 
> E                       "warn": true
> E                   }
> E               }, 
> E               "msg": "non-zero return code", 
> E               "rc": 1, 
> ```

This issue is nothing to do with test_dir_bcast failure. test_dir_bcast TC is passing for us. We validated with sonic-mgmt commit 1b53581d1d32239a5b133b8c9000c0911746e698.

**Comment by rajkumar38** [comment]
Below errors are seen while configuring COPP parameter "genetlink_name" and "genetlink_mcgrp_name". Looks like these are configured by sFlow trap group.
sFlow not supported in Marvell SAI and these errors are expected.
```
Sep  7 07:22:05.646160 str2-7215-acs-1 INFO syncd#/supervisord: syncd 07:22:05 SAI: ERROR HOST_INTERFACE xpSaiHostInterface.c:1180 : Failed to set 6
Sep  7 07:22:05.647230 str2-7215-acs-1 INFO syncd#/supervisord: syncd 07:22:05 SAI: ERROR HOST_INTERFACE xpSaiHostInterface.c:1291 : Attr type not available
```
We have replaced above errors with,
```
Sep 15 03:38:28.802874 str-marvell-acs-1 INFO syncd#/supervisord: syncd 03:38:28 SAI: ERROR HOST_INTERFACE xpSaiHostInterface.c:1180 : Attr 6 Not supported
Sep 15 03:38:28.803071 str-marvell-acs-1 INFO syncd#/supervisord: syncd 03:38:28 SAI: ERROR HOST_INTERFACE xpSaiHostInterface.c:1279 : Host Interface type 2 not supported
```
For below logs, we have fixed the log level,
```
Sep  7 07:22:05.554334 str2-7215-acs-1 INFO syncd#/supervisord: syncd ../xps/xpsFdb.c:1500, ERROR: Entry not found in table Error code : (23)
Sep  7 07:22:05.554871 str2-7215-acs-1 INFO syncd#syncd: ../xps/xpsFdb.c:1500, ERROR: Entry not found in table Error code : (23)
Sep  7 07:22:05.555770 str2-7215-acs-1 INFO syncd#/supervisord: syncd 07:22:05 SAI: ERROR NEIGHBOR xpSaiNeighbor.c:1668 : fdb get failed for mac ff:ff:ff:ff:ff:ff vlan 1000
```
Changes are part of PR #8762

**Comment by Blueve** [comment]
Thanks @rajkumar38 !
Yeah, we aware the sflow feature issue, it is expected.

For the `test_dir_bcast` test, the test case not changed after your commit. I will trouble shoot it on my side, thanks for your informtion.
