### ISSUE TITLE
[Nokia][7215] TestSfpApi failed due to type_abbrv_name not exists in transceiver_info_dict

### ISSUE THREAD

**Issue by Blueve** [Azure/sonic-buildimage#8745]
#### Description

TestSfpApi failed due to type_abbrv_name not exists in transceiver_info_dict

Three tests failed due to this issue:
- test_get_tx_bias
- test_tx_disable
- test_get_rx_power

If this key is not required for all platform, we might need update test case instead.

#### Steps to reproduce the issue:
1. Run platform test
2. Check result

#### Describe the results you received:
Test setup failure
```
KeyError: 'type_abbrv_name'
```

#### Describe the results you expected:
Test pass without error

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Blueve** [comment]
@dflynn-Nokia could you please take a look? 
Let's determine solution from a) add type_abbrv_name data  b) update test case

**Comment by dflynn-Nokia** [comment]
Taking a look now.

**Comment by dflynn-Nokia** [comment]
@Blueve : When I run test_sfp.py I do not see the KeyError failure for 'type_abbrv_name' that you are seeing. Can you share the sonic-mgmt commit id that you are set to? I am currently at commit 3e096cf1c45b91f96a658042134e03f960d9eb17 (9/10/21)

Note: I do see that indeed the type_abbrv_name key is not currently supported. I can add support for that if required.

**Comment by Blueve** [comment]
@dflynn-Nokia  The issue has been there for a long time... We are not upgrade our public image testbed recently, last repro happens on 202012.33599-ab07ba29d (Sep 4/21).

I think you can work on3e096cf1c45b91f96a658042134e03f960d9eb17.
I will upgrade our testbed image to 3e096cf1c45b91f96a658042134e03f960d9eb17

**Comment by Blueve** [comment]
Sorry... we don't have a build for 3e096cf1c45b91f96a658042134e03f960d9eb17

See here: https://sonic-build.azurewebsites.net/ui/sonic/pipelines/141/builds?branchName=202012
Maybe we can choice one image such as?
<html>
<body>


36022 | 20210913.1 | 202012 | Azure.sonic-buildimage.official.marvell-armhf | succeeded | 2021-09-13T04:00:33 | 2021-09-14T12:43:40 | 04fd5ed3ad | Build Link | Artifacts
-- | -- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by dflynn-Nokia** [comment]
I was referring to the commit id in the sonic-mgmt repo, not sonic-buildimage.
I created PR# [8772](https://github.com/Azure/sonic-buildimage/pull/8772) to deal with this.
