### ISSUE TITLE
Failed to build: pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by TyagiShailesh** [Azure/sonic-buildimage#8796]
202106 failing with the following errors:

st@sv-s32:~/sonic/sonic-buildimage$ make configure PLATFORM=mellanox
+++ Cheking platform/mellanox +++
+++ Making configure +++
BLDENV=stretch make -f Makefile.work configure
make[1]: Entering directory '/home/st/sonic/sonic-buildimage'
~/sonic/sonic-buildimage/src/sonic-build-hooks ~/sonic/sonic-buildimage
make[2]: Entering directory '/home/st/sonic/sonic-buildimage/src/sonic-build-hooks'
dpkg-deb: building package 'sonic-build-hooks' in 'buildinfo/sonic-build-hooks_1.0_all.deb'.
make[2]: Leaving directory '/home/st/sonic/sonic-buildimage/src/sonic-build-hooks'
~/sonic/sonic-buildimage
Image sonic-slave-stretch:49c2f9f8e10 not found. Building...
Sending build context to Docker daemon  47.62kB
Step 1/63 : FROM debian:stretch
 ---> 8701ac7aec56
Step 2/63 : MAINTAINER gulv@microsoft.com
 ---> Running in 6cd3061aed30
Removing intermediate container 6cd3061aed30
 ---> 6af686ef58c9
Step 3/63 : COPY ["no-check-valid-until", "/etc/apt/apt.conf.d/"]
 ---> 6ec2029ea37a
Step 4/63 : COPY ["buildinfo", "/usr/local/share/buildinfo"]
 ---> 2ad49af58e34
Step 5/63 : RUN dpkg -i /usr/local/share/buildinfo/sonic-build-hooks_1.0_all.deb
 ---> Running in b9a968a34516
Selecting previously unselected package sonic-build-hooks.
(Reading database ... 6502 files and directories currently installed.)
Preparing to unpack .../sonic-build-hooks_1.0_all.deb ...
Unpacking sonic-build-hooks (1.0) ...
Setting up sonic-build-hooks (1.0) ...
Removing intermediate container b9a968a34516
 ---> 110d444e9c8d
Step 6/63 : RUN pre_run_buildinfo
 ---> Running in a0047d9ede5d
Removing intermediate container a0047d9ede5d
 ---> 99ddb413675d
Step 7/63 : RUN echo "deb [arch=amd64] http://debian-archive.trafficmanager.net/debian/ stretch main contrib non-free" >> /etc/apt/sources.list &&         echo "deb-src [arch=amd64] http://debian-archive.trafficmanager.net/debian/ stretch main contrib non-free" >> /etc/apt/sources.list &&         echo "deb [arch=amd64] http://debian-archive.trafficmanager.net/debian-security/ stretch/updates main contrib non-free" >> /etc/apt/sources.list &&         echo "deb-src [arch=amd64] http://debian-archive.trafficmanager.net/debian-security/ stretch/updates main contrib non-free" >> /etc/apt/sources.list &&         echo "deb [arch=amd64] http://debian-archive.trafficmanager.net/debian stretch-backports main" >> /etc/apt/sources.list &&         echo "deb [arch=amd64] http://packages.trafficmanager.net/debian/debian stretch main contrib non-free" >> /etc/apt/sources.list &&         echo "deb [arch=amd64] http://packages.trafficmanager.net/debian/debian stretch-updates main contrib non-free" >> /etc/apt/sources.list &&         echo "deb [arch=amd64] http://packages.microsoft.com/debian/9/prod stretch main" >> /etc/apt/sources.list
 ---> Running in d05c01f4c872
Removing intermediate container d05c01f4c872
 ---> 873113ba6e42
Step 8/63 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Running in 74581eef66ba
Removing intermediate container 74581eef66ba
 ---> 1415ecffeb11
Step 9/63 : RUN apt-get update && apt-get install -y         apt-utils         default-jre-headless         openssh-server         curl         wget         unzip         git         build-essential         libtool         lintian         sudo         dh-make         dh-exec         kmod         libtinyxml2-4         libboost-program-options1.62-dev         libtinyxml2-dev         python         python-pip         python3-pip         libncurses5-dev         texinfo         dh-autoreconf         doxygen         devscripts         git-buildpackage         perl-modules         libswitch-perl         dh-systemd         libzmq5         libzmq3-dev         jq         libreadline-dev         texlive-latex-base         texlive-generic-recommended         texlive-fonts-recommended         libpam0g-dev         libpam-dev         libcap-dev         imagemagick         ghostscript         groff         libpcre3-dev         gawk         chrpath         libc-ares-dev         libsnmp-dev         libjson-c3         libjson-c-dev         libsystemd-dev         python-ipaddr         libcmocka-dev         python3-all-dev         python3-all-dbg         install-info         logrotate         cdbs         libxml-simple-perl         graphviz         aspell         bc         fakeroot         build-essential         devscripts         quilt         stgit         module-assistant         gem2deb         libboost-all-dev         libevent-dev         libglib2.0-dev         libqt4-dev         python-all-dev         python-twisted         phpunit         libbit-vector-perl         openjdk-8-jdk         javahelper         maven-debian-helper         ant         libmaven-ant-tasks-java         libhttpclient-java         libslf4j-java         libservlet3.1-java         qt5-default         pkg-php-tools         libpcre3         libpcre3-dev         byacc         flex         libglib2.0-dev         bison         expat         libexpat1-dev         dpatch         libdb-dev         iptables-dev         ctags         libtool-bin         libxml2-dev         libusb-1.0-0-dev         libcurl3-nss-dev         libunwind8-dev         telnet         libc-ares2         libgoogle-perftools4         cpio         squashfs-tools         zip         linux-compiler-gcc-6-x86         linux-kbuild-4.9         libdaemon-dev         libdbus-1-dev         libjansson-dev         libpcap-dev         dnsutils         libusb-dev         augeas-tools         libyaml-dev         libevent-dev         libjudy-dev         libedit-dev         libnanomsg-dev         python-stdeb         libjemalloc-dev         liblua5.1-0-dev         lua-bitop-dev          lua-cjson-dev         dkms         cppcheck         clang         pylint         python-pytest         gcovr         python-pytest-cov         python-parse         default-libmysqlclient-dev         libssl1.0-dev         libperl-dev         libpci-dev         libpci3         libsensors4         libsensors4-dev         libwrap0-dev 	debhelper         autotools-dev         libbsd-dev         pkg-config         check         docutils-common         libjs-sphinxdoc         libjs-underscore         python-docutils         python-jinja2         python-markupsafe         python-pygments         python-roman         python-sphinx         sphinx-common         python3-sphinx         python-dev         procmail         autoconf-archive         cm-super-minimal         libatm1-dev         libelf-dev         libmnl-dev         libselinux1-dev         linuxdoc-tools         lynx         texlive-latex-extra         texlive-latex-recommended         iproute2         texi2html         bash-completion         dosfstools         qemu-kvm         libvirt-clients         librrd8         librrd-dev         rrdtool         automake1.11         libselinux1-dev         liblzo2-dev         libnetfilter-conntrack-dev         libnftnl-dev         protobuf-compiler         libprotobuf-dev         xxd         libexplain-dev         libevent-dev         swig         autoconf         m4         libxml2-utils         xsltproc         python-lxml         libexpat1-dev
 ---> Running in 590cb4ec9eca
Err:1 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://packages.microsoft.com/debian/9/prod stretch InRelease
  Temporary failure resolving 'packages.microsoft.com'
Err:3 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:4 http://packages.trafficmanager.net/debian/debian stretch InRelease
  Temporary failure resolving 'packages.trafficmanager.net'
Err:5 http://debian-archive.trafficmanager.net/debian stretch InRelease
  Temporary failure resolving 'debian-archive.trafficmanager.net'
Err:6 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Err:7 http://debian-archive.trafficmanager.net/debian-security stretch/updates InRelease
  Temporary failure resolving 'debian-archive.trafficmanager.net'
Err:8 http://packages.trafficmanager.net/debian/debian stretch-updates InRelease
  Temporary failure resolving 'packages.trafficmanager.net'
Err:9 http://debian-archive.trafficmanager.net/debian stretch-backports InRelease
  Temporary failure resolving 'debian-archive.trafficmanager.net'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch/InRelease  Temporary failure resolving 'debian-archive.trafficmanager.net'
W: Failed to fetch http://debian-archive.trafficmanager.net/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'debian-archive.trafficmanager.net'
W: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch-backports/InRelease  Temporary failure resolving 'debian-archive.trafficmanager.net'
W: Failed to fetch http://packages.trafficmanager.net/debian/debian/dists/stretch/InRelease  Temporary failure resolving 'packages.trafficmanager.net'
W: Failed to fetch http://packages.trafficmanager.net/debian/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'packages.trafficmanager.net'
W: Failed to fetch http://packages.microsoft.com/debian/9/prod/dists/stretch/InRelease  Temporary failure resolving 'packages.microsoft.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package libpam0g-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpam-runtime

Package perl-modules is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  perl-base

Package texinfo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package install-info is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package bash-completion is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  util-linux mount bsdutils bash

Package apt-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apt

Package libpcre3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package cpio is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  tar

Package debhelper is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package dosfstools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'apt-utils' has no installation candidate
E: Unable to locate package default-jre-headless
E: Unable to locate package openssh-server
E: Unable to locate package curl
E: Unable to locate package wget
E: Unable to locate package unzip
E: Unable to locate package git
E: Unable to locate package build-essential
E: Unable to locate package libtool
E: Unable to locate package lintian
E: Unable to locate package sudo
E: Unable to locate package dh-make
E: Unable to locate package dh-exec
E: Unable to locate package kmod
E: Unable to locate package libtinyxml2-4
E: Unable to locate package libboost-program-options1.62-dev
E: Couldn't find any package by glob 'libboost-program-options1.62-dev'
E: Couldn't find any package by regex 'libboost-program-options1.62-dev'
E: Unable to locate package libtinyxml2-dev
E: Unable to locate package python
E: Unable to locate package python-pip
E: Unable to locate package python3-pip
E: Unable to locate package libncurses5-dev
E: Package 'texinfo' has no installation candidate
E: Unable to locate package dh-autoreconf
E: Unable to locate package doxygen
E: Unable to locate package devscripts
E: Unable to locate package git-buildpackage
E: Package 'perl-modules' has no installation candidate
E: Unable to locate package libswitch-perl
E: Unable to locate package dh-systemd
E: Unable to locate package libzmq5
E: Unable to locate package libzmq3-dev
E: Unable to locate package jq
E: Unable to locate package libreadline-dev
E: Unable to locate package texlive-latex-base
E: Unable to locate package texlive-generic-recommended
E: Unable to locate package texlive-fonts-recommended
E: Package 'libpam0g-dev' has no installation candidate
E: Unable to locate package libpam-dev
E: Unable to locate package libcap-dev
E: Unable to locate package imagemagick
E: Unable to locate package ghostscript
E: Unable to locate package groff
E: Package 'libpcre3-dev' has no installation candidate
E: Unable to locate package gawk
E: Unable to locate package chrpath
E: Unable to locate package libc-ares-dev
E: Unable to locate package libsnmp-dev
E: Unable to locate package libjson-c3
E: Unable to locate package libjson-c-dev
E: Unable to locate package libsystemd-dev
E: Unable to locate package python-ipaddr
E: Unable to locate package libcmocka-dev
E: Unable to locate package python3-all-dev
E: Unable to locate package python3-all-dbg
E: Package 'install-info' has no installation candidate
E: Unable to locate package logrotate
E: Unable to locate package cdbs
E: Unable to locate package libxml-simple-perl
E: Unable to locate package graphviz
E: Unable to locate package aspell
E: Unable to locate package bc
E: Unable to locate package fakeroot
E: Unable to locate package build-essential
E: Unable to locate package devscripts
E: Unable to locate package quilt
E: Unable to locate package stgit
E: Unable to locate package module-assistant
E: Unable to locate package gem2deb
E: Unable to locate package libboost-all-dev
E: Unable to locate package libevent-dev
E: Unable to locate package libglib2.0-dev
E: Couldn't find any package by glob 'libglib2.0-dev'
E: Couldn't find any package by regex 'libglib2.0-dev'
E: Unable to locate package libqt4-dev
E: Unable to locate package python-all-dev
E: Unable to locate package python-twisted
E: Unable to locate package phpunit
E: Unable to locate package libbit-vector-perl
E: Unable to locate package openjdk-8-jdk
E: Unable to locate package javahelper
E: Unable to locate package maven-debian-helper
E: Unable to locate package ant
E: Unable to locate package libmaven-ant-tasks-java
E: Unable to locate package libhttpclient-java
E: Unable to locate package libslf4j-java
E: Unable to locate package libservlet3.1-java
E: Couldn't find any package by glob 'libservlet3.1-java'
E: Couldn't find any package by regex 'libservlet3.1-java'
E: Unable to locate package qt5-default
E: Unable to locate package pkg-php-tools
E: Package 'libpcre3-dev' has no installation candidate
E: Unable to locate package byacc
E: Unable to locate package flex
E: Unable to locate package libglib2.0-dev
E: Couldn't find any package by glob 'libglib2.0-dev'
E: Couldn't find any package by regex 'libglib2.0-dev'
E: Unable to locate package bison
E: Unable to locate package expat
E: Unable to locate package libexpat1-dev
E: Unable to locate package dpatch
E: Unable to locate package libdb-dev
E: Unable to locate package iptables-dev
E: Unable to locate package ctags
E: Unable to locate package libtool-bin
E: Unable to locate package libxml2-dev
E: Unable to locate package libusb-1.0-0-dev
E: Couldn't find any package by glob 'libusb-1.0-0-dev'
E: Couldn't find any package by regex 'libusb-1.0-0-dev'
E: Unable to locate package libcurl3-nss-dev
E: Unable to locate package libunwind8-dev
E: Unable to locate package telnet
E: Unable to locate package libc-ares2
E: Unable to locate package libgoogle-perftools4
E: Package 'cpio' has no installation candidate
E: Unable to locate package squashfs-tools
E: Unable to locate package zip
E: Unable to locate package linux-compiler-gcc-6-x86
E: Unable to locate package linux-kbuild-4.9
E: Couldn't find any package by glob 'linux-kbuild-4.9'
E: Couldn't find any package by regex 'linux-kbuild-4.9'
E: Unable to locate package libdaemon-dev
E: Unable to locate package libdbus-1-dev
E: Unable to locate package libjansson-dev
E: Unable to locate package libpcap-dev
E: Unable to locate package dnsutils
E: Unable to locate package libusb-dev
E: Unable to locate package augeas-tools
E: Unable to locate package libyaml-dev
E: Unable to locate package libevent-dev
E: Unable to locate package libjudy-dev
E: Unable to locate package libedit-dev
E: Unable to locate package libnanomsg-dev
E: Unable to locate package python-stdeb
E: Unable to locate package libjemalloc-dev
E: Unable to locate package liblua5.1-0-dev
E: Couldn't find any package by glob 'liblua5.1-0-dev'
E: Couldn't find any package by regex 'liblua5.1-0-dev'
E: Unable to locate package lua-bitop-dev
E: Unable to locate package lua-cjson-dev
E: Unable to locate package dkms
E: Unable to locate package cppcheck
E: Unable to locate package clang
E: Unable to locate package pylint
E: Unable to locate package python-pytest
E: Unable to locate package gcovr
E: Unable to locate package python-pytest-cov
E: Unable to locate package python-parse
E: Unable to locate package default-libmysqlclient-dev
E: Unable to locate package libssl1.0-dev
E: Couldn't find any package by glob 'libssl1.0-dev'
E: Couldn't find any package by regex 'libssl1.0-dev'
E: Unable to locate package libperl-dev
E: Unable to locate package libpci-dev
E: Unable to locate package libpci3
E: Unable to locate package libsensors4
E: Unable to locate package libsensors4-dev
E: Unable to locate package libwrap0-dev
E: Package 'debhelper' has no installation candidate
E: Unable to locate package autotools-dev
E: Unable to locate package libbsd-dev
E: Unable to locate package pkg-config
E: Unable to locate package check
E: Unable to locate package docutils-common
E: Unable to locate package libjs-sphinxdoc
E: Unable to locate package libjs-underscore
E: Unable to locate package python-docutils
E: Unable to locate package python-jinja2
E: Unable to locate package python-markupsafe
E: Unable to locate package python-pygments
E: Unable to locate package python-roman
E: Unable to locate package python-sphinx
E: Unable to locate package sphinx-common
E: Unable to locate package python3-sphinx
E: Unable to locate package python-dev
E: Unable to locate package procmail
E: Unable to locate package autoconf-archive
E: Unable to locate package cm-super-minimal
E: Unable to locate package libatm1-dev
E: Unable to locate package libelf-dev
E: Unable to locate package libmnl-dev
E: Unable to locate package libselinux1-dev
E: Unable to locate package linuxdoc-tools
E: Unable to locate package lynx
E: Unable to locate package texlive-latex-extra
E: Unable to locate package texlive-latex-recommended
E: Unable to locate package texi2html
E: Package 'bash-completion' has no installation candidate
E: Package 'dosfstools' has no installation candidate
E: Unable to locate package qemu-kvm
E: Unable to locate package libvirt-clients
E: Unable to locate package librrd8
E: Unable to locate package librrd-dev
E: Unable to locate package rrdtool
E: Unable to locate package automake1.11
E: Couldn't find any package by glob 'automake1.11'
E: Couldn't find any package by regex 'automake1.11'
E: Unable to locate package libselinux1-dev
E: Unable to locate package liblzo2-dev
E: Unable to locate package libnetfilter-conntrack-dev
E: Unable to locate package libnftnl-dev
E: Unable to locate package protobuf-compiler
E: Unable to locate package libprotobuf-dev
E: Unable to locate package xxd
E: Unable to locate package libexplain-dev
E: Unable to locate package libevent-dev
E: Unable to locate package swig
E: Unable to locate package autoconf
E: Unable to locate package m4
E: Unable to locate package libxml2-utils
E: Unable to locate package xsltproc
E: Unable to locate package python-lxml
E: Unable to locate package libexpat1-dev
The command '/bin/sh -c apt-get update && apt-get install -y         apt-utils         default-jre-headless         openssh-server         curl         wget         unzip         git         build-essential         libtool         lintian         sudo         dh-make         dh-exec         kmod         libtinyxml2-4         libboost-program-options1.62-dev         libtinyxml2-dev         python         python-pip         python3-pip         libncurses5-dev         texinfo         dh-autoreconf         doxygen         devscripts         git-buildpackage         perl-modules         libswitch-perl         dh-systemd         libzmq5         libzmq3-dev         jq         libreadline-dev         texlive-latex-base         texlive-generic-recommended         texlive-fonts-recommended         libpam0g-dev         libpam-dev         libcap-dev         imagemagick         ghostscript         groff         libpcre3-dev         gawk         chrpath         libc-ares-dev         libsnmp-dev         libjson-c3         libjson-c-dev         libsystemd-dev         python-ipaddr         libcmocka-dev         python3-all-dev         python3-all-dbg         install-info         logrotate         cdbs         libxml-simple-perl         graphviz         aspell         bc         fakeroot         build-essential         devscripts         quilt         stgit         module-assistant         gem2deb         libboost-all-dev         libevent-dev         libglib2.0-dev         libqt4-dev         python-all-dev         python-twisted         phpunit         libbit-vector-perl         openjdk-8-jdk         javahelper         maven-debian-helper         ant         libmaven-ant-tasks-java         libhttpclient-java         libslf4j-java         libservlet3.1-java         qt5-default         pkg-php-tools         libpcre3         libpcre3-dev         byacc         flex         libglib2.0-dev         bison         expat         libexpat1-dev         dpatch         libdb-dev         iptables-dev         ctags         libtool-bin         libxml2-dev         libusb-1.0-0-dev         libcurl3-nss-dev         libunwind8-dev         telnet         libc-ares2         libgoogle-perftools4         cpio         squashfs-tools         zip         linux-compiler-gcc-6-x86         linux-kbuild-4.9         libdaemon-dev         libdbus-1-dev         libjansson-dev         libpcap-dev         dnsutils         libusb-dev         augeas-tools         libyaml-dev         libevent-dev         libjudy-dev         libedit-dev         libnanomsg-dev         python-stdeb         libjemalloc-dev         liblua5.1-0-dev         lua-bitop-dev          lua-cjson-dev         dkms         cppcheck         clang         pylint         python-pytest         gcovr         python-pytest-cov         python-parse         default-libmysqlclient-dev         libssl1.0-dev         libperl-dev         libpci-dev         libpci3         libsensors4         libsensors4-dev         libwrap0-dev 	debhelper         autotools-dev         libbsd-dev         pkg-config         check         docutils-common         libjs-sphinxdoc         libjs-underscore         python-docutils         python-jinja2         python-markupsafe         python-pygments         python-roman         python-sphinx         sphinx-common         python3-sphinx         python-dev         procmail         autoconf-archive         cm-super-minimal         libatm1-dev         libelf-dev         libmnl-dev         libselinux1-dev         linuxdoc-tools         lynx         texlive-latex-extra         texlive-latex-recommended         iproute2         texi2html         bash-completion         dosfstools         qemu-kvm         libvirt-clients         librrd8         librrd-dev         rrdtool         automake1.11         libselinux1-dev         liblzo2-dev         libnetfilter-conntrack-dev         libnftnl-dev         protobuf-compiler         libprotobuf-dev         xxd         libexplain-dev         libevent-dev         swig         autoconf         m4         libxml2-utils         xsltproc         python-lxml         libexpat1-dev' returned a non-zero code: 100
Unable to find image 'sonic-slave-stretch:49c2f9f8e10' locally
Error response from daemon: pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: No such container:path: sonic-slave-stretch:/etc/os-release
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/pre-versions
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/post-versions
Error: No such container: sonic-slave-stretch
Image sonic-slave-stretch-st:214dfc4e57a not found. Building...
Sending build context to Docker daemon  47.62kB
Step 1/18 : ARG slave_base_tag_ref=latest
Step 2/18 : FROM sonic-slave-stretch:${slave_base_tag_ref}
pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Unable to find image 'sonic-slave-stretch-st:214dfc4e57a' locally
docker: Error response from daemon: pull access denied for sonic-slave-stretch-st, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make[1]: *** [Makefile.work:293: configure] Error 125
make[1]: Leaving directory '/home/st/sonic/sonic-buildimage'
make: *** [Makefile:71: configure] Error 2

**Comment by TyagiShailesh** [comment]
It was docker network error.

**Comment by zhengbiqing** [comment]
I failed 3 times for this reason:

The command '/bin/sh -c git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /usr/share/depot_tools' returned a non-zero code: 128
Unable to find image 'sonic-slave-stretch:eb0558e0531' locally
Error response from daemon: pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: No such container:path: sonic-slave-stretch:/etc/os-release
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/pre-versions
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/post-versions
Error: No such container: sonic-slave-stretch
pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Unable to find image 'sonic-slave-stretch-zbq:ae7cc3083f7' locally
docker: Error response from daemon: pull access denied for sonic-slave-stretch-zbq, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make[1]: *** [Makefile.work:312: configure] Error 125
make: *** [Makefile:84: configure] Error 2


How to fix it?

**Comment by Xuanfq** [comment]
I encountered this too. How to fix it?
