### ISSUE TITLE
show techsupport fail when /usr/core folder not existing

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#8850]
#### Description
show techsupport fails on any platform not provided /usr/bin/hw-management-generate-dump.sh

#### Steps to reproduce the issue:
1. run "show techsupport" on platform didn't provide /usr/bin/hw-management-generate-dump.sh
2.
3.

#### Describe the results you received:
See log below

#### Describe the results you expected:
show techsupport should succeed.

#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.32
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-armmp
Build commit: d740d6ae05
Build date: Sun Sep 26 15:19:58 UTC 2021
Built by: AzDevOps@sonic-agent-arm64-02

Platform: armhf-nokia_ixs7215_52x-r0
HwSKU: Nokia-7215
ASIC: marvell
ASIC Count: 1
Serial Number: NK205210084
Uptime: 01:27:46 up  4:08,  1 user,  load average: 0.12, 0.23, 0.26
```
#### Output of `show techsupport`:
removed directory '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453/warmboot/teamd'
removed directory '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453/warmboot'
removed directory '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453'
handle_error $? $LINENO
ERR: RC:-1 observed on line 1224
HW Mgmt dump script /usr/bin/hw-management-generate-dump.sh does not exist
mkdir: created directory '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453'
mkdir: created directory '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453/log'
sonic_dump_str2-7215-acs-1_20210927_230453/log/techsupport_time_info.mdpRPlzew5
removed '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453/log/techsupport_time_info.mdpRPlzew5'
removed directory '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453/log'
removed directory '/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453'
/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453.tar:        90.6% -- replaced with /var/dump/sonic_dump_str2-7215-acs-1_20210927_230453.tar.gz
/var/dump/sonic_dump_str2-7215-acs-1_20210927_230453.tar.gz

real    2m7.188s
user    1m2.188s
sys     0m15.576s
admin@str2-7215-acs-1:~$ echo $?
1

**Comment by Blueve** [comment]
https://github.com/Azure/sonic-utilities/blob/826311cd366825c332a27799e1044509aa3d530e/scripts/generate_dump#L1277

The scripts shouldn't fail even `hw-management-generate-dump.sh` doesn't exists.

From the log `ERR: RC:-1 observed on line 1224` seems like the the issue were happens here:

https://github.com/Azure/sonic-utilities/blob/826311cd366825c332a27799e1044509aa3d530e/scripts/generate_dump#L1224

**Comment by yxieca** [comment]
The problem was introduced by this PR: https://github.com/Azure/sonic-utilities/pull/1833, when /var/core doesn't exist, the script will fail.

**Comment by yxieca** [comment]
https://github.com/Azure/sonic-utilities/pull/1723 for master

**Comment by yxieca** [comment]
https://github.com/Azure/sonic-utilities/pull/1843 pending merge for 202006.

**Comment by yxieca** [comment]
Above 3 PRs introduced error at line 1224 and line 196
