### ISSUE TITLE
Can't add route with a nexthop of a PortChannel

### ISSUE THREAD

**Issue by DavidZagury** [Azure/sonic-buildimage#8907]
#### Description

We no longer can add routes with a nexthop of a PortChannel.
This was possible until the refactor of add/del route functions in this PR - [config]Static routes to config_db (https://github.com/Azure/sonic-utilities/pull/1534)

#### Steps to reproduce the issue:
1. config portchannel add PortChannel0001
2. sudo config route add prefix 20.0.0.1/32 nexthop PortChannel0001

#### Describe the results you received:
Command fails with error:
`Error: ip address is not valid.
`
#### Describe the results you expected:
Command succeed and route added successfully. 
Route should be appear in "show ip route" output.

#### Additional information you deem important (e.g. issue happens only occasionally):
This was possible until the refactor of add/del route functions in this PR - [config]Static routes to config_db (https://github.com/Azure/sonic-utilities/pull/1534)

**Comment by d-dashkov** [comment]
Started looking into it
