### ISSUE TITLE
`fwutil update all` incorrectly autocompletes to `fwutil update auto`

### ISSUE THREAD

**Issue by alexrallen** [Azure/sonic-buildimage#8925]
#### Description

The click library uses the names of functions to assist in the generation of CLI auto-complete trees. In `fwutil update` the method for updating all available firmware is `auto_update`

See here: https://github.com/Azure/sonic-utilities/blob/1029c5487dd1190215dae6ca557d6feb96113c9d/fwutil/main.py#L406
```
# 'auto_update' group
@click.group()
@click.pass_context
def auto_update(ctx):
    """Auto-update platform firmware"""
    pass
```

This is causing click to mistakenly label the command as `auto` instead of `all` as defined lower in the file. **Renaming this function to `all_update` resolves this problem.**

#### Steps to reproduce the issue:
1. Type `fwutil update`
2. Hit `tab`

#### Describe the results you received:
```
root@r-qa-sw-eth-21101:/home/admin# fwutil update 
auto     chassis  module  
```

#### Describe the results you expected:
```
root@r-qa-sw-eth-21101:/home/admin# fwutil update 
all    chassis  module  
```

**Comment by dgsudharsan** [comment]
@sujinmkang  FYI
