### ISSUE TITLE
`fwutil update all` does not print `fw_au_status` file in human-readable format

### ISSUE THREAD

**Issue by alexrallen** [Azure/sonic-buildimage#8926]
#### Description

When the `fwutil update all` command is run and it generates a `fw_au_status` file for tracking upgrade status, it does not create it in a human readable format. This is important because users are intended to reference this file to check the status of their firmware upgrades.

#### Steps to reproduce the issue:
1. Setup `platform_components.json`

```
{
    "chassis": {
        "MSN2410": {
            "component": {
                "ONIE": {                },
                "SSD": {                },
                "BIOS": { },
                "CPLD1": {                         
                        "firmware": "/lib/firmware/CPLD_older.mpfa"
                },
                "CPLD2": { 
                        "firmware": "/lib/firmware/CPLD_older.mpfa"
                },
                "CPLD3": {
                        "firmware": "/lib/firmware/CPLD_older.mpfa"
                }
            }
        }
    }
}
```

2. Run `fwutil update all fw --boot=cold`

#### Describe the results you received:
```
root@r-qa-sw-eth-21101:/home/admin# cat /var/platform/fw_au_status 
{"cold": [{"comp": "MSN2410/CPLD1", "status": false, "info": "err_others"}, {"comp": "MSN2410/CPLD3", "status": false, "info": "err_others"}]}
```

Status is referred to as "false" and info message is not useful for debugging. Would also much prefer pretty-printing the JSON so that it can be easily parsed when printed on a terminal screen. 

#### Describe the results you expected:
```
{
    "MSN2700/BIOS":
        {
            "status": "updated",
            "from": "0ACLH004_02.02.007",
            "to": "0ACLH004_02.02.010",
            "info": "completed"
        },
    "MSN2700/SSD":
        {
            "status": "scheduled",
            "from": "4",
            "to": "5",
            "info": "installation scheduled for warm reboot"
        },
    "MSN2700/CPLD1":
        {
            "status": "skipped",
            "from": "5",
            "to": "10",
            "info": "warm reboot not supported for auto-update"
        }
    ]
}
```

This should be the response we get per the HLD. Informative and easy to read.

**Comment by dgsudharsan** [comment]
@sujinmkang  FYI

**Comment by sujinmkang** [comment]
@alexrallen I think it would be better to have readable fw_au_status but you can check update status using "fwutil show update status" to check the status(refer to https://github.com/Azure/SONiC/blob/master/doc/fwutil/fwutil.md)? can you use it for now to check the update status?

**Comment by alexrallen** [comment]
For now, yes this is non-functional. However from a quality perspective we should have any output to the terminal be human readable.
