### ISSUE TITLE
problem for ifconfig down/up a (front pannel) interface with ip6 address

### ISSUE THREAD

**Issue by zhenggen-xu** [Azure/sonic-buildimage#896]
The configured global ip6 interface will be gone.

**Comment by lguohan** [comment]
option introduced first here. 

https://github.com/torvalds/linux/commit/f1705ec197e705b79ea40fe7a2cc5acfa1d3bfac

Then, later reverted 

https://github.com/torvalds/linux/commit/841645b5f2dfceac69b78fcd0c9050868d41ea61

**Comment by lguohan** [comment]
better to have a service to monitor the link event and assign v6 address back to the internal after it came up back.

**Comment by lguohan** [comment]
this only happens when you use ifconfig to shutdown the link, it does not happen when the physical link loss carrier.

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-buildimage/pull/1992 resolved
