### ISSUE TITLE
[DPB] Unable to breakout a port on Mellanox SN2700

### ISSUE THREAD

**Issue by tw0byt3** [Azure/sonic-buildimage#8993]
**Description:**

The Dynamic Port Breakout feature is not working as expected on the latest master image

**Describe the results you received:**

config interface breakout Ethernet0 4x10G[25G] -y

Running Breakout Mode : 1x100G[50G,40G,25G,10G]

Target Breakout Mode : 4x10G[25G]

Ports to be deleted :
 {
    "Ethernet0": "100000"
}
Ports to be added :
 {
    "Ethernet0": "10000",
    "Ethernet1": "10000",
    "Ethernet2": "10000",
    "Ethernet3": "10000"
}

After running Logic to limit the impact

Final list of ports to be deleted :
 {
    "Ethernet0": "100000"
}
Final list of ports to be added :
 {
    "Ethernet0": "10000",
    "Ethernet1": "10000",
    "Ethernet2": "10000",
    "Ethernet3": "10000"
}
Note: Below table(s) have no YANG models:
KDUMP, MCLAG_DOMAIN, MCLAG_INTERFACE, MCLAG_UNIQUE_IP, SNMP, SNMP_COMMUNITY, XCVRD_LOG,
sonic_yang(3):All Keys are not parsed in FEATURE
dict_keys(['dhcp_relay'])
sonic_yang(3):exceptionList:["'set_owner'"]
sonic_yang(3):Data Loading Failed:All Keys are not parsed in FEATURE
dict_keys(['dhcp_relay'])
Data Loading Failed
All Keys are not parsed in FEATURE
dict_keys(['dhcp_relay'])
ConfigMgmt Class creation failed
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed

**Describe the results you expected:**

config interface breakout <intf> <mode> should work without errors

**Comment by stepanblyschak** [comment]
https://github.com/Azure/sonic-buildimage/pull/9276
