### ISSUE TITLE
[bullseye] fdisk and gpg missing from host

### ISSUE THREAD

**Issue by alexrallen** [Azure/sonic-buildimage#9011]
**THIS IS A BUG TARGETING the Debian 11 / Kernel 5.10 UPGRADE** 

#### Description
The packages `fdisk` and `gpg` are missing from the host image. They were previously present in buster. 

This is currently breaking `fwutil` which assumes these packages will be present. 

Manual installation of these packages fixes the `fwutil` flow. 

#### Steps to reproduce the issue:
1. Run `show platform firmware status` on a Mellanox switch

#### Describe the results you received:
```
Error: Command 'mount -n -r -t ext4 /bin/sh: 1: fdisk: not found /mnt/onie-fs' returned non-zero exit status 1.. Aborting...
Aborted!
```

#### Describe the results you expected:
Should return the expected output for this command.

**Comment by saiarcot895** [comment]
This will be fixed in my PR.
