### ISSUE TITLE
[bullseye] kdump-tools is not built

### ISSUE THREAD

**Issue by alexrallen** [Azure/sonic-buildimage#9096]
**THIS IS A BULLSEYE ISSUE ONLY AND NOT PRESENT IN MASTER**

#### Description

`target/debs/bullseye/kdump-tools_1.6.1-1.deb` is not being built which is causing issues with kdump on the switch as the file `/etc/default/kdump-tools` is not present so `sonic-kdump-config` fails

Log from build....
```
sonic-mellanox.bin.log:5058:dpkg: error: cannot access archive 'target/debs/bullseye/kdump-tools_*.deb': No such file or directory
```

#### Steps to reproduce the issue:
1. Run `sonic-kdump-conifg --enable`

#### Describe the results you received:
```
Unable to read USE_KDUMP from /etc/default/kdump-tools
```

#### Describe the results you expected:
Successfully enable kdump

**Comment by saiarcot895** [comment]
This is fixed in my current Bullseye PR.

**Comment by lguohan** [comment]
@saiarcot895 , can you link this issue with your pr?
