### ISSUE TITLE
[CBF][Yang] Create yang model for the following: "DSCP_TO_FC_MAP" "EXP_TO_FC_MAP"

### ISSUE THREAD

**Issue by smaheshm** [Azure/sonic-buildimage#9108]
#### Steps to reproduce the issue:
[New feature]

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@TACappleman  please help to take a look at this PR

**Comment by smaheshm** [comment]
https://github.com/Azure/sonic-buildimage/pull/9116
