### ISSUE TITLE
Build sonic-marvell-arm64.bin fail because ImportError: No module named mock  

### ISSUE THREAD

**Issue by seanwu-ec** [Azure/sonic-buildimage#9115]
#### Description
Build sonic-marvell-arm64.bin fail because ImportError: No module named mock 
I think that "RUN pip2 install mock==3.0.5" should be added to sonic-slave-stretch/Dockerfile.j2 , just like Buster's.

#### Steps to reproduce the issue:
1. checkout commit https://github.com/Azure/sonic-buildimage/commit/4e0c4fb8327893f6e153c1d14794c221f70a3bc1
2. make init
3. make configure PLATFORM=marvell-arm64 PLATFORM_ARCH=arm64
4. make target/sonic-marvell-arm64.bin

#### Describe the results you received:
Build log:
[sonic_config_engine-1.0-py2-none-any.whl_unittest_fail.txt](https://github.com/Azure/sonic-buildimage/files/7439410/sonic_config_engine-1.0-py2-none-any.whl_unittest_fail.txt)

#### Describe the results you expected:
Build successful and sonic-marvell-arm64.bin generated.

#### Output of `show version`:

```
NA
```
#### Output of `show techsupport`:

```
NA
```

**Comment by zhangyanzhao** [comment]
https://github.com/Azure/sonic-buildimage/commit/56049830fb8e0bbf2eb08587ad9628789eac15b3 could fix this issue.

**Comment by lguohan** [comment]
marvel has moved the syncd docker to buster, this issue should be addressed.
