### ISSUE TITLE
Fix `python setup.py --name`

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-buildimage#9127]
Good catch! It is working now, and I will fix later in anther PR.

_Originally posted by @qiluo-msft in https://github.com/Azure/sonic-buildimage/pull/9111#discussion_r739602328_

**Comment by saiarcot895** [comment]
I ended up fixing this in #8191, in commit a1d30e3aa06991e8f2679c641eb1eaac2f7bfe92. That change was needed to get Bullseye working.

**Comment by qiluo-msft** [comment]
Thanks @saiarcot895!
