### ISSUE TITLE
translate_acl is not working

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#913]
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig Traceback (most recent call last):
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig   File "/usr/local/bin/translate_acl", line 8, in <module>
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig     import openconfig_acl 
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig   File "/usr/local/lib/python2.7/dist-packages/openconfig_acl.py", line 16, in <module>
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig     from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig   File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/yangtypes.py", line 30, in <module>
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig     import six
Aug 24 16:03:20.0 str-a7050-acs-1 INFO supervisord: swssconfig ImportError: No module named six

**Comment by lguohan** [comment]
admin@str-a7050-acs-1:~$ show version
SONiC Software Version: SONiC.HEAD.172-d918b13
Distribution: Debian 8.9
Kernel: 3.16.0-4-amd64
Build commit: d918b13
Build date: Thu Aug 24 12:03:09 UTC 2017
Built by: sonicbld@jenkins-slave-phx-1

**Comment by taoyl-ms** [comment]
The reason for this issue is that `pyangbind` publish a new version 0.6.0 at 2017-08-16 which includes a new dependency (`six`). I'll modify dockerfile and explicitly install `pyangbind` version 0.5.10 to avoid this issue.
