### ISSUE TITLE
Error:server certificate verification failed when build sonic bin

### ISSUE THREAD

**Issue by AntheaJiang** [Azure/sonic-buildimage#9147]
Hello there:

When I build sonic bin, the error messages will show since October , :
fatal: unable to access 'https://salsa.debian.org/kernel-team/initramfs-tools.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

I can avoid the error message by copying debs from other project which was compiled successfully  ,but errors still exist when I git clone new code from git.
so how can I solve this problem? "export GIT_SSL_NO_VERIFY=1 " or "git config --global http.sslVerify false" don't work for me.

**Comment by abhiranjeet** [comment]
Hi,

I am facing this same issue. I made the change in dockerfile mentioned above. But the error still persists. Any suggestions ?

Thanks !

**Comment by AntheaJiang** [comment]
You should put "RUN export GIT_SSL_NO_VERIFY=1" at the position like other "RUN xxx" sentence, not at the beginning of Docker,j2

**Comment by abhiranjeet** [comment]
Yes, I added another line "RUN export GIT_SSL_NO_VERIFY=1", not at the beginning.

**Comment by AntheaJiang** [comment]
> Yes, I added another line "RUN export GIT_SSL_NO_VERIFY=1", not at the beginning.

Sorry,can't login because of network until today,have you solve this issue? I have no idea why don't work for you.
