### ISSUE TITLE
Bunch of docker container is missing??

### ISSUE THREAD

**Issue by mbze430** [Azure/sonic-buildimage#9189]
#### Description

None of the physical port works

#### Steps to reproduce the issue:
1. show interfaces status - shows all ports are down regardless
2. sudo config interface startup [interface name] - doesn't do anything.
3.

#### Describe the results you received:
all ports down.  However the log show the following:
Nov  7 07:56:47.398702 localhost DEBUG /disk_check.py: /etc is Read-Write
Nov  7 07:56:47.400355 localhost DEBUG /disk_check.py: /home is Read-Write
Nov  7 07:57:08.353551 localhost ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception du
ring update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", l
ine 43, in start#012    self.update_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py",
line 232, in update_data#012    mibs.counter_table(sai_id), blocking=True)#012  File "/usr/lib/python3/dist-packages/swsscommon/sw
sscommon.py", line 1709, in get_all#012    return dict(super(SonicV2Connector, self).get_all(db_name, _hash, blocking))#012  File
"/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1663, in get_all#012    return _swsscommon.SonicV2Connector_Native
_get_all(self, db_name, _hash, blocking)#012RuntimeError: Key '{COUNTERS:oid:0x1000000000012}' unavailable in database '{COUNTERS_
DB}'
Nov  7 07:57:47.276878 localhost ERR monit[493]: 'container_checker' status failed (3) -- Expected containers not running: dhcp_re
lay, teamd, swss

#### Describe the results you expected:

Ports to be turned on
#### Output of `show version`:
SONiC Software Version: SONiC.202106.49071-99724508f
Distribution: Debian 10.11
Kernel: 4.19.0-12-2-amd64
Build commit: 99724508f
Build date: Sat Nov  6 14:17:22 UTC 2021
Built by: AzDevOps@sonic-build-workers-000V6W

Platform: x86_64-cel_seastone-r0
HwSKU: Seastone-DX010
ASIC: broadcom
ASIC Count: 1
Serial Number: DX010B2F108423LK100045
Model Number: R0872-F0010-01
Hardware Revision: N/A
Uptime: 08:13:42 up  9:17,  1 user,  load average: 0.32, 0.45, 0.53

Docker images:
REPOSITORY                    TAG                      IMAGE ID            SIZE
docker-dhcp-relay             latest                   493d6af95b08        428MB
docker-fpm-frr                202106.49071-99724508f   2c153b1832f7        451MB
docker-fpm-frr                latest                   2c153b1832f7        451MB
docker-sflow                  202106.49071-99724508f   17c02db2c16a        433MB
docker-sflow                  latest                   17c02db2c16a        433MB
docker-platform-monitor       202106.49071-99724508f   00f4d200e9b2        636MB
docker-platform-monitor       latest                   00f4d200e9b2        636MB
docker-snmp                   202106.49071-99724508f   a5dcbe20bf5a        462MB
docker-snmp                   latest                   a5dcbe20bf5a        462MB
docker-teamd                  202106.49071-99724508f   39a50d7e94b9        432MB
docker-teamd                  latest                   39a50d7e94b9        432MB
docker-nat                    202106.49071-99724508f   8ec973df9c10        435MB
docker-nat                    latest                   8ec973df9c10        435MB
docker-macsec                 202106.49071-99724508f   ea950a780631        436MB
docker-macsec                 latest                   ea950a780631        436MB
docker-lldp                   202106.49071-99724508f   66d6ed7314ff        461MB
docker-lldp                   latest                   66d6ed7314ff        461MB
docker-database               202106.49071-99724508f   eb4c7c474313        421MB
docker-database               latest                   eb4c7c474313        421MB
docker-router-advertiser      202106.49071-99724508f   4c372686f764        421MB
docker-router-advertiser      latest                   4c372686f764        421MB
docker-orchagent              202106.49071-99724508f   fcf98bb4033a        451MB
docker-orchagent              latest                   fcf98bb4033a        451MB
docker-sonic-mgmt-framework   202106.49071-99724508f   2196c5566412        576MB
docker-sonic-mgmt-framework   latest                   2196c5566412        576MB
docker-sonic-telemetry        202106.49071-99724508f   8d3cb062e469        509MB
docker-sonic-telemetry        latest                   8d3cb062e469        509MB
docker-syncd-brcm             202106.49071-99724508f   31a0d4a8ec84        717MB
docker-syncd-brcm             latest                   31a0d4a8ec84        717MB

**Comment by zhangyanzhao** [comment]
@mbze430  please provide more detail on the repro steps. Looks like the dockers are there, but not running.

**Comment by mbze430** [comment]
You can close it.  i ended uninstalling (clear out) SONiC and reloading it.  I haven't had those type of error message in the log since.
