### ISSUE TITLE
ECMP hash is not configured as expected for IPv4 packets

### ISSUE THREAD

**Issue by Xichen96** [Azure/sonic-buildimage#9236]
#### Description

A failed fib test indicates that, IPv4 TCP packets with the same src IP, dst IP but different src port and dst port are not transmitted through different network interfaces as expected. Looks like only L3 hash is used for IPv4 packets and not L4. IPv6 packets are routed through L4 hash.

#### Steps to reproduce the issue:
1. Construct multiple TCP packets with the same IPv4 IP and different src port and dst port
2. Send packet to switch
3. Check for packets transmitted statistics on switch

#### Describe the results you received:
Packets are routed though only one output interface.

#### Describe the results you expected:
Packets routed should be balanced across different output interfces.

#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.41
Distribution: Debian 10.11
Kernel: 4.19.0-12-2-amd64
Build commit: 84eefd6578
Build date: Sat Oct 30 10:02:58 UTC 2021
Built by: cloudtest@3cfd51cec000000Platform: x86_64-cel_e1031-r0
HwSKU: Celestica-E1031-T48S4
ASIC: broadcom
ASIC Count: 1
Serial Number: R0882F2B039723BY000014
Uptime: 20:29:24 up 7 min, 2 users, load average: 5.04, 4.59, 2.44


```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Blueve** [comment]
Failed tests are:
```
FAILED fib/test_fib.py::test_basic_fib[True-True-1514] - Exception
FAILED fib/test_fib.py::test_hash[ipv4] - Exception
```

**Comment by Blueve** [comment]
To be verify in our testbed
