### ISSUE TITLE
Clean up Mellanox issue_version and MFT Makefiles

### ISSUE THREAD

**Issue by alexrallen** [Azure/sonic-buildimage#9279]
Due to the Mellanox SDK / SAI / syncd not supporting bullseye currently we have introduced a couple of workarounds for a few packages in the mellanox platform.

Namely in `issue_version` and `MFT` Makefiles we add checks to determine which build environment is currently active (buster / bullseye) and make build decisions based on that.

This issue is to track the removal of these workarounds once these packages are upgraded and capable of being run on the host in bullseye.

**Comment by qiluo-msft** [comment]
Another issue: why BLDENV is not usable in `platform/mellanox/mft/Makefile` ?
