### ISSUE TITLE
based on the following issues and prs, looks like the warning message can be skipped, using the newer version is good.

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-buildimage#9318]
@qiluo-msft , based on the following issues and prs, looks like the warning message can be skipped, using the newer version is good.
Maybe we can improve the test case, explicitly ignore the warning.
https://github.com/redis/redis-py/pull/1726/files
https://github.com/redis/redis-py/issues/1725
https://github.com/redis/redis-py/pull/1721

_Originally posted by @xumia in https://github.com/Azure/sonic-buildimage/pull/9317#issuecomment-973503702_

**Comment by qiluo-msft** [comment]
@xumia Thanks for the suggestion! I am working on it.

**Comment by zhangyanzhao** [comment]
handled already
