### ISSUE TITLE
no docker-ptf-saithrift after branch 202006 

### ISSUE THREAD

**Issue by 119064273** [Azure/sonic-buildimage#9321]
#### Description
    I want to test sonic-mgmt/test/qos/test_qos_sai.py on sonic branch 202106   
    but it need saithrift related module, since after 202006 docker-ptf-saithrift is removed,
 I try to use the old docker-ptf-saithrift , but some modules's version not match,   help help !
    does any way to test sonic-mgmt/test/qos/test_qos_sai.py on sonic branch 202106?

**Comment by 119064273** [comment]
@lguohan @yingxie2021 @lixinxu  can you give some advice?

**Comment by zhangyanzhao** [comment]
build issue which need be fixed

**Comment by zhangyanzhao** [comment]
Richard, please check with build team on this issue. Thanks.

**Comment by richardyu-ms** [comment]
copy on that. @zhangyanzhao 

I am not sure so about the status of docker docker-ptf-saithrift, i started my work from 202012 branch, and do not get touch with that docker, docker-ptf-saithrift. 

For testing purpose, we use the docker-ptf directly, for sai related testing we are using and will use docker-saiserver as client and  docker-ptf as the testing server side.
@119064273 do you ever check that two dockers?
meanwhile, what's your expectation from docker docker-ptf-saithrift?

thanks.

**Comment by 119064273** [comment]
@richardyu-ms , when we use sonic-mgmt to test qos, we found qos_sai test need  saithrift switch ... ,  how do you test it ?

**Comment by msosyak** [comment]
You need to use regular docker-ptf. it contains PYTHON_SAITHRIFT package.

https://github.com/Azure/sonic-buildimage/blob/master/platform/vs/docker-ptf.mk#L5

**Comment by 119064273** [comment]
confirm. close
