### ISSUE TITLE
Incorrect CLI validation for unsupported speed

### ISSUE THREAD

**Issue by ihorchekh** [Azure/sonic-buildimage#9327]
#### Description

Setting unsupported speed on interface results in an error, however, when setting speed using the same digits like any supported speed the error doesn't appear, e.g. speed 50000 is supported and if we try to set speed 500 which is not supported and we'll get no errors, but 499 or 501 causes an error. This is not a functional issue and it doesn't set up unsupported speed, but the error should be shown.

#### Steps to reproduce the issue:

1. Run cmd "sudo config interface speed Ethernet0 499"
2. Run cmd "sudo config interface speed Ethernet0 500"

#### Describe the results you received:

1. Invalid speed specified: 499
Valid speeds:200000,100000,50000,40000,25000,10000,1000
2. No error

#### Describe the results you expected:
Error in step 2 - the same as in step 1

#### Output of `show version`:

```
SONiC.202106_rc_4_20211103.2-0a17680cd_Internal
```
#### Output of `show techsupport`:

[sonic_dump_r-anaconda-51_20211111_122328.tar.gz](https://github.com/Azure/sonic-buildimage/files/7570447/sonic_dump_r-anaconda-51_20211111_122328.tar.gz)

**Comment by MaratGubaiev** [comment]
Fixed https://github.com/Azure/sonic-utilities/pull/1946

**Comment by zhangyanzhao** [comment]
Please double check whether this is fixed.

**Comment by MaratGubaiev** [comment]
> Please double check whether this is fixed.

It is already fixed.
See https://github.com/Azure/sonic-utilities/pull/1952
