### ISSUE TITLE
bad udp checksums found when sending a DHCPDISCOVER packet to SONiC switch(enable DHCP relay)

### ISSUE THREAD

**Issue by okanchou9** [Azure/sonic-buildimage#933]
Hi,

When I configured the DHCP server information on minigraph.xml and setup a DHCP client(ubuntu) to send out the DHCPDISCOVER packet to test the DHCP relay but get bad udp checksums error message in /var/log/syslog:

Sep  4 08:04:56.0 sonic INFO dhcrelay: 7 bad udp checksums in 13 packets

Would like to know is the DHCP relay feature is working now or not.

Sample minigraph.xml(Only DHCP part):

`<VlanInterfaces>
        <VlanInterface>
          <Name>Vlan1000</Name>
          <AttachTo>Ethernet0;Ethernet4;Ethernet8;Ethernet12;Ethernet16;Ethernet20;Ethernet24;Ethernet28;Ethernet32;Ethernet36;Ethernet40;Ethernet44;Ethernet48;Ethernet52;Ethernet56;Ethernet60;Ethernet64;Ethernet68;Ethernet72;Ethernet76;Ethernet80;Ethernet84;Ethernet88;Ethernet92;Ethernet96;Ethernet100;Ethernet104;Ethernet108</AttachTo>
          <NoDhcpRelay>False</NoDhcpRelay>
          <StaticDHCPRelay>0.0.0.0/0</StaticDHCPRelay>
          <Type i:nil="true"/>
          <VlanID>1000</VlanID>
          <Tag>1000</Tag>
          <Subnets>192.168.0.0/27</Subnets>
        </VlanInterface>
</VlanInterfaces>`

`<a:DeviceProperty>
            <a:Name>DhcpResources</a:Name>
            <a:Reference i:nil="true"/>
            <a:Value>10.0.0.1;10.0.0.3;10.0.0.5;10.0.0.7</a:Value>
</a:DeviceProperty>`

---
Regards,
Kenie Liu

**Comment by jleveque** [comment]
DHCP relay agent should be currently working. Am I correct to assume the DHCP handshake not completing? Have you determined that the packets with bad UDP checksums are the DHCPDISCOVER packets coming from the client or are they DHCPOFFER packets coming back from the server? Would it be possible to try a different client?

**Comment by okanchou9** [comment]
Hi jleveque,

- Am I correct to assume the DHCP handshake not completing?

Kenie: No, I think the DHCP handshaking wasn't executed since SONiC switch recognized this DHCPDISCOVER packet as an illegal packet due to bad UDP checksums. Also I didn't see SONiC switch relay the DHCPDISCOVER  packet to DHCP server, too.

- Have you determined that the packets with bad UDP checksums are the DHCPDISCOVER packets coming from the client or are they DHCPOFFER packets coming back from the server?

- Would it be possible to try a different client?

Kenie: Yes, please refer the attachment for the pcap file that I captured on SONiC switch. I tried 3 different devices(a docker PTF provided by sonic-buildimage, an Ubuntu server and a switch) to send out DHCPDISCOVER packet but all got bad udp checksums in syslog. I'm sure all DHCPDISCOVER packets sent from 3 devices are correct without any issue.

[Capture.zip](https://github.com/Azure/sonic-buildimage/files/1283261/Capture.zip)

**Comment by jleveque** [comment]
Hi Kenie,

Could you please run tcpdump simultaneously on both the client and the SONiC switch and capture a DHCPDISCOVER packet being sent? I'd like to compare the packets and their checksums on both devices. Thanks.

**Comment by jleveque** [comment]
@okanchou9: Since you have not responded in over two years, I am assuming this issue is resolved. Please feel free to reopen the issue if need be.
