### ISSUE TITLE
[yang-models] BGP neighbor admin_status should be up/down

### ISSUE THREAD

**Issue by ganglyu** [Azure/sonic-buildimage#9350]
#### Description

src/sonic-yang-models/yang-models/sonic-bgp-common.yang needs to be updated.

#### Describe the results you received:
    leaf admin_status {
        type boolean;
        description "To enable BGP peer";
    }

#### Describe the results you expected:
    leaf admin_status {
        type stypes:admin_status;
    }

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ganglyu** [comment]
@venkatmahalingam

**Comment by MaratGubaiev** [comment]
Done.
See https://github.com/Azure/sonic-buildimage/pull/9429

**Comment by zhangyanzhao** [comment]
#9429  is merged.
