### ISSUE TITLE
[warm-reboot] SERDES objects get removed from ASICDB after warm-reboot from 201811 to 202012 

### ISSUE THREAD

**Issue by tjchadaga** [Azure/sonic-buildimage#9409]
#### Description

SERDES objects are missing from ASIC DB after warm-reboot from 201811 to 202012. The objects are discovered during warm-reboot and added to current view after workaround (https://github.com/Azure/sonic-sairedis/pull/959), but not added to the temporary view generated with new image. This results in a 'remove' operations being triggered and the objects get deleted from ASIC-DB.

#### Steps to reproduce the issue:
1. Warm-reboot from 201811 to 202012 

#### Describe the results you received:
After warm-reboot to 202012, asic-db does not have any SERDES objects
```
redis-dump -d 1 -k "*SERDES*" -y
{}
```
#### Describe the results you expected:
Serdes objects should be present in the asic-db after warmboot (similar to coldboot case as shown below)
```
redis-dump -d 1 -k "*SERDES*" -y | more
{
  "ASIC_STATE:SAI_OBJECT_TYPE_PORT_SERDES:oid:0x5700000000008b": {
    "expireat": 1638309195.648262, 
    "ttl": -0.001, 
    "type": "hash", 
    "value": {
      "NULL": "NULL"
    }
  }, 
  "ASIC_STATE:SAI_OBJECT_TYPE_PORT_SERDES:oid:0x5700000000014a": {
    "expireat": 1638309195.6482592, 
    "ttl": -0.001, 
    "type": "hash", 
    "value": {
      "NULL": "NULL"
    }
  }, 
.
.
```

#### Output of `show version`:

```
SONiC Software Version: SONiC-OS-20201231.44
Distribution: Debian 10.11
Kernel: 4.19.0-12-2-amd64

Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-D108C8
ASIC: broadcom
ASIC Count: 1
Serial Number: SSJ18423396
Uptime: 21:50:42 up 0 min,  1 user,  load average: 1.98, 0.51, 0.17
```
#### Additional information you deem important (e.g. issue happens only occasionally):
```

Nov 12 07:30:36.536598 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_PORT_SERDES on current view 123 is different than on temporary view: 0


Nov 12 07:30:37.028405 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_PORT_SERDES:oid:0x5700000000177f
Nov 12 07:30:37.028405 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_PORT_SERDES:oid:0x57000000001780
Nov 12 07:30:37.028415 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_PORT_SERDES:oid:0x57000000001781
.
.

```

**Comment by kcudnik** [comment]
This fix should keep new discovered objects around: https://github.com/Azure/sonic-sairedis/pull/985
