### ISSUE TITLE
[yang-models] port validation issue, lanes is mandatory

### ISSUE THREAD

**Issue by ganglyu** [Azure/sonic-buildimage#9553]
'PORT': {
		'Ethernet0': {
			'speed': '40000', 
			'description': 'OCPSCH0104012MS:Ethernet12', 
			'mtu': '9100', 
			'tpid': '0x8100', 
			'pfc_asym': 'off', 
			'admin_status': 'up'
		}
	}, 
Config db schema generated by minigraph can’t pass yang validation, PORT table does not have 'lanes' field.
It seems that we need to update yang model or sonic-config-engine.

#### Steps to reproduce the issue:
1. Run command 'sonic-cfggen -m tests/sample_graph.xml --print-data'.
2. Use sonic_yang to validate config db schema.

#### Describe the results you received:
Yang validation failed.

#### Describe the results you expected:
Yang validation should pass.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by qiluo-msft** [comment]
The Step 1 needs `-p` parameter.
I checked below 2 command lines. All the ports have the lanes attribute.

```
$ sonic-cfggen -m tests/simple-sample-graph-case.xml --print-data -p tests/t0-sample-port-config.ini
$ sonic-cfggen -m tests/sample_graph.xml --print-data -p tests/t0-sample-port-config.ini
```

**Comment by qiluo-msft** [comment]
@ganglyu The fixing PR is reverted. Should we reopen this issue? Is it still an issue?
