### ISSUE TITLE
[DPB] DellEMC Z9332f Dynamic port breakout fails in verbose mode

### ISSUE THREAD

**Issue by aravindmani-1** [Azure/sonic-buildimage#9606]
#### Description
In DellEMC Z9332f, breakout mode is working fine if verbose mode is not added.

#### Steps to reproduce the issue:
1. Do config interface breakout EthernetX <breakout_mode> -y -f -v
2. Observe the failure.

#### Describe the results you received:
**Without -v:**
    root@sonic:~# config interface breakout Ethernet0 1x400G -y -f
    
    Running Breakout Mode : 4x100G
    Target Breakout Mode : 1x400G
    
    Ports to be deleted :
    {
    "Ethernet0": "100000",
    "Ethernet2": "100000",
    "Ethernet4": "100000",
    "Ethernet6": "100000"
    }
    Ports to be added :
    {
    "Ethernet0": "400000"
    }

    After running Logic to limit the impact
    
    Final list of ports to be deleted :
    {
    "Ethernet0": "100000",
    "Ethernet2": "100000",
    "Ethernet4": "100000",
    "Ethernet6": "100000"
    }
    Final list of ports to be added :
    {
    "Ethernet0": "400000"
    }
    Note: Below table(s) have no YANG models:
    KDUMP, SNMP, SNMP_COMMUNITY,
    Below Config can not be verified, It may cause harm to the system
    {}
    Do you wish to Continue? [y/N]: y
    Breakout process got successfully completed.
    Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
    root@sonic:~#

**With -v option:**
    root@sonic:~# config interface breakout Ethernet0 1x400G -y -f -v
    
    Running Breakout Mode : 4x100G
    Target Breakout Mode : 1x400G
    
    Ports to be deleted :
    {
    "Ethernet0": "100000",
    "Ethernet2": "100000",
    "Ethernet4": "100000",
    "Ethernet6": "100000"
    }
    Ports to be added :
    {
    "Ethernet0": "400000"
    }
    
    
    
    After running Logic to limit the impact
    
    Final list of ports to be deleted :
    {
    "Ethernet0": "100000",
    "Ethernet2": "100000",
    "Ethernet4": "100000",
    "Ethernet6": "100000"
    }
    Final list of ports to be added :
    {
    "Ethernet0": "400000"
    }
    sonic_yang(3):Yang Models Load failed:[priority,] message string
    Yang Models Load failed
    [priority,] message string
    ConfigMgmt Class creation failed
    Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed
    root@sonic:~#
    
#### Describe the results you expected:
Breakout mode has to work in verbose mode too.

#### Output of `show version`:
root@sonic:~# show ve

SONiC Software Version: SONiC.master.59513-dirty-20211216.193424
Distribution: Debian 11.1
Kernel: 5.10.0-8-2-amd64
Build commit: 734b1bfee
Build date: Thu Dec 16 19:40:34 UTC 2021
Built by: AzDevOps@sonic-build-workers-000ZNL

Platform: x86_64-dellemc_z9332f_d1508-r0
HwSKU: DellEMC-Z9332f-O32
ASIC: broadcom
ASIC Count: 1
Serial Number: 1SQXCW2
Model Number: 0J5HDG
Hardware Revision: A00
Uptime: 16:37:36 up 4 days, 29 min,  1 user,  load average: 0.36, 0.49, 0.59

**Comment by prgeor** [comment]
@zhenggen-xu @praveen-li please help on this DPB issue

**Comment by praveen-li** [comment]
@aravindmani-1 

Are we working on some Dev version of YANG models here. In which yang model below priority field is present?


sonic_yang(3):Yang Models Load failed:[priority,] message string
Yang Models Load failed
[priority,] message string

**Comment by aravindmani-1** [comment]
@praveen-li Issue is seen in latest master image and the error pops up only when we use "-v" option.

**Comment by zhangyanzhao** [comment]
syslog is required.

**Comment by praveen-li** [comment]
@aravindmani-1  Plz share syslog, I will have a look then we can jump on call, today (01/06) or tom eve.

**Comment by aravindmani-1** [comment]
[syslog.txt](https://github.com/Azure/sonic-buildimage/files/7826385/syslog.txt)
@praveen-li Please find the requested syslog.

**Comment by praveen-li** [comment]
Issue is introduced by this PR\Commit.
https://github.com/Azure/sonic-buildimage/commit/4d07bbbec6b4826ae5383c08370cc07578d91dba

We are passing a List for syslog printing, which is not supported
https://github.com/Azure/sonic-buildimage/blame/master/src/sonic-yang-mgmt/sonic_yang_ext.py#L52

```
>>> ls = ['45', '65', '78']
>>> syslog.syslog(syslog.LOG_INFO, ls)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: [priority,] message string
```

Try str(self.yangFiles), it should work. Thanks a lot

Thanks,

Regards
Praveen
________________________________

**Comment by aravindmani-1** [comment]
Thanks Praveen. It does resolves the issue when i used str(self.yangFiles).

**Comment by zhangyanzhao** [comment]
@aravindmani-1  can you please raise a PR with the suggested solution, link it to this issue and close this issue? Thanks.
