### ISSUE TITLE
[yang-models] sonic-scheduler.yang pattern issue

### ISSUE THREAD

**Issue by ganglyu** [Azure/sonic-buildimage#9611]
#### Description

In config_db.json, scheduler name is ‘sheduler.0’ or ‘scheduler.1’, and they can’t match the new pattern, https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-scheduler.yang#L36

#### Steps to reproduce the issue:
1. Run apply-patch command to modify configuration.

#### Describe the results you received:
apply-patch command failed for scheduler pattern.

#### Describe the results you expected:
apply-patch command should work.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ganglyu** [comment]
@AshokDaparthi

**Comment by zhangyanzhao** [comment]
@venkatmahalingam will help to check with Dell team to update scheduler YANG mode to support scheduler.0/.1 value.

**Comment by venkatmahalingam** [comment]
@AshokDaparthi Please take a look at this issue.

**Comment by zhangyanzhao** [comment]
@AshokDaparthi  kindly ping..

**Comment by AshokDaparthi** [comment]
@zhangyanzhao - Raised the pull request https://github.com/Azure/sonic-buildimage/pull/9873

**Comment by ganglyu** [comment]
verified

**Comment by ganglyu** [comment]
verified.
