### ISSUE TITLE
Error in building sonic-vs image

### ISSUE THREAD

**Issue by abhiranjeet** [Azure/sonic-buildimage#9620]
#### Description

Tried building `sonic-vs.img.gz` image

#### Steps to reproduce the issue:
1. `make init`
2. `make configure PLATFORM=broadcom`
3. `make target/sonic-vs.img.gz`

#### Describe the results you received:
```
+ /usr/bin/kvm -m 3072 -name onie -boot order=cd,once=d -cdrom target/files/buster/onie-recovery-x86_64-kvm_x86_64-r0.iso -device e1000,netdev=onienet -netdev user,id=onienet,hostfwd=:0.0.0.0:3041-:22 -vnc 0.0.0.0:0 -vga std -drive file=target/sonic-vs.img,media=disk,if=virtio,index=0 -drive file=./sonic-installer.img,if=virtio,index=1 -serial telnet:127.0.0.1:9000,server
+ '[' -d /proc/11390 ']'
+ echo 'ERROR: kvm died.'
ERROR: kvm died.
+ cat /tmp/tmp.DONcmHp8kV
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory
+ exit 1
+ on_exit
+ rm -f /tmp/tmp.DONcmHp8kV
```

#### Describe the results you expected:
Expected the build to go through successfully

Any suggestions to why this might be happening ?

Thanks in advance !

**Comment by zhangyanzhao** [comment]
Is this issue still there? Can you please double check?

**Comment by abhiranjeet** [comment]
Yes, its working now, I had to enable virtualization on my build machine. Thanks !
