### ISSUE TITLE
[yang-models] missing ACCEPT in sonic-types.yang which used in ACL

### ISSUE THREAD

**Issue by wen587** [Azure/sonic-buildimage#9638]
#### Description
packet_action enumeration missing `ACCEPT`, which is used in ACL control plane.
sonic-acl.yang
```
container sonic-acl {
                container ACL_RULE {
                        description "ACL_RULE part of config_db.json";
                        list ACL_RULE_LIST {
                                leaf PACKET_ACTION {
                                        type stypes:packet_action;
                                }
```
sonic-types.yang
```
typedef packet_action{
        type enumeration {
            enum DROP;
            enum FORWARD;
            enum REDIRECT;
            enum DO_NOT_NAT;
        }
    }

```

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@wen587 can you please raise a PR to make the change for the YANG model and add one test case? Thanks.

**Comment by wen587** [comment]
> @wen587 can you please raise a PR to make the change for the YANG model and add one test case? Thanks.

@zhangyanzhao 
Hi Yanzhao, Not sure how to add that. Could you assign to someone in yang team? I have one testcase from Generic Config Updater may help.

```
admin@vlab-01:~/cacl$ sudo config apply-patch -i /FEATURE -i /QUEUE -i /SCHEDULER addrule.json
Patch Applier: Patch application starting.
Patch Applier: Patch: [{"op": "add", "path": "/ACL_RULE", "value": {"SSH_ONLY|TEST_DROP": {"L4_DST_PORT": "22", "IP_PROTOCOL": "6", "IP_TYPE": "IP", "PACKET_ACTION": "ACCEPT", "PRIORITY": "9998", "SRC_IP": "9.9.9.9/32"}}}]
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating target config does not have empty tables, since they do not show up in ConfigDb.
Patch Applier: Sorting patch updates.
Note: Below table(s) have no YANG models:
BGP_PEER_RANGE, CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, KDUMP, RESTAPI, SNMP, SNMP_COMMUNITY, TELEMETRY,
libyang[0]: Invalid value "ACCEPT" in "PACKET_ACTION" element. (path: /sonic-acl:sonic-acl/ACL_RULE/ACL_RULE_LIST[ACL_TABLE_NAME='SSH_ONLY'][RULE_NAME='TEST_DROP']/PACKET_ACTION)
sonic_yang(3):Data Loading Failed:Invalid value "ACCEPT" in "PACKET_ACTION" element.
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

Error: Given patch is not valid because it will result in an invalid config
```

**Comment by praveen-li** [comment]
@wen587 Can we meet for 15-30 min to discuss this. I can help you to resolve this and raise the PR yourself. This way in future, It will be easy to resolve such issues. Thx. I am in PST timezone, kindly suggest a appropriate time. Thx.

**Comment by wen587** [comment]
@praveen-li  Hi Praveen, I have meeting this Tuesday and Wednesday. Can we schedule at Thursday PST time 5:00PM PST?

**Comment by praveen-li** [comment]
Sure, Thurday 5 PM PST is good.



Thanks,

Regards
Praveen
________________________________

**Comment by praveen-li** [comment]
1.) Add an ACCEPT entry here.
    typedef packet_action{
        type enumeration {
            enum DROP;
            enum ACCEPT;   <<<<<<<<<<
            enum FORWARD;
            enum REDIRECT;
            enum DO_NOT_NAT;
        }
    }


2.)https://datatracker.ietf.org/doc/html/rfc7951  To know JSON to yang encoding.

3.) Add the test case:

3a.) Add a json entry for test in acl.json file [https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/tests/yang_model_tests/tests_config/acl.json]

   "ACL_RULE_PACKET_ACTION_ACCEPT": {
        "sonic-acl:sonic-acl": {
            "sonic-acl:ACL_RULE": {
                "ACL_RULE_LIST": [
                    {
                        "ACL_TABLE_NAME": "NO-NSW-PACL-V6",
                        "DST_IPV6": "2001::2/64",
                        "PACKET_ACTION": "ACCEPT",   <<< We are just testing it.
                        "PRIORITY": 999980,
                        "RULE_NAME": "Rule_20"
                    }
                ]
            },
            "sonic-acl:ACL_TABLE": {
                "ACL_TABLE_LIST": [
                    {
                        "ACL_TABLE_NAME": "NO-NSW-PACL-V6",
                        "policy_desc": "Filter IPv6",
                        "ports": [
                            "Ethernet0",
                        ],
                        "stage": "EGRESS",
                        "type": "L3V6"
                    }
                ]
            }
        },
        "sonic-port:sonic-port": {
            "sonic-port:PORT": {
                "PORT_LIST": [
                    {
                        "admin_status": "up",
                        "alias": "eth0",
                        "description": "Ethernet0",
                        "mtu": 9000,
                        "name": "Ethernet0",
                        "speed": 25000
                    }
                ]
            }
        }
    },

3b.)  in tests/acl.json file add below entry:

https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/tests/yang_model_tests/tests/acl.json

Since our case is validation success, we will add an entry as below:

 "ACL_RULE_PACKET_ACTION_ACCEPT": {
     "desc": 'PACKET_ACTION ACCEPT should be validated and marked as success by Libyang'
}

Test File: https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py
