### ISSUE TITLE
Is there a way to shorten SONiC compile time?

### ISSUE THREAD

**Issue by hubblezzhu** [Azure/sonic-buildimage#9671]
Hi, I am a newcomer who has just come into contact with SONiC, and I am doing some functional verification based on SONiC.
I found that it takes 4~5 hours to compile every time I make some little modifications. 
So is there any way to shorten SONiC compile time?

Any help will be highly appreciated.

**Comment by yxieca** [comment]
@hubblezzhu please try to use CACHE: https://github.com/Azure/sonic-buildimage/blob/master/Makefile.work#L39. It won't help your first build, but subsequent incremental build should be faster. And if you are changing a particular part, you can also only build the immediate target until your dev changes are done.
