### ISSUE TITLE
wget docker-sonic-p4.gz returns 403 forbidden

### ISSUE THREAD

**Issue by richmondstacey** [Azure/sonic-buildimage#9673]
#### Description

The P4 Docker .gz artifact is missing? When trying to wget the "docker-sonic-p4.gz", it returns a 403 forbidden status.

```
wget https://sonic-jenkins.westus2.cloudapp.azure.com/job/p4/job/buildimage-p4-all/543/artifact/target/docker-sonic-p4.gz
```

Even with `--no-check-certificate`.

```
wget --no-check-certificate https://sonic-jenkins.westus2.cloudapp.azure.com/job/p4/job/buildimage-p4-all/543/artifact/target/docker-sonic-p4.gz

--2022-01-04 15:41:08--  https://sonic-jenkins.westus2.cloudapp.azure.com/job/p4/job/buildimage-p4-all/543/artifact/target/docker-sonic-p4.gz
Resolving sonic-jenkins.westus2.cloudapp.azure.com (sonic-jenkins.westus2.cloudapp.azure.com)... 52.250.106.22
Connecting to sonic-jenkins.westus2.cloudapp.azure.com (sonic-jenkins.westus2.cloudapp.azure.com)|52.250.106.22|:443... connected.
WARNING: cannot verify sonic-jenkins.westus2.cloudapp.azure.com's certificate, issued by ‘CN=Microsoft Azure TLS Issuing CA 01,O=Microsoft Corporation,C=US’:
  Issued certificate has expired.
HTTP request sent, awaiting response... 403 Forbidden
2022-01-04 15:41:09 ERROR 403: Forbidden.

```

After looking into the forums, it looks like the artifact location has been moved, but there's nothing listed/available for P4 or PINS. Per this discussion: https://groups.google.com/g/sonicproject/c/nfom0YXay8w

So, the request is 2 fold:
1. Please update the documentation to point to the correct artifact/.gz file or update it to show that this is now invalid/not supported.
2. How do we get access to a P4-Sonic built image/deployment method for Docker? I don't see any listed in the new pipelines, per: https://sonic-build.azurewebsites.net/ui/sonic/pipelines

#### Steps to reproduce the issue:
1. wget --no-check-certificate https://sonic-jenkins.westus2.cloudapp.azure.com/job/p4/job/buildimage-p4-all/543/artifact/target/docker-sonic-p4.gz

#### Describe the results you received:
403 Forbidden - Invalid certificate

#### Describe the results you expected:
The docker-sonic-p4.gz file...

#### Output of `show version`:

/NA

#### Output of `show techsupport`:

/NA

#### Additional information you deem important (e.g. issue happens only occasionally):

I presume this is related to the migration toward PINS instead of just having P4RT with SONiC... but there's not any documentation for us to follow for this here:
https://github.com/Azure/sonic-pins

Thanks!

**Comment by richmondstacey** [comment]
This looks related to https://github.com/Azure/SONiC/issues/906 in the main repo.

**Comment by richmondstacey** [comment]
There isn't a link for P4, however. I assume this is not supported anymore. And if so, the ask in 906 above is to get the wiki/docs updated.

**Comment by mfyuce** [comment]
> There isn't a link for P4, however. I assume this is not supported anymore. And if so, the ask in 906 above is to get the wiki/docs updated.

As indicated [here](https://github.com/Azure/sonic-buildimage/issues/2591#issuecomment-649425081), P4 platform is not supported any more.
