### ISSUE TITLE
[sonic-cfggen] Minigraph parser must generate port lanes and speed

### ISSUE THREAD

**Issue by ganglyu** [Azure/sonic-buildimage#9676]
#### Description

Please refer to https://github.com/Azure/sonic-buildimage/issues/9553
Config db schema generated by minigraph can’t pass yang validation, PORT table does not have 'lanes' field.
We will add a new constraint for minigraph parser: if PORT table does not have 'lanes' field, minigraph parser will raise an exception.
When we invoke sonic-cfggen, must provide '-p' or '-S' for minigraph parser to make sure PORT table has 'lanes' field.
https://github.com/Azure/sonic-buildimage/blob/master/files/image_config/topology/topology.sh#L14
Above line should be updated to use '-p' or '-S' to provide port_config.ini or platform.json, so that new constraint will not block anything.

#### Steps to reproduce the issue:
1. Run command 'sonic-cfggen -m xxx.xml --print-data', and make sure config_db does not proivde lanes.
2. Check command output.

#### Describe the results you received:
sonic-cfggen can generate config db schema, and there's no lanes field in PORT table.

#### Describe the results you expected:
sonic-cfggen should raise an exception.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by qiluo-msft** [comment]
@ganglyu The fixing PR is reverted. Should we reopen this issue? Is it still an issue?
