### ISSUE TITLE
NTP support for management VRF, show information “cgroup change of group failed” when using “cgexec -g l3mdev:mgmt ntpq -p”

### ISSUE THREAD

**Issue by guking3** [Azure/sonic-buildimage#9725]
#### Steps to reproduce the issue:
1. config vrf add mgmt
2. enable ntp 
3. show ntpq -p

#### Describe the results you received:
root@sonic:/var/log#  cgexec -g l3mdev:mgmt ntpq -p
cgroup change of group failed

#### Describe the results you expected:
ntpq -p message

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by bsun-sudo** [comment]
Are you using a Buster image?. If so, could you please try either "ip vrf exec mgmt ntpq -p " or "show ntp" (which checks version and uses either "ip vrf exec mgmt ntpq -p -n" or "cgexec -g l3mdev:mgmt ntpq -p".

**Comment by guking3** [comment]
@bsun-sudo,Thanks for your reply, information as belove: 
root@sonic:~# ip vrf exec mgmt ntpq -p 
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*172.17.0.114 (b                2 u    1   64    1    0.257  -344.69   0.250
root@sonic:~# 
root@sonic:~# ip vrf exec mgmt ntpq -p -n
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*172.17.0.114                    2 u   10   64    1    0.235  -343.70   1.191
root@sonic:~# show ntp
synchronised to NTP server (172.17.9.114) at stratum 3 
   time correct to within 580 ms
   polling server every 64 s
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*172.17.0.114                   2 u   46   64    1    0.235  -343.70   1.191
root@sonic:~# 
root@sonic:~# cgexec -g l3mdev:mgmt ntpq -p
cgroup change of group failed

Sould we use the cgexec -g l3mdev:mgmt to check?
cgexec -g l3mdev:mgmt ntpq -p

**Comment by bsun-sudo** [comment]
@guking3 from the output, seems you are indeed running a SONiC image with Debian buster. "cgcreate -g l3mdev:mgmt" is no longer needed, so "cgexec -g l3mdev:mgmt" doesn't work anymore. Please use "ip vrf exec" instead.
