### ISSUE TITLE
[yang-models] sonic-mirror-session.yang miss policer leaf

### ISSUE THREAD

**Issue by wen587** [Azure/sonic-buildimage#9743]
#### Description
sonic-mirror-session.yang doesn't support policer where it is needed for rate limit

#### Steps to reproduce the issue:
1. Sample mirror session config contains policer.
```
admin@vlab-01:~/everflow$ cat session.json
{
  "MIRROR_SESSION": {
    "mirror_session_dscp": {
    "dscp": "5",
    "dst_ip": "2.2.2.2",
    "policer": "everflow_static_policer",
    "src_ip": "1.1.1.1",
    "ttl": "64",
    "type": "ERSPAN"
    }
  }
}

```
2.
3.

#### Describe the results you expected:
We need to add Yang model for policer first then add the leaf for sonic-mirror-session.yang.

#### Output of `show version`:

```
admin@vlab-01:~/everflow$ show ver

SONiC Software Version: SONiC.master.58770-6402a0226
Distribution: Debian 11.1
Kernel: 5.10.0-8-2-amd64
Build commit: 6402a0226
Build date: Mon Dec 13 09:02:14 UTC 2021
Built by: AzDevOps@sonic-build-workers-000Z9S

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 08:30:18 up  2:47,  2 users,  load average: 0.21, 0.35, 0.27

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by wen587** [comment]
POLICER yang missing should be solved first to fix above issue.
https://github.com/Azure/sonic-buildimage/issues/9742

**Comment by zhangyanzhao** [comment]
@rupesh-k can you please help to take a look? Thanks.
