### ISSUE TITLE
[yang] validating TACPLUS with empty “global” fails, while non-empty “global” does not fail

### ISSUE THREAD

**Issue by wen587** [Azure/sonic-buildimage#9746]
#### Description
yang validation fail when `global` is empty, but it succeeds when nonempty.

_Background of tacacs table._ 
In t0 topo, tacacs has default value while configDB doesn't contain those table.
After sudo config tacacs value, its table will appear in configDB.
Then the table will contains empty value after set back to default.

#### Steps to reproduce the issue:
1. config tacacs and let TACPLUS table appear in configDB
```
admin@vlab-01:~$ show run all | grep -w TACPLUS
admin@vlab-01:~$ sudo config tacacs timeout 3
admin@vlab-01:~$ show run all | grep -w TACPLUS -A3
    "TACPLUS": {
        "global": {
            "timeout": "3"
        }

```
2. Verify by python script. Pass. (Some yang is outdated so we ignore them)
```
admin@vlab-01:~$ cd /usr/local/yang-models/
admin@vlab-01:/usr/local/yang-models$ sudo mkdir ignore
admin@vlab-01:/usr/local/yang-models$ sudo mv sonic-queue.yang sonic-scheduler.yang sonic-feature.yang ignore/
admin@vlab-01:/usr/local/yang-models$ cd -
/home/admin

admin@vlab-01:~$ cat verify_configDB_yang.py
import subprocess
import sonic_yang
import json
def get_config_db_json():
    cmd = "show runningconfiguration all"
    result = subprocess.Popen(cmd, shell=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    text, err = result.communicate()
    return json.loads(text)
configDbJson = get_config_db_json()
sy = sonic_yang.SonicYang("/usr/local/yang-models")
sy.loadYangModel()
sy.loadData(configDbJson )
sy.validate_data_tree()
admin@vlab-01:~$

admin@vlab-01:~$ python verify_configDB_yang.py
Note: Below table(s) have no YANG models:
BGP_PEER_RANGE, CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, FEATURE, KDUMP, QUEUE, RESTAPI, SCHEDULER, SNMP, SNMP_COMMUNITY, TELEMETRY,
admin@vlab-01:~$
```
3. set tacacs back to default and run python script again. It fails.
```
admin@vlab-01:~$ sudo config tacacs default timeout
admin@vlab-01:~$ show run all | grep -w TACPLUS -A3
    "TACPLUS": {
        "global": {}
    },
    "TACPLUS_SERVER": {
admin@vlab-01:~$ python verify_configDB_yang.py
Note: Below table(s) have no YANG models:
BGP_PEER_RANGE, CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, FEATURE, KDUMP, QUEUE, RESTAPI, SCHEDULER, SNMP, SNMP_COMMUNITY, TELEMETRY,
sonic_yang(3):All Keys are not parsed in TACPLUS
dict_keys(['global'])
sonic_yang(3):exceptionList:[]
sonic_yang(3):Data Loading Failed:All Keys are not parsed in TACPLUS
dict_keys(['global'])
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 1062, in loadData
    self._xlateConfigDB(xlateFile=xlateFile)
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 695, in _xlateConfigDB
    self._xlateConfigDBtoYang(jIn, yangJ)
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 682, in _xlateConfigDBtoYang
    self._xlateContainer(cmap['container'], yangJ[key][subkey], \
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 662, in _xlateContainer
    raise(Exception("All Keys are not parsed in {}\n{}".format(table, \
Exception: All Keys are not parsed in TACPLUS
dict_keys(['global'])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/verify_configDB_yang.py", line 12, in <module>
    sy.loadData(configDbJson )
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 1072, in loadData
    raise SonicYangException("Data Loading Failed\n{}".format(str(e)))
sonic_yang_ext.SonicYangException: Data Loading Failed
All Keys are not parsed in TACPLUS
dict_keys(['global'])

```
#### Describe the results you received:
See above.

#### Describe the results you expected:
Action should succeed because it should be valid configDB.

#### Output of `show version`:

```
admin@vlab-01:~/tacacs$ show ver

SONiC Software Version: SONiC.master.58770-6402a0226
Distribution: Debian 11.1
Kernel: 5.10.0-8-2-amd64
Build commit: 6402a0226
Build date: Mon Dec 13 09:02:14 UTC 2021
Built by: AzDevOps@sonic-build-workers-000Z9S

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 09:54:13 up  4:11,  2 users,  load average: 0.14, 0.14, 0.15

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@ArthiSivanantham can you please help to take a look at this issue? Venkat will follow-up with you. Thanks.

**Comment by zhangyanzhao** [comment]
Dell team is working on this.

**Comment by venkatmahalingam** [comment]
We'll update our findings today.

**Comment by ArthiSivanantham** [comment]
For config validation, in sonic_yang_ext.py "_xlateContainer()" method, translates a dictionary in config DB to a Yang JSON container using yang model. A copy of config keys are deleted after every match. When all the keys are being processed, an empty dictionary was expected,

https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-mgmt/sonic_yang_ext.py#L654

**Working case:**

admin@testsonic5:~$ sudo config tacacs timeout 3

configC:  {'global': {'timeout': '3'}}
model:  OrderedDict([('@name', 'global'), ('leaf', OrderedDict([('@name', 'timeout'), ('type', OrderedDict([('@name', 'uint16'), ('range', OrderedDict([('@value', '1..60'), ('error-message', OrderedDict([('value', 'TACACS timeout must be 1..60')]))]))])), ('default', OrderedDict([('@value', '5')]))]))])


configC.keys was empty after processing the dict at the above mentioned point. (#654)

**Non-working case:**

There is an early return when processing a container inside a container case ( "_xlateContainerInContainer()" method in sonic_yang_ext.py).  If the config has an empty dict as a value, it's key is not being cleaned up and returned from that function,

https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-mgmt/sonic_yang_ext.py#L597


admin@testsonic5:~$ sudo config tacacs default timeout

configC:  {'global': {}}
model:  OrderedDict([('@name', 'global'), ('leaf', OrderedDict([('@name', 'timeout'), ('type', OrderedDict([('@name', 'uint16'), ('range', OrderedDict([('@value', '1..60'), ('error-message', OrderedDict([('value', 'TACACS timeout must be 1..60')]))]))])), ('default', OrderedDict([('@value', '5')]))]))])


configC : {'global': {}} was not empty and the validation failed as,

Exception: All Keys are not parsed in TACPLUS
dict_keys(['global'])

https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-mgmt/sonic_yang_ext.py#L659

Requesting the script owner @praveen-li  to re-visit the logic of clearing dictionary keys (for empty value).

**Comment by wen587** [comment]
any update for this one?

**Comment by wen587** [comment]
Is there an ETA for this one?

**Comment by qiluo-msft** [comment]
@praveen-li Could you help check "re-visit the logic of clearing dictionary keys (for empty value)"?

**Comment by praveen-li** [comment]
Let me check it once tomorrow.

Thanks,

Regards
Praveen
________________________________

**Comment by praveen-li** [comment]
Which yang model is in picture here, Kindly send me the link.
Here global is container and Timeout is leaf right ?



Thanks,

Regards
Praveen
________________________________

**Comment by wen587** [comment]
sonic-system-tacacs.yang
Right, global is container and timeout is leaf.

**Comment by praveen-li** [comment]
Kindly add below, it should fix this issue. Let me know if not. Thx.
    
if not configC.get(ccontainer['@name']):
+       # Empty container, clean config and return
+      del configC[ccontainer['@name']]
        return

**Comment by wen587** [comment]
Hi @praveen-li , Could you elaberate where to add those lines?
