### ISSUE TITLE
When using command "reboot -f", fancontrol service will start failed in platform monitor docker.

### ISSUE THREAD

**Issue by wadelnn** [Azure/sonic-buildimage#975]
**Description**

When using command "reboot -f", fancontrol service will start failed in platform monitor docker.

**Steps to reproduce the issue:**
1. check fancontrol status (status in running)
   root@sonic:/# docker exec -it pmon service fancontrol status
2. force reboot
    root@sonic:/# reboot -f
3. check fancontrol status again (status failed)
    root@sonic:/# docker exec -it pmon service fancontrol status

**Describe the results you received:**
fancontrol status will be failed. Need to restart fancontrol service.

**Describe the results you expected:**
fancontrol status should still in running state.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `show version`:**

    ```
    root@sonic:/home/admin# show version
    SONiC Software Version: 201709.01
    Distribution: Debian 8.9
    Kernel: 3.16.0-4-amd64
    Build commit: 48fd6fb
    Build date: Wed Sep 20 08:35:00 UTC 2017
    Built by: wadelnn@sonic

    Docker images:
    REPOSITORY TAG IMAGE ID SIZE
    docker-syncd-brcm latest 8376adf32a72 318.4 MB
    docker-orchagent-brcm latest daf63e4b4ce9 258.4 MB
    docker-lldp-sv2 latest 9221ad7a1769 256.5 MB
    docker-dhcp-relay latest c2bde5d68369 253.5 MB
    docker-database latest b75f64ffd3f6 251.7 MB
    docker-snmp-sv2 latest 74fd7c82e8de 291.3 MB
    docker-teamd latest a0277c3a87fb 255.4 MB
    docker-platform-monitor latest 8b964742f161 271 MB
    docker-fpm-quagga latest f177ce9a9578 262 MB
    ```

**Comment by wadelnn** [comment]
The root cause is as follows.
When fancontrol service started, the fancontrol process will check the /var/run/fancontrol.pid is exist or not.
If fancontrol.pid exist, the service will exit to avoid duplicate process.
/var/run is tmpfs on host side. Files under this directory must be cleared (removed or truncated as appropriate) at the beginning of the boot process.
But in docker, /var/run is mount in root-aufs. It will not clear /var/run at the beginning in the platform-monitor docker.

**Comment by stcheng** [comment]
I wonder if for each docker, we clean the `/var/run` folder intentionally during docker start up time.
Previously, we're facing the rsyslog pid issue in the same manner.
