### ISSUE TITLE
broadcom-dnx: warning message, "image you're trying to install is of a different ASIC type"

### ISSUE THREAD

**Issue by jon-nokia** [Azure/sonic-buildimage#9759]
#### Description
Warning message during sonic-installer or onie-nos-install, “The image you're trying to install is of a different ASIC type as the running platform's ASIC.  Do you still wish to install this image? [y/n]” 

Root Cause:
Recall when building an image with PLATFORM=broadcom, two images are built
 - sonic-broadcom.bin
 - sonic-broadcom-dnx.bin

device/**/platform_asic files indicate which ASIC are supported

The DNX build continues to use PLATFORM=broadcom, however the device/**/platform_asic files advertise “broadcom-dnx” for those devices that support DNX (instead of XGS).  This confuses the build_image.sh:generate_device_list() function and prevents it from generating the list of supported platforms for the configured build,  instead, installer/$TARGET_PLATFORM/platforms_asic lists only XGS platforms and the subsequent grep, which uses "-x, --line-regexp" option will not match those platform_asic files that contain "broadcom-dnx"

Not sure if we should remove grep "-x" option or solve in some other manner.

#### Steps to reproduce the issue:
1. Build image for PLATFORM=broadcom
2. Attempt to install the sonic-broadcom-dnx.bin
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
@qiluo-msft, as a fix to this issue, can we use the $TARGET_MACHINE instead of $CONFIGURED_PLATFORM ? https://github.com/Azure/sonic-buildimage/blob/ca36b4a57b1e0c027d32527894163e60716aa5dd/build_image.sh#L100

**Comment by qiluo-msft** [comment]
@wen587 Could you please check this issue?

**Comment by wen587** [comment]
@jon-nokia Hi could you please share your `show version`

**Comment by wen587** [comment]
@jon-nokia  Hi, could you try recent build see if it is resolved?

**Comment by jon-nokia** [comment]
@wen587 Yes, we already cherry-picked - works great! Thanks.
