### ISSUE TITLE
linux_ngknet insmod issue of saibcm-modules

### ISSUE THREAD

**Issue by dereksun01** [Azure/sonic-buildimage#9845]
#### Description

@saiarcot895  or Someone, I use lastly saibcm-modules kernel module and find a issue of linux_ngknet.ko can not be install and show message: 
"insmod: ERROR: could not insert module linux_ngknet.ko: Device or resource busy"

Following my information:

root@as7326-56x:/lib/modules/5.10.0-8-2-amd64/extra# lsmod |grep linux
linux_ngbde            57344  0
linux_knet_cb          24576  0
psample                  20480  1 linux_knet_cb
linux_bcm_knet       90112  1 linux_knet_cb
linux_user_bde        28672  0
linux_kernel_bde     65536  2 linux_bcm_knet,linux_user_bde
root@as7326-56x:/lib/modules/5.10.0-8-2-amd64/extra#

Thanks,

#### Steps to reproduce the issue:
1. git clone saibcm-modules of SONiC source.
2. Building saibcm-modules source and copy *.ko into SONiC.
3. Reboot system.

#### Output of `show version`:

```
root@as7326-56x:/lib/modules/5.10.0-8-2-amd64/extra# show version

SONiC Software Version: SONiC.master.0-dirty-20220124.015826
Distribution: Debian 11.2
Kernel: 5.10.0-8-2-amd64
Build commit: c80dabd0d
Build date: Mon Jan 24 02:03:55 UTC 2022
Built by: ubuntu@ip-10-5-1-132

Platform: x86_64-accton_as7326_56x-r0
HwSKU: Accton-AS7326-56X
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 00:57:11 up 22:01,  1 user,  load average: 0.36, 0.22, 0.19
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saiarcot895** [comment]
Is there anything in the dmesg log or `journalctl -ke`?

**Comment by dereksun01** [comment]
Dear Saiarcot895,

It's great to got your reply. Now, for our platform, we found error following message:

DMA pool size: 33554432
BDE dev 0 (PCI), Dev 0xb873, Rev 0x01, Chip BCM56873_A0, Driver BCM56870_A0
SOC unit 0 attached to PCI device BCM56873_A0
rc: unit 0 device BCM56873_A0
0:soc_trident3_chip_reset: TS_PLL locked on unit 0 using 50.0MHz external reference clock
Recommended to add "ptp_ts_pll_fref=50000000" config variable
0:soc_trident3_chip_reset: BS_PLL0 locked on unit 0 using 50.0MHz external reference clock
Recommended to add "ptp_bs_fref_0=50000000" config variable
0:soc_trident3_chip_reset: BS_PLL1 locked on unit 0 using 50.0MHz external reference clock
Recommended to add "ptp_bs_fref_1=50000000" config variable
<nounit>:soc_knet_check_version: **KNET check version fail** rv -1 version 13 netif_max 128 filter_max 128
0:soc_knet_init: knet version check failed rv -1
<nounit>:soc_knet_cleanup: KNET Rx thread did not exit after 5 seconds [state = 2]
0:soc_dma_attach: Failed to initialize KNET: rv=-11
recv /dev/linux-bcm-knet: : Bad file descriptor
<nounit>:soc_knet_rx_thread: KNET RX RECV error - thread aborting [state = -1]


dmesg:
[  264.283028] linux-kernel-bde (12501): _interrupt_disconnect d 0
[  264.283032] linux-kernel-bde (12501): _interrupt_disconnect: isr_active = 1
[  264.283034] linux-kernel-bde (12501): disconnect primary isr
[  264.283052] linux-kernel-bde (12501): _interrupt_connect d 0
[  264.283054] linux-kernel-bde (12501): _interrupt_connect:isr_active = 0
[  264.283055] linux-kernel-bde (12501): connect primary isr
[  264.283071] linux-kernel-bde (12501): _interrupt_connect(3783):device# = 0, irq_flags = 128, irq = 32

Do you know why does SDK of SONiC community check KNET of community version fail?

Thank your help.  :)

**Comment by dereksun01** [comment]
Dear Saiarcot895,

Thank your kindly feedback and we found the issue is about wrong CANCUN files on SONiC community image.
