### ISSUE TITLE
Incorrect status of mirror session in everflow test

### ISSUE THREAD

**Issue by okanchou9** [Azure/sonic-buildimage#987]
**Description**

Ran everflow test and failed at logic test. Found the status of mirror session is still active after session route is removed.

**Steps to reproduce the issue:**
1. Run everflow logic_test.yml

**Describe the results you received:**

Test is failed when script is checking the status of mirror session after session route is removed.
Please refer the attachment for the test log.
[everflow_logic.txt](https://github.com/Azure/sonic-buildimage/files/1332020/everflow_logic.txt)

**Describe the results you expected:**

Pass this test.

**Comment by okanchou9** [comment]
Hi,

Would like to know any update for this issue?

---
Regards,
Kenie Liu

**Comment by stcheng** [comment]
On the latest image, the everflow test passes. Could you try the latest image with the latest test?

**Comment by lguohan** [comment]
no response over 3 months, assuming no more questions from originator.
