### ISSUE TITLE
SONiC master with Broadcom CANCUN version issue

### ISSUE THREAD

**Issue by dereksun01** [Azure/sonic-buildimage#9878]
#### Description

Dear judyjoseph or Someone,

We find lastly SONiC image has CANCUN version issue on our platform.
That will be caused SDK initialization fail and syncd stop.

#### Steps to reproduce the issue:
1. Upgrade SONiC image file (49a036e9) on Accton as7326_56x.
2.
3.

#### Describe the results you expected:
- Broadcom upgrade bcm56870_a0 CANCUN files for SDK-6.5.24 on SAI package.

#### Output of `show version`:

```
root@as7326-56x:~# show ver

SONiC Software Version: SONiC.master.67679-49a036e90
Distribution: Debian 11.2
Kernel: 5.10.0-8-2-amd64
Build commit: 49a036e90
Build date: Tue Jan 25 18:17:00 UTC 2022
Built by: AzDevOps@sonic-build-workers-0013WI

Platform: x86_64-accton_as7326_56x-r0
HwSKU: Accton-AS7326-56X
ASIC: broadcom
ASIC Count: 1
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by dereksun01** [comment]
Dear @judyjoseph or Someone,

Could you confirm this issue for CANCUN files(bcm56870_a0) for SDK-6.5.24 on SAI package?
Thank your kindly help.

**Comment by gechiang** [comment]
New BRCM HSDK Cancun files moved to different location causing this issue.
Case raised and was informed where to find it.
A PR will be raised to address this issue shortly...

**Comment by dereksun01** [comment]
Dear @gechiang,

I have confirmed this PR and it's works fine on as7326_56x. I will close this issue and thank your kindly help.
@judyjoseph , thank your help.

:)
