### ISSUE TITLE
what if i only want to run this on my Home Lab VM

### ISSUE THREAD

**Issue by toggit** [Azure/sonic-buildimage#9893]
Hello guys,

in docs i can see in a list of supported platform its look like its only for hardware platforms or maybe i get it wrong.
but what if i only want to run this on my Home Lab.
does this project support a build for Virtual Machine?  or maybe docker-compose ?

i want to do test for:
 L2 vlan /trunk / lacp
 L3  static and dynamic routing / vxlan / vrf / svi.

**Comment by bluecmd** [comment]
This is what the sonic-vs (Virtual Switch) is for! :-).
You can run it in e.g. QEMU or GNS3 - and likely many more.

**Comment by akokhan** [comment]
You may find useful the following blog:
https://plvision.eu/rd-lab/blog/sdn/sonic-network-os-configuration

**Comment by toggit** [comment]
ok this is good information.
case close
