### ISSUE TITLE
Get port alias but not port name in snmp_interface test

### ISSUE THREAD

**Issue by okanchou9** [Azure/sonic-buildimage#990]
**Description**
Expect get port name but get port alias in snmp_interface test

**Steps to reproduce the issue:**
1. Run snmp_interface test

**Describe the results you received:**
"snmp_intf": [
        "Ethernet20/1", 
        "Ethernet16/1", 
        "Ethernet30/1", 
        "Ethernet23/1", 
        "Ethernet19/1", 
        "Ethernet17/1", 
        "Ethernet29/1", 
        "Ethernet18/1", 
        "Ethernet24/1", 
        "Ethernet21/1", 
        "Ethernet14/1", 
        "Ethernet32/1", 
        "Ethernet22/1", 
        "Ethernet7/1", 
        "Ethernet4/1", 
        "Ethernet26/1", 
        "Ethernet6/1", 
        "Ethernet13/1", 
        "Ethernet9/1", 
        "Ethernet15/1", 
        "Ethernet12/1", 
        "Ethernet10/1", 
        "Ethernet8/1", 
        "Ethernet31/1", 
        "Ethernet11/1", 
        "Ethernet1/1", 
        "Ethernet28/1", 
        "Ethernet2/1", 
        "Ethernet25/1", 
        "Ethernet3/1", 
        "Ethernet27/1", 
        "Ethernet5/1", 
    ]

**Describe the results you expected:**
"minigraph_map_sonic_to_ngs": {
        "Ethernet0": "Ethernet0", 
        "Ethernet100": "Ethernet100", 
        "Ethernet104": "Ethernet104", 
        "Ethernet108": "Ethernet108", 
        "Ethernet112": "Ethernet112", 
        "Ethernet116": "Ethernet116", 
        "Ethernet12": "Ethernet12", 
        "Ethernet120": "Ethernet120", 
        "Ethernet124": "Ethernet124", 
        "Ethernet16": "Ethernet16", 
        "Ethernet20": "Ethernet20", 
        "Ethernet24": "Ethernet24", 
        "Ethernet28": "Ethernet28", 
        "Ethernet32": "Ethernet32", 
        "Ethernet36": "Ethernet36", 
        "Ethernet4": "Ethernet4", 
        "Ethernet40": "Ethernet40", 
        "Ethernet44": "Ethernet44", 
        "Ethernet48": "Ethernet48", 
        "Ethernet52": "Ethernet52", 
        "Ethernet56": "Ethernet56", 
        "Ethernet60": "Ethernet60", 
        "Ethernet64": "Ethernet64", 
        "Ethernet68": "Ethernet68", 
        "Ethernet72": "Ethernet72", 
        "Ethernet76": "Ethernet76", 
        "Ethernet8": "Ethernet8", 
        "Ethernet80": "Ethernet80", 
        "Ethernet84": "Ethernet84", 
        "Ethernet88": "Ethernet88", 
        "Ethernet92": "Ethernet92", 
        "Ethernet96": "Ethernet96"
    }

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm using version 201709 in my box to run the test, not sure this is expected result at this version or not since I can pass this test at version 201705.
Any comment are welcome, thanks.

---
Regards,
Kenie Liu

**Comment by stcheng** [comment]
@qiluo-msft do we expect the alias or the interface name in the snmp test?

**Comment by qiluo-msft** [comment]
I think alias.

**Comment by stcheng** [comment]
then the snmp behavior is correct, it is the test issue that fails this task.

**Comment by okanchou9** [comment]
Hi all,

Thank you for the info for this behavior.
Also just found that lldp had the same behavior:

ARISTA01T1#sh lldp neighbors 
Last table change time   : 4:07:16 ago
Number of table inserts  : 1
Number of table deletes  : 0
Number of table drops    : 0
Number of table age-outs : 0

Port       Neighbor Device ID               Neighbor Port ID           TTL
Et1        switch2                          Ethernet29/1               120
ARISTA01T1#

Is that also expected, too?

---
Regards,
Kenie Liu

**Comment by taoyl-ms** [comment]
Yes. alias is also expected in lldp test.

**Comment by okanchou9** [comment]
Thank you guys.
