### ISSUE TITLE
Portconfig.ini parser in different applications are expecting different schema

### ISSUE THREAD

**Issue by taoyl-ms** [Azure/sonic-buildimage#992]
Currently multiple applications are parsing portconfig.ini independently, and each of them are expecting a different schema. For example, some of them support port speed and/or port index fields while some do not.

We'll need unify the schema for that file and create a single parse to read from that file.

**Comment by jleveque** [comment]
We also need to enforce a consistent name for the port index column. Some files call it `index` (e.g., https://github.com/Azure/sonic-buildimage/blob/master/device/dell/x86_64-dell_s6100_c2538-r0/Force10-S6100/port_config.ini), while others call it `port` (e.g., https://github.com/Azure/sonic-buildimage/blob/master/device/arista/x86_64-arista_7260cx3_64/Arista-7260CX3-C64/port_config.ini).

**Comment by jleveque** [comment]
Consistent naming convention for columns addressed here: https://github.com/Azure/sonic-buildimage/pull/1001. Still need to create a single parser library per language.

**Comment by jleveque** [comment]
Related to https://github.com/Azure/sonic-buildimage/issues/496

**Comment by jleveque** [comment]
Resolved with https://github.com/Azure/sonic-buildimage/pull/1072
