### ISSUE TITLE
[yang] missing MIRROR_INGRESS_ACTION and MIRROR_EGRESS_ACTION in sonic-acl.yang

### ISSUE THREAD

**Issue by wen587** [Azure/sonic-buildimage#9929]
#### Description
missing MIRROR_INGRESS_ACTION and MIRROR_EGRESS_ACTION in sonic-acl.yang
which is used for EverflowAlwaysOn in Generic Config Updater E2E test.

#### Steps to reproduce the issue:
1. 
```
admin@vlab-01:~/everflow$ sudo config acl add table EVERFLOW_DSCP MIRROR_DSCP

admin@vlab-01:~/everflow$ sudo config apply-patch -i /FEATURE -i /QUEUE -i /SCHEDULER add_rule.json
Patch Applier: Patch application starting.
Patch Applier: Patch: [{"op": "add", "path": "/ACL_RULE", "value": {"EVERFLOW_DSCP|RULE_1": {"DSCP": "5", "MIRROR_INGRESS_ACTION": "mirror_session_dscp", "PRIORITY": "9999"}}}]
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating target config does not have empty tables, since they do not show up in ConfigDb.
Patch Applier: Sorting patch updates.
Note: Below table(s) have no YANG models:
BGP_PEER_RANGE, CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, KDUMP, RESTAPI, SNMP, SNMP_COMMUNITY, TELEMETRY,
sonic_yang(3):All Keys are not parsed in ACL_RULE
dict_keys(['EVERFLOW_DSCP|RULE_1'])
sonic_yang(3):exceptionList:["'MIRROR_INGRESS_ACTION'"]   <=====================
sonic_yang(3):Data Loading Failed:All Keys are not parsed in ACL_RULE
dict_keys(['EVERFLOW_DSCP|RULE_1'])
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

Error: Given patch is not valid because it will result in an invalid config
```
2.
3.

#### Describe the results you received:
See above

#### Describe the results you expected:
no error expected

#### Output of `show version`:

```
admin@vlab-01:~/everflow$ show ver

SONiC Software Version: SONiC.master.59050-dirty-20211214.171137
Distribution: Debian 11.1
Kernel: 5.10.0-8-2-amd64
Build commit: 2a467f8eb
Build date: Tue Dec 14 17:18:24 UTC 2021
Built by: AzDevOps@sonic-build-workers-000ZFY

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 08:31:10 up 23:11,  1 user,  load average: 0.44, 0.52, 0.59

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by qiluo-msft** [comment]
@stepanblyschak Could you help check the issue?

In yang model, the ACL_TABLE_TYPE/actions is a string as [link](https://github.com/Azure/sonic-buildimage/blob/09b0cc2ccef41bf0fbb0fa4d42bca28f37e13f59/src/sonic-yang-models/yang-templates/sonic-acl.yang.j2#L270)

However, in swss schema ACL_TABLE_TYPE_ACTIONS value is a list of strings as [link](https://github.com/Azure/sonic-swss/blob/d9e72a9677b896058021913d412dad83503d79b6/doc/Configuration.md#acl-and-mirroring)

**Comment by zhangyanzhao** [comment]
@wen587 please schedule a meeting with @praveen-li  to understand more detail.

**Comment by stepanblyschak** [comment]
Hi @qiluo-msft , in yang model ACL_TABLE_TYPE/actions is a leaf-list of strings [here](https://github.com/Azure/sonic-buildimage/blob/09b0cc2ccef41bf0fbb0fa4d42bca28f37e13f59/src/sonic-yang-models/yang-templates/sonic-acl.yang.j2#L269).

But how it is related to this issue? This issue is due to ACL_RULE yang container not having all actions that are supported by orchagent including:
- ACTION_REDIRECT_ACTION
- ACTION_DO_NOT_NAT_ACTION
- ACTION_MIRROR_INGRESS_ACTION
- ACTION_MIRROR_EGRESS_ACTION
- ACTION_DTEL_FLOW_OP
- ACTION_DTEL_INT_SESSION
- ACTION_DTEL_DROP_REPORT_ENABLE
- ACTION_DTEL_TAIL_DROP_REPORT_ENABLE
- ACTION_DTEL_FLOW_SAMPLE_PERCENT
- ACTION_DTEL_REPORT_ALL_PACKETS

**Comment by qiluo-msft** [comment]
Agree with @stepanblyschak
