### ISSUE TITLE
Configuring default Vlan 1 can cause swss crash

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-buildimage#9946]
#### Description

If user configures Vlan 1, as `config vlan add 1`, orchagent is crashing. This is because Vlan 1 is already configured during orchagent initialization and a user configuration results in SAI returning INVALID value or ALREADY EXISTS error, causing orchagent to crash. 

#### Steps to reproduce the issue:
1. config vlan add 1
2.
3.

#### Describe the results you received:
orchagent crash

#### Describe the results you expected:
CLI should throw an error specifying the user that Vlan 1 is default vlan. Orchagent should not crash. 

#### Output of `show version`:

```
Happens on all branches 202012, 202111, master etc
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by MaratGubaiev** [comment]
I am working on it.
Now I just need to check the fix.

**Comment by prsunny** [comment]
Fixed PR merged
